### ISSUE TITLE
Context, request unavailable in profile_menu

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1001]
### Context
in Profile menu need to add option with param (customer/:id/edit - for example). I tried to call `request` and `context` variable in `avo.rb` file in profile_menu block for build link. But variables unavailable. How can i add parameterized link or call request (context) variable (for build link) in profile menu?

### System configuration
**Avo version**: 2.9

**Rails version**: 7.0.1

**Ruby version**: 3.1.2

**License type** (Community or Pro): Community

### Screenshots

<img width="524" alt="Screenshot 2022-06-28 at 15 56 01" src="https://user-images.githubusercontent.com/27281496/176183815-5be357e9-8574-434e-9d57-429eb0faa0cb.png">

**Comment by adrianthedev** [comment]
Can you please share how the `current_customer` is defined in the `context` object?

**Comment by Sweex99** [comment]
@adrianthedev 

<img width="385" alt="Screenshot 2022-06-28 at 22 10 06" src="https://user-images.githubusercontent.com/27281496/176264645-ea949145-d555-4b47-9ae9-f439f371f677.png">

**Comment by adrianthedev** [comment]
Can you try `params[:slug]` instead of `req.params[:slug]`?

**Comment by adrianthedev** [comment]
Does `params[:slug]` evaluate properly? Does it give proper string? Also, does the `Customer.find_by_slug` trigger a query in the DB? Can you see it in the logs?

**Comment by Sweex99** [comment]
> Can you try `params[:slug]` instead of `req.params[:slug]`?

did not work

**Comment by Sweex99** [comment]
> 


> Does `params[:slug]` evaluate properly? Does it give proper string? Also, does the `Customer.find_by_slug` trigger a query in the DB? Can you see it in the logs?

in logs, query for find customer is exist

**Comment by adrianthedev** [comment]
So what does `puts params[:slug]` output? And can you give me an example of a path where it doesn't work? @Sweex99

**Comment by Sweex99** [comment]
this is path to custom controller (customer#edit)  - localhost:3000/customers/:id/edit

<img width="482" alt="Screenshot 2022-06-29 at 14 23 41" src="https://user-images.githubusercontent.com/27281496/176425503-32d5a2a6-f6de-4eb4-9fc5-35dfe18ed7aa.png">

**Comment by adrianthedev** [comment]
I meant, where is it that it doesn't work?

TBH, I don't know how that can really work on regular Avo pages.

To give you an example, let's say you are on the page of User with an id of 1. So `/avo/resources/users/1`. There's no `slug` param there (no `params[:slug]`).

I think you should build the path using that `current_user` object in context. Here's an example below.

```ruby
config.set_context do
  {
    current_user: current_user,
    current_customer: Customer.find_by(user_id: current_user.id) # or something similar
  }
end

config.profile_menu = -> {
  link "Profile", path: "/customer/#{context[:current_customer].id}", icon: "user-circle"
}
```

**Comment by adrianthedev** [comment]
Ok. I prepared a PR to merge in the next release.

Can you please try [2.9.1.pre5](https://rubygems.org/gems/avo/versions/2.9.1.pre5) and let me know if you have all the variables you need?

**Comment by Sweex99** [comment]
amazing!
