### ISSUE TITLE
authorize_action doesn’t work with has_many through associations and policies

### ISSUE THREAD

**Issue by mid** [avo-hq/avo#1005]
### Steps to Reproduce
1. Create a `User` model, resource & policy
2. Create a `Role` model, resource & policy
3. Create a `UserRole` model
4. Add `has_many :roles, through: :user_roles` to `User`
5. Add `attach_roles?` and `detach_roles?` to `UserPolicy` (both evaluating to true)
6. Add `create?` to `UserPolicy` (evaluating to false)
7. Try to attach or detach a role to a user - `Avo::Services::AuthorizationService#authorize_action` stops the action

However, if authorization is disabled, or both `UserPolicy#create?` and `UserPolicy#destroy?` evaluates to true, then attach/detach functionality works as expected. But that's not the expected behavior.

Adding the example ruby classes:

```ruby
class User < ApplicationRecord
  has_many :user_roles
  has_many :roles, through: :user_roles
end
```

```ruby
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
end
```

```ruby
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end
```

```ruby
class RolePolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end

  def index?
    true
  end

  def show?
    true
  end

  def create?
    true
  end

  def update?
    true
  end
end
```

```ruby
class UserPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end

  def index?
    true
  end

  def show?
    true
  end

  # def create?
  #   true
  # end

  # def destroy?
  #   true
  # end

  def attach_roles?
    true
  end

  def detach_roles?
    true
  end

  def view_roles?
    false
  end

  def edit_roles?
    false
  end

  def create_roles?
    false
  end

  def destroy_roles?
    false
  end
end
```

```ruby
class UserResource < Avo::BaseResource
  self.title = :email
  self.includes = []

  field :id, as: :id
  field :email, as: :text, readonly: true
  field :roles, as: :has_many, through: :user_roles
end
```

```ruby
class RoleResource < Avo::BaseResource
  self.title = :name
  self.includes = []

  field :id, as: :id
  field :name, as: :text, required: true
  field :identifier, as: :text, required: true
end
```

### System configuration
**Avo version**:
2.9.0

**Rails version**:
7.0.3

**Ruby version**:
3.1.2

**License type** (Community or Pro):
Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by mid** [comment]
Not working (with authorization):
![Not working](https://m.machine.lt/screencast_2022-06-30-vhnxx.gif)

Working (without any authorization):
![Working](https://m.machine.lt/screencast_2022-06-30-zfayk.gif)

**Comment by adrianthedev** [comment]
Ok. Cool! Let me check it out. 

I've got my hands full for the next few days and I'll get on it after I release https://github.com/avo-hq/avo/pull/1003, https://github.com/avo-hq/avo/pull/916, https://github.com/avo-hq/avo/pull/985, and https://github.com/avo-hq/avo/pull/995.

The repo is available if you have the time to have a look. Maybe it's not that difficult to fix.

**Comment by pmackay** [comment]
I think I'm finding a similar problem. Would be interested if there is an identified issue on this.

**Comment by adrianthedev** [comment]
Hey @mid, I see the bug. I'll have it fixed in the next release. Thank you for writing!
