### ISSUE TITLE
Pre-release 2.9.1.pre6 seems to break ImportMaps

### ISSUE THREAD

**Issue by db0sch** [avo-hq/avo#1011]
### Describe the bug
I've been using Avo version 2.9.0 perfectly, alongside my app using ImportMaps (rails 7 default setup), without any issue.
In order to use the `force_locale` feature introduced in 2.9.1.pre4, I've bumped the gem.
But somehow, this broke import map somehow, and the app (NOT avo) does not have any Javascript anymore.

I really have no idea why. I've been looking into this for hours today. Trying to compare the commits to spot which part of the code between 2.9.0 and the 2.9.1 pre-release might cause this, with no success.

The only thing I can notice is this message in my web console:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://v4-dev.127.0.0.1.nip.io:3000/assets/es-module-shims.min-b8099fffdbd758070d4801321d43b389c5b6174a50782f9f4cb57061533b7ac2.js
Source Map URL: /assets/es-module-shims.js-0717ab7a61a0e786cbf5807f2809472f83677b98e564a184d7f4281a4e4abce8.map
```

and this message in my logs:
```
2022-07-04 18:08:11 +0200 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
```

This has driving me crazy, so I've decided to post an issue, as maybe someone will have an idea on where to look and how to fix this.

### Steps to Reproduce
1. Use ImportMaps to load javascript, in a Rails 7 app, with Avo 2.9.0. Everything should work as expected.
2. Bump Avo to `2.9.1.pre6` or even `2.9.1.pre4`
3. Try to trigger any JS loaded via Import Maps
4. JS is not loaded. See error

### Expected behavior
JS should load.

### Actual behavior
JS is broken

### System configuration
**Avo version**:
Working: 2.9.0
Not Working: 2.9.1.pre4 or 6

**Rails version**:
Rails 7.0.3

**Ruby version**:
ruby 3.1.2p20

**License type** (Community or Pro):
Pro

### Screenshots
<img width="1438" alt="Screenshot 2022-07-04 at 18 20 16" src="https://user-images.githubusercontent.com/6984619/177191573-a6bd165c-e0ed-41eb-9302-288969abe043.png">
<img width="1440" alt="Screenshot 2022-07-04 at 18 20 03" src="https://user-images.githubusercontent.com/6984619/177191569-a84a192e-f029-4028-a8b0-a4a7c77f775c.png">

### Additional context
Because of this bug, I've reverted the Avo gem to 2.9.0, and can't use the multi-language feature 😞 

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency (for us)
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @db0sch,

I tried to replicate this with a new rails app with importmaps.

The imported JS loads properly on my end. Can you try it on your end and confirm it works?

```
rails new rails_7_importmaps
cd rails_7_importmaps

bin/rails app:template LOCATION='https://avohq.io/app-template'
bin/rails g controller home
# create an index.html.erb inside `app/views/home`
# add the `def index; end` method to `home_controller`
```

Where are you getting that error? Are you using SSL in development?

![CleanShot 2022-07-04 at 19 36 59](https://user-images.githubusercontent.com/1334409/177193390-23a3c437-6a69-4de5-8b16-31cdf1070ff4.png)

**Comment by adrianthedev** [comment]
Using `2.9.1pre6` BTW

![CleanShot 2022-07-04 at 19 41 28](https://user-images.githubusercontent.com/1334409/177193783-fb33b2ee-6012-4ff3-81a5-66e6a0f43447.png)

**Comment by adrianthedev** [comment]
Actually, let me troubleshoot it some more.

**Comment by adrianthedev** [comment]
I see some differences from `main` and `2.9.0`. I'm actively looking into it.

**Comment by adrianthedev** [comment]
@db0sch, I found it. 

I release the `pre` versions from my own machine built in a custom docker image. The build process also picks up a few more artifacts from my machine, so they are a bit different from the official releases.

In `pre4` and `pre6` (and probably in other `pre` releases), there's a rogue empty `application.js` file lurking in the `app/assets/builds` directory, that shouldn't be there. When your app was loading that file instead of your own `application.js`. 

Sorry about that. I'm cleaning it up and releasing a new pre-release for you to use until tomorrow's official release.

**Comment by adrianthedev** [comment]
@db0sch please try out `pre7`

https://rubygems.org/gems/avo/versions/2.9.1.pre7

**Comment by adrianthedev** [comment]
Did that fix it for you @db0sch?

**Comment by db0sch** [comment]
Hello @adrianthedev Thanks a lot.
I didn't have the time to check if the new release fixes, yet.
I'll try tonight, or tomorrow morning.
Thanks a lot for being so reactive 🙏

**Comment by adrianthedev** [comment]
Cool. No hurry!

**Comment by db0sch** [comment]
Thanks @adrianthedev 
Unfortunately, I do have the same bug.

Interestingly enough though, I compared the 2 application.js sent by the app with and without the pre7 version of avo:

Without AVO pre7:
```js
// => /assets/application-3229fcecdda7e4736b4759e651ac79e1b8294fa8e4f32a6f3f6fafbdc383abb8.js
import "@hotwired/turbo-rails";
import "controllers";
import * as bootstrap from "bootstrap";


// Enable Bootstrap Tooltips
const initTooltip = () => {
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
  [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
};

initTooltip();
```

☝️ which matches with what I have in my code

WITH pre7:
```js
(()=>{})();
//# sourceMappingURL=/assets/application.js-8126603a99003c29abd335aedc35194359cf35d0798939e63481a47cc7b7c1ad.map
//!
;
```
and this `.map` file lead to:
```json
{
  "version": 3,
  "sources": [],
  "sourcesContent": [],
  "mappings": "",
  "names": []
}
```

So indeed, somehow, pre-release is including a rogue `application.js` taking the precedence on mine 😞

**Comment by adrianthedev** [comment]
Are you sure you are on pre7? Ca you run `gem uninstall avo` first to uninstall everything and then bundle install?

I just want to make sure you have the right version. 
That "empty" application.js shouldn't be there.

**Comment by adrianthedev** [comment]
BTW, to install a specific version, I wrote this guide. 

https://docs.avohq.io/2.0/faq.html#try-a-pre-release-version

**Comment by db0sch** [comment]
Thanks a lot @adrianthedev for your help.
Always reactive. We appreciate it.

I guess this solves the issue 👌

**Comment by adrianthedev** [comment]
You're welcome! Glad it was solved. You should try `2.10` it might be fixed there too.
