### ISSUE TITLE
Can i remove 'Go Back' and 'Cancel' buttons for specific resource?

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1013]
### Context
How Can i remove 'Go Back' and 'Cancel' buttons for specific resource? Like `self.show_back_button = true` and `self.show_cancel_button = true`. And can i remove index page for some resources (only - :show, :edit, :create)?

### System configuration
**Avo version**: 2.9.1

**Rails version**: 7.0.1

**Ruby version**: 3.1.2

**License type** (Community or Pro): Community

**Comment by adrianthedev** [comment]
You can't do that right now.

We're open for PRs if you'd like to tackle that. Shouldn't be that difficult.

**Comment by Sweex99** [comment]
@adrianthedev Can you implement - disable index page?

**Comment by adrianthedev** [comment]
Oh, sorry. I didn't see that. I usually post different tickets for each request.

What do you mean by "disable index page"? Do you mean to not have it available on the sidebar menu? You could do that using the `index?` method on your policy. More details [here](https://docs.avohq.io/2.0/authorization.html#policies).

**Comment by Sweex99** [comment]
got it! wait for your PR)

**Comment by adrianthedev** [comment]
I'm pretty swamped with features customers requested a while back. I'm not sure when I'll be available to add that. 
TBH, the quickest way of getting that feature is to try and make the PR yourself when you have time. You can use a different option as a guide. Something like `self.description` on the `BaseResource`.

**Comment by Sweex99** [comment]
got it, i am not sure that i will have enough time(, but it not need ASAP

**Comment by adrianthedev** [comment]
I think this is fixed on the show page with `show_controls`. [Docs](https://docs.avohq.io/2.0/customizable-controls.html)
