### ISSUE TITLE
'Go Back' doesn't work as expected when navigating to an associated resource

### ISSUE THREAD

**Issue by hassyyy** [avo-hq/avo#1018]
### Describe the bug

Clicking on "Go back" in show page doesn't go back to the previous page. Instead, it goes back to the index page of the resource

### Steps to Reproduce
1. Create a resource(Reviews) which is associated to another resource(User)
2. Go to index page of resource(Reviews)
3. Click on the associated resource record(User)
4. Click on 'Go Back'

### Expected behavior

It should go to the previous page (index page of resource - Reviews)

### Actual behavior

It goes to the index page of resource - User

### System configuration
Avo version: 2.4.1

Rails version: 7.0.2.3

Ruby version: 3.1.1

License type (Community or Pro): Community

### Screenshots

https://user-images.githubusercontent.com/23002310/177504162-ca02bd21-6dd7-40a7-baa1-de88c01561fd.mov

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Yes, I see what you mean. I generally left those like this because they are not a painful problem. It's more of an annoyance. 

This is a good first issue that someone starting out could pick up.

**Comment by hassyyy** [comment]
Yes, exactly. Back button in the browser or the device works as expected. I thought of disabling that button itself but I came to know that [it's not available yet](https://github.com/avo-hq/avo/issues/1013)

Let's wait for someone to fix it either way. If I get time, I will give it a try as well 💪

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if you have new info.
