### ISSUE TITLE
Invalid license message

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#1024]
### Describe the bug

I have a fairly new app with only 3 resources added to Avo and I am getting an invalid license message and Avo crash when I try to deploy it to production (expected)

### Expected behavior
as a new user with only a few resources and nothing special I expect to be in the community license

### Actual behavior

It seems the root cause is in the
```ruby 
def on_resources_path
   request.original_url.match?(/.*#{Avo::App.root_path}\/resources\/.*/)
end
```

 request.original_url is 
```
"http://localhost:3000/admin_avo/resources/users"
```

but `/.*#{Avo::App.root_path}\/resources\/.*/` returns
```ruby
/.*http:\/\/localhost:3000\/admin_avo\/\/resources\/.*/
```

The regex has an extra backspace and therefore always return false whereas it should be true

### System configuration
**Avo version**: 2.10

**Rails version**: 7

**Ruby version**: 3.1

**License type** (Community or Pro): cOmmunity

**Comment by adrianthedev** [comment]
@alispat @adrienpoly The SSL certificate was renewed. I apologize for the downtime. Not sure why it didn't renew itself but will investigate.

**Comment by adrianthedev** [comment]
I sent over a license key for you to be able to do development and deployment and will fix this in the following days.

**Comment by adrianthedev** [comment]
I released https://rubygems.org/gems/avo/versions/2.10.2 that should address this issue ✌️
