### ISSUE TITLE
Reorder key-value fields

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1029]
### Feature
It would be helpful to reorder key-value fields. At the moment when you enter key values the only way to reorder them is to delete and re-add, which is difficult if you have many entries.

### Current workarounds
Delete and re-add those entries. Alternatively, when you display them to the user (outside of avo) you could apply a sort, but only very simple sorting would be possible (like alphabetical ordering).

### Screenshots
![Screenshot 2022-07-08 at 17 10 14](https://user-images.githubusercontent.com/111963/178030055-d3cbe13b-09d0-41ed-9731-d56c0209f690.jpg)

### Additional context
You can see this in the [avo demo app](https://avodemo.herokuapp.com/avo/resources/projects/36/edit)

**Comment by adrianthedev** [comment]
That sounds like a good idea. It shouldn't be that difficult to implement. Maybe someone can pick it up.

 - We have icon assets for records re-ordering (`arrow-up.svg` & `arrow-down.svg`). 
 - The JS logic should be to move an item in an array. The field holds the items as array of arrays in memory (`[['hoho', 'hohoho'], ['Teste', 'abc'], ...]` in the above example).
 - The JS logic should enable/disable the up/down buttons when the item is first/last
 - That's it 🤷‍♂️

**Comment by enderahmetyurt** [comment]
Hey @adrianthedev I can get it if it's still available 🙏

**Comment by adrianthedev** [comment]
Yes, you can!

**Comment by enderahmetyurt** [comment]
@adrianthedev you mean something like this 🤭 

https://github.com/user-attachments/assets/3986f146-b39f-4f65-bc48-8f52067a7acb

**Comment by enderahmetyurt** [comment]
https://github.com/user-attachments/assets/fb5a518c-f5c0-453f-a66d-b3779f9cf980



even it works in front-end well, it cannot be updated on DB. 

I checked what I sent to controller `"meta"=>"{\"ahmet\":\"\",\"ender\":\"\",\"yurt\":\"\"}"}` it looks like that but it looks on DB

```
3.3.1 :003 > p.meta_for_database
 => "{\"ender\":\"\",\"ahmet\":\"\",\"yurt\":\"\"}"
3.3.1 :004 > p.meta
 => {"ender"=>"", "ahmet"=>"", "yurt"=>""}
```

I am pretty new in AVO codebase. Where or what should I check?

**Comment by Paul-Bob** [comment]
Hey @enderahmetyurt, looking great already, thank you!

I would start by debugging it here https://github.com/avo-hq/avo/blob/main/lib/avo/fields/key_value_field.rb#L86.

The `fill_field` method is called to ensure that the data from the params is correctly parsed for each field before assigning it to the record and hitting the DB. There is a base `fill_field` and some fields override it, `KeyValueField` is one of those

**Comment by enderahmetyurt** [comment]
> Hey @enderahmetyurt, looking great already, thank you!
> 
> 
> 
> I would start by debugging it here https://github.com/avo-hq/avo/blob/main/lib/avo/fields/key_value_field.rb#L86.
> 
> 
> 
> The `fill_field` method is called to ensure that the data from the params is correctly parsed for each field before assigning it to the record and hitting the DB. There is a base `fill_field` and some fields override it, `KeyValueField` is one of those

Thank you man. I'll look at it 🙏

**Comment by Paul-Bob** [comment]
Let me know how it goes

**Comment by enderahmetyurt** [comment]
I debugged it and I noticed that `meta` field cannot be updated since The keys in meta to be changed are the same as the previous one.

![Screenshot 2024-10-02 at 09 15 06](https://github.com/user-attachments/assets/5e43c4b1-c39d-4c13-ad0e-e4c50d7b7e55)

but if I changed the `fill_field` method like this

```ruby
  begin
    new_value = JSON.parse(value)
  rescue StandardError
    new_value = {}
  end
  
  record.update(meta: {}) if key == 'meta'
  
  record.send(:"#{key}=", new_value)
  
  record
```

https://github.com/user-attachments/assets/85fd1d03-b7b0-44c4-b5c9-d4888ff9f2eb



it looks good but I don't like the solution. I'd like to hear your ideas 🙏

**Comment by Paul-Bob** [comment]
We can't do a direct `update` on `fill_field` method because it would be an early update without validations then we would have 2 updates on the same record per save request.

I suspected that this could be the issue, thanks for debugging it!

I'll do some research, meanwhile, let me know if you find anything.

While writing this, an idea just came to mind. What if we mark the key as dirty on the `fill_field` method, something like: `record.send(:"#{key}_will_change!")`

**Comment by enderahmetyurt** [comment]
```ruby
  def fill_field(record, key, value, _params)
    begin
      new_value = JSON.parse(value)
    rescue StandardError
      new_value = {}
    end

    record.send(:"#{key}_will_change!")
    record.send(:"#{key}=", new_value)

    record
  end
```

it works fine like above :)

**Comment by Paul-Bob** [comment]
Cool! Looking good!
