### ISSUE TITLE
Invalid License Error - Custom Tool?

### ISSUE THREAD

**Issue by sdcoffey** [avo-hq/avo#1030]
### Describe the bug
I just finished setting up a really basic Avo installation. Love Avo so far!

I have just a couple of resources, so I would expect to be well within the bounds of the community edition. However, I'm getting an invalid license error stating that I'm using a custom tool when I'm pretty sure I'm not. In dev this presents as a warning banner, and in production, the app crashes (which makes sense).

Here's my initializer
```ruby
# avo.rb
Avo.configure do |config|
  config.root_path = '/admin'

  config.license = 'community' 

  # ...
end
```

And here's the relevant section of my routing config:
```ruby
  authenticate :user, ->(u) { u.admin? } do
    mount Avo::Engine => '/admin'
    mount Sidekiq::Web, at: '/admin/sidekiq'
    mount Blazer::Engine, at: '/admin/blazer'
  end
```

### Steps to Reproduce
1. Visit `/admin`

### Expected behavior
No License Error

### Actual behavior
<img width="984" alt="Screen Shot 2022-07-09 at 09 34 25" src="https://user-images.githubusercontent.com/3506415/178114745-bc7461d7-2ac0-48bb-86a5-94f6ac7dc13a.png">

### System configuration
**Avo version**: 2.10.0

**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**License type** (Community or Pro): community

## 🤔 What I think is the issue
Picking through the source code, Avo checks to see if I'm on the root path to determine if I'm using a custom tool:
https://github.com/avo-hq/avo/blob/d3cec9bb7189d76c3835fa9e32c7542870af5c56/app/controllers/avo/application_controller.rb#L263-L265

however when I step through this code, I see the following values:
```ruby
request.original_fullpath => "/admin"
Avo::App.root_path => "http://localhost:3000/admin"
```
Obviously the above code would never evaluate to true when the root path also contains the host and the port.

I __think__ this check look more like the others, e.g.:
```ruby
    def on_root_path
      request.original_url.match?(/.*#{Avo::App.root_path}\/?/)
    end

    def on_resources_path
      request.original_url.match?(/.*#{Avo::App.root_path}\/resources\/.*/)
    end

    ...
```

#### Impact

This bug means that I can't deploy Avo to production 😱

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @sdcoffey. I sent a pro key to your email so you can continue to develop and deploy Avo. 
I'm away for a few days, but I'll have a fix up soon.

**Comment by sdcoffey** [comment]
🙏 thank you!

**Comment by adrianthedev** [comment]
I released https://rubygems.org/gems/avo/versions/2.10.2 that should address this issue ✌️
