### ISSUE TITLE
404 when searching on resource with namespaced model

### ISSUE THREAD

**Issue by sdcoffey** [avo-hq/avo#1042]
Hey Avo team! Have another one for you

### Describe the bug
I have this resource:

```ruby
class CurrencyResource < Avo::BaseResource
  self.model_class = Warehouse::Currency
  self.title = :name

  self.search_query = lambda { |params:|
    scope.ransack(symbol_i_cont: params[:q].upcase, name_i_cont: params[:q], m: 'or').result(distinct: false)
  }

  field :name, as: :text, link_to_resource: true
end
```

When i run a search on this resource from the index page, I get the following error (as seen in the Rails logs):

```
ActionController::RoutingError (No route matches [GET] "/admin/avo/avo_api/warehouse/currencies/search"):
```

If i `gem open avo` and make the following change here:

**Before**
https://github.com/avo-hq/avo/blob/7a6721b6d8fb4871517c837db7e38a77ba0f09f8/app/components/avo/views/resource_index_component.html.erb#L36-L38

**After**
```ruby
# Changed resource to @resource.model_key from @resource.model_name.collection
<div class="flex items-center px-4 w-64">
  <%= render partial: 'avo/partials/resource_search', locals: {resource: @resource.model_key} %> 
</div>
```

It works as expected

### Steps to Reproduce
1. Add a basic resource with a namespaced model
2. Add a search scope in the resource declaration
3. Run the search from the index page

### Expected behavior & Actual behavior
Functional Search

### Models and resource files
Pasted above

### System configuration
**Avo version**: 2.10.2

**Rails version**: 7

**Ruby version**: 3.1.2

**License type** (Community or Pro): community

How much are you impacted by this issue?
Please set a level for Impact and Urgency
*Mark [x] inside the backets
-->
#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
That's amazing @sdcoffey. That must have slipped on a refactoring. Would you mind opening a PR with that fix? We should be able to release it on Tuesday.

Thank you!
