### ISSUE TITLE
404 for search with custom relative_url_root

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1052]
### Describe the bug

Avo has_many related search isn't using relative_url_root

### Steps to Reproduce
1. Add this configuration
application.rb
```rb
      config.relative_url_root = '/development/internal-api'
```
config.ru
```rb
  map '/development/internal-api' do
    run Rails.application
  end
```
3. Make a has_many association searchable: true
4. observe 404

### Expected behavior & Actual behavior
Expected: search request at
http://localhost:3000/development/internal-api/avo/avo_api/teams/search?q=charlie&global=false

Actual: search request at
http://localhost:3000/avo/avo_api/teams/search?q=charlie&global=false

### System configuration
**Avo version**: 2.10.2

**Rails version**: 7.0.2

**Ruby version**: 3

**License type** (Community or Pro): Pro

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by coffenbacher** [comment]
Hi @adrianthedev, I just noticed this issue is back in my local environment 🤔 Is it possible there was a regression at some point?

**Comment by adrianthedev** [comment]
Are you on the latest Avo version? We fixed that at one point.

**Comment by coffenbacher** [comment]
I am on the latest version 2.27.1, I think it was working for me from the time of the issue until sometime fairly recently

**Comment by adrianthedev** [comment]
Can you share a recording of the JS console and the request panel?
I'm curious about what's happening there.

**Comment by coffenbacher** [comment]
Here are some screenshots of those that might help?? 🙏 Thanks for looking!

<img width="1059" alt="Screenshot 2023-03-10 at 2 35 00 PM" src="https://user-images.githubusercontent.com/245867/224441482-5a89056d-bc37-4bc6-8ecd-14961f034a96.png">
<img width="1013" alt="Screenshot 2023-03-10 at 2 34 31 PM" src="https://user-images.githubusercontent.com/245867/224441485-ced0b58f-8fe9-4e3d-a599-6df38dcc693f.png">
<img width="1181" alt="Screenshot 2023-03-10 at 2 34 13 PM" src="https://user-images.githubusercontent.com/245867/224441489-43ab8ff1-2aa7-4474-82b7-1598f87486a3.png">
<img width="1181" alt="Screenshot 2023-03-10 at 2 33 57 PM" src="https://user-images.githubusercontent.com/245867/224441493-73c768dc-2bf2-4b64-9f81-0bf15507c10f.png">

application.rb
<img width="539" alt="Screenshot 2023-03-10 at 2 41 24 PM" src="https://user-images.githubusercontent.com/245867/224441718-777521f5-094e-4a45-902f-1de8aa3340b7.png">

config.ru
<img width="539" alt="Screenshot 2023-03-10 at 2 40 59 PM" src="https://user-images.githubusercontent.com/245867/224441722-c55032a0-170e-4b93-b9d3-1675dabdc8be.png">

**Comment by coffenbacher** [comment]
Found some additional information digging in the minified JS as to where a problem might be, this seems to resolve it for the window:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/245867/224442970-ffc3f468-46c0-4794-af6c-153592e7fb50.png">

**Comment by adrianthedev** [comment]
hmmm. I remember now, you have this piece of configuration, which I don't really know how it works and what kind of paths it creates.

```ruby
map '/development/internal-api' do
  run Rails.application
end
```

Would you be kind to create a new rails app with that config so I can test it and see how I can provide a fix for good?

**Comment by coffenbacher** [comment]
Hi @adrianthedev , yes sure! Here you go:

https://github.com/coffenbacher/avo-repro

No changes except adding the config.ru route map, relative_url_root in application.rb, and adding a Widget model that belongs to Categories for search testing.

**Comment by adrianthedev** [comment]
Related to this: https://github.com/avo-hq/avo/issues/1641
