### ISSUE TITLE
I can't have a resource named Order

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1063]
### Describe the bug
I can't have a resource named Order, after you create one you can even see the index

### Steps to Reproduce
1. Generate a resource with name order
2. Try to test the complete CRUD, go create one order.
3. 5. See error

### System configuration
**Avo version**: 2.10.2

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots
![image](https://user-images.githubusercontent.com/13969616/179375550-17a8c0de-13c5-4a6b-8e24-05d829f00fe5.png)
![image](https://user-images.githubusercontent.com/13969616/179375543-d93fe982-e9c5-40a3-90dc-637a2f85a9c9.png)

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Ues. It's a bug introduced in the last release. 

[This](https://github.com/avo-hq/avo/pull/1053) PR fixes that. It should be out in the next release.
