### ISSUE TITLE
Config "buttons_on_form_footers: true" show form buttons at the top and not the footer

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#1067]
### Describe the bug
It seems that when you set the config "buttons_on_form_footers" the footer is visible at the top above the form and not below.

### Steps to Reproduce
1. Enable buttons_on_form_footers in avo settings
2. Navigate to a form

### Expected behavior & Actual behavior
Form buttons should be present below and not above the form

### System configuration
**Avo version**:
2.11.0

**Rails version**:
6.1.3

**Ruby version**:
2.7

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/11912368/179760642-6a56adfb-ec53-420a-9836-6b7c5edc96f7.png">

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x ] low urgency

**Comment by adrianthedev** [comment]
It's actually View components acting out 😐

**Comment by adrianthedev** [comment]
Fixing in https://github.com/avo-hq/avo/issues/1925
