### ISSUE TITLE
A mechanism for identifying/generating paths from resources

### ISSUE THREAD

**Issue by dhnaranjo** [avo-hq/avo#1068]
### Feature
Given an arbitrary Avo resource or AR model, I would like to have route helpers to call `new_resourses_RESOURCENAME_path` appropriate for the resource or model.

Roughly I'd like to be able to:
```
dog = Dog.create
cat = Cat.create
avo.resource_path(dog) # calls "resources_dog_path", resolves to "#{AVO_BASE_PATH}/resources/dogs"
avo.new_resource_path(cat) # calls "new_resources_cat_path", resolves to "#{AVO_BASE_PATH}/resources/cats/new"
```

### Current workarounds
The absence of the feature is non-blocking. I'm able to work around it well enough. In each relevant resource define a method similar to the one below and call it in the Action.

```
class PredictionResource < Avo::BaseResource
  ...
    def new_record_path
    avo.new_resources_prediction_path
  end
  ...
end
```

### Screenshots
Not Applicable

### Additional context

While the request is generally applicable the specific use case is: I'm trying to make an action that duplicates a record. When the action is used on a record the user should be taken to a 'new' page but with all attributes of the duplicated record prefilled. The content below is provided as background

I've got this action:
```
class DuplicateRecord < Avo::BaseAction
  self.name = "Duplicate record"
  def handle(**args)
    models, resource = args.values_at(:models, :resource)
    model = models.first
    redirect_to resource.avo.new_resources_prediction_path(duplicate_of_id: model.id)
    silent
  end
end
```

And this here concern I'm including in relevant `Avo::ResourcesController`s.
```
module Avo::Duplicable
  def new
    super
    if params[:duplicate_of_id]
      @model = Prediction.find(params[:duplicate_of_id]).dup
      @resource = @resource.hydrate(model: @model, view: :new, user: _current_user)
    end
  end
end
```

The problem is the point in the Action where you're `redirect_to`'d `avo.new_resources_predictions_path`, `Prediction` being a model in my app. I am looking for a way to generate the appropriate path for any arbitrary resource.

I have tried `avo.polymorphic_path` but that points me at `prediction_path`, which does not exist, and is not appropriate for the `new` action anyway.

If you happen to have any critique of the duplication code feel free to toss that in, but don't go out of your way. It all works well enough for my needs.

**Comment by adrianthedev** [comment]
Given it's a `PredictionResource`, the `avo.new_resources_prediction_path` helper should work just fine.

Can you share the Avo version and the name of your resource, please? AFAIK the path helpers should work.

**Comment by adrianthedev** [comment]
Please try `Avo::App.view_context.avo.new_resources_prediction_path`. The base action does not have the `view_context` object so it doesn't know how to create the routes. I'll add it in the next release.

**Comment by dhnaranjo** [comment]
I'm on Avo 2.9.0.

What I'm looking for is the ability for the Action to be reusable for multiple arbitrary Resources. I should be able to create a brand new model and resource and add this duplication behavior to it by adding the action to the `Resource` and my concern to the `ResourcesController`, without making modification to either the action or concern. Currently this isn't possible.

I was gonna refer you to [Rails polymorphic routes](https://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html) and realized I could achieve what I'm going for with

```
resource_path_name = model.class.name.underscore.to_sym
resource.avo.polymorphic_path([:new, :resources, resource_path_name])
```

I still think it'd be nice if a resource could provide its own helpers.

**Comment by adrianthedev** [comment]
Hey man, nothing to be embarrassed about. If anything, I should be for not surfacing the docs better. Working on that.

You can use `Avo::App.view_context.avo.new_resources_prediction_path` to fix that temporarily until the next release when the regular routes will work.
