### ISSUE TITLE
Error with optional belongs_to and resource labels

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#1074]
### Describe the bug
It seems that in the newest Avo version (2.11.0, upgraded from version 2.7) labels of optional belongs_to are causing error on loading the index (and also edit) view of a resource.

For example:
If I have a list of `users` which have a optional belongs_to field, then I get following error on loading the users index view:

```
undefined method `id' for nil:NilClass
```

### Steps to Reproduce
1. Add optional belongs to to a resource
2. Load the index view where at least for one the belongs_to is missing

### Expected behavior & Actual behavior
Add check if the belongs_to is optional

### Models and resource files
I think thats the part which causes the error
```
 def label
        value.send(target_resource.class.title)
 end
```

### System configuration
**Avo version**:
2.11.0

**Rails version**:
6.3.1

**Ruby version**:
2.7

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency (not for us, but might cause error also for new users)
 - [] low urgency

**Comment by blacklist-arcc** [comment]
Same problem on our site. We have a resource with `belongs_to :other_resource, required: false` in the model. Viewing the resource with the ` :belongs_to` option in the avo resource will result in the same error.

```
undefined method `title' for nil:NilClass
def label
  value.send(target_resource.class.title)
end
[avo (2.11.0) lib/avo/fields/belongs_to_field.rb:183:in `label'](http://localhost/avo/resources/videos#)
```

Business impact is medium for us - the field can be edited on the opposite site with `has_one` relationship.

**Comment by adrianthedev** [comment]
Yes, it's related to https://github.com/avo-hq/avo/pull/1084.

View component changed the way it evaluates the content inside a wrapper component. Pre v`2.61` it did not evaluate it before, now it evaluates it beforehand. We used the wrapper components as safeguards for scenarios like these (when the value is `nil`) and now that broke with that release.

@blacklist-arcc and @jony1993 please use version `2.11.1` that reverts the view component version update.

Sorry about that. I'll have to figure out a way to refactor all the fields somehow.

https://rubygems.org/gems/avo/versions/2.11.1

**Comment by adrianthedev** [comment]
And thank you for reporting it so soon!
