### ISSUE TITLE
Include stimulus to custom page

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1078]
### Context
I create customer page (html, route, action controller) and i want to connect stimulus controller to my custom page but it does not work. How can i include stimulus controller to customer page
### System configuration
**Avo version**: 2.10.2

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type** (Community or Pro): COM

### Screenshots

![Screenshot 2022-07-20 at 18 06 43](https://user-images.githubusercontent.com/27281496/180017750-2e01ad8d-8316-495d-89a2-c5b96c0b6e9f.png)
![Screenshot 2022-07-20 at 18 07 19](https://user-images.githubusercontent.com/27281496/180017757-38ba7e54-041b-488d-aaa3-4483bb01029e.png)
![Screenshot 2022-07-20 at 18 07 42](https://user-images.githubusercontent.com/27281496/180017762-0fdd2fae-b6df-4e5b-a474-8188adab4d1a.png)

**Comment by adrianthedev** [comment]
You need to add that JS controller on the page with a custom asset pipeline. It sounds more advanced than it is. 

It's adding the JS `javascript_include_tag` to your `_head.html.erb` partial (which you eject from Avo with `bin/rails generate avo:eject :head`.
