### ISSUE TITLE
Date field adds/subtracts timezone offset

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1079]
### Describe the bug

The date field is subtracting the timezone offset when it shouldn't

### Steps to Reproduce
1. Go to a resource with a date field
2. set the field to 20th of the month
3. set the browser timezone to something US based like `CST`
4. observe on the `Index` it displays 19th instead of 20th

### System configuration
**Avo version**:
6.11

**Rails version**: 

**Ruby version**:

**License type**:

 - [x] Community
 - [x] Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by estebanutz** [comment]
@adrianthedev I recently upgraded to 2.13.1, and my date fields are subtracting days each time I save. 

### Steps to reproduce
Steps to reproduce the behavior:

1. Date Resource like: `field :published_date, as: :date, first_day_of_week: 1, picker_format: "F J Y", format: "yyyy-LL-dd"`
2. Create a record with a date
3. Edit record and save without touching the date field
4. Record should show a day before.
5. Repeat edit and save to keep subtracting dates. 

### System Configuration
Avo version:
6.11

Rails version:
Rails 6.1.6.1

Ruby version: 
ruby 2.7.2p137

License type:
Pro

**Comment by adrianthedev** [comment]
Oh man. These date and date_time fields are such a PITA. I see the bug. I'll have it fixed by the next release. I'll also have a pre-release version for you to try out tmr.

Sorry about this.

**Comment by estebanutz** [comment]
@adrianthedev I know! PITA indeed! But thanks for looking into it!

**Comment by adrianthedev** [comment]
Hey @estebanutz can you try https://rubygems.org/gems/avo/versions/2.13.4.pre.1 and see if the issue persists?

**Comment by estebanutz** [comment]
@adrianthedev The issue has been fixed. Thanks!

**Comment by adrianthedev** [comment]
Cool. Thanks for helping and sorry about the troubles.
