### ISSUE TITLE
Custom Pundit policy per resource

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1085]
### Feature

Add the ability to select which policy a resource should use. 

From [here](https://discord.com/channels/740892036978442260/740893011994738751/999699188004692009). 

### Approach
_These thoughts come to my mind but feel free to use your own approach._

Add a `authorization_policy` `class_attribute` to `BaseResource`.

Right now, each resource has an `authorization` method applied to it. This will create a new `AuthorizationService` which, by default, tries to figure out the policy by itself from the model you're trying to authorize.
I think that's where we need to hook in and pass it a policy class (around here).
Then, add a `policy` method to the `AuthorizationService` which will default to figuring it by itself from the `@model` or use the one you give it.

**Comment by bear-in-mind** [comment]
Hey @adrianthedev I might work on this today. Can I ping you if I need help ?

**Comment by adrianthedev** [comment]
Hey man. Yes sure. Ping me!
Thanks for picking this up!
