### ISSUE TITLE
Avo crashes if the validator fails and the user attached a file

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1119]
### Describe the bug

It only happens sometimes.

### Steps to Reproduce and brake
1. Go to projects
2. click on create project
3. click attach a file and don't fill in any fields
4. click on submit and see it crash

<details>
<summary>Fails with</summary>

```
No route matches {:action=>"show", :controller=>"avo/projects", :id=>#<Project id: nil, name: "", status: nil, stage: "Discovery", budget: nil, country: "", users_required: nil, started_at: nil, meta: nil, created_at: nil, updated_at: nil, description: "", progress: 50>}, possible unmatched constraints: [:id]
Did you mean?  resources_project_url
               resources_projects_url
               resources_projects_path
               new_resources_project_url

```
![CleanShot 2022-08-01 at 22 41 17](https://user-images.githubusercontent.com/1334409/182231943-4523f182-647a-43fb-9afe-fe3380aadf0b.gif)

![CleanShot 2022-08-01 at 22 42 14](https://user-images.githubusercontent.com/1334409/182232005-73d10d2f-b85c-4203-b6e4-d5043a6f90a1.jpg)

</details>

### Steps to Reproduce and succeed
1. Go to a user
2. click create new user
3. select a file to upload and don't fill any other fields
4. click submit
5. observe it's not crashing

<details>
<summary>Details</summary>

![CleanShot 2022-08-01 at 22 42 44](https://user-images.githubusercontent.com/1334409/182232145-205d4785-3948-4c8a-9a14-5207932296d4.gif)

</details>

### System configuration
**Avo version**: 2.11

**Rails version**:

**Ruby version**:

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

**Comment by Adeynack** [comment]
It happens systematically when a file is attached. Not "sometimes". And this has quite a high impact in our case at [nerdgeschoss](https://github.com/nerdgeschoss) since the user expects to be reminded of the required fields instead of seeing the application crash. 😐 

We would appreciate if someone could look quickly into it. 🙏🏼

**Comment by Paul-Bob** [comment]
@Adeynack thank you for the details, we are working on fixing this issue
