### ISSUE TITLE
Issue with path helpers and relative URL root

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1132]
### Describe the bug

I am running my app like this, such that Avo is accessible at `http://localhost:3000/development/internal-api/avo/`
```rb
  map '/development/internal-api' do
    run Rails.application
  end
```
and 
```rb
      config.relative_url_root = '/development/internal-api'
```

Most features work well, but when I try to use helpers like 
```rb
<%= link_to "Add as example", avo.resources_example_path %>
```

It links to `/development/avo/examples` instead of `/development/internal-api/avo/examples` like I would have expected.

Any ideas??

### System configuration
**Avo version**: 2.12

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey man, sorry. 
I never mapped out an application like that. I don't know the implications.

My hunch is that it's not an Avo issue, but a Rails & "how it handles engines" issue.

Can you share a link to the docs where that `map` statement is documented?

**Comment by adrianthedev** [comment]
Also, can't you use the regular `routes` file to use that path?

**Comment by coffenbacher** [comment]
Could be a Rails issue indeed. The support for running at relative paths seems pretty wonky. I was following [this blog post](https://jlintusaari.net/deploying-rails-application-to-subdirectory/) to get it working because the official Rails guide.

If this is unlikely to be Avo-specific, I'll try digging into it and seeing if I can resolve it. 

What did you mean by using the `routes` file, I didn't follow that suggestion? Is the idea to adjust the routes to serve at a relative URL instead of trying to configure the whole Rails application itself? I could try that, if that's what you mean 🤔

**Comment by coffenbacher** [comment]
Yeah 👍  basically what I'm doing is serving different environments with nginx on different prefixes, but for that to work the application has to link to the prefixed URLs
```rb
/development/internal-api
/test/internal-api 
etc. 
```

Anyways, that is way outside of Avo so I won't bother you with that, but I appreciate the idea of a scope and if I can't figure out why the paths are wrong I'll try that instead!

I did notice one odd thing though and I'm wondering if this makes you think of anything that might help me track down the issue. The Avo sidebar links all work great from standard Avo `resources`, but when I click into a custom Avo `tool`, all of the sidebar links suddenly start linking to these wrong (abbreviated) relative URL. It's like the path helpers are wrong but only inside the context of a tool, not a resource. Can you think of anything that might cause that?

**Comment by adrianthedev** [comment]
I think I noticed that at one point.

Try moving the custom tool routes from `Rails.application.routes.draw do` to a new `Avo::Engine.routes.draw do` like below.

```ruby
if defined? ::Avo
  Avo::Engine.routes.draw do
    # make sure you don't add the `avo/` prefix to the controller below
    get 'custom_page', to: "tools#custom_page"
  end
end
```

Here's [the guide](https://docs.avohq.io/2.0/recipes/multitenancy.html#update-the-custom-tools-routes) for multitenancy.

**Comment by coffenbacher** [comment]
Oh sick, that worked! Thank you! 🙌
