### ISSUE TITLE
Taking a long time to load some screens

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1134]
### Context
When opening a form, it will take over a minute to load the page, which remains not responsible.

### System configuration
**Avo version**: 2.12.0

**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**License type** (Community or Pro): Pro (trial)

### Screenshots
https://user-images.githubusercontent.com/575138/183966010-2e045fde-bd12-4419-8807-e784076349a4.mp4

I clicked on edit and it took a very long time to load the form. The products table is filled with around 33k products, and the schema is not the best (it is legacy, very old, and are proposing changes).

No errors on rails console, no errors on the browser.

**Comment by adrianthedev** [comment]
It's probably the `belongs_to` field that's loading all the products in order to display them in the select box.

Try adding `searchable: true` to that field.

**Comment by alansikora** [comment]
Bingo! Thanks a lot!
