### ISSUE TITLE
Pre-populate fields on create pages from URL params

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1136]
### Feature

I would love it if there was a way to pre-populate fields on the create page from the URL as a flexible way to link from custom tools to the standard [C]RUD page. For example:

http://localhost:3000/avo/resources/widgets/new?name=hello%20world

### Current workarounds

I imagine this might be possible using custom fields and Javascript but I haven't gotten that far yet. I thought about creating a record and then linking to the edit page, but there were some required fields I couldn't robustly set to defaults.

**Comment by adrianthedev** [comment]
Hey man.

Have you tried the [`default` option](https://docs.avohq.io/2.0/field-options.html#default-value)? It also takes a block where you can use the `params` global object.

```ruby
field :name, as: :text, default: -> { Avo::App.params[:name] }
```

**Comment by coffenbacher** [comment]
Oh great, that callback looks like exactly what I need.

Only issue now is that the default doesn't seem to work on text fields for me. The select field example in the default documentation works for me.

I.e. these both have seem to have no effect on the field content as far as I can tell:
```rb
  field :name, as: :text, default: 'John'
```
```rb
 field :name, as: :text, default: -> { 'John' }
```

**Comment by adrianthedev** [comment]
Is that on the `Edit` or `New` view? The default option works only on the `new` view.

**Comment by coffenbacher** [comment]
That's on the /new view indeed.

Makes sense why the edit view wouldn't work 👍

**Comment by adrianthedev** [comment]
You could try and use the [`format_using`](https://deploy-preview-3--avo-v2-docs.netlify.app/2.0/field-options.html#fields-formatter) option to coerce the default value on edit somehow.
