### ISSUE TITLE
Revamp the filtering system

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1154]
Things I'd like to add to this new iteration:

- [ ] filterable fields
- [ ] allow multiple conditions
- [ ] the end-user should be able to add& remove filters and conditions as they wish

#### Code snippets

```ruby
  field :first_name, as: :text, filterable: true
  field :stage, as: :text, filterable: {processing: "Processing", done: "Done"}
  field :status, as: :select, filterable: true, options: {}
  field :created_at, as: :date_time, filterable: true
```

#### Screenshots

![Image](https://user-images.githubusercontent.com/1334409/185737232-6cd759eb-baf4-42f0-9b0c-66711a7d20dc.jpg)

**Comment by brandondrew** [comment]
this looks awesome!

**Comment by adrianthedev** [comment]
It's coming in Avo 3 🚀

**Comment by adrianthedev** [comment]
Shipped in Avo 3
