### ISSUE TITLE
Authorization bugged when multiple resources have the same model class

### ISSUE THREAD

**Issue by nicholaswellens** [avo-hq/avo#1162]
Encountered this bug in our project and thought it might be useful to share it.

## Bug
When multiple resources define the same `model_class`, authorization for associations (eg. attach_xxx) stopped working correctly for those resources. Although it sometimes correctly blocks the actions (not allowing to attach), the buttons are still visually shown. 
In our case it was for a _has_many_ association, and _pundit_ is used for authentication.

## Reason
I have tried to investigate the problem, this is what I think is happening:

Imagine we have two resources, _resource1_ and _resource2_ both pointing to _model1_, and we open the show page of _resource_2_ .
Inside the method `authorize_association_for` (`resource_component.rb`) there is the following line (47): 

`reflection_resource = ::Avo::App.get_resource_by_model_name(@reflection.active_record.name)`

The method `get_resource_by_model_name` fetches a single resource, which can be the wrong one if the model is associated with more than one resource (eg. fetching _resource1_ instead of _resource2_, as happened in our case)

Later we call `authorization` on this resource, and because _resource_1_ is not properly hydrated (user is nil, I'm assuming this is because we don't hydrate a resource when we are not using it) the authorization fails, even though it authorizes with the correct model _model1_.

#### NOTE: 
In the same situation, also the name of the associated field was not getting rendered on the show:
Eg when we have `field :paper_trail_versions, as: :has_many, name: "Version History"`
It shows _Versions_ instead of _Version History_. --> during rendering of `Avo::PanelComponent`, title is nil. Without multiple resources having the same `model_class`, it renders correctly. Am still investigating this.

## System configuration

Avo version: 2.12.0

Rails version: 6.1.6.1

Ruby version: 3.0.2

License type (Community or Pro): Pro

**Comment by adrianthedev** [comment]
HEy @nicholaswellens can you please try out https://rubygems.org/gems/avo/versions/2.13.5.pre.1 and let us know if it fixes the issue?

**Comment by adrianthedev** [comment]
Hmmm... yeah. You're right. I thought the field was fetched in a smarter way. Let me refactor that.

**Comment by nicholaswellens** [comment]
@adrianthedev It is working! (the problem with `name` seems to also be resolved!). 

Although not needed in this particular case, I wonder what would happen if someone wants both resources to show the _association methods_. With both resources mappings added to `model_resource_mapping`, I assume only one of the resources would work correctly (tested this around a bit). In either case, for our use case it is fixed. Thank you for your fast answers/fixes!

**Comment by OlexYakov** [comment]
@adrianthedev 
It's solved with the `config.model_resource_mapping`, but the bug will still persist without it.
`authorize_association_for` will call `field.resource` ( `app/components/avo/resource_component.rb`), which eventually calls
`get_resource_by_model_name` in `FechesThings`. Code for context:
```ruby
        # Returns the Avo resource by singular snake_cased name
        #
        # get_resource_by_name('User') => UserResource
        # get_resource_by_name(User) => UserResource
        def get_resource_by_model_name(klass)
          # Fetch the mappings imposed by the user.
          # If they are present, use those ones.
          mapping = get_mapping_for_model klass
          return get_resource(mapping) if mapping.present?

          valid_resources
            .find do |resource|
              resource.model_class.model_name.name == klass.to_s
            end
        end
```
The problem is that we find by `resource.model_class.model_name.name`. Find will return the first element that evaluates to true. If two `Resources` have the same `model_class` only the first ever loaded will be found.

**Comment by nicholaswellens** [comment]
replacing `field.resource` call by @parent_resource in `authorize_association_for` is not an option? Although it is just a local solution

**Comment by adrianthedev** [comment]
That's correct @nicholaswellens. Only one resource would work. That is the main goal of the mapping option. To set the "default" resource for a model. 
However, if you want to use a different resource on a `has_many` field you can specify it with the `use_resource` fied option.

**Comment by adrianthedev** [comment]
That doesn't work because that's not the resource were looking for. It's the one on the `has_many` field. Consider that a resource can have more than one has many fields

**Comment by adrianthedev** [comment]
Guys, thank you for troubleshooting and brainstorming this with me. I appreciate your involvement in digging through the code!

I'll go ahead and merge #1171 and make the mapping a good practice with Avo apps.
