### ISSUE TITLE
How to handle different id property 

### ISSUE THREAD

**Issue by faqndo97** [avo-hq/avo#1165]
### Context
I have a model with id and name, but the `to_param` of the model is the name, so the links to show and edit action in the admin send the `name` as the `id` and of course it returns 404. I couldn't figure out how to solve this problem. Ideas? Thanks

### System configuration
**Avo version**: 2.11.0

**Rails version**:  6.1

**Ruby version**: 3.0.4

**License type** (Community or Pro): Community

**Comment by adrianthedev** [comment]
From what I can see I understand that you're trying to query the records using a custom query `/avo/resources/users/john-13` instead of `/avo/resources/users/13`, right? 

Does [this](https://docs.avohq.io/2.0/customization.html#custom-find-scope) guide help?

**Comment by faqndo97** [comment]
@adrianthedev I saw the custom_find_scope but I understand that that's to append scopes to the find query, not to find by a different attribute. What do you think? 

Basically instead of search by `find(params[:id])` it should do something like `find_by(name: params[:id])`

**Comment by adrianthedev** [comment]
Ok. I see what you mean. Yeah, that won't work. Sorry.

Add the following method on the `Avo::UsersController`

```ruby
  def set_model
    @model = eager_load_files(@resource, @resource.class.find_scope).find_by name: params[:id]
  end
```

Please be aware that this is an internal method that could change in the future, so you'll need to keep an eye on it when updating Avo.

Closing for now, but please feel free to reopen if this persists.

**Comment by segiddins** [comment]
Unfortunately, this doesn't work for resources with associations on them. Would it maybe make sense to move the `scope.find params[:id]` into a method on the resource, so this can be customized in a single place?

**Comment by adrianthedev** [comment]
Why doesn't it work @segiddins? What fails?

Can you share a reproduction app so I can have a look? It's rather difficult to help out in a hypothetical scenario. Solid code always works best!
If that's too difficult to create a new app, fork https://github.com/avo-hq/main.avodemo.com and add your particular changes to it so I can have a look. The avodemo app should have most association scenarios already built-in.

**Comment by segiddins** [comment]
https://github.com/segiddins/main.avodemo.com/pull/new/segiddins/to-param, go to http://127.0.0.1:3020/avo/resources/people/Winifred%20Bartoletti/spouses?turbo_frame=has_many_field_show_spouses

**Comment by adrianthedev** [comment]
Got it. Thank you!

I'm AFK for the better part of the day, but I'll figure out a solution, no worries.

**Comment by adrianthedev** [comment]
@segiddins. I started work on this but went into a deeper rabbit hole. 
This will be fixed by the next release (next Tuesday).

**Comment by segiddins** [comment]
Awesome, thanks so much!!!

**Comment by adrianthedev** [comment]
Just released 2.26 without this fix @segiddins. I'm actively working on it and will have another release with it fixed tomorrow.

**Comment by adrianthedev** [comment]
This has been enabled in https://rubygems.org/gems/avo/versions/2.26.2.pre.pr1579.
@segiddins and @faqndo97 please try it out.

Docs: https://docs.avohq.io/2.0/customization.html#custom-find-method-for-show-and-edit-pages
PR: https://github.com/avo-hq/avo/pull/1579

**Comment by adrianthedev** [comment]
It will be out in stable next Tuesday.
