### ISSUE TITLE
Cannot play intro video in full screen

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1170]
### Describe the bug
https://avohq.io If you fullscreen the video on the front page of the website. The video appears greyed out and only gives you the option to open the chat bubble.

**Comment by adrianthedev** [comment]
I don't get the same results. Are you using any type of adblocker or custom script?

![CleanShot 2022-08-25 at 13 09 23](https://user-images.githubusercontent.com/1334409/186637992-17689ace-feed-455c-8662-e0626e47ae49.gif)

**Comment by jmarsh24** [comment]
I'm using the latest safari with no adblockers or custom scripts.
![out](https://user-images.githubusercontent.com/48605824/186641644-5f372578-546f-460b-9146-345d755a0256.gif)

**Comment by adrianthedev** [comment]
I see it too now. Fixin it! Thanks!
