### ISSUE TITLE
Can't use a `trix` field in an Action

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1184]
### Describe the bug
Adding a `trix` field to an action returns the following 500 error:
![Screenshot 2022-08-30 at 12 15 52](https://user-images.githubusercontent.com/38864576/187411929-2960104b-8e2d-4cbf-8fbb-0be6673fb9a8.png)

### Steps to Reproduce
In an action, add the following:
```ruby
field :description, as: :trix
```

### Expected behavior & Actual behavior
It should display a trix editor, but the modal generation fails, and the request ends with the error above. Changing the `trix` for `textarea` works fine.

### System configuration
**Avo version**: 2.12.0

**Rails version**: 6.1

**Ruby version**: 2.7.4

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
I'll look into it.

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/avo/pull/1211
