### ISSUE TITLE
Lock/performance issues

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1185]
So, I've been experiencing this, which is a bummer. This is local development env, everything runs on localhost:

https://user-images.githubusercontent.com/575138/186984938-339acaec-e3dc-41d2-9c3f-0ef4dc114f83.mp4

As you can see, the query on DB takes 87ms and returns 37 rows:

https://user-images.githubusercontent.com/575138/186985328-3de7491d-b175-43cc-beba-6c325d435709.mp4

**Comment by adrianthedev** [comment]
Can you share the information on the [issue template](https://github.com/avo-hq/avo/issues/new?assignees=&labels=&template=bug_report.md&title=) please? They help with troubleshooting the issue.

Also, the query in the second video is a subset of data, not everything in the table. How many records are there in total in the table?

**Comment by adrianthedev** [comment]
You should update from 2.13.0 to at least `2.13.1`. There was a bug with the search not paginating results on that version.

https://github.com/avo-hq/avo/releases/tag/v2.13.1
