### ISSUE TITLE
Can't show resources with files

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1187]
### Describe the bug
I've just upgraded from 2.13 to 2.14 and every resource show page that has images has broken, and shows this error:

![Screenshot 2022-08-30 at 18 00 06](https://user-images.githubusercontent.com/111963/187496817-45ff3b11-464b-4424-af6b-79092d33e041.jpg)

I can't upgrade avo unless this is fixed as I use a lot of images.

### Steps to Reproduce
1. Use the local file active storage service
2. Add a resource with a file field, eg. `field :images, as: :files`
3. Start the server, create a new model with that resource and upload an image
4. See the error

### Expected behavior & Actual behavior

I'd expect it to show the resource with the uploaded file, but instead it crashes

### System configuration
**Avo version**: 2.14.1

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Additional context

I've had a look at the error in the web console and it seems that when rails calls this:

```
url_helpers.rails_disk_service_url(verified_key_with_expiration, filename: filename, **url_options)
```

`url_options` is nil - removing that parameter seems to prevent the error (a url is generated instead)

I'm using the disk active storage service, I haven't tried any of the other services yet to see if they have the same issue.

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Got it. I'm on it! There must be something related to the active storage versions.

**Comment by adrianthedev** [comment]
@iainbeeston I was able to reproduce it on a rails 7 app. 

Can you try [`2.14.2.pre.1`](https://rubygems.org/gems/avo/versions/2.14.2.pre.1)? I am using a different helper to fetch the path as an attachment (to trigger the download with the proper filename).

**Comment by iainbeeston** [comment]
@adrianthedev That works for me, could you please release that fix? 🙏

**Comment by adrianthedev** [comment]
Oh man. I'm so glad!

Releasing now.

**Comment by adrianthedev** [comment]
https://rubygems.org/gems/avo/versions/2.14.2 is out with that fix. Thanks for troubleshooting with me, and sorry for the trouble.
