### ISSUE TITLE
Unable to use Tailwind CSS on ejected templates

### ISSUE THREAD

**Issue by veelenga** [avo-hq/avo#1188]
### Steps to Reproduce

1. Eject logo template: `rails generate avo:eject :logo`
2. Try using some TailwindCSS utilities:

```diff
-<%= link_to root_path, class: 'logo-placeholder h-full w-full flex justify-start' do %>
+<%= link_to root_path, class: 'logo-placeholder h-full w-20 flex justify-start' do %>
  <%= image_tag '/avo-assets/logo.png', class: 'hidden sm:block object-contain', title: 'Avo' %>
  <%= image_tag '/avo-assets/logomark.png', class: 'sm:hidden object-contain', title: 'Avo' %>
<% end %>

```

### Expected behavior & Actual behavior

The `w-20` utility doesn't have any expected effect, however `w-10` works correctly. Seems like only some of the pre-compiled classes can be used in ejected templates.

### System configuration
**Avo version**: 2.13.1

**Rails version**: 7.0.3.1

**Ruby version**:3.1.2p20

**License type**:

 - [x] Community
 - [ ] Pro

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @veelenga. You are correct. The precompiled assets only have classes that are used in Avo.

To be able to use all Tailwind utilities you should add your own Tailwind config in your app using your [asset pipeline](https://docs.avohq.io/2.0/custom-asset-pipeline.html). 
What are you using now? Sprockets?

**Comment by veelenga** [comment]
Yes, sprockets. I tried following the [guide](https://tailwindcss.com/docs/guides/ruby-on-rails) and added tailwind to my project. It works perfectly on custom pages (out of avo), however, I am still not able to use it in ejected pages. 

Is this expected?

**Comment by adrianthedev** [comment]
No, that's not normal. Can you share the `tailwind.config.js` file contents? Can you ensure that `/app/views/**/*.erb',` this is under the `content` tag?

```js
module.exports = {
  mode: 'jit',
  future: {},
  content: [
    'app/avo/resources/**/*.rb',
    'app/views/**/*.erb',
  ]
}
```

This is given that you have the `tailwind.config.js` file at the root of your Rails app. You might need to play around with the paths, so they match.

**Comment by veelenga** [comment]
The command in the doc pre-generates the such a tailwind.config.js:

```js
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    'public/*.html',
    'app/helpers/**/*.rb',
    'app/javascript/**/*.js',
    'app/views/**/*.{erb,haml,html,slim}'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
  ]
}
```

and this works perfectly on views out of avo, but not in the ejected templates.

**Comment by adrianthedev** [comment]
This is weird, I just tried it out with the same steps (install `tailwindcss-rails` and all), and it kept my class.

![CleanShot 2022-08-31 at 10 28 46](https://user-images.githubusercontent.com/1334409/187619062-5fa980df-c5b7-412a-8f52-26808b674563.jpg)
![CleanShot 2022-08-31 at 10 28 57](https://user-images.githubusercontent.com/1334409/187619099-6472734c-5309-4e09-8613-eda5bd0e3fa1.jpg)

Just to cover my bases, can you confirm the following?

- you ejected `:logo` and applied your custom class (`w-20`), and you see that class added in the DOM
- you installed `tailwind-css` gem and compiled the css.
- you ejected `:head` and added the compiled CSS file to `_head.html.erb`. You see new CSS file added to the DOM

**Comment by adrianthedev** [comment]
I'm working on making it easier to add Tailwind to custom Avo content. I'll release something soon. I hope I get the chance to release some beta version today.

**Comment by veelenga** [comment]
It works if I add this to ejected _head.html.erb:

```erb
<%= stylesheet_link_tag 'tailwind', media: 'all' %>
```

Thanks for the help.

**Comment by adrianthedev** [comment]
Great! Thanks for troubleshooting it with me. I'll have a PR up to better support this use case.
