### ISSUE TITLE
Remove deprecated dependency to hotwire-rails

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#1192]
### Describe the bug

Avo has a built in dependency with hotwire-rails. This gem has been deprecated.
https://github.com/hotwired/hotwire-rails
A side effect is that this dependency link prevent me from upgrading my app to hotwire 7.2beta

I think the dependency should be replaced by `turbo-rails` and `stimulus-rails` (if you use the later)

### Steps to Reproduce
https://github.com/avo-hq/avo/blob/main/avo.gemspec#L44

### Expected behavior & Actual behavior
I would hope that Avo has as few dependency as possible that would prevent me from upgrading my app.

**License type**:

 - [x] Community
 - [ ] Pro

**Comment by adrianthedev** [comment]
You're right. I'll add this to the roadmap.
