### ISSUE TITLE
Resource links, rendered in tabs, not working as intended

### ISSUE THREAD

**Issue by nicholaswellens** [avo-hq/avo#1194]
### Describe the bug
`belongs_to` links (and other links that do not have turbo disabled or target set) that are defined under tabs, don't work correctly. 

### Steps to Reproduce
1. Go to show page of a resource that has tabs
2. Press the link of a `belongs_to` field
3. Does not direct correctly to the associated resource

### Expected behavior & Actual behavior
- Expected: Directs to the associated resource after pressing link
- Actual: stays on same page, tabs disappear

### Screenshots
![Screenshot from 2022-08-31 11-12-55](https://user-images.githubusercontent.com/18333645/187655434-e620fa43-5dc4-4d2c-a770-30c09b55f8a8.png)

![Screenshot from 2022-08-31 11-14-57](https://user-images.githubusercontent.com/18333645/187655788-0c58924b-6343-4a44-8875-7765ccb0e023.png)

(From a different tab & field)
![image](https://user-images.githubusercontent.com/18333645/187658306-23c7f5f6-548f-4f03-81b4-e38f47c6d900.png)

### Notes
Adding  `target: "_top"` to `link_to` in the `belongs_to` component solves the problem (but not sure if that is the correct approach)

### System configuration

Avo version: 2.12.0 (also tested with 2.14.2)

Rails version: 6.1.6.1

Ruby version: 3.0.2

#### Impact

 - [ ] High impact
 - [] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Ok. I see the issue.
Could you please use your workaround until we push a permanent fix? 
Thank you!

**Comment by Paul-Bob** [comment]
Hey, thanks for the note @nicholaswellens, actually that was my approach too, with a little tweak, we only apply `target: "_top"` when the field is inside a tab group

**Comment by nicholaswellens** [comment]
@Paul-Bob Great! Thanks for the fix!  :+1:
