### ISSUE TITLE
Cannot use Avo 2.14.2 without Sprockets

### ISSUE THREAD

**Issue by rajaravivarma-r** [avo-hq/avo#1203]
### Describe the bug
In our application we do not use sprockets, since we use webpacker.  So we removed all files and configurations related to sprockets. For example files under `app/assets`.

We tried to updated from 1.25 to 2.14.2, which leads to the following error,
```
railties (6.1.6.1) lib/rails/railtie/configuration.rb:97:in `method_missing'
avo (2.14.2) lib/avo/svg_finder.rb:33:in `default_strategy'
avo (2.14.2) lib/avo/svg_finder.rb:12:in `pathname'
```
Because `::Rails.application.assets` this returns `nil` in our case.

We would like to not use sprockets. Could you please remove this dependency?

### Steps to Reproduce
1. Clone this repo, created to demonstrate this behaviour https://github.com/rajaravivarma-r/avo-demo
  a. The command used to create bootstrap the rails project, without sprockets, is given in the README.md
2. Start the rails server `./bin/rails s` and point the browser to `localhost:3000`

### Expected behavior & Actual behavior
App should run without throwing errors, but it throws an error.

### Models and resource files
Repository provided in *Steps to reproduce*

### System configuration
**Avo version**: 2.14.2

**Rails version**: 6.1.6.1

**Ruby version**: 3.0.0

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots
<img width="1435" alt="Screenshot 2022-09-02 at 1 41 13 AM" src="https://user-images.githubusercontent.com/1841235/188003885-8e504401-0193-4df1-9c94-188caeb9b415.png">

### Additional context
- NA

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r. Can you try https://rubygems.org/gems/avo/versions/2.14.3.pre.6.nosprockets and let me know if that solves it for you?

**Comment by rajaravivarma-r** [comment]
@adrianthedev I tried the nosprockets version, it now throws this error 
`ActionView::Template::Error (uninitialized constant Webpacker::WebpackAssetFinder):
    1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
    2:   <%= render Avo::Views::ResourceIndexComponent.new(
    3:       resource: @resource,
    4:       resources: @resources,
    5:       models: @models,
`

**Comment by rajaravivarma-r** [comment]
![Screenshot 2022-09-02 at 4 40 16 PM](https://user-images.githubusercontent.com/1841235/188127217-404f7b57-f1d1-4cb7-bf90-1da823993e05.png)

**Comment by adrianthedev** [comment]
Cool. Let me troubleshoot this further and get back to you bu Monday. 
It's caused by the new way we're displying svgs.

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r.
I looked into this issue more and yes, V 2.0 won't work with just webpacker alone. You will have to install [sprockets](https://github.com/rails/sprockets) or [propshaft](https://github.com/rails/propshaft) side-by-side with webpacker.

AFAIK you won't have to do anything else, and you shouldn't be impacted by running both. I ran an app for years with sprockets and webpacker, and all was well. I'm happy to help you fix any problems that may occur from having both of them.

The reasoning behind this is that we removed webpacker from our tooling for a slimmer JS pipeline powered by `js-bundling` with `esbuild`. In that process, we are now using the `Rails.application.assets` object to fetch assets (mainly SVGs), and that is provided by sprockets or propshaft.

I'd love it if I could help you update Avo to the latest 2.x version. There are a lot of improvements there, and I apologize for having you put in this effort for the upgrade.

**Comment by rajaravivarma-r** [comment]
Hey @adrianthedev, I got you. We wanted to remove sprockets because, we did not use it and to enforce developers to stick to just one tool which is webpacker.

We will decide upon this using your inputs. I'll close this issue as it is clear. Thank you!

**Comment by adrianthedev** [comment]
Thank you for understanding @rajaravivarma-r. Let me know if I can help with anything going forward.

**Comment by tersor** [comment]
> I looked into this issue more and yes, V 2.0 won't work with just webpacker alone. You will have to install [sprockets](https://github.com/rails/sprockets) or [propshaft](https://github.com/rails/propshaft) side-by-side with webpacker.

For anyone that uses [Vite Ruby](https://vite-ruby.netlify.app/), this fix applies to them too.
