### ISSUE TITLE
Can't load avo on main due to missing assets

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1210]
### Describe the bug
When using [main](https://github.com/avo-hq/avo/tree/a98c72026518c194d74584f3651c42ca86c83ea8) avo javascript and stylesheets don't load for me, and I get the following not found errors in the rails logs:

```
14:23:25 web.1  | Started GET "/avo-assets/avo.base.css" for ::1 at 2022-09-05 14:23:25 +0100
14:23:25 web.1  |   
14:23:25 web.1  | ActionController::RoutingError (No route matches [GET] "/avo-assets/avo.base.css"):
14:23:25 web.1  |   
14:23:25 web.1  | Started GET "/avo-assets/avo.base.js" for ::1 at 2022-09-05 14:23:25 +0100
14:23:25 web.1  |   
14:23:25 web.1  | ActionController::RoutingError (No route matches [GET] "/avo-assets/avo.base.js"):
```

### Steps to Reproduce
1. Set avo in your gem file to `gem "avo", github: 'avo-hq/avo'`
2. `bundle install` and `bin/rails assets:clobber`
3. Start the rails server
4. Load avo in the browser

### Expected behavior & Actual behavior
Page loads and everything is styled as it was in avo 2.14.2, but actually no stylesheets load and the page looks white and unsettled.

### System configuration
**Avo version**: [main](https://github.com/avo-hq/avo/tree/a98c72026518c194d74584f3651c42ca86c83ea8)

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots

![Screenshot 2022-09-05 at 14 28 18](https://user-images.githubusercontent.com/111963/188460728-c4165b3d-5d94-4420-bdae-f5850c3f9845.jpg)

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Try and run `avo:build-assets` like [here](https://github.com/Rakefile)

**Comment by iainbeeston** [comment]
It works when I do that 👍

**Comment by adrianthedev** [comment]
Cool! Closing this for now.

**Comment by iainbeeston** [comment]
I feel like `CONTRIBUTING.md` or `bin/init` should mention running `bin/rails avo:build-assets` so that other developers don't have this issue. I'm not entirely sure why that's needed so I'm not sure the best place for it to go. @adrianthedev do you have an opinion on that?

**Comment by adrianthedev** [comment]
Yes, we should document that somewhere. Maybe there or in the docs. I'll make a note to have that documented. 

The reason for that is that we bundle the assets when we publish the gem so it doesn't impact your asset pipeline and your deployment process. 
We don't hook into the `asset:precompile` step because one might not have Node.js or anything like that when deploying with Avo.

**Comment by iainbeeston** [comment]
I've just realised that this is more of a problem than I had thought - it makes it very difficult to use avo directly from GitHub (for example, to use the latest main version) on a server (to do that you'd have to add an extra build step to run `bin/rails avo:build-assets`)

**Comment by adrianthedev** [comment]
Yes. I kinda wanted users not to use it directly from github, but from rubygems and I didn't automate that. But still, people will use it however they want to. 

You can automate that on the server using this hook. 

https://github.com/avo-hq/avodemo/blob/main/Rakefile
