### ISSUE TITLE
Actions (with zero resources) don't render

### ISSUE THREAD

**Issue by rickychilcott** [avo-hq/avo#1212]
### Describe the bug
The new "select all" feature from @Paul-Bob (#1148) has a small regression.

### Steps to Reproduce
1. Have an action on any resource - the table must be empty (i.e. no Fish in the FishResource table)
2. Go to the resource
3. Click on 'Actions'
4. Click the action you added
5. Don't see anything (but the console says:)

```log
stimulus.js:1658 Error connecting controller

TypeError: Cannot read properties of null (reading 'dataset')
    at get selectionOptions [as selectionOptions] (action_controller.js:39:90)
    at n.connect (action_controller.js:11:14)
    at gre.connect (stimulus.js:1068:29)
    at vre.connectContextForScope (stimulus.js:1260:17)
    at kre.scopeConnected (stimulus.js:1575:20)
    at Sre.elementMatchedValue (stimulus.js:1495:27)
    at $R.tokenMatched (stimulus.js:793:27)
    at VR.tokenMatched (stimulus.js:726:23)
    at stimulus.js:720:38
    at Array.forEach (<anonymous>)

{identifier: 'action', controller: n, element: div.hidden.text-slate-800}
```

The issue has to do the stimulus controller blowing up on the `datasets` portion of:

```js
  get selectionOptions() {
    return document.querySelector(`[data-selected-resources-name="${this.resourceName}"]`).dataset
  }
```

Since the selected resources are none, `dataset` isn't a thing.

### Expected behavior & Actual behavior

It should show the action 😄 

### System configuration
**Avo version**: 2.14.2

**Rails version**: 7.0.3.1

**License type**: 

 - [ ] Community
 - [x] Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

It's blocking upgrade... but I can hold off...

**Comment by Paul-Bob** [comment]
Hi @rickychilcott thanks for the detailed issue, sorry for the inconvenience. This should be easy to fix
