### ISSUE TITLE
I18n missing translations

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1216]
### Describe the issue and screenshots

- [x] Can't translate pagination details.

![image](https://user-images.githubusercontent.com/69730720/188857884-d636f250-ceff-4090-964b-ae48345c995a.png)

- [x] Can't translate "Filter by"

![image](https://user-images.githubusercontent.com/69730720/188858651-a094e480-b1b3-4fc1-97ca-6f074d92e586.png)

- [x] Despite changing the translations for search placeholder it don't apply, don't know if it's because I have some bad configuration

![image](https://user-images.githubusercontent.com/69730720/188859621-0e859150-80a7-41db-8cec-513bc46e94d3.png)

- [x] Using pluralized `one` instead `zero` on `no_item_found` and on `no_related_item_found` translation
 ```ruby
error_log:
        zero: "log de erro zero"
        one: "log de erro one"
        other: "logs de erro other"
```
![image](https://user-images.githubusercontent.com/69730720/188860997-78b9c158-e0ab-47fd-8dae-e9d2d8fc5b54.png)

### System configuration
**Avo version**:
2.14.2

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
For the `search` label, check out the [autocomplete config](https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-js/autocomplete/#parameters)

The `no_item_found` and `no_related_item_found` will be a breaking change so please update the upgrade guide in the docs.

Let's remove the `oops_nothing_found` key from all.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @adrianthedev , i get can this one, maybe we need some tool to keep translation updated, i was looking for this one: https://github.com/glebm/i18n-tasks, do you thinks is a good idea install as development dependency?

**Comment by adrianthedev** [comment]
Thank you @PedroAugustoRamalhoDuarte. Yes, let's install `i18n-tasks`. Looks like a pretty complete gem.
Can you do that in the same PR plase?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Yes!!
