### ISSUE TITLE
Filters button overlap

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1217]
### Describe the bug

Filters button overlap an already opened filters menu
![image](https://user-images.githubusercontent.com/69730720/188862787-06b4b47a-767b-415c-8319-0c190d452960.png)

### System configuration
**Avo version**:
2.14.2

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Paul-Bob** [comment]
Also, filters don't make sense on empty table

**Comment by adrianthedev** [comment]
What if the table is empty from the filters selaection? How would one reset the filters?
