### ISSUE TITLE
Throw an error when a field is declared multiple times on the same view.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1223]
### Feature

Because of things like `tabs` / `panel`, it's commonly necessary to declare the same field multiple times.  Unfortunately, this can lead to surprising results.  For example:  I just spent a few minutes going WTF when changes to a date field were getting ignored, because the old value was being POST'ed to the server.  I had just gotten done reorganizing a resource to use tabs, and had duplicated some field definitions so they would still show up in the index view.  It took me a few minutes to connect the dots.

It would be nice if definitions for the same field, with overlapping views that they apply to, produced an error instead of silently just making the field show up multiple times on the page with a last-one-wins approach to form submission.

### Current workarounds

N/A

### Screenshots

N/A

### Additional context

N/A

**Comment by Paul-Bob** [comment]
Hei @MrJoy, thank you for reporting this. 

@adrianthedev my approach would be:

- [ ]  raise exception when multiple definitions of some field were found on the same form

```ruby
...
field :name, as: :text
field :name, as: :text
...
```

- [ ]  ask the developer to choose the field used on the form, something like this:

```ruby
...
field :name, as: :text, use_this_one_on_forms: true
field :name, as: :text
...
```
Re-name need for `use_this_one_on_forms`...

**Comment by adrianthedev** [comment]
Hey @MrJoy.

I see how that can be annoying. Unfortunately, we don't have the capacity to add that right now.
We're delighted to review and merge a PR (and help guide you through the codebase if needed) for that.

**Comment by adrianthedev** [comment]
Closing for now but feel free to reopen if you start work or have other questions.
