### ISSUE TITLE
Broken standalone actions 

### ISSUE THREAD

**Issue by veelenga** [avo-hq/avo#1225]
### Describe the bug

Avo v2.14.0 release introduces a regression and breaks standalone actions. No bug in v2.13.2 release.

### Steps to Reproduce

1. Create a standalone action
2. Attach an action to resource table without records
3. Select an action (click "Dummy action", see screen)

Reproducible in demo app: https://avodemo.herokuapp.com/avo/resources/fish

### System configuration
**Avo version**: 2.14.2

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [ ] Pro

### Screenshots

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3624712/189521083-da22de70-5d65-475c-8f46-c1c94705ee36.png">

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Thanks @veelenga. I labeled this as a bug. We have our hands quite full at the moment. We'll get on this as soon as possible. If this is of immediate interest to you, we appreciate PRs.

**Comment by veelenga** [comment]
Thanks, @adrianthedev. I noticed this is already fixed in https://github.com/avo-hq/avo/commit/4fccd6ad99779a9e98a4e0104498339d8c94c5e0
