### ISSUE TITLE
Is there a way to create a date filter?

### ISSUE THREAD

**Issue by rajaravivarma-r** [avo-hq/avo#1226]
### Feature
We would like to filter items created in a date range. I've gone through the docs and issues but couldn't find a way to achieve this. Is there a way to create a date range or date filter?

### Current workarounds
Probably create a TextFilter and parse that as date time to achieve this.

#### Date picker
![date-component](https://user-images.githubusercontent.com/1841235/189598919-41abbaa6-7cd7-4f48-952b-9834bee7f0aa.png)

#### Date range picker
![unnamed](https://user-images.githubusercontent.com/1841235/189598982-945bc91a-ab1f-4847-a11e-976cb3d8679f.png)

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r. There isn't a ways of doing that yet, but I see how that would be useful! Date ranges too.

We don't have that on our roadmap yet so if you want to put up a PR, I'd be happy to help you navigate the codebase.
Here's a similar PR from a contributor that added the text filter https://github.com/avo-hq/avo/pull/530

We'd like to add this type of filtering soon.
https://github.com/avo-hq/avo/issues/1154

**Comment by nicholaswellens** [comment]
I believe @OlexYakov has more insight on this! (he is on vacatio now though)

**Comment by rajaravivarma-r** [comment]
Hi @adrianthedev, I will think about creating a PR. Thanks for the pointer.

**Comment by rajaravivarma-r** [comment]
@nicholaswellens Ok. For the time being I'll see what I can do.

**Comment by OlexYakov** [comment]
@rajaravivarma-r as @nicholaswellens mentioned, I did create a date (and daterange) picker filter. I could create a PR (probably tomorrow) if you want.

**Comment by OlexYakov** [comment]
For now you can check this draft PR https://github.com/avo-hq/avo/pull/1229.
To create a filter, you would do something like:
```ruby
class CreatedAtFilter < Avo::Filters::DateTimeFilter
  self.name = "Created at filter"
  self.date_field = :created_at
end

```

**Comment by rajaravivarma-r** [comment]
@OlexYakov Thanks. I'll take a look.

**Comment by murpj238** [comment]
Hi @adrianthedev @OlexYakov, this has come up as a requirement multiple times for us recently. The PR has gone stale, is there any reason why it hasn't been merged in?

**Comment by adrianthedev** [comment]
Because it still requires some work. We'd love to get your help with this.

**Comment by tiffanynk** [comment]
Has there been an update on this issue?
