### ISSUE TITLE
Readonly trix fields are still editable

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1235]
### Describe the bug
If you have a trix field and set `readonly: true` on it, it sets the disabled attribute on the textarea input but this does not make the editor itself readonly.

According to this [github issue](https://github.com/basecamp/trix/issues/331) `trix_field_controller.js` needs to set `contenteditable=false` after loading, or another option might be to render the show version of the field when readonly is set.

### Steps to Reproduce
1. Add a trix field and set readonly on it, eg. `field :text, as: :trix, readonly: true`
2. Go to the edit form for that resource and find the field

### Expected behavior & Actual behavior
The trix editor shouldn't be editable. What happens right now is the field is editable but any changes are not saved (although this isn't obvious to the user as they can type in what they like and there is no error)

### System configuration
**Avo version**: 2.14.2

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Paul-Bob** [comment]
Hey, we are working to fix this issue. 

I think render the show version of the field should be the option...

`contenteditable=false` should work too but if there are 2 trix fields on the same page where only one is read-only it would disable both right?

**Comment by Paul-Bob** [comment]
Rendering the show view for the field on the edit:
![image](https://user-images.githubusercontent.com/69730720/190851258-f25e2251-e0c4-4c26-9faa-57cf020f5ca1.png)
![image](https://user-images.githubusercontent.com/69730720/190851266-126a6275-5dfe-42a1-9a9d-907f1a71890b.png)
