### ISSUE TITLE
How to handle database constraints errors without exposing the actual issue?

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1246]
### Context
When deleting a resource with FKs pointing to it, the presented error is not user friendly.

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots
![image](https://user-images.githubusercontent.com/575138/191290931-a208f52d-cad5-4375-92fc-8a86d7bc5831.png)

**Comment by OlexYakov** [comment]
IMO, this is not an Avo concern, but your apps. Usually, if the data is coming from the user and has DB constrictions, you should to rails validations too. Even if it seems like duplication, it serves different purposes.
[This article](https://thoughtbot.com/blog/validation-database-constraint-or-both) might help you.

**Comment by alansikora** [comment]
Alright, I will take a look and reopen the issue if needed!
