### ISSUE TITLE
Is it possible to send parameters to filters and actions?

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1247]
### Context
I'd like to have a way to send parameters to filters and actions, so I can work on generic actions and filters. Sometimes, when dealing with a lot of tables, building a filter/action for every table becomes way too time consuming and hurts `DRY`.

For example, something like this:

```ruby
action ExportToCsv, fields: [:name, :id]
```

```ruby
filter LikeFilter, fields: [:name, :description]
```

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Comment by adrianthedev** [comment]
No, it's not currently possible, but that's a great feature to have. Similar to what you can do with [cards](https://docs.avohq.io/2.0/dashboards.html#override-card-options-from-the-dashboard) right now. I'll add it to the roadmap.

Thanks for the recommendation.

**Comment by alansikora** [comment]
Is it possible to have a rough estimate on when we going to have this?

**Comment by adrianthedev** [comment]
Probably in a few weeks (6-8 weeks). We're trying to finish some work we already started working on.

**Comment by adrianthedev** [comment]
We are open to receiving PRs with this feature if you want to take a shot. I'm happy to help you navigate the codebase.

**Comment by alansikora** [comment]
Nice! I'd be very happy to help, but I've been quite busy lately. I will definitely try.
