### ISSUE TITLE
Is it possible to know the current context when running actions?

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1248]
### Context
I'd like to run actions in the current state, for example: if the action is ran in the edit view, I want to know what is being shown currently (or the filter/query being applied). Also, if I'm filtering using filters, I'd like to have that filter as well inside the action.

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Comment by adrianthedev** [comment]
We don't yet have a mechanism for that, but you have access to the params using `::Avo::App.params`, and then you can use something like [this](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/base_controller.rb#L323) to decode the filters param. Then, you can access what payload was sent and what query was applied.

Sorry it's not something more straightforward. If you do somehow make it simpler and you'd like to send in a PR, we'd love to support that.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.
