### ISSUE TITLE
Impossible to have recursive resources

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1250]
### Describe the bug
I'd like to represent a tree structure in Avo, for example you might have a Person model that has many child Persons, who can also have many child Persons. In avo I have a "Person" resource that has a "has many" field for it's children. That works great, except that when I click on a child Person in the has many field, avo re-renders the parent instead of showing me the child that I clicked on.

### Steps to Reproduce
I've reproduce the issue in [this repository](https://github.com/iainbeeston/avo-recursive-resources), but basically you need a resource with a has many field for the same resource (in a tree structure), trying to view or edit any child resource will simply re-render the parent.

### Expected behavior & Actual behavior

I'd expect that it should render the child resource, and it should be possible to click through the hierarchy in avo.

### System configuration
**Avo version**: 2.15.2

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots

This video shows the problem using the [the bug repository I made](https://github.com/iainbeeston/avo-recursive-resources)

https://user-images.githubusercontent.com/111963/191810924-f6187aaa-01d4-4241-a25a-375daccc107c.mov

### Additional context

Looking into the code for avo, the problem seems to occur in the show action of the base controller. When the controller action starts, it correctly loads the child model and hydrates a resource for it. Next avo tries to load the "via" resource (the parent) so it can be shown in the breadcrumbs (see [here](https://github.com/avo-hq/avo/blob/ad21797b3fa28ffd3baa15b95698e5b8a2b009e1/app/controllers/avo/base_controller.rb#L87). it calls `Avo::App.get_resource_by_model_name`, which looks to find the resource in `Avo::App.valid_resources`. Looking at this at runtime, the resource returned by `get_resource_by_model_name` is the child resource that was created a few lines before. This is then hydrated using the parent model, overwriting it.

I would have expected that it should create a new resource for the via association every time?

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by iainbeeston** [comment]
@adrianthedev This has fixed the immediate issue but now I'm finding something strange, and I'm not sure if it is related or a new issue. When I view a recursive resource, the `has_many :children` field always shows the children of the "via" resource (ie the parent) not the model I'm currently looking at. You can see that in the [sample app](https://github.com/iainbeeston/avo-recursive-resources) that I linked to above, which I've updated to use avo/main.

**Comment by iainbeeston** [comment]
You can see what I mean in this video (note that if there is a "via" resource parameter the has-many field does not change, but if I click back up to the index view and click in again, it does change)

https://user-images.githubusercontent.com/111963/192755203-bfdf1012-b8e1-456b-a3a1-b5fde7e54318.mov

**Comment by adrianthedev** [comment]
Ok. I see it. looking into it.

**Comment by adrianthedev** [comment]
@iainbeeston please try the `main` branch. I think I fixed it. There's a recording on the PR 👆

**Comment by iainbeeston** [comment]
@adrianthedev That works perfectly, thank you! 🙇

**Comment by adrianthedev** [comment]
Anytime man! Thanks for the help with the reproducible repo and for being an awesome community member. I love your "let's get sh*t done" attitude.

**Comment by iainbeeston** [comment]
Sorry I can’t help more! I’d love to make pull requests but I don’t always understand what the code is doing (I’m not sure I can explain why that is!)
