### ISSUE TITLE
Edit page hangs when deployed but works fine locally

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1258]
### Describe the bug
When editing a specific resource, the page hangs when deployed, but works perfectly fine locally.

### Steps to Reproduce
Deploy the app, edit the resource.

### Models and resource files
```ruby
class ProductResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.search_query = -> do
    scope.ransack(id_eq: params[:q], m: "or", name_cont: params[:q], ean_cont: params[:q]).result(distinct: false)
  end

  field :id, as: :id
  field :name, as: :text
  field :ean, as: :text
  field :company, as: :belongs_to, searchable: true
  field :product, as: :belongs_to, searchable: true

  tabs do
    field :products, as: :has_many
    field :product_measure_conversions, as: :has_many
    field :product_parameters, as: :has_many
    field :product_prices, as: :has_many
  end

  action ExportToCsv
end
```

```ruby
class Product < ApplicationRecord
  self.table_name = "colecta.product"
  self.primary_key = "id"

  alias_attribute :owner_id, :id_product_owner
  alias_attribute :parent_id, :id_product_ref
  alias_attribute :name, :product_name

  belongs_to :company, :foreign_key => :id_product_owner
  belongs_to :product, :foreign_key => :id_product_ref, :optional => true

  has_many :products, :foreign_key => :id_product_ref
  has_many :product_measure_conversions, :foreign_key => :id_product
  has_many :product_parameters, :foreign_key => :id_product
  has_many :product_prices, :foreign_key => :id_product
end
```

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots
https://user-images.githubusercontent.com/575138/192631857-11647110-091a-49d2-8ac4-34f64deb1607.mp4

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
I suspect the searchable belongs_to to be the culprit again. Can you check and see that the license and lincese key are properly set in the production env?

Go to /avo/avo_private/debug and check the license.

**Comment by alansikora** [comment]
For some reason the client still did not purchase it. I'm sorry about that, I thought it was all good.

Just asked him to make sure to purchase it ASAP.

**Comment by adrianthedev** [comment]
No worries. The way I always looked at it is that the developer would purchase the license and transfer/bill it to the customer. But that works too ✌️
