### ISSUE TITLE
When editing a resource on a deployed env, the list does not update

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1259]
### Describe the bug
When editing a resource on a deployed env, the list does not update.

### Steps to Reproduce
Edit a resource, list the resource.

### Models and resource files
```ruby
class CompanyResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.search_query = -> do
    scope.ransack(id_eq: params[:q], m: "or", name_cont: params[:q], identifier_cont: params[:q]).result(distinct: false)
  end

  field :id, as: :id
  field :name, as: :text
  field :identifier, as: :text
  field :company_type, as: :belongs_to, searchable: true

  action ExportToCsv
end
```

```ruby
class Company < ApplicationRecord
  self.table_name = "colecta.company"

  belongs_to :company_type, foreign_key: :id_company_type

  has_many :parameters, :foreign_key => :id_owner
end
```

### System configuration
**Avo version**: 2.15.3

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

### Screenshots

https://user-images.githubusercontent.com/575138/192633187-453fcb92-6ed0-4985-bc1c-a3ef17469437.mp4

#### Impact

 - [X] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [X] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Try and turn off the [index caching](https://docs.avohq.io/2.0/customization.html#cache-resources-on-the-index-view).

**Comment by alansikora** [comment]
It works when disabling index caching. Is it a bug?

**Comment by adrianthedev** [comment]
Does your model have the `updated_at` column? If not, then the `cache` helper in Rails might not know when to bust the cache.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.
