### ISSUE TITLE
Custom Resource Tool: Adding input wrapper styles

### ISSUE THREAD

**Issue by tiffanynk** [avo-hq/avo#1265]
### Feature
Add styles to generated custom resource tool for input wrappers like the existing `input_classes`. This would take care of spacing and alignment out of the box and it would match the main panel for a resource.

![main panel for resource](https://user-images.githubusercontent.com/63679192/192840913-f4e4ed84-72ed-417c-8ca3-296bc326365d.png)

### Current workarounds
I was able to inspect the main panel via Dev Tools and applied the same CSS and HTML structure to match:

code:
```
 <div class="relative flex flex-col md:flex-row md:items-center pb-2 md:pb-0 leading-tight min-h-14" style>
      <div class="h-full pt-4 md:pt-0 md:h-14 flex self-start items-center text-slate-800">
           <div class="md:w-64 px-6 md:px-6  w-48 flex uppercase font-semibold text-gray-500 text-sm">
                 <%= form.label :access_token %>
                  <span class="text-red-600 ml-1">*</span>
            </div>
     </div>
.....
</div>
```

### Screenshots

<img width="560" alt="My hack" src="https://user-images.githubusercontent.com/63679192/192841885-c7cd342a-0f99-44f7-992f-6fdd8b71e143.png">
This is what I was able to do by adding in the classes above.

**Comment by adrianthedev** [comment]
can you try out the `PanelComponent`? [Here](https://docs.avohq.io/2.0/native-components/avo-panel-component.html) are the docs for it and [one](https://github.com/avo-hq/avodemo/blob/main/app/views/avo/tools/custom_page.html.erb), [two](https://github.com/avo-hq/avodemo/blob/main/app/views/avo/resource_tools/_fish_information.html.erb) examples of usage.

Please let me know if this fixes the issue.

**Comment by tiffanynk** [comment]
@adrianthedev I am actually using the `PanelComponent`, and the code snippet above is what I nested inside the form that I had copied from the `_fish_information.html.erb` - which just looks like this:

![Screen Shot 2022-09-28 at 5 27 52 PM](https://user-images.githubusercontent.com/63679192/192911855-238638be-be8a-40d2-9b15-4e5f78c876bc.png)

I wanted to keep the default theming that comes with Avo and just make sure that the main panel and this resource tool matched in terms of spacing and alignment. I _think_ what I'm actually trying to do (after some digging around) is something you had mentioned in #1128 , but I'm not sure if that's quite done yet.

**Comment by adrianthedev** [comment]
You're right! #1128 should expose those fields in a much nicer way.
Please go ahead and create the form unstyled and I'll make sure they are ready for production in the next release. 
I'll have a pre-release for you to try out today.

**Comment by adrianthedev** [comment]
Hey @tiffanynk. Please try out [`2.16.1.pre.1.nativefields`](https://rubygems.org/gems/avo/versions/2.16.1.pre.1.nativefields) and let me know how that goes.
Check out [this](https://github.com/avo-hq/avo/pull/1138/files#diff-b618e6775e9b8655b6fcfdec518b6449164c10db11d4be8b46f87b05bdb8e032R1) sample on how I use it.

The API is still not final, but should get you a long way.

**Comment by tiffanynk** [comment]
That works out, thanks for pointing me the this direction!

**Comment by adrianthedev** [comment]
Cool. Please send any feedback or ideas [here](https://github.com/avo-hq/avo/discussions/1273). Thank you!
