### ISSUE TITLE
Use a background behind uploaded images

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1268]
### Feature

I have a lot of images that are white with a transparent background. Unfortunately because the page background in avo is white, these are invisible once uploaded.

### Current workarounds

?

### Screenshots

![Screenshot 2022-09-29 at 16 49 16](https://user-images.githubusercontent.com/111963/193078818-99795556-80c1-4595-b819-64c15376b3c2.jpg)
![Screenshot 2022-09-29 at 16 49 27](https://user-images.githubusercontent.com/111963/193078821-e8b3bfc2-7708-4518-9e0f-1da6d24afd07.jpg)

### Additional context

I think it should be easy to fix this by adding `bg-application rounded-xl` (or possibly a darker background color?) to the div that surrounds the images, but I'm not sure if this would fit in with your intended styles. If the image isn't transparent then it should cover this background colour completely.

**Comment by adrianthedev** [comment]
@iainbeeston can you give https://github.com/avo-hq/avo/pull/1274 a try? In the PR I also added an example on how to add the background image to a grid item.
