### ISSUE TITLE
Locking gem to view-component 2.6 is blocking newer release from being bundled

### ISSUE THREAD

**Issue by msmiller** [avo-hq/avo#1270]
### Describe the bug

I'm trying to add Avo to an existing project which is running view-component v2.71.0. Problem is the current Avo is locked on view-component 2.6. Which means the best version of Avo that will run is 2.11. Sadly, that has the "Warning: You license is invalid ..." thing on all resource editors, making Avo essentially unusable for production. This issue doesn't happen with the current release of Avo. Problem is I don't want to downgrade the rest of our stack just to run Avo.

This isn't crucial as we can wait a little while to add Avo, but this issue is blocking us from committing to it.

### Steps to Reproduce
1. Set view-component to v. 2.7 in Gemfile
2. Have avo gem be open-ended in Gemfile
3. bundle and run bin/dev
4. Go to any resource page's editor or viewer
5. See warning

### Expected behavior & Actual behavior
Warning shouldn't appear on Community edition and doesn't when I back v-c to 2.6 and run the latest Avo.

### Models and resource files
Any resource will do it.

### System configuration
**Avo version**: 2.11

**Rails version**: 7.0.4

**Ruby version**: 3.0.3

**License type**:

 - [x] Community
 - [ ] Pro

### Screenshots
![Xnip2022-09-29_19-07-40](https://user-images.githubusercontent.com/98423/193174730-e6185481-b3a9-49c4-90b0-36ba60d2b00e.jpg)

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Got it. I'll release the view component dependency. There was an issue at one point with one version of view component.
