### ISSUE TITLE
Avo's Rails dependency is overly broad.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1278]
### Context

I would like to re-raise the issue of Avo dependencies first brought up in #540.

To answer the question you asked and didn't get a response to:

What you would want to do is remove `spec.add_dependency "rails"...` and instead add `spec.add_dependency "activerecord" ...`, etc.

For situations where a single feature (or a small number of features) depends on components of Rails, you could break the feature out into a separate gem that depends on avo and the relevant Rails component.  Like, for example, rich text fields are of zero value to me at my day job so having Avo drag `actiontext` into my environment is overhead that I'd prefer to avoid.  Similarly, we don't have any need of `actionmailbox`, `actioncable` (and by extension, `websocket-driver`, and `websocket-extensions`), or `activestorage` (and by extension, `image_processing` and `mini_magick`).

To make things seamless for existing users, you could migrate most code into an `avo-core` gem, and make the `avo` gem be an umbrella that brings everything in -- like how the `rails` gem is just a placeholder that does nothing but bring in all the components of Rails.

I'm looking at trying Avo for my day job, right now which is why this issue came up.  I've been trying to keep our deploys light and more readily auditable.  I've worked pretty hard to prune down our dependencies as much as possible and Avo undoes a fair bit of that effort right now.  It's probably not a deal-breaker, although I won't know for sure until I see how much the extra gems add to AMI build times.  (Only one seems to have a native extension, and it's trivial, so I don't anticipate this being a huge issue -- but these kinds of things do add up eventually.)

### System configuration
**Avo version**: 2.16.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type** (Community or Pro): Community, at present.  Possibly Pro in the near future, if all goes well.

**Comment by adrianthedev** [comment]
I see what you mean and understand your concern in the long run. I'll make sure we trim the dependencies in the next couple of releases.

Thanks for raising this issue.

**Comment by adrianthedev** [comment]
Hey @MrJoy, maybe you could help. 

After a preliminary scan, I think Avo needs only these railties for the base scenario.

```ruby
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"
```

How would I go to install only those? As far as I can see, when trying to install a "barebones" rails app (`rails new barebones --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-record --skip-active-job --skip-active-storage --skip-action-cable`), we still get `gem "rails", "~> 7.0.4"` in the gemfile, but just different `require` statements in the `application.rb` (`require` each railtie instead of `require rails/all`).
And that's something you control in your app.

So, can you please advise on how would you proceed in this case?

**Comment by adrianthedev** [comment]
To make it clear, the dependency I'm missing is `action_controller`.

**Comment by adrianthedev** [comment]
Got it. `actionpack` is what I need. I'll keep you posted.

**Comment by MrJoy** [comment]
It looks like you'll also need a little conditional code here and there.  In particular, I was getting some errors related to `ActiveStorage` in `Avo::App#init`.  Not fatal, because you already guard that code, but it would be a bit cleaner to have an `if defined?(ActiveStorage)` check in there.

In our Gemfile, we manage the dependencies like so:

```ruby
RAILS_VERSION_SPECIFIER = ["~> 7.0.3"].freeze
# gem "actioncable", *RAILS_VERSION_SPECIFIER
# gem "actionmailbox", *RAILS_VERSION_SPECIFIER
gem "actionmailer", *RAILS_VERSION_SPECIFIER
gem "actionpack", *RAILS_VERSION_SPECIFIER
# gem "actiontext", *RAILS_VERSION_SPECIFIER
gem "actionview", *RAILS_VERSION_SPECIFIER
# gem "activejob", *RAILS_VERSION_SPECIFIER
gem "activemodel", *RAILS_VERSION_SPECIFIER
gem "activerecord", *RAILS_VERSION_SPECIFIER
# gem "activestorage", *RAILS_VERSION_SPECIFIER
gem "activesupport", *RAILS_VERSION_SPECIFIER
gem "railties", *RAILS_VERSION_SPECIFIER
```

**Comment by adrianthedev** [comment]
Hey @MrJoy, I posted [a comment](https://github.com/avo-hq/avo/pull/1280#issuecomment-1264322363) on the PR with the issue I'm running into at the moment. Maybe you have some idea on how to solve it.
I think it's pretty easy to replicate it on your local machine. `git clone` and `bundle install` should do it. Then run `rails server` to start the app and see the error.

**Comment by MrJoy** [comment]
Will take a look!

**Comment by MrJoy** [comment]
You're also going to have some issues with the environment configs, initializers, and boilerplate code in the dummy app.  E.G. mailer base class, asset configuration, etc.  For the most part you should be able to just strip that out and go.

I'm tracking down an issue with ActionMailer and Devise right now...

**Comment by MrJoy** [comment]
```
      WebMock::NetConnectNotAllowedError:
        Real HTTP connections are disabled. Unregistered request: POST https://avohq.io/api/v1/licenses/check with body '{"license":"pro","license_key":null,"avo_version":"2.16.0","rails_version":"6.1.6.1","ruby_version":"3.0.3","environment":"test","ip":"127.0.0.1","host":"www.example.com","port":80,"app_name":"AvoDummy"}' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/json', 'User-Agent'=>'Ruby'}

        You can stub this request with the following snippet:

        stub_request(:post, "https://avohq.io/api/v1/licenses/check").
          with(
            body: "{\"license\":\"pro\",\"license_key\":null,\"avo_version\":\"2.16.0\",\"rails_version\":\"6.1.6.1\",\"ruby_version\":\"3.0.3\",\"environment\":\"test\",\"ip\":\"127.0.0.1\",\"host\":\"www.example.com\",\"port\":80,\"app_name\":\"AvoDummy\"}",
            headers: {
        	  'Accept'=>'*/*',
        	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
        	  'Content-Type'=>'application/json',
        	  'User-Agent'=>'Ruby'
            }).
          to_return(status: 200, body: "", headers: {})

        registered request stubs:

        stub_request(:post, "https://avohq.io/api/v1/licenses/check").
          with(
            body: hash_including({"license"=>"pro", "license_key"=>"license_123"}))
```

I think I'm past the point of code loading issues, and running into other issues that are unrelated such as this.  (Also, dummy app's schema.rb seems to be out of date.)

Will submit a PR to your PR.

**Comment by MrJoy** [comment]
Ah, schema.rb might be me.  I may have already had a `dummy` DB.
