### ISSUE TITLE
Suggested alternative approach to license management.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1279]
### Context

Looking at the Avo code, it looks like Avo phones home periodically to check its license.  Fundamentally, that means that (assuming I get a Pro license) the uptime of my admin system is dependent upon your license server's uptime.

That is something of a deal-breaker for my current organization, unfortunately.

I'd suggest you try the strategy Mike Perham uses with Sidekiq Pro:  Run a gem server that uses authentication.

Basically, when using Sidekiq Pro, you wind up adding this to your project Gemfile:

```ruby
source "https://gems.contribsys.com/" do
  gem "sidekiq-pro", "~> 5.5.1"
end
```

Developers run a command like this on their workstation (and CI does the same during image builds):

```bash
bundle config --local gems.contribsys.com <some_value>:<some_value>
```

And voila!  License checks happen when Bundler is looking for updates / installing things, rather than at runtime.  An Avo outage thus cannot become a problem for my uptime.

### System configuration
**Avo version**: N/A

**Rails version**: N/A

**Ruby version**: N/A

**License type** (Community or Pro): Pro

**Comment by adrianthedev** [comment]
Hey @mrjoy, thanks for writing!

I understand this is a concern and I'm constantly thinking on how to improve this process. 
I know this isn't ideal but I chose to have a "less than ideal" distribution strategy in order to deliver more functionality to the users and validate the need for this project. 

I see now that there is a need and I can go back to these features/mechanisms that I made as a "first-iteration" and improve them. 

My understanding on the distribution system of sidekiq pro, is that there are essentially two gems. And you install one or another. Is that right?

**Comment by MrJoy** [comment]
There's the base SideKiq gem, and the there's the Pro and Enterprise gems.  You install the base gem in all cases, and the Pro / Enterprise gem as appropriate to your license.  They layer the additional functionality on top of the base SideKiq gem using whatever hooks/mechanisms it provides.

**Comment by MrJoy** [comment]
Whoops, I'm wrong.  It looks like you just load the pro or enterprise gem as needed instead of loading the base one.  Not sure where I got the idea both were used.

**Comment by MrJoy** [comment]
Ah!  I see.  `sidekiq-pro` explicitly depends on `sidekiq`, which is why I commented out my `gem "sidekiq"` statement.  So I was right the first time that the Pro / Enteprise gems builds on top of the base one.

**Comment by adrianthedev** [comment]
Yes, so the licensing happens on bundle-time by actually giving you the gem if the license is valid and not giving the gem if the license is invalid.
So there are two different gems `sidekiq` and `sidekiq-pro`.

We don't yet have this in place right now. We're focusing more on building the features you need.

We plan on breaking things apart in the near future.

Regarding the licensing server uptime, we pushed some changes in the latest Avo version that will keep Avo running even if our licensing server is down or the connection broke somehow. We put that in place to make sure you and your users have a more stable experience.

**Comment by adrianthedev** [comment]
Closing for now, but I'm open to alternatives. I want to make this a better experience all-round.

**Comment by MrJoy** [comment]
The server going down is not the only failure mode.

* Depending on how you're scheduling requests, a very slow response from the server could result in things backlogging.  
* An unexpectedly large response from the server (say, due to a bug) could result in greater than expected resource usage.
* A bug that incorrectly results in a negative response from the server would impair our service.

It's up to you to prioritize things as you see fit, but just as a data point:  This issue remains the highest priority -- and a showstopper -- for my organization.

**Comment by adrianthedev** [comment]
Hey @MrJoy. The license-checking mechanism covers most of those cases, but I understand your concern.

If your organization requires special builds with the telemetry removed, we can cover that under a special license.

Please [get in touch](https://calendly.com/adrianthedev) with me over a video call to make that happen.

**Comment by MrJoy** [comment]
@adrianthedev I appreciate the flexibility.  I'll proceed with our test spike (converting a subset of functionality from ActiveAdmin over to Avo), and if things line up well, I'll schedule that discussion.
