### ISSUE TITLE
Wrong policy is applied in AssociationsController

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1283]
FYI I just noticed that in 'has_many' frames, some resources wouldn't show up.

After digging a little, it turns out that Avo would keep using the `parent_resource` policy scope instead of the policy of the actual resource, and thus disregard any custom policy present in the current resource.

I already solved the bug, but am working on a batch of fixes related to `use_resource` options. Will push a PR soon :)

**Comment by adrianthedev** [comment]
Got it. Thanks for reporting and for the PR!

**Comment by adrianthedev** [comment]
I think this has been fixed in https://github.com/avo-hq/avo/pull/1300.
