### ISSUE TITLE
Multiple resources for one model not working as expected

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1284]
### Describe the bug

I am trying to create multiple resources for the same model class (essentially two views on the same model, to be used in different contexts), and instead of appearing as separate resources as expected, they are appearing as duplicates in the `all_resources` menu. I was trying to follow https://docs.avohq.io/2.0/resources.html#use-multiple-resources-for-the-same-model but it didn't seem to cover the scenario I am looking at. I am not sure whether this is a bug or a new feature.

### Steps to Reproduce
1. Create a separate resource for an existing resource with the same model_class
2. Observe the duplication in the menu

### Expected behavior & Actual behavior

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/245867/193975994-708b4593-07ea-478c-889c-95d37eec1fdd.png">

### Models and resource files

Example commit on example project 

https://github.com/avo-hq/avodemo/commit/d24681896c3a176152c361794ce0e233584cec8a

### System configuration
**Avo version**: 2.15

**Rails version**: 3.1.2

**Ruby version**:

**License type**:

 - [ ] Community
 - [X] Pro

#### Impact

 - [ ] High impact
 - [X] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [X] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yup @coffenbacher. Definitely a bug. Thanks for reporting. I'll have it fixed in the next release. Could you try out the [menu editor](https://docs.avohq.io/2.0/menu-editor.html) feature? Manually building the menu would enable you to go around this bug until the next release.

**Comment by adrianthedev** [comment]
BTW, thanks for the reproduction. It helped me pinpoint the issue really fast

**Comment by coffenbacher** [comment]
Awesome, thanks for the quick fix, as always!!
