### ISSUE TITLE
Dynamic datetime field

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1288]
### Feature

Our clients/users all work and think in their own timezones, so an option to dynamically set the timezone of the datetime field based on a different value in the resource would be amazing. 

So for example, we will constantly need to respond to things like "Hey, can you look at the event at 3pm and ...." or "I'm missing an event at 10am, can you see if you can find it?" and when we are working out of our local timezone, none of the schedules make much sense without mental gymnastics.

For example something like:

```rb
  field :event_at,
        name: 'Event at (local time)',
        as: :date_time,
        timezone: ->(model: model, resource: resource, view: view, field: field) do
            resource.user_timezone
        end
```

### Current workarounds

Probably a way to do it through a custom field! We can also do mental calculations in our head based off of our own timezone for now, although this is very taxing. We can also change our own user-wide timezone temporarily.

**Comment by adrianthedev** [comment]
Hey @coffenbacher. Avo should automatically read the browser's timezone and convert the value to that. There might be edge cases where that isn't working, so I see what you mean about a dynamic setting.

We have a `timezone` setting, but that's static, and doesn't take in a block.
Would you be comfortable with opening a PR and adding this feature? You can look at [this](https://github.com/avo-hq/avo/pull/955) PR, where I made the `required` option a callable block. A similar conversion should be done here too.

I'll mark this PR as a [hacktoberfest](https://hacktoberfest.com/) PR and you'll be closer to achieving that too.

I'm happy to help you more with navigating the code.

Thank you 🙏

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if you have new info.
