### ISSUE TITLE
Time field or `noCalendar` option for date_time

### ISSUE THREAD

**Issue by sarahlafer** [avo-hq/avo#1289]
### Context

Hi Avo team! 👋 

We are creating an event resource on Avo with a field which should allow us to change the **time** of an event. For this we are using `as: :date_time` like in [this part](https://docs.avohq.io/2.0/fields/date_time.html) of the docs.
This gives us a flatpickr calendar with the date and time as well.

However, we would like to **not display the calendar** and only show the time picker (the date doesn't matter and could be today's date by default), to have a display like this 👇 
<img width="350" alt="Screenshot 2022-10-06 at 13 21 29" src="https://user-images.githubusercontent.com/28513469/194300435-991c1a0e-e20a-4e68-a8a9-f13b689a7ee3.png">

### Possible solution

Flatpickr offers [the option](https://flatpickr.js.org/examples/#:~:text=2016%2D10%2D20-,Time%20Picker,-%23) but we saw that it is not possible to pass the `noCalendar` value inside the [date_field_controller.js](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers/fields/date_field_controller.js#L13-L22).

Is there any other way to just show the time or would it be possible to add this option? (Also happy to contribute) 

Thank you for your help! 🙌

**Comment by adrianthedev** [comment]
Hey @sarahlafer. Welcome 👋
Would you be comfortable opening a PR and creating a new type of field called `time`?
It would do essentially what you said, open up a flatpickr instance with only the time enabled.

I would start the PR by:

- adding a migration with a new field on a model (maybe `starting_at` on `Course`?)
- creating a new Avo field file like [this one](https://github.com/avo-hq/avo/blob/main/lib/avo/fields/date_time_field.rb)
- copying over the component files from [here](https://github.com/avo-hq/avo/tree/main/app/components/avo/fields/date_time_field)
- and then, add a conditional and tweak the format a bit in [this](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers/fields/date_field_controller.js) Stimulus JS file

This Stimulus JS part is a bit gnarly (we should refactor it a bit), but we try to keep things as standard as possible.
One thing to keep in mind is that we send the dates/times over in the UTC format and then converting them to the browser's timezone. Not sure if this is required for this field. Probably not?

I'm happy to answer any other questions regarding this PR/feature.
Thanks for using Avo!

**Comment by sarahlafer** [comment]
Hi @adrianthedev, thanks for the quick reply!

It would be great to contribute and add a `time` field! I'll look into it asap and let you know if I'm stuck :)

**Comment by adrianthedev** [comment]
Awesome! 🏄‍♀️
