### ISSUE TITLE
Failed to use avo with rails 7 api mode

### ISSUE THREAD

**Issue by thiagovsk** [avo-hq/avo#1292]
### Context
Hi guys, I started to use avo today, I have a simple rails application with API mode and I tried to use avo, but I have a problem with rails assets:

```
ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/railtie/configuration.rb:96:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration
(NoMethodError)
Did you mean?  asset_host
```

### System configuration
**Avo version**:  2.16.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type** (Community or Pro): Community

### Steps to reproduce

rails new my_api --api
rails app:template LOCATION='https://avohq.io/app-template'

after that, just run the rails server and access localhost:3000/avo

am I doing something wrong? 

Thanks for helping 👏

**Comment by adrianthedev** [comment]
Hey @thiagovsk. Avo will probably not work in api_mode. It needs features like views and route helpers that api_mode strips away. 
It's all documented [here](https://docs.avohq.io/2.0/recipes/api-only-app.html#use-avo-in-an-api-only-rails-app). 
You are better off using Rails the regular way.

**Comment by thiagovsk** [comment]
> Hey @thiagovsk. Avo will probably not work in api_mode. It needs features like views and route helpers that api_mode strips away. It's all documented [here](https://docs.avohq.io/2.0/recipes/api-only-app.html#use-avo-in-an-api-only-rails-app). You are better off using Rails the regular way.

@adrianthedev thanks for the explanation, I'll try to change my API rails app to a regular app
