### ISSUE TITLE
Easy way to get routes in actions

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1301]
### Feature

It feels like many actions will need to redirect to another page in avo but it's not clear how to do it. The documentation has an example but the url is hard coded. Links to the main app are simpler (`main_app.routes.url_helpers.route_method`) but I'm not sure how to get an avo route. I think ideally avo route helpers would be available inside an action, like they are in a controller?

### Current workarounds

At the moment I'm using this rather ugly workaround:

```
resource = ::Avo::App.get_resource_by_model_name(klazz)
redirect_to resource.resource_path(resource: resource, model: model)
```

**Comment by adrianthedev** [comment]
Avo is an engine, so all route helpers should be prepended with the engine name. Rails is an engine as well.
So for all routes that you have in your own app (`config/routes.rb`) you should add the `main_app` engine name.
For All Avo routes you should reference the `avo` helper.

Examples: 

For your app:

 - `https://YOUR_APP.com/contact` -> `main_app.contact_path`
 - `https://YOUR_APP.com/orders/55` -> `main_app.orders_path(55)`

For Avo paths:

 - `https://YOUR_APP.com/avo/resources/users/3` -> `avo.resources_user_path(3)`
 - `https://YOUR_APP.com/avo/dashboards/dashy` -> `avo.dashboard_path(:dashy)`

I wrote more about this in [this guide](https://docs.avohq.io/2.0/faq.html#why-don-t-regular-url-helpers-work-as-expected) (which I'll probably promote to a full page somewhere in the docs) explaining this behavior.

Does this answer your question?

**Comment by iainbeeston** [comment]
Yes that’s very helpful, thank you! I’ve raised [this PR](https://github.com/avo-hq/vitepress-docs/pull/8) on the docs to show how to use the route helpers in actions.

**Comment by adrianthedev** [comment]
🙌 Perfect. Thanks!
