### ISSUE TITLE
Show actions outside the menu - alongside create and edit

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1302]
### Feature

As far as I can tell actions always have to appear inside the actions dropdown menu. Sometimes if there's a really commonly used action it would be great to be able to make it appear as a button like the standard avo CRUD actions.

### Current workarounds

Not that I'm aware of?

**Comment by adrianthedev** [comment]
Hey @iainbeeston. For the Show view, you can [fully customize the controls](https://docs.avohq.io/2.0/customizable-controls.html#show-page).
Is this what you are looking for?

We haven't yet added all the other views because we wanted to see if it's something that customers really used.

**Comment by adrianthedev** [comment]
The controls API is quite flexible to recreate the default layout and add your own actions.

Yeah, that could be a way too. I'm a bit worried about the complexity of it all. That would mean adding another way of doing the same thing.

**Comment by adrianthedev** [comment]
I'm going to be honest and say we're not going to support that in the near future. 
I'm not saying that we won't in the future. We already have a way of supporting this use-case.

**Comment by iainbeeston** [comment]
I think that's fair, I'll look into using the controls instead 👍
