### ISSUE TITLE
Acts_as_list resource controller override.

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1313]
### Context
I'm using acts_as_list in my app and I'm trying to override the index method in avo so I don't have to use a default scope. For some reason this isn't working. What do I need to overrride to get change the order of the model?

```ruby
class Avo::CategoriesController < Avo::ResourcesController
  def index
    super
    resource.model_class.by_position
  end
end
```

### System configuration
**Avo version**: 2.17.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

**Comment by adrianthedev** [comment]
I think [`resolve_query_scope`](https://docs.avohq.io/2.0/customization.html#custom-query-scopes) is what you're looking for. This way you can access that scope and update it based on your needs.

There's [this way](https://docs.avohq.io/2.0/resources.html#unscoped-queries-on-index) of avoiding the default scope.

**Comment by jmarsh24** [comment]
That worked. It might be nice to update the acts_as_list documentation with this information instead of using a default scope as this can cause some issues down the line as you start combining scopes.

**Comment by adrianthedev** [comment]
[Done](https://docs.avohq.io/2.0/records-reordering.html)! Thanks!
