### ISSUE TITLE
Typo on Release Notes

### ISSUE THREAD

**Issue by tiffanynk** [avo-hq/avo#1315]
### Describe the bug
In the upgrade guide for [2.16 -> 2.17](https://docs.avohq.io/2.0/upgrade.html#upgrade-from-2-16-to-2-17), there is a typo with updating the custom field wrapper.

```
- <%= edit_field_wrapper field: @field, index: @index, form: @form, resource: @resource, displayed_in_modal: @displayed_in_modal do %>
+ <%= field_wrapper **field_wrapper_tags do %>
```

`field_wrapper_tags` should be `field_wrapper_args`. It would also be helpful to note that instead of `@field`, we will need to access the field with `field` only.

**Comment by adrianthedev** [comment]
Thank you. It's fixed now.
