### ISSUE TITLE
adding index view scopes

### ISSUE THREAD

**Issue by holden** [avo-hq/avo#1317]
Forgive me if for some reason I overlooked this feature but it would be great to have scoped filters as buttons on the index view.

ActiveAdmin calls these index scopes https://activeadmin.info/3-index-pages.html, and it just makes it easier when you have an index with a lot of information on it to tab between "all, completed, upcoming, etc." I know you can accomplish this with filters on the right but it's not as pleasant a UI experience as being able to show them as tabs or buttons with maybe even the feature to show the size of the scope.

Hope that makes sense.

## Stripe example

<img width="499" alt="CleanShot 2022-10-17 at 12 05 52@2x" src="https://user-images.githubusercontent.com/48241/196150554-9b788422-e94d-441d-8236-da1b7f737150.png">

## ActiveAdmin example

![CleanShot 2022-10-17 at 12 06 13@2x](https://user-images.githubusercontent.com/48241/196150742-9ab6903f-c1f7-43d2-a84b-7636182a3315.png)

**Comment by adrianthedev** [comment]
Hey @holden. That's definitely a useful feature. Thank you for writing. 

I added [it](https://github.com/avo-hq/avo/issues/1318) to [the roadmap](https://github.com/orgs/avo-hq/projects/3/views/1).
I don't yet have a more exact time when we'll release this. We're already designing Avo v3.0, and we might add it then.
