### ISSUE TITLE
Can’t change the label of actions menu

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1330]
### Describe the bug

I’d like to change the label of the actions drop-down menu, when using show_controls. I’d like to have different action menus with different labels for different kinds of actions. The documentation says that the action menu accepts label and title options but neither of these seem to work for me.

### Steps to Reproduce
1. Add this code to a resource:

```ruby
self.show_controls = -> do
  actions_list label: “Do Stuff”
  edit_button label: “Testing”
end
```

2. View the resource in the browser

### Expected behavior & Actual behavior

I’d expect that the edit button has the text “Testing” and the actions menu has the text “Do Stuff”, but although the edit button text is correct the actions menu still says “Actions”.

### System configuration
**Avo version**: 2.17.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hmmm, yes. It seems that the value is [hardcoded](https://github.com/avo-hq/avo/blob/main/app/components/avo/actions_component.html.erb#L14). Are you participating in [hacktoberfest](https://hacktoberfest.com/)? Are you available for a PR?
If not, maybe I can have a look towards the end of the week.

**Comment by iainbeeston** [comment]
No, I’m afraid I don’t have time outside work and or at work right now 🙁 If you could fix it that would be great!
