### ISSUE TITLE
URL "type"

### ISSUE THREAD

**Issue by jpalley** [avo-hq/avo#1336]
### Context
I've got a field that holds a url (it's validated with validate_url gem). I'm using "format_using" 

`format_using: ->(value) { "<a href='#{value}' target='_new'>#{value}</a>".html_safe } `

 to make the url clickable in the index/show views.  This works for index/show/edit.  But it doesn't work for new. For new, the text field is formatted with the "format_using" html as generated above. I'd like for it to just be blank.

I'm not clear why the new and edit are behaving differently.  Am I doing something wrong or is this a bug?

### System configuration
**Avo version**: 2

**Rails version**: 7

**Ruby version**: 3.1

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

**Comment by adrianthedev** [comment]
You have access to the `view` object inside the block. Can you do `format_using: ->(value) { "<a href='#{value}' target='_new'>#{value}</a>".html_safe if view != :new }`

Closing for now. Feel free to reopen it if it's still an issue.
