### ISSUE TITLE
Cannot remove uploaded files

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1337]
### Describe the bug

Whenever I try to delete any attached file from a resource, I hit a 404 error. I've been able to reproduce the error in a demo app [here](https://github.com/iainbeeston/avo-delete-files)

### Steps to Reproduce

1. Check out https://github.com/iainbeeston/avo-delete-files (which has a single resource with a file field defined as `field :photo, as: :file`)
1. `bin/rails s`
2. Go to https://localhost:3000/avo
3. Create a person with a photo file
4. Delete the photo file

### Expected behavior & Actual behavior

This should remove the file and go back to the resource show page. Instead it hits a 404 page (it looks like the file is successfully removed though)

### Models and resource files

Here's the sample resource from my demo repo:

```ruby
class PersonResource < Avo::BaseResource
  self.title = :id
  self.includes = []

  field :id, as: :id
  field :name, as: :text
  field :photo, as: :file
end
```

### System configuration
**Avo version**: 2.1.7

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yes. There's a PR ready to be merged. It will be fixed by the next release.
