### ISSUE TITLE
Deleting attachment is broken?

### ISSUE THREAD

**Issue by mighani** [avo-hq/avo#1338]
### Describe the bug

I upload an attachment with active storage local service. On digital ocean service, it's the same behavior.
This works. But deleting the attachment does not. It deletes the attachment in the active_storage_attachments table but not in the active_storage_blobs. Also an error message occurs in the UI.

### Steps to Reproduce
1. Upload an attachment
2. Try to delete it

### Expected behavior & Actual behavior
The attachment should be deleted in both tables if using local service, and if used e.g., aws or digital ocean also on the remote bucket. The view should be redirected to the page where I clicked on the delete button.

### System configuration
**Avo version**: 2.17.0

**Rails version**:   7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**License type**:

 - [ ] Community
 - [ x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ x] No

### Screenshots or screen recordings
https://www.loom.com/share/f59c6dfe43074c5ba2123b7154ba843f

#### Impact

 - [x ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Fixed in https://github.com/avo-hq/avo/pull/1309

The attachment gets deleted but the redirect is broken.
It will be out in the next release.

Thanks for reporting🙏
