### ISSUE TITLE
Timestamps are rendered with UTC timezone.

### ISSUE THREAD

**Issue by rajaravivarma-r** [avo-hq/avo#1341]
### Describe the bug
Before upgrading to 2.17.1.pre.3, the timezone values were correctly set to `Asia/Kolkata`, now after the upgrade it show `UTC`, though I have made no changes except upgrade to this version.
The formatting string I use is `MMMM dd, y HH:mm z`

Is there a way to just have it format via Ruby, without having to create a custom field. Our app works only for users within India, at least for sometime, so it makes our life easier if we could format it on the backend.

One more issue we faced with moment js is, it rendered `Asia/Calcutta` for some users and `Asia/Kolkatta` for some users. Though, *Kolkatta* is the new name for *Calcutta*, I don't know why it renders *Calcutta* only for some users.

### Steps to Reproduce
1. Upgrade to versions 2.17.1.pre.3
2. Define a resource with `field :created_at, as: :date_time, sortable: true, format: ApplicationHelper::JS_DATETIME_FORMAT, only_on: :index`. Go to the resource page.
3. The timezone value marked by string `z` will be displayed as UTC.

### Expected behavior & Actual behavior
It should display `Asia/Kolkatta`. It displays `UTC`.

### Models and resource files
```ruby
class PurchaseResource < Avo::BaseResource
  self.title = :uuid
  field :created_at, as: :date_time, sortable: true, format: ApplicationHelper::JS_DATETIME_FORMAT, only_on: :index
end
```

### System configuration
**Avo version**: 2.17.1.pre.3

**Rails version**: 6.1.6.1

**Ruby version**: 3.0.0p0

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
<img width="1105" alt="AvoMomentJSProblem" src="https://user-images.githubusercontent.com/1841235/196993064-1b0765cb-1279-43e2-ab54-479ec7d5a37b.png">

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by rajaravivarma-r** [comment]
Hey @adrianthedev, sorry, the upgrade brought a bug. If. you can think of a quick fix for this, then it would be really helpful for us to go live with the upgrade, reverting the upgrade is not an option since we have put in a lot of work to make it work.

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r. Not sure from what version you upgraded from, but we changed the `format` option a while back. The formatting is being done in the browser to support the browser's timezone.
So you must use [luxon](https://moment.github.io/luxon/#/formatting?id=table-of-tokens)'s tokens to format it.

[Docs](https://docs.avohq.io/2.0/fields/date_time.html)

**Comment by rajaravivarma-r** [comment]
Ah! it is the same thing. The `z` in the format string (`MMMM dd, y HH:mm z`) should have displayed `Asia/Kolkata`, but instead it displays UTC.

**Comment by adrianthedev** [comment]
Hmmm, I don't get it now. Is the time value correct?

**Comment by rajaravivarma-r** [comment]
Yeah, it is the same code. I'll clear up the cookies and check.

**Comment by rajaravivarma-r** [comment]
I can confirm that it only happens with version `2.17.1.pre.3`. It works fine with `2.17.0`.

**Comment by adrianthedev** [comment]
Ok. And what values can you see in each version? Can you share one record in both versions please?

**Comment by rajaravivarma-r** [comment]
Here is the recording. It might seem like I'm upgrading from 2.16.0, but I tried with 2.17.0 as well, and the results are the same.

https://user-images.githubusercontent.com/1841235/197024644-ebe74678-efe7-4936-8a66-b3c29257c72f.mp4

**Comment by rajaravivarma-r** [comment]
That would be awesome.

**Comment by adrianthedev** [comment]
Cool. It will probably be up tomorrow, not tonight. Thanks for the recording

**Comment by rajaravivarma-r** [comment]
Okay!
