### ISSUE TITLE
Loading some has_many associations stuck in redirect

### ISSUE THREAD

**Issue by rajaravivarma-r** [avo-hq/avo#1342]
### Describe the bug
Loading some `has_many` associations gets stuck in a loop.

Let us say I have a `InvestorResource` which `has_many` `BankAccountResource`, then loading the `BankAccounts` gets stuck in  a loop of redirection.

Some of the has_many resources loads just fine, some doesn't.

### Expected behavior & Actual behavior
It should be loaded. It doesn't load.

### Models and resource files
`investor.rb`
```ruby
class Investor < OnbRecord
  has_many :bank_accounts, dependent: :restrict_with_exception
end
```
`bank_account.rb`
```ruby
class BankAccount < OnbRecord
  self.inheritance_column = nil
  belongs_to :investor
  belongs_to :bank_branch, foreign_key: :bank_branch_ifsc_code, primary_key: :ifsc_code
  has_many :bank_mandates

  delegate :name, to: :investor, prefix: 'investor'
end
```
`investor_resource.rb`
```ruby
class InvestorResource < Avo::BaseResource
  self.title = :name
  self.includes = %i[contact_detail kyc_identity_detail addresses bank_accounts]
  field :bank_mandates, as: :has_many, name: 'Mandates' # Loads fine
  field :bank_accounts, as: :has_many # Doesn't load fine
  field :investment_accounts, as: :has_many # Loads fine
end
```

`bank_account_resource.rb`
```ruby
class BankAccountResource < Avo::BaseResource
  self.title = :id
  self.includes = []
  self.record_selector = false

  field :id, as: :id
  field :account_holder_name, as: :text
  field :number, as: :text
  field :type, as: :text
end
```

### System configuration
**Avo version**: 2.17.1.pre.3

**Rails version**: 6.1.6.1

**Ruby version**: 3.0.0p0

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://user-images.githubusercontent.com/1841235/197030756-40d8490a-9c73-45f8-b8e4-b5e76318c675.mp4

### Additional context
It seems to be caused by a redirect. Here's the log,
```
Started GET "/sandbox/resources/investors/804/bank_accounts?turbo_frame=has_many_field_show_bank_accounts" for 127.0.0.1 at 2022-10-20 23:43:23 +0530
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
Processing by Avo::AssociationsController#index as HTML
  Parameters: {"turbo_frame"=>"has_many_field_show_bank_accounts", "resource_name"=>"investors", "id"=>"804", "related_name"=>"bank_accounts"}
  Tenant Load (0.5ms)  SELECT "tenants".* FROM "tenants" WHERE "tenants"."id" = $1 LIMIT $2  [["id", 22], ["LIMIT", 1]]
  ↳ config/initializers/avo_configuration.rb:17:in `block (2 levels) in <main>'
Unpermitted parameters: :turbo_frame, :resource_name, :related_name
  Investor Load (229.7ms)  SELECT "investors".* FROM "investors" WHERE "investors"."id" = $1 ORDER BY "investors"."created_at" DESC LIMIT $2  [["id", 804], ["LIMIT", 1]]
Redirected to http://localhost:3000/sandbox/resources/investors/804
Completed 302 Found in 851ms (ActiveRecord: 450.9ms | Allocations: 6179)
```

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Are you using an authorization policy for `Investor`? If yes, add this and see if that helps.
```ruby
def view_bank_accounts?
  true
end
```

**Comment by rajaravivarma-r** [comment]
I understood the problem. There is a `def view_bank_accounts? false end` in `ApplicationPolicy`, but I override that in `InvestorPolicy`.

If I return `true` from `ApplicationPolicy#view_bank_accounts?`, then it loads just fine. Do you know why the override didn't take preference?

**Comment by rajaravivarma-r** [comment]
I understood the problem. In the `authorize_if_defined` method, the `policy_class` is set to `BankAccountPolicy` rather than the parent model policy `InvestorPolicy`.
Since `BankAccountPolicy` inherits from `ApplicationPolicy`, it has `view_bank_accounts?` set to false, which triggers the `NotAuthorized` exception and subsequently the redirect.

Contrarily, the `get_items` in lib/avo/concerns/has_fields.rb:277 uses the `InvestorPolicy` to determine if it should be rendered.

I think the `view_bank_accounts?` should be checked on the `InvestorPolicy` rather than `BankAccountPolicy`.

**Comment by adrianthedev** [comment]
[I think there is a bug](https://github.com/avo-hq/avo/pull/1303) in the associations authorization.

[The PR](https://github.com/avo-hq/avo/pull/1300) that should fix it.

Try this [`2.17.1.pre.2.customauthorizationclients`](https://rubygems.org/gems/avo/versions/2.17.1.pre.2.customauthorizationclients) build and see if that fixes the `view_bank_accounts?` in the wrong policy issue.
This does not contain the fixes with date-time, but I can create a custom build afterwards.

**Comment by adrianthedev** [comment]
BTW, you arae right about _I think the view_bank_accounts? should be checked on the InvestorPolicy rather than BankAccountPolicy._

**Comment by rajaravivarma-r** [comment]
Sure. thanks for the prompt response. I'll check that.

**Comment by rajaravivarma-r** [comment]
Oops, I missed your statement about the `date-time` issue. I can't give up that fix. I'll do some kind of work around in our codebase for this fix, until a build is out.

**Comment by adrianthedev** [comment]
@rajaravivarma-r I can make a custom build for you to have both fixes. I just want you to test out this other build to see if it fixes this `view_bank_accounts?` issue.

So, to reiterate, if the `2.17.1.pre.2.customauthorizationclients` fixes the authorization issue, I'll merge it to the `date_time` branch to create a special build for you to work with.

**Comment by rajaravivarma-r** [comment]
Gotcha! I'll test that build.

**Comment by rajaravivarma-r** [comment]
@adrianthedev The build `2.17.1.pre.2.customauthorizationclients` fixes the problem and loads the has_many associations properly. But it breaks, if we have used `authorize(method)` in any custom controller inheriting from `Avo::ApplicationController`. I fixed it by adding `include Pundit::Authorization`.

Could you please make a build with the `Invalid DateTime` fix and `duplication autocomplete` fix on top of this?

**Comment by adrianthedev** [comment]
Great. I'll have that build by the end of the day after I fix the date-time issue better. Is that ok?

**Comment by rajaravivarma-r** [comment]
It would be nice If you could let a build out earlier so that I can move ahead with deploying the fixes. I wouldn't urge, if it didn't affect the users, which increases the load on our support team. Hope you understand.

**Comment by adrianthedev** [comment]
Ok let me try and push this faster.

**Comment by rajaravivarma-r** [comment]
That would be great. Thank you!

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r. Please try this build https://rubygems.org/gems/avo/versions/2.17.1.pre.4.issue.1342

**Comment by rajaravivarma-r** [comment]
Will update you in a short while.

**Comment by adrianthedev** [comment]
@rajaravivarma-r heads-up, there might still be a few bugs around the date-time field, which https://github.com/avo-hq/avo/pull/1344 should fix. I'm actively working on that.

**Comment by rajaravivarma-r** [comment]
Hi @adrianthedev, It works well and the bugs are fixed. Thanks you!

> heads-up, there might still be a few bugs around the date-time field, which https://github.com/avo-hq/avo/pull/1344 should fix. I'm actively working on that.
Gotcha! I'll have a user code work around for this as a temporary fix.
