### ISSUE TITLE
Visibility of fields under tabs not working as intended

### ISSUE THREAD

**Issue by nicholaswellens** [avo-hq/avo#1352]
### Describe the bug
1) `visible` attribute on field definition has no effect when inside tabs.
2) `only_on` is not working for fields that are inside panels within tabs.

### Steps to Reproduce

1)

- Add a field under a tab, with `visible` block 
![image](https://user-images.githubusercontent.com/18333645/197555546-8ec80fc6-eecf-4c18-8ed9-58a74fbde26f.png)
- Check show page:
![image](https://user-images.githubusercontent.com/18333645/197555755-829792f6-294e-4000-8b00-ae14b27d61b3.png)

2) 

- Add a field under a panel within a tab, with `only_on` attribute
![image](https://user-images.githubusercontent.com/18333645/197580377-a78e5422-04ec-493c-bc9d-ab0b83849bd8.png)
- Check show page:
![image](https://user-images.githubusercontent.com/18333645/197557016-646c3159-222d-43a0-a205-36622ff7ff27.png)

### Expected behavior & Actual behavior
Expected: visibility checks are respected
Actual: are not respected

### Notes
I have some guesses as what the causes could be. I am looking at the `visible_items` method in `tab.rb` (let me know if I am looking at the wrong place):
![image](https://user-images.githubusercontent.com/18333645/197558954-4f92086e-deb0-4489-a573-c9c04eaf1f41.png)
1) This method seems to only check for visibility for a view, not the fields' `visible` block
2) When there is no panel, `items` represents **fields**. However, when a panel is inside a tab `items` represents **panels**, so it does not do the view visibility checks. In this case the fields are found _one layer further_ `items.first.items_holder.items`

### System configuration
**Avo version**: 2.15.3

**Rails version**: 6.1.6.1

**Ruby version**: 3.0.2

#### Impact

 - [ ] High impact
 - [] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Paul-Bob** [comment]
Hello @nicholaswellens , thank you for the detailed issue! we've been working on this and it should be fixed on the next release.
