### ISSUE TITLE
I can't use helper methods of Pundit

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1367]
### Describe the bug
I cannot use the default helpers of Pundit on views, for example `policy_scope(Event)`
I saw that `include Pundit::Authorization` was removed from Avo::ApplicationController, if I include it in each controller it works again.

### Steps to Reproduce
Just add `policy_scope()` in any view and try to use it.

### System configuration
**Avo version**:
2.18
**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hmmm... You're right. We should add it back.

Until then, please add this somewhere in your code (can be `avo.rb` initializer).

```ruby
Rails.configuration.to_prepare do
  if defined?(Pundit::Authorization)
    Avo::ApplicationController.include Pundit::Authorization
  else
    Avo::ApplicationController.include Pundit
  end
end
```

Thanks!
