### ISSUE TITLE
select field not working

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1371]
From [here](https://github.com/avo-hq/avobookr/issues/1).

### Describe the bug

Cloning and running the example application in the repo - when setting a value via a select field, it does not get displayed later on even though all values are properly set in the database. This happens for both, the version 2.7 of avo, as well as for the latest (2.18).

### Steps to Reproduce
1. Clone the example "avobookr" repository. Install gems and setup DB.
2. Go to '/avo' and signup/login
3. Create a new booking
4. In the details page of the booking (http://localhost:3000/avo/resources/bookings/2), the column for "Booked for" is empty

### Expected behavior & Actual behavior

It should show the value as seen in the demo video (https://www.youtube.com/watch?v=BK47E7TMXn0&t=84s)

### System configuration
**Avo version**:
2.7 and 2.18
**Rails version**:

**Ruby version**:

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/6041919/198024838-c31bade7-c599-49d5-9beb-ef24b9f7bb84.png">

### Additional context

- 
#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Paul-Bob** [comment]
@adrianthedev any clue where is the issue? This was working with the same code right?!

**Comment by adrianthedev** [comment]
Hmm. Not sure. Can you ask the OP?

**Comment by adrianthedev** [comment]
Hmmm. Maybe try and replicate the field in the dummy app? Maybe we hit the issue?

**Comment by Bergrebell** [comment]
it looks like it's some issue with displaying the enum. we could print the integer.
