### ISSUE TITLE
Attachment uploads with Trix - bug with `force_locale`

### ISSUE THREAD

**Issue by Annedj** [avo-hq/avo#1386]
### Describe the bug

We are using Avo for our admin with multilingual content, and have set up a **blog post resource** using **Trix**, with attachment uploads.
This works well when adding an attachment from the `edit` page.

However, if there is a locale forced in the `edit` page URL (which is often the case as we are handling seven different locales) - for instance: `/admin/resources/posts/1125/edit?force_locale=en`, then the upload fails as it cannot find the endpoint `"/admin/?force_locale=en/avo_api/resources/posts/1125/attachments"` located [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/attachments_controller.rb#:~:text=%3Acreate%5D-,def%20create,-blob%20%3D%20ActiveStorage).

After investigating the code source of Avo, I found uploading an attachment triggers a `POST` request on the URL set [here](https://github.com/avo-hq/avo/blob/main/app/javascript/js/controllers/fields/trix_field_controller.js#:~:text=return%20%60%24%7Bwindow.location.origin%7D%24%7Bwindow.Avo.configuration.root_path%7D/avo_api/resources/%24%7Bthis.resourceName%7D/%24%7Bthis.resourceId%7D/attachments%60). However, `root_path` returns the URL with the locale query and an extra forward slash, which is making the request fail:

```js
window.Avo.configuration.root_path // => '/admin/?force_locale=en'
```

### Steps to Reproduce
1. On an app with [multilingual content](https://docs.avohq.io/2.0/recipes/multilingual-content.html)
2. Set up a `Post` model with a `rich_text` `content` column
3. Set up a `Post` resource with a Trix field for that column
4. Create a post and, once created, try to upload an attachment to the content

### Expected behavior & Actual behavior

The attachment uploads well if no locale is set, but will fail if there is one set - or if there is any query in the URL. As said, `window.Avo.configuration.root_path` does not return a correct endpoint for the `POST` request to succeed. 

### Models and resource files
`Post` model with a `rich_content` column and:
```ruby
has_many_attached :trix_attachments
has_rich_text :text
```
Resource with `field :text, as: :trix, attachment_key: :trix_attachments`

### System configuration
**Avo version**: 2.16

**Rails version**: 7.0

**Ruby version**: 3.1.2

**License type**:
- [X] Pro

**Are you using Avo monkey patches or overriding views or view components?**
No.

#### Impact

 - [X] High impact
 - [ ] Medium impact
 - [ ] Low impact

This mean that our users won't be able to create blog posts in another locale than English at the moment

#### Urgency

 - [ ] High urgency
 - [X] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Thanks for writing @Annedj.

This will be fixed in the next release.

**Comment by Annedj** [comment]
That's great, thanks for the fast answer!

**Comment by Annedj** [comment]
Hi @adrianthedev 👋 

Hope you are well! We are still having this issue unfortunately even after #1388, the change removed the `/` but still keeps the query params, which now makes the endpoint look like this:

```
Started POST "/admin?force_locale=pt-BR/avo_api/resources/post/1141/attachments" 
```

where it should be like:
```
Started POST "/admin/avo_api/resources/post/1141/attachments?force_locale=pt-BR" 
```

It still seems to come from Avo [`root_path`](https://github.com/avo-hq/avo/issues/1386#:~:text=After%20investigating%20the%20code%20source%20of%20Avo%2C%20I%20found%20uploading%20an%20attachment%20triggers%20a%20POST%20request%20on%20the%20URL%20set%20here.%20However%2C%20root_path%20returns%20the%20URL%20with%20the%20locale%20query%20and%20an%20extra%20forward%20slash%2C%20which%20is%20making%20the%20request%20fail%3A), which returns the query url and then interpolate the rest of the URL.

Let me know if you need more infos and thanks for the latest release! 🙏

**Comment by adrianthedev** [comment]
Sorry about that @Annedj. I probably tested something else for that fix.

I posted [this PR](https://github.com/avo-hq/avo/pull/1484) that should fix this.

Can you please try out this version `2.21.1.pre.pr1484` (`gem 'avo', '2.21.1.pre.pr1484'`) and let me know if that fixes it?

**Comment by Annedj** [comment]
Just tested, works perfectly, thanks for the quick fix 🙌 

```
Started POST "/admin/avo_api/resources/post/1141/attachments?force_locale=pt-BR"
```

**Comment by adrianthedev** [comment]
Amazing! Again, sorry for the mixup.

You can use that version until our next release.
