### ISSUE TITLE
Multi-line field help text

### ISSUE THREAD

**Issue by dhnaranjo** [avo-hq/avo#1390]
### Feature
Currently rendered field help to not respect line breaks, so `this\nbit\nof\text` would render as `this string of text`. I believe it should render as:
```
this
bit
of
text
```

Maybe render markdown even?

### Current workarounds
I created a Resource Tool with the instructions I would have put in the field help, but this is, I feel, a heavy solution.

### Screenshots or screen recordings
<img width="514" alt="image" src="https://user-images.githubusercontent.com/536280/199770549-63df4db2-8062-43be-98a2-eff65df76e19.png">

**Comment by adrianthedev** [comment]
The `help` field should take html content so you can use `<br />`.

```ruby
field :first_name, as: :text, placeholder: "John", stacked: true, help: "Something<br/>here"
```

![CleanShot 2022-11-03 at 18 08 59](https://user-images.githubusercontent.com/1334409/199773589-9aec0629-a1a4-4398-9ac9-e01c1999475a.jpg)

**Comment by dhnaranjo** [comment]
Neat. I could put together a lil markdown processing helper to do the lifting for me. Think I'll do that and maybe you'll wanna incorporate it. Plz hold.

**Comment by adrianthedev** [comment]
Sure! I was going to propose that. Send it our way please!

**Comment by dhnaranjo** [comment]
So this right here handles my needs, but maybe this is more of a recipe than a built-in thing? I dunno, you tell me.

```
module MarkdownHelpText
  class Renderer < Redcarpet::Render::HTML
    def header(text, level)
      case level
      when 1 then %(<h1 class="mb-4">#{text}</h1>)
      when 2 then %(<h2 class="mb-4">#{text}</h1>)
      else
        %(<h#{level} class="mb-2">#{text}</h#{level}>)
      end
    end

    def paragraph(text)
      %(<p class="mb-2">#{text}</p>)
    end

    def block_code(code, language)
      <<~HTML
        <pre class="mb-2 p-1 rounded bg-gray-500 text-white text-sm">
        <code class="#{language}">#{code.chomp}</code>
        </pre>
      HTML
    end

    def codespan(code)
      %(<code class="mb-2 p-1 rounded bg-gray-500 text-white text-sm">#{code}</code>)
    end

    def list(contents, list_type)
      list_style = case list_type
             when "ul" then "list-disc"
             when "ol" then "list-decimal"
             else "list-none"
             end
      %(<#{list_type} class="ml-8 mb-2 #{list_style}">#{contents}</#{list_type}>)
    end
  end

  def markdown_help(content, renderer: Renderer)
    markdown = Redcarpet::Markdown.new(
      renderer.new,
      filter_html: false,
      escape_html: false,
      autolink: true,
      fenced_code_blocks: true
    ).render(content)

    %(<section>#{markdown}</section>)
  end
end
```

With field defined as

```
  field :description_copy, as: :markdown,
    placeholder: "DEFAULT: \n" + Views::ProviderReports::Screeners::Table::DEFAULT_DESCRIPTION_COPY,
    help: markdown_help(<<~MARKDOWN
      # Dog
      ## Cat
      ### bird
      paragraph about hats **bold hat**

      ~~~
      class Ham
        def wow
          puts "wow"
        end
      end
      ~~~

      `code thinger`

      - one
      - two
      - three
    MARKDOWN
    )
```

Resulting in:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/536280/199812265-266f0294-9afc-4283-8181-9a7d8c5ebf4e.png">

**Comment by adrianthedev** [comment]
Maybe we shouldn't add it as of yet to the `main` branch. I added it as [a recipe](https://docs.avohq.io/2.0/recipes/use-markdown-in-help-attributes.html) on the docs until we figure out a better distribution strategy.

Thanks for sharing @dhnaranjo! As always, a great help!
