### ISSUE TITLE
Installing Avo breaks projects already using breadcrumbs

### ISSUE THREAD

**Issue by katafrakt** [avo-hq/avo#1394]
After adding Avo to a project where I already used a bredcrumbs gem ([Gretel](https://github.com/kzkn/gretel)), the project breaks, because Avo pulls `breadcrumbs_on_rails`, which defines same methods as Gretel, but with different arity.

This happens because `breadcrumbs_on_rails` [fearlessly patches](https://github.com/weppos/breadcrumbs_on_rails/blob/12962e873cce8864a53e01d3d54dc0a299897f5e/lib/breadcrumbs_on_rails/railtie.rb) `ActionController::Base` and as a result it's not possible to limit its usage only to Avo controllers[^1].

Looking at the code of `breadcrumbs_on_rails`, which is quite short, I think it would be best in Avo internalized it, renamed `breadcrumbs`-like methods to `avo_breadcrumbs` and removed the dependency on this external library. I think I can prepare a pull request if you approve this direction.

[^1]: Gretel kind of does the same, but with views, so they both are not the greatest ecosystem citizens in this regard.

**Comment by adrianthedev** [comment]
Thanks for writing @katafrakt. I agree that we don't use that gem too much.

I'm open to merging a PR that eliminates `breadcrumbs_on_rails` from Avo. Thank you for offering!
