### ISSUE TITLE
Add ability to completely customize destroy_user_session_path

### ISSUE THREAD

**Issue by nkriege** [avo-hq/avo#1407]
### Feature
Loving Avo so far! We ran into a small issue with the sign-out menu item though. We don't use Devise, and so our sign-out path does not follow the pattern of `destroy_*_session_path`. This means that we cannot configure the link by just setting `current_user_resource_name`. We would benefit from having the ability to customize the entire `destroy_user_session_path`.

Would you be interested in a PR to add this configuration setting? If so, I'd be happy to work on it.

### Current workarounds
We are currently working around this issue by monkey patching `Avo::SidebarProfileComponent` to completely override the `destroy_user_session_path` method. Something like this:
```ruby
require "avo/sidebar_profile_component"

class Avo::SidebarProfileComponent
  def destroy_user_session_path
    :logout_path
  end
end
```

The only other approach I can think of would be to rename the route to match the currently supported pattern.

**Comment by adrianthedev** [comment]
YES! We would be interested in a PR that would fix that bad design decision we took in the beginning. 

Thank you!

**Comment by nkriege** [comment]
Ok, I'll take a crack at this. I'll of course leave `current_user_resource_name` in place so that the change will be backwards compatible. I'm thinking of adding a `destroy_user_session_path` setting that would take priority and would take the full name of the path.

As an aside, I found it slightly confusing that `destroy_user_session_path` refers to the *name* of the path and not the url path itself. I assume I will follow that same naming convention in the setting, but if you think something like `destroy_user_session_path_name` (or something else) would be better I'd be happy to change to whatever you like. As long as it's clearly documented I don't think this will be an issue.

**Comment by adrianthedev** [comment]
That's the approach I was thinking about. Thanks

I'm thinking... maybe call the configuration option `sign_out_path_name`? Do you think it's a good name or should we stick to the devise way fo doing it?

**Comment by nkriege** [comment]
That sounds good to me. I'll leave the method name unchanged, but call the configuration option `sign_out_path_name`.
