### ISSUE TITLE
Destroy record with generic errors, provided error messages are swallowed

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1414]
### when destroying a record, generic errors are shown

When a record is destroyed, the error message is generic. 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1938264/200564197-8b37ba72-c6d6-45d6-b9d6-cc45e15a1431.png">
the actual errors messages are swallowed

### Steps to Reproduce
1- add any validation to prevent your model from destroying a record 
2- add an error message 
3- destroy the record 
4- the generic error message will be shown instead of the error provided 

### Expected behavior & Actual behavior

show the error message provided

### System configuration
**Avo version**: latest

**Rails version**: 

**Ruby version**:

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
@elassadi can you share the validation that would prevent from destroying? I tried this callback on the model and it returned the error on the screen.

```ruby
  before_destroy do
    raise "hey"
  end
```

![CleanShot 2022-11-09 at 10 19 43](https://user-images.githubusercontent.com/1334409/200776351-829aa784-514d-4834-835a-d894a488ecd5.jpg)

**Comment by elassadi** [comment]
```ruby
before_destroy do 
    errors.add(:base, "Some Errors" ) #<< those. errors are swallowed 
    throw(:abort)
 end
```
