### ISSUE TITLE
Translation issues on resources

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1420]
### System configuration
**Avo version**: 2.18.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [x ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x ] Yes. If so, please post code samples.
 - [ ] No

### Screenshots or screen recordings

# Translation issues on resources
I explain my issue  as deep as possible:
1. I'm using the `https://my-domain.com/locale/.../.../` formula in my app with this routes configuration:
```ruby
Rails.application.routes.draw do
    scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
       ...
       mount Avo::Engine, at: Avo.configuration.root_path
       ...
   end
end
```
2. Following the AVO translation instructions in `avo.en.yml` and `avo.es.yml` has the next configuration:
```ruby
en:
  avo:
    field_translations:
      my_resource:
        report: "Report"
        table: "Table"
        ....

es:
  avo:
    field_translations:
      my_resource:
        report: "Informe grafico"
        table: "Informe tabla"
        ....
```
3. In my_resource fields puts the next:
```ruby
field :link_reports, as: :text, translation_key: 'avo.field_translations.my_resource.report'
....
field :link_tables, as: :text, translation_key: 'avo.field_translations.my_resource.table'
```
In this way, I will have 2 URLs, one per locale:
`https://my-domain.com/en/avo/resources/my_resource`
and
`https://my-domain.com/es/avo/resources/my_resource`

The system appears to work, because with locale `/es/` the `report` and `table` keys are translated successfully, but when I change the locale in the URL to `/en/` the translations continue in SPANISH, and they should appear in english. I have not tested with third locale

Have I any mistake? Where is the issue?

Thanks in advance....

**Comment by adrianthedev** [comment]
Not sure this way of nesting paths is supported in Avo.

Please read [this](https://docs.avohq.io/2.0/customization.html#mount-avo-under-a-nested-path) regarding nesting under a particular path and [this](https://docs.avohq.io/2.0/recipes/multilingual-content.html) for switching the locale temporary or permanently.

I advise you don't try to use that nested structure `/en/avo`|`es/avo`, but a regular `/avo` path with `set_locale` for permanent switching and a language switcher or `force_locale` param for a temporary switch.

**Comment by angel-checkealos** [comment]
@adrianthedev I have seen your info. I like to use the `set_locale` para in the profile menu. I only want to translate view tags and signs, not model contents. I have one question, is it necessary to use `gem 'mobility', '~> 1.2.5'`?
This gem appears to be used to translate application contents.

**Comment by angel-checkealos** [comment]
@adrianthedev I continue with issues. I have removed the nesting locale on routes commenting scope for locale
```ruby
Rails.application.routes.draw do
     # scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
       ...
       mount Avo::Engine, at: Avo.configuration.root_path
       ...
   # end
end
```
I have add in `app/controllers/application_controller.rb` the next code:
```ruby
    before_action :set_default_locale

    def set_default_locale
      I18n.locale = params[:set_locale] || I18n.default_locale

      I18n.default_locale = I18n.locale
    end
```
in `config/initializers/avo.rb`:
```ruby
  config.locale = :en
  config.profile_menu = -> {
    ...
    link "Cambiar a español", path: "?set_locale=es"
    link "Switch to English", path: "?set_locale=en"
  }
```
`avo.en.yml` and `avo.es.yml` has not been modified. They are the same as above.

Now I get 2 URLs
`https://my-domain.com/avo/resources/my_resource?set_locale=en`
and
`https://my-domain.com/avo/resources/my_resource?set_locale=es`

The issue persist when I have in a field in a resource:
```ruby
field :link_reports, as: :text, translation_key: 'avo.field_translations.my_resource.report'
....
field :link_tables, as: :text, translation_key: 'avo.field_translations.my_resource.table'
```
The application always show SPANISH translations independently of `set_locale=en` or `set_locale=es`

Where is the problem?

Thanks in advance

**Comment by adrianthedev** [comment]
First of all, make sure you are on the pro license and that the license key is properly set. This feature only works in the pro version.

Your questions👇

No. The `mobility` gem is not required to change the language of the tags.

You don't neet to add the `before_action :set_default_locale` in your `application_controller`. We have that in our controller.

Try the following. Go to `https://my-domain.com/avo/resources/my_resource?set_locale=es` and refresh the page. Abo should be translated to Spanish. 
Then to `https://my-domain.com/avo/resources/my_resource?set_locale=en` and refresh. Now it should be in English.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if you have new information.
