### ISSUE TITLE
Issue when using PrefixId and Actions.

### ISSUE THREAD

**Issue by holden** [avo-hq/avo#1426]
### Describe the bug
I'm getting a `Hashids::InputError in Avo::ActionsController#handle` unable to hash error.

```
      pos = alphabet.index(input[i])

      raise InputError, "unable to unhash" unless pos

      num += pos * alphabet.length ** (input.length - i - 1)
    end
```

### Steps to Reproduce

The prefix id gem works fine with create, update and destroy but seems to fail when trying to use it with avo actions.

eg I have

`has_prefix_id :event` in my model `event`

and am using an action as per:

https://docs.avohq.io/2.0/actions.html

It fails even with everything commented out, it previously worked fine without prefix id.

```
class StatusComplete < Avo::BaseAction
  self.name = "Complete"
  self.message = "Are you sure you want to mark this event as complete?"
  self.visible = -> do
    resource.model.try(:may_complete?) ? view == :show : false
  end

  def handle(**args)
    #models, fields = args.values_at(:models, :fields)
    # models.each do |model|
    #   if model.may_complete? && model.complete!
    #     succeed 'Yup'
    #   else
    #     fail "#{model.errors.full_messages.join(', ')}"
    #   end
    # end
  end
end

```

### System configuration
**Avo version**:
2.91
**Rails version**:
7.0.0
**Ruby version**:
3.1.2
**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Can you please share the full stack trace for that error?

**Comment by holden** [comment]
Rails.root: /Users/holden/Code/paid-projects/cirqus-pro

[Application Trace](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#) | [Framework Trace](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#) | [Full Trace](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:182:in `block in unhash'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:179:in `times'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:179:in `unhash'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:132:in `block in internal_decode'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:127:in `times'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:127:in `internal_decode'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[hashids (1.0.6) lib/hashids.rb:49:in `decode'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[prefixed_ids (1.2.2) lib/prefixed_ids/prefix_id.rb:21:in `decode'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[prefixed_ids (1.2.2) lib/prefixed_ids.rb:75:in `block in find'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[prefixed_ids (1.2.2) lib/prefixed_ids.rb:75:in `map'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[prefixed_ids (1.2.2) lib/prefixed_ids.rb:75:in `find'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[avo (2.19.0) app/controllers/avo/actions_controller.rb:38:in `handle'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/abstract_controller/base.rb:215:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/rendering.rb:53:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:118:in `block in run_callbacks'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[i18n (1.12.0) lib/i18n.rb:322:in `with_locale'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[avo (2.19.0) app/controllers/avo/application_controller.rb:329:in `set_avo_locale'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actiontext (7.0.3.1) lib/action_text/rendering.rb:20:in `with_renderer'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actiontext (7.0.3.1) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:127:in `instance_exec'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:138:in `run_callbacks'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:233:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `block in instrument'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `instrument'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activerecord (7.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/abstract_controller/base.rb:151:in `process'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionview (7.0.3.1) lib/action_view/rendering.rb:39:in `process'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal.rb:188:in `dispatch'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_controller/metal.rb:251:in `dispatch'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:852:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/engine.rb:530:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/railtie.rb:226:in `public_send'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/railtie.rb:226:in `method_missing'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:852:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/static.rb:23:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/static.rb:161:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/etag.rb:27:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/head.rb:12:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/cookies.rb:697:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activerecord (7.0.3.1) lib/active_record/migration.rb:603:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[sentry-rails (5.4.1) lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[sentry-ruby (5.4.1) lib/sentry/rack/capture_exceptions.rb:13:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/rack/logger.rb:40:in `call_app'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `block in call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `block in tagged'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:38:in `tagged'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `tagged'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/method_override.rb:24:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/runtime.rb:22:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[activesupport (7.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/server_timing.rb:20:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/static.rb:23:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[rack (2.2.4) lib/rack/sendfile.rb:110:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[actionpack (7.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[railties (7.0.3.1) lib/rails/engine.rb:530:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/configuration.rb:252:in `call'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/request.rb:76:in `handle_request'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/server.rb:441:in `process_client'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
[puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:5000/avo/resources/events/event_EL1nrZbxBbWeSneMNVJomWAk#)
Request
Parameters:

{"authenticity_token"=>"-s6E4UJYhnj1N7HIh4yufMw99vebH2Ie-hTJ7VPCcBo-fcLsXz3of7xMDPajHWFB_YMpM6gb1oqn-JL5BzTPIw",
 "fields"=>{"avo_resource_ids"=>"644", "avo_selected_query"=>""},
 "button"=>"",
 "resource_name"=>"[FILTERED]",
 "action_id"=>"status_complete"}

**Comment by adrianthedev** [comment]
Not sure how to make this work with `prefix_id`.

What happens is, when you select records on the Index page (to run actions on), Avo picks up the `id` for those models. Then, when the action is executed, it will run `model_klass.find THOSE_IDS`.
That's the place where it fails. It tries to do `Event.find([1,2,3])` and because `prefixed_ids` is overriding that method, it tries to decode those ids and fails.

I tried to tweak Avo to pick up `@model.param` instead of `@model.id`, which would output the `prefixed_id` and then the `find` method would not fail because it would run `Event.find(['event_blabla', 'event_blahblah'])` and those ids would be decoded properly.
Buuuut, then, it breaks the current, supported, integration with `FriendlyId`. In that case it will run `Event.find(['some-event', 'some-other-event'])` and that will fail.

I see this issue was raised in the past https://github.com/norman/friendly_id/issues/935.

There is one way to make this work. use `prefix_id` without overriding the `find` and `param` methods.

```ruby
has_prefix_id :event, override_find: false, override_param: false
```

Now, you'll have the default way of doing things (showing the actual `id`) in Avo, and you can change the `find` methods to `find_by_prefix_id` in your own code.

Again, I'm open to making this work, but I'd love it if you could help out and brainstorm solutions.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if you have any thoughts on this.

**Comment by adrianthedev** [comment]
Hey @holden. Please keep an eye open on this PR https://github.com/avo-hq/avo/pull/1579 and the next release on Tuesday.
That will enable the use of `prefix_id` out of the box.

**Comment by holden** [comment]
Awesome, will do.  Thanks so much!

**Comment by adrianthedev** [comment]
You should be able to test it using https://rubygems.org/gems/avo/versions/2.26.2.pre.pr1579 ✌
