### ISSUE TITLE
Problems with timezone only in Avo

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1441]
### Describe the bug
In the application, I have set timezone "America/Sao_Paulo" and for avo as well, but no matter what I put on timezone in avo.rb doesn't change the timezone for dates on avo...

### Steps to Reproduce
1. Have the records on UTC time
2. Set config.time_zone to anyone that you want in application.rb
3. Create a record and see the time of created_at
4. Set any timezone on avo.rb
5. Go to the record and see that nothing has changed

### Expected behavior & Actual behavior
I need all dates to follow a single source of timezone

### System configuration
**Avo version**:  Avo 2.19.0

**Rails version**: .7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @lukasedw.
That options should be deprecated. I'll make a not of it for v3.

By default, all time-related fields will cast the time to the browser timezone.
If you want to override that you can use the `timezone` option on the `date_time` field.
https://docs.avohq.io/2.0/fields/date_time.html

**Comment by lukasedw** [comment]
Even using that option does not change anything...

**Comment by adrianthedev** [comment]
Does that fixes the issue for you @lukasedw?
