### ISSUE TITLE
NN Translation needed

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1453]
### Context

NN translation needed for [lib/generators/avo/templates/locales/pagy/nn.yml](https://github.com/avo-hq/avo/pull/1433/files/d10d03dac00c42e61cf2273364772e0d4ef80f23#diff-84d21aa32d65d4640270126f8c6428d82d44155d6283a0d86327091ef675b053)

**Comment by adrianthedev** [comment]
@tersor may we ask for your help on this one please?

**Comment by tersor** [comment]
@adrianthedev jep, [PR created](https://github.com/avo-hq/avo/pull/1456).

**Comment by adrianthedev** [comment]
Thank you @tersor! We appreciate the help!
