### ISSUE TITLE
Filter in index with grid

### ISSUE THREAD

**Issue by waliffcordeiro** [avo-hq/avo#1461]
### Describe the bug
When accessing the filter in the index that contains the grid, the filter appears in scroll format instead of a modal

### Steps to Reproduce
![Screenshot from 2022-11-28 11-06-17](https://user-images.githubusercontent.com/43971264/204299212-2c5a3bae-47f0-4199-8f19-4fddf6c15f1f.png)

https://user-images.githubusercontent.com/43971264/204299298-063d8bf7-1aa1-415b-a651-048e01601f4b.mp4

### Expected behavior & Actual behavior
Expected: A filter with priority z-index modal
Actual: Filter in scroll

### System configuration
**Avo version**:
latest

**Rails version**:
7.0.1

**Ruby version**:
3.1.0

#### Impact

 - [ ] High impact
 - [X] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [X] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hmm. that's weird. I can't seem to reproduce this on `2.20`. Can you check https://main.avodemo.com/ and see if you can reproduce it?
Maybe you have something that overrides the `overflow` CSS property?

**Comment by waliffcordeiro** [comment]
> Hmm. that's weird. I can't seem to reproduce this on `2.20`. Can you check https://main.avodemo.com/ and see if you can reproduce it? Maybe you have something that overrides the `overflow` CSS property?

In the demo (https://main.avodemo.com/avo/resources/posts) I verified that this doesn't really happen.

I'll check my system and get back to you. Thank you!

**Comment by adrianthedev** [comment]
No worries!

Closing for now. Feel free to reopen if this still persists.
