### ISSUE TITLE
Cards and Dasboards: current_user is not recognized inside cards or dashboards

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1464]
### System configuration
**2.19**:

**7.04**:

**3.1.2**:

**License type**

 - [ ] Community
 - [ x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ x] No

### Screenshots or screen recordings

I am trying to access to `current_user` on cards to filter records for an specific user. I get the same error using `current_user` in dashboard
```bash
undefined local variable or method `current_user'
```

I have tried to set as context in `config/initializers/avo.rb` just like in docs
```ruby
Avo.configure do |config|
  config.set_context do
    {
      foo: 'bar',
      user: current_user,
      params: request.params,
    }
  end
end
```
But there is no result, or I am not able to access to this params.

Is there any way to access to `current_user`on dashboard and card files?
or
how can I access to declared context variables?

Thanks

**Comment by adrianthedev** [comment]
So there are ttwo ways of doing that.

1. Setting the user in the context like you did above and then, access them using `::Avo::App.context[:current_user]`
https://docs.avohq.io/2.0/customization.html#context

2. set the `current_user_method` in the initializer and then access it using `current_user`

https://docs.avohq.io/2.0/authentication.html#customize-the-current-user-method

I recommend using the second option as that `current_user` variable will be used by Avo internally too.

**Comment by angel-checkealos** [comment]
Thank you Adrian.

I have tested your first solution and works fine in my app.
I don't if is a bug or a misconfiguration on my side, but `current_user_method` is configured in my app from the beginning (I use devise as authentication module):
```ruby
Avo.configure do |config|
  ....
  config.current_user_method = :current_user
  ....
end
```
With this configuration, I am able to use `current_user` in resources, policies, tools, etc..., but when I have tried to use it in dashboard and cards, I have an error. I paste the error in the console for your information, in case you want to make more inquiries or can detect if I have a misconfiguration:
```bash
|   User Load (39.7ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 8630 ORDER BY `users`.`id` ASC LIMIT 1
| Processing by Avo::Dashboards::CardsController#show as */*
|   Parameters: {"index"=>"0", "turbo_frame"=>"client_dashboard_client_users", "dashboard_id"=>"client_dashboard", "id"=>"client_dashboard"}
|   Rendering vendor/bundle/ruby/3.1.0/gems/avo-2.19.0/app/views/avo/dashboards/cards/show.html.erb
|   Rendered vendor/bundle/ruby/3.1.0/gems/avo-2.19.0/app/views/avo/dashboards/cards/show.html.erb (Duration: 23.4ms | Allocations: 4157)
| Completed 500 Internal Server Error in 31ms (ActiveRecord: 0.0ms | Allocations: 6946)
| 
| 
|   
| ActionView::Template::Error (undefined local variable or method `current_user' for #<ClientUsers:0x00007ffb393381c8 @dashboard=ClientDashboard, @options={}, @index=0, @cols=nil, @rows=nil, @label=nil, @refresh_every=nil, @description=nil, @params=#<ActionController::Parameters {"index"=>"0", "turbo_frame"=>"client_dashboard_client_users", "controller"=>"avo/dashboards/cards", "action"=>"show", "dashboard_id"=>"client_dashboard", "id"=>"client_dashboard", "format"=>"client_users"} permitted: false>>
| 
|         users = User.where( company_name: current_user.company_name )
|                                           ^^^^^^^^^^^^):
|     1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
|     2:   <%= render Avo::CardComponent.new card: @card %>
|     3: <% end %>
|   
| app/avo/cards/client_users.rb:26:in `query'
| Started GET "/avo/failed_to_load?turbo_frame=client_dashboard_client_users&src=/avo/dashboards/client_dashboard/cards/client_dashboard.client_users?index=0&turbo_frame=client_dashboard_client_users" for 172.20.0.1 at 2022-11-30 06:47:24 +0000
| Cannot render console from 172.20.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
|   User Load (41.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 8630 ORDER BY `users`.`id` ASC LIMIT 1
| Processing by Avo::HomeController#failed_to_load as HTML
|   Parameters: {"turbo_frame"=>"client_dashboard_client_users", "src"=>"/avo/dashboards/client_dashboard/cards/client_dashboard.client_users?index=0"}
|   Rendering vendor/bundle/ruby/3.1.0/gems/avo-2.19.0/app/views/avo/home/failed_to_load.html.erb
| Unpermitted parameter: :turbo_frame. Context: { controller: Avo::HomeController, action: failed_to_load, request: #<ActionDispatch::Request:0x00007ffb3a66d950>, params: {"turbo_frame"=>"client_dashboard_client_users", "src"=>"/avo/dashboards/client_dashboard/cards/client_dashboard.client_users?index=0", "controller"=>"avo/home", "action"=>"failed_to_load"} }
|   Rendered vendor/bundle/ruby/3.1.0/gems/avo-2.19.0/app/views/avo/home/failed_to_load.html.erb (Duration: 20.8ms | Allocations: 2308)
| Completed 200 OK in 27ms (Views: 23.1ms | ActiveRecord: 0.0ms | Allocations: 4991)
```

Thank you very much.

**Comment by adrianthedev** [comment]
Hmm. That's weird. It should work.

Would you say you are using it in the same way as we do on avodemo?

[Demo link](https://main.avodemo.com/avo/dashboards/dashy) see the bottom left card showing "Current user ID: 39" and the source code [here](https://github.com/avo-hq/main.avodemo.com/blob/main/app/views/avo/cards/_custom_card.html.erb#L5)

**Comment by angel-checkealos** [comment]
Hi Adrian:
The issue is not in the view file. The issue is in the card.rb file `app/avo/cards/client_users.rb`
```ruby
class ClientUsers < Avo::Dashboards::MetricCard
    self.id = "client_users"
    self.label = I18n.t( 'cards.client_users' )
    self.refresh_every = 10.minutes
    self.cols = 1

    def query        
        users = User.where( company_name: current_user.company_name )
        result users.count
    end
end
```
I am trying to get only the users with same company_name that current_user, but `current_users` is not recognized.

On the other hand, I can confirm you that if I declare the `user: current_user` in initializer on `config.set_context` and I use it card.rb file with `::Avo::App.context[:user].company_name`

Has I any misconfiguration on my code?

Thanks

**Comment by adrianthedev** [comment]
Hey @angel-checkealos. Thanks for the clarification that it's a metric card. Yes. I see this on my end too. This is a bug.
Fixing it in the next release. Please use the `context` object until then.

**Comment by angel-checkealos** [comment]
Thank you Adrian. I will wait for the next release.
