### ISSUE TITLE
Security Issue when using pundit policies

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1466]
### Describe the bug
If the current_user_method block is fed nil, then the pundit policy is never used by avo and defaults to allow any user to access the admin interface and perform all actions. 

### Steps to Reproduce

Add this line to your avo.rb initializer
```
Avo.configure do |config|
  config.current_user_method do
    nil
  end
end
```
### Expected behavior & Actual behavior
An error should be raised.

### System configuration
**Avo version**:
2.19.0
**Rails version**:
7.0.3
**Ruby version**:
3.1.2
**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yes. That's a fair concern.

We'll look into fixing that.

**Comment by adrianthedev** [comment]
@Paul-Bob do you think we can add a check in the `AuthorizationService` to raise and error, but only if there is a policy present (so they use the authorization feature) and no `current_user` set?

**Comment by JensRavens** [comment]
I don't think an actual error should be raised here, as it's quite possible that you want to give access to certain parts of the avo app to guest users. But that should be determined by the policy (e.g. just call the policy with `nil` as user so the policy can decide if the page should be shown).

**Comment by Paul-Bob** [comment]
I agree with @JensRavens on this one, we still can have policy without an current_user setted. 

@adrianthedev what do you think about [this fix](https://github.com/avo-hq/avo/pull/1473/commits/8ce9c76ce8e5d5f3d223b133075ba62c78932b5d)?

**Comment by adrianthedev** [comment]
Yup. agreed! I think I was too hasty with that comment. 

Thanks @JensRavens!

**Comment by JensRavens** [comment]
Hey @adrianthedev, I see that the issue was closed but also the corresponding PR was closed without merging. Is there any workaround that we can use instead?

**Comment by adrianthedev** [comment]
@JensRavens can you [`2.21.2.pre.pr1486`](https://rubygems.org/gems/avo/versions/2.21.2.pre.pr1486) and let me know how it works for you guys?

I think you're right about the approach of letting the authorization service run without the user.
Not sure why it was there before. We'll investigate more too.

**Comment by JensRavens** [comment]
Yep, that works!
