### ISSUE TITLE
Badly formatted error messages

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1467]
### Describe the bug

I've noticed that in avo 2.20 validation error messages (that appear in a popup flash message) appear surrounded by `[""]`. This didn't happen before but I'm not sure which version the change appeared in. It also seems like validation messages appear twice with different formatting.

### Steps to Reproduce
1. Find a resource for a model with a presence validation
2. Create the resource without setting that field
3. Look at the error messages that pop up

For example: https://main.avodemo.com/avo/resources/posts/new

### Expected behavior & Actual behavior

There should be two validation messages:

* You might have missed something. Please check the form.
* Name can't be blank

Instead there are three:

* You might have missed something. Please check the form.
* ["Validation failed: Name can't be blank"]
* ["Name can't be blank"]

### System configuration
**Avo version**: 2.20

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![Screenshot 2022-11-30 at 12 50 44](https://user-images.githubusercontent.com/111963/204802879-fbe92e89-3b62-46d1-8bcd-b4013f18caa2.jpg)

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yup. This looks like a regression on something we pushed in 2.20. Thank you @iainbeeston!
