### ISSUE TITLE
Sidebar translation key ignored

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1478]
### Describe the bug

translation key for a field in a sidebar block is not translated 

```ruby
         sidebar do
           field :name, as: :text, translation_key: "translations.name"
        end
      end
```

### Expected behavior & Actual behavior

to be translated 

### System configuration
**Avo version**: 2.20

**Rails version**:7.*

**Ruby version**:3.*

**License type**:

 - [] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @elassadi I just tested this on avodemo and it seems to work on my end. Coul dyou please double-check the settings?

Here's [the commit](https://github.com/avo-hq/main.avodemo.com/commit/808295a36f99ac56e8068a4a5a30fa46376882bd) with the update and here's [the link](https://main.avodemo.com/avo/resources/teams/4) to those changes.

I'll happy look into this more if it's still an issue.
