### ISSUE TITLE
Usage of headless pundit policies in sidebar

### ISSUE THREAD

**Issue by Bergrebell** [avo-hq/avo#1481]
### Feature

It would be great to use headless policies in the sidebar to controll what sections are visible to a user. With the current setup, we can controll the resources but the section name is still visible in the sidebar.

```
class SideboardPolicy
  attr_reader :user

  def initialize(user, _record)
    @user = user
  end

  def teams?
    user.admin?
  end
end
```

```
section "Teams", icon: "heroicons/outline/cog-6-tooth", visible: -> {
    authorize :sideboard, :teams?
    } do
     resource :users, visible: -> {
        authorize current_user, User, "index?", raise_exception: false
      }
end
```

### Current workarounds

```
section "Admin", icon: "heroicons/outline/cog-6-tooth", visible: -> {
      @current_user.admin?
    } do
      resource :users, visible: -> {
        authorize current_user, User, "index?", raise_exception: false
      }
end
```

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/6041919/205644170-2c89bb05-560c-4a13-a2d4-148a14bccd36.png)

**Comment by Bergrebell** [comment]
Let me try! :)

**Comment by adrianthedev** [comment]
You might even be able to replace `SOME_RULE` with `Pundit.policy!(current_user, Team).index?` and use the policy methods

**Comment by Bergrebell** [comment]
thanks! this works like a charm!
