### ISSUE TITLE
Associations controller uses parent policy scope class for scoping associated records

### ISSUE THREAD

**Issue by calebuharrison** [avo-hq/avo#1488]
### Describe the bug
When loading records to display in a `has_many` panel, it appears the `AssociationsController#index` action is using the parent's policy scope class to scope the child records rather than the child records' policy scope class. As an example, if I'm looking at the `show` view of a `PostResource`, and that `PostResource` `has_many :comments`, then the comments will have been scoped by an instance of the `PostPolicy::Scope` class rather than the `CommentPolicy::Scope` class. This is causing several of my `has_many` fields to throw errors because the parent policy scope class references columns that don't exist on the child records.

### Steps to Reproduce
1. Set up a `PostPolicy::Scope` class that, when resolved, statically returns posts with a title of "Title".
2. Set up a `has_many :comments` association, and set the `CommentPolicy::Scope` class to resolve `scope.all` comments.
3. Load the `show` view for the `Post` with the statically configured title of "Title", and notice that the `has_many` panel for comments errors out because comments don't have titles.

### Expected behavior & Actual behavior
Associations should be scoped by their own policy scope classes, but right now they are scoped by the parent scope class.

### System configuration
**Avo version**: 2.21

**Rails version**: 7.0.4

**Ruby version**: 3.0.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
@calebuharrison please try [`2.21.3.pre.pr1489`](https://rubygems.org/gems/avo/versions/2.21.3.pre.pr1489)

**Comment by calebuharrison** [comment]
@adrianthedev that fixed it for me! Thank you so much!
