### ISSUE TITLE
Trash bin icon missing on arbitrary rows

### ISSUE THREAD

**Issue by mighani** [avo-hq/avo#1490]
### Describe the bug

On the index view, on some rows the trash bin icon is missing. So i cant delete the row on the index view. On the view page, I am able to delete the record. 

See screenshot: https://share.getcloudapp.com/5zu2wLDq

### Steps to Reproduce
It's not reproducible. Sometimes and on arbitrary rows, the icon is missing. Maybe just add a couple of rows, more than 30 to test it ?

### Expected behavior & Actual behavior

Icon should be visible.

### Models and resource files

This is the resource
```ruby
class ProjectassignmentResource < Avo::BaseResource
  self.title = :id
  self.includes = []
  # self.search_query = -> do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id
  field :from_date, as: :date, name: "Von",sortable: true, hide_on: [:index]
  field :to_date, as: :date, name: "Bis", sortable: true
  field :employee, as: :belongs_to, name: "Mitarbeiter", searchable: true
  field :project, as: :belongs_to, name: "Projekt", searchable: true
  field :contact, required: false, searchable: true, as: :belongs_to, name: 'Vertrags Kontakt',
        help: "Welcher Kontakt beim Kunden oder Vermittler ist verantwortlich für die Verlängerung?"
  field :hourly_rate, as: :number, name: "Stundensatz"
  field :order_id, as: :text, name: 'Bestellnummer', hide_on: [:index]
  field :archived, as: :boolean, sortable: true,name: 'Archiviert'
  field :note, as: :trix, name: 'Notizen', attachments_disabled: true, hide_on: [:index]
  field :meta, hide_on: [:index],as: :key_value, key_label: "Attribut", value_label: "Attribut Wert", action_text: "Neues Attribut", delete_text: "Attribut Löschen", disable_editing_keys: false, disable_adding_rows: false, disable_deleting_rows: false
  # add fields here
  filter EndingProjectsFilter
end
```

### System configuration
**Avo version**: 2.20.0

**Rails version**: 7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://share.getcloudapp.com/5zu2wLDq

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
@mighani from what I can see it looks like the authorization is kicking in and hides that icon.

Can you check the pundit policy (might be `projekte_policy.rb`) and the `destroy?` method? That might hide it.

**Comment by mighani** [comment]
@adrianthedev Thanks for prompt answer. I DO have a policy. The destroy method looks like

`def destroy?
    user.is_admin? || user.is_hr?
  end`

If the condition was false, it would hide it for all the rows and not for individual ones. Am I wrong?

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.
