### ISSUE TITLE
Client-side localization template not updated properly when table with no records is rendered as a has_many field.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1493]
### Describe the bug

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/113625/208357540-54144bc5-4167-43f7-baab-bdc2142574ed.png">

Notice the error message.

### Steps to Reproduce

I have a field declared like so:

```ruby
        field(:versions,
              as:                  :has_many,
              discreet_pagination: true,
              hide_on:             %i[new edit],
              scope:               -> { query.unscope(:order).order(created_at: :desc, id: :desc) })
```

The association is defined on the relevant model by PaperTrail.  In the event that there are no records for the association, that message is shown.  When records are present, everything renders properly.

### Expected behavior & Actual behavior

I would expect the message to say "No related versions found".

### Models and resource files

```ruby
class VersionResource < Avo::BaseResource
  self.model_class = PaperTrail::Version

  self.record_selector    = false
  self.visible_on_sidebar = false

  field :id,             as: :id
  field :created_at,     as: :date_time, sortable: true
  field :event,          as: :text,      sortable: true
  # ...
end

class AdministratorResource < Avo::BaseResource
  self.title = :email

  heading "Identity"
  field :id,    as: :id,   link_to_resource: true

  # ...

  tabs do
    tab("Versions") do
      panel do
        field(:versions,
          as:                  :has_many,
          discreet_pagination: true,
          hide_on:             %i[new edit],
          scope:               -> { query.unscope(:order).order(created_at: :desc, id: :desc) })
      end
    end
  end
end

class Administrator < ApplicationRecord
  has_paper_trail ignore: %w[updated_at]

  # ...
end
```

### System configuration
**Avo version**: 2.21.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.3

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

`app/views/avo/partials/_head.html.erb`:
```erb
<%= stylesheet_link_tag 'avo_supplement', media: 'all' %>
```

### Screenshots or screen recordings

See above.

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Hey @MrJoy. We made some changes to the translation strings and that broke a few things.
Could you re-run `bin/rails generate avo:locales` and see if that fixes it?

**Comment by adrianthedev** [comment]
@Paul-Bob we really broke a lot of people's apps. I'm thinking about reverting this particular string... WDYT?

**Comment by Paul-Bob** [comment]
Hey @adrianthedev. I think we have several approaches here:

1 - Keep it like it is and tell people who report to update the locales
2 - Revert it to the old version and keep it "broken" until avo 3 (by broken i mean wrong translations on empty messages for most languages excluding EN, nothing dramatic =)) )
3 - We release the fix on avo 2.

I don't like to see that we have several reports on this one, i neither like to see it "broken". From what i see people don't like the generic message that much, so maybe we should go with the option 2 or 3, it's your call

**Comment by MrJoy** [comment]
That did indeed fix things for me.  I apparently forgot to run that when updating.  My mistake!

You could consider adding a post-install message to the gem encouraging people who are upgrading to re-run the locale generation task.

**Comment by adrianthedev** [comment]
Yes. We need a better strategy for updates. I'd love it if `bundler` would have a `post-install` hook so we can automatically apply updates.
