### ISSUE TITLE
Policies are all being initialized with a `nil` user.

### ISSUE THREAD

**Issue by calebuharrison** [avo-hq/avo#1495]
### Describe the bug
After upgrading to 2.22.0, all policies are initialized with a `nil` user, which is causing all authorization to fail.

### Steps to Reproduce
1. Add a policy to any resource in an application
2. Add a non-trivial policy that requires some sort of specific user state.
3. Notice that the policy fails to authorize correctly because it does not receive the current user.

### Expected behavior & Actual behavior
Policies should be correctly populated with the current user, and should thus authorize correctly. Instead, policies do not receive a user and fail to authorize correctly.

### Models and resource files
It's worth noting that I'm using `ActiveSupport::CurrentAttributes` in my app, so my avo initializer uses a block to set the `current_user_method`: `config.current_user_method { Current.user }`.

### System configuration
**Avo version**: 2.22.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.3

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by Paul-Bob** [comment]
Hei @calebuharrison, we are sorry to hear that you are experiencing this issue We have checked on our end and everything seems to be working as expected. Could you please provide more information about the issue you are experiencing and any steps you have taken so far to try to resolve it? This will help us better understand the problem and work towards a solution.

Thank you for your patience and cooperation.

![image](https://user-images.githubusercontent.com/69730720/209408905-1a280e1b-2346-4146-8d4b-b9fa3fa1ac2e.png)


![image](https://user-images.githubusercontent.com/69730720/209409063-3f9ff627-bc02-41a5-a4b3-e32a27519cdf.png)

**Comment by adrianthedev** [comment]
I'll try to explain a bit what happened with V2.22.
After the discussion here https://github.com/avo-hq/avo/issues/1466 a real security issue came up. If somehow, the block you gave Avo to be the current user evaluated to `nil`, all policies would return `true` by default (see the fix in https://github.com/avo-hq/avo/pull/1486). 
That's not what we want, but we want to invoke the policy and give it the actual value `nil` so it can evaluate it properly.

So, https://github.com/avo-hq/avo/pull/1486, should not influence the behavior like that.

I'm curious though, how are you setting the `Current.user` inside the app? That should be done in Avo's controllers.
Can you share where you assign `Current.user = SOME_USER`?

My hunch is that that isn't assigned properly, but I might be wrong.

FYI, [this](https://avohq.io/blog/safely-extend-a-ruby-on-rails-controller) is how we recommend people extend the Avo's `ApplicationController`.

**Comment by adrianthedev** [comment]
One more question pops up for me. Can you check if pre 2.22, the `user` variable in your policies is actually populated with the user?

**Comment by calebuharrison** [comment]
Sorry to report and vanish, guys - Christmas and all that!

I actually assign `Current.user` in a route constraint:

```rb
# routes.rb
require "constraints/user_constraint"

Rails.application.routes.draw do
  #
  mount Avo::Engine => Avo.configuration.root_path, :constraints => UserConstraint.new
  #
end
```

```rb
# lib/constraints/user_constraint.rb

class UserConstraint
  def matches?(request)
    user_id = request.session[:user_id]
    return false unless user_id.present?
    Current.user = User.find_by(id: user_id)
    Current.user.present?
  end
end
```

I'm not sure how it would be possible for the route to match and render _something_, but `Current.user` be nil. I can confirm that the `user` variable is populated pre 2.22.

**Comment by adrianthedev** [comment]
That's weird @calebuharrison.

I created [this](https://github.com/avo-hq/main.avodemo.com/pull/7) branch on the avodemo app. Could you try it out and let me know if you still experience it?

### Testing

When you go to `/avo/resources/teams` you should see a `puts ["policy user->", user].inspect` in the console output with the user.
You'll notice that the user has been forced to the id of `52`.

Do you get the same results with the avodemo app?
