### ISSUE TITLE
Context is not working

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1498]
### Describe the bug
I am setting the context on avo config:
![Screenshot from 2022-12-27 11-59-30](https://user-images.githubusercontent.com/13969616/209684351-11189274-7f74-44ee-9a80-cb46e17b9d96.png)
But I cant get it on resources
![Screenshot from 2022-12-27 12-00-07](https://user-images.githubusercontent.com/13969616/209684419-f56c5e67-b152-4cc0-a543-7343db3af946.png)
It returns nil!

### Steps to Reproduce
Just try to use context as documented here https://docs.avohq.io/2.0/customization.html#context

### Expected behavior & Actual behavior

My final goal is to use this https://docs.avohq.io/2.0/field-options.html#field-visibility

### System configuration
**Avo version**: 2.22.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by lukasedw** [comment]
I know the problem when defining the user, instead **current_user**, should use **_current_user**

**Comment by adrianthedev** [comment]
Hmmm... yeah. That's a mistake on the docs side. I'll fix that.

THanks for getting back with the resolve.
