### ISSUE TITLE
Server reboot required after each change to a resource file

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#1500]
### Describe the bug

I ran into a strange situation where after regenerating an AVO resource whenever I edit the resource file the resource route disappear (and the resource also disappear from the side bar) and in the console I have this message

```
ActionController::RoutingError (No route matches [GET] "/avo/resources/plans"):
```

After a server reboot it goes back to normal

This is a new install on a Rails 6.1.7 with a fair amount of other gems. I could could narrow down the issue to 2.19.0 version. Running 2.18.0 works fine but all version above have the same issue. 
I am pretty sure there is a conflict with some GEM or our code as this would have been detected otherwise. 
Happy to share further information or test things to help fix this issue.

### Steps to Reproduce
1. Add this configuration 'AVO > 2.19.0
2. generate a resource
3. Go to avo resource page
4. edit the resource file (comment a field by example)
5. See error by visiting again the resource page

### System configuration
**Avo version**:

**Rails version**:
6.1.7
**Ruby version**:
3.0.3

**License type**:

 - [X ] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [X] Yes. If so, please post code samples.
 - [ ] No

I have view_components-contrib

**Comment by adrianthedev** [comment]
Hmm. That shouldn't happen. We are eager_loading the resources in the [`DynamicRouter`](https://github.com/avo-hq/avo/blob/main/lib/avo/dynamic_router.rb#L6). 
That is also what generates the resource routes.


What can happen, is this:

 - Avo reads all your resources
 - the `DynamicRouter` generates the routes
 - you access the app and you get an error
 - the `DynamicRouter` fails to generate the new route, hence the `No route matches [GET] "/avo/resources/plans"`

This is my hunch.

When you get that error, please make a change to the last resource you changed before. Preferably to undo the last change. That should make zeitwerk reload the code again and you might not need to reload the server.

I want to re-iterate I never had to do a hard server reload to reload the resource classes.

Let me know if that fixes the "need to reload the server" for you. If not, we can jump on a call to figure it out together.

**Comment by adrienpoly** [comment]
Thanks for your detailed answer It helped me find the cause of this bug. 
I added a breaking point into this DynamicRouter and found out that we had `Rails.application.config.eager_load` set to true.

Setting `config.eager_load = false` in `config/development.rb` solved it 

Not sure why we had this set like that in the first place but this is another story 

Thanks for your help

**Comment by adrianthedev** [comment]
Perfect! Yeah. `eager_loading` should be disabled in development.
