### ISSUE TITLE
AlertComponent outside of avo engine 

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1501]
### Context
Can i move alert component to my own layout. I was trying paste `turbo_frame_tag 'alerts'` to my `application.html.erb`. But flash messages that i set in controller doesn`t appear.

### System configuration
**Avo version**: 2.22.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1156" alt="Screenshot 2022-12-29 at 13 16 39" src="https://user-images.githubusercontent.com/27281496/209943844-e7d29303-2ac8-4188-abc2-ac857051552a.png">
<img width="407" alt="Screenshot 2022-12-29 at 13 18 06" src="https://user-images.githubusercontent.com/27281496/209943847-c63d653c-aa81-4430-95c0-ea83511bcdee.png">

**Comment by adrianthedev** [comment]
I haven't tried them outside of Avo, but they should follow Rails defaults.

Can you try `flash[:error]` instead of `flash.now[:error]`.

In Avo I see we use regular HTML responses

```ruby
respond_to do |format|
  format.html { redirect_to after_create_path, notice: create_success_message}
end
```

**Comment by Sweex99** [comment]
i sorted out with that)
