### ISSUE TITLE
Search feature with multi-lingual content

### ISSUE THREAD

**Issue by Annedj** [avo-hq/avo#1502]
### Describe the bug

We are using Avo for our admin with multilingual content, and the [**search feature**](https://docs.avohq.io/2.0/search.html) does not work with a forced locale in the URL.

### Steps to Reproduce

1. On an app with [multilingual content](https://docs.avohq.io/2.0/recipes/multilingual-content.html)
2. Set up a model and resource with a `search_query`
3. Go to a resource index with a `force_locale` set to one of your locale
4. Click on the search bar and type a search
5. The search doesn't load

<img width="400" alt="image" src="https://user-images.githubusercontent.com/57643651/210221165-1f649d22-4f80-4965-9cb1-c63a57d7efbb.png">

### Expected behavior & Actual behavior

This works well if there are no params in the URL. However if there are any, the api endpoint called is:

`Started GET "/admin%3Fforce_locale=es-419/avo_api/cities/search?q=Mexico&global=false"`

when it should be `Started GET "/admin/avo_api/cities/search?q=Mexico&global=false"`.

Similar to this [issue](https://github.com/avo-hq/avo/issues/1386#:~:text=However%2C%20root_path%20returns%20the%20URL%20with%20the%20locale%20query%20and%20an%20extra%20forward%20slash%2C%20which%20is%20making%20the%20request%20fail%3A), it comes from:

```js
window.Avo.configuration.root_path // => '/admin/?force_locale=en'
```
on this line: `app/javascript/js/controllers/search_controller.js:219` and a few other occurrences in this file.

### System configuration
**Avo version**: "2.21.1.pre.pr1484" (also tried on v2.22)

**Rails version**: 7.0

**Ruby version**: 3.1.2

**License type**:
 - [X] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [X] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [X] Low impact
Our users can still use the search in the English version of the admin, but they don't always have permissions to create content in English so they can be stuck to create new records (and link another model through the [search](https://docs.avohq.io/2.0/associations/belongs_to.html#:~:text=as%3A%20%3Ahas_many%2C-,searchable%3A%20true,-end)).

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [X] Low urgency

Thanks in advance and happy new year!

**Comment by adrianthedev** [comment]
Ok. I think I know how to fix it @Annedj.
I'll just remove any query params from `window.Avo.configuration.root_path`. Those caused only problems and they are not really supposed to be there IMHO.

I'll have a fix up tomorrow.
