### ISSUE TITLE
Acts As Taggable On

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#1512]
Hi,

I have created a Tag Resource, so I can see all the tags in my app.

I'd like the Show view to show a list of all the objects tagged with that tag.   Eg, I'd like a set of tables below the tag details, one for each type of object that has that tag associated.

What is the best way of achieving this?

**Comment by adrianthedev** [comment]
I think the best way to go is to create a `has_many` field on the `TagResource`. That should go in and find all the related items for that tag.

Check out this guide.

https://docs.avohq.io/2.0/recipes/act-as-taggable-on-integration.html

Run this command to have the resources and controllers for this integration.

`rails app:template LOCATION='https://railsbytes.com/script/VRZskb'`

**Comment by rctneil** [comment]
Thanks. 

This does work but what I was hoping for was not to display Taggings, but instead display a table view of each type of item tagged with that tag.  One table view for each object type.

Is this possible?  I realize it would need to look at taggings to figure this out but just unsure how to achieve it.

**Comment by adrianthedev** [comment]
Doesn't the `TagResource` do that? It's there in my gif.

**Comment by adrianthedev** [comment]
Did the last message solve the issue?

**Comment by rctneil** [comment]
I'm still looking into this but will 100% report back soon enough!

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.
