### ISSUE TITLE
Progress bar field does not update display value when editing

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#1519]
### Describe the bug

Progress bar field does not update display value when editing. Probably a small error with id

### Steps to Reproduce
1. Create a resource with progress bar

### Expected behavior & Actual behavior
Updates the display value when scroll

### Models and resource files
```ruby
class SprintsGoalResource < Avo::BaseResource
  self.title = :name
  self.includes = []

  field :id, as: :id
  field :name, as: :text
  field :start, as: :date
  field :end, as: :date
  field :percentage, as: :progress_bar, display_value: true,
    value_suffix: "%"
end

```

### System configuration
**Avo version**: 2.23.2

**Rails version**: 7.0.4

**Ruby version**: 3.1.0

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://user-images.githubusercontent.com/43936240/211418636-e4c237bf-7b87-408f-8109-7c536fe9b243.mp4

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

I can fix that during this week

**Comment by adrianthedev** [comment]
Hey @PedroAugustoRamalhoDuarte. Thanks for getting back to us with this.

I checked on https://avodemo.com and it works there.

Can you check the JS console and give us the output please? Maybe there's some extension that's blocking that.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Of course:
Console:
![image](https://user-images.githubusercontent.com/43936240/211542884-8e4cae16-5b2e-4f97-9ce8-9f0be99cbb30.png)

Js code in browser:
![image](https://user-images.githubusercontent.com/43936240/211542941-2b6add02-bfd6-4e57-9475-f8ec88c3f1b6.png)

Html for the input:
![image](https://user-images.githubusercontent.com/43936240/211543424-fa2a17db-812e-4cf4-8348-c7d99810a88b.png)

**Comment by PedroAugustoRamalhoDuarte** [comment]
I think the fix is only change this line: https://github.com/avo-hq/avo/blob/e84dbebd9b05baaf6d7498ecb77bd9e1bbda9162/app/components/avo/fields/progress_bar_field/edit_component.html.erb#L21 to field.id

I think is working in the demo because de field name is project
