### ISSUE TITLE
Avo field without form object

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1523]
### Describe the bug
I am not sure if is a bug, but I can use [native form components](https://docs.avohq.io/2.0/native-field-components.html#declaring-fields) without form object.

### Steps to Reproduce
Just try to use this `<%= avo_show_field(:photo, as: :text) %>`

### Expected behavior & Actual behavior
To work

### System configuration
**Avo version**: 2.23.2

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No
 
I am overwriting the Avo::ApplicationHelper:135 with

```
      if form.present?
        field.hydrate(model: form.object)
      end
```

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
This PR adds your monkey-patch to `main` 🙌
