### ISSUE TITLE
Authorisation does not working for "has_many: through"

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1527]
### Context
I was created country resource (`columns: code, name`) and created relationship with customer model `(has_many :through )`. And trying assign to country and customer resources policy rules, i want to disable create country record from customer edit and create pages
### System configuration
**Avo version**: 2.22.0

**Rails version**: 7.0.4

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="527" alt="Screenshot 2023-01-12 at 15 02 24" src="https://user-images.githubusercontent.com/27281496/212073399-715e088d-f066-44cf-b724-f2e8b8ef57d4.png">
<img width="380" alt="Screenshot 2023-01-12 at 15 02 42" src="https://user-images.githubusercontent.com/27281496/212073479-a61629ef-4d24-42ff-9506-111fd1eead07.png">
<img width="466" alt="Screenshot 2023-01-12 at 15 03 10" src="https://user-images.githubusercontent.com/27281496/212073554-c37c846c-a53c-40fb-a9e6-c1747c5da660.png">
<img width="1408" alt="Screenshot 2023-01-12 at 15 03 28" src="https://user-images.githubusercontent.com/27281496/212073696-09fecc3c-98c2-4c2c-b057-04f71111c614.png">

**Comment by adrianthedev** [comment]
That should work and the button should be hidden @Sweex99.

https://share.cleanshot.com/CmG7wqlS

Can you please double-check that the valid policy is being used there (You can add a `puts` statement to that method and watch for it in the console.) and that you are on a pro license?

If that doesn't work we can hop on a call to check it out together.

**Comment by Sweex99** [comment]
no, i am using com licence locally, pro on staging env. 
I tried add `binding.pry`, but code didn`t stop.

**Comment by adrianthedev** [comment]
So the authorization feature is a pro feature. It will not work on the community license.
Please share the URL of the app, or the last 8 characters of the license key (please don't share it all) you are using so I can troubleshoot on my end.

**Comment by veelenga** [comment]
@adrianthedev does the authorization feature suppose to work in the development environment?

**Comment by adrianthedev** [comment]
Yes, but only with the Pro license. It will not work on `community` in any nevironment.

```ruby
# config/initializers/avo.rb
Avo.configure do |config|
  config.license = 'pro'
  config.license_key = '************************' # or use ENV['AVO_LICENSE_KEY']
end
```

**Comment by adrianthedev** [comment]
Closing for now. Feel free to re-open.
