### ISSUE TITLE
Problem creating related has_one record for a model

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1530]
### System configuration
**2.21.0**:

**7.0.4**:

**3.1.2**:

**License type**

 - [ ] Community
 - [ X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ X] No

### Screenshots or screen recordings
Scenario:
Model: Client and client_addresses
Association: client `has_many` client_addresses

```ruby
class Sampler < ApplicationRecord
    has_one :sampler_address
end
```

```ruby
class SamplerAddress < ApplicationRecord
    belongs_to :sampler
end
```

```ruby
class CreateSamplerAddresses < ActiveRecord::Migration[7.0]
  def change
    create_table :sampler_addresses do |t|
      t.integer :sampler_id
      t.string :address_1
      ......
      t.timestamps
    end
  end
end
```

SCREENS

1. This is the sampler show view, with related address and `has_one` address
<img width="876" alt="Screenshot 2023-01-17 at 10 33 55" src="https://user-images.githubusercontent.com/106058674/212861834-7db0b77c-f55e-44bd-8a03-ea4372e867dc.png">

2. Create new address and save. The error appears and the redirection to sampler show, doesn't work
<img width="925" alt="Screenshot 2023-01-17 at 10 32 06" src="https://user-images.githubusercontent.com/106058674/212861426-a44b6545-d249-40c2-b959-ceae72eaeceb.png">

3. SamplerAddressResource
```ruby
class SamplerAddressResource < Avo::BaseResource
    self.title = :id
    self.includes = [:sampler]
    # self.search_query = -> do
    #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
    # end

    field :id, as: :id
    # Fields generated from the model
    field :sampler_id, as: :hidden
    field :address, as: :text
    field :address_2, as: :text
    field :city, as: :text
    field :province, as: :text
    field :zip, as: :text
    field :country_id, as: :select, options: Country.all.map{ |country| [country.name_en, country.id] }.to_h, only_on: [:show, :new, :edit]
    
    # add fields here
end
```

3. This is the terminal output
The address is created and associated successfully to sampler, but I don't know how the error appears and the redirection doesn't work
<img width="1262" alt="Screenshot 2023-01-17 at 10 44 38" src="https://user-images.githubusercontent.com/106058674/212864416-eef1865f-9a32-42cb-9543-ccf3e9c64956.png">

Any help will be appreciated

**Comment by Paul-Bob** [comment]
Hey @angel-checkealos , you can not create an `SamplerAddress` withou a `Sampler`. I think your field `field :sampler_id, as: :hidden`  on `SamplerAddressResource` should be `field :sampler, as: :has_one`

**Comment by angel-checkealos** [comment]
Thank you @Paul-Bob, I have tested your solution but it doesn't work.
Keeping in mind that the form for new address is loaded from Sampler resource, this "Sampler" exist in the database, and its ID is submitted with the form as `via_resource_id=483` and `via_relation=sampler`. In fact the `SamplerAddress` is successfully created in the database, as you can see in the console result, but the error appears and the redirection doesn't work.

**Comment by Paul-Bob** [comment]
@angel-checkealos I've been testing on our side with similar models and it works as expected, my setup:

## Samplers
```ruby
class CreateSamplers < ActiveRecord::Migration[6.1]
  def change
    create_table :samplers do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

```ruby
class Sampler < ApplicationRecord
  has_one :sampler_address
end
```

```ruby
class SamplerResource < Avo::BaseResource
  self.title = :id

  field :id, as: :id
  field :name
  field :sampler_address, as: :has_one
end
```

## Samplers Adresses
```ruby
class CreateSamplerAddresses < ActiveRecord::Migration[6.1]
  def change
    create_table :sampler_addresses do |t|
      t.references :sampler, null: false, foreign_key: true
      t.string :street

      t.timestamps
    end
  end
end
```

```ruby
class Sampler < ApplicationRecord
  has_one :sampler_address
end
```

```ruby
class SamplerAddressResource < Avo::BaseResource
  self.title = :id

  field :id, as: :id
  field :street, as: :text
  field :sampler, as: :belongs_to
end
```

![working](https://user-images.githubusercontent.com/69730720/213296916-6a4a0d39-b82f-4cf5-aa60-c98e7400eff8.gif)



Actually it breaks if i change that `field :sampler, as: :belongs_to`  to `field :sampler_id, as: :hidden`, can you explain better what do you want to achieve with `field :sampler_id, as: :hidden`?

**Comment by angel-checkealos** [comment]
Thank you very much @Paul-Bob Finally I have solved the issue.

**Comment by Paul-Bob** [comment]
Amazing news! Anytime! Did you solved it with my solution or something else? Thanks!
