### ISSUE TITLE
Polymorphic belongs_to relationship failing with foreign_key error on create/edit actions

### ISSUE THREAD

**Issue by murpj238** [avo-hq/avo#1532]
### Describe the bug
I have a polymorphic belong_to relation on a resource. When I go to edit or create a record, I get this error:

`undefined method `foreign_key' for nil:NilClass` 

Based on the context on the error page, the code is not detecting the `polymorphic_as` parameter
<img width="804" alt="image" src="https://user-images.githubusercontent.com/16115649/213202211-99889564-43f2-43f4-bedf-e66a8b737bf9.png">

### Steps to Reproduce
Steps to reproduce the behaviour:
1. Create a model with a polymorphic reference to another table
2. Add the belongs_to field to your model with all the parameters to identify it as polymorphic. As specified [here](https://docs.avohq.io/2.0/associations/belongs_to.html#polymorphic-belongs-to)
3. Go to the Avo index page for the resource and click on the option to create a record

### Expected behavior & Actual behavior
I expect the new record page to appear with the belongs_to relationship pre-populated.

What happens is that I get the error message listed above.

### Models and resource files
Model that is referenced
```
class ReferencedModel < ApplicationRecord
    has_many :referencing_model, -> { order(order: :asc) }, as: :referenceable
end

class ReferencedModelResource < Avo::BaseResource
    tabs do
        field :referencing_model, as: :has_many
    end
end
```

Model that references
```
class ReferencingModel < ApplicationRecord
    belongs_to :referenceable, polymorphic: true
end

class ReferencingModel Resource < Avo::BaseResource
    field :referenceable, as: :belongs_to, polymorphic_as: :referenceable, types: [::ReferencedModel]
end
```

### System configuration
**Avo version**: 2.23.2

**Rails version**: 6.1.7

**Ruby version**: 2.7.6

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @murpj238. Thanks for writing.

I can't seem to replicate this bug. I attached a video of it. Can you please recheck the association names?

One thing did pop into my head. You can check out my example. 
We didn't use `reviewable` as the field id on the polymorphic resource. 
We used the same name as the reverse association (a `Project` has many) `reviews`. 
Use `reviewable` in the `polymorphic_as` option.

```ruby
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
end

class ReviewResource < Avo::BaseResource
  tabs do
    field :reviews,
      as: :belongs_to,
      polymorphic_as: :reviewable,
      types: [::Fish, ::Post, ::Project, ::Team]
  end
end


class Project < ApplicationRecord
  has_many :reviews, -> { order(created_at: :asc) }, as: :reviewable
end

class ProjectResource < Avo::BaseResource
  field :reviews, as: :has_many
end
```

https://share.cleanshot.com/bmw1Vgpl

Happy to help further.

**Comment by murpj238** [comment]
Hi @adrianthedev, thanks for the prompt response!

I figured out why I was getting the error. I noticed an old belongs_to reference which didn't exist anymore was left on the resource.

So the create/edit page now loads. Only issue I'm having now is that its very slow to load for some reason.

I think this issue can be closed though.

**Comment by adrianthedev** [comment]
The slowness might be from the belongs_to field. If you have a lot of records, Avo will load all of them in that drop-down.

You can get around that using the `searchable: true` options (only on Pro license).
This will replace the dropdown with a search UI.

**Comment by murpj238** [comment]
Amazing, that's sorted it out! Thank you @adrianthedev
