### ISSUE TITLE
Cannot set sortable: true on model resource

### ISSUE THREAD

**Issue by jyavorska** [avo-hq/avo#1538]
### Describe the bug
I have a field on my model which shows the number of days a user has been inactive. The way this is implemented on the model is quite simple:

```
  def last_visited_at
    visits.last&.started_at
  end
```

### Steps to Reproduce

I've tried adding it to an Avo resource in two ways:

#### As field

`  field :days_inactive, as: :number, searchable: false, sortable: true`

#### As computed field

```
  field 'Days inactive', as: :number, searchable: false, sortable: true do |model, resource, view|
    model.days_inactive
  rescue
    false
  end  
```

### Expected behavior & Actual behavior
I receive the following errors when clicking on the sort button within the Avo user interface.

When I use a direct field, I get the following error:

`PG::UndefinedColumn: ERROR: column users.last_visited_at does not exist LINE 1: SELECT "users".* FROM "users" ORDER BY users.last_visited_at... ^`

When I use a computed field and try to sort, I get:

`Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "users.Last visited at desc".This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().`

I guess since both of these are computed fields, it shouldn't be querying the database to sort them. I couldn't find anything in the docs that said this shouldn't work, so wanted to check if I was doing something wrong.

### System configuration
**Avo version**: 2.17

**Rails version**: 7.0.3

**Ruby version**: 3.2.0

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @jyavorska.

You need to use the sortable block for that.
Check out the docs [here](https://docs.avohq.io/2.0/field-options.html#custom-sortable-block).

You can't just order by `last_visited_at` because that's a property that is being fetched from the associated records.
You'll need to do a join query there to bring in the last visit and order by that.

**Comment by jyavorska** [comment]
Thanks so much!

**Comment by jyavorska** [comment]
@adrianthedev the example is ordering by something else completely, but it's not clear to me how you'd order the thing in question (last_visited_date for me). I tried this:

```
  field "Last visited at", as: :date, sortable: ->(query, direction) {
    puts query.order(last_visited_at: direction)
    return nil
  } do |model, resource, view|
    model.last_visited_at
  rescue
    false
  end
```

This results in the same error as above: `Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "users.Last visited at desc".This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().`.

Here's the example for reference. 

```
class UserResource < Avo::BaseResource
  field :is_writer,
    as: :text,
    sortable: ->(query, direction) {
      # Order by something else completely, just to make a test case that clearly and reliably does what we want.
      query.order(id: direction)
    },
    hide_on: :edit do |model, resource, view, field|
      model.posts.to_a.size > 0 ? "yes" : "no"
    end
end
```

**Comment by adrianthedev** [comment]
I made a few corrections to your field. Changed the id to `last_visited_at`, removed the computed part because it will go into your model, and run your already present `def last_visited_at` method.
I also changed the `sortable` block to return the original query to suit your needs. But please check the query, as I'm not sure it's correct (this part is not Avo, but regular Rails).

```ruby
field :last_visited_at, 
  as: :date, 
  sortable: ->(query, direction) {
	# Not sure this is the correct query. Please check it
    query.includes(:visits).order("visits.started_at #{direction}")
  }
```

Let me know if that works.

**Comment by jyavorska** [comment]
That's it exactly, thanks again. An example in the docs that covers a situation like this one would be really helpful, but in any case really appreciate you taking the time to help me understand.
