### ISSUE TITLE
Canban view

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1542]
### Feature

A Canban view that allows the user to see all records of a resource, organized by stage (e.g. to-do, in progress, done) and color-coded by priority. The view should also allow the user  to easily move tasks between stages and re-prioritize as needed.

- Configurable lanes, stage field and priorisation fields  through new DSL 
```
class IssueResource < Avo::BaseResource
  self.default_view_type = :canban
  

    # some configuration proposition 
    field status as:canban_lanes,  options: [{  label: :todo},{ label: :in_progress}]
# using lambda
    field :status as:canban_lanes,  options:-> { somedynamic_labels }
    field :rank, as: :canban_prio 
```

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/1938264/213914074-ea7909b5-4038-4eff-875c-905b404d63a8.png)

**Comment by adrianthedev** [comment]
Thanks for writing @elassadi.

This is definitely on our roadmap for Avo 3.
That's the API we were thinking of. Some configuration to what should be the field for the columns. Next, some fields to be added to the card. Maybe even allow you to add as many as you want (vs constraining to a few fields like on the grid view).
Is this something that you need urgent?

**Comment by elassadi** [comment]
Hi @adrianthedev 

cool 👍 

 There is no urgency. I think this will be nice for the framework in general with Avo 3 .
