### ISSUE TITLE
No %{item} found on index pages

### ISSUE THREAD

**Issue by yorsant** [avo-hq/avo#1546]
### Describe the bug
The string is not getting interpolated.

### Steps to Reproduce

1. Open a resource index page with items to show.
2. Check the string showing there have yet to be any records.

### Expected behavior & Actual behavior
Show the resource name in the plural. Not the variable name.

### Models and resource files
No need. It happens for any empty index page.

### System configuration
**Avo version**: 2.24.0

**Rails version**: 7.0.4.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1236" alt="Screenshot 2023-01-23 at 10 48 00 PM" src="https://user-images.githubusercontent.com/12414043/214209682-d66338d2-0f68-44bd-b8c4-910e4ad0e0f4.png">

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Hey @yorsant. Apologies for the delay.
We made some changes a few versions back and changed a translations string. Can you run `bin/rails generate avo:locales` to regenerate the locales and see if that fixes it?
This happens when updating Avo form an earlier version and should not happen again with this string.

**Comment by yorsant** [comment]
Thanks.
I was following the upgrade guides. I think it would be nice to add this step there (if you know what version is causing it).
I'll try that and post results here.

**Comment by yorsant** [comment]
Works fine.

**Comment by adrianthedev** [comment]
You're totally right. I pushed changes to have that command there.

Thank you!

**Comment by yorsant** [comment]
Thank you guys for this tool, it's awesome.

**Comment by adrianthedev** [comment]
Thank you for the kind words! They keep us going!
