### ISSUE TITLE
Conditional filter using pundit

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1547]
### Context
We use pundit with avo in order to create multiple admin-like views. A super admin is able to see all types of ressources and items and a company admin for example can only view ressources and items belongs to his company. To realize this we use conditional index views. A company admin is not able to see the super admin status for accounts for example in the index view. At this point we discover a small issue. If we decide depend to the account role what cols are presented in the index view the filter we build will not fit anymore to all types of index views.

Example:

Super admin viewing the index of the "accounts" table:
|id|email|name|is_admin|is_company_admin|
|---|---|---|---|---|
|1|test1@domain1.com|Test User|true|true|
|2|test2@domain1.com|Test User|false|false|
|2|test3@domain1.com|Test User|false|true|

company admin viewing the same table
|email|name|is_company_admin|
|---|---|---|
|test1@domain1.com|Test User|true|
|test2@domain1.com|Test User|false|
|test3@domain1.com|Test User|true|

The index view differs. If we write a filter for the table that only shows the super admins, it will not work in the company admin view. Consequently, we would have to hide the filter for a company admin. We have not yet found a way via pundit to hide a filter when a certain condition is met.

### System configuration
**Avo version**: 2.24.1

**Rails version**: 7.0.4.1

**Ruby version**: 3.1.1

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Have you looked into the `visible` option?

https://docs.avohq.io/2.0/filters.html#visibility

Some entities don't go hand-in-hand with Pundit's policies like models do so we provided `visible` blocks where you have access to a lot of things like `params`, `request`, `current_user`, `context`, and more so you can return `true`/`false` to show/hide that entity (a filter in this case).

**Comment by FLX-0x00** [comment]
I have used a cached version of the documentation where the visibility section was not shown up on this page. Thanks.

**Comment by adrianthedev** [comment]
Yeah, I know. That's a problem that I can't really fix from my end. The old docs site has a service worker that caches the old site for users that visited it previously.
The only way to un-cache it is to hard refresh on the client-side.
Sorry about that.
