### ISSUE TITLE
Grid View - Cover image broken when but working in show/edit 

### ISSUE THREAD

**Issue by Jam0r85** [avo-hq/avo#1548]
Hello!

New to Ruby on Rails and Avo, loving it so far (dabbling after being a long time laravel user)

I have a PropertyRoom model which has a single attached image. On the show/edit pages the image displays fine however when using GRID view I get a broken image. Not sure if this is a current bug but couldn't find anything on search.

<img width="1223" alt="SCR-20230125-idy" src="https://user-images.githubusercontent.com/18726355/214573053-ccedccc5-1f14-4251-9522-d8971313a362.png">

![SCR-20230125-ie5](https://user-images.githubusercontent.com/18726355/214573067-83a233ce-f81a-4274-a35b-ca79bab4d48b.jpeg)

The PropertyRoom model is setup as follows

<img width="490" alt="SCR-20230125-ihl" src="https://user-images.githubusercontent.com/18726355/214573619-c776a042-532f-4a78-9299-cb32b4c28c7d.png">

And the PropertyRoomResource is as follows

<img width="914" alt="SCR-20230125-iht" src="https://user-images.githubusercontent.com/18726355/214573640-9fced901-0860-451a-8e62-d644cf514a4d.png">

Any ideas?

**Comment by adrianthedev** [comment]
What do you get as the img `src` on the grid view?
What happens when you switch to the table view on index? Is it visible there?

**Comment by Jam0r85** [comment]
Changing to table view I get the following

<img width="1221" alt="SCR-20230125-p7g" src="https://user-images.githubusercontent.com/18726355/214646965-60b2423c-6080-4d7e-9406-8c0ac77fd786.png">

The image path in grid view is

http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0515f1a01b9c1729f78369fc6d38daa5f6df40e2/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJU2xCSEJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFMZ0FXa0M0QUU9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--a553ff260075eaa7b32b30021269cb834d15fabc/IMG_1737.JPG

The image path when viewing the resource is

http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0515f1a01b9c1729f78369fc6d38daa5f6df40e2/IMG_1737.JPG

**Comment by adrianthedev** [comment]
That's weird. It should display as an image on the table view too.

What Avo version are you on?

Can you try adding `is_image: true` to the `cover`?

**Comment by Jam0r85** [comment]
No difference :(

Version 2.24.1

**Comment by adrianthedev** [comment]
This is weird.

Try to add `is_image: true` to the field outside of the grid, please. They might be related.

**Comment by ngsimon** [comment]
I had a similar issue and solved it on ubuntu after installing a missing dependency:

```
sudo apt-get install -y libvips
```
