### ISSUE TITLE
Clicking "go back" from a resource always goes to the first page of the collection

### ISSUE THREAD

**Issue by davidcelis** [avo-hq/avo#1555]
### Describe the bug

When using Avo's various "go back" or "cancel" buttons/links when viewing or editing a resource, the default behavior is that you get directed back to the first page of the resource's collection, regardless of how far you had to page through the collection to get to the resource you'd been viewing or editing.

### Steps to Reproduce

1. Have or create an Avo resource that has many records, at least more than one page
2. View a resource on page 2 or later
3. Click the "⬅ Go back" link
4. You are now back on page 1 and must manually page through the collection again

### Expected behavior & Actual behavior

You should be taken back to the page you had been viewing when you clicked through to the resource

### System configuration

**Avo version**: 2.24.0

**Rails version**: 7.0.4.1

**Ruby version**: 3.2.0

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://user-images.githubusercontent.com/36873/215209486-a7b9c47c-6022-4654-a420-30fec7925695.mov

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Hmm, yes. We might be able to get off easy by adding a `via_page` param which we pick up from the `params` object.
I'll add it to the roadmap.

**Comment by Paul-Bob** [comment]
@Nevelito, thanks for opening a PR for this issue! Honestly, I think this is already working as expected in the latest Avo version, so we might not need any changes here. 

@davidcelis, could you please double-check that it's working as expected in the latest Avo version `3.14.0`?

**Comment by Paul-Bob** [comment]
Closing since this was already implemented
