### ISSUE TITLE
Create a `belongs_to` record from the associated record screen

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1556]
### Feature

In a `Post` `has_many` `Comment`s example, when on a Comment new page, next to the posts dropdown you'd have a plus icon which when clicked it will open a modal with the post form ready to create a new post.

From [here](https://discord.com/channels/740892036978442260/740893011994738751/1059859496832344225)

## Aproach

The way I would go about it is like this:

1. update the belongs_to edit field to add that, plus link
1. it links to the create screen with a special `via_` attribute
1. that lets the controller know to use a different view from the `base/new.html.erb`. it will use a new view that is wrapped inside a modal. it will also be wrapped in a turbo-frame element similar to how actions work
2. that new modal new view would actually load up the `Avo::Views::ResourceEditComponent` in a large modal window.
3. The modal window will have the submit button that will save the form's record.
4. after the update action goes through, we need a way to reload the `belongs_to` dropdown field. we can't do a full page reload because the user might have pre-filled other fields and they won't appreciate loosing those values

## Other considerations

1. a nice to have would be to have that new record selected on the field reload
2. this should work nicely with the searchable belongs_to field
3. the modal should ensure that it displays validation errors if they may incur
4. ideally it will not use any custom JS and work on native Turbo methods
5. it should not worsen the experience for the create action and belongs_to field

### Screenshots

A rough sketch of how envision it to look

![CleanShot 2023-01-28 at 12 39 30](https://user-images.githubusercontent.com/1334409/215262145-8e644c63-5004-4a08-8473-32fbc785aa43.jpg)

**Comment by sdcoffey** [comment]
Hey @adrianthedev, did a way to do this ever make it into a release of Avo? Would love to use this feature. Thanks!

**Comment by adrianthedev** [comment]
Nope. Not yet.

I' love to get some time to work on it. We'd also merge a PR if we had one. Shouldn't be suuuuper dificult.

**Comment by sdcoffey** [comment]
Challenge accepted!

**Comment by adrianthedev** [comment]
🔥🔥🔥

My approach would be:

 - add a plus button net to the select
 - that will load up a modal with a turbo_frame pointing to a new view with the parent in the URL (ex: https://main.avodemo.com/avo/resources/users/new?via_record_id=4&via_relation=teams&via_relation_class=Team)
 - (this is something that I don't know by heart how to solve), but the controller should create the new record already associated with the parent
 - the controller would respond with aturbo_stream response that would close the modal and update the select field with the new option (probably regenerate it somehow)

Feel free to build it otherwise if you want that, and let me know if you need help navigating the codebase.

... and thank you!

**Comment by sdcoffey** [comment]
@adrianthedev took a stab at this [here](https://github.com/avo-hq/avo/pull/1876). I went about this in mostly the way you recommended with some minor variations. Let me know your feedback!

**Comment by adrianthedev** [comment]
I have this on the radar @sdcoffey. We're a bit busy with the public beta launch, so we're probably going to have a look later next week.

Thank you for doing the grind like this ❤️

**Comment by sdcoffey** [comment]
Sounds great! Thanks @adrianthedev
