### ISSUE TITLE
Actions sometimes require a server restart to pick up on changes.

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1560]
### Describe the bug

Sometimes, actions need a server restart to pick up on a `message` change. It shouldn't do that

**Comment by gervic08** [comment]
I'm facing a similar issue with an action. It doesn't update options for select field without restarting the server

**Comment by adrianthedev** [comment]
I know that there are some cases when they need a server restart. Not always, but sometimes.

I'd like to fix those in Avo 3 and then backport it to Avo 2.

**Comment by gervic08** [comment]
Maybe this could be helpful for some people facing the same issue:

- In my action I had a select field with a scope from a related model as options. It didn't udpate after choose an option in the dropdown until I changed the way to querying the options as a computed field:

before:
`field :schedule,
         as: :select,
         options: Schedule.free.sort.map { |schedule| [schedule.name, schedule.name] }

**FIXED**:
`field :schedule,
         as: :select,
         **options: ->(model:, resource:, view:, field:) do 
           Schedule.free.sort.map { |schedule| [schedule.name, schedule.name] }
         end`**

**Comment by adrianthedev** [comment]
We wanted to pick this up next, but doesn't seem to happen anymore in the latest versions.
Can anyone please try to reproduce it and let us know how. A reproduction repo would be the easiest way to share it with us.

I'll close it for now.
