### ISSUE TITLE
Use Authorization method (update?/edit?) on reordering controls 

### ISSUE THREAD

**Issue by JeremasPosta** [avo-hq/avo#1562]
### Feature

As a user, I want to see the reordering action buttons if I have write permissions. (`update?`/`edit?` on Pundit policies or create a new `reorder?` method)
### Current workarounds

I really tried and failed in my research.
If we have a way to access the current user on the resources, we can do something like this:
```
  self.ordering = current_user.admin? ? {
    visible_on: :index,
    actions: {
      higher: -> { record.move_higher },
      lower: -> { record.move_lower },
      to_top: -> { record.move_to_top },
      to_bottom: -> { record.move_to_bottom }
    }
  } : {}
```
### Screenshots or screen recordings

Makes no sense to me a user with no `update` permissions can reorder the items:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/60799999/216083210-62b2dbbc-4cfc-4e0e-a305-b1f71e82ff2f.png">

### Additional context

N/A

**Comment by adrianthedev** [comment]
Related: https://github.com/avo-hq/avo/issues/1524

Would you be open to submit a PR for this feature?

**Comment by JeremasPosta** [comment]
@adrianthedev I believe yes, feel free to assign this issue to me.

**Comment by adrianthedev** [comment]
Thank you @JeremasPosta! Let me know if you need help navigating the codebase.

**Comment by JeremasPosta** [comment]
@adrianthedev I worked on a fix adding `can_reorder?`. So updating line 3 at `app/components/avo/index/resource_controls_component.html.erb` worked Ok.

```
  <% if can_reorder? %>
    <%= render Avo::Index::Ordering::ButtonsComponent.new resource: @resource, reflection: @reflection, view_type: @view_type %>
  <% end %>
```

I tested it, by adding  policies to the `Course` and `CourseLink` resources, with `def reorder_links?` and `def reorder?`.
And, looks this works nice. But, I realized this approach will be a bit awkward for current users due they should define the policy method in order to be able to see the reorder controls.

This oposses to the `Avo's seamless upgrade` feeling.

I'd like to add a fallback to `can_edit?` on ` def can_reorder?`, but I wasn't able to achieve it yet.

Simple update could be using just:

```
  <% if can_edit? %>
    <%= render Avo::Index::Ordering::ButtonsComponent.new resource: @resource, reflection: @reflection, view_type: @view_type %>
  <% end %>
```
Giving us less granular control, and maybe some users can find it also odd if they actually used reorder without edit permissions.

Let me know what you think; or if you can help me with the fallback condition, I can quickly open a PR for it.

**Comment by adrianthedev** [comment]
Hey @JeremasPosta. I think the best way to evaluate this is to push up a PR. It doesn't have to be polished or complete yet.

> But, I realized this approach will be a bit awkward for current users due they should define the policy method in order to be able to see the reorder controls.

I know it's not ideal, but it's "ok" to add that breaking change in. We'll document it.

> I'd like to add a fallback to can_edit? on  def can_reorder?

I would keep them separate to have that granularity level.

Thank you for working on this!
