### ISSUE TITLE
Unable to use :hidden together with computed field, results in "SQLite3::ConstraintException: NOT NULL constraint failed: didums.tenant_id"

### ISSUE THREAD

**Issue by lwe** [avo-hq/avo#1567]
### Describe the bug

The background is a multi-tenancy application, without the use of Pundit (just as bare bones as possible right now).

### Steps to Reproduce

1. Setup the following models:
```
./bin/rails g model tenant name:string --skip-avo-resource
./bin/rails g model didum name:string belongs_to:tenant --skip-avo-resource
```
2. Add a foreign key constraint and not null to the `..._create_didums.rb` migration:
```
    create_table :didums do |t|
      t.string :name, null: false
      t.belongs_to :tenant, foreign_key: true, null: false
      t.timestamps
    end
```
3. Create a seeds file to fake the current tenant: `Tenant.find_or_create_by!(name: "Initech Corp.")`
4. Run migrations & seeds
5. Setup a new resource with `./bin/rails g avo:resource didum` and use the following resource:

```ruby
class DidumResource < Avo::BaseResource
  self.title = :name

  self.includes = []
  # self.search_query = -> do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id

  # Fields generated from the model
  field :name, as: :text

  # Added this
  field :tenant_id, as: :hidden do |model|
    Tenant.first.id
  end
end
```

### Expected behavior & Actual behavior

**Expected:** When creating a new user it's created with the default tenant.
**Actual** It fails with the following validation error

<img width="540" alt="image" src="https://user-images.githubusercontent.com/83660/216829375-4a57b606-a503-424d-884b-29260d6dd277.png">

### Models and resource files
See above.

### System configuration
**Avo version**: v2.25.0

**Rails version**: 7.0.4.2

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro (_planned_, but currently still in the trial phase)

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

[Discord discussion](https://discord.com/channels/740892036978442260/740893011994738751/threads/1071803811645104238)

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by lwe** [comment]
Current workaround is the following, which also seems OK from a security PoV, overriding `fill_model` on the resource, though no idea how public that API is 🙈 

```
  field :tenant, as: :belongs_to, readonly: true

  def fill_model(model, params, extra_params: [])
    super.tap do |model|
      model.tenant = Tenant.first
    end
  end
```

**Comment by adrianthedev** [comment]
That's weird. It should work as expected.

Can you check the `POST` request and see if the `tenant_id` is populated with the proper id or not? I'm trying to see where it fails.

**Comment by lwe** [comment]
No, that's the thing, it's not in the `params`, which is very weird - also there's no hidden field created.

**Comment by adrianthedev** [comment]
Ok. My bad.
I forgot that computed fields don't show up on forms.

The fix here is to have getter/setter methods on the model itself.

```ruby
class Didum
  def default_tenant
    Tenant.first.id
  end

  def default_tenant=(value)
    tenant.id = value # or skip this part if tenant is already present
  end
end

class DidumResource
  field :default_tenant, as: :hidden
end
```

Now you can remove the `fill_model` monkeypatch

**Comment by lwe** [comment]
Thanks a lot!
