### ISSUE TITLE
Question about realizing a rolify field

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1568]
I using pundit and rolify gem in order to restrict the access to specific ressources in avo. I was searching for a solution to add and remove dynamicly rolify roles to a ressource. As rolify does not act as "normal" has_many associations it will be a bit trickier to get a function in avo in order to display, add, create and remove roles. I using a custom action currently for this - just wanted to ask, if there any other considerations in order to solve this in a smooth way.

Cheers.

**Comment by adrianthedev** [comment]
I see two ways of doing this.

1. Through a [custom field](https://docs.avohq.io/2.0/custom-fields.html). When you generate a custom field you get access to the `erb` file where you can customize the experience and add checkboxes, radio inputs, or anything you might need to capture the values to assign roles. The field would be used on the `UserResource` or any other resource that actually deals with authorization.
2. Through a [resource tool](https://docs.avohq.io/2.0/resource-tools.html). This is similar and gives you a larger area where you can add your content. See [this resource tool](https://github.com/avo-hq/main.avodemo.com/blob/main/app/views/avo/resource_tools/_fish_information.html.erb) (visible [here](https://main.avodemo.com/avo/resources/fish/7/edit?via_view=index)) that exposes input fields.
3. Depending on your setup, you could fix this easily using a [key_value field](https://docs.avohq.io/2.0/fields/key_value.html) on a virtual attribute on your model.

The virtual attribute can be solved through two methods on your model.

```ruby
class User
  def abilities
    # extract the abilities from somewhere
  end
  
  def abilities=(value)
    # write the abilities somewhere
  end
end

class UserResource
  field :abilities, as: :key_value
end
```

**Comment by FLX-0x00** [comment]
Thank you for your fast input. I will go and create a custom field for rolify. If the code works is this interesting for you to integrate in avo - then i will share my work on this task

**Comment by adrianthedev** [comment]
yes. definitely!
We have plans to create a proper shocase/marketplace type of site where anyone can share their creations officialy.

**Comment by adrianthedev** [comment]
@FLX-0x00 how does the object returned by rollify looks like?

The `tags` field expects an array with hashes with `value` and `label` attributes.

```ruby
[{
  value: 111,
  label: "Pretty something"
}]
```

One thing you can do now is to have intermediate getters and setters on your model that will transform the values to what the tags field expects.

```ruby
def new_roles
  roles.map do |role|
    {
      value: role.id,
      label: role.name
    }
  end
end

def new_roles=(value)
  self.roles = value
end


field :new_roles, as: :tags, name: "Roles"
```

Another option is to create a PR on Avo so the `tags` field has those attributes configurable.

**Comment by FLX-0x00** [comment]
Roles that are made with rolify are a Model named "Role", and acts polymorphic i think.
![image](https://user-images.githubusercontent.com/26464774/221956851-b57df12a-d47e-47e6-a870-8d1f5b539a10.png)

The "name" is the value i look for, but maybe i should check if a has_many field will work O.o

**Comment by adrianthedev** [comment]
you might be able to do that. but you have to create a resource for a `Role`

**Comment by FLX-0x00** [comment]
the model is generated by rolify

![image](https://user-images.githubusercontent.com/26464774/221957828-7f0ff241-f98f-4de2-9c1b-6f8072663e04.png)

**Comment by adrianthedev** [comment]
```ruby
def new_roles
  roles.map do |role|
    {
      value: role.id,
      label: role.name
    }
  end
end

def new_roles=(value)
  self.roles = value
end
```
These should be added to the `User` model. It will take the actual `Role` model instance and turn into a hash.

**Comment by FLX-0x00** [comment]
pretty close

![image](https://user-images.githubusercontent.com/26464774/221959048-cddde450-4308-4759-8638-80330ee6d0dc.png)
![image](https://user-images.githubusercontent.com/26464774/221959111-b36acda9-c67c-4de8-9c3e-2552a940b875.png)

Account model:

  def new_roles
    roles.map do |role|
      {
        value: role.id,
        label: role.name
      }
    end
  end

  def new_roles=(value)
    self.roles = value
  end

okay i think i have to go deeper on this topic.  i appreciate your time very much

**Comment by adrianthedev** [comment]
PS, try the latest Avo 2.27. We just pushed some changes to the tags field.

**Comment by FLX-0x00** [comment]
okay getting some errors with a new constant that is used called Current (used in footer)

```
20:38:11 web.1  | ActionView::Template::Error (uninitialized constant #<Class:0x0000622d13322a38>::Current):
20:38:11 web.1  |     1: <div class="text-center text-sm text-gray-700 <%= 'print:hidden' if Avo.configuration.hide_layout_when_printing %>">
20:38:11 web.1  |     2:   <a href="https://avohq.io/" target="_blank">Avo</a> · &copy; <%= Date.today.year %> AvoHQ · <span title="<%= Avo::App.license.valid ? 'valid' : 'invalid'%> <%= Avo::App.license.id %> license">v<%= Avo::VERSION %></span> · Current.user.id = <%= Current.user&.id %>
20:38:11 web.1  |     3: </div>
```

will checkout if there is any upgrading things todo =)

**Comment by adrianthedev** [comment]
Hmmm... it's on me. Just wait a second, I'll push a fix.

**Comment by adrianthedev** [comment]
Try 2.27.1

**Comment by adrianthedev** [comment]
can you try my suggestion here? To have an intermediary getter and setter?

**Comment by FLX-0x00** [comment]
thought this is already done.

current Account Model
![image](https://user-images.githubusercontent.com/26464774/221964049-2ba70f96-d3aa-421f-9622-5b8fe1bdcb6b.png)

and field in avo ressource

`  field :new_roles, as: :tags, name: "Roles"`

**Comment by adrianthedev** [comment]
Ok. let me look into it tomorrow. It's late on my end.
I'll have a fix, no worries.

**Comment by FLX-0x00** [comment]
okay, nice. we found that the show function works with arrays instead of hashes or json strings - maybe only used in fetched suggestions

![image](https://user-images.githubusercontent.com/26464774/221977276-dab368d1-df2e-43a8-81c8-cd78f2423916.png)

Field definition:

`field :avo_roles, as: :tags, suggestions: -> { Role.all.pluck(:name) }, enforce_suggestions: true` 

UI:
![image](https://user-images.githubusercontent.com/26464774/221977502-724e08cf-1e12-4c33-ba2e-b2d45d1ccde8.png)

Only the updating process is a bit strange as we do not know enough about the avo internals. the value comes not in a nice format to the updating method. maybe rolify is something that is interesting enough for the community to get this feature right in avo with a tags field as shown in `acts_as_taggable_on`. Maybe we need a `acts_as_rolify` in order to match the special conditions. Updating roles can be done with `add_role` or `remove_role` but i think the  `self.roles = Role.where(name: values)` will do the job as they update the tables instantly.

**Comment by FLX-0x00** [comment]
The "reverse" way, ressource for a role, works but with a hassle message

![image](https://user-images.githubusercontent.com/26464774/221982688-e36e4ea6-ca1c-4105-a37f-6bed1365ef43.png)

`self.model_class = Role` is defined, but error message wont dissapear

**Comment by adrianthedev** [comment]
Nice! That looks good!
For that readonly tags field you can hide it on forms with `hide_on: :forms`.

**Comment by FLX-0x00** [comment]
nice one! should i write a short markdown doku about this part?

**Comment by adrianthedev** [comment]
Yes, please!

https://github.com/avo-hq/avodocs

**Comment by FLX-0x00** [comment]
done
