### ISSUE TITLE
How to setup authorization clients?

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#1569]
### Context
I want to disable Authorization in AVO, I check in the source course, there is the nil client https://github.com/avo-hq/avo/blob/main/lib/avo/services/authorization_clients/nil_client.rb, but i cannot find in the docs how i can use this instead the Pundit one.

### System configuration
**Avo version**:
2.17.0
**Rails version**:
7.0.4
**Ruby version**:
3.1.0
**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

**Comment by adrianthedev** [comment]
Thanks for posting @PedroAugustoRamalhoDuarte 

I found that the best approach for solving these issues is to tell us what you are trying to achieve with as many details as needed and we could guide you through how to do that.

To answer your question, you can't disable it. But maybe there's something else you could do to solve it.

So, what are you trying to achieve?
Aslo, please post the relevant monkey-patches that you applied to Avo so we have all the details.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thanks for the support, Adrian.
In my application, I have a lot of ActionPolicy policies for the normal usage (not using avo) in my APP, but I don't want to use this in AVO admin (that works only for admins users that can see everything). For that, I don't want to use the `Avo::Services::AuthorizationClients`.

The best option for me is disabling entire authorization for AVO.

 I have checked the source code and there is this config `config.authorization_client`  that works for me, I think only needs to appear in the docs
 
 ```ruby
 # avo.rb
 config.authorization_client = 'Avo::Services::AuthorizationClients::NilClient'
 ```

**Comment by PedroAugustoRamalhoDuarte** [comment]
Maybe is better `Avo::Services::AuthorizationClients::NilClient` for community license?

**Comment by adrianthedev** [comment]
Can you please post the stack-trace for the error? I'm trying to figure out what is wrong. 
I don't know how Action policy works.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Relax, no problem right now, I have fixed my problem adding this config for the initializer: 
```ruby
config.authorization_client = 'Avo::Services::AuthorizationClients::NilClient'
```
works for  version >= 2.18

**Comment by adrianthedev** [comment]
You can also do `config.authorization_client = nil` to use that client. Thanks for looking into the code and the docs contribution.
