### ISSUE TITLE
Belongs_to action field throws error: undefined method `_reflections' for nil:NilClass

### ISSUE THREAD

**Issue by iyerushalmi** [avo-hq/avo#1572]
### Describe the bug
When attempting to use a searchable belongs_to field in an action, the app throws an error: ActionView::Template::Error (undefined method `_reflections' for nil:NilClass

### Steps to Reproduce
1. Create two models: Product and InboundShipmentItem
2. Set associations: product has_many inbound_shipment_items, and inbound_shipment_item belongs_to product
3. Create an action with field :product, as: :belongs_to, required: true, searchable: true 
4. Assign the action to InboundShipmentItem

### Expected behavior & Actual behavior
Action popup should show a searchable field for product. Instead it throws the following error:

> 
> ActionView::Template::Error (undefined method `_reflections' for nil:NilClass
> 
>         if @model._reflections[reflection_key.to_s].klass.present?
>                  ^^^^^^^^^^^^^):
>     25:       <% if @action.get_fields.present? %>
>     26:         <div class="my-4 -mx-6">
>     27:           <% @action.get_fields.each_with_index do |field, index| %>
>     28:             <%= render field
>     29:               .hydrate(resource: @resource, model: @resource.model, user: @resource.user, view: @view)
>     30:               .component_for_view(@view)
>     31:               .new(field: field, resource: @resource, index: index, form: form, compact: true)
>   
> avo (2.25.0) lib/avo/fields/belongs_to_field.rb:235:in `target_resource'
> avo (2.25.0) app/components/avo/fields/belongs_to_field/edit_component.html.erb:86:in `block in call'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> avo (2.25.0) app/helpers/avo/resources_helper.rb:25:in `block in field_wrapper'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> view_component (2.82.0) lib/view_component/base.rb:302:in `content'
> avo (2.25.0) app/components/avo/field_wrapper_component.html.erb:22:in `block in call'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
> avo (2.25.0) app/components/avo/field_wrapper_component.html.erb:1:in `call'
> view_component (2.82.0) lib/view_component/compiler.rb:107:in `render_template_for'
> view_component (2.82.0) lib/view_component/base.rb:133:in `render_in'
> actionview (7.0.4) lib/action_view/helpers/rendering_helper.rb:42:in `render'
> view_component (2.82.0) lib/view_component/base.rb:200:in `render'
> avo (2.25.0) app/helpers/avo/resources_helper.rb:24:in `field_wrapper'
> avo (2.25.0) app/components/avo/fields/belongs_to_field/edit_component.html.erb:82:in `call'
> view_component (2.82.0) lib/view_component/compiler.rb:107:in `render_template_for'
> view_component (2.82.0) lib/view_component/base.rb:133:in `render_in'
> actionview (7.0.4) lib/action_view/helpers/rendering_helper.rb:42:in `render'
> avo (2.25.0) app/views/avo/actions/show.html.erb:28
> avo (2.25.0) app/views/avo/actions/show.html.erb:27:in `each'
> avo (2.25.0) app/views/avo/actions/show.html.erb:27:in `each_with_index'
> avo (2.25.0) app/views/avo/actions/show.html.erb:27
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> view_component (2.82.0) lib/view_component/base.rb:302:in `content'
> view_component (2.82.0) lib/view_component/slotable_v2.rb:319:in `get_slot'
> view_component (2.82.0) lib/view_component/slotable_v2.rb:92:in `block in renders_one'
> avo (2.25.0) app/components/avo/modal_component.html.erb:10:in `call'
> view_component (2.82.0) lib/view_component/compiler.rb:107:in `render_template_for'
> view_component (2.82.0) lib/view_component/base.rb:133:in `render_in'
> actionview (7.0.4) lib/action_view/helpers/rendering_helper.rb:42:in `render'
> avo (2.25.0) app/views/avo/actions/show.html.erb:16
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> actionview (7.0.4) lib/action_view/helpers/form_helper.rb:768:in `form_with'
> avo (2.25.0) app/views/avo/actions/show.html.erb:10
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
> actionview (7.0.4) lib/action_view/helpers/capture_helper.rb:45:in `capture'
> actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:71:in `tag_string'
> actionview (7.0.4) lib/action_view/helpers/tag_helper.rb:189:in `method_missing'
> turbo-rails (1.3.3) app/helpers/turbo/frames_helper.rb:42:in `turbo_frame_tag'
> avo (2.25.0) app/views/avo/actions/show.html.erb:1
> actionview (7.0.4) lib/action_view/base.rb:244:in `public_send'
> actionview (7.0.4) lib/action_view/base.rb:244:in `_run'
> actionview (7.0.4) lib/action_view/template.rb:157:in `block in render'
> activesupport (7.0.4) lib/active_support/notifications.rb:208:in `instrument'
> actionview (7.0.4) lib/action_view/template.rb:361:in `instrument_render_template'
> actionview (7.0.4) lib/action_view/template.rb:155:in `render'
> actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
> activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
> activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
> actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
> actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:79:in `render_with_layout'
> actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
> actionview (7.0.4) lib/action_view/renderer/template_renderer.rb:11:in `render'
> actionview (7.0.4) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
> actionview (7.0.4) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
> actionview (7.0.4) lib/action_view/rendering.rb:117:in `block in _render_template'
> actionview (7.0.4) lib/action_view/base.rb:270:in `in_rendering_context'
> actionview (7.0.4) lib/action_view/rendering.rb:116:in `_render_template'
> actionpack (7.0.4) lib/action_controller/metal/streaming.rb:216:in `_render_template'
> actionview (7.0.4) lib/action_view/rendering.rb:103:in `render_to_body'
> actionpack (7.0.4) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
> actionpack (7.0.4) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
> actionpack (7.0.4) lib/abstract_controller/rendering.rb:25:in `render'
> actionpack (7.0.4) lib/action_controller/metal/rendering.rb:30:in `render'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
> /Users/username/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
> activesupport (7.0.4) lib/active_support/core_ext/benchmark.rb:14:in `ms'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
> activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:21:in `render'
> meta-tags (2.18.0) lib/meta_tags/controller_helper.rb:22:in `render'
> avo (2.25.0) app/controllers/avo/application_controller.rb:68:in `render'
> actionpack (7.0.4) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
> actionpack (7.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
> <internal:kernel>:90:in `tap'
> actionpack (7.0.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
> actionpack (7.0.4) lib/abstract_controller/base.rb:215:in `process_action'
> actionpack (7.0.4) lib/action_controller/metal/rendering.rb:53:in `process_action'
> actionpack (7.0.4) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
> activesupport (7.0.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
> i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
> avo (2.25.0) app/controllers/avo/application_controller.rb:330:in `set_avo_locale'
> activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
> actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
> actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
> activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
> activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
> activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
> actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
> actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
> activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
> activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
> activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
> actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
> actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
> activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
> actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
> actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
> actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
> actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
> actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
> actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
> actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
> railties (7.0.4) lib/rails/engine.rb:530:in `call'
> railties (7.0.4) lib/rails/railtie.rb:226:in `public_send'
> railties (7.0.4) lib/rails/railtie.rb:226:in `method_missing'
> actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
> actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
> actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
> actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
> rack (2.2.6.2) lib/rack/static.rb:161:in `call'
> warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
> warden (1.2.9) lib/warden/manager.rb:34:in `catch'
> warden (1.2.9) lib/warden/manager.rb:34:in `call'
> rack (2.2.6.2) lib/rack/tempfile_reaper.rb:15:in `call'
> rack (2.2.6.2) lib/rack/etag.rb:27:in `call'
> rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'
> rack (2.2.6.2) lib/rack/head.rb:12:in `call'
> actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
> actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
> rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in `context'
> rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
> activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
> activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
> actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
> web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
> web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
> web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
> web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
> railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
> railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
> activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
> activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
> activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
> railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
> sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
> rack (2.2.6.2) lib/rack/method_override.rb:24:in `call'
> rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'
> activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
> actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
> actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
> rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'
> actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
> railties (7.0.4) lib/rails/engine.rb:530:in `call'
> puma (5.6.5) lib/puma/configuration.rb:252:in `call'
> puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
> puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
> puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
> puma (5.6.5) lib/puma/server.rb:443:in `process_client'
> puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

### Models and resource files

```
class Product < ApplicationRecord
	has_many :inbound_shipment_items
end

class InboundShipmentItem < ApplicationRecord
  belongs_to :product, optional: true
end

class RandomAction < Avo::BaseAction
  self.name = "Random Action"
  self.message = "Here is a message."

  field :product, as: :belongs_to, required: true, searchable: true

  def handle(**args)
    models, fields, current_user, resource = args.values_at(:models, :fields, :current_user, :resource)

  end
end
```

### System configuration
**Avo version**: 2.25.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2p20

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @iyerushalmi. How are you using this action? From the `Index` view (listing) or from the show view of a record?

**Comment by iyerushalmi** [comment]
I simplified the above example (perhaps I should not have). There is actually one more model called InboundShipment which has_many :inbound_shipment_items. I tried doing the action from the Show view of an InboundShipment to an InboundShipmentItem

**Comment by adrianthedev** [comment]
I'm sorry, but I can't see it just from this ticket.
Could you create a sample repo with this issue? You can start from scratch or use [this repo](https://github.com/avo-hq/avo-reproduction) and add more to show your use-case.

**Comment by iyerushalmi** [comment]
Hi Adrian, I will try to do that but do you have any idea what type of things most commonly cause this error? perhaps that information would allow me to further investigate on my end without having to go through the tedious process of building a new repo. I can report back on my findings here in case I am successful

**Comment by iyerushalmi** [comment]
Hi Adrian, I will try to do that but do you have any idea what type of things most commonly cause this error? perhaps that information would allow me to further investigate on my end without having to go through the tedious process of building a new repo. I can report back on my findings here in case I am successful

I did some further testing and found that there is no error if i do it from the Show page of the InboundShipmentItem. The error shows however if I do it from the Show page of the parent InboundShipment (via the has_many table)

**Comment by adrianthedev** [comment]
Oh, ok. Yes. That makes sense. That's why I asked.

The issue is that when you do it from the Index view, there is no "one" `InboundShipmentItem`, but many, because someone may select more than just one record. So, if there's no one record, the `belongs_to` doesn't know how to query the association.

When you do it from the `Show` view, then, it know which record is and will know how to query for that record's belongs_to association.

Does that make sense?

**Comment by iyerushalmi** [comment]
Makes sense. Is there any way to show a searchable lookup box for the action from index view? I don't need the default value for the lookup to be set (I understand the system would have no way of knowing given the user could select multiple records)...I just need the UI to provide an option for the user to select a Product.

**Comment by adrianthedev** [comment]
I know, and using just the `belongs_to` field, you can't achieve that.
There are two things that you can try:

1. try and use the tags field, which you can [pre-populate with existing values](https://docs.avohq.io/2.0/fields/tags.html#options). This approach has the caveat that if you have a lot of values it will take a long time to load and might make the app unresponsive, which is not the desired result.
2. try and update the tags field to support Ajax requests. I can help you navigate the codebase, and you could champion this feature.
3. create a custom field and make it support ajax requests.

I'm sorry I can't give you a better solution than this.
After we launch Avo 3 I plan on revamping the tags field to support ajax requests too.

**Comment by iyerushalmi** [comment]
Noted with thanks. I do not know if I have the bandwidth to take this on right now but may have more time end of this month. I'll let you know if I make any progress.

**Comment by adrianthedev** [comment]
Please follow this PR to get the functionality you need.

**Comment by iyerushalmi** [comment]
Looks great, thank you Adrian!

**Comment by smathieu** [comment]
I've complained about this on Discord a while back, but I'm raising it again given we've just hit that issue one more time (same issue, but built by someone else on our team).

It's very strange that the API for actions works this way. It's very easy to misuse it. It works on the `show` view, but fails on `index`. Someone can easily test their action on the show page, assumes it works, but it shows in the index view and it fails there!

The tag work around is complex and doesn't provide the same search UI our users are used to with the belongs_to field.

It feels like it would so much more preferable if 

```
        field :my_record,
          as: :belongs_to,
          required: true,
          searchable: true
```

would be initialized as blank in the index view rather than crashing.

**Comment by adrianthedev** [comment]
Yes, that field won't work on the index view.

I wrote about why [here](https://github.com/avo-hq/avo/issues/1572#issuecomment-1421461084).

Is there anything else I didn't understand from your message?

**Comment by smathieu** [comment]
I understand it doesn't work this way at the moment, but I think the current behavior is surprising. Actions are by default visible on index & show views. The easiest way to have an action work on a record is to use the `belongs_to` association. This works on the `show` view, but then raises on `index`. I think the Avo DSL should avoid cases where things work in one context, but raises in another.

Yes - there are work arounds with tags & select, but these are more complex to setup and isn't consistent UI wise. 

In the context of an action on the index view, I think `belongs_to` should work, but not pre-populate the value. This gives us an easy way to add a record with a one-liner and it provides a consistent search UI and reuses the resource's scope and search logic.

**Comment by adrianthedev** [comment]
I added a warning about that to the docs @smathieu.
It's a small edge case in the grand scheme of things, and we'd like to focus on more important matters.
Sorry for the frustration it brings.
We're open to PRs if you'd like to take a swing at things to make it better.
