### ISSUE TITLE
MultiSelect Filter button leaks raw HTML in the UI

### ISSUE THREAD

**Issue by claytongentry** [avo-hq/avo#1573]
### Describe the bug
Button in the MultiSelect filter leaks raw HTML in the UI. Bug is present in all Avo versions back through 2.21. Button text looks like:
```
<span class="translation_missing" title="translation missing: en.avo.filter_by">Filter By</span>Filter
```

### Expected behavior & Actual behavior

It should just render the "Filter By..." button text.

### System configuration
**Avo version**:
`>= 2.21`

**Rails version**:
7

**Ruby version**:
3.1.2

**License type**:

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

**Comment by adrianthedev** [comment]
Can you please run `bin/rails generate avo:locales` and see if that fixes it?

**Comment by claytongentry** [comment]
Wow, that did it. Thanks!
