### ISSUE TITLE
Associations are failing

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1576]
### Context
When creating a new resource, it fails with some required fields being blank.

### System configuration
**Avo version**: 2.25.0

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/575138/218256001-ca7b7379-d2de-4a48-85f0-9c54517c9297.png)

`Form on the screenshot: Product`

```ruby
class ProductResource < Avo::BaseResource
  self.title = :product_name
  self.includes = []
  self.search_query = -> do
    scope.ransack(
      m: "or",
      id_eq: params[:q],
      product_name_cont: params[:q],
      ean_cont: params[:q],
      sku_cont: params[:q],
      internal_code_cont: params[:q]
    ).result(distinct: false)
  end

  field :id, as: :id
  field :product_name, as: :text
  field :ean, as: :text
  field :sku, as: :text
  field :internal_code, as: :text
  field :status, as: :text

  field :product_measure_unit, as: :belongs_to, searchable: true

  field :company_partner, as: :belongs_to, searchable: true, readonly: -> { view == :edit }

  field :related_product, as: :belongs_to, searchable: true, readonly: -> { view == :edit }

  tabs do
    field :products, as: :has_many
    field :product_conversions, as: :has_many
    field :product_parameters, as: :has_many
    field :product_prices, as: :has_many
    field :factories, as: :has_many, through: :product_factory
  end

  action ExportToCsv
end
```

```ruby
class Product < ApplicationRecord
  self.table_name = "colecta.product"
  self.primary_key = "id"

  belongs_to :related_product, foreign_key: :id_product_ref

  belongs_to :product_measure_unit, foreign_key: :id_measure_unit_ean

  belongs_to :company_partner
  has_one :company, :through => :company_partner, :source => :company_client

  has_many :product_factories, foreign_key: :id_product
  has_many :factories, :through => :product_factories

  has_many :products, :foreign_key => :id_product_ref
  has_many :product_conversions, :foreign_key => :id_product
  has_many :product_parameters, :foreign_key => :id_product
  has_many :product_prices, :foreign_key => :id_product

  before_create do
    self.id_product_owner = self.company_partner.company_client.id
    self.id_product_owner_type = self.company_partner.company_client.company_type.id
  end

  def self.ransackable_attributes(auth_object = nil)
    ["brand", "category", "company_partner_id", "create_date", "description", "dun", "ean", "id", "id_instance", "id_measure_unit", "id_measure_unit_dun", "id_measure_unit_ean", "id_organization_owner", "id_product_owner", "id_product_owner_type", "id_product_ref", "image", "internal_code", "product_group1", "product_group10", "product_group2", "product_group3", "product_group4", "product_group5", "product_group6", "product_group7", "product_group8", "product_group9", "product_name", "shelf_life", "sku", "status", "subcategory", "update_date"]
  end
end
```

`Unidade de Medida: ProductMeasureUnit - this relation works`

```ruby
class ProductMeasureUnit < ApplicationRecord
  self.table_name = "colecta.product_measure_unit"

  has_many :from_product_conversions, class_name: "ProductConversion", foreign_key: :id_measure_unit_from
  has_many :to_product_conversions, class_name: "ProductConversion", foreign_key: :id_measure_unit_to
  has_many :product_measures, foreign_key: :id_measure_unit

  def title
    "#{self.measure_unit}#{self.description.present? ? " - #{self.description}" : ""}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["description", "id", "measure_unit"]
  end
end
```

```ruby
class ProductMeasureUnitResource < Avo::BaseResource
  self.title = :title
  self.includes = []
  self.search_query = -> do
    scope.ransack(id_eq: params[:q], m: "or", unit_cont: params[:q], description_cont: params[:q]).result(distinct: false)
  end

  field :id, as: :id
  field :measure_unit, as: :text
  field :description, as: :text

  tabs do
    field :from_product_conversions, as: :has_many, translation_key: 'avo.field_translations.from_product_conversions'
    field :to_product_conversions, as: :has_many, translation_key: 'avo.field_translations.to_product_conversions'
    field :product_measures, as: :has_many
  end

  action ExportToCsv
end
```

`Parceria: CompanyPartner - this relation DOES NOT work`

```ruby
class CompanyPartnerResource < Avo::BaseResource
  self.title = :title
  self.includes = []
  self.search_query = -> do
    scope.joins(:company_provider).joins(:company_client).ransack(
      :company_provider_name_cont => params[:q],
      :company_client_name_cont => params[:q],
      :id_eq => params[:q],
      :m => "or"
    ).result(distinct: false)
  end

  field :id, as: :id
  field :company_provider, as: :belongs_to
  field :company_client, as: :belongs_to

  tabs do
    field :products, as: :has_many
  end
end
```

```ruby
class CompanyPartner < ApplicationRecord
  self.table_name = "colecta.company_partner"
  self.primary_key = "id"

  belongs_to :company_provider, foreign_key: :id_company_provider, class_name: "Company"
  belongs_to :company_client, foreign_key: :id_company_client, class_name: "Company"

  has_many :products, foreign_key: :company_partner_id

  def self.ransackable_attributes(auth_object = nil)
    ["create_date", "id", "id_company_client", "id_company_provider", "id_instance"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["company_client", "company_provider", "products"]
  end

  def title
    "#{company_provider.name} - #{company_client.name}"
  end
end
```

`Produto: RelatedProduct - this relation DOES NOT work`

```ruby
class RelatedProduct < ApplicationRecord
  self.table_name = "colecta.product"
  self.primary_key = "id"

  belongs_to :product, foreign_key: :id_product_ref

  belongs_to :product_measure_unit, foreign_key: :id_measure_unit_ean

  belongs_to :company_partner
  has_one :company, :through => :company_partner, :source => :company_client

  has_many :product_factories, foreign_key: :id_product
  has_many :factories, :through => :product_factories

  has_many :products, :foreign_key => :id_product_ref
  has_many :product_conversions, :foreign_key => :id_product
  has_many :product_parameters, :foreign_key => :id_product
  has_many :product_prices, :foreign_key => :id_product

  def self.ransackable_attributes(auth_object = nil)
    ["brand", "category", "company_partner_id", "create_date", "description", "dun", "ean", "id", "id_instance", "id_measure_unit", "id_measure_unit_dun", "id_measure_unit_ean", "id_organization_owner", "id_product_owner", "id_product_owner_type", "id_product_ref", "image", "internal_code", "product_group1", "product_group10", "product_group2", "product_group3", "product_group4", "product_group5", "product_group6", "product_group7", "product_group8", "product_group9", "product_name", "shelf_life", "sku", "status", "subcategory", "update_date"]
  end
end
```

```
the model for RelatedProduct is the same as the Product: we use different resources so we can have different rules and policies for different situations
```

It is important to note that those relations work fine on the views:

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/575138/218256347-07b433c3-7e79-4608-b853-ef0d8ee40aec.png">

**Comment by adrianthedev** [comment]
Can you please share the console output from that request? I'm curious `params` have been sent.

**Comment by crbrasfield** [comment]
@adrianthedev I also was experiencing an issue last week with `readonly: true` fields not being present in the `params` when submitting forms.

**Comment by adrianthedev** [comment]
Hmmm. Yup. Try using `disabled: true` instead of `readonly: true`. @alansikora you too please.

The difference between them is that the `disabled` fields are being added to the model and the `readonly` ones are not. That's a feature, not a bug. It's a security feature to ensure that bad actors will not go into the DOM and re-enable the field, add an arbitrary value and submit it.

**Comment by crbrasfield** [comment]
@adrianthedev I was actually having the same issue with `disabled: true` as well. Basically I always wanted the field to have the value `admin`, but the only way I could get it to submit was by leaving it editable.

```rb
field(:namespace, as: :text, disabled: true, default: 'admin', help: 'This field should not be editable')
```

![Screen Shot 2023-02-13 at 11 26 12 AM](https://user-images.githubusercontent.com/17411437/218528910-11a8fef2-befd-444c-9f1f-c01aa2ee8e39.png)

![Screen Shot 2023-02-13 at 11 26 46 AM](https://user-images.githubusercontent.com/17411437/218528905-3dd091d9-6dd8-4158-bf38-3cbaea5b1004.png)

**Comment by adrianthedev** [comment]
It seems that disabled inputs are not submitted.

You can do that by using a `hidden` field after the disabled one.

```ruby
field(:namespace, as: :text, disabled: false, default: 'admin', help: 'This field should not be editable')
field(:namespace, as: :hidden, default: 'admin')
```

[https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled)

<img width="801" alt="CleanShot 2023-02-13 at 21 12 37@2x" src="https://user-images.githubusercontent.com/1334409/218551939-7d16bfb8-b686-4537-b836-1e9211504d79.png">

**Comment by crbrasfield** [comment]
ahhh, I got so caught up in the Avo options that I wasn't considering the default HTML behavior 😬 
Thanks @adrianthedev, the `as: :hidden` option is exactly what I needed.

**Comment by adrianthedev** [comment]
I now see we have an issue.

In HTML, `disabled` does not get submitted with the form but `readonly` is. So `readonly` is more permissive.
In Avo, `readonly` will prevent the value from being submitted. So it's less permissive. I'd like to switch them but will be a pretty massive breaking change.

Maybe push that breaking change to v3?

**Comment by adrianthedev** [comment]
@alansikora to give you a fix too, try adding a `hidden` field after the `belongs_to` field.

```ruby
field :company_partner, as: :belongs_to, searchable: true, readonly: -> { view == :edit }
field :company_partner_id, as: :hidden, visible: ->(resource:) { resource.view == :edit }
```

**Comment by adrianthedev** [comment]
Yes.. I see it too @murpj238.
Pushing a fix next week. Can you use those fields outside of the panels until then? You can use the `heading` as a separator.

https://docs.avohq.io/2.0/fields/heading.html

**Comment by adrianthedev** [comment]
False alarm @murpj238. I can't seem to reproduce it.

Can you ple

**Comment by murpj238** [comment]
@adrianthedev 

Yes steps to reproduce are:
Go to mentee track/mentor track resource page. Go to the matches (has_many) tab. Then create a new match.
What should happen is the image in my last comment of staging.

Ruby version ruby 2.7.6p219
Rails version 6.1.7
Avo version 2.23.2

**Comment by adrianthedev** [comment]
Can we move the conversation there please? Also, make sure you click the subscribe button on the bottom right on that ticket.
https://github.com/avo-hq/avo/issues/1586

I asked a question there as well.

**Comment by murpj238** [comment]
@adrianthedev apologies moving now

**Comment by alansikora** [comment]
So, looks like it works the way you said @adrianthedev!

There is something going on tho, this resource does not work correctly:

```ruby
class Stock < ApplicationRecord
  self.table_name = "transactions.stock"

  belongs_to :product, foreign_key: :id_product
  belongs_to :company_partner, foreign_key: :id_company_partner
  belongs_to :product_measure_unit, foreign_key: :id_measure_unit

  def title
    "#{product.name} - #{company_partner.company_client.name}"
  end
end
```

```ruby
class StockResource < Avo::BaseResource
  self.title = :id
  self.includes = []
  self.search_query = -> do
    scope.ransack(
      m: "or",
      id_eq: params[:q],
      # product_name_cont: params[:q],
      # ean_cont: params[:q],
      # sku_cont: params[:q],
      # internal_code_cont: params[:q]
    ).result(distinct: false)
  end

  field :id, as: :id, hide_on: [:index]

  field :product, as: :belongs_to, searchable: true, readonly: -> { view == :edit }
  field :id_product, as: :hidden, visible: ->(resource:) { resource.view == :edit }

  field 'EAN', as: :text do |model, resource, view|
    model.product.ean
  rescue
    false
  end
  field 'Loja', as: :text do |model, resource, view|
    model.company_partner.company_client.name
  rescue
    false
  end
  field 'Código Interno', as: :text do |model, resource, view|
    model.product.internal_code
  rescue
    false
  end

  field :company_partner, as: :belongs_to, searchable: true, hide_on: [:index], readonly: -> { view == :edit }
  field :id_company_partner, as: :hidden, visible: ->(resource:) { resource.view == :edit }

  field :product_measure_unit, as: :belongs_to, searchable: true, hide_on: [:index], readonly: -> { view == :edit }
  field :id_measure_unit, as: :hidden, visible: ->(resource:) { resource.view == :edit }

  field :position_date, as: :date, readonly: -> { view == :edit }

  field :quantity, as: :number

  action ExportToCsv
end
```

<img width="597" alt="image" src="https://user-images.githubusercontent.com/575138/221189316-a774ba12-c110-4c8a-8a3e-229f912ee2cd.png">

The logs are:

```colecta-admin-1             |   Stock Create (0.4ms)  INSERT INTO "transactions"."stock" ("id_product", "id_company_partner", "id_measure_unit", "id_batch", "id_stock_type", "hash", "position_date", "quantity", "batch_validate", "create_date", "update_date", "id_instance", "measure_unit", "stock_type", "unit_type", "duplicate_record", "file_line", "id_file_instance") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING "id"  [["id_product", 461287], ["id_company_partner", 2872537], ["id_measure_unit", "42.0"], ["id_batch", nil], ["id_stock_type", nil], ["hash", nil], ["position_date", nil], ["quantity", "123.0"], ["batch_validate", nil], ["create_date", nil], ["update_date", nil], ["id_instance", nil], ["measure_unit", nil], ["stock_type", nil], ["unit_type", nil], ["duplicate_record", nil], ["file_line", nil], ["id_file_instance", nil]]```

All columns are nullable on this table
