### ISSUE TITLE
`Avo::BaseCard#type` doesn't permit intermediate sub-classes.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1577]
### Describe the bug

```ruby
def type
  return :metric if self.class.superclass == ::Avo::Dashboards::MetricCard
  return :chartkick if self.class.superclass == ::Avo::Dashboards::ChartkickCard
  return :partial if self.class.superclass == ::Avo::Dashboards::PartialCard
end
```

This doesn't permit me to define an intermediate sub-class of a card-type, which I may want to do for DRYing things up.

A better implementation might be:

```ruby
def type
  return :metric if self.is_a?(::Avo::Dashboards::MetricCard)
  return :chartkick if self.is_a?(::Avo::Dashboards::ChartkickCard)
  return :partial if self.is_a?(::Avo::Dashboards::PartialCard)
end
```

### Steps to Reproduce

N/A

### Expected behavior & Actual behavior

`Avo::BaseCard#type` should return the appropriate type, even if my class inherits from `SomeClass` (which inherits from `Avo::Dashboards::<something>Card`).

### System configuration
**Avo version**: 2.25.0

**Rails version**: 7.0.4.2

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Makes sense!
