### ISSUE TITLE
Trix: Upload image attachment with cloud storage provider not working

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1582]
We use google cloud storage as active_storage provider and on productive deploy, editing a richtext field with avo and trix work fine except uploading images. On dev environment (postgresql) the image attachment work as expected. We have setup all requirements but are not able to get this feature working. Uploading any attachment using avo works fine.

I can share some log output from our logging service:

```
INFO -- : [0505ecb5-78d2-4759-9df0-702fcbfcd78d] Parameters: {"Content-Type"=>"image/jpeg", "file"=>#<ActionDispatch::Http::UploadedFile:0x00007fa3cd626b28 @tempfile=#<Tempfile:/tmp/RackMultipart20230215-13-p22y3y.jpg>, @original_filename="1674046353.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"1674046353.jpg\"\r\nContent-Type: image/jpeg\r\n">, "filename"=>"1674046353.jpg", "attachment_key"=>"[FILTERED]", "locale"=>"/de|en/", "resource_name"=>"REMOVED", "id"=>"1"}
INFO -- : [0505ecb5-78d2-4759-9df0-702fcbfcd78d] [36m GCS Storage (1.2ms) [0m[32mUploaded file to key: 1g1uyjomyj65yfd0s6mtxp3bonvt (checksum: T2CRJCFwlMiCeDPU0R+H0g==)[0m
[0505ecb5-78d2-4759-9df0-702fcbfcd78d] Completed 500 Internal Server Error in 23ms (ActiveRecord: 13.0ms | Allocations: 5010)
Google::Cloud::Error (Invalid upload source):
```

Unfortunately we can not provide more details.

**Comment by adrianthedev** [comment]
Hey @FLX-0x00. I can't figure out what is happening from that logging.
I am using AWS S3 in my production environment, which is working fine. You can test it [here](https://main.avodemo.com/avo/resources/posts/52).
I also haven't heard about anything like that from other users.

The way I would go around this is:

- scour the web for "Google::Cloud::Error (Invalid upload source):". It sounds like a permissions issue to me.
- check the active storage repo for any issues like that
- create a regular page with Trix and GCS and push it to the production env. to see if that works.

**Comment by FLX-0x00** [comment]
Sorry for that - was a CORS configuration error. now working

**Comment by FLX-0x00** [comment]
In the attachments controller there is a missing cast for the `io` parameter.
https://github.com/avo-hq/avo/blob/d5455bfb083c50b8c793ae564bf278b2ba66c5b3/app/controllers/avo/attachments_controller.rb#L10

you can fix the issue by casting the `file` param into a real `io` object

```ruby
blob = ActiveStorage::Blob.create_and_upload! io: params[:file].to_io, filename: params[:filename]
```
