### ISSUE TITLE
Panels invisible in production

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1586]
### Describe the bug

From [here](https://github.com/avo-hq/avo/issues/1576#issuecomment-1433150200).

We've got a similar issue on our app also. Although strangely, it's only occurring in our Production environment, it works correctly on staging and locally.

Here's an example from production:
![image](https://user-images.githubusercontent.com/16115649/219386262-4f2ce052-2a84-4424-ba29-c64babc84496.png)

Here's one from staging:
![image](https://user-images.githubusercontent.com/16115649/219387597-c2fe4d3c-6a17-4f6f-9600-0248366d3310.png)

Have you any idea why this would happen?

Our relation is here

```
  panel name: 'Mentee 🙋' do
    field :mentee,
          as: :belongs_to,
          polymorphic_as: :mentee,
          types: [::MenteeTrack, ::CareerMenteeTrack],
          attach_scope: -> { query.matchable },
          disabled: -> { params[:via_relation] == 'mentee' },
          only_on: :new,
          searchable: true
  end

  panel name: 'Mentor 💁' do
    field :mentor,
          as: :belongs_to,
          polymorphic_as: :mentor,
          types: [::MentorTrack, ::CareerMentorTrack],
          attach_scope: -> { query.matchable },
          disabled: -> { params[:via_relation] == 'mentor' },
          only_on: :new,
          searchable: true
  end
```

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Does that happen when you add other fields like `id` or `text` fields?

**Comment by murpj238** [comment]
@adrianthedev not sure I understand what you mean? Do you mean when I add another field on the Match resource?

**Comment by adrianthedev** [comment]
Yes, inside one of the panels to see if that makes the panel disappear in production.

**Comment by murpj238** [comment]
Hi Adrian, I tried this locally and it caused it to fail completely. It's a not a huge issue for us as it works correctly without readonly/disabled. I was wondering if you had any idea why our Production environment didn't work, but all others do?

**Comment by adrianthedev** [comment]
Apologies for the delay. I've been a bit busy finishing up [Friendly.rb](https://friendlyrb.com) preparations.

I'll have another look this weekend.
Sorry for not being able to fix this sooner.

**Comment by murpj238** [comment]
Great, thank you @adrianthedev

**Comment by adrianthedev** [comment]
@murpj238 please try [2.26.3.pre.pr1601](https://rubygems.org/gems/avo/versions/2.26.3.pre.pr1601) and let me know if the issue persists.
I found a place where the `view` variable was wrongly memoized.

**Comment by murpj238** [comment]
@adrianthedev thanks Adrian, I'll give that a go and let you know!
