### ISSUE TITLE
Can  not load two different fields from same association but different scope

### ISSUE THREAD

**Issue by francoasdev** [avo-hq/avo#1587]
Hi friends, 
Not sure if this is is a bug report or a feature request, but here it goes:

I'm building an app for football league management.
I have a Game model with the next associations:
```
 belongs_to :home_team, class_name: "Team", foreign_key: 'home_team_id'
 belongs_to :away_team, class_name: "Team", foreign_key: 'away_team_id'
```

I have a model Player with these scopes:
```
  scope :home_team, -> (game) { game.home_team.players }
  scope :away_team, -> (game) { game.away_team.players }
```

In GameResource from avo I have the next tabs:
```
  tabs do
    field :players, as: :has_and_belongs_to_many, scope: -> { query.home_team(self.parent) }, name: "Jugadores locales"
    field :players, as: :has_and_belongs_to_many, scope: -> { query.away_team(self.parent) }, name: "Jugadores visitantes"
  end
```

When both fields are active, it only applies the first for both tabs. Both scopes are working well, but it seems avo doesn't let you use same field twice with different scopes. 

Please let me know If there is another way to make it work instead of working in a change in the gem repo. Any kind of help is appreciated, just want to make it work ASAP. 
Thanks in advance.

**Comment by adrianthedev** [comment]
So you basically have this

```ruby
class Game
  belongs_to :home_team, class_name: "Team", foreign_key: 'home_team_id'
  belongs_to :away_team, class_name: "Team", foreign_key: 'away_team_id'
end

class Player
  scope :home_team, -> (game) { game.home_team.players }
  scope :away_team, -> (game) { game.away_team.players }
end

class GameResource
  tabs do
    field :players, as: :has_and_belongs_to_many, scope: -> { query.home_team(self.parent) }, name: "Jugadores locales"
    field :players, as: :has_and_belongs_to_many, scope: -> { query.away_team(self.parent) }, name: "Jugadores visitantes"
  end
end
```

I'm wondering if you could add a `has_many_through` association to `Game` like so:

```ruby

class Game
  belongs_to :home_team, class_name: "Team", foreign_key: 'home_team_id'
  belongs_to :away_team, class_name: "Team", foreign_key: 'away_team_id'
  
  has_many :home_players, through: :home_team
  has_many :away_players, through: :away_team
end

class GameResource
  tabs do
    field :home_players, as: :has_many, through: :home_team, name: "Jugadores locales"
    field :away_players, as: :has_many, through: :home_team, name: "Jugadores visitantes"
  end
end
```

I haven't tested this code. You might need to tweak it a bit.

The rule of thumb is that you give to Avo the field id that you have on the model `home_players` and `away_players`. This way Avo knows what to call from that model.

**Comment by francoasdev** [comment]
Thank you Adrian! 
That worked, only had to specify the source for :home_team and away_team, so Game model ended up like these:
```
class Game
  belongs_to :home_team, class_name: "Team", foreign_key: 'home_team_id'
  belongs_to :away_team, class_name: "Team", foreign_key: 'away_team_id'
  
  has_many :home_players, through: :home_team
  has_many :away_players, through: :away_team
end
```
Then, you can call the fields :home_players and :away_players in this simple way:
```
  tabs do
    field :home_players, as: :has_many, name: "Jugadores locales"
    field :away_players, as: :has_many, name: "Jugadores visitantes"
  end
```
I'm closing this issue as it's now resolved.
