### ISSUE TITLE
Adding nested attributes to controller new

### ISSUE THREAD

**Issue by simonhutchings** [avo-hq/avo#1590]
### Context
How can I adapt new in the controller. I want to add translation nested attributes

eg.

`I18n.available_locales.each do |lang|
@resource.translations.new(locale: lang)
end`

### System configuration
**Avo version**: 2.26.0

**Rails version**: 7.0.4.2

**Ruby version**: 3.1.3

**License type**

 - [x] Community
 - [ ] Pro

** going pro when project finished

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Hey @simonhutchings. I don't quite understand your request. Can you try to explain it differently to me?

**Comment by simonhutchings** [comment]
I want to create those nested attributes when the new record is instantiated. Doesn't seem that I can create my own controllers in the same way that you can in active admin, so at the moment trying from the model after_initialize but that triggers on new and create.

Obviously i could put the code in the view, but that just feels a bit dirty

```
  after_initialize do
    generate_translations if translations.blank?
  end
```

```
  def generate_translations
    logger.info "**** Generating translations"

    I18n.available_locales.each do |language|
      translations.new(locale: language)
    end
  end
```

**Comment by adrianthedev** [comment]
Hmmm... let me push an update to allow you to do that.
It will be out in this Tuesday's release.

**Comment by adrianthedev** [comment]
Hey @simonhutchings. So far, from what I can see, the issue is that on `after_initialize` you don't know if you're on `new` or `edit`, right?

If so, you can ask the object is it's new or not.


```ruby
  after_initialize do |obj|
    if obj.new_record?
      logger.info "**** Generating translations"

      I18n.available_locales.each do |language|
        translations.new(locale: language)
      end
    end
  end
```

**Comment by simonhutchings** [comment]
Have already tried new record. It runs on edit too!

**Comment by adrianthedev** [comment]
Are you sure? I think it shouldn't. 

It's not manifesting on my end. Do you have different results?

![CleanShot 2023-02-28 at 13 31 04](https://user-images.githubusercontent.com/1334409/221841598-41e05861-f070-476d-8cf3-610c72935fdb.gif)

**Comment by simonhutchings** [comment]
It actually triggers it on create. So initially the form shows 2 translation panels, en & de. When it saves it is obviously initialising again in the controller script and so creates another 2 translations in the db. And so on as I save edits it adds another 2.

I'm guessing in the controller it’s calling new/save rather than create

**Comment by adrianthedev** [comment]
Hey @simonhutchings. Is this fixed? 
Were you able to replicate my demo where you can differentiate between `new` and `edit`?
