### ISSUE TITLE
Automatic translation lookup

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#1593]
### Feature
I wonder if we could set some automatic implicit translation lookup rules. For instance, couldn't we set `translation_key` for each field to go look into `avo.field_translations.RESOURCE_NAME.FIELD_NAME` instead of having to specify the same route for every field, and every resource ?

Also, I don't believe `Actions` and `Filters` have a specific way of handling translations (I manually resort to calling `I18n` and a custom path). I think this could be a cool opportunity to add global, implicit I18n support to avo in most parts of the gem :)

Unless I'm completely off and all this already exists, but I think I re-read documentation quite a few times already 😅

What do you think ?

### Current workarounds
Right now it looks like this:
```ruby
  field :ease, as: :number, hide_on: :index, translation_key: "avo.fields_translations.action_suggestion.ease"
  field :cost, as: :number, hide_on: :index, translation_key: "avo.fields_translations.action_suggestion.cost"
  field :link, as: :text, hide_on: :index, translation_key: "avo.fields_translations.action_suggestion.link"
  field :created_at, as: :date_time, hide_on: [:index, :edit, :new], translation_key: "avo.fields_translations.action_suggestion.created_at"
```

If we set some clear, logic lookup rule (just like some parts of Rails do), we could get rid of having to specify `translation_key` everywhere, as long as one would respect the said rule, but still allow manual override.

**Comment by adrianthedev** [comment]
Hmmm. Yeah, I see what you mean. It's ugly.

So the schema would be `avo.field_translations.RESOURCE_NAME.FIELD_ID`. But that would clash if there were a resource with the same name as the field id. We currently have `avo.field_translations.FIELD_ID` translation scheme.
Maybe we should have `avo.automatic_field_translations.RESOURCE_NAME.FIELD_ID`? But `automatic_field_translations` feels too complex? 
I'm open to suggestions.

Yes. I'd merge a PR like that if there were one.

**Comment by bear-in-mind** [comment]
Got you. I'll run some tests on my end and will propose something :)

**Comment by bear-in-mind** [comment]
By the way, I just spotted a bug in translation lookup on associations: the panel title and all buttons (`attach`,` create`) are apparently based on the `has_many` field name, instead of looking into the `translation_key` of the associated ressource. I'll create a separate issue and try to find some time for a fix

**Comment by adrianthedev** [comment]
Ok. Thank you.

Sorry for the late replies, I'm a bit busy these days, but I expect to have more time towards the end of the week.

**Comment by adrianthedev** [comment]
Or... how about this idea? Have another top-level `avo_fields` translation key. So the new schema would be `avo_fields.RESOURCE_ID.FIELD_ID`?
