### ISSUE TITLE
Inconsistent Ordering Behavior

### ISSUE THREAD

**Issue by estebanutz** [avo-hq/avo#1597]
### Context
I'm experiencing inconsistent behavior when ordering devices. Devices have a family filter to make it easier for clients to order devices in their respective families. Locally everything works as it should; you filter by one family, order all those devices, etc. and the view is still on the filtered page. In production env, it gets weird, where in some families, the filter is reset after ordering, redirecting you to the unfiltered index page. When order doesn't work, the params "&filters=" is not in the fetched URL. Any help would be greatly appreciated! Am I missing something? Please see code below:

### System configuration
**Avo version**: 2.15.3

**Rails version**: 6.1.7

**Ruby version**: 2.7.2p137

**License type**
 - [ ] Community
 - [ X] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [X ] No

```
class Device < ApplicationRecord
  include SuggestedTags
  include ActiveModel::Validations
  validates_with FeaturedImageValidator
  validates_with ThumbnailImageValidator

  acts_as_list scope: :device_family

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :device_family
  has_one_attached :featured_image
  has_one_attached :thumbnail_image

  validates :name, :description, :featured_image, :thumbnail_image, presence: true

  scope :order_asc, -> {order(position: :asc)}

  def should_generate_new_friendly_id?
    name_changed?
  end
end
```

```
class DeviceResource < Avo::BaseResource
  self.title = :name
  self.includes = [:device_family]
  self.search_query = -> do
    scope.ransack(name_cont: params[:q]).result(distinct: false)
  end
  self.resolve_find_scope = ->(model_class:) do
    model_class.friendly
  end
  self.resolve_query_scope = ->(model_class:) do
    model_class.order(device_family_id: :asc, position: :asc)
  end
  self.ordering = {
    visible_on: :index,
    actions: {
      higher: -> { record.move_higher },
      lower: -> { record.move_lower },
      to_top: -> { record.move_to_top },
      to_bottom: -> { record.move_to_bottom },
    }
  }

  filter DeviceFamilyFilter

  field :id, as: :id
  field :position, as: :text, readonly: true, hide_on: [:show, :edit, :new], name: "Pos"
  field :name, as: :text, required: true
  field :description, as: :textarea, rows: 2, required: true
  field :featured_image, as: :file, required: true, is_image: true, name: "Featured Image", help: "Image needs to be JPG or PNG and less than 2MB."
  field :thumbnail_image, as: :file, required: true, is_image: true, name: "Thumbnail Image", hide_on: [:index], help: "Image needs to be JPG or PNG and less than 1MB."
  field :device_family, as: :belongs_to, required: true
  field :tags, as: :tags, acts_as_taggable_on: :tags, close_on_select: false, suggestions: -> { record.tags_suggestions }, enforce_suggestions: true
end
```

```
class DeviceFamily < ApplicationRecord
	include SuggestedTags
	include ActiveModel::Validations
	validates_with FeaturedImageValidator

	extend FriendlyId
	friendly_id :name, use: :slugged

	has_many :devices
	has_one_attached :featured_image

	validates :name, :description, :featured_image, presence: true

	def should_generate_new_friendly_id?
		name_changed?
	end
end
```

```
class DeviceFamilyResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.search_query = -> do
    scope.ransack(name_cont: params[:q]).result(distinct: false)
  end
  self.resolve_find_scope = ->(model_class:) do
    model_class.friendly
  end

  field :id, as: :id
  field :name, as: :text, required: true
  field :description, as: :textarea, rows: 2, required: true
  field :featured_image, as: :file, is_image: true, name: "Featured Image", required: true, help: "Image needs to be JPG or PNG and less than 2MB."
  field :tags, as: :tags, acts_as_taggable_on: :tags, close_on_select: false, suggestions: -> { record.tags_suggestions }, enforce_suggestions: true
end
```

**Comment by estebanutz** [comment]
By the way, I ran the app in production mode locally, but same behavior as dev; everything works fine. I imported the same DB data locally, same thing, everything works fine.

**Comment by adrianthedev** [comment]
I can't see any `sortable` option on any resource. How are they sortable?

**Comment by estebanutz** [comment]
@adrianthedev I apologize, I meant to say **ordering**, not sorting!!! Sorry for the confusion, I'll update the context and title. my bad!

**Comment by adrianthedev** [comment]
@estebanutz can you provide a screen recording with what's happening?
It's not clear to me how to reproduce it. 
Thanks!

**Comment by estebanutz** [comment]
@adrianthedev Unfortunately this client data can't be shared publicly, it's an internal system. Again for context, the expected behavior is to filter devices by family and reordering them. When you do that on production the filtered family is reset. The ordering is happening, but it looks like you are redirected to the devices index page. 

Here's what I have found out so far. 
Locally the ordering buttons have the **filters** param when you apply the filter: 
```
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=higher&amp;referrer=%2Fadmin%2Fresources%2Fdevices%3Fpage%3D1%26filters%3DeyJEZXZpY2VGYW1pbHlGaWx0ZXIiOiIxIn0%253D">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=lower&amp;referrer=%2Fadmin%2Fresources%2Fdevices%3Fpage%3D1%26filters%3DeyJEZXZpY2VGYW1pbHlGaWx0ZXIiOiIxIn0%253D">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=to_top&amp;referrer=%2Fadmin%2Fresources%2Fdevices%3Fpage%3D1%26filters%3DeyJEZXZpY2VGYW1pbHlGaWx0ZXIiOiIxIn0%253D">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=to_bottom&amp;referrer=%2Fadmin%2Fresources%2Fdevices%3Fpage%3D1%26filters%3DeyJEZXZpY2VGYW1pbHlGaWx0ZXIiOiIxIn0%253D">
```

On production they do not, and this is after applying the filter.
```
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=higher&amp;referrer=%2Fadmin%2Fresources%2Fdevices">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=lower&amp;referrer=%2Fadmin%2Fresources%2Fdevices">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=to_top&amp;referrer=%2Fadmin%2Fresources%2Fdevices">
<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=to_bottom&amp;referrer=%2Fadmin%2Fresources%2Fdevices">
```

**Comment by adrianthedev** [comment]
@estebanutz It's very difficult for me to provide support without a way to reproduce it.
I had a look at all the information provided and ran quite a few tests on my end but can't get your results.

The links you sent look ok.
A quick question. Does the user have access to `admin/resources/devices`? I mean, do they get redirected if they land there?

The last thing that comes to mind we could do is to have a video call together where we can troubleshoot the production app.
I'm open to other ideas.

Sorry I don't have a quick solution for you.

My reproduction 👇

![CleanShot 2023-02-26 at 19 22 36](https://user-images.githubusercontent.com/1334409/221426070-4d7192f7-508f-4fd0-aa6e-90ad40aa3f1e.gif)

**Comment by estebanutz** [comment]
@adrianthedev I understand. I'll see if I can provide a video. I'll check with the client. 

Yes, the user has access to `admin/resources/devices`. 

In the video you provided, do the ordering buttons have the '&filters=' params after you apply the filter? 

Because on mine they don't. The buttons have all the other parameters (direction, and referrer), except for filters. You can see them in the code I posted above, and I think that's why I don't get the expected behavior on production.

**Comment by adrianthedev** [comment]
No, it does not have the `filters` param, but that's intended. It has the `referrer` param which in turn has the `filters` param inside. So after the reordering is executed, it will redirect to that referrer.

This is the code that generates that route so you can have a look for yourself.

https://github.com/avo-hq/avo/blob/main/app/components/avo/index/ordering/button_component.rb#L21
https://github.com/avo-hq/avo/blob/main/app/components/avo/index/ordering/button_component.html.erb#L1

**Comment by estebanutz** [comment]
@adrianthedev Still troubleshooting on my end. I can see you have filters in your referrer param, again I do not and this the order form after applying a filter:

`<form class="button_to" method="post" action="/admin/reorder/devices/3?direction=higher&amp;referrer=%2Fadmin%2Fresources%2Fdevices">`

**Comment by adrianthedev** [comment]
Yes. I understand. I don't know what could cause it.
It's challenging without troubleshooting live.

**Comment by estebanutz** [comment]
@adrianthedev I was able to fix the issue. I'm not 100% sure what caused the problem but I fixed it by regenerating the friendly slugs and disabling Avo's cache on index views 'config.cache_resources_on_index_view = false' now all the buttons have 'filters' in the referrer param.

**Comment by adrianthedev** [comment]
Pfff. This is a relief.
IMHO, the caching shouldn't impact it. Not sure about the slugs, though...
Anyway. I'm glad it's fixed.

Thanks for sharing!
