### ISSUE TITLE
Translations on tabs does not work

### ISSUE THREAD

**Issue by alansikora** [avo-hq/avo#1598]
### Describe the bug
Translations does not work on relation tabs

### Steps to Reproduce
1. Create tabs:
```ruby
tabs do
    field :from_product_conversions, as: :has_many, translation_key: 'avo.field_translations.from_product_conversions'
    field :to_product_conversions, as: :has_many, translation_key: 'avo.field_translations.to_product_conversions'
    field :product_measures, as: :has_many
  end
```
2. Visit the page and verify it does not work:
<img width="577" alt="image" src="https://user-images.githubusercontent.com/575138/221239193-1bfce99a-d4e4-4ad8-9e2c-a47c249172b2.png">

3. Try to add a tab with a key:
![image](https://user-images.githubusercontent.com/575138/221239365-714ab775-3a92-435d-bc7a-b4832f4ff3fb.png)

4. Check it tries to translate with a fixed `en` location:
![image](https://user-images.githubusercontent.com/575138/221239473-12231e3b-e25d-487c-95d3-a4c1a34699b8.png)

### Expected behavior & Actual behavior
Should use the correct location, not always `en`

### Models and resource files
```ruby
class ProductMeasureUnitResource < Avo::BaseResource
  self.title = :title
  self.includes = []
  self.search_query = -> do
    scope.ransack(id_eq: params[:q], m: "or", unit_cont: params[:q], description_cont: params[:q]).result(distinct: false)
  end

  field :id, as: :id
  field :measure_unit, as: :text
  field :description, as: :text

  tabs do
    field :from_product_conversions, as: :has_many, translation_key: 'avo.field_translations.from_product_conversions'
    field :to_product_conversions, as: :has_many, translation_key: 'avo.field_translations.to_product_conversions'
    field :product_measures, as: :has_many
  end

  action ExportToCsv
end
```

### System configuration
**Avo version**: 2.26.0
**Rails version**: 7.0.3.1
**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [X] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [X] High urgency (some users can't read English)
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
I'll have a look and have a fix in the next release (next Tuesday).
