### ISSUE TITLE
Unable to build custom dashboard dependent on current user

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1604]
Currently, it is not possible to create a custom dashboard in the Avo gem that displays cards based on the logged-in user and existing entries in the database. The intended use case is a corporate dashboard where company administrators can view user activity on the platform. To achieve this, the dashboard class needs to make effective use of the logged-in user. However, this can only be partially achieved using the context object. Firstly, internal caching causes cards to "disappear" for different users (potentially the same issue as #1507). Secondly, the current_user can only be accessed within the visible and authorisation blocks. Also, using Avo::App.context[:current_user] prevents the production environment from starting as it is null at this point.

i would appreciate input and ideas on this topic, as we would like to make avo accessible to non-admin users as well.

**Comment by adrianthedev** [comment]
Are they really two dashboards or a variant of the same one?

Can you create two dashboards, and use the `self.visible` block to conditionally show them to your users?

**Comment by FLX-0x00** [comment]
I always use two dashboards, one company dashboard and one admin dashboard. Visibility works fine. But our plattform offers different type of products and these type of products are handled in differerent ways. For example one company admin visit his dashboard and his employees accessed only a few products, i would like to render only the cards for the products that his employees used. Or using conditional views (renders chart view only if product is used by minimum 2 users). Hope you can understand what i am try to build.

**Comment by adrianthedev** [comment]
Ok. So a `self.visible` option would work for you? You would have access to the `current_user`.

> Firstly, internal caching causes cards to "disappear" for different users (potentially the same issue as https://github.com/avo-hq/avo/issues/1507).

I'd like to hear more about that. Can you share a reproduction repo or video?

> Also, using Avo::App.context[:current_user] prevents the production environment from starting as it is null at this point.

Same here. I'm not sure I understand the issue. Isn't that valid case? when the app boots up there isn't a request object, thus no user.

**Comment by FLX-0x00** [comment]
Maybe i overlooked this, but i can not see that current_user is accessible in the Avo::DashboardsController Class directly.

![image](https://user-images.githubusercontent.com/26464774/222221796-87bdb8bd-0a78-4089-92d8-112930a83ea7.png)

![image](https://user-images.githubusercontent.com/26464774/222221933-09f56a9e-0243-431c-9436-a84005bc1d58.png)

Caching ... i will record a video and send you via email with a reference to this issue.

**Comment by FLX-0x00** [comment]
current_user is a method that is not available in a class - only in a method. Dashboards are defined in classes so i have only access to current_user if a method is called. So only the context variable can be used with the current user bound to...and the Dashboard has to catch if the context is present or not? Is that an intended solution?

**Comment by adrianthedev** [comment]
<img width="515" alt="CleanShot 2023-03-01 at 19 55 55@2x" src="https://user-images.githubusercontent.com/1334409/222222517-7d1efed5-0241-43cb-a8d3-ba8ae0cc2ad9.png">
this is not going to work.
The reason is that the class is being evaluated on boot time (most likely) where there's no request.
That's why the fields and most other entities have a `visible` block that can be evaluated on runtime when there's a `request` and a user available.

You'll soon be able to do this (in one or two days).

`divider label: "something", visible -> { current_user.has_role? :admin }`

**Comment by FLX-0x00** [comment]
Okay, nice. If this will work with cards then it is perfect.

**Comment by FLX-0x00** [comment]
@adrianthedev is it possible to access current_user in a Avo::Dashboards::MetricCard ? we actual use Avo::App.context[:user] and set the current_user in the context. Is that a intended solution?

**Comment by FLX-0x00** [comment]
Thank you adrian, for your incredible fast responses! Awesome to work with you. We will get another avo licence too for our next project ;)

**Comment by adrianthedev** [comment]
Hey @FLX-0x00.

Please give [`2.27.2.pre.pr1606`](https://rubygems.org/gems/avo/versions/2.27.2.pre.pr1606) a try and let me know if that works for your use-case.
Please watch this video, where I go through how I built that feature and how it's supposed to be used.

https://www.youtube.com/watch?v=2LpaP8UdzxY

**Comment by FLX-0x00** [comment]
Thanks, i will go into later that day and provide detailed feedback!

**Comment by FLX-0x00** [comment]
Wow. This works so great. Also thanks to your small coding session - we enjoyed the deeper look into avo and learned a lot of internals. We also will go into sponsorship and looking forward to work even closer to you.

**Comment by adrianthedev** [comment]
Wow! Thank you for your support! We appreciate the help!

Please join our [Discord](https://avo.cool/chat) to add you to our #sponsors channel.
