### ISSUE TITLE
Class attribute for Eager loading not working

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1605]
### Describe the bug
This is not working: https://docs.avohq.io/2.0/resources.html#eager-loading
I went and debugged, looks like that includes is not been setting the value, every time we get an empty array, so tried to use another class_attribute on base_resource.rb, like "includes_sym," and replaced on base_controller, and it worked.

### Steps to Reproduce
1. Add include to a resource
2. Now try to fetch it, and you will see n+1 queries there

### Expected behavior & Actual behavior
To work

### System configuration
**Avo version**: 2.27.1

**Rails version**: 7.0.4

**Ruby version**: 3.2.0

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Can you please share more details please? The eager loading seems to be working on my end.
