### ISSUE TITLE
Clashing Tailwind types and regular css when using Tailwind on ejected components and tools

### ISSUE THREAD

**Issue by tholman** [avo-hq/avo#1607]
Hi ya'll

Running into a css priority issue when using the tailwind asset pipeline suggested, predominantly the avo styles have a higher priority than anything added in the pre head, which means that the avo base, which includes styles with tags like:

 ```[multiple], [type=date], [type=datetime-local], [type=email], [type=month], [type=number], [type=password], [type=search], [type=tel], [type=text], [type=time], [type=url], [type=week], select, textarea```

will override any tailwind styles put on inputs that aren't included already in the avo tailwind. For example, I have an 

`<input type="text" class="border-2" />` in an ejected component the avo styles will take priority preventing the the introduced tailwind classes. 

<img width="494" alt="Screenshot 2023-03-02 at 4 02 09 PM" src="https://user-images.githubusercontent.com/794999/222551558-888ecae7-e6eb-4caa-94b3-0f8f47699f2c.png">

<img width="505" alt="Screenshot 2023-03-02 at 4 02 16 PM" src="https://user-images.githubusercontent.com/794999/222551556-45714f3e-ae05-4ecf-9ded-398ed5ce662c.png">

There are also naturally a whole lot of duplicated css in the application where the two tailwinds are fighting
...

To get around this, I've currently vendored the avo gem, and prioritized my own tailwind install over the avo components base, which gives the tailwind styles full priority and inclusion, but naturally introduces it's own problems like mismatching colors/priority issues.

Just looking for any direction into reconciling this if at all possible

Cheers !

**Comment by adrianthedev** [comment]
Thanks, @tholman for writing this.
I know it's not the best technique for handling Tailwind, and we'll have a better way to do it in Avo 3 (post-launch).

Are you able to run with that setup for now?

**Comment by adrianthedev** [comment]
Got it.
Let me know if there are any.

Thank you for understanding; we're really on the last stretch with Avo 3 and want to focus all our efforts on the release.
I'll get back to you when we have something worth showing.

**Comment by tholman** [comment]
Closing as #wontfix, current complete tailwind override maintainable on the medium term

**Comment by adrianthedev** [comment]
We have a new approach we're testing with Avo 3 that we'll end up exposing to the users.

We have a task that finds the gem path (BUNDLE_PATH/avo), we create all the requires whitelisting paths (app/views, app/components, etc.) and add to your current paths (your app/views, your app/components) and rebuild the assets on your app.

This will ensure you only have one Tailwind config in your app that handles the admin.

**Comment by veelenga** [comment]
@adrianthedev that is very promising, great work 👍 

Are there any plans to backport this to avo 2? That may reduce the complexity of migrating to avo 3 in the future.

**Comment by adrianthedev** [comment]
I want to be honest and say that probably not. 
We're focusing all our efforts on finishing and releasing Avo 3.
