### ISSUE TITLE
Validation messages change in Rails 7.1.0.alpha

### ISSUE THREAD

**Issue by zzak** [avo-hq/avo#1611]
Hello!

Reporting this because I noticed you had some tests against the validation messages:
https://github.com/avo-hq/avo/blob/a51ee9aa36bc002ecfe5478265e49a6a380c467d/spec/system/avo/user_forms_spec.rb#L38-L47

While I'm not sure these are coming from Rails, I wanted to let you know that in rails/rails#45463 we changed the apostrophe in the user-facing default messages.

If you are impacted by this, could you try testing against Rails `main` branch?

Thank you!

**Comment by adrianthedev** [comment]
Yes, this makes sense.
We'll add Rails 7 to the CI system with Avo 3.
