### ISSUE TITLE
Association creation from friendly_id record

### ISSUE THREAD

**Issue by simonhutchings** [avo-hq/avo#1613]
Page mode has 
```
extend FriendlyId
friendly_id :menu_title, use: [:slugged, :globalize]
```

Page resource has:

```
self.resolve_find_scope = ->(model_class:) do
  model_class.friendly
end
```

error at 

`284  raise(RecordNotFound.new("Couldn't find #{name} with '#{key}'=#{id}", name, key, id))`

But when I create from an association panel i get, "Couldn't find Page with 'id'=home-page", yet it works no problem to see and update the page itself

### System configuration
**Avo version**:

**Rails version**: 2.27.1

**Ruby version**: 3.1.3

**License type**:

 - [x] Community
 - [ ] Pro

converting to pro when project finished

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @simonhutchings. 
Yeah, we expected some friction with that PR. But it's ok because it's all for the better.

Can you tell me what kind of association you're trying to create? Show me the association and the resource fields and where are you trying to use them.
Please give me more information, so I'm able to recreate it on my end. Id like to push a fix ASAP.

**Comment by simonhutchings** [comment]
Page has many page panels as parent, and has a friendly_id set through :menu_title which is in the translation table. I guess on associations you need to check if model has friendly_id set. After all it is one of most used gems out there. That potentially would get rid of the need to add resolve_find_scope into a resource.

```
class Page < ApplicationRecord
  has_many :page_panels, -> { order(position: :asc) }, as: :parent, dependent: :destroy

  translates :title, :meta_keywords, :meta_description, :description, :menu_title, :menu_description, :browser_title, :slug, fallbacks_for_empty_translations: true, touch: true
  accepts_nested_attributes_for :translations
  
  extend FriendlyId
  friendly_id :menu_title, use: [:slugged, :globalize]
end
```

Page panel belongs to polymorphic parent, does not use friendly_id or translations. Page block below that model would have both, but at the moment have not migrated that over as rebuilding from scratch, so minimised the code here!

```
class PagePanel < ApplicationRecord
  acts_as_list scope: :parent_id, add_new_at: :bottom
  serialize :settings, Hash
  
  belongs_to :parent, polymorphic: true, touch: true
end
```

**Comment by adrianthedev** [comment]
Cool. Thanks! I'll try and release a fix in the next few days. Please use the previous version of Avo until then if this is a blocker.

**Comment by adrianthedev** [comment]
Hey @simonhutchings can you try removing the `self.resolve_find_scope` option and use this one instead?

```ruby
  self.find_record_method = ->(model_class:, id:, params:) do
    model_class.friendly.find id
  end
```

**Comment by simonhutchings** [comment]
Yes that works!

**Comment by adrianthedev** [comment]
Cool! I'll add that to the upgrade guide. Thanks!

Closing for now

**Comment by adrianthedev** [comment]
Upgrade guide: https://docs.avohq.io/2.0/upgrade.html#upgrade-from-2-26-to-2-27
