### ISSUE TITLE
Issue with dynamically tags with fetch_values_from. Labels are not printed, only ids

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1619]
### System configuration
**Avo version**: 2.27

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [ X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X ] No

## Description
Following the instructions give in this video https://www.youtube.com/watch?v=YzQHMo5NdoI&t=186s I have been able to load records from table using fetch, without problems.
The label/value data are stored successfully in the DB as array of ids `["25","365","564"]`

  ## The issue
Once the ids are stored and load the show page, the ids are printed without label, instead to print the labels.
<img width="653" alt="Screenshot 2023-03-09 at 13 19 06" src="https://user-images.githubusercontent.com/106058674/224021164-55129408-6ce0-43a2-a22e-9017d976c8b9.png">

If you edit this record the ids appears in red and are removed in the field. So on every edit I need to select again the tags

https://user-images.githubusercontent.com/106058674/224022010-80e674fc-6bb1-43ac-9300-051e39d068a1.mov

I suppose that it is caused because on show, the fetch to get the labels for stores values is falling, and can not represent the labels.

My code:
In main model resource:
```ruby
field :add_sampler_ids, as: :tags, fetch_values_from: -> {"/avo/resources/samplers/get_samplers?record_id=#{resource&.model&.id}"}
```
In my AVO controller:
```ruby
def get_samplers
    samplers = Sampler.all.map do |sampler|
      {
        value: sampler.id,
        label: sampler.user.email
      }
    end
    render json: samplers
 end
```
In routes.rb:
```ruby
if defined? ::Avo
  Avo::Engine.routes.draw do
    scope :resources do
      get "samplers/get_samplers", to: "samplers#get_samplers"
    end
  end
end
```

Any idea about the solution? Something in my code or AVO issue?

**Comment by adrianthedev** [comment]
I see.

What's happening there is that you're storing ids in that field (`add_sampler_ids`); the `value`, and `label` hashes you return from the controller are not persisted in that field. 
Avo doesn't know how what is the "pretty name" for those ids. 

Let me look into it next week and push an update.

**Comment by angel-checkealos** [comment]
Fine, but I don't use fetch_values_from, the process works fine. I suppose that this is because of it has preloaded all the values...
I suppose that the solution should be to do a fetch with the ids to compose the pairs label/value.

I wait for your review. Thanks in advance

**Comment by adrianthedev** [comment]
## Approach

We should provide with a block `fetch_labels` that will have the `value` available and where the user can add their own logic to fetch the labels

```ruby
# pseudo-code
field :tags, as: :tags,
  fetch_values_from: -> { URL },
  fetch_labels: -> { Tags.find(value).pluck(:name) }
```
