### ISSUE TITLE
Allow users to choose along different 'view' modes

### ISSUE THREAD

**Issue by JeremasPosta** [avo-hq/avo#1626]
### Feature

Adds the ability to have a kind of 'profiles' to allow the users to perform a different set of tasks in a more ordered way.

As user_1 performing task `task_1` I want to see on my resource's `show` and `edit` views only the fields belonging to `task_1` set.
As user_1 performing task `task_2` I want to see on my resource's `show` and `edit` views only the fields belonging to `task_2` set.
### Current workarounds

I implemented it somehow ejecting the `base/edit` renderer file, and force-hiding the undesired fields with some JS within that file.
For choosing what to show or not, I added an action to change between 'edit modes'
### Screenshots or screen recordings

N/a
### Additional context

N/a

**Comment by adrianthedev** [comment]
Thanks for your suggestion.

I'm trying to understand the use-case better.
Is this related to an event (performed task_1 or task_2) or related to the state of that record (if record.published == true { show these fields } else {show other fields})?

**Comment by JeremasPosta** [comment]
Related to the state of a record could work because we can extend it
 >  (if record.published == true { show these fields } else {show other fields}

 but I implemented something like this to fit our needs:
 > (if current_user.working_on_a_specific_task == true { show these fields } else {show other fields}
 
 The thing is resources can get enormous very quickly.
 If today as a user I'm working on eg, 'Adding customer's notes', I want to be able to activate the 'Adding notes' edition mode. So, the fields I see on my edit page can be trimmed and display only the required fields.

This is useful for hiding other fields I don't want to edit by error and to find the required more easily.

**Comment by JeremasPosta** [comment]
My respects! I missed completely that feature!

I believe
```
field :name, as: :text, visible: -> (resource:) { current_user.working_on_a_specific_task }
```
should work pretty well for what I need to do.

Thanks a lot! I will give it a try these days. 😄
