### ISSUE TITLE
Defunct cruft in generated Avo config.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1633]
https://github.com/avo-hq/avo/blob/39f6f8e1d24247749fdad1e1d1be13323f09f7c7/lib/generators/avo/templates/initializer/avo.tt#L64

The `resource_controls` option that got renamed is still referenced in the template produced by the avo generator.

**Comment by adrianthedev** [comment]
Thanks for this. I marked it as a good first issue, maybe someone can pick it up and fix it.

## Approach

Remove the `# config.resource_controls = :right` line from `avo.tt`.

**Comment by Aaryanpal** [comment]
Hey @adrianthedev , 
Could you assign this to me i would like to work on this issue

**Comment by adrianthedev** [comment]
Done 🙌 and Thank you 🙏
