### ISSUE TITLE
Destroy attachment form using turbo frames

### ISSUE THREAD

**Issue by ali-haider-eqt** [avo-hq/avo#1645]
### Context
Hey AVO team, I am facing an issue with deleting an attachment in one of my resource (Product) and to delete attachments I have also defined policies i.e

```
  def delete_attachments?
    true
  end
```

Attachment destroying successfully but unfortunately it is not reflecting changes on frontend and giving an error

> Uncaught (in promise) Error: The response (200) did not contain the expected <turbo-frame id="destroy_attachment_form"> and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.

I don't see any guidelines in AVO document to add turbo frame into resource field, so for quick handling I have passed `turbo_visit_control: "reload",` in my file field but still same issue. Any kind of help would be grateful. Thanks!

### System configuration
**Avo version 2.28.0**:

**Rails version 7.0.4**:

**Ruby version 3.1.2**:

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1680" alt="Screenshot 2023-03-23 at 1 28 14 PM" src="https://user-images.githubusercontent.com/105207904/227145606-1a20967c-3edc-438c-977c-c45a301a25a7.png">

**Comment by adrianthedev** [comment]
I was able to reproduce it.
I'll try to push a fix today (tomorrow the latest).
