### ISSUE TITLE
Avo not referencing Friendly ID when creating polymorphic resource

### ISSUE THREAD

**Issue by curreta** [avo-hq/avo#1648]
### Describe the bug
When trying to add a polymorphic resource using Avo, the lookup for the associated model fails because Avo is not referencing the Friendly ID for the associated model. 

### Steps to Reproduce

    Visit the avo Product show page.
    Click Create New Photo from the Product page.
    Error occurs.

### Expected behavior & Actual behavior

ActiveRecord::RecordNotFound at /resources/photos/new
Couldn't find Product with 'id'=sistema-9-6-in-rectangular-storage-bin
Error occurs on line:

https://github.com/avo-hq/avo/blob/0fe20f939b81ba4f563419ab131d7b52f4bf37e3/lib/avo/base_resource.rb#L385

I believe this should be referencing the find_record_method somehow?

### Models and resource files
```ruby
class ProductResource < Avo::BaseResource
  self.title = :name
 # ...
  field :id, as: :id
  # Fields generated from the model
  field :name, as: :text, link_to_resource: true, help: 'Shown on the product page'
  field :photos, as: :has_many, hide_on: %i[index]
  # ...
  self.find_record_method = lambda { |model_class:, id:, params:|
    model_class.friendly.find id
  }
end
```

```ruby
# frozen_string_literal: true

class PhotoResource < Avo::BaseResource
  self.title = :id
  self.includes = [:imageable]
  # self.search_query = -> do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id
  # Fields generated from the model
  field :title, as: :text
  field :description, as: :textarea
  field :image, as: :file
  field :main, as: :boolean
  field :imageable, as: :belongs_to, polymorphic_as: :imageable, types: [::Product]
  # add fields here
end
```

### System configuration
**Avo version**:
2.28.0
**Rails version**:
7.0.4.3
**Ruby version**:
3.2.1
**License type**:

 - [ x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

#### Impact

 - [ ] High impact
 - [x ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Thanks for reporting this. I'll look into it tomorrow.
