### ISSUE TITLE
Dynamic options in belongs_to field

### ISSUE THREAD

**Issue by thiagovsk** [avo-hq/avo#1650]
Hi guys, I need some help here!

is there a way to query belongs_to field based on another model id?

For example, I have 3 models, User, User Category, and Company

```
class User < ApplicationRecord
  belongs_to :company
  belongs_to :user_category
end

class UserCategory < ApplicationRecord
  belongs_to :company
  has_many :users
end

class Companyy < ApplicationRecord
  has_many :users
  has_many :users
end
 ```

And I have the follow userResource form

```
class UserResource < Avo::BaseResource
  heading "Company", only_on: :new
  field :comapany, as: :belongs_to
  
  heading "User Categories", only_on: :new
  field :user_category, as: :belongs_to
end
```
in my case, I would like to show in user_categories belongs_to select, only user_categories that match with the previous company selected

In the new user form
1- first select the company
2- select the user_category where company_id is the company_id that I previous selected

It's possible with some js or something? Because it's not possible, I need to create users and companies and after that create user_categories

Thanks, guys!

**Comment by adrianthedev** [comment]
Thanks for writing this ticket @thiagovsk. I have some baby chores this evening and will try to answer. I'll do it tomorrow if I can't do it tonight.

**Comment by thiagovsk** [comment]
> Thanks for writing this ticket @thiagovsk. I have some baby chores this evening and will try to answer. I'll do it tomorrow if I can't do it tonight.

@adrianthedev thanks for helping me, take your time, it's not urgent haha

Regards

**Comment by adrianthedev** [comment]
Hey @thiagovsk.
Yes, that can be done with a bit of custom code in Avo.

Please check out [this link](https://main.avodemo.com/avo/resources/courses/150/edit) ([source code here](https://github.com/avo-hq/main.avodemo.com)) where when you change the country select, the city field repopulates with cities from that country.

See [this video](https://youtu.be/ZMOz22FaAUg?t=905) where I build that feature and the guide [here](https://docs.avohq.io/2.0/stimulus-integration.html#custom-stimulus-controllers).

In Avo 3 we're working on making that kind of interaction happen without any JS code from your side.

**Comment by thiagovsk** [comment]
@adrianthedev tks for sharing this!!!!
I appreciate our job with avo!
