### ISSUE TITLE
Filled field was not recognized by AVO after using "readonly: true"

### ISSUE THREAD

**Issue by dailson-igo** [avo-hq/avo#1657]
Ruby: 3.1.2p20
Rails: 7.0.4.3
Avo: 2.29.1

When I set a field to read-only after assigning a value to it:

```
field :user, as: :belongs_to, default: -> { Avo::App.context[:current_user].id }, readonly: true
```

Avo reports the following message when trying to save
- You might have missed something. Please check the form.
- Validation failed: User must exist

Although Avo indicates the presence of a mandatory field, the **AVO saves the record normally, as if it had not given any validation error.** Looks like Avo doesn't accept receiving parameter set to read-only

```
Started POST "/avo/resources/schedulings?via_relation=room&via_relation_class=Room&via_resource_id=4" for 127.0.0.1 at 2023-03-31 12:08:35 -0300
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]

Processing by Avo::SchedulingsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "via_resource_id"=>"4", "via_relation"=>"room", "scheduling"=>{"room_id"=>"4", "user_id"=>"1", "booked_at"=>"2023-04-02T13:00:00.000-03:00", "booked_for"=>"8"}, "fake_booked_at"=>{"fake"=>"2023-04-02 13:00:00"}, "button"=>"", "via_relation_class"=>"Room"}

Unpermitted parameter: :user_id. Context: { controller: Avo::SchedulingsController, action: create, request: #<ActionDispatch::Request:0x00007fe3b32ed3a0>, params: {"authenticity_token"=>"[FILTERED]", "via_resource_id"=>"4", "via_relation"=>"room", "scheduling"=>{"room_id"=>"4", "user_id"=>"1", "booked_at"=>"2023-04-02T13:00:00.000-03:00", "booked_for"=>"8"}, "fake_booked_at"=>{"fake"=>"2023-04-02 13:00:00"}, "button"=>"", "via_relation_class"=>"Room", "controller"=>"avo/schedulings", "action"=>"create"} }

```
However, when I remove the read-only setting or change from "readonly: true" to "disabled: true"
```
field :user, as: :belongs_to, default: -> { Avo::App.context[:current_user].id }
```

The AVO saves normally, without error message.
```
Started POST "/avo/resources/schedulings?via_relation=room&via_relation_class=Room&via_resource_id=4" for 127.0.0.1 at 2023-03-31 12:07:05 -0300
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]


Processing by Avo::SchedulingsController#create as TURBO_STREAM

  Parameters: {"authenticity_token"=>"[FILTERED]", "via_resource_id"=>"4", "via_relation"=>"room", "scheduling"=>{"room_id"=>"4", "user_id"=>"1", "booked_at"=>"2023-04-02T16:00:00.000Z", "booked_for"=>"8"}, "fake_booked_at"=>{"fake"=>"2023-04-02 13:00:00"}, "button"=>"", "via_relation_class"=>"Room"}


  TRANSACTION (0.1ms)  begin transaction
  Room Load (0.2ms)  SELECT "rooms".* FROM "rooms" WHERE "rooms"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  

  Scheduling Create (0.4ms)  INSERT INTO "schedulings" ("room_id", "user_id", "booked_at", "booked_for", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["room_id", 4], ["user_id", 1], ["booked_at", "2023-04-02 16:00:00"], ["booked_for", 8], ["created_at", "2023-03-31 15:07:05.453246"], ["updated_at", "2023-03-31 15:07:05.453246"]]


  TRANSACTION (3.9ms)  commit transaction
```

**Comment by adrianthedev** [comment]
So, if I understand correctly, you want to display the field as disabled in the UI but when someone submits the form, have the user field properly populated with the `current_user.id` in that new record in the DB.
Is my assumption correct?

**Comment by dailson-igo** [comment]
The problem is that AVO reports that the User field has not been filled in, when in fact it is. But it only shows this message wrongly when the filled field is set to "readonly: true". Even with the message about the absence of information, the record is normally saved with all the fields, as if AVO had not informed about the absence of any field. When I replace "readonly: true" with "disabled: true", everything works normally.

**Comment by adrianthedev** [comment]
So, can't you use `disabled` instead of `readonly` and have this issue fixed? Is there anything I'm missing to understand why you won't use `disabled`?

It is by design that the `readonly` is not filled to the record. 
We explain why on the documentation.

<img width="743" alt="CleanShot 2023-04-03 at 16 37 25@2x" src="https://user-images.githubusercontent.com/1334409/229526352-64275810-7db8-4a1f-b4be-727bc5b9caea.png">

**Comment by dailson-igo** [comment]
But if he doesn't pass the parameter when it's configured as "readonly: true", how did he correctly save the user's information in the database?

I had set the field as "readonly: true" because I watched the videos [Build a booking app in less than an hour with Rails and Avo Admin](https://www.youtube.com/watch?v=BK47E7TMXn0) and at 8:33 the field was configured this way, but maybe it was in an earlier version of Avo where it worked differently.

**Comment by adrianthedev** [comment]
I'm sorry for the confusion in the video. That was an older version, and we changed the way `required` works just so we can mitigate that security flaw.

So, using `disabled` would make it work the way you want it?

**Comment by adrianthedev** [comment]
Closing this as resolved. Feel free to reopen
