### ISSUE TITLE
Create an `inherit_from_policy` helper for associations authorization

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1663]
### Feature

Currently, if you want to replicate the general resource policy methods for that resource as an association, you have to either duplicate the logic or to call the same policy method for each method.

We should have a helper that generates those methods from the parent policy automatically and let the user override them if needed.

```ruby
# before
def create_users?
  Pundit.policy!(user, record).create?
end


def edit_users?
  Pundit.policy!(user, record).edit?
end

...etc.

# after
  include Avo::PolicyHelpers
  inherit_association_from_policy :team_members, TeamMembersPolicy
```

Naming TBD.
This might require adding a module to that policy.

**Comment by Paul-Bob** [comment]
I'm not sure if this kind of code organization is our responsibility to maintain. If i understand it well, what the request describes can be easily achieved by includes:

app/
├─ policies/
│  ├─ associations/
│  │ ├─ comments.rb
```ruby
module Associations
  module Comments
    def attach_comments?
      false
    end

    def detach_comments?
      false
    end
  end
end
``` 

Now whenever you want to apply the comments associations policy you just need to `include Associations::Comments`

For example:
app/
├─ policies/
│  ├─ project.rb
```ruby
class ProjectPolicy < ApplicationPolicy
  include Associations::Comments
end
``` 

app/
├─ policies/
│  ├─ post.rb
```ruby
class PostPolicy < ApplicationPolicy
  include Associations::Comments

  # Override included method
  def attach_comments?
    true
  end
end
```

**Comment by Paul-Bob** [comment]
@adrianthedev I think i made some confusion, the idea is not to reuse the code, is to apply on associations the same policy that associated model have on his own policy, my bad, it make sense now...

**Comment by Paul-Bob** [comment]
I have a suggestion for this one, what if we apply it by default without that `inherit_as_association_from_policy :users, UsersPolicy`? And user can override it?

**Comment by adrianthedev** [comment]
You are corect in your second comment. 
It’s about making it easier to crwate and maintain those policy methods. The biggest issue is that the method logic is almost always duplicated from the parent policy. 

I mostly agree woth your suggestion to automatically use the parent policy methods. 
One thing we must take into account is when when users use a different policy for a resource. The helper gives them a way of specifying which policy to use. 

That’s why I was thinking of having the helper as the first iteration, but I’m open to suggestions.

**Comment by Paul-Bob** [comment]
> One thing we must take into account is when when users use a different policy for a resource.
I think we can access the right policy through the resource. Anyway the helper will avoid the breaking change,  you're right, it's a better choice for the first iteration.
