### ISSUE TITLE
The link_to menu item path should take a block and have the current_user available inside. Same for `label`.

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1665]
### Feature

You might want to create a menu link that redirects to the current users account page. That link, is currently static and not dynamic.
Let's make the `label` and `path` take a block.

**Comment by Paul-Bob** [comment]
That's static but we can achieve that by string interpolation...

Example:
`link_to "Search #{current_user.name}", "https://google.com/search?q=#{current_user.name}", target: :_blank`

@adrianthedev do we really want to make the label and path callable? Current user is already available when declaring the links

**Comment by FLX-0x00** [comment]
I will check this out on our environment as this kind of feature request comes from us initially.

**Comment by Paul-Bob** [comment]
That would be great @FLX-0x00, thank you! The implementation is quite simple, actually already have it implemented on a local branch but for the specified use case I think isn't worth since the the desire result can be achieved by interpolation.

**Comment by FLX-0x00** [comment]
okay, interpolation works - you are right. Is there any chance to get the path helpers from the routes on this? If i use something like resources_user_path(current_user) it will fail as it can not find the method on main:object.

**Comment by FLX-0x00** [comment]
This is exactly what i am searching about! Thank you very much for pointing this out. I think the issue can now be closed as its possible with default rails magic without introducing anything new.

**Comment by Paul-Bob** [comment]
I'm glad  you made it! Closing the issue in favor of "default rails magic"! =))
