### ISSUE TITLE
There currently isn't a way to sign out using rodauth

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1666]
### Feature

Rodauth requires the sign-out link to acutally be a post request to a path.

Maybe we should offer a more low-level way to customize that link. Maybe using a special partial somehow where the user can ass a custom form.

**Comment by FLX-0x00** [comment]
Will we have an option for this in avo 3?

**Comment by FLX-0x00** [comment]
is there any progress on avo3 on this @adrianthedev ?

**Comment by adrianthedev** [comment]
I know that rodauth is using a form to sign out from the app, not just a GET request.

I wonder if we can extend our `link_to` from the menu builder to support that
I feel like this line will create the item we need in the profile menu.

`link_to "sign out", rodauth_signout_path, method: :delete, class: 'text-red-600'`
