### ISSUE TITLE
Make option sortable overwritable by user on id field type 

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1676]
### Context
The ID field is sortable regardless of the options given. I think its better to make the field only sortable if the user decides to make them sortable - but that may break existing views. Often something like hashids is used and the ID field is perfect for this as it hides on forms and is readonly by default. I know - the same approach can be done with `as: :text, readonly: true, hide_on: :forms`. The idea is simply to keep the option to true by default but accept the option false on `sortable` when given.

### System configuration
**Avo version**:
Latest and greatest

**Rails version**:
7
**Ruby version**:
3.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
```ruby
field :hashid, as: :id, link_to_resource: true, sortable: false
```
Direct link to the code snippet: https://github.com/avo-hq/avo/blob/572cfbef61231f66a945418429e2749b757c2734/lib/avo/fields/id_field.rb#L8

**Comment by adrianthedev** [comment]
Yes, I agree that it should be configurable.

I'll add it to the roadmap.
