### ISSUE TITLE
Reorder records using drag and drop

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1680]
### Feature

It would be cool and useful to have a drag-and-drop interface to reorder the records.

### Current workarounds

The reorder feature has an "arrow-up/down", "move to top/bottom" system.

### Screenshots or screen recordings

![CleanShot 2023-04-15 at 08 19 29@2x](https://user-images.githubusercontent.com/1334409/232184617-2601b5e9-481d-4a11-b0b5-e9da2823bc6f.png)

**Comment by FLX-0x00** [comment]
Sounds cool. Where do you store the information about which items are in which position?

**Comment by adrianthedev** [comment]
That's up to you, really. You can use your own implementation or something like `acts_as_list` gem.

More on this in the [docs](https://docs.avohq.io/2.0/records-reordering.html). There's even a video on the top with me demoing the feature.

**Comment by adrianthedev** [comment]
Closed by https://github.com/avo-hq/avo/pull/2574
