### ISSUE TITLE
The `visible` field option should render the field but make it hidden

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1685]
### Feature

Right now, the field is not rendered at all.

**Comment by FLX-0x00** [comment]
Make sense - quick question. I cannot find a hint on the avo docs for making field level authorization. Maybe not the right place to talk about this since hiding fields will not prevent updates, but maybe you can provide a nudge on this. Maybe this is an expert thing?

I think a lot of cases will be hiding a specific field and preventing from updating. Just random thoughts - open to discussions on this.

**Comment by adrianthedev** [comment]
You can hide fields using the `visible` option.

[Docs](https://docs.avohq.io/2.0/field-options.html#field-visibility)

```ruby
field :name, as: :text, visible: -> { current_user.is_admin? }
```

**Comment by adrianthedev** [comment]
Hmmm... maybe I didn't understand the problem?

>  hiding fields will not prevent updates

What do you mean?
Can you provide an example scenario?

**Comment by FLX-0x00** [comment]
We have two roles for example: admin, company_admin
And we have a company object

Company:
- hashid
- name
- logo_url

The admin can change everything. The company admin can only change the name of his own Company object, but he should not be able to change the logo_url. Only admins should be able to update the logo_url.

A company admin is able to change the logo_url even if it is not visible, because he has the update? policy.

Makes more sense?

**Comment by segiddins** [comment]
We currently use `visible` to hide sensitive fields -- if they start getting rendered, that would leak information to users who aren't supposed to have it

**Comment by adrianthedev** [comment]
Yes. That makes sense. I think I was too quick to create this issue. 

This type of functionality can be addressed using the `hidden` field. 

Closing for now.

**Comment by FLX-0x00** [comment]
Thanks. What about blocking users from updating specific columns? As discribed in my second comment

**Comment by adrianthedev** [comment]
So you have two options there:

1. Hide the field altogether with `visible: ->(resource:) { current_user.some_condition? }`. Now only the users that see that field will be able to edit it.
2. Use the `readonly` option (with a similar block like above) which will render the field as disabled and even if a bad actor re-enables the field in the DOM, that value will not be passed to the record.

Does that make sense?

**Comment by FLX-0x00** [comment]
okay perfect, thanks for making this clear to me @adrianthedev

**Comment by FLX-0x00** [comment]
@adrianthedev Hold! the visible option does not preventing the user from updating a field that is not visible / rendered to the user. 

My setup: Lets say we haven an object `Company` and two roles (`admin` and `company_admin`)

Company
- name
- secret

Company policy

```ruby
  def edit?
    user.has_any_role? :admin, :company_admin
  end

  def update?
    edit?
  end
```

Lets say the we want only admins be able to view and edit the `secret` field. We define our resource file as follows:

```ruby
class CompanyResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  
  field :name, as: :text, sortable: true
  field :secret,
        as: :code,
        language: 'nothing',
        theme: 'dracula',
        visible: -> (resource:) { @current_user.has_role? :admin }
end
```
A user with the role `company_admin` assigned is able to update the `name` of course. But intecepting the request in burp and modify the request from
```
------WebKitFormBoundary5QxIRjlUVWxckH7R
Content-Disposition: form-data; name="company[name]"

CONTENT
```

to


```
------WebKitFormBoundary5QxIRjlUVWxckH7R
Content-Disposition: form-data; name="company[secret]"

CONTENT
```

the request will update the field `secret` even if its not visible. The only way to prevent this is the `readonly` option using this syntax in the resource:

```ruby
  field :secret,
        as: :code,
        language: 'nothing',
        theme: 'dracula',
        visible: -> (resource:) { context[:user].has_role? :admin },
        readonly: -> { !@current_user.has_role? :admin }
```

so @adrianthedev can you please revisit this and take a closer look as this is important for our avo experience.

**Comment by adrianthedev** [comment]
Hmmm. Ok. Checking it.

**Comment by Paul-Bob** [comment]
@FLX-0x00 i opened a new issue relatively to your last comment, you can track it [here](https://github.com/avo-hq/avo/issues/1695)

**Comment by Paul-Bob** [comment]
> Yes. That makes sense. I think I was too quick to create this issue.
> 
> This type of functionality can be addressed using the `hidden` field.
> 
> Closing for now.
