### ISSUE TITLE
Error when click on a link on the dashboard

### ISSUE THREAD

**Issue by gabojkz** [avo-hq/avo#1686]
### Context
I created a model an a resource as explained in the documentation but I get undefined method `new_resources_expense_path'

### System configuration
**Avo version**:  /bundle/ruby/3.2.0/gems/avo-2.30.0

**Rails version**: 7

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1179" alt="Screenshot 2023-04-17 at 11 26 56" src="https://user-images.githubusercontent.com/11217929/232458935-bb26a39a-1be2-4c58-b870-1b9cf7e85414.png">

**Comment by adrianthedev** [comment]
Can you please post the mode and resource code?

**Comment by gabojkz** [comment]
sorry I deleted the code to continue working on something else is a newly created app on ROR 7
