### ISSUE TITLE
Mounting AVO to a subdomain

### ISSUE THREAD

**Issue by ProGM** [avo-hq/avo#1692]
### Describe the bug
I've tried to map AVO to a subdomain, but it fails to respond, returning the default page of Rails.

### Steps to Reproduce
1. Install Avo
2. Edit your routes.rb like this:
```ruby
constraint subdomain: 'avo' do
  mount Avo::Engine, at: '/'
end
```

### Expected behavior & Actual behavior
I expect to navigate to avo.mydomain.com and find avo. Instead, I find the default rails page.

### System configuration
**Avo version**: 2.9

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.0

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
I haven't used Avo on a subdomain, but I'm 100% sure it can be done.

I [posted](https://discord.com/channels/740892036978442260/740893011994738751/1097828797329448991) this question on our Discord channel, maybe someone can help.

If not, I'll have a look in the next few days.

**Comment by rickychilcott** [comment]
I'm not explicitly using the `"avo"` subdomain, I use `"admin"`, but it works for me. 

Two things to try:
1) Does admin work for you?
2) Do subdomains (for another rack app) work at all for your app?

If it's helpful, try:

```ruby
constraint subdomain: 'avo' do
  get "hi", to: -> (env) {  [200, {}, ["👋"]] }
end
```

`curl http://avo.mydomain.com/hi`

Note that unless you've got a some sort of server in front of rails that is proxying requests, /etc/hosts entries, and/or something like ngrok - I'm not sure how you'd get subdomains locally. I use Caddy and have some cert CA's setup to get my app working locally.

**Comment by ProGM** [comment]
Hi @rickychilcott ,
Let me give all the context.
If I mount Avo without specifying the subdomain, it works ALSO on the subdomain, of course:
```
mount Avo::Engine, at: '/'
```
However this is not what I want, because it mounts all Avo routes both on the subdomain and the primary domain.

But if I do:
```ruby
constraint subdomain: 'avo' do
  mount Avo::Engine, at: '/'
end
``

and I do `curl -v http://avo.mydomain.com/`, I get the default Rails page.

The same happens if I use `domain` instead of `subdomain`:
```ruby
constraint domain: 'avo.mydomain.com' do
  mount Avo::Engine, at: '/'
end
``

I figured out a solution for now, by using a custom Rack Middleware, but it's not an optimal solution, since I have to match the Avo routes with a regexp and exclude them when the subdomain is "avo".

**Comment by rickychilcott** [comment]
I see. But the app is mounted at that subdomain. Meaning there are other routes that are routable but the root url is not. If memory serves, I link to a non root route in my app. And avo.root_url doesn’t work. 

Is that what you’re seeing?

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if you have new information.

**Comment by ProGM** [comment]
Hi there, just an update.
After trying to isolate the problem, I figured out that:
* Mounting on a subdomain works correctly as is, I was simply messing up with other stuff
* Mounting on a custom domain works, but [the option name is "host", not "domain"](https://stackoverflow.com/a/48546059):
```
constraint host: 'avo' do
  mount Avo::Engine, at: '/'
end
```

**Comment by adrianthedev** [comment]
Thanks for sharing! I added it to the docs under the `Installation` page.
