### ISSUE TITLE
image field in sidebar are displayed with object-fit: cover

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1697]
### Describe the bug

With https://github.com/avo-hq/avo/pull/1683/files#diff-07cf3c32ff78fd2d310203994c209cc23680f4df0840a851d91acc5e8ef40e68R5 avo introduce a new file view type. After this changes an image in the sidebar will be displayed as object-fit: cover instead of fitting the whole paraent object (this was before). Also i want to ask if there is any possibilty to hide the title of a field, so that the logo only is visible or should i consider writing a resource tool for this?

### Steps to Reproduce

```ruby
  sidebar do
    field :logo, 
          as: :file, 
          is_image: true, 
          display_filename: false
  end
```

![image](https://user-images.githubusercontent.com/26464774/233019232-86e6ab46-a7f4-4ba4-bc7e-336f2602f595.png)

### Expected behavior & Actual behavior
The image will be presented more nicely with `object-fit: contain`

### System configuration
2.30.2

Rails 7

Ruby 3.2.0

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hmmm. Yeah, that makes sense.

Let me think of a good solution for this.

**Comment by adrianthedev** [comment]
I haven't forgotten about this @FLX-0x00. I'm just working overtime to have the beta of Avo 3 out.
