### ISSUE TITLE
Link to close session disappeared when using Devise with a Usuario class (instead User class) inside a namespace

### ISSUE THREAD

**Issue by dailson-igo** [avo-hq/avo#1700]
### Describe the bug
The problem with the absence of the logout link seems to be related to the use of the class named Usuario. It didn't occur when I used the name User for class.

### Steps to Reproduce
```
$ rails new devise-namespace --css tailwind -j esbuild --skip-test
$ cd devise-namespace
$ rails app:template LOCATION='http://avohq.io/app-template'
$ code .

# Add gem
gem "devise", "~> 4.9"

$ bundle
$ rails g devise:install
$ rails g devise Namespaced::Usuario
$ rails db:migrate
$ rails g avo:resource Namespaced::Usuario

# Create devise user
Namespaced::Usuario.create!(email: "admin@test.com", password: "admin123")

# config/initializers/avo.rb
Avo.configure do |config|
  config.current_user_method = :current_usuario
end

# config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, class_name: "Namespaced::Usuario"
  authenticate :usuario do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  root to: redirect("/avo")
end
```

### Expected behavior & Actual behavior
After authenticating with the created admin user, the user's email appears at the bottom of the screen. The link to end the session should also appear, but with these settings the link is unavailable

### System configuration
**Avo version**: 2.30.2

**Rails version**: 7.0.4.3

**Ruby version**: 3.1.2p20

**License type**:
 - [X] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/104414789/233410421-1489563d-879d-4878-8028-f7a9833da6b8.png)

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [X] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hi @dailson-igo, would it be possible for you to create a repository with the instructions and share it here? It would be really helpful for me to see the code in action. Thank you!

**Comment by dailson-igo** [comment]
Of course Adrian. Created repository:
[devise-namespace](https://github.com/dailson-igo/devise-namespace)

**Comment by adrianthedev** [comment]
Thanks for the reproduction app. That really helped.

So, because this is not the usual devise/authentication setup, Devise generates a different path, and you need to tell Avo about it.
The fix is to add this `config.sign_out_path_name = :destroy_usuario_session_path` to `avo.rb`.

This is another reason why you should consider changing all the business codes to English instead of Brazilian. My opinion is that you'll run into more of these issues in the future. Besides that, you're limiting your app to only Brazilian-speaking developers.
That's my recommendation 😇
