### ISSUE TITLE
CSV export fails when applying filter and selecting all matching records

### ISSUE THREAD

**Issue by ddetienne** [avo-hq/avo#1702]
### Describe the bug

The error occurs during the export of records to csv, when: 

1. records are filtered AND
2. records are selected over more than one page, i.e. "Select all matching" has been clicked. 

In the code, the issue has been identified to occur in **actions_controller.rb**. 

In the scenario described above, `@resource.model_class.find_by_sql decrypted_query` in 

```
unless @action.standalone
        args[:models] = if @selected_query.present?
          @resource.model_class.find_by_sql decrypted_query
        else
          @resource.find_record resource_ids, params: params
        end
end
```

is called. 

`decrypted_query` is `SELECT \"posts\".\"id\" AS t0_r0, \"posts\".\"name\" AS t0_r1, \"posts\".\"body\" AS t0_r2, \"posts\".\"is_featured\" AS t0_r3, \"posts\".\"published_at\" AS t0_r4, \"posts\".\"user_id\" AS t0_r5, \"posts\".\"created_at\" AS t0_r6, \"posts\".\"updated_at\" AS t0_r7, \"posts\".\"status\" AS t0_r8, \"posts\".\"slug\" AS t0_r9, \"users\".\"id\" AS t1_r0, \"users\".\"email\" AS t1_r1, \"users\".\"first_name\" AS t1_r2, \"users\".\"last_name\" AS t1_r3, \"users\".\"roles\" AS t1_r4, \"users\".\"birthday\" AS t1_r5, \"users\".\"custom_css\" AS t1_r6, \"users\".\"team_id\" AS t1_r7, \"users\".\"encrypted_password\" AS t1_r8, \"users\".\"reset_password_token\" AS t1_r9, \"users\".\"reset_password_sent_at\" AS t1_r10, \"users\".\"remember_created_at\" AS t1_r11, \"users\".\"created_at\" AS t1_r12, \"users\".\"updated_at\" AS t1_r13, \"users\".\"active\" AS t1_r14, \"users\".\"slug\" AS t1_r15, \"active_storage_attachments\".\"id\" AS t2_r0, \"active_storage_attachments\".\"name\" AS t2_r1, \"active_storage_attachments\".\"record_type\" AS t2_r2, \"active_storage_attachments\".\"record_id\" AS t2_r3, \"active_storage_attachments\".\"blob_id\" AS t2_r4, \"active_storage_attachments\".\"created_at\" AS t2_r5, \"active_storage_blobs\".\"id\" AS t3_r0, \"active_storage_blobs\".\"key\" AS t3_r1, \"active_storage_blobs\".\"filename\" AS t3_r2, \"active_storage_blobs\".\"content_type\" AS t3_r3, \"active_storage_blobs\".\"metadata\" AS t3_r4, \"active_storage_blobs\".\"byte_size\" AS t3_r5, \"active_storage_blobs\".\"checksum\" AS t3_r6, \"active_storage_blobs\".\"created_at\" AS t3_r7, \"active_storage_blobs\".\"service_name\" AS t3_r8 FROM \"posts\" INNER JOIN \"users\" ON \"users\".\"id\" = \"posts\".\"user_id\" LEFT OUTER JOIN \"active_storage_attachments\" ON \"active_storage_attachments\".\"record_type\" = 'Post' AND \"active_storage_attachments\".\"name\" = 'cover_photo' AND \"active_storage_attachments\".\"record_id\" = \"posts\".\"id\" LEFT OUTER JOIN \"active_storage_blobs\" ON \"active_storage_blobs\".\"id\" = \"active_storage_attachments\".\"blob_id\" WHERE \"users\".\"team_id\" IN (1, 2, 3) ORDER BY posts.created_at desc`

The query seems to be valid, it was validated by an external validation tool and could be successfully run in query console. 

Nevertheless, `args[:models]` is `[#<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>, #<Post id: nil, tag_list: nil>]`

This leads to export_csv.rb failing with the following error: 

![error](https://user-images.githubusercontent.com/7384757/233631300-873165c4-c5aa-457a-adc7-4b0bdd624071.png)

### Steps to Reproduce
1. Create example_filter.rb and add it along with the ExportCsv action to post_resource.rb as done [here](https://github.com/avo-hq/avo/compare/main...ddetienne:avo:bug/decrypted_query_fails_to_load_models)
2. Go to posts and switch to list view
3. Filter by "example_filter" selecting Apple, Google and Facebook. Important is to have more than 12 records, so we can select all matching records in the next step
4. Select all matching records, it should be more than the ones displayed on the current page
5. Click on the "Export csv" action and click run

### Expected behavior & Actual behavior

The records should be exported as a downloadable csv, but the above described error occurs. 

### Models and resource files

Error could be reproduced in avo dummy app: https://github.com/ddetienne/avo/tree/bug/decrypted_query_fails_to_load_models

### System configuration
**Avo version**:
2.30.2

**Rails version**:
6.1.0

**Ruby version**:
3.1.2

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Paul-Bob** [comment]
Hello @ddetienne, I am encountering the same issue on the branch you provided. Upon further investigation, I found that the query can be converted to SQL, but when we execute `Post.find_by_sql(sql_query)`, it returns numerous records that are filled with nil values.

Based on this, it appears that the query is causing the problem. After reviewing the models and their associations, I noticed that the query used in the apply method of the `ExampleFilter` was not entirely correct. I attempted to resolve the issue using the following query: `query.joins(user: :team_memberships).where(team_memberships: { team_id: value })` and it successfully resolved the problem on my end.

**Comment by ddetienne** [comment]
There was indeed a mistake in the query I provided in ExampleFilter, thanks for checking and fixing it! Thanks to this, I could also find the issue and fix the query that was breaking my app. 

For completeness, here is the full example and how I fixed it: 

### Models and associations
farmer belongs_to farmer_group
farmer_group belongs to project 

### Breaking query 
`query.joins(:farmer_group).where(farmer_group: { project_id: value })` inspired from this query `Customer.joins(:orders).where(orders: { created_at: time_range }).distinct` found here https://guides.rubyonrails.org/active_record_querying.html

This query was working fine except for the case described above. 

### Correct query 
`query.joins(farmer_group: :project).where(projects: { id: value })` fixed my problem. 

### Conclusion 
I am still not quite 100% sure where the problem lied but the issue is solved. Thanks a lot for your help @Paul-Bob !
