### ISSUE TITLE
When installing Avo detect if the app has a User model and create a resource for it.

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1719]
### Feature

From [here](https://discord.com/channels/836637622432170028/1101956759729483827/1102836906645016586).

Most apps have a `User` model. When you install Avo in an existing app it should detect that and generate a `User` resource automatically.

### Current workarounds

Generate the resource manually.

### Approach

Update the [`install` generator](https://github.com/avo-hq/avo/blob/819cc1711979d68f7c982bffe90b1a625fd1cc4b/lib/generators/avo/install_generator.rb#L1) to also run `bin/rails generate avo:resource user`.

**Comment by FLX-0x00** [comment]
Note that such resources do not always use the name User. For rodauth, it is Account by default.

**Comment by adrianthedev** [comment]
That's a good point. Thanks!
Maybe we could search for rodauth and `Account` as well and incorporate that too.
