### ISSUE TITLE
Time field and timezone issue.

### ISSUE THREAD

**Issue by holden** [avo-hq/avo#1735]
### Context
I'm having a little bit of fun with timezones generally, but I noticed one oddity when I simply set a time field to `Etc/UTC` or `UTC` it doesn't seem like use it correctly. It's like the form is using one timezone and the show another?

`field :start_time, as: :time, timezone: -> { "Etc/UTC" }` # or UTC

Also, I just created the field `start_time` so there shouldn't be anything else there in the model causing this.

https://github.com/avo-hq/avo/assets/48241/9a1addaf-9728-446a-93fa-f44a8444bac0

I've been trying to fix a timezone issue we've been having generally by separating date, time and timezone into 3 fields.

### System configuration
**Avo version**:

2.32.2

**Rails version**:

7.0.1

**Ruby version**:

3.2.1

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by holden** [comment]
I dug into the component a little and found the `relative` method.  If I set this to `false` it seems to work as intended and it doesn't modify the time in the background.  eg if I set 20:00 i get 20:00 now!

`field :start_time, as: :time, timezone: -> { "Etc/UTC" }, relative: false, picker_format: "H:i"`

I also noticed the `picker_format` seems to be ignored as seconds still show up.

![CleanShot 2023-05-11 at 08 45 33@2x](https://github.com/avo-hq/avo/assets/48241/e9127f72-048f-467b-9db6-15a94ba6eb1c)

**Comment by adrianthedev** [comment]
The `picker_format` refers to the time format in the actual field (on `Edit`), not the picker popup itself.
You can use `picker_options` to hide those from the popup.
[flatpickr options](https://flatpickr.js.org/options/)

**Comment by holden** [comment]
I tried passing in the picker_options to flatpicker, and it works fine for 24hours but didn't seem to work for date format.

`field :start_time, as: :time, timezone: -> { "Etc/UTC" }, relative: false, picker_format: "H:i", picker_options: { dateFormat: "H:i" }`

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if we can help.
