### ISSUE TITLE
Use `to_param` instead `id` when query actions records

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1736]
### Context

Right now, on actions, Avo it's ignoring all gems that manipulate the record id because instead using `to_param` when do a query to get selected records it's using the actually DB `id`.

[From here.](https://discord.com/channels/740892036978442260/740893011994738751/1105901712956465242)

**Comment by FLX-0x00** [comment]
I think this should be implemented, as often something like hashid is used to add another layer of security. Although preventing unallowed direct access to resources should be done in the policy sections, it can be used as another security feature on top or at the level of obfuscation. So avo should not accept the raw id if something like hashids or other types of id manipulation are in use.
