### ISSUE TITLE
Resource Index Map view does not hide table on sizedown

### ISSUE THREAD

**Issue by fastjames** [avo-hq/avo#1738]
### Describe the bug
When I created the resource index map view, one of the requests was to hide the optional table for small screens. I had this working during the PR creation, but it is not behaving in the same way now. Instead of hiding the map when I narrow the browser, it keeps the table visible. Clicking on the view type toggle buttons at the top has no effect on the page.

### Steps to Reproduce
1. Set the browser width to >1024px
2. Configure the map view to render the table as well
3. Visit the index page for a resource with a location
4. Switch to the map view
5. Resize the browser width to <1024px

### Expected behavior & Actual behavior
Expected behavior: the map remains visible, while the table is hidden. The view type toggle buttons switch between the map component and the table component.
Actual behavior: the table remains visible. The view type toggle buttons have no effect.

### System configuration
**Avo version**: 2.32.2

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by fastjames** [comment]
I reviewed the later changes to the PR, and it looks like the removal of the `hidden lg:block` styles here may be related to the observed problem:

https://github.com/avo-hq/avo/pull/1679/commits/597ebdb3fd68d5fba96dd4a2d13d11f316cb4ce3#diff-bfb2866c796332877f4c58dbd26ab0f5aab49ac8cab67d264d6eb347f645629cL7

I'm not sure if there is a clean way to accomplish this with only grid styles, or if we have to use the `hidden` class.

**Comment by adrianthedev** [comment]
I think hiding the table when `visible` is see to true is not the right option here. I mean, the user specified that the table is visible.
Right now it's collapsing bellow or above the table.

Am I missing something?

**Comment by fastjames** [comment]
After fixing the map display height, the current behavior is fine so we no longer need to hide the table in this case. Closing as no longer needed.
