### ISSUE TITLE
Resource index map view does not set map height for vertical layout

### ISSUE THREAD

**Issue by fastjames** [avo-hq/avo#1739]
### Describe the bug
On the resource index map view, if the table is rendered in the `:top` or `:bottom` layout styles, the map renders as a very short (14px high) element instead of having an expected height of several hundred px.

### Steps to Reproduce
1. Configure a resource with a location
2. Configure the resource index map display to render the table in the :bottom layout style.
3. Visit the resource index page.

### Expected behavior & Actual behavior
Expected behavior: the map and table elements should render, each about the same height, with the map above the table.
Actual behavior: the table renders properly, but the map renders at about 14px high (observed on Safari) or 0px high (observed on Firefox).

### System configuration
**Avo version**: 2.32.2

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by fastjames** [comment]
This one appears to be cured by restoring the min-h-* classes that were removed here:
https://github.com/avo-hq/avo/pull/1679/commits/597ebdb3fd68d5fba96dd4a2d13d11f316cb4ce3#diff-bfb2866c796332877f4c58dbd26ab0f5aab49ac8cab67d264d6eb347f645629cL2

That seems like a suboptimal solution, though. I would love to learn more about a better way of doing this with tailwind that works with the mapbox javascript code on the page.

**Comment by adrianthedev** [comment]
I tested on Chrome, Firefox, and Safari on macos and I can't seem to get those results. Trying to figure out if this is a browser, or OS issue.
Could you share a screenshot?

<img width="880" alt="CleanShot 2023-05-11 at 00 17 09@2x" src="https://github.com/avo-hq/avo/assets/1334409/88c15ccf-be55-4e83-ac3a-a93859eb6957">

The reason why I removed those classes is that in my experience, with CSS, it's better to let things "fill their space" as they need to. So instead of hardcoding the height for the map container, let the container stretch as big as the content (map) is. I believe that the map has a configurable height.
That being said, I didn't want this bug to pop up.

**Comment by adrianthedev** [comment]
I now read the whole description and you said it manifests on Safari...

This is Safari Technology preview on my end.
<img width="1570" alt="CleanShot 2023-05-11 at 00 22 55@2x" src="https://github.com/avo-hq/avo/assets/1334409/de0c67e5-d17a-46f0-988e-faa5a6a07fca">

**Comment by adrianthedev** [comment]
Ok. let me test it differently. Gimme a sec.

**Comment by fastjames** [comment]
With the help of @adrianthedev I figured out that this was a local configuration issue. I had the following in my map view configuration:

```
mapkick_options: {
  height: "100%"
}
```

This apparently sets the height to 100% of the enclosing div, which (in my case) has a height of 0px. I removed the `height` entry altogether, and the map appeared as expected.
