### ISSUE TITLE
Let "total count" be hidden from pagination for large tables.

### ISSUE THREAD

**Issue by nasa42** [avo-hq/avo#1748]
### Feature

For large tables (with tens of millions of rows), the "total count" query makes the index page extremely slow. [Active Admin provides an option `pagination_total`](https://activeadmin.info/3-index-pages.html) to disable the count query. Is there a similar configuration option in Avo?

```[tasklist]
### Tasks
- [ ] https://github.com/avo-hq/avo/issues/2027
```

**Comment by adrianthedev** [comment]
Hey @nasa42 👋
Thanks for writing. Would you be open to submit a PR to have that disabled? I think pagy has a toggle in the `pagy_info` method.

**Comment by Paul-Bob** [comment]
Use https://ddnexus.github.io/pagy/docs/extras/countless/

From [here ](https://discord.com/channels/740892036978442260/1163562116431757463)
