### ISSUE TITLE
Use Avo::BaseResourcesController when available

### ISSUE THREAD

**Issue by JeremasPosta** [avo-hq/avo#1758]
### Feature

According to the docs: https://docs.avohq.io/2.0/resources.html#extending-avo-resourcescontroller
I should add a new 'Avo::BaseResourcesController' in order to add extra functionalities.

As a dev generating a new model with the rails generator, or via the avo:resource generator, I would expect the new file to be created with the new `Base` controller instead of the regular one.

I'm not 100% sure this is the best approach, but I know the cycle from now will be:
Create a new resource, notices there is an `after_action` missing, debug, and discover that the problem is the controller inheriting from another class.

### Current workarounds

Just rename the class after the generator builds the file.

**Comment by adrianthedev** [comment]
Hey @JeremasPosta.

Yeah, we need to figure a better solution for Avo 3.
We didn't introduce this breaking change in Avo 2 because it would break a lot of apps.

Please see [this](https://avohq.io/blog/safely-extend-a-ruby-on-rails-controller) blog post as well.

**Comment by JeremasPosta** [comment]
I understand, no worries! 
Thanks!
