### ISSUE TITLE
Turbo interfering with action redirects.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1761]
### Describe the bug

When an Action redirects to an endpoint that redirects somewhere off-site, the redirect is swallowed.  I can work around this by instead of using `redirect_to`, render a page that uses a meta tag to do the redirect as Avo/Turbo will pick that up and replace the page with it.

### Steps to Reproduce

```ruby
class SomeAction < Avo::BaseAction
  self.name    = "Some Action"
  self.visible = -> { view == :show }

  def handle(**args)
    models, = args.values_at(:models)

    unless models&.length == 1
      error("You must do the thing to exactly one thing at a time.")
      return
    end

    model_id = models.first.id
    target   = view_context.resources_some_model_path(model_id)

    redirect_to(main_app.something_path(target:, model_id:)) # The action at something_path does a `redirect_to('...', allow_other_host: true)`
  end
end
```

### Expected behavior & Actual behavior

The user should be redirected properly.

### System configuration
**Avo version**: 2.32.6

**Rails version**: 7.0.4.3

**Ruby version**: 3.1.4

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Could you try adding `self.may_download_file = true` to the action?

**Comment by MrJoy** [comment]
Unfortunately, that does not help.

**Comment by MrJoy** [comment]
@Paul-Bob After restarting the server, `self.may_download_file = true` does the trick!
