### ISSUE TITLE
Tailwind install process lists incomplete package script entry

### ISSUE THREAD

**Issue by fastjames** [avo-hq/avo#1764]
## Enhancement

The `avo:tailwindcss:install` [command](https://docs.avohq.io/2.0/custom-asset-pipeline.html#use-tailwindcss-utility-classes) will instruct the user to add the following line to the `package.json` file. 
But, if the parent app uses the `tailwindcss-rails` gem, the `tailwind.config.js` file is not going to be in the project root directory, but in `config/tailwind.config.js`, thus, making the `avo:tailwindcss` command not work correctly.
We should check where the `tailwind.config.js` file is and append the `-c ./config/tailwind.config.js` to the instructions.

```bash
# before
"scripts": { "avo:tailwindcss": "tailwindcss -i ./app/assets/stylesheets/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css --minify" }

# after after we detect the location of the file
"scripts": { "avo:tailwindcss": "tailwindcss -i ./app/assets/stylesheets/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css -c ./config/tailwind.config.js --minify" }
```

Initial description 👇
---

### Describe the bug
In https://github.com/avo-hq/avo/pull/1693 , a user prompt was added instructing users to add the following script entry to their `package.json`:

```
"scripts": { "avo:tailwindcss": "tailwindcss -i ./app/assets/stylesheets/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css --minify" }
```

I think this entry may be incomplete, because it does not specify a location for the tailwind configuration file. When tailwindcss-rails is installed, it puts the `tailwind.config.js` file under `config`. The `tailwindcss` command expects to find that configuration file "in the root of the project" (see https://tailwindcss.com/docs/configuration). Without a specific parameter like `-c ./config/tailwind.config.js`, I don't think the tailwindcss command will find the configuration file as expected.

### Steps to Reproduce
1. Add tailwindcss-rails to an avo-based rails application as documented in https://docs.avohq.io/2.0/custom-asset-pipeline.html#use-tailwindcss-utility-classes.
2. Add a non-standard directory to the `content` list in `config/tailwind.config.js`
3. Add a utility class to a file in that non-standard directory
4. Visit the view served by the file modified in step 3

### Expected behavior & Actual behavior
The utility class added in step 3 should be active on the page. Instead, it's ignored because tailwind did not know we were using it and so it was stripped.

### System configuration
**Avo version**: 2.32.6

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @fastjames.

I just installed a new rails app using `rails new rails_7-test-tailwind  -j esbuild --css tailwind -d postgresql --main` and the tailwind config file is in the root directory of the app.

I think you should add `-c config/tailwind.config.js` to that script.

<img width="602" alt="CleanShot 2023-06-08 at 21 59 12@2x" src="https://github.com/avo-hq/avo/assets/1334409/e907019e-ab3f-47ff-a399-70ec33560c8a">


<img width="602" alt="CleanShot 2023-06-08 at 21 59 12@2x" src="https://github.com/avo-hq/avo/assets/1334409/7fb00af8-09f9-43d9-80d8-43a8e66e4304">

**Comment by adrianthedev** [comment]
We should have a check in that `avo:tailwindcss:install` generate command to find the `tailwind.config.js` and add it like above.
I'll add the `Help needed` label. Maybe we get a PR incoming 😛
