### ISSUE TITLE
Avo 3 rendering issue at narrow breakpoint.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1767]
### Describe the bug

Sidebar and main form width aren't matched up at narrow breakpoint.

![image](https://github.com/avo-hq/avo/assets/113625/8ec627fa-ed49-456f-83c5-c56bdfe89789)

### Steps to Reproduce

Visit: https://main.avodemo.com/avo/resources/teams/4

Reduce window width to smallest breakpoint.

### Expected behavior & Actual behavior

Presumably the main form would have a width similar to the sidebar, when both are stacked vertically.

### System configuration
**Avo version**: 3.0.0

**Rails version**: ?

**Ruby version**: ?

**License type**:

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by RocKhalil** [comment]
this line needs to be fixed: https://github.com/avo-hq/avo/blob/1cf7c1dff7b114f959c00a6e02337548135e2bfb/app/components/avo/panel_component.html.erb#L28

to
```html
<div class="relative flex-1 w-full <% if sidebar? %> sm:w-2/3 <% end %>">
```

but I'm not sure which branch is the current working branch; I'll fix it when someone points me to the V3 branch :-)
