### ISSUE TITLE
The action's `visible` block is not respected in the `action` show control

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1769]
### Describe the bug

If an action has `self.visible = -> {false}`, the action is still displayed on the page if the `show_controls` uses it `action TheAction`

**Comment by adrianthedev** [comment]
Let's add the `visible` block to the `action` control

```ruby
  self.show_controls = -> do
    action ReleaseFish visible: -> {false}
  end
```

**Comment by Paul-Bob** [comment]
@adrianthedev I'm not sure if about the visible block on the `action` control.

I think we should call the action's `self.visible` block even if the action is on `show_controls`. We can inject the "`render_type`" where that action is rendered.

Example: (random logic)

```ruby
self.visible = -> {
  if user.admin? && render_type == show_control
    true
  elsif render_type == row_control
    true
  else
    false
  end
}
```

On the example above the action is rendered on `show_controls` only for admins, on `row_controls` for everyone and is not rendered anywhere else...

In my opinion, employing a visible block to handle row, show, and other controls for actions, while relying on the `self.visible` attribute for other actions, can complicate maintenance and development. This becomes especially challenging when the developer needs to apply the same logic to all action instances. However, if the developer has access to `resource`, `record`, `"render_type"`, `user`, `view`, and possibly the parent resource and model, they can centralize and maintain all the logic around the `self.visible` class attribute of the action.

**Comment by adrianthedev** [comment]
Ok. I agree with you. One place to set the visibility.
We need to think about a system.

The use can render this action on:
 - index - as index control or in action list
 - show - as show control or in action list
 - edit - as edit control or in action list
 - row - as row control or in action list

So we can use the `view` object, and maybe the `render_type` will be `:{row|show|index|edit}_control` or `:action_list`?
Open to suggestions.

**Comment by Paul-Bob** [comment]
I think the suggested nomenclature is on point but `:action_list` is not a `render_type`, it should be a boolean that indicates whenever the action is rendered inside or outside a list.

Example:
```ruby
...
if render_type == :row_control && inside_list?
...
```

Not sure if this is easy to implement but I think this will offer the most granular configuration for the developers

**Comment by adrianthedev** [comment]
> it should be a boolean that indicates whenever the action is rendered inside or outside a list.

It's too complicated. You already need to remember view and renderr_type, now you also have to remember another boolean. Too many things to remember.

Another suggestion I have is `render_type` is `:{row|show|index|edit}_control` or `:{row|show|index|edit}_list`. I'm not 100% convinced with this one.

**Comment by adrianthedev** [comment]
not sure how difficult version 3 is to implement. can you flesh out an MVP in 30 minutes?

**Comment by Paul-Bob** [comment]
Check the [related PR](https://github.com/avo-hq/avo/pull/1833). The PR fixes the reported issue, the `visible` block is now respected on show controls too. Right now on Avo2 is possible to verify if is show control or not from the view, `if view == :show`...

The MVP should be implemented on Avo3, there is where we have all the controls (row, index, edit, ...).

Let me know if I should implement it right now or should we let it for later.
