### ISSUE TITLE
Allow submission of security issues / vulnerabilities in github repository

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1776]
Just a reminder / todo list entry: It would be nice if @adrianthedev can enable the possibility of reporting a vuln directly through Github. See: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by adrianthedev** [comment]
Done and done!

Thank you @FLX-0x00!
