### ISSUE TITLE
Bug in searchable field searchable : true and belongs_to

### ISSUE THREAD

**Issue by mighani2** [avo-hq/avo#1778]
### Describe the bug
I have an employee resource and a job_application resource. 
Each job_application class has one employee associated with it.

```
class JobApplication < ApplicationRecord
  belongs_to :employee, optional: true 

```
```
class Employee < ApplicationRecord
  after_commit :notify, if: :saved_change_to_note?
  has_many :inventory_updates
  has_many :job_applications
```

```
class JobApplicationResource < Avo::BaseResource
  self.title = :employee
  self.includes = []
  field :id, as: :id
  field :employee,  as: :belongs_to, searchable: true, name: 'Mitarbeiter', sortable: true
```
```
class EmployeeResource < Avo::BaseResource
  self.title = :full_name
  self.includes = []
  self.search_query = -> do
    scope.ransack(last_name_cont: params[:q], first_name_cont: params[:q], m: "or").result(distinct: false)
  end
```

In the frontend when I wanted to add an employee to the job_application, a search field would pop up, where I can search for an employee.

With avo 2.24.0 this worked fine, but updating to 2.34.0 something seems to be broken. In the console I get this 

[e5d6524a-0e8b-4b4c-a0d7-cf9f365351ef] Started GET "/avo/avo_api/employees/search?q=&global=false&via_association=belongs_to&via_association_id=employee&via_reflection_class=Projectassignment&via_reflection_id=&via_parent_resource_id=&via_parent_resource_class=&via_relation=" for 127.0.0.1 at 2023-06-06 15:50:42 +0200
[e5d6524a-0e8b-4b4c-a0d7-cf9f365351ef]   User Load (3.0ms)  **SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1**
Processing by Avo::SearchController#show as */*
[e5d6524a-0e8b-4b4c-a0d7-cf9f365351ef]   Parameters: {"q"=>"", "global"=>"false", "via_association"=>"belongs_to", "via_association_id"=>"employee", "via_reflection_class"=>"Projectassignment", "via_reflection_id"=>"", "via_parent_resource_id"=>"", "via_parent_resource_class"=>"", "via_relation"=>"", "resource_name"=>"employees"}

When I remove the searchable: true from the resource field, I can see a dropdown with all employees, but the search experience seems to be broken. With has_many association it works. Only with the belongs_to i notice this problem.

### System configuration
**Avo version**: 2.34.0

**Rails version**: 7.0.5

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ x] No

### Screenshots or screen recordings

https://share.getcloudapp.com/DOuKNyEb 

#### Impact

 - [ x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by mighani2** [comment]
One addition, when i remove the searchable:true I chose an employee from the dropdown. Saving the resource then yields an exception:

<header style="color: rgb(240, 240, 240); background: rgb(204, 0, 0); padding: 0.5em 1.5em; font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="overflow-wrap: break-word; margin: 0.2em 0px; line-height: 1.1em; font-size: 2em;">NoMethodError in Avo::JobApplicationsController#create</h1></header><main role="main" id="container" style="box-sizing: border-box; width: 1841px; padding: 0px 1.5em; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="exception-message" style="padding: 8px 0px;"><div class="message" style="margin-bottom: 8px; line-height: 25px; font-size: 1.5em; font-weight: bold; color: rgb(204, 0, 0);">undefined method `find' for nil:NilClass</div></div><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(217, 217, 217); background: rgb(236, 236, 236); max-width: 978px;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#221</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background-color: rgb(255, 255, 255);">

219 220 221 222 223 224 | def valid_polymorphic_class(possible_class)         types.find do \|type\|           type.to_s == possible_class.to_s         end       end
-- | --


</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px;"><code>Rails.root: /Users/mighani/projekte/kipper</code></p><div id="traces-0"><a href="http://0.0.0.0:3000/avo/resources/job_applications/new#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Application Trace</a><span> </span>|<span> </span><a href="http://0.0.0.0:3000/avo/resources/job_applications/new#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Framework Trace</a><span> </span>|<span> </span><a href="http://0.0.0.0:3000/avo/resources/job_applications/new#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Full Trace</a><div id="Full-Trace-0" class="tdfocus-1686061211245" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0 tdfocus-1686061174616  selected" data-exception-object-id="792780" data-frame-id="0" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(204, 0, 0); overflow-wrap: break-word;">avo (2.34.0) lib/avo/fields/belongs_to_field.rb:221:in `valid_polymorphic_class'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061147997  " data-exception-object-id="792780" data-frame-id="1" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">avo (2.34.0) lib/avo/fields/belongs_to_field.rb:202:in `fill_field'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061153650 " data-exception-object-id="792780" data-frame-id="2" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">avo (2.34.0) lib/avo/base_resource.rb:327:in `block in fill_model'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061158057 " data-exception-object-id="792780" data-frame-id="3" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:382:in `block in each_pair'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061160433 " data-exception-object-id="792780" data-frame-id="4" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:381:in `each_pair'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061161286 " data-exception-object-id="792780" data-frame-id="5" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:381:in `each_pair'</a><br><a class="trace-frames trace-frames-0 tdfocus-1686061162279 " data-exception-object-id="792780" data-frame-id="6" href="http://0.0.0.0:3000/avo/resources/job_applications/new#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">avo (2.34.0) lib/avo/base_resource.rb:322:in `fill_model'</a></code></div></div></main>**NoMethodError in Avo::JobApplicationsController#create
undefined method `find' for nil:NilClass**
Extracted source (around line #221):
219
220
221
222
223
224
              

      def valid_polymorphic_class(possible_class)
        types.find do |type|
          type.to_s == possible_class.to_s
        end
      end

Rails.root: /Users/mighani/projekte/kipper

[Application Trace](http://0.0.0.0:3000/avo/resources/job_applications/new#) | [Framework Trace](http://0.0.0.0:3000/avo/resources/job_applications/new#) | [Full Trace](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[avo (2.34.0) lib/avo/fields/belongs_to_field.rb:221:in `valid_polymorphic_class'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[avo (2.34.0) lib/avo/fields/belongs_to_field.rb:202:in `fill_field'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[avo (2.34.0) lib/avo/base_resource.rb:327:in `block in fill_model'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:382:in `block in each_pair'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:381:in `each_pair'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[actionpack (7.0.5) lib/action_controller/metal/strong_parameters.rb:381:in `each_pair'](http://0.0.0.0:3000/avo/resources/job_applications/new#)
[avo (2.34.0) lib/avo/base_resource.rb:322:in `fill_model'](http://0.0.0.0:3000/avo/resources/job_applications/new#)

Maybe its related

**Comment by mighani2** [comment]
Another hint: I have another belongs_to which works, so its not for all belongs_to resource fields.
Parameters: {"q"=>"", "global"=>"false", "via_association"=>"belongs_to", "via_association_id"=>"cost_type", "via_reflection_class"=>"Cost", "via_reflection_id"=>"", "via_parent_resource_id"=>"", "via_parent_resource_class"=>"", "via_relation"=>"", "resource_name"=>"cost_types"}

The difference is that in employee there is: via_reflection_class=Projectassignment
I have this in the employee class:

has_many :projectassignments
has_many :projects,  through: :projectassignments

**Comment by mighani2** [comment]
I switched back to Avo 2.33.2 now the parameters are:
[c64d2fb4-926f-41b4-b21f-68933a2ab1f9]   Parameters: {"q"=>"", "global"=>"false", "via_association"=>"belongs_to", "via_association_id"=>"employee", "via_reflection_class"=>"JobApplication", "via_reflection_id"=>"1", "via_parent_resource_id"=>"", "via_parent_resource_class"=>"", "via_relation"=>"", "resource_name"=>"employees"}
Now, 2 things happend, the via_reflection_class seems to be correct. In my initial post it was projectassignment.
Also, i am now able at least to save the job_application resource. 

So, 2.33.3 seems to break / change something

**Comment by mighani2** [comment]
I found the problem now: somehow presently the search action has to be authorized in the pundit policy file. No idea, from when this was introduced.

**Comment by adrianthedev** [comment]
Hey @mighani2. Thanks for doing this deep dive and figuring out the issue.

We have a pretty detailed upgrade guide for Avo.
That particular `search?` method was added in 2.29. You can see it [here](https://docs.avohq.io/2.0/upgrade.html#upgrade-from-2-28-to-2-29).

I also suggest you go through each upgrade step and ensure you're covered.

Closing for now. PLease feel free to reopen if this is still an issue.

**Comment by adrianthedev** [comment]
BTW, we might have a bug in 2.34 with polymorphic belongs_to. please keep an eye out for a patch today or tomorrow.
