### ISSUE TITLE
Error pagy/i18n.rb:150:in `clear': can't modify frozen Hash: {"en"=> while installing avo to existing app. 

### ISSUE THREAD

**Issue by mateuszbialowas** [avo-hq/avo#1783]
### Describe the bug
I can not install avo in my app. 
I have an error: 
```
lib/pagy/i18n.rb:150:in `clear': can't modify frozen Hash: {"en"=>[{"pagy.item_na
```
Look PR with the code and full error
https://github.com/mateuszbialowas/ogloradar/pull/36

### Steps to Reproduce
1. Bundle 'avo'
2. run: bin/rails generate avo:install
3. Error: 
```
pagy/i18n.rb:150:in `clear': can't modify frozen Hash: {"en"=>[{"pagy.item_name.one"
```

### System configuration
**Avo version**:
    avo (2.34.3)

**Rails version**:
rails (7.0.4.3)
**Ruby version**:
ruby '3.2.2'
**License type**:

 - [ x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by mateuszbialowas** [comment]
When I remove file:
config/initializers/pagy.rb
then I can install avo without problem, but I need to setup i18n translations for pagy.

**Comment by adrianthedev** [comment]
can you delete the file, install Avo and then reinstate the file? Does that keep everything working?

**Comment by mateuszbialowas** [comment]
Unfortunately this is not working. I removed pagy.rb, then install avo, then restore pagy.rb and while I am starting the rails server i have the same error.

**Comment by adrianthedev** [comment]
<img width="810" alt="CleanShot 2023-06-09 at 19 53 53@2x" src="https://github.com/avo-hq/avo/assets/1334409/82ee3e23-f9ac-4226-9990-bd106d2d2d8c">

I think this is the issue. I think you have to remove the `freeze` statement. Avo adds a few translations for pagy that it doesn't have.

**Comment by mateuszbialowas** [comment]
I comment this freeze, and still the same problem. 
<img width="1468" alt="CleanShot 2023-06-09 at 18 56 10@2x" src="https://github.com/avo-hq/avo/assets/58574619/33327b66-0655-4024-a5a5-705fffd0dc80">

I also change the locale to en, but still the same problem. 
This is the commit with changes

**Comment by mateuszbialowas** [comment]
This is working:
https://github.com/mateuszbialowas/ogloradar/pull/36/commits/99d1312f0e96a5fa13d4589f46e09f145e4b6d11
I removed:
`Pagy::I18n.load`

**Comment by mateuszbialowas** [comment]
Yes, thank you.

**Comment by mateuszbialowas** [comment]
Its working. Thank you.
