### ISSUE TITLE
External gem i18n behavior broken? 

### ISSUE THREAD

**Issue by rickychilcott** [avo-hq/avo#1786]
https://github.com/avo-hq/avo/pull/1765/files#r1212263609

These lines seem also to be breaking `clearance` gem's I18n for me as well -- I'm not able to override clearances locales with the latest avo versions.

I have run `bin/rails generate avo:locales` and it doesn't seem to fix the issue, but when I comment out the `initializer "avo.locales"` it seems to restore the standard i18n override behavior with external gems.

I haven't investigated if it effects other gems, but a quick skim of [clearance](https://github.com/thoughtbot/clearance)'s code shows  they're not doing anything fancy with their i18n usage -- so I suspect it's widespread.

This is blocking me from upgrading to the latest patched avo versions.

**Comment by rickychilcott** [comment]
The issue is not present in Avo 2.33.0 but all later versions exhibit this behavior.

**Comment by adrianthedev** [comment]
Sorry about that.

Can you quickly try `gem 'avo', '2.34.4.pre.1'` and let me know if that fixes it?

**Comment by rickychilcott** [comment]
That seemed to work locally on my failing spec. Pushing to CI to check there.

**Comment by rickychilcott** [comment]
All of CI passed for me. Merging and deploying so I'm happy with this fix. Thanks @adrianthedev!

**Comment by adrianthedev** [comment]
Cool! Thanks for your help in troubleshooting this! Closing for now while I release a more stable version.
