### ISSUE TITLE
Change new button path

### ISSUE THREAD

**Issue by lukasedw** [avo-hq/avo#1792]
### Feature
I want to have some specific index url params on new button url path.
For example, for a Index of type X it will create type X resources. Thats why I need a param on the new button to know that we are creating a X type of resource.

### Current workarounds
None

**Comment by adrianthedev** [comment]
> I need a param on the new button to know that we are creating a X type of resource.

I mean, when you are on the `User` resource, when you click the new button, you create a `user` record.

Could you be a bit more specific please?

**Comment by lukasedw** [comment]
I will create another one with more detail

**Comment by adrianthedev** [comment]
Ok. Sounds good.
I just want to put this out there. I want to help. Real-wolrd scenarios are easier to understand and relate to.
Maybe this is a need that many folks need...
