### ISSUE TITLE
undefined method `hydrate' for nil:NilClass

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1802]
### Describe the bug

I am not able to display a has_many association, having some Rails error:

`
    def set_related_resource
      @related_resource = related_resource.hydrate(params: params)
    end

    def set_model
`

### Steps to Reproduce

1. Create a model Villa
2. Create a model VillaLayout
3. Add belongs_to :villa to VillaLayout model
4. Add has_many :villa_layouts, dependent: :destroy, inverse_of: :villa to the Villa model
5. Create a Villa, add a Villa layout (directly in the DB)
6. Go to http://localhost:3000/avo/resources/villas/1

### System configuration
**Avo version**:
avo (2.35.0)

**Rails version**:
rails (7.0.5)

**Ruby version**:
ruby 3.0.2p107

**License type**:

 - [ ] Community
 - [x] Pro (trial)

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @jetienne.
I don't see what the error is.

**Comment by Paul-Bob** [comment]
I followed your steps and worked as expected on my end, without any errors. Maybe you miss-configured something. Check the migrations, model and resource configuration

**Comment by adrianthedev** [comment]
Or, create a reproduction repo so we can have a look at the errors.

**Comment by jetienne** [comment]
@adrianthedev Thank you a lot for your quick answer. Here is the repo: https://github.com/mercey-co/avo-bug-report

**Comment by adrianthedev** [comment]
Thanks @jetienne! The issue is that you don't have a `VillaLayoutResource` file.
Avo needs a resource for the association in order to know which fields to show, how to search it, etc.

**Comment by jetienne** [comment]
@adrianthedev Works like a charm :) I thought the nested resource was not necessary...

**Comment by adrianthedev** [comment]
It is required because Avo needs to know what to display (fields, what kind of view, can you search it, and more).

We'll improve the messaging there. Maybe an error like "We couldn't find a resource for association..."
