### ISSUE TITLE
searchable option / ransack tries to scope the first field matching the name even in conditional views

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1807]
### Context
I know, another nasty bug - but... consider having a model `License` and a model `Domain`. A license has many domains, and a domain belongs to a license.

```ruby
class LicenceResource < Avo::BaseResource
...
  field :domain, as: :text, sortable: false, hide_on: :forms do |model|
    model.domain.name
  end
  field :domain, as: :belongs_to, required: true, only_on: :forms, searchable: true
...
```
The domain name should be visible as text on index and show, so the first field uses `hide_on: :forms`. The belongs to field should only be visible in forms, so this uses `only_on: :forms` and should be searchable.

For example, if you run the search in the `new` form, the search result will be empty because the code crashes in the background with the following message

```
NoMethodError (undefined method `attach_scope' for #<Avo::Fields::TextField:0x000061a8401b7598 @show_on_index=true ...  
@attach_scope ||= field&.attach_scope
```

The search api tries to scope the field, but selects the text field instead of the belongs to field. After switching the position of the fields in the `LicenseResource` the search will be successful.

```ruby
class LicenceResource < Avo::BaseResource
...
  field :domain, as: :belongs_to, required: true, only_on: :forms, searchable: true
  field :domain, as: :text, sortable: false, hide_on: :forms do |model|
    model.domain.name
  end
...
```

### System configuration
**Avo version**: v2.35.0

**Rails version**: 7.0.5

**Ruby version**: 3.1.1p18

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Pff. Yup. That's a bug. Similar to https://github.com/avo-hq/avo/issues/1796.
We're on it!

Until we fix it, try and reverse the fields if you can so the "right" one is picked first.

**Comment by adrianthedev** [comment]
Hey @FLX-0x00.
I talked it over with @Paul-Bob and figured that this could be fixed using this workaround (changing the order). With Avo 3 around the block, we're reworking a few things there and fixing it in the process.
I'll mark this as a won't fix on Avo 2 so we can focus on bigger & better things (Avo 3).
Thanks!
