### ISSUE TITLE
searchable option partially bypasses the scope in has_many association

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#1808]
### Describe the bug
Considering a model `Account` and a model `Role`. An account has many roles and a role has and belongs to many accounts. 

Simple resource of the accounts
```ruby
class AccountResource < Avo::BaseResource
...
field :roles, as: :has_many, searchable: true
```

And simple scope / policy of roles that uses the `account_editor` role to scope only roles that starts with "user_". So an account with the `account_editor` role attached is not able to see his own role.

```ruby
class RolePolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      if user.has_any_role? :admin
        scope.all
      elsif user.has_role? :editor
        scope.where("name LIKE ?", "user_%")
      else
        scope.none
      end
    end
  end
```
This works as expected

![image](https://github.com/avo-hq/avo/assets/26464774/ca1672f0-8324-452a-96b4-1064337a4e36)

But clicking on the search bar will reveal the `account_editor` role that is attached to the user even if this is not in scope.

![image](https://github.com/avo-hq/avo/assets/26464774/20db8c46-19ee-4657-9049-557980736a61)

I would like to ask if this is normal behavior. Maybe I am missing the concept and not seeing the difference between the search and the "index" view of the has_many association.

**Comment by adrianthedev** [comment]
Hey @FLX-0x00 👋

We don't apply the authorization to the search query. Thinking about it, we should, but can't speak for the complexity right now.
I'll ask @Paul-Bob to have a look and respond back on how easy it is, and how long till we add it.

Until then, I think you can apply the policy manually in the `search_query`.

```ruby
# before
scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)

# after
view_context.policy_scope(scope).ransack(id_eq: params[:q], m: "or").result(distinct: false)
```

**Comment by FLX-0x00** [comment]
Got it - thanks for the quick fix, this should be working fine for our needs

**Comment by Paul-Bob** [comment]
Hello @FLX-0x00 thank you for the detailed description.

> I'll ask @Paul-Bob to have a look and respond back on how easy it is, and how long till we add it.

@adrianthedev I think we can apply the policy scope [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L115). Although I haven't tested it yet, I assume that resolving this should be relatively straightforward unless we encounter any unexpected complications during the process.

> and how long till we add it.

We currently have some ongoing tasks at hand, we'll pick this one at the most opportune time. Thank you for your understanding and patience.

**Comment by FLX-0x00** [comment]
Thanks for picking up this issue so fast! You guys are awesome.
