### ISSUE TITLE
GitHub link on https://avohq.io/ is completely broken for me

### ISSUE THREAD

**Issue by brandondrew** [avo-hq/avo#1811]
(I didn't see a repo for the main web site (only for docs.avohq.io) so I'm posting this here.  If the docs repo also includes avohq.io, then it might be good to change the note on that repo.)

### Describe the bug

The GitHub link on https://avohq.io is completely broken, at least for me

### Expected behavior & Actual behavior

I got a nifty animation, and a message "Pop-up Window Blocked".  I did not get taken to a new page.  I expected to be taken to GitHub.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by brandondrew** [comment]
I'm using Safari Version 16.5 (17615.2.9.11.6, 17615) on macOS 12.6.6 (21G646)

**Comment by adrianthedev** [comment]
It's a safari thing. I pushed an update now. thank you!
