### ISSUE TITLE
Location field doesn't show the map

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1814]
### Describe the bug

Using the location field, I am not able to view the map.
- Villa resource contains is set with field :coordinates, as: :location, stored_as: [:lat, :lng]
- I can successfully edit (see screenshot)
- Rails console  ENV['MAPBOX_ACCESS_TOKEN'] returns the Mapbox key (Default public token)
- But the view mode doesn't display the map (see screenshot)

### System configuration
**Avo version**:
avo (2.35.0)

**Rails version**:
rails (7.0.5)

**Ruby version**:
ruby "3.0.2"

**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![Screenshot 2023-06-29 at 13 18 32](https://github.com/avo-hq/avo/assets/201689/4db1b4d2-2467-48a5-ba20-a24ac0f7537b)

![Screenshot 2023-06-29 at 13 20 05](https://github.com/avo-hq/avo/assets/201689/02ed9b2a-e5e2-4b1a-ba3e-64de11aa9d5f)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by iainbeeston** [comment]
I'm seeing this too. My setup is the same. I did wonder if this is because we are both using the `stored_as` option?

**Comment by adrianthedev** [comment]
![](https://media.giphy.com/media/eP1fobjusSbu/giphy.gif)

Hmmm. This is embarrassing.

It seems that the `stored_as` feature is not implemented. It worked on our end and on the tests because we also had setters and getters on that model.

```ruby
  def coordinates
    [latitude, longitude]
  end

  def coordinates=(value)
    self.latitude = value.first
    self.longitude = value.last
  end
```

Can you please add them to your models as a workaround until we fix it?

**Comment by jetienne** [comment]
worked for me! thanks
