### ISSUE TITLE
Sidebar not properly stacked

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1819]
### Describe the bug
The sidebar doesn't display well, not as a right column of the main section:
![Screenshot 2023-07-01 at 09 11 22](https://github.com/avo-hq/avo/assets/201689/bd62f3be-beec-4a6b-a6a7-23f484f43bba)

### Models and resource files

```ruby
class ContactResource < Avo::BaseResource
  self.title = :full_name
  self.includes = []
  self.search_query = -> do
    scope.ransack(id_eq: params[:q], first_name_cont: params[:q], last_name_cont: params[:q], email_cont: params[:q], m: "or").result(distinct: false)
  end

  grid do
    cover :avatar, as: :file, is_image: true
    title :full_name, as: :text, required: true, link_to_resource: true
  end

  field :full_name, as: :text, as_label: true, show_on: :index, hide_on: [:show, :forms]
  field :email, as: :text, show_on: :index, protocol: :mailto, hide_on: [:show, :forms]
  field :phone, as: :text, show_on: :index, protocol: :tel, hide_on: [:show, :forms]

  tabs do
    tab "General" do
      panel do
        row do
          field :first_name, as: :text, stacked: true
          field :last_name, as: :text, stacked: true
        end
        row do
          field :phone, as: :text, stacked: true
          field :phone2, as: :text, hide_on: :index, stacked: true
        end
        row do
          field :email, as: :text, protocol: :mailto, filterable: true, stacked: true
          field :website, as: :text, hide_on: :index, stacked: true
        end
          field :bio, as: :markdown, hide_on: :index
        field :spoken_language, as: :text, hide_on: :index
      end
      field :contact_skills, as: :has_many, show_on: :edit
    end
    tab "Roles" do
      field :associated_roles, as: :has_many, show_on: :edit
    end
  end

  sidebar do
    field :avatar, as: :file, is_image: true, as_avatar: :rounded
  end
end
```

### System configuration
**Avo version**:
v2.35.0

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby "3.2.2"

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yes. That's a known limitation.
It's happening because there are no fields in the main panel. The main panel is created automatically by Avo with all the fields that are not in tabs, sidebar, other `panel`s.

We won't fix this in Avo 2. We are looking into ways of fixing this in Avo 3 as the internals have been reworked a bit.

Closing for now, but I'm open to your feedback and suggestions.
