### ISSUE TITLE
Using :as :tags for habtm associations?

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1820]
### Context
Is it possible to use the :tags field to manage habtm associations?

Let's say, I have a Villa model, and a Amenity model. A villa can have several amenities, and one amenity can be associated to several villas. There is an association model called VillaAmenity.

Today, I am using the belongs_to field, it needs lots of clicks for my user just to add an amenity, and it would be way easier to do it through a tags field. 

If this is possible, could you describe the how-to?

Thanks,

### System configuration
**Avo version**:
v2.35.0

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby "3.2.2"

**License type**
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
I haven't tested it myself, but I remember someone telling me they did it.
I created this new channel for others to share things and asked a question [here](https://discord.com/channels/740892036978442260/1125160641569771550/1125161678280085515).

I bet you could do that using getter and setter methods on the model and pointing the tags field on that property.

Unfortunately I don't have the time right now to prototype this feature.
