### ISSUE TITLE
Row block gives unpermitted parameters

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1823]
### Describe the bug

Using row block in a form, the fields are rejected (unpermitted parameters)

The following code in a resource fails with the issue `Unpermitted parameters: :first_name, :last_name, :phone2, :website. Context: { controller: Avo::ContactsController... `:

```ruby
tabs do
    tab "General" do
      panel do
        row do
          field :first_name, as: :text, stacked: true
          field :last_name, as: :text, stacked: true
        end
```

By commenting the row block, it works: 

```ruby
  tabs do
    tab "General" do
      panel do
        #row do
          field :first_name, as: :text, stacked: true
          field :last_name, as: :text, stacked: true
        #end
```

### System configuration
**Avo version**:
v2.35.0

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby "3.2.2"

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Oups.
Looking into it.

**Comment by jetienne** [comment]
@adrianthedev Thank you. Do you know when this fix will be available? Is there any patch I could apply before this release? Thanks!

**Comment by adrianthedev** [comment]
Releasing `2.36.1` now

**Comment by jetienne** [comment]
works like a charm

**Comment by adrianthedev** [comment]
Ah-mazing!
