### ISSUE TITLE
AvoHQ 2.36 lose chosen file

### ISSUE THREAD

**Issue by dailson-igo** [avo-hq/avo#1828]
### Describe the bug
AvoHQ loses the name and reference of the file chosen to be attached during the creation of a new record if the validation of any field fails.
https://github.com/dailson-igo/losechosenfile

### Steps to Reproduce
1. New record
2. Choose the file to be attached. The file name will appear next to the button to choose the file
3. Leaving some field out of the validation standards, for example, validates :description, presence: true
4. I click on save and the system informs me that some validation failed
5. The file name that appeared next to the selection button disappears, probably the reference was lost and I have to select the same file again

### Expected behavior & Actual behavior
That keeps the selected file even if some validation informs the lack of conformity

### Models and resource files
Model: TestUploadFile

### System configuration
**Avo version**: 2.36

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ X ] Pro (Trial)

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ X ] No

### Screenshots or screen recordings
Before validates:
![Screenshot from 2023-07-04 13-07-56](https://github.com/avo-hq/avo/assets/104414789/14ecfbb4-540b-4e6d-945d-25bd9a64d7a8)

<br>

After validates:
![Screenshot from 2023-07-04 13-07-59](https://github.com/avo-hq/avo/assets/104414789/d8674c8f-2d6e-4d41-91b2-f7c085be5b22)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ X ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ X ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Isn't this default form behavior? Is the file populated back on a validation error?

**Comment by dailson-igo** [comment]
> Isn't this default form behavior? Is the file populated back on a validation error?

I'm sorry Adrian.  It really is the default behavior.  I found a solution and will try to implement it, but if anyone knows how to implement it in AvoHQ, I'll be grateful, and later, we'll put it in the Avo recipes.

Active Storage: How to retain uploaded files on form resubmission?
https://medium.com/@TETRA2000/active-storage-how-to-retain-uploaded-files-on-form-resubmission-91b57be78d53

**Comment by Paul-Bob** [comment]
Hi @dailson-igo, actually I'm also intrigued by this behavior and would love to improve it. We have a lot going on right now and would appreciate if someone take initiative to submit a PR with a possible resolution. We should cover all "fluxes". For example, if form submission fail on validation but user close the tab or press cancel button instead re-submit the form,  we should assure somehow that active storage don't store inaccessible "garbage".

We'll not prioritize this one because it's the default behavior, but again, we'll  gratefully review a possible resolution.

**Comment by adrianthedev** [comment]
Yes, this is a problem that is not easily fixable for everyone. The attaching mechanisms are quite complex.
I think you will be able to fix this issue in your particular instance with some hooking into the resource controller. Check out the `create`, `update`, `fill_model`, and `set_model_to_fill` methods in `Avo::BaseController` among others.

If there's anything we can do to accommodate you having this feature, please submit a PR and we'd love to make it easier for folks to add this on their Avo apps too ✌️

Closing for now, but feel free to reopen it.
