### ISSUE TITLE
Keep current active tab when editing

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1834]
### Feature

When using tabs, it would be great:
- when clicking on 'edit', the current tab remains the active editing one
- when saving, it redirects to the same tab as the one your just edited

**Comment by adrianthedev** [comment]
Thanks for these recommendations. They are definitely good improvements to have.

We'd love to merge PRs that add that functionality if we had them.

**Comment by michael-lins** [comment]
I was reading the [Tab documentation page](https://docs.avohq.io/2.0/tabs.html) and realised it is a **Pro** feature. Can we help with this issue using the GitHub code without a license?

**Comment by adrianthedev** [comment]
Yes. That's possible. You should be able to do that locally in the development env.

**Comment by michael-lins** [comment]
Interesting, I'm going to give this a try then, since I'm willing to engage in Avo development.

**Comment by adrianthedev** [comment]
This if fixed.
