### ISSUE TITLE
Alternative wysiwyg integration options

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#1839]
### Feature

It would be great to either have a built-in custom wysiwyg support (e.g. tinyMCE or any other), or have an option to set custom class to `textarea` field so even Free license users can use custom wysiwyg.

Having `trix` support is great but it's very limited in text formatting features.

### Current workarounds

Pro license + custom field type makes this possible, but it's not very user-friendly. Not only it requires creating a custom field, but also requires a Pro license.

### Screenshots or screen recordings

N/A

### Additional context

N/A

**Comment by adrianthedev** [comment]
> Pro license + custom field type makes this possible, but it's not very user-friendly

I don't know how to make it more user-friendly other than enabling custom fields and enabling users to create exactly hat they want.

Again, Trix is a great way to get started. I agree it's not the best in it's class or the most flexible one.
I see that you're on the Community license.

We would accept a PR to add TipTap to Avo as a standard field. That would go into the Community license, so your contribution would immediately fix your issue and help others in the process.

I'll paste over some

**Comment by xeron** [comment]
> I don't know how to make it more user-friendly other than enabling custom fields and enabling users to create exactly hat they want.

There's already a way to add custom JS to avo pages - https://docs.avohq.io/2.0/custom-asset-pipeline.html and https://docs.avohq.io/2.0/customization.html

Using this ^^ it should be possible to add tinymce or any other headless javascript based wysiwyg.

However next step is usually to assign some class to textarea field, which is currently not possible without using custom fields.

I was thinking may be instead of adding new field type, it would be possible to add custom class functionality to textarea (and other fields)?

E.g. something like this:

```ruby
field :content, as: :textarea, class: tinymce
```

What do you think?

P.S. Actually while typing this I realized tinymce allows to override the selector for textarea field, so may be I should just specify some class already assigned by avo?

I'll look into opening a PR if I won't be able to solve it using existing customization options.

**Comment by xeron** [comment]
I just tried this approach and it works, but only if I refresh the "edit" page. If I just press "edit" from the index it doesn't work most of the times. I think javascript init which replaces textarea with wysiwyg isn't being triggered when page is loaded with Turbo.

**Comment by adrianthedev** [comment]
Yes. That approach is not going to be bulletproof because of how Turbo works.
The JS plugin (tinymce, or another) is listening for the `document:load` event which in Turbo apps is only triggered once on page load and not when user navigates the website.
Turbo emits the `turbo:load` event.

In order to make this easier to work with we used Stimulus controllers which natively hook into the `turbo:load` event.

So, the way to do that is to use a new Stimulus controller to initialize the JS plugin.
I think you'll find much inspiration by jumping into the code and checking out those PRs I highlighted above.
You should be able to create one yourself.

**Comment by xeron** [comment]
Yes, thanks, I'll figure it out.

For now I've settled on calling `tinyMCE.stop()` before initializing it to workaround Turbo. It's slow but it works.

I actually tried to implement it using Stimulus but I think my JS knowledge is not good enough to figure this out. I may try again in the future.
