### ISSUE TITLE
Edit won't edit the right resource

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1842]
### Describe the bug

Let's pretend we have a Villa resource, and Villa belongs to Destination.

### Steps to Reproduce
1. Search for a villa and open the view page
2. Click on the destination name (it opens the destination view page
3. Click on Edit (edit destination)
-> It edits the villa, not the destination

### System configuration
**Avo version**:
v2.36.1

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby '3.2.2'

**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
I tried this on my end and can't seem to reproduce it.
Can you please create a reproduction repo cause it's very weird behavior. It shouldn't happen.

**Comment by jetienne** [comment]
@adrianthedev I will try to extract this issue then... 

I recorded a BEB: https://app.birdeatsbug.com/sessions/KIEfgTXzw9dr2JV0cyh6lNxA5clqVv0aowA0YGxsCIch, so you can see the upper part of the page is not updated, the edit CTA is still the one for the Villa

**Comment by adrianthedev** [comment]
Hmmm. I suspect that it's because it loads the link inside a turbo-frame, and not the main view.
That's why we request reproduction repos 😅

OK. We'll have a look.

**Comment by Paul-Bob** [comment]
Hi @jetienne!

Indeed there is a bug. We need to reproduce it somehow in order to fix it, can you please provide a little reproduction repository? Even the involved resources code would be helpful for now.

Thank you for understanding

**Comment by jetienne** [comment]
@Paul-Bob I just shared a private repository (check the readme file). You can then easily reproduce the bug, by doing the exact same steps as my birdeatsbug.

**Comment by jetienne** [comment]
Thanks a lot. Can I kill the repo?

**Comment by Paul-Bob** [comment]
Go for it!
