### ISSUE TITLE
Markdown Editing content is hidden

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1843]
### Describe the bug

We have a resource Villa with a field description (field :description, as: :markdown, stacked: true).  The field is part of a tab.

### Steps to Reproduce
1. Search for a villa
2. Click on the tab 'Description'. (Markdown content is display properly)
3. Click on Edit, then tab 'Description'
BUG: the markdown editing content is empty
4. Click on the block, the content appears

### System configuration
**Avo version**:
v2.36.1

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby '3.2.2'

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2023-07-11 at 14 46 51](https://github.com/avo-hq/avo/assets/201689/ec12ed83-740a-4024-b5a9-a798f5bc413f)

After clicking on the bloc:
![Screenshot 2023-07-11 at 14 46 57](https://github.com/avo-hq/avo/assets/201689/6d4d14b6-240e-499d-9933-d48c33cfc74f)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
It's a bug. I'm on it.

**Comment by adrianthedev** [comment]
@jetienne can you live with this for a little while longer?
I'd like to focus on launching Avo 3 and refactor the tabs feature a bit so we don't have that issue anymore.

**Comment by jetienne** [comment]
@adrianthedev It all depends when I can be live (production) with the v3...
