### ISSUE TITLE
Action on "Select all matching" raises "ActiveModel::MissingAttributeError"

### ISSUE THREAD

**Issue by smathieu** [avo-hq/avo#1850]
### Describe the bug

When running an action against multiple page of results from the index view of a resource (by clicking "[Select all matching]"), the action fails by raising a ActiveModel::MissingAttributeError.

The generated query by Avo is

```sql
SELECT "catalog_products"."id" AS t0_r0, "catalog_products"."source_id" AS t0_r1, "catalog_products"."source" AS t0_r2, "catalog_products"."name" AS t0_r3, "catalog_products"."image_url" AS t0_r4, "catalog_products"."description" AS t0_r5, "catalog_products"."created_at" AS t0_r6, "catalog_products"."updated_at" AS t0_r7, "catalog_products"."manufacturer_id" AS t0_r8, "catalog_products"."subtype" AS t0_r9, "catalog_products"."slug" AS t0_r10, "catalog_products"."published" AS t0_r11, "catalog_products"."primary_category_id" AS t0_r12, "certifications"."id" AS t1_r0, "certifications"."product_id" AS t1_r1, "certifications"."source" AS t1_r2, "certifications"."source_id" AS t1_r3, "certifications"."certification_type" AS t1_r4, "certifications"."issued_at" AS t1_r5, "certifications"."expires_at" AS t1_r6, "certifications"."created_at" AS t1_r7, "certifications"."updated_at" AS t1_r8 FROM "catalog_products" INNER JOIN "catalog_product_categories" ON "catalog_product_categories"."product_id" = "catalog_products"."id" INNER JOIN "catalog_categories" ON "catalog_categories"."id" = "catalog_product_categories"."category_id" INNER JOIN "catalog_certifications" "certifications" ON "certifications"."product_id" = "catalog_products"."id" WHERE "catalog_product_categories"."category_id" = 8 AND "certifications"."certification_type" = 'product_epd' AND "catalog_products"."published" = TRUE ORDER BY catalog_products.created_at desc
```

Action code is:

```ruby
class PublishAction < Avo::BaseAction
  self.name = "Publish"

  field :published, as: :boolean

  def handle(**args)
    args[:models].each do |model|
      model.update(published: args[:fields]["published"])
    end
  end
end
```

By inspecting the `args[:models]` attribute of the action, I can see the `id` attribute is not being set. e.g. ` #<Catalog::Product:0x00000001143f9c50 id: nil>`

I suspect is because the `ActionsController` uses `find_by_sql`, but the `id` attribute in the query was aliased to `t0_r0`, preventing ActiveRecord to mapping the attributes back to the model. 

### Steps to Reproduce
1. Create an action
2. On the index view, apply the action to multiple pages of results.
3. 
### Expected behavior & Actual behavior
Models are loaded correctly

### System configuration
**Avo version**: 2.36.1

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by smathieu** [comment]
As a side note (and feature request), it would be nice if `models` could be an active record scopes, rather than an array of models to make batch update easier.

e.g.
```ruby
models.update_all(published: false)
```

**Comment by adrianthedev** [comment]
> As a side note (and feature request), it would be nice if models could be an active record scopes, rather than an array of models to make batch update easier.

This is a very good idea! Thanks!

We'll have a look and try to reproduce it.

**Comment by Paul-Bob** [comment]
Hello @smathieu.

Unfortunately, we weren't able to reproduce the issue. It's possible that the bug only occurs with a specific configuration or query. We kindly request a small reproduction repository to help us replicate the bug and resolve it.

Thank you for your understanding.

**Comment by smathieu** [comment]
Is there a reproduction repo I can fork and start with?

After testing this some more, I wanted to provide more details for the reproduction. This seems to only happen when selecting all values after a filter was applied. The filter in question is joining to a different table, which generates these ID aliases in the query.

<img width="1243" alt="filters" src="https://github.com/avo-hq/avo/assets/148622/fc8b61ec-8049-46fe-920d-933d44b9a3ae">

Filter code:

```ruby
class CertificationFilter < Avo::Filters::SelectFilter
  self.name = "Certification Type"

  def apply(_request, query, value)
    if value
      query = query.certified_with(value)
    end
    query
  end

  def options
    Catalog::Certification.certification_types.keys.inject({}) do |h, v|
      h[v] = v.humanize.titleize
      h
    end
  end
end
```

Implementation of `certified_with`

```ruby
    scope :certified_with, ->(certification) do
      joins(:certifications).where(certifications: { certification_type: certification })
    end
```

**Comment by Paul-Bob** [comment]
My guess is that somewhere the query gets "buggy" and with a tweak on the right place we can make it work. It's hard for me to debug it without access to the repo.

> Is there a reproduction repo I can fork and start with?
No, there isn't.

I recommend performing a step-by-step debug process to identify where the query is breaking. Make sure that the scope is properly added to the query .

We have previously received reports about the select all feature, and most of them were resolved by fixing the query returned in the `apply` method of the filter.

**Comment by adrianthedev** [comment]
@smathieu you could start from https://github.com/avo-hq/main.avodemo.com/tree/pre-avo-3 (`pre-avo-3` branch uses Avo 2).

**Comment by Paul-Bob** [comment]
Hi @smathieu, any updates?

**Comment by adrianthedev** [comment]
Closing for now. Please feel free to reopen if this still persists.
