### ISSUE TITLE
NoMethodError (undefined method `attach_scope' for #<Avo::Fields::TextField

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1851]
### Describe the bug

We have a Villa model, belongs_to Destination. When editing the villa, the searchable destination modal raises an error:
`NoMethodError (undefined method `attach_scope' for #<Avo::Fields::TextField`

### Steps to Reproduce
https://app.birdeatsbug.com/sessions/2CkdppWGtQ2q9vD1wCUpGMqEsrZ0qMkPdr4IHrKQP3uJ

### Models and resource files

```ruby
class villa < ApplicationRecord

    belongs_to :destination
```

```ruby
class VillaResource < Avo::BaseResource
      ....
      panel name: "Locations" do
        row do
          field :destination, as: :belongs_to, searchable: true, stacked: true
```

### System configuration
**Avo version**:
avo (2.36.1)

**Rails version**:
gem "rails", "~> 7.0.6"

**Ruby version**:
ruby '3.2.2'

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
does the `destination` resource have the `search_query` configured?

**Comment by jetienne** [comment]
yes:

```ruby
class DestinationResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.search_query = -> do
    scope.ransack(name_cont: params[:q], m: "or").result(distinct: false)
  end
```

Moreover, destination is used by an other belongs_to, and it works there.

**Comment by adrianthedev** [comment]
![CleanShot 2023-07-13 at 12 10 46](https://github.com/avo-hq/avo/assets/1334409/48b74fb8-1767-4546-9a04-a876dfea2170)
Would you be able to make that public?

I tried it on the dummy app using this configuration and can't seem to reproduce it.

```ruby
  panel do
    row do
      field :course, as: :belongs_to, searchable: true, stacked: true
    end
  end
```

**Comment by jetienne** [comment]
@adrianthedev I found the issue:

This code fails:

```ruby
class VillaResource < Avo::BaseResource
...
  field :destination, as: :text, hide_on: %i[show forms] do |model|
    "#{model.destination.name} - #{model.destination.parent.try(:name)}"
  end

  tabs do
    tab 'General' do
       ...
      panel name: 'Locations' do
        row do
          field :destination, as: :belongs_to, searchable: true, stacked: true
```

When this one doesn't fail

```ruby
  field :destination_path, as: :text, hide_on: %i[show forms] do |model|
    "#{model.destination.name} - #{model.destination.parent.try(:name)}"
  end

  tabs do
    tab 'General' do
       ...
      panel name: 'Locations' do
        row do
          field :destination, as: :belongs_to, searchable: true, stacked: true
```

**Comment by adrianthedev** [comment]
Hmm. Ok. It matches the initial `text` `:destination` field instead of the belongs_to. 

Yeah. The rename makes sense.
