### ISSUE TITLE
Unpermitted parameters for date fields in an action

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1857]
### Describe the bug
Passing some date fields in an action fails.

### Steps to Reproduce
1. Create an action
2. Add some fields like 
```ruby
  field :date_from, as: :date
  field :date_to, as: :date
```
3. Run the action

```ruby
`16:33:18 web.1  | Unpermitted parameters: :fake_from, :fake_to. Context: { controller: Avo::ActionsController, action: handle, request: #<ActionDispatch::Request:0x000000011f3bf838>, params: {"authenticity_token"=>"[FILTERED]", "action_id"=>"BulkAvailabilities", "fields"=>{"avo_resource_ids"=>"033d5edb-f1cb-4afb-a8a2-7021335f71d2", "avo_selected_query"=>"", "from"=>"2023/07/20", "to"=>"2023/07/30", "slot_duration"=>"2", "rate"=>"300", "rate_currency"=>"USD"}, "fake_from"=>{"fake"=>"2023-07-20"}, "fake_to"=>{"fake"=>"2023-07-30"}, "button"=>"", "controller"=>"avo/actions", "action"=>"handle", "resource_name"=>"villas"} }``
```

### System configuration
**Avo version**:
v2.37.0

**Rails version**:
rails (7.0.6)

**Ruby version**:
ruby '3.2.2'

**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Those fake inputs are there just so we can attach the JS plugin to them AFAIK.
Are the regular fields `date_from` & `date_to` not updating the values?

**Comment by jetienne** [comment]
@adrianthedev My bad, in fact they are. I had some issues because the fields are not date (but strings), and I was mislead by the error I mentioned.
We can close this ticket.

**Comment by adrianthedev** [comment]
I agree that the experience around date & datetime fields is not perfect. I'd love to get some time to improve those. We'd welcome PRs too.
