### ISSUE TITLE
Resource titles on index pages are not respecting Rails inflection rules.

### ISSUE THREAD

**Issue by jcn** [avo-hq/avo#1858]
### Describe the bug
Resource titles on index pages are not respecting Rails inflection rules. 

### Steps to Reproduce
1. Add this configuration 

    - Add a resource which is named as an acronym (msa.rb) with class name MSA < ApplicationRecord
    - Add the inflection to the inflections.rb file `inflect.acronym "MSA"` and `inflect.acronym "MSAs" `
    - Create Avo resource

2. Go to /avo/resoures/msas
3. See that the header shows "Msas" instead of "MSAs" (note that the sidebar and breadcrumb display properly)

### Expected behavior & Actual behavior
Title on the page should show "MSAs" as per the inflection rules.

### System configuration
**Avo version**:
3.0.0.pre13 though this is showing in 2 as well

**Rails version**:
7.0.6

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

![](https://cdn.discordapp.com/attachments/740893011994738751/1131688167720894494/Screen_Shot_2023-07-20_at_4.43.20_PM.png)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

# Proposed solution
Solution appears to be to change https://github.com/avo-hq/avo/blob/5d8b9109d43abcb9d1aa359c7761ad40fb82540d/lib/avo/base_resource.rb#L266 to use `.humanize` instead of `.capitalize` and probably in base_field.rb as well on https://github.com/avo-hq/avo/blob/5d8b9109d43abcb9d1aa359c7761ad40fb82540d/lib/avo/fields/base_field.rb#L127 and https://github.com/avo-hq/avo/blob/5d8b9109d43abcb9d1aa359c7761ad40fb82540d/lib/avo/fields/base_field.rb#L137C6-L137C6

**Comment by adrianthedev** [comment]
Related thread: https://discord.com/channels/740892036978442260/740893011994738751/1131688167922216971
