### ISSUE TITLE
Standalone actions to access the parent model

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1864]
### Feature

It would be beneficial to have access to the parent model when working with a standalone action in an association, given its wide range of applications such as bulk importing items associated with the parent model.

### Current workarounds

Currently, a workaround exists where the standalone action is used on the parent resource. However, this approach lacks context as the action is displayed at the top of the page instead of being positioned adjacent to the relevant association.

**Comment by adrianthedev** [comment]
Hmmm. Are we talking about the same thing?
In this scenario a User has_many TeamMembers. Are you talking about the "Actions" dropdown on the Team Members?

![CleanShot 2023-07-25 at 11 12 24](https://github.com/avo-hq/avo/assets/1334409/9cc2fc4b-7392-49a7-91e7-b4809321885d)


https://main.avodemo.com/avo/resources/teams/4#:~:text=Attach%20team%20member-,Actions,-Create%20new%20team

**Comment by jetienne** [comment]
Yes, exactly

**Comment by adrianthedev** [comment]
You can use hidden fields and the `request.referer` value to get that information. Those field values will be passed to the `handle` method.
We'd welcome a more first-party solution if you'd like to dive into the code and submit a PR.

But please wait until we merge #1865 and cut a release which fixes a bug where hidden fields are not displayed.

```ruby
  field :parent_id,
    as: :hidden,
    default: -> do
      get_id(Avo::App.request.referer) # strip the id from the referer string
    end
  field :parent_type,
    as: :hidden,
    default: -> do
      get_type(Avo::App.request.referer) # strip the type from the referer string
    end
```

**Comment by adrianthedev** [comment]
Releasing 2.37.1 now
