### ISSUE TITLE
Action lightbox does not scroll

### ISSUE THREAD

**Issue by cdanzig** [avo-hq/avo#1866]
*problem*
If you have a large number of fields for an action the lightbox is unusable as it does not scroll.

*proposed solution*
I would suggest adding the following css attributes to .modal-body

    overflow: auto;
    max-height: 100%;

**Comment by adrianthedev** [comment]
Hey @cdanzig!

Would you be available to send in a PR with this fix?

**Comment by cdanzig** [comment]
https://github.com/avo-hq/avo/pull/1867
