### ISSUE TITLE
Display an action to hide Trix field content in index/show pages (as opposed to the existing show content)

### ISSUE THREAD

**Issue by michael-lins** [avo-hq/avo#1871]
### Feature
I would like to suggest an action to hide Trix field content in index/show pages as opposed to the existing show content.

### Current workarounds
I understand this is currently achievable by adding custom code to the project's implementations in isolation, but it would be interesting to have this as a built-in feature activated by code customization on avo resources.

### Screenshots or screen recordings
Example of existing Show Content of Trix fields on index/show pages
<img width="752" alt="Example of existing Show Content of Trix fields on index/show pages" src="https://github.com/avo-hq/avo/assets/1015076/5eeb8806-b664-4238-8a65-3701dad581b8">

Example of the suggested action in place to hide Trix content
<img width="771" alt="Example of the suggested action in place to hide Trix content" src="https://github.com/avo-hq/avo/assets/1015076/2b5b9ab0-7c62-430e-ac9b-2ef11ffd219e">

### Additional context
No, I just imagined it would be useful as I got a very huge content to visualize on the example page.

**Comment by adrianthedev** [comment]
Yeah, I think That's a good idea!
I see it as a field option `always_show_content: true` which defaults to `false`. What do you think?

Would you be able to submit a PR for it?

PS: Apologies for the late reply. We've been pretty busy with the v3 launch.

**Comment by zhephyn** [comment]
Hey @adrianthedev . Could this issue be assigned to me and i work through it?

**Comment by Paul-Bob** [comment]
Thank you @zhephyn !

**Comment by zhephyn** [comment]
Hey @Paul-Bob . I'm setting up my local environment for development and so far its been going great. However when i navigate to the url "http://localhost:3030/admin/resources/projects" as part of the dummy app, i get the error below. 
![Image](https://github.com/user-attachments/assets/b335b575-b322-42be-b916-657f4a5982a5)
![Image](https://github.com/user-attachments/assets/d630437c-094a-4d20-8c07-c9aba9910dae)
I can fix the above error however, what I'm inquiring about is that if i were to proceed to fix the error, should i use the same branch for the initial "Trix show/hide content" feature or its better to solve the above error individually with its own branch, after which i can then proceed to implement the "show/hide content" feature? For context, I'm using a windows machine if that helps in anyway. Also, i understand that this could be an issue on just my end, which if that's the case, then i'll just solve it and work through the initial feature i was supposed to implement. Thanks in advance.

**Comment by Paul-Bob** [comment]
Hey @zhephyn 

> Also, i understand that this could be an issue on just my end, which if that's the case, then i'll just solve it and work through the initial feature i was supposed to implement. 

I think that's the case, try starting the server by running `bin/dev` which will also trigger the necessary builds.

**Comment by zhephyn** [comment]
Hey @Paul-Bob . Is the bin/dev command supposed to be prefixed by the word "ruby" when running it in the terminal as "ruby bin/dev"? I've CD'd into the avo directory and tried running just "bin/dev" in my terminal(git bash), but i get  "bin not recognized as a command error". Then when i run the "ruby bin/dev" command, i get a "no ruby script found in input" error. Is this the right way of running the bin/dev command? 
PS: I'm sorry if these questions seem very basic, its my first time setting up the repository and running into these errors because of the OS i'm running is very frustrating. Thanks in advance.

**Comment by Paul-Bob** [comment]
> but i get "bin not recognized as a command error"

Make sure to be on the avo directory and run it like: `bin/dev` (all together)

![Image](https://github.com/user-attachments/assets/3d9d483c-f411-49b8-a02a-54ef63da7247)

> I'm sorry if these questions seem very basic

It's ok, no need to apologize

`bin/dev` it's a script basically

> running into these errors because of the OS i'm running is very frustrating.

It might be related with the OS, are you using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)?

**Comment by zhephyn** [comment]
I'm using git bash and below is what i see in the terminal when i run bin/dev
![Image](https://github.com/user-attachments/assets/f4a6017e-08a7-4995-99c3-998384c16d58)

**Comment by zhephyn** [comment]
Glad to say i've reached some progress. I made the 2 changes you recommended above, then ran the bin/dev command. I got this error in the terminal.
![Image](https://github.com/user-attachments/assets/47e29baf-e26c-4b63-8f46-6f778e1284ba)
Then to solve the above error, i changed the first line in the Procfile.dev file from: `web: bin/rails server -p 3030` to: `web: rails server -p 3030`. Screenshot of final code attached below.
![Image](https://github.com/user-attachments/assets/5103a326-47a1-458b-a995-276a0107b72e)
After the above change, running the bin/dev command proceeded as expected for the CSS and JS files. However, towards the end, i ran into an error related to associated with foreman.
![Image](https://github.com/user-attachments/assets/59a12a6f-5b4d-4144-b09e-5019b6e58eca)
Regardless of this though, i managed to access the projects page of the dummy app in the browser by navigating to localhost:3000, something which was impossible before, showing that the build process was partly successful. 
![Image](https://github.com/user-attachments/assets/93c0325b-664d-4db4-87c6-fabc5b3e9a3a)
Now i think it might be okay to proceed with the feature implementation.
PS: You mentioned not commiting the previous changes i made when setting up the development environment. Could you elaborate more on this? I'm yet to create a branch for the show/hide content trix feature.

**Comment by zhephyn** [comment]
Hey @Paul-Bob . i worked through this and opened a PR. I'd appreciate any feedback in reference to it. Thanks in advance.

**Comment by Paul-Bob** [comment]
Duplicated issue, closing in favor of https://github.com/avo-hq/avo/issues/3263
