### ISSUE TITLE
Catch and show ransack errors

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1881]
### Feature

Ransack 4 requires the user to declare `ransackable_attributes` and associations on the model. When someone uses the search feature, the failures will make the search unusable.
Let's catch that error and display it to the user.

**Comment by Paul-Bob** [comment]
@adrianthedev the error raises on an JS request, that means that we need to "manually" handle it with JS.

I found another way to raise the error and don't handle it with JS. We can run `Avo::ExecutionContext.new(target: resource.class.search_query, params: {}, query: resource.model_class).handle`  when the search input box is loading, and if something is wrong with ransack the error will raise on load (and the normal rails error page appear) and not when searching.

Not sure which one to implement, if we want to handle the error with JS maybe we should render an error modal (only in development) that have the error text and a close button.

**Comment by adrianthedev** [comment]
Let's do a check when we display the search bar for resource search (not global) and show a floating alert to say that.
THe alert will be visible only if the `self.search` is present and `MODEL.ransackable_attributes` is not set.
If the resource does not have the `self.search` enabled, we don't show that.

For the global search let's not try to search in that resource if `ransackable_attributes` is missing.

Does that work?

**Comment by Paul-Bob** [comment]
Yes but someone not using ransack on the `self.search` will be spammed with that alert without necessity

**Comment by adrianthedev** [comment]
> THe alert will be visible only if the self.search is present

Only if self search is present

**Comment by Paul-Bob** [comment]
> someone not using ransack 

Let's say someone uses `pg_search`, will still have the `self.search` present and don't need `ransackable_attributes`

**Comment by adrianthedev** [comment]
We'll solve this with this hack of resuing with a search item describing the error.

```ruby

    rescue
      [{
        "🚨🚨 THIS error appears 🚨🚨"
      }]
```

In the next iteration we'll remove the JS plugin for ever.
