### ISSUE TITLE
Filtering results with FILTER are not retained when returning with the 'Go back' button.

### ISSUE THREAD

**Issue by yuki-yogi** [avo-hq/avo#1883]
### Describe the bug
When moving to the show screen from a list result filtered by FILTER and then returning with the 'Go back' button, the FILTER filtration is canceled.
As well as the new Dynamic FILTER feature in avo3, this also occurs with the current avo(2.38.0) FILTER.

### Steps to Reproduce
1. Filter by FILTER
2. Transition from the narrowed down list of results to the detail screen
3. Go back with the 'Go back' button from the show screen

### Expected behavior & Actual behavior
It is desirable that the FILTER filtering state is maintained even after moving to the show screen after filtering with the FILTER and then returning to the index screen with the 'Go back' button.

### System configuration
**Avo version**: 3.0: https://avodemo.com/avo/resources/courses
**Avo version**: 2.38.0 (also too)
**Rails version**: 7.0.6
**Ruby version**: 3.2.2
**License type**:

 - [ ] Community
 - [x] Pro
**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
[Courses-—-Avodemo7.webm](https://github.com/avo-hq/avo/assets/14293538/398bf1cb-604d-49f6-9250-8ead4c45a0c8)

[Users-—-Avodemo7.webm](https://github.com/avo-hq/avo/assets/14293538/e844b24a-539e-42eb-8d67-336e7ea93892)

### Additional context
I will try to avoid this by adding an implementation that opens the link to the details screen in a new tab in my app.

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yeah. The back button is a PITA to make it "smart".
We'll probably end up removing it in the stable release. 

Another way we could "fix" this is to remember the last state of filters in `session` somewhere and just restore them nomatter where you cam from (as a back action or not).

In any case, the back button ate up too much of our time.
