### ISSUE TITLE
Issues using active record models with acts_as_tenant gem

### ISSUE THREAD

**Issue by qubbit** [avo-hq/avo#1884]
### Context
I'm using acts_as_tenant to provide multi-tenancy. I have added `acts_as_tenant :account
` to my `Employee` model. Whenever I attempt to create an employee record through Avo, I get a db rollback even though the `account_id` is provided. I suspect this has to do with strong params, but what I don't understand is `acts_as_tenant` is adding the accound_id with a default scope at a lower level than the rails controller. Trying to understand how I can mitigate this issue of not being able to pass in this account_id.

Error log

```
Set tenant Super admin
THE PARAMS {"authenticity_token"=>"shRa3sPIRauIpAaokbpqBCr5QucFD7RcmD6TpjL5Il-5pbEy7QQUDF4JJ5zQxcMZoqBTJAzOGPESRT58ul5yEg", "employee"=>#<ActionController::Parameters {"first_name"=>"G", "last_name"=>"A", "date_of_birth"=>"2023/08/11", "driver_license"=>"", "license_state"=>"OH", "license_expiry"=>"", "bci_date"=>"", "bci_expiration_date"=>"", "ssn"=>"", "cpr_certification_date"=>"", "cpr_certification_expiry_date"=>"", "hire_date"=>"", "employment_start_date"=>"", "termination_date"=>""} permitted: false>, "fake_date_of_birth"=>{"fake"=>"2023-08-11"}, "fake_license_expiry"=>{"fake"=>""}, "fake_bci_date"=>{"fake"=>""}, "fake_bci_expiration_date"=>{"fake"=>""}, "fake_cpr_certification_date"=>{"fake"=>""}, "fake_cpr_certification_expiry_date"=>{"fake"=>""}, "fake_hire_date"=>{"fake"=>""}, "fake_employment_start_date"=>{"fake"=>""}, "fake_termination_date"=>{"fake"=>""}, "button"=>"", "controller"=>"avo/employees", "action"=>"create"}
  TRANSACTION (0.1ms)  BEGIN
  Account Load (0.2ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Employee Create (0.3ms)  INSERT INTO "employees" ("first_name", "last_name", "date_of_birth", "driver_license", "license_state", "license_expiry", "created_at", "updated_at", "ssn", "bci_date", "bci_expiration_date", "cpr_certification_date", "cpr_renewed_date", "hire_date", "employment_start_date", "termination_date", "cpr_certification_expiry_date", "account_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING "id"  [["first_name", "G"], ["last_name", "A"], ["date_of_birth", "2023-08-11"], ["driver_license", ""], ["license_state", "OH"], ["license_expiry", nil], ["created_at", "2023-08-06 19:59:29.842289"], ["updated_at", "2023-08-06 19:59:29.842289"], ["ssn", "[FILTERED]"], ["bci_date", nil], ["bci_expiration_date", nil], ["cpr_certification_date", nil], ["cpr_renewed_date", nil], ["hire_date", nil], ["employment_start_date", nil], ["termination_date", nil], ["cpr_certification_expiry_date", nil], ["account_id", 1]]
  TRANSACTION (0.1ms)  ROLLBACK
```

### System configuration
**Avo version**: 2.37.2 

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by Paul-Bob** [comment]
Hi @qubbit, without `acts_as_tenant` it works fine?

Can you provide more information please? **Model** and **resource** **relevant code** and **full error stack** would be helpful

**Comment by qubbit** [comment]
Hi @Paul-Bob I apologize, but after many minutes spent into this pulling my hair I found out it was caused by the `audited` gem (which I'm using for generating audit records). In my defense, there was no indication of why this was happening in the error message.
