### ISSUE TITLE
Authorization on a custom field disallows access to index

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1885]
### Describe the bug

When hiding a given field of a resource, based on a Pundit policy, the whole resource is not accessible anymore.

### Steps to Reproduce
1. Create a model `Contact` with name, age and comments
2. Add a Pundit Policy, so the comments are visible only if age < 18
3. Issue: contracts#index is not accessible anymore

### Models and resource files

Full repository here: https://github.com/mercey-co/field_auth

### System configuration
**Avo version**:
v2.38.0

**Rails version**:
v7.0.6

**Ruby version**:
v3.2.2

**License type**:
 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://www.loom.com/share/e3b2fc94a800469b98d84ed124f0d0af?sid=d1d8f4fd-3068-443d-b556-673b5443cc45

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @jetienne.

First of all you don't need this on the comments field: 
```ruby
visible: ->(resource:) { resource.authorization.authorize_action(:show_comments?) }
``` 
https://docs.avohq.io/2.0/authorization.html#view_association

The issue only appears when the code 
```ruby
  def show_comments?
    record.age < 18
  end
```
is present on the `Avo::ContactPolicy` class?!

Can you restart the server and confirm that the issue persists?

**Comment by jetienne** [comment]
@Paul-Bob I reworked my example, so there is only one method on the policy file, for several fields on the resource (father_name, mother_name)

**Comment by jetienne** [comment]
I think #index is 403, because the fields are not accessible. But I am not displaying those fields on the index view...

**Comment by Paul-Bob** [comment]
It's working fine on my end
![image](https://github.com/avo-hq/avo/assets/69730720/96fa5119-b315-4829-91d9-78155077e9be)

**Comment by jetienne** [comment]
Just try to click on Create new contact

**Comment by Paul-Bob** [comment]
`resource.authorization.authorize_action(:show_parents?)` instead returning `false` is raising an exception that we normally catch when an request is not authorized to be rendered. 

In order to fix this you should modify it to `resource.authorization.authorize_action(:show_parents?, raise_exception: false)`

Maybe an field level authorization feature would make sense in this cases.

**Comment by jetienne** [comment]
Thank you. OK, I can then raise_exception: false.. Perhaps useful to add this to the documentation..

**Comment by Paul-Bob** [comment]
We do not have documentation about this internal methods. We would recommend to use it this way instead from policy.

```ruby
  with_options hide_on: :index, visible: ->(resource:) { resource.model.age.present? && resource.model.age < 18 } do
    field :father_name, as: :text
    field :mother_name, as: :text
  end
```

I'm not sure why you opted by policy instead direct logic inside visible block.

**Comment by jetienne** [comment]
for Single Responsibility Principle reasons :)

**Comment by Paul-Bob** [comment]
Can't disagree with that! =))

I'll close this issue as solved, feel free to reopen it if necessary!
