### ISSUE TITLE
[V3] using symbol notation to initialize a custom field does not work

### ISSUE THREAD

**Issue by maxencehenneron** [avo-hq/avo#1888]
### Describe the bug

using the following syntax does not seem to work on custom fields:

```ruby
field :text_test, as: :test
```

The following syntax works:

```ruby
field :text_test, as: Avo::Fields::TestField
```

### Steps to Reproduce

Create a custom field 

bin/rails generate avo:field test

add the field to a resource

field :text_test, as: :test 

### Expected behavior & Actual behavior

Expected behavior
It should display the custom "test" field

Actual behavior
An error displays:

```
There's an invalid field configuration for this resource.
field :text_test, as: :test
```

### System configuration
**Avo version**: v3.0.1.beta2

**Rails version**: 7.0.6

**Ruby version**: 3.0.4p208

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Thank you @maxencehenneron! We'll have this fixed before the stable release.
