### ISSUE TITLE
Can This Work With Shrine / Carrierwave etc?

### ISSUE THREAD

**Issue by ssingh510** [avo-hq/avo#189]
Hi,

I'm trying to use the file field with a shrine column and I keep getting an error of 

undefined method 'attached?' for nil class. 

I'm not sure if it's a problem on my end or if it's because of the gem.

Setup is straight forward, installed shrine gem, did a database migration to add image_data as a json column to my Post model and then used the file field on the shrine virtual attribute (column is :image_data)

file :image, is_image: true

**Comment by adrianthedev** [comment]
Hi.

At the moment Avo supports rails [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html) for file uploads. If this is a new project you could try it. Active Storage is pretty easy to work with and Avo's integration with it is super quick.
Otherwise, the field declaration is correct `file :image, is_image: true`

**Comment by ssingh510** [comment]
So right now the only support is for active storage? Do you know what the timeline is like for supporting other file uploading gems?

**Comment by adrianthedev** [comment]
We're working on bringing custom fields in Avo soon (1-2 weeks). You could use that to build support for other file uploading gems.

Let me know if I can help more. I'm also hangin out on the [Discord server](https://discord.gg/pkTF6y8) ✌️.

**Comment by adrianthedev** [comment]
I'm going to close this for now. Let me know how Acitve Storage and Avo work for you! 🤙

**Comment by mstanislav** [comment]
Just for anyone searching around (like I was) this did indeed work out with custom fields quite quickly. This seems to work well for me similar to what I had in my native show/edit prior to Avo. May still realize this has a re-factor somewhere but created a new record, shows the image in the view, and editing shows the image filename/caches data as expected for a validation-failure case. Hope this at least helps someone - and also gives a great idea of what's possible overall!

**Execute:** `bin/rails generate avo:field shrine_logo`

**Edit app/avo/fields/shrine_logo_field.rb**
```
class ShrineLogoField < Avo::Fields::BaseField
  attr_reader :logo

  include ImageUploader.Attachment(:logo)

  def initialize(name, **args, &block)
    super(name, **args, &block)

    @logo = args[:logo] || nil
  end
end
```

**Edit app/components/avo/fields/shrine_logo_field/edit_component.html.erb**
```
<%= field_wrapper **field_wrapper_args do %>
  <%= @form.hidden_field :logo, value: @form.object.cached_logo_data %>
  <%= @form.file_field @field.id,class: classes("w-full") %>
  <%= "#{@field.logo ? "Current: " +  @field.value.original_filename : ""}" %>
<% end %>
```

**Edit app/components/avo/fields/shrine_logo_field/show_component.html.erb**
```
<%= field_wrapper **field_wrapper_args do %>
  <%= image_tag @field.value.download_url %>
<% end %>
```

**Comment by adrianthedev** [comment]
Thanks for this @mstanislav 🙌

**Comment by WvanLelyveld** [comment]
Super cool!
I noticed I needed to make one change to make this work... Add the module to the new class:

```
class Avo::Fields::ShrineLogoField < Avo::Fields::BaseField
  attr_reader :logo
...
```

instead of 


```
class ShrineLogoField < Avo::Fields::BaseField
  attr_reader :logo
...
```

But wouldnt have been able to make it work without this, thanks!

**Comment by Paul-Bob** [comment]
Yes, @WvanLelyveld, in Avo `3.x`, you should use `class Avo::Fields::ShrineLogoField`, whereas `class ShrineLogoField` is intended for Avo `2.x` only.

Thanks for sharing this!
