### ISSUE TITLE
Policy not taken in account for 'Advanced' licence

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1892]
### Describe the bug
With a valid 'advanced' licence, config.license = 'advanced' doesn't take in account anymore the policies, while config.license = 'pro' does.

### System configuration
**Avo version**:
    avo (3.0.1.beta2)
    avo-advanced (0.1.62)

**Rails version**:
7.0.7

**Ruby version**:
3.2.2

**License type**:
 - [ ] Community
 - [ ] Pro
 - [x] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @jetienne, you're not the first one trying to use the `config.license = "advanced"` and having this issue. We had the same report here https://discord.com/channels/740892036978442260/1138497133113249892

We're considering to deprecate this configuration, but, for now, just keep the `config.license = "pro"`.

I'll make sure to include a prominent warning near this configuration in our documentation.

**Comment by Paul-Bob** [comment]
https://docs.avohq.io/3.0/licensing.html#add-the-license-key

Warning added, thank you for this report.
