### ISSUE TITLE
Tab not hidden, even if no content 

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1893]
### Describe the bug
Note: this was working properly with avo2.

A tab is still visible, even if it doesn't contain any content.

### Steps to Reproduce

```ruby
tab 'Balance' do
  panel do
    row do
      field :foo, as: :text, hide_on: :forms, visible: -> { false }
    end
  end
  field :deal_balances, as: :has_many, name: 'Balance'
end
```

Add some policy on deal_balances, so they are hidden.

The tab will still be visible:

![Screenshot 2023-08-10 at 07 44 43](https://github.com/avo-hq/avo/assets/201689/b4852b9e-d1d9-425f-8b63-af4f72d4e2ce)

### System configuration
**Avo version**:
avo (3.0.1.beta2)
avo-advanced (0.1.62)

**Rails version**:
7.0.7

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
We want to refactor the way tabs are being rendered. We took a bet on turbo frames and I think it's not the right pattern for them. The mechanism is too complex.

We'll address this issue.
