### ISSUE TITLE
Make `view` smarter

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1901]
### Feature

Let's make the `view` variable smarter, similar to how `Rails.environment.(development|production)?` works.

Show and index respond only to equality and `?` and edit and new respond to `form?` too.

```ruby
# when on index
view == :index # true
view.index? # true
view.form? # false

# when on edit
view == :edit # true
view.edit? # true
view.form? # true
```

Also let's introduce `display?` that is the opposite of forms (only index and show).
The `:display` should work as `hide_on: :display`, `only_on: display`, and `except_on: :display`.

**Comment by Paul-Bob** [comment]
We can't keep `view == :index` with `StringInquirer` and I think there isn't some "SymInquirer". View become a string.

`view.show? == (view == "show")`

**Comment by Paul-Bob** [comment]
We kept `view == :index` by overriding the `==` operator.
