### ISSUE TITLE
Emails overflow outside sidebar

### ISSUE THREAD

**Issue by acetinick** [avo-hq/avo#1905]
### Describe the bug
Raised by our QA teams, solution is to truncate emails that dont fit

### Steps to Reproduce

![image](https://github.com/avo-hq/avo/assets/571649/9dfd1ab5-1dec-464b-a107-222cf71bbac7)

**Comment by adrianthedev** [comment]
You can add `def name` method to the model of the user (if you're using devise, do it on `User`). Whatever you return from that method will be displayed in that spot.

Can you use that until we have a proper fix? 🙌

**Comment by acetinick** [comment]
yea not critical for now,  we can wait for CSS fix) just very minor bug

**Comment by adrianthedev** [comment]
TailwindCSS has a cool little [helper class](https://tailwindcss.com/docs/text-overflow#truncate) for this.
