### ISSUE TITLE
Tags field is not styled correctly

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1906]
### Describe the bug

I think somewhere in our Tailwind purging process we're not keeping some styles that we need.

<img width="878" alt="CleanShot 2023-08-12 at 23 25 59@2x" src="https://github.com/avo-hq/avo/assets/1334409/becc0b20-fec6-4416-93c8-ea0c157c65f9">

### Steps to Reproduce
1. Check any `tags` field

**Comment by Paul-Bob** [comment]
@adrianthedev  I noticed that in this line https://github.com/avo-hq/avo-3/blob/main/app/helpers/avo/application_helper.rb#L74C9-L74C9 `py-2 px-3` is what is causing this issue.

**Comment by Paul-Bob** [comment]
Actually the problem was that `avo-pro.css` stylesheet was not getting registred on avo's `asset_manager`
