### ISSUE TITLE
New badge state for secondary (grey) useful for "drafting"

### ISSUE THREAD

**Issue by acetinick** [avo-hq/avo#1909]
### Feature
Currently we have good colors for badges, but useful would be to have a grey color for states like "drafting"

eg.
![image](https://github.com/avo-hq/avo/assets/571649/5f5c631d-2c4a-42fb-98e4-90a8dece68f4)

**Comment by adrianthedev** [comment]
Agreed! It's on the roadmap!

**Comment by adrianthedev** [comment]
I added te Help wanted and good first issue labels for others to pick it up.

**Comment by adrianthedev** [comment]
Reopening to keep track for Avo 3.

**Comment by adrianthedev** [comment]
Fixed in Avo 3 by https://github.com/avo-hq/avo-3/pull/369/files

**Comment by adrianthedev** [comment]
Fixed in Avo 3 by https://github.com/avo-hq/avo-3/pull/369/
