### ISSUE TITLE
Unable to add custom country to countries list 

### ISSUE THREAD

**Issue by BoberMod** [avo-hq/avo#1911]
### Describe the bug
It is not possible to add a new country to the "country" field using `countries` gem ([github](https://github.com/countries/countries/)) which is used by Avo for this field type

### Steps to Reproduce
1. Create new initializer:
```
Rails.application.config.after_initialize do
  ISO3166::Data.register(
    alpha2: 'LOL',
    iso_short_name: 'Happy Country',
    translations: {
      'en' => 'Happy Country',
      'de' => 'glückliches Land'
    }
  )
end
```
2. Enable these options in the current environment:
```
config.cache_classes = true
config.eager_load = true
```
3. Create new resource with `:country` type field:
```
field :country_code, as: :country
```
4. Visit resource page form with country field
5. Open country select field

### Expected behavior & Actual behavior
Actual behavior: "Happy Country" country is not present in the list of countries
Expected behavior: the newly added country is present in the countries list

### System configuration
**Avo version**: 2.35.0 (also reproduces with 2.39.0)

**Rails version**: 7.0.7

**Ruby version**: 3.1.3

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
N/A

### Additional context
- `countries` gem supports adding custom data and an example is taken from [gem docs](https://github.com/countries/countries/#loading-custom-data)
- It works as expected when `cache_classes = false`, but it's enabled by default on the production environment
- It works as expected when `ISO3166::Country.translations` called from Rails console or outside Avo app
- It doesn't matter which [Rails initialization event](https://guides.rubyonrails.org/configuring.html#initialization-events) is used

### Workaround
Move code from initializer into `config/application.rb` (and there's no need to use init events). I18n translation won't work in this case.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @BoberMod.
Can you please make a test repo with instructions so we can quickly test and apply patches to?

Thank you.
