### ISSUE TITLE
config.buttons_on_form_footers = true KO

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#1921]
### Describe the bug
`config.buttons_on_form_footers = true`doesn't display at the bottom.

### Steps to Reproduce
1. apply this configuration to avo

### System configuration
**Avo version**:
v3.beta7

**Rails version**:
7.0

**Ruby version**:
3.2

**License type**:
 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2023-08-23 at 11 32 18](https://github.com/avo-hq/avo/assets/201689/9f85c425-cc32-4b9f-9101-471207775e2b)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
It's actually an edge-case that you're nesting all fields under tabs.

The way we render the fields that don't belong in tabs is in a "main panel". That main panel has the form buttons on top and bottom.
Yours is empty so they are rendered one under the other.

I created this ticket to track and fix.
https://github.com/avo-hq/avo/issues/1925

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/1925

Please subscribe to that for notifications.

**Comment by jetienne** [comment]
@adrianthedev Thanks :)
