### ISSUE TITLE
Create separate page for the eject command

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#1924]
The Eject command deserves it's own page with more detailed examples.

**Comment by Paul-Bob** [comment]
Where do you consider that more detailed examples are needed? I read the docs and I think they are clear enough but I'm rigged since I implemented some of the ejection features and wrote the docs on them.

**Comment by adrianthedev** [comment]
Let's start with moving all the content from the `customization` page to it's own page.
Please leave a link behind that it has moved.
We should do this only for Avo 3 docs.

**Comment by adrianthedev** [comment]
Oh. I only now saw the linked pull request. Sorry.

**Comment by Paul-Bob** [comment]
@adrianthedev just merged the PR. I have one question:

> Let's start with moving all the content from the `customization` page to it's own page.

Here you're referring to eject docs right? Ore each from `customization` page to its own page?
