### ISSUE TITLE
Incorrect label for belongs_to selects

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#1929]
### Describe the bug

When editing or creating new records with `belongs_to` fields label's `for` value doesn't match the input's `id` value.

In Chome inspector Issues tab the following messages appear:

> The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
> To fix this issue, make sure the label's for attribute references the correct id of a form field.

![Screenshot 2023-08-31 at 4 44 11 AM](https://github.com/avo-hq/avo/assets/110569/da54f3ec-a26e-41d7-a82d-9f9304002094)

### Steps to Reproduce

1. Create 2 models, with `has_many` / `belongs_to` relationship
2. Create avo resource with `belongs_to` field
3. Go to new or edit view of the object which uses `belongs_to`
4. Try clicking a label for `belongs_to` field
5. Correct select input won't be focused

### Expected behavior & Actual behavior

This config generates the following HTML:

```html
…
<label for="result_event">Event</label>
…
<select … name="result[event_id]" id="result_event_id"><option value="">Choose an option</option>
<option value="…">Event 1</option>
…
```

You can see label's `for` is `result_event` but input's `id` is `result_event_id`.

Expected to see the same id in label's `for` and in input's `id`.

### Models and resource files

```ruby
class Event < ApplicationRecord
  has_many :results, dependent: :destroy
end
```

```ruby
class Result < ApplicationRecord
  belongs_to :event, touch: true
end
```

```ruby
class ResultResource < Avo::BaseResource
…
  field :event, as: :belongs_to
…
end
```

### System configuration
**Avo version**: 2.40.0
**Rails version**: 7.0.7.2
**Ruby version**: 3.2.2

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

N/A

### Additional context

N/A

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @xeron good catch! My browser do not complains about it, I'm using Firefox. Also tried with Chrome, didn't complained at all.

> Correct select input won't be focused

What do you mean? It works as expected on my end.

Anyway good catch again, the label's `for` should have the same value as the input's `id`

**Comment by xeron** [comment]
> Also tried with Chrome, didn't complained at all.

Sorry, not in the console, issues tab:

![Screenshot 2023-08-31 at 4 44 11 AM](https://github.com/avo-hq/avo/assets/110569/7d233b99-d715-48bb-9c74-09fd63916aa6)

I'll make it more clear in the bug report.

> What do you mean? It works as expected on my end.

For `belongs_to` fields select dropdown is not focused when you click on related label because of the id mismatch.

**Comment by xeron** [comment]
It's been a while since I reported this. Could someone take a look? I checked the code but I don't really understand where this part comes from.

**Comment by xeron** [comment]
Well I know select id comes from here, but if I change it to `@field.id` it fixed the label matching but breaks the form:

https://github.com/avo-hq/avo/blob/1e08e09c1feb13f60e6d0651d084f8568161b691/app/components/avo/fields/belongs_to_field/edit_component.html.erb#L100
