### ISSUE TITLE
Assign Stimulus controllers to actions 

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#1938]
### Feature

Similar to how we [assign stimulus controllers to resources](https://docs.avohq.io/2.0/stimulus-integration.html#assign-stimulus-controllers-to-resource-views) we should be able to assign stimulus controllers to actions.

Another possibility is to reuse the controller assigned to the resource and be able to use it on all the actions used by that resource.

**Comment by Paul-Bob** [comment]
From [here](https://discord.com/channels/740892036978442260/1147268129421004871)

**Comment by bryszard** [comment]
I'll make my attempt to solve this one.

**Comment by Paul-Bob** [comment]
Thank you @bryszard let us know if you need any help!
