### ISSUE TITLE
Alerts auto-dismiss too quickly and don't render long strings

### ISSUE THREAD

**Issue by gee-forr** [avo-hq/avo#1939]
### Context

I am using an action that needs to give some data back to a user that they must use in a different system, and I'm using the `success "a message"` method in the action.

The problem is 2-fold:

1. The alert dismisses after 5 seconds, which is not long enough for a user to grab the information from the alert before it disappears.
2. The alert does not correctly render really long strings (see the screenshot below)

It could be that there's another way to provide longer lived feedback to a user, but I can't seem to find anything in the docs. It also looks like the auto-dismiss value is hardcoded in the `AlertComponent` template.

It feels like I should be doing something different, as giving users an alert to interact with doesn't seem right. It would be great if there was a banner option I could use instead that showed a permanent and prominent message until manually dismissed.

### System configuration
**Avo version**: 2.40.0
**Rails version**: 6.0.6.1
**Ruby version**: 2.7.8
**License type**: Pro
**Are you using Avo monkey patches, overriding views or view components?**: No

### Screenshots or screen recordings

![CleanShot 2023-09-05 at 15 01 15](https://github.com/avo-hq/avo/assets/345730/9986ecb4-c85a-4562-a4b5-10112f4f004f)

**Comment by Paul-Bob** [comment]
Hi @gee-forr thank you for reportingn this. I think we can solve this issue by making the the auto-dismiss time configurable and ensure that the alerts expose all text properly.

**Comment by gee-forr** [comment]
Fantastic news! Thank you.

Let me know if there's anything I can do to help.

**Comment by gee-forr** [comment]
@Paul-Bob - in the meantime - is it possible to override the alert component myself? I see that it's possible, but I'm not 100% sure how to do so? Do I simply copy the component.rb and its component.html.erb template to my app and modify it?

**Comment by gee-forr** [comment]
Thank you and acknowledged on the maintenance point.

Unfortunately, this particular app won't be able to support modifications to its asset pipeline due to some legacy decisions, so I'll have to wait until the fix for this issue makes its way into avo itself.

Looking forward to bumping that version :)

**Comment by adrianthedev** [comment]
If you already overriden the `alert_component.html` file you can add ` style="word-break: break-all;"` and have that link broken into multiple rows.

<img width="821" alt="CleanShot 2023-09-09 at 09 41 41@2x" src="https://github.com/avo-hq/avo/assets/1334409/a86495ef-3bbc-4ce4-abc9-ced8844c37d7">

<img width="928" alt="CleanShot 2023-09-09 at 09 41 48@2x" src="https://github.com/avo-hq/avo/assets/1334409/6aa0fccd-15d0-46c6-9658-6cbec02c3ab9">

Closing for now.
Please feel free to reopen if this doesn't fix it.

**Comment by yanovitchsky** [comment]
Hello. Is there any update without overriding the alert component ?
