### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by santib** [avo-hq/avo#1943]
At our company we are evaluating replacing ActiveAdmin with AvoHQ Community for our [Rails API Base app](https://github.com/rootstrap/rails_api_base). We specifically want to use free tools by default and upgrade only when necessary.

The question is if the license allows a commercial closed-source app to use AvoHQ Community version and manually extend it for example with Pundit (similar to the [Pro version](https://docs.avohq.io/2.0/authorization.html#make-sure-avo-knows-who-your-current-user-is)).

Thanks 🙌

**Comment by adrianthedev** [comment]
As a general rule of thumb, you can use the Community version and extend it as you want.
I don't see how you could extend it to use Pundit without using our own authorization feature hooks.

Even if you do that, the time it would take is definitely worth more than the cost of a Pro license, and in the end you might end up with a sub-par authorization feature.
Think about that more.

Purchasing a Pro license helps the project grow and gives you more features out of the box.

**Comment by santib** [comment]
>I don't see how you could extend it to use Pundit without using our own authorization feature hooks.

I didn't do the investigation. So do you mean that it isn't easy/possible to extend AvoHQ Community? I thought it was like Sidekiq that even if the Pro/Ent plans have great features, the community could build plugins around the Community version.

>Even if you do that, the time it would take is definitely worth more than the cost of a Pro license, and in the end you might end up with a sub-par authorization feature.
Think about that more.
>
>Purchasing a Pro license helps the project grow and gives you more features out of the box.

I understand your point, but as an Open Source base repository (which is used by people outside our org), we aren't going to add any paid tool by default. That doesn't mean that we can consider upgrading the admin site for clients if they are willing to pay for paid features.

**Comment by adrianthedev** [comment]
It's not like Sidekiq.
Some features are built-in to Avo, and some can be added as extensions. Authorization is something pretty built-in and would be difficult to build another authorization feature around it.

I understand your concern with the open-source repository. Unfortunately, we don't have the resources to refactor that feature out. We understand that that might leave some use cases unusable and I'm sorry for that.

But there's another thing I'd like to raise awareness to. Even open-source repositories and tools have to be hosted somewhere, they need databases, storage services, and more. Those cost money.
I know that this is a gem that you use in your app, not the service that hosts your app, but the same principle applies. 
We work to earn money to bring that value to the table.

**Comment by santib** [comment]
Hey I get your point, I also do Open Source work and understand how hard it is to get financial support. Thanks for your response :v:
