### ISSUE TITLE
Weird behavior when creating a model from a has_many field

### ISSUE THREAD

**Issue by iBlackShadow** [avo-hq/avo#1944]
### Context

I have a model which `belongs_to` another model
```ruby
create_table :notes do |t|
  t.text :note, null: false
  t.belongs_to :provider, null: false, foreign_key: true
end
```
```ruby
class Note < ApplicationRecord
  belongs_to :provider

  validates :note, presence: true
end
```

then on the parent resource i have a `has_many` field
```ruby
field(:notes, as: :has_many)
```

When i try to create a new note the UI says the creation failed but the note is created successfully

I am not sure if i missed something and this is expected but i took a quick look at the source code and believe that the issue is [Here](https://github.com/avo-hq/avo/blob/8f780eca21e0e80595925aece6f76f703ec78a22/app/controllers/avo/base_controller.rb#L129C9-L129C9), the controller tries to save the model before setting `provider_id` which fails (This would be the error reported on the UI) but then [later on](https://github.com/avo-hq/avo/blob/8f780eca21e0e80595925aece6f76f703ec78a22/app/controllers/avo/base_controller.rb#L144) the model is saved again after setting `provider_id` and succeds.

as a work around i am overriding the `save_model_action` method on the `NotesController`
```ruby
class Avo::NotesController < Avo::ResourcesController
  def save_model_action
    true
  end
end
```

with that creating notes works as expected

### System configuration
**Avo version**: 2.36.2

**Rails version**: 7.0.7.2

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/avo-hq/avo/assets/6798292/4e760788-373e-41cb-ae6c-c3dd0c89e4d0

**Comment by adrianthedev** [comment]
hey @iBlackShadow. I think we forgot about this one somehow.
Apologies.

I'm wondering why the styles are a bit different on your end. I don't see the white panel background.

Also, did you experience this issue anywhere else? Were you able to fix it?

**Comment by iBlackShadow** [comment]
i think the styles just look weird on the video, for some reason the brightness is way too high on it.

this is how it really look like
![avo](https://github.com/avo-hq/avo/assets/6798292/f6ee07c0-1ea3-4e4b-b912-d3602bcee612)

as for fixing it, i had to override `save_model_action` like i mentioned on the issue but atleast i figured a better way than just returning true
```ruby
  def save_model_action
    provider = Provider.find(params[:via_resource_id])

    @model.provider = provider
    @model.save!
  end
```

**Comment by adrianthedev** [comment]
yeah. it's something weird inside that is failing.
We haven't seen anything like this before
Let's monitor it and see if it's consistent anywhere else.

**Comment by Paul-Bob** [comment]
@adrianthedev looking at the `def create` code in `Avo::BaseController` we should run `saved = save_model` after all that reflections logic. Otherwise it's saving the model before assigning the parent then saving again after assigning the parent. Double save is unnecessary and don't raise any error if you don't have parent validations on first one but if you have a parent validation then first save raise the error and the second save works leading to this weird behavior. I think we should reopen this issue and move the `saved = save_model`  just below all the reflections logic and remove the double saving.

**Comment by adrianthedev** [comment]
Ok @Paul-Bob.
Let's reopen (or create a new one) and fix it, please.

**Comment by Paul-Bob** [comment]
@iBlackShadow I guess you didn't have the `provider` field in your notes resource right? You need that field on the notes resources even if as hidden so it can be filled on creation.
