### ISSUE TITLE
save_model_action not called/documented in Avo 3

### ISSUE THREAD

**Issue by therabidbanana** [avo-hq/avo#1945]
### Describe the bug

I had an Avo 2 prototype that I've upgraded to Avo 3 (beta8). save_model_action is no longer being called in the controller and is not documented in the Avo 2 to 3 guide so I wonder if maybe this is a bug/oversight? 

I suspect it's related to wanting to think more holistically about adapters, which would be exactly what I need to replace this hook: https://github.com/avo-hq/avo/issues/1418

### Steps to Reproduce

1. Add `def save_model_action; raise 'uhoh; end` to an Avo resource controller
2. Create/edit a new resource and click save

### Expected behavior & Actual behavior

Expected - an exception is raised **or** Avo 2 to 3 guide calls out this is no longer supported
Actual - no exception is raised and the model is created/updated. Change in API is not documented.

### System configuration
**Avo version**:
Avo 3.0.1.beta8

**Rails version**:
6.1.7.6

**Ruby version**:
3.1.3

**License type**:

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

I've been able to work around by writing custom create/update actions but doing this is undocumented so I've had to have a bit of trial and error with what parts I need from the base controller to support.

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Can you try `save_record_action` instead?

One of the changes we made with Avo 3 is to rename `model` to `record`. Whenever we think of the model we don't know whether we're talking about the class or an actual instantiated record.
The `record` is more straighforward.

**Comment by therabidbanana** [comment]
Ah ha! That does work!
