### ISSUE TITLE
The fix for #1865 has broken default procs on custom actions

### ISSUE THREAD

**Issue by dark-panda** [avo-hq/avo#1946]
The commit at 5db08d462978ff77f4f4d0cfca0b5689923a3374 breaks the following use case:

```ruby
class CustomAction < Avo::BaseAction
  self.name = 'Custom Action'
  self.message = 'Some kind of custom action'

  field :option_a, as: :boolean, default: -> { @record.can?(:option_a) }
  field :option_b, as: :boolean, default: -> { @record.can?(:option_b) }
  field :option_c, as: :boolean, default: -> { @record.can?(:option_c) }
end
```

In this case, I've noticed that since the commit at 5db08d462978ff77f4f4d0cfca0b5689923a3374, the default value procs for `:option_b` and `:option_c` no longer have `@record` populated and the value is simply `nil`. This was working in the commit immediately before 5db08d462978ff77f4f4d0cfca0b5689923a3374. 

### System configuration
**Avo version**:  v2.37.1 and above

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@dark-panda can you try simply `record` instead of `@record`?

**Comment by dark-panda** [comment]
@adrianthedev same thing: `record` is set correctly for the first but subsequent fields are `nil`.

**Comment by adrianthedev** [comment]
@Paul-Bob can you please have a look into this?

**Comment by Paul-Bob** [comment]
Notice that the `@record` is present only if action runs from `show` or `edit` views. You should replace the block with `@record&.can?(...)` to prevent it to break if @record is not present.

**Comment by dark-panda** [comment]
The problem here still exists, and it is not as @Paul-Bob describes. In the case of the action I'm showing, we are on the `show` view, and record simply doesn't show up on fields past the first one. For instance, in the example code:

```ruby
field :option_a, as: :boolean, default: -> { @record.can?(:option_a) }
field :option_b, as: :boolean, default: -> { @record.can?(:option_b) }
field :option_c, as: :boolean, default: -> { @record.can?(:option_c) }
```

When the modal is opened, `field :option_a`'s default block works fine and `@record` is populated, but the fields for `:option_b` and `:option_c` simply are not populated at all. This is all on the `show` view, it's just that the only field that even sees `@record` is the first one -- same request, same `show` page view, it just simply isn't populated on anything other than the first field.

Reverting the commit 5db08d462978ff77f4f4d0cfca0b5689923a3374 resolves the issue in `main` as it stands.

**Comment by Paul-Bob** [comment]
[reproduction_try.webm](https://github.com/avo-hq/avo/assets/69730720/5ecb2005-30a0-43fc-9811-e39bd411104f)

@dark-panda I tried to reproduce it on `v2.43.0` and it seems to be working fine, are you able to share a reproduction repository so we can reproduce it?

**Comment by dark-panda** [comment]
@Paul-Bob in a minimal test case, it's still happening for me, and I think I see why based on your code and mine. 

In the code shown in the video, you're using `#blank?` and `#present?`, which are defined on `Object` in Rails so those methods are available on every object, and that might be hiding the issue -- if `@record` is `nil` in your case, using `#present?` and `#blank?` won't raise a `NoMethodError` on a `nil` object like I was seeing. Try putting a method into the model and try calling that to see what happens. If `@record` is ever `nil`, it should raise a `NoMethodError`.

Working this out a bit further, if we take your code and add some debugging output and the safe navigation operator on a method I've added to the `User` model....

```ruby
class RevealFish < Avo::BaseAction
  field :option_a, as: :boolean, default: -> {
    puts ">>> option_a #{@record.present?}"
    @record&.foo?
  }

  field :option_b, as: :boolean, default: -> {
    puts ">>> option_b #{@record.present?}"
    @record&.foo?
  }

  field :option_c, as: :boolean, default: -> {
    puts ">>> option_c #{@record.present?}"
    @record&.foo?
  }

  def handle(...)
    succeed ":)"
  end
end
```

Here's what the current `main` branch does in my test repo when I open up that action:

```
>>> option_a true
>>> option_a false
>>> option_b true
>>> option_b false
>>> option_c true
>>> option_c false
>>> option_a true
>>> option_a true
>>> option_b true
>>> option_b true
>>> option_c true
>>> option_c true
```

If I revert the commit in 5db08d462978ff77f4f4d0cfca0b5689923a3374:

```
>>> option_a true
>>> option_b true
>>> option_c true
>>> option_a true
>>> option_a true
>>> option_b true
>>> option_b true
>>> option_c true
>>> option_c true
```

So those `default` procs are actually being called a bunch of times on each load of the action: 

* when 5db08d462978ff77f4f4d0cfca0b5689923a3374 is applied, the procs are called 4 times each for each field and in some cases `@record` is `nil`. 
* when the commit is reverted, each proc is called 3 times, and they're always present. 

In the case of the revert, that's working for me, because I wasn't checking for the existence of `@record`, but it was always present in that case. Without reverting, `@record` is only sometimes `nil`, and that lead to my `NoMethodError`. In the case of your code, you're getting the results you'd expect because presumably only the last calls to the procs take precedence, and because you were using `#present?` and `#blank?` you weren't hitting a `NoMethodError` like I was.

Can you try using something other than `#blank?` and `#present?` that would do the whole `NoMethodError` thing and see if that happens for you?

**Comment by Paul-Bob** [comment]
I was able to reproduce it, will investigate the issue, thanks for pointing that out
