### ISSUE TITLE
Field :tag throws undefined method error upon submitting form

### ISSUE THREAD

**Issue by stephonfraser** [avo-hq/avo#1958]
### Context

I'm working on creating a blog and I'd like to utilize the tag field. I copied the tag example from the avo documentation to my project and changed the suggestions method. It did not throw an error and the suggestions worked fine. However, when I clicked submit I received error:  undefined method `tag=' for #<Blog id: nil, name: nil, author_id: 1, created_at: nil, updated_at: nil>

Please see attached screenshot for resource, model and the error I encountered. Can you please assist?

### System configuration
**Avo version**: 2.41.0

**Rails version**: 7.0.8

**Ruby version**: 3.2.1

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="563" alt="image" src="https://github.com/avo-hq/avo/assets/43830615/ddc0942b-38a5-4ab9-928b-791f173282c4">
<img width="351" alt="image" src="https://github.com/avo-hq/avo/assets/43830615/a665df40-cc99-49c4-81b9-c0870e66233d">

![image](https://github.com/avo-hq/avo/assets/43830615/df48d738-f1e8-4e3e-a80a-c0a4ac99cc20)

**Comment by Paul-Bob** [comment]
Hello @stephonfraser, do your `Blog` model have an DB attribute called `tag`? For example, on our courses we use [PostgreSQL array fields](https://docs.avohq.io/2.0/fields/tags.html#postgresql-array-fields) where the courses table schema have `t.text "skills", default: [], array: true` this way `ActiveRecord` will generate an reader and writer for `skills` and Avo can read and write to it.

If you don't want to have an DB attribute for this use case consider creating the reader and writer manually on your `Blog` model, check [Array Fields](https://docs.avohq.io/2.0/fields/tags.html#array-fields).

**Comment by adrianthedev** [comment]
Hey @stephonfraser. What was the fix?

**Comment by stephonfraser** [comment]
@adrianthedev My project wasn't connected to a database. I connected it to a PostgreSQL database and created the DB attribute.

**Comment by adrianthedev** [comment]
Gotcha! Thanks for clearing it up!
