### ISSUE TITLE
Avo trying to preload ActiveStorage attachments, even when not needed.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1965]
### Describe the bug

I have this code in a resource:

```ruby
    panel("Identity", hide_on: %i[index]) do
      field(:profile_photo, as: :file, accept: "image/*", hide_on: %i[index])
    end
```

And, when viewing the Index view of the resource, Avo is attempting to eager-load `profile_photo_attachment`

### Steps to Reproduce
1. Create a model with an ActiveStorage attachment type
2. Create a resource for the model, with a `fields` method containing the above.
3. View the index page for the resource
4. Observe query in log as below:

```
15:52:57 web.1          |   ActiveStorage::Attachment Load (0.6ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_type" = $1 AND "active_storage_attachments"."name" = $2 AND "active_storage_attachments"."record_id" IN ($3, $4, $5)  [["record_type", "User"], ["name", "profile_photo"], ["record_id", 22], ["record_id", 16], ["record_id", 1]]
```

### Expected behavior & Actual behavior

Eager-loading should either only happen when actually needed, or when explicitly requested via `self.includes`.

### System configuration
**Avo version**: 3.0.1.beta19

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

Same as in #1949

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Same as https://github.com/avo-hq/avo/issues/1968.

It was a mistake to do that. Will revert it in Avo 3.

**Comment by MrJoy** [comment]
@Paul-Bob What release is this fix going out in?

**Comment by Paul-Bob** [comment]
Next one, `3.0.1.beta25` will already have this one included
