### ISSUE TITLE
bug: `has_one` fields don't render unless target resource `self.title` is present

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1966]
### Describe the bug

When I have such a relationship, the field never renders.

I can get it to render if I declare the field `as: :belongs_to`, but that blows up as soon as I try to run an action.

### Steps to Reproduce

```ruby
class CalendarInstance < ApplicationRecord
  belongs_to :account,  inverse_of: :calendar_instances

  has_one :user, through: :account
end
```

```ruby
class Avo::Resources::CalendarInstance < Avo::BaseResource
  def actions
    action(Avo::Actions::Whatever)
  end

  def fields
    # This will render on index/show, but when trying to run an action, it will fail because it
    # can't find a `user_id` field on the model.
    field(:user, as: :belongs_to, sortable: true, required: true, hide_on: %i[edit])
    # This will not render at all:
    field(:user, as: :has_one, sortable: true, required: true, hide_on: %i[edit])
  end
end
```

In Avo 2, I could declare the field as `belongs_to` and everything Just Worked for my use-cases.

### Expected behavior & Actual behavior

I need to be able to have fields representing a `has_one ..., through: ...` relationship, as this is a _very_ common thing in my codebase.

### System configuration
**Avo version**: 3.0.1.beta19

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

Nothing relevant, see #1949 for details.

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by MrJoy** [comment]
One extra detail:  `CalendarInstance` is the base class for an STI construction.  So, there's also this class in the mix:

```ruby
class GoogleCalendarInstance < CalendarInstance
end
```

**Comment by MrJoy** [comment]
And for completeness:

```ruby
class Account < ApplicationRecord
  belongs_to :user
end
```

**Comment by Paul-Bob** [comment]
Hello @MrJoy I confirmed that `has_one :model` where in the model is declared as `has_one :model, through: :another_model` works as expected. In your example since `CalendarInstance`  ` belongs_to :account,  inverse_of: :calendar_instances` I think you're missing `Account`  `has_many: :calendar_instances, inverse_of: :account`

**Comment by MrJoy** [comment]
I omitted the relevant part of the Account class by mistake.  It's:

```ruby
has_many :calendar_instances, dependent: :destroy
```

I'll see if I can make a simple repro case, but your example appears to be substantially different than our situation.  We're not using HABTM and we have a `belongs_to` in the chain of relationships.

**Comment by adrianthedev** [comment]
So just to be sure I understand the scenario. Did this work in Avo 2?

**Comment by MrJoy** [comment]
Yes, it did.

**Comment by MrJoy** [comment]
https://github.com/MrJoy/avo-debug

That is about as thoroughly stripped down as I could make it.  I could maybe have stripped out the User model as well but I think this should be sufficiently bare-bones to be easy for you to work with.

**Comment by MrJoy** [comment]
If, after setting things up and running `rake db:seed` you navigate to:

http://localhost:5000/admin/resources/calendar_instances/1

Click the actions list, then click the one action there, you'll find (via the network inspector because there appears to be some less-than-ideal error handling around an action failing before the confirmation modal shows) that the request is failing with:

```
undefined method `user_id' for #<GoogleCalendarInstance id: 1, account_id: 1, calendar_id: 1, type: "GoogleCalendarInstance">
```

**Comment by Paul-Bob** [comment]
@MrJoy let me know if adding `self.title = :name` to `Avo::Resources::User`and using the `field(:user, as: :has_one, sortable: true, required: true, hide_on: %i[edit])` works as expected

**Comment by MrJoy** [comment]
That does appear to work around the issue, thank you.  I'll implement that for now and await a fix.
