### ISSUE TITLE
Make more informed decisions when displaying the default dynamic filters options

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1972]
### Feature

For dynamic filters, eliminate meaningless options.

Specifically, "is present" and (for some types, e.g. boolean) "is blank" are meaningless in the context of a `NOT NULL` column type.

### Current workarounds

Not that I'm aware of.

**Comment by Paul-Bob** [comment]
A way to provide your custom list of predicates would be helpful in this scenarios

**Comment by adrianthedev** [comment]
Yes, that could be helpful. The easier thing to do would be to just have a `conditions` option there and specify the ones you want.

This is something that we would like to add in the near future.

**Comment by MrJoy** [comment]
Customization is good, but in a few cases better choices can be made automatically based on metadata about the field.

**Comment by bryszard** [comment]
Could you send a config for situation in which this occurs? I can't find an example in the dummy app or the docs that would fit what you're describing @MrJoy.

**Comment by adrianthedev** [comment]
Yes. I agree with [that](https://github.com/avo-hq/avo/issues/1972#issuecomment-1765298699).

**Comment by adrianthedev** [comment]
I think what he means @bryszard is that you could get is present or is blank options in a boolean field when the field is actually not nullable, so the options remaining are true or false.
But Avo 3 still displays the present and blank options to the user.

Is that correct @MrJoy?

See [this](https://avodemo.com/avo/resources/users) page with the "is active" filter.

**Comment by bryszard** [comment]
@adrianthedev I can see it in the docs for 3.0 and I can see it in the demo that you've linked. But when I work on the `main` branch for this repo, I can't see the `filterable` feature. 

How can I find it?

**Comment by MrJoy** [comment]
> Could you send a config for situation in which this occurs? I can't find an example in the dummy app or the docs that would fit what you're describing @MrJoy.

Create a model with a field of type `BOOLEAN NOT NULL`, and create a dynamic filter (`field(..., filterable: true)`) for it.  It will have options like "is blank" that aren't meaningful.  I haven't done any sort of exhaustive analysis of what situations that sort of thing arises in.

Dynamic filters are a paid feature of Avo 3, which is why you're not finding it in the code.
