### ISSUE TITLE
Dynamic filters button failing to show if the search is not enabled

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1973]
### Describe the bug

I've added dynamic filters to a bunch of our resources.  On many of those resources, the button does not show up on the index view.  Strangely, this is _only_ the case if I don't set `config.always_expanded = true`.  If I set that, then all places that should have dynamic filters visible do.

### Steps to Reproduce

1. Set up <https://github.com/MrJoy/avo-debug>
2. Disable `config.always_expanded = true`
3. `bin/dev`
4. Navigate to <http://localhost:5000/admin/resources/calendars>
5. Notice lack of filter button
6. Stop Rails
7. Re-enable `config.always_expanded = true`
8. `bin/dev`
9. Navigate to <http://localhost:5000/admin/resources/calendars>
10. Notice that filters are present and functional.

### Expected behavior & Actual behavior

When Advanced license is enabled, and a resource has `filterable: true` on one or more fields, and `config.always_expand` is not set to `true` then I should see the Filter button on the resource.

### Models and resource files

<https://github.com/MrJoy/avo-debug>

### System configuration
**Avo version**: 3.0.1.beta20

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
This is a display bug where some partials are visible/hidden based on the features that resource has enabled.

Somehow, there's this edge-case where if the search is not enabled that partial of dynamic filters is hidden.
We need to fix it.

Quick solution for this: enable search for that resource.

**Comment by Paul-Bob** [comment]
Thank you for the detailed report and for the reproduction repository @MrJoy that was very useful to identify the issue!

The fix will be included on the today release (not released yet), please reopen the issue if the bug persists after update.

**Comment by MrJoy** [comment]
@Paul-Bob So, I just tested this by removing my workaround.  On an association view, in a tab, I see the button -- on the right, instead of the left -- and clicking it does nothing.

Things seem to be fixed on the index view.
