### ISSUE TITLE
Global defaults for resource / field options.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1977]
### Feature

I'd like to be able to set global defaults that can be overridden at the resource/field level for a number of resource options, and at least one field option.

Specifically, for resources:

* `index_controls`
* `row_controls`
* `show_controls`
* `edit_controls`
* `record_selector`
* `visible_on_sidebar`

And, for fields:

* `discreet_pagination`

**Comment by dhnaranjo** [comment]
I believe you could:

```
class ApplicationResource < Avo::BaseResource
  self.visible_on_sidebar = false
end

class YourModelResource < ApplicationResource
   ,,,
end
```

**Comment by adrianthedev** [comment]
That is something you can do, but you have to come up with your own abstractions.

Resource files are Ruby classes. Using the example above, you can develop abstractions that can make those options a reality.

**Comment by MrJoy** [comment]
That works for most things, but the discreet pagination one would require making an abstraction on top of `field` which seems like an unwise thing to do.

**Comment by adrianthedev** [comment]
I think you could monkey patch it somehow in `HasBaseField`.

I'll close this for now.
