### ISSUE TITLE
Tool generator generates unsecured route.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1979]
### Describe the bug

When using `rails generate avo:tool`, the update to routes.rb produces a route that is not protected by Devise.

Specifically, it produces:

```ruby
  scope :admin do
    get "my_tool", to: "avo/tools#my_tool"
  end
```

This should be within an `authenticate` block.

### Steps to Reproduce
1. `rails generate avo:tool my_tool`

### System configuration
**Avo version**: 3.0.1.beta20

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Because custom tools are very much regular Rails code, we presumed that users will move that route into their routing scheme anyway.

But you have a good point.
I added the "Help wanted" label. Hopefully, someone can contribute this feature.

**Comment by enderahmetyurt** [comment]
I can look after it @adrianthedev if it's still available.

**Comment by Paul-Bob** [comment]
Thank you @enderahmetyurt!

**Comment by Paul-Bob** [comment]
Could we pause this for now? I'm uncertain whether we should move forward with it.

1. Why enforce the route to be tied to a specific gem (devise) when Avo doesn't actually require it?
2. Why generate the route inside a block if we're unsure whether the user wants it? They might want an info page that's accessible to everyone

In my opinion, we should keep the route generation stupid simple. The goal is to provide a starting point that you can customize as needed, rather than delivering a fully finalized solution.

**Comment by MrJoy** [comment]
That's a perfectly reasonable approach.  It's easy for the user to change things either way, and I tend to prefer to defaulting to a more secure posture but...  Not everyone is going to be using Devise and handling the myriad ways it could be configured would certainly be a challenge.

Perhaps just adding a comment in the generated code saying "be sure to secure this route if you don't want it publicly accessible" is a happy medium?

**Comment by enderahmetyurt** [comment]
so, May I continue it :) @Paul-Bob

**Comment by Paul-Bob** [comment]
Yes @enderahmetyurt thank you! We appreciate it! It's not as challenging as the previous approach.
