### ISSUE TITLE
Search non-functional.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1990]
### Describe the bug

My search configuration is being totally ignored.

### Steps to Reproduce
1. Add this configuration to a model:
  ```ruby
  self.search = {
    query: lambda do
             query
               .ransack(id_eq:      params[:q],
                        email_cont: params[:q],
                        name_cont:  params[:q],
                        m:          "or")
               .result(distinct: false)
               .unscope(:limit)
           end,
  }
  ```
2. Add the corresponding allowances in the model:
  ```ruby
  def self.ransackable_attributes(_auth = nil) = %i[id email name]

  def self.ransackable_associations(_auth = nil) = %i[]
  ```
4. Go to the relevant resource index view.
5. Attempt to perform a search.
6. Note the query actually executed:
  ```text
  11:12:24 web.1          | {"q"=>"Something", "global"=>"false", "resource_name"=>"accounts"}
  11:12:24 web.1          |   Account Count (4.6ms)  SELECT COUNT("accounts"."id") FROM "accounts"
  11:12:24 web.1          |   Account Load (1.0ms)  SELECT "accounts".* FROM "accounts" LIMIT $1  [["LIMIT", 8]]
  ```

Notice that no fields are searched, and my attempt to remove the `LIMIT` clause is ignored.

Removing the `.unscope(:limit)` or replacing it with `.limit(12345)` does not change the behavior at all.

### Expected behavior & Actual behavior

Search should attempt to search for models, instead of just listing all of them.

### Models and resource files

I've updated my <https://github.com/MrJoy/avo-debug> repo to replicate the issue.  See the `User` resource / model.

### System configuration
**Avo version**: 3.0.1.beta22

**Ransack version**: 4.1.0

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (~~I found a workaround, but I'd love to have it fixed.~~ I can continue development, but this is impairing the ability of our support team to do their job in production.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by MrJoy** [comment]
Upon further testing, it seems this _also_ affects dynamic filters.  They just... don't filter anything.

**Comment by adrianthedev** [comment]
I can't manage to reproduce this. 
Can you try this? BEware that it's going to allow search on everything for that model.

```ruby
def self.ransackable_attributes
  super
end

def self.ransackable_associations
  super
end
```

**Comment by MrJoy** [comment]
Aha!  The problem is I'm returning an array of symbols, not an array of strings.
