### ISSUE TITLE
Allow overriding of max width for badges.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1991]
### Feature

Allow overriding of maximum width for badges.

### Current workarounds

Haven't found one.

### Screenshots or screen recordings

<img width="452" alt="image" src="https://github.com/avo-hq/avo/assets/113625/227bd0be-28c1-413f-974c-3bdc49794f80">

### Additional context

We're using badges for status fields for users, and we have status values like "suspended_by_user" and "suspended_by_cs".  The maximum width is cutting things off such that the only way to tell which value is in use is to hit "edit" / view source.

**Comment by adrianthedev** [comment]
You should be able to override it by ejecting the component and customizing it on your end.

`rails g avo:eject --component Avo::Fields::Common::BadgeViewerComponent`

Closing for now. feel free to reopen if this still persists.

**Comment by MrJoy** [comment]
@adrianthedev That works for now.  You might try `max-width: fit-content` though.  Some quick testing locally suggests it might be a better option than a fixed value.

**Comment by adrianthedev** [comment]
The thing we're trying to avoid is this happening.
We'd like for it to be the same width but not stretch too much...

![CleanShot 2023-11-01 at 11 21 58@2x](https://github.com/avo-hq/avo/assets/1334409/f895ed9b-c500-4d29-a55a-7e9b8caa7229)

**Comment by MrJoy** [comment]
Gotcha.  I prefer variable sizing because size/gross shape is among the first attributes the brain registers when processing an object (IIRC, color and size/gross shape are the first two, but I forget the exact order) so there might be a small UX benefit to having variety for a column (particularly if one has multiple values that are assigned the same color), but if your priority is aesthetics then the fixed maximum makes sense.

**Comment by adrianthedev** [comment]
That makes sense as well! we'll have that configurable using CSS.

I'd like to stop shipping styling configuration toggles in Ruby. This change should be done using CSS.

Pseudo-example:

```css
[data-component="badge"] {
  max-width: auto;
}
```
