### ISSUE TITLE
Can't log in to AvoHQ...

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#1997]
### Describe the bug

I'm getting a 500 error every time I try to log in to AvoHQ.

### Steps to Reproduce

https://github.com/avo-hq/avo/assets/113625/6002ddba-079c-4292-aa04-1ed2d060e8d1

### Models and resource files

N/A

### System configuration
**Avo version**: N/A

**Rails version**: N/A

**Ruby version**: N/A

**License type**:

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (Don't actually _need_ to log in at this time, but will need to eventually.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Fixed! Thanks for the report.
