### ISSUE TITLE
Don't load `options` for select when field is `disabled`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2002]
### Context

Don't load `options` for select when field is `disabled` or when it comes from an association that don't allow to be edited, example, `belongs_to`

From [here](https://discord.com/channels/740892036978442260/1167733059999776779)

**Comment by adrianthedev** [comment]
Are we sure we want to do this? I mean, I get the perf improvement, but is anyone doing this outside of Avo?

**Comment by Paul-Bob** [comment]
I think we should do it for 2 main reasons, performance and also security. When field is disabled we should not expose the options.

**Comment by Paul-Bob** [comment]
> Based on that idea we should not comoute or show the value of disabled text fields too. 
> I wouldn't do this. If the performance of this is such a big impact, I think the user should prevent computing it by themselves. 

I'm not saying we should not render the value but the unnecessary hidden select options that are not even visible and totally unnecessary since the select field is disabled.

I get your point, I'm not sure if is possible to compute the select options on a `belongs_to` field , we can skip this implementation, should not impact much, only on very large tables and we have the `searchable` option that avoids the select to load all possible records
