### ISSUE TITLE
ImportMaps pulling avo.custom.js from spec/dummy instead of app/javascript

### ISSUE THREAD

**Issue by nhorton** [avo-hq/avo#2003]
I followed the v3.0 instructions for using importmaps and have a pretty generic `avo.custom.js` made by the generator, and loaded with the `_head.html.erb` partial from the generator. The code for the head partial is simple:
```
<!-- Avo JS -->
<%= javascript_include_tag "https://cdn.plaid.com/link/v2/stable/link-initialize.js", nonce: true %>
<%= javascript_importmap_tags "avo.custom" %>
<!-- End Avo JS -->
```
But the resulting web renders is pulling from spec/dummy instead of my normal assets path. Any ideas?

**Comment by adrianthedev** [comment]
Yup. An error on our end.
Please use a different name, not `avo.custom` until we issue a fix.

Thanks for the report.

**Comment by adrianthedev** [comment]
We need to remove `app/assets/builds/avo.custom.js|map` from the final artefact @Paul-Bob
