### ISSUE TITLE
highlight search results

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2014]
### Feature

use `highlight` to highlight search results: https://apidock.com/rails/v5.2.3/ActionView/Helpers/TextHelper/highlight

### Screenshots or screen recordings

current search results:
<img width="727" alt="Screenshot 2023-11-06 at 09 03 16" src="https://github.com/avo-hq/avo/assets/13472945/4808e951-5eb6-4202-9172-67c4fee64624">
desired state with highlighting:
<img width="594" alt="Screenshot 2023-11-06 at 09 03 03" src="https://github.com/avo-hq/avo/assets/13472945/617364cd-c0a8-4c63-a37e-3fa4908f6e80">

**Comment by GajendraR** [comment]
i want to work on it

**Comment by adrianthedev** [comment]
You got it @GajendraR!

As an approach, I would recommend returning the search results with the string highlighted (in the `search_controller.rb` and then adding a CSS rule to apply that styling.

Let me know if you get stuck or need more help navigating the codebase.

We appreciate your help.
