### ISSUE TITLE
💡 allow embedding avo tables

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2015]
### Feature

Maybe just by wrapping index tables into a `<%= turbo_frame_tag resource_name do ...%>`, we can render them in the views of the main app like:

```
<%= turbo_frame_tag :users, src: avo.resources_users_path %>
```

**Comment by yshmarov** [comment]
> Hei @yshmarov! Great idea! Actually this is already one of our [roadmap items for v3](https://v3.avohq.io/roadmap)

Amazing! I will be looking forward! 🥰

**Comment by Bergrebell** [comment]
+1 - this would be really great to have!

**Comment by zlailari** [comment]
+1 - and FYI it looks like this ticket was reopened but is still marked as `Done` in the roadmap

**Comment by adrianthedev** [comment]
Moved it back into To-do.

What is your use-case? How yould you use this feature @zlailari?

**Comment by zlailari** [comment]
We have 3 user types:
1. Regular product users who never see avo
2. Internal employees who use the full admin panel
3. Enterprise customers who can view and take some admin actions on their associated users

Being able to embed avo tables in the enterprise dashboard (for group 3) would accelerate how quickly we could ship some features

**Comment by adrianthedev** [comment]
I see. Yes, that makes sense.

Would you be open to pay an enterprise license for a feature like that ($30K+/year)?

**Comment by zlailari** [comment]
Unfortunately, an enterprise license isn't within our budget and our current use case doesn't justify that level of expenditure. It would be a great addition to the product though!

**Comment by adrianthedev** [comment]
Yes. I agree. It would be a good feature.
The development effort to build and maintain it going forward is probably quite high for us.

Can I ask what are you building with Avo?

**Comment by Paul-Bob** [comment]
This should work for all resources type including the [array resources](https://github.com/avo-hq/avo/pull/3469).
