### ISSUE TITLE
Improove documentation for actions

### ISSUE THREAD

**Issue by yashka713** [avo-hq/avo#2017]
### Context
I can't find an answer to what I should do to make action available? I turn `true` all policies for the parent and for the `VendorUser`. But action still blocked

### System configuration
**Avo version**: 3.0.1.beta23

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding ,views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="1134" alt="Screenshot 2023-11-06 at 13 02 02" src="https://github.com/avo-hq/avo/assets/15985355/bbaf4ce0-2bda-4a59-8fd7-d32712da9d45">

**Comment by Paul-Bob** [comment]
Hey @yashka713

Your "Display Active" action is already available. With police you can hide and block that action execution.

Our docs can be exhaustive and it's common to miss some details while reading it.

> Avo actions allow you to perform specific tasks on one or more of your records.
https://docs.avohq.io/3.0/actions.html#actions

The action will become enabled while selection one or more records


> You may need to run actions that are not necessarily tied to a model. Standalone actions help you do just that.
https://docs.avohq.io/3.0/actions.html#standalone-actions

If you need an action that is not tied to a model `self.standalone = true` is what you're looking for.

**Comment by Paul-Bob** [comment]
@yashka713 does it makes sense?

**Comment by yashka713** [comment]
Yes, thank you 🚀 

This is exactly what I was looking for

> You may need to run actions that are not necessarily tied to a model.

This is a misunderstanding sentence, I thought  `model` was an ActiveRecord model. And action `tied` to this model through resource

In V3 you clarified `model` to `record` but if you have time to add a screenshot, it will be helpful

One more question, since we are both here... Why did AVO team decide to prevent `show_controls` changing for `pro` license owners in V3? I am asking because our business model has only 1 resource for displaying and the `back_button` does not work well in some cases. So we use `link_to` to generate the right link for `back` button

**Comment by Paul-Bob** [comment]
> This is a misunderstanding sentence, I thought model was an ActiveRecord model. And action tied to this model through resource
> 
> In V3 you clarified model to record but if you have time to add a screenshot, it will be helpful
> 

We should clarify that on actions, I'll add a task for that.

> One more question, since we are both here... Why did AVO team decide to prevent `show_controls` changing for `pro` license owners in V3? I am asking because our business model has only 1 resource for displaying and the `back_button` does not work well in some cases. So we use `link_to` to generate the right link for `back` button

On `V3` we extended the `show_controls` feature to custom controls everywhere, `index`, `show`, `edit`, even `row` controls, check https://main.avodemo.com/avo/resources/fish, pick a fish and verify that all views and rows have customized controls.  

`show_controls` is part of a bigger system now and it require extra maintenance from our part. That system is available on `advanced` licenses.

**Comment by yashka713** [comment]
> We should clarify that on actions, I'll add a task for that.

Many thanks to you and the team

Thank you for explanation about `show_controls`
