### ISSUE TITLE
Set the display position of the Card of Resource[Avo3]

### ISSUE THREAD

**Issue by yuki-yogi** [avo-hq/avo#2018]
### Feature
- Set the display position of the Card of Resource

### Current workarounds
- none

### Screenshots or screen recordings
- none

### Additional context
In social blade, the graphs are below the listings. We would like to realize such an easy-to-view screen and graphs with Resource's card function.
https://socialblade.com/youtube/user/pewdiepie

<img width="848" alt="スクリーンショット 2023-11-08 2 01 59" src="https://github.com/avo-hq/avo/assets/14293538/f4fe7d19-7771-4132-901e-84151ef699aa">

**Comment by adrianthedev** [comment]
@yuki-yogi I don't quite get the request here. You'd like to add a graph card on a resource show page? You can already do that.

**Comment by adrianthedev** [comment]
Hey @yuki-yogi. I had a call with Paul today and from that conversation and this new comment I got it.
You want to ability to add cards in more places than just above the main panel of a resource.

We make this a first-party feature in later iterations of the product.

You could achieve that using a custom view component and override Avo's if you really need it.
Another way of doing it is with resource tools AFAIK.

Thanks for the feedback!
