### ISSUE TITLE
Field `belongs_to` is using the name to find the resource

### ISSUE THREAD

**Issue by nicolascochin** [avo-hq/avo#202]
Hi, 

The `belongs_to` field relation is not working. 
Looking at the code, I think the error is right here: 
https://github.com/avo-hq/avo/blob/017aa12209bf1adc471630dde8d17b163669372f/lib/avo/app/fields/belongs_to.rb#L25

As we can see, the name is used to find the resource. I think this is a mistake as the name could be anything. 
The relation's class name should be used (as it is for the `has_many` field) 

Something like this : 
```ruby
class_name = model._reflections[id.to_s].options[:class_name].present? ? model._reflections[id.to_s].options[:class_name] : model._reflections[id.to_s].name
App.get_resources.find { |r| r.class == "Avo::Resources::#{class_name.to_s.camelcase.singularize}".safe_constantize }
```

**Comment by adrianthedev** [comment]
Hi,
Yup! That's the bug! 
I have a PR ready that better searches for an Avo resource. I'll tag a new version in the next hour or so!

Thank you for letting us know! I appreciate it!

**Comment by adrianthedev** [comment]
Tagged in https://github.com/avo-hq/avo/releases/tag/v0.4.5. 
Let us know if this fixed your issue.
