### ISSUE TITLE
Incorrect dashboard card ranges on initial page load

### ISSUE THREAD

**Issue by nicholaswellens** [avo-hq/avo#2022]
### Describe the bug
When having multiple dashboard cards with `ranges`, and those cards have different `initial_range`s, the `range` for the cards is sometimes incorrect on initial load. See below for what I suspect the problem is. Not urgent, since I have a workaround.

### Steps to Reproduce
1. Create a dashboard with two Cards, each with ranges, but with different initial ranges (can choose an `initial_range` that doesn't exist in the other cards `ranges`). See the dashboard screenshot as an example.
2. Refresh the dashboard (multiple times if needed)
3. See one card malfunctioning because of not having the correct `range` set.

### Expected behavior & Actual behavior
- The `range` of the cards on initial load being equal to their respective `initial_range`
- See first dashboard screenshot for expected behavior in the example.
- Actual behavior: card malfunctioning. See second dashboard screenshot.

### Models and resource files

![image](https://github.com/avo-hq/avo/assets/18333645/08a371ac-6f4e-40c7-b6ab-6277a72ada41)
![image](https://github.com/avo-hq/avo/assets/18333645/50f7d2f9-baf4-4506-89fd-094c2db9aa8e)

### System configuration
**Avo version**: 2.38.0

**Rails version**: 6.1.7.4

**Ruby version**: 3.0.2

**License type**:

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

Desired case:
![image](https://github.com/avo-hq/avo/assets/18333645/24038b9b-9980-4c96-9eb1-1416b2218009)

 Bug case:
![image](https://github.com/avo-hq/avo/assets/18333645/7dc27d71-fc0c-4ac1-807b-510ff30af535)

### Problem investigation
A turbo frame for each card gets eager loaded on dashboard page load (_avo/dashboards/show.html.erb_). Each of these calls sends params (including the range, equal to the `initial_range` if set). These calls update the `Avo::App` `params` class attribute each time. The `range` of a card is effected by the range param set (see screenshot below). The eager loading requests of the turbo frames do not necessarily match the order in which the `query`, and thus `range`, method of the cards are called, resulting in using params for card y when checking the `range` of card x. Eg. both turbo frame requests (of card x and card y) arrive before card x's `range` actually gets called. See last screenshot for a real example: the card class is `DailySales` but if we look at the params, they are params (and thus have the `range`) from the `Income` card turbo frame!

_avo/base_card.rb_
![image](https://github.com/avo-hq/avo/assets/18333645/8ac0d9dc-5b49-4413-98ff-b2b48798e090)
![image](https://github.com/avo-hq/avo/assets/18333645/d846e5dc-aaf9-42a1-a7e1-bf0b03b4f427)

![Screenshot from 2023-11-09 19-36-32](https://github.com/avo-hq/avo/assets/18333645/cd4adb79-c38c-4e50-b8e3-2f38f4108bd0)

### Current workaround
I overrid `BaseCard` and removed the `range` param from the turbo frame load, which fixes the issue for me (the params can still be from the wrong card on initial load but it doesn't affect anything). 

![image](https://github.com/avo-hq/avo/assets/18333645/11e88c33-36f9-4ff9-9f32-f782973df558) 

Notes:
- I think the `range` param only makes a difference in `frame_url` if `enforced_range` is being used, but I believe it is never used, _dashboards/show.html.erb_ has a `@range` param for that but I don't see it being defined anywhere. 
![image](https://github.com/avo-hq/avo/assets/18333645/f842376e-d142-4b58-ade8-2aaa112590dd)

- Slightly unrelated remark: `frame_url` and `range` methods use `ranges.first` as a backup, but shouldn't it be `ranges.first.second` as `ranges` is a hash (or array of array)?

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yes. This is a race condition that happens because I badly designed the `Avo::App.params` object.
It's fixed in Avo 3 by using [`CurrentAttributes`](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html), which is thread-safe and won't allow for this to happen.

Are you planning to upgrade to Avo 3 soon?

**Comment by nicholaswellens** [comment]
@adrianthedev Great that it is fixed in Avo 3! Yes I believe we will eventually upgrade, and until then I will use the workaround :)
