### ISSUE TITLE
How to access current_user in a filter

### ISSUE THREAD

**Issue by mighani** [avo-hq/avo#2026]
### System configuration
**Avo version**: 2.44

**Rails version**: 7

**License type**

 - [ ] Community
 - [ x] Pro

I want to show a filter to a loggedIn user where he can see only employees which belong to his own department. For this, I would need access to the current_user in the filter to manipulate the filter options. Can I achieve this some how?

**Comment by adrianthedev** [comment]
Can you try `Avo::App.current_user`?

**Comment by mighani** [comment]
It works :-) Thank you
