### ISSUE TITLE
Turbo Rails issue

### ISSUE THREAD

**Issue by hmasing** [avo-hq/avo#2032]
### Context
Getting "Content missing" on associated records and "Unpermitted Parameters" on :turbo_frame:

### System configuration
**Avo version**: 2.34.5

**Rails version**: 7.0.8

**Ruby version**: 3.2.0

**License type**

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

![image](https://github.com/avo-hq/avo/assets/100706/42757aed-cabf-4824-8cd0-6d16107d4ec5)
![image](https://github.com/avo-hq/avo/assets/100706/9db2ed88-f5fd-4ead-9e9b-7ba2c2b88600)

**Comment by hmasing** [comment]
We use haml, not erb in our application. Per previous chats, I have put in absolute paths for our flash messages which fixed the issue in some areas, but not apparently in others.

**Comment by adrianthedev** [comment]
@hmasing I think we need a reproduction repository to be able to debug this.
You can start with [this repo](https://github.com/avo-hq/avo-reproduction) ot make it quicker.

**Comment by hmasing** [comment]
> @hmasing I think we need a reproduction repository to be able to debug this. You can start with [this repo](https://github.com/avo-hq/avo-reproduction) ot make it quicker.

I'll try, but I'm a team of one with an app with about 80 namespaced models so I don't think I have the cycles to reproduce this specific use case outside our stack. Thanks, and I will do my best to get this done!

**Comment by adrianthedev** [comment]
I understand. It's kind of the same situation here.
There are so many moving pieces inside the parent app that can cause this, that we may never figure it out by ourselves. 
It's difficult for us to troubleshoot blindly.

**Comment by hmasing** [comment]
I totally get it.  :-) I am open to a pairing session if that would be helpful to you guys.

**Comment by adrianthedev** [comment]
You don't need to set up the whole thing.
Usually, when you try to reproduce the issue, you find the bug.

We offer Avo-related technical support. If you're interested, please reach out to me at adrian@avohq.io
