### ISSUE TITLE
packager.dev error when installing Avo gem

### ISSUE THREAD

**Issue by joshfester** [avo-hq/avo#2036]
### Context
Following the docs for v3, I add this to my gemfile
`gem "avo", ">= 3.0.1.beta9", source: "https://packager.dev/avo-hq/"`

When I run bundle install, I get this error message:
`Bundler::HTTPError: Could not download gem from https://packager.dev/avo-hq/ due to underlying error <bad response Internal Server Error 500 (https://packager.dev/avo-hq/gems/avo-3.0.1.beta24.gem)>`

I tried locking it to just 3.0.1.beta9, and get the same issue:
`Bundler::HTTPError: Could not download gem from https://packager.dev/avo-hq/ due to underlying error <bad response Internal Server Error 500 (https://packager.dev/avo-hq/gems/avo-3.0.1.beta9.gem)>`

### System configuration
**Avo version**: 3.0.1.beta9

**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Looking into it

**Comment by adrianthedev** [comment]
Found the bug and pushed a fix. Can you please try again @joshfester

**Comment by joshfester** [comment]
That worked! Thanks so much 🙏
