### ISSUE TITLE
[Help wanted] Accessing params in custom Action

### ISSUE THREAD

**Issue by jtethras** [avo-hq/avo#2037]
### Context

```
class GenericResource < Avo::BaseResource

  field :review_meetings, as: :has_many, through: :review, only_on: %i[show edit]
```

There is a custom action on `ReviewMeeting`:
```
class ReviewMeetingResource < Avo::BaseResource

  self.show_controls = lambda do
    action CancelMeeting
  end
```

When I go to `ReviewMeetingResource#show` from `GenericResource`, there are additional params in the path:
`/resources/review_meetings/49?via_resource_class=GenericResource&via_resource_id=mlniAw`

I'd like to eventually access `via_resource_class` and `via_resource_id` values in my `CancelMeeting#handle`,

Would appreciate some help for an issue. Thanks!

**Avo version**:
v2.41.0
**Rails version**:
6.1

**Comment by adrianthedev** [comment]
Are you using Avo 2 or Avo 3?

**Comment by jtethras** [comment]
> Are you using Avo 2 or Avo 3?

Avo 2
