### ISSUE TITLE
search bar and link "back to app" are not visible on mobile view

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2060]
### Describe the bug

desktop:
<img width="1710" alt="Screenshot 2023-11-25 at 12 11 25" src="https://github.com/avo-hq/avo/assets/13472945/02d57f27-5923-4914-83a2-1945962a5403">

mobile:
<img width="563" alt="Screenshot 2023-11-25 at 12 11 37" src="https://github.com/avo-hq/avo/assets/13472945/569a8efa-1cab-4917-a5d1-8a98aad53716">

**=> no search and link back to app on mobile**

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@yshmarov I can't seem to reproduce it on my end or on the [demo site](https://avodemo.com/avo/resources/projects).

Can you check to see if you ejected the `_navbar` partial?
[This](https://github.com/avo-hq/avo/blob/main/app/views/avo/partials/_navbar.html.erb) is the original one.

**Comment by adrianthedev** [comment]
It happens only on Firefox
