### ISSUE TITLE
The pagination is not reset on a filter change

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2076]
Seem yet present
for example if from

https://main.avodemo.com/avo/resources/projects?keep_filters_panel_open&page=2

filter by a country
https://main.avodemo.com/avo/resources/projects?page=2&filters[country][is][]=GT
I receive a error 500 on main.avodemo.com
or 
Pagy::OverflowError at /resources/ea_service_categories
expected :page in 1..1; got 2
in local env

_Originally posted by @stefsava in https://github.com/avo-hq/avo/issues/428#issuecomment-1838463730_

**Comment by yuki-yogi** [comment]
Thanks for creating the issue.
I was about to report this issue as well.

**Comment by yuki-yogi** [comment]
Thanks for adding it to the roadmap.
Sometimes I run into this glitch.

**Comment by Paul-Bob** [comment]
It will be fixed on the next release
