### ISSUE TITLE
Wrong inheritance

### ISSUE THREAD

**Issue by nicolascochin** [avo-hq/avo#208]
Hi, 

The `Avo::ApplicationMailer` should inherits `::ActionMailer::Base` (missing the `::`) 
https://github.com/avo-hq/avo/blob/05e829de8a488432d2ab009b09a05bf6bb0f099d/app/mailers/avo/application_mailer.rb#L2

This is failing some tools such as erd (https://github.com/voormedia/rails-erd) as the `Avo::ApplicationMailer` can't be loaded 
```ruby
irb(main):004:0> Avo::ApplicationMailer
Traceback (most recent call last):
        2: from (irb):3
        1: from (irb):4:in `rescue in irb_binding'
NameError (uninitialized constant Avo::ActionMailer)
Did you mean?  ActionView
```

Regards, 

Nicolas

**Comment by adrianthedev** [comment]
Haven't been able to replicate it in the console but makes sense and addressed it in the PR.

Thank you for this!
