### ISSUE TITLE
Action view fails to render with select field using dynamic lambda options

### ISSUE THREAD

**Issue by shiroemons** [avo-hq/avo#2083]
### Describe the bug

When using a select field within an action with a lambda function to dynamically generate options, a 500 Internal Server Error occurs.

### Steps to Reproduce
1. Add a select field to an action with the following options configuration:
   ```ruby
   field :event, as: :select, options: -> { ::Event.all.map { [_1.name, _1.id] } }
   ```
2. Navigate to the action from the list view within the application.
3. Trigger the action, which results in a 500 Internal Server Error and the action modal does not appear.

### Expected behavior & Actual behavior

Expected: The action's view should render correctly with the select field.
Actual: The application throws a 500 Internal Server Error.

### System configuration

**Avo version**: 2.44.0
**Rails version**: 7.0.4.3
**Ruby version**: 3.2.2
**License type**: 

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

Error message from logs:
```
Completed 500 Internal Server Error in 203ms (ActiveRecord: 0.0ms | Allocations: 13034)

ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    26:       <% if @action.get_fields.present? %>
    27:         <div class="my-4 -mx-6">
    28:           <% @action.get_fields.each_with_index do |field, index| %>
    29:             <%= render field
    30:               .hydrate(resource: @resource, model: @resource.model, user: @resource.user, view: @view)
    31:               .component_for_view(@view)
    32:               .new(field: field, resource: @resource, index: index, form: form, compact: true)
```

When using a select field with static options, no errors are generated. For example, if you define a field with a simple hash of options as follows, it will work correctly without generating any errors

```ruby
field :type, as: :select, options: { 'Large container': :large, 'Medium container': :medium, 'Tiny container': :tiny }
```

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
In Avo 2 the `options` block takes a few arguments.
https://docs.avohq.io/2.0/fields/select.html#computed-options

```ruby
options: ->(model:, resource:, view:, field:)
```

You might have seen the 3.0 version of the docs site. There is a version switcher on the top-right to got to the 2.0 version of the site.
The search will always take you to 3.0. We don't have a solution to fix that. We're open to get some help with that.
