### ISSUE TITLE
Wrong module

### ISSUE THREAD

**Issue by nicolascochin** [avo-hq/avo#209]
Hi, 

The Avo configuration uses the iso gem. 
In the `locale_tag` method, this gem is used but should use the global scope
cf https://github.com/avo-hq/avo/blob/f93486296860f0a107f28d56273d4ceab9f206ed/lib/avo/configuration.rb#L48

example : 
```ruby 
irb(main):007:0> Avo.configuration.locale_tag
Traceback (most recent call last):
        1: from (irb):7
NameError (uninitialized constant Avo::Configuration::ISO)
irb(main):008:0> 
``` 

The result is that the default locale is changed to `en`

**Comment by adrianthedev** [comment]
Great catch. Thank you!
