### ISSUE TITLE
Fix `Rails.application.secrets.secret_key_base`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2090]
`Rails.application.secrets.secret_key_base` will be removed in rails `7.2`. We should assure that our `lib/avo/services/encryption_service.rb` do not call `Rails.application.secrets.secret_key_base` when rails version `>= 7.2`.

Also make sure that all avo packages use `ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base` to avoid warning logs.
```[tasklist]
### Tasks
- [x] Add `>= 7.2` condition before calling `Rails.application.secrets.secret_key_base`
- [x] Ensure `ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base` usage on all avo packages spec.
```

**Comment by lrjbrual** [comment]
hi @Paul-Bob, 

I try to add avo free version in one of my applications, using "rails", "~> 8.0.0",  and ruby-3.3.1. however, when I put in my production, I have an error saying about my secretkey, here is the screenshot:

![Image](https://github.com/user-attachments/assets/ff02e4e6-94b6-4785-ab84-86c6db2e2c2f)

I already do precompile assets, and I did not know if I need to add this in avo.rb 

`  config.license_key =   (ENV['SECRET_KEY_BASE'] || Rails.application.credentials.secret_key_base)`

the documentation says that I need to add the secret_key_base https://docs.avohq.io/2.0/installation.html#requirements 
but not sure if that is correct to add in avo.rb

Can you help? 

Thank you in advance

**Comment by Paul-Bob** [comment]
Hi @lrjbrual

I think that is happening because the log file does not exist.

The file should be created automatically by [this line](https://github.com/avo-hq/avo/blob/main/lib/avo/configuration.rb#L241). If the issue persist you can change the avo loger using this configuration https://docs.avohq.io/3.0/customization.html#logger

Let me know how it goes

**Comment by lrjbrual** [comment]
> this line

Thanks for the reply. I still got this issue: after following the docs to enable in avo.rb:

```
  ## == Logger ==
  config.logger = -> {
    file_logger = ActiveSupport::Logger.new(Rails.root.join("log", "avo.log"))

    file_logger.datetime_format = "%Y-%m-%d %H:%M:%S"
    file_logger.formatter = proc do |severity, time, progname, msg|
      "[Avo] #{time}: #{msg}\n".tap do |i|
        puts i
      end
    end

    file_logger
  }

```

Here is the info from my docker production, even I added also permission as all, but I still have this, and my docker continues restarting. 
![Image](https://github.com/user-attachments/assets/83e9731b-669e-4d1c-9257-f233c1356ab5)

**Comment by Paul-Bob** [comment]
It seems that the permissions are not correctly assigned. 

The code from the documentation is the default configuration, you cand try changing the logger from file to stout

Something like this

```ruby
## == Logger ==
config.logger = -> {
  file_logger = ActiveSupport::Logger.new(STDOUT)

  file_logger.datetime_format = "%Y-%m-%d %H:%M:%S"
  file_logger.formatter = proc do |severity, time, progname, msg|
    "[Avo] #{time}: #{msg}\n".tap do |i|
      puts i
    end
  end

  file_logger
}
```

**Comment by lrjbrual** [comment]
> It seems that the permissions are not correctly assigned.
> 
> The code from the documentation is the default configuration, you can try changing the logger from file to stout
> 
> Something like this
> 
> ## == Logger ==
> config.logger = -> {
>   file_logger = ActiveSupport::Logger.new(STDOUT)
> 
>   file_logger.datetime_format = "%Y-%m-%d %H:%M:%S"
>   file_logger.formatter = proc do |severity, time, progname, msg|
>     "[Avo] #{time}: #{msg}\n".tap do |i|
>       puts i
>     end
>   end
> 
>   file_logger
> }

Hi @Paul-Bob, Yes I used that code. I found an issue with the server with inheritance permission. But now it is working. thanks. 
btw, I like Avo and seems cool to use for projects. thanks again

**Comment by Paul-Bob** [comment]
Awesome! Thanks for the feedback!
