### ISSUE TITLE
`Pagy::OverflowError`

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#2092]
### Describe the bug

If you are on page N of results, and apply a filter that produces N-1 pages of results, an error is thrown and a page reload is required to proceed.

Perhaps resetting the page offset when applying a new filter / changing a filter would be prudent.  Or, at least, not letting the exception kill the filter controls and pagination controls.

### Steps to Reproduce
1. Set up a resource, with filterable fields.
2. Create a lot of records
3. View the index page, and navigate several pages through the results
4. Add a field filter that will narrow the results to a small number.
5. See error

### Expected behavior & Actual behavior

I would expect to either see no results, but have the controls all remain present, or have my pagination offset reset to the first page.

### System configuration
**Avo version**: 3.1.1

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by MrJoy** [comment]
<img width="820" alt="image" src="https://github.com/avo-hq/avo/assets/113625/c9dc5003-0c2a-4fe8-8ae6-5d7498c3efe1">

**Comment by Paul-Bob** [comment]
I think this is same as https://github.com/avo-hq/avo/issues/2076

**Comment by MrJoy** [comment]
I believe you are correct.
