### ISSUE TITLE
Action fields populate values from models

### ISSUE THREAD

**Issue by marcoroth** [avo-hq/avo#2097]
### Steps to Reproduce
1. Update the `app/avo/actions/release_fish.rb` file with:

```ruby
class Avo::Actions::ReleaseFish < Avo::BaseAction
  self.name = "Release fish"

  def fields
    field :name, help: "This field is populated from the `name` field form the model just because it has the same name, but I think it shouldn't"
  end
end

```

3. Go to http://127.0.0.1:3020/avo/resources/fish
4. Click on "Release Carp"
5. See `name` input prefilled with value from `Fish` model

![CleanShot 2023-12-12 at 23 46 34](https://github.com/avo-hq/avo/assets/6411752/6b81c0fa-9034-4ef7-afe6-bc4973b59b22)

### Expected behavior & Actual behavior

I would expect the input field to be empty, since the action doesn't necessarily have anything to do with the model you are runing the action against.

### Models and resource files

Repro repo: https://github.com/marcoroth/main.avodemo.com/tree/action-input-prefilled

Full diff: https://github.com/avo-hq/main.avodemo.com/commit/082bab329a103cda834e1755639d23fd9e12f2f4

### System configuration
**Avo version**: `3.1.4` (the bug has been present since at least `3.0.1.beta7`)

**Rails version**: `7.0.8`

**Ruby version**: `3.2.2`

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
That's kind of a feature not a bug 😅.

It allows for fields to be autopopulated with data from the resource.
Think about the scenario where you don't want to enable the edit view but want to have an action with a few fields from the action pre-populated.

This can be fixed using `default: -> { "" }`. Not the prettiest solution, I know.
