### ISSUE TITLE
Security: disable_editing_keys can be bypassed by editing the DOM

### ISSUE THREAD

**Issue by Mys7ic** [avo-hq/avo#2103]
Fields of type `key_value` support the disabling of some editing functions such as `disable_editing_keys`.

However, the `disable` functions only deactivate the functions in the frontend. In general, a difference is made between `disabled` and `readonly` for fields. However, the additional `disable` functions for `key_value` are more like `readonly`.

Although this is not a direct vulnerability, but still security-relevant

### References
https://docs.avohq.io/3.0/fields/key_value.html#disable_editing_keys
https://docs.avohq.io/3.0/field-options.html#disabled
https://docs.avohq.io/3.0/field-options.html#readonly

### Steps to Reproduce
remove disable in Browser

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Peek 2023-12-13 16-32](https://github.com/avo-hq/avo/assets/26570201/49ba1a04-d34e-4ee7-9a1e-4545d6e46bcb)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hmmm. I see.

As this is a field, users can duplicate it and fix this on their own.
Unfortunately we don't have the bandwidth to work on it right now or in the foreseeable future.

We would love and welcome a contribution thought.

**Comment by adrianthedev** [comment]
I'll close this as `wontfix` for now to keep the issue tracker clear.
If anyone wants to pick it up we'll open the issue.
