### ISSUE TITLE
In the attach view, try to show a list of records and have something like a checkbox or add button

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2115]
This is an example of what I mean (shopeo).

The suggestions could be added as a DSL option

![Image](https://user-images.githubusercontent.com/1334409/169785763-7a391a36-8fdf-4584-be7d-625d5d7227c8.png)

**Comment by Paul-Bob** [comment]
Closing as duplicated of https://github.com/avo-hq/avo/issues/2116
