### ISSUE TITLE
Implicit authorization

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2125]
This disables everything (access to the resource/search/attachments/uploads, everything) until someone implicitly enables them.

Maybe we should introduce a roles system that will handle this.

From https://github.com/avo-hq/avo/discussions/1574

**Comment by adrianthedev** [comment]
This should work great with https://github.com/avo-hq/avo/issues/2126

**Comment by icaroryan** [comment]
Any updates on this? I'm also going through the same issue. Using some monkey-patching as a workaround

**Comment by icaroryan** [comment]
UP

**Comment by adrianthedev** [comment]
I wonder if this can be achieved by making all methods return `false` in the `ApplicationPolicy`?

**Comment by icaroryan** [comment]
I've been using some monkey-patching as a workaround, which has been working good so far. Just a little inconvenient having to manually add it for every association.

application_policy.rb
```rb
def self.has_association(association, with_full_permissions = false)
  ['create', 'attach', 'detach', 'destroy', 'edit'].each do |action|
    define_method(:"#{action}_#{association}?") { with_full_permissions }
  end
  define_method(:"show_#{association}?") { Pundit.policy!(user, record).show? }
  alias_method :"view_#{association}?", :show?
end
```

Kudos to @segiddins for sharing this in https://github.com/avo-hq/avo/discussions/1574
