### ISSUE TITLE
Index inline editing

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2129]
Enable inline editing on the `Index` view.

**Comment by filipegiusti** [comment]
Is this the same as https://github.com/avo-hq/avo/issues/1112? Is there a way to vote/request/fund this?

**Comment by adrianthedev** [comment]
Yes @filipegiusti. It's the same issue.

There is the opportunity to fund this feature and prioritize it, but let's have a conversation about what do you need from it.
Please book something in [my calendar](https://calendly.com/adrianthedev).

**Comment by adrianthedev** [comment]
Closing in favor of #1112
