### ISSUE TITLE
Add cover and profile photo to resource show component

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2137]
Give the user the ability to make any record look like a FB or Notion page.

Maybe set something in the DSL as what is the "cover" field and what is the "profile photo" field.

### Example

![Image](https://github.com/avo-hq/avo/assets/1334409/93cf0fec-5d10-4893-8a7a-bc3015808fd7)

**Comment by Paul-Bob** [comment]
Closed by https://github.com/avo-hq/avo/pull/2722
