### ISSUE TITLE
Jumpstart-pro template returns error out of the box

### ISSUE THREAD

**Issue by swistaczek** [avo-hq/avo#2148]
When using https://avohq.io/templates/jumpstart-pro with jumpstart-pro, I discovered a wrongly named module was being inherited.

<img width="1055" alt="Screenshot 2023-12-18 at 11 13 24" src="https://github.com/avo-hq/avo/assets/13238/e2e25298-b6d7-4021-890b-ebfd0ba8e358">

🔗 https://github.com/avo-hq/jumpstart-pro-app-template

**Comment by swistaczek** [comment]
another one 

<img width="1054" alt="Screenshot 2023-12-18 at 11 14 56" src="https://github.com/avo-hq/avo/assets/13238/fdafa1d2-9bcc-4837-8ff1-c4eab659dfb2">

**Comment by adrianthedev** [comment]
Thanks for the report @swistaczek.

Should be fixed now! Can you please try again?

**Comment by swistaczek** [comment]
Thanks, @adrianthedev; that part looks good now!  I will post more findings in this thread to avoid unnecessary spam. 

<img width="1054" alt="Screenshot 2023-12-18 at 11 24 19" src="https://github.com/avo-hq/avo/assets/13238/81318e9c-d2a3-4357-a4b3-f13119a2c8e2">
<img width="1029" alt="Screenshot 2023-12-18 at 11 25 11" src="https://github.com/avo-hq/avo/assets/13238/f74ae85c-6726-4f79-a6be-b9a236677090">

**Comment by adrianthedev** [comment]
pushed a fix for that too.

**Comment by adrianthedev** [comment]
Closing for now.

Feel free to reopen if anything is still broken ✌️
