### ISSUE TITLE
Warn developer if they override one of Avo's controllers

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2161]
Creating for example `AttachmentResource` will generate the `Avo::AttachmentsController` overriding the `app/controllers/avo/attachments_controller.rb`

We should fail in the generator if the user is trying to override controllers that break the app. Also we should show how can they use another name for resource/controller for a specific model using `--model_class attachment`

**Comment by Paul-Bob** [comment]
Related to https://github.com/avo-hq/avo/issues/2437

**Comment by adrianthedev** [comment]
Yes. :| Let's prioritize this sometime.
