### ISSUE TITLE
Show distinct values on Index

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2162]
A user has a field called status with multiple values. 
We'd love to be able to click a button on the `Index` view and show all the values from the DB and how many are in which category.

**Comment by bryszard** [comment]
@adrianthedev I'll try to tackle this one :)

**Comment by adrianthedev** [comment]
It's yours! 
Looking forward to see how this looks like.
Thanks!

**Comment by adrianthedev** [comment]
I think we can tie this one very nicelt with the dynamic filetrs feature to further filyer the records down. 
But one step at a time

**Comment by bryszard** [comment]
@adrianthedev I have the first draft for the design. I'd add a bar chart icon next to the column label, which will be clickable and then it will show a small box with the summaries in it.

Not sure if we should be allowing columns to be both sortable and "summarizable".

Let me know what do you think:

![image](https://github.com/avo-hq/avo/assets/12682792/fbf7259d-112a-4c8c-a74c-540e422be800)

**Comment by adrianthedev** [comment]
I think it's a good start.
I've been thinking about how to "marry" all these actions (sorting, filtering, and distinct values).

Instead of limiting the user to just one button, or showing two of them (and maybe later getting into issues when we add a third action), we could add a dropdown like Airtable has to show all the actions one can do with that column.

What do you think about the approach?

If you're not comfortable with designing it, I can take over and make it a bit prettier after you submit the PR.


![CleanShot 2024-01-15 at 14 03 22](https://github.com/avo-hq/avo/assets/1334409/26e8456e-ea56-4a9c-82a8-a5a0c8170de9)

**Comment by bryszard** [comment]
@adrianthedev Good idea. A similar solution, but simpler, you can find on Metabase:

![image](https://github.com/avo-hq/avo/assets/12682792/c8c9326f-dc43-4b2b-8208-3147c05211f5)

I'll try to come up with something (probably during the weekend).

**Comment by adrianthedev** [comment]
yes, the airbnb fropdown is a bit more advanced and we don't need it like that.
Metabase has a good solution too!

What does the "Distribution" button do?

**Comment by bryszard** [comment]
In their case it is a link a query with visualisation that shows you the distribution of the value, like this:

![image](https://github.com/avo-hq/avo/assets/12682792/da73781f-c512-4d45-94ec-a66f77058de0)

**Comment by bryszard** [comment]
@adrianthedev Right now it looks like this:

![image](https://github.com/avo-hq/avo/assets/12682792/c5909531-1917-4134-9174-22a2a0d2679b)

Not sure what styling we want to apply inside there. 
I was also thinking about adding a pie chart inside, WDYT?

**Comment by adrianthedev** [comment]
The pie chart might be a cool thing to have. 

That looks cool.

**Comment by bryszard** [comment]
This is how it could look with the pie chart. I'll need to tweak the integration between those two parts:

![image](https://github.com/avo-hq/avo/assets/12682792/d65f95aa-a52a-4c29-a3c1-cbd918c7917a)

**Comment by adrianthedev** [comment]
This looks great @bryszard. I'll move the convo to the PR and make sure we'll review it this week.
Thank you!
