### ISSUE TITLE
Customize the flash messages time

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2167]
Would be interesting to be able to choose the exact time that the flash messages last.

**Comment by Paul-Bob** [comment]
Related issues: 

- https://github.com/avo-hq/avo/issues/1939 
- https://discord.com/channels/740892036978442260/1204494450512896080

**Comment by adrianthedev** [comment]
This is fixed by `Avo.configuration.alert_dismiss_time`
