### ISSUE TITLE
Turbo 8 beta with Avo

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#2192]
Hey,

Getting this error:

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because turbo-rails >= 1.3, < 2.A could not be found in https://github.com/hotwired/turbo-rails.git (at main@4eb4e92)
  and turbo_power >= 0.3.1, < 0.6.0 depends on turbo-rails ~> 1.3,
  turbo_power >= 0.3.1, < 0.6.0 cannot be used.
So, because avo >= 2.44.0 depends on turbo_power ~> 0.5.0
  and Gemfile depends on avo ~> 3.1,
  version solving has failed.
```

When trying to install using `gem "turbo-rails", github: "hotwired/turbo-rails", branch: "main"`

**Comment by adrianthedev** [comment]
What Avo version are you using?

**Comment by rctneil** [comment]
`gem "avo", "~> 3.1"`

**Comment by adrianthedev** [comment]
For some reason it tries to install Avo 2.44.

![CleanShot 2023-12-18 at 21 29 26@2x](https://github.com/avo-hq/avo/assets/1334409/df7ddedc-6fd3-4d0c-9fa8-b1cc76e60e50)


Were you able to run Avo 3?

**Comment by rctneil** [comment]
I can't even install it.  Bundling just fails.

**Comment by adrianthedev** [comment]
I can't figure it out with just this information 🤷

Try `bundle update avo` first.
Are you trying to upgrade from Avo 2 to Avo 3?

**Comment by rctneil** [comment]
Apologies Adrian!.  I don't really have any more info.

Basically I am installing Avo for the first time in this app.  I added the line to my `Gemfile` and tried to bundle. That's the error i'm getting.

Really sorry, If I had anything else to post here then I honestly would!

**Comment by rctneil** [comment]
Full Gemfile:

https://gist.github.com/rctneil/151fec87786c00e99cc5a8834fc8cae9

**Comment by adrianthedev** [comment]
ok. thanks for the Gemfile. that helped. I was blindfolded here.

Let me push an update.

**Comment by rctneil** [comment]
May I ask which part of the `Gemfile` helped?   It'll make my future Issue reporting better!

**Comment by adrianthedev** [comment]
All of it as I was able to run `bundle install` with it to get the error.

I fixed it here https://github.com/avo-hq/avo/pull/2193.
Tomorrow we'll release a new version with this fix.

**Comment by rctneil** [comment]
Gotcha!  Thanks.  Just successfully installed using the main branch.

**Comment by adrianthedev** [comment]
That's great.

Add this to your `Rakefile` to ensure that the assets will be compiled in production.

```ruby
Rake::Task["db:migrate"].enhance do
  Rake::Task["avo:build-assets"].execute
end
```
