### ISSUE TITLE
Pagy::OverflowError expected :page in 1..1; got 3

### ISSUE THREAD

**Issue by adrienpoly** [avo-hq/avo#2284]
### Describe the bug

getting this `Pagy::OverflowError expected :page in 1..1; got 3` error when combining pagination with dynamic filters

### Steps to Reproduce
1. Go to a resource with a dynamic filter
2. Navigate to page 3
3. Add a dynamic filter that will return a small set of results (user.email contains adrian@avohq.com)

### Expected behavior & Actual behavior
The page=3 params remains in the or it should be updated but is all case it should not crash the app

### System configuration
- 3.2.1

**License type**:

 - [ ] Community
 - [ ] Pro
 - [ x] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Similar issues https://github.com/avo-hq/avo/issues/2092, https://github.com/avo-hq/avo/issues/2076

**Comment by adrienpoly** [comment]
sorry didn't search prior to posting this issue it is the same indeed
