### ISSUE TITLE
Scope tooltips should not be the same as the title

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2285]
It's redundant.

![Image](https://github.com/avo-hq/avo/assets/1334409/759f1a56-20f8-4042-8361-7dcc9f85cbb3)

**Comment by PraveenShinde3** [comment]
@adrianthedev  on what page is this ?

**Comment by adrianthedev** [comment]
This feature is the [Scopes](https://docs.avohq.io/3.0/scopes.html) feature in avo-advanced.

**Comment by azhrhussain** [comment]
What it should be? @adrianthedev

**Comment by adrianthedev** [comment]
It should default to nothing. I fixed it in a commit yesterday.
