### ISSUE TITLE
Top of `show` view (`actions`, `filters`, `controls`, etc) disappears if no fields are rendered outside tabs.

### ISSUE THREAD

**Issue by JeremasPosta** [avo-hq/avo#2302]
### Describe the bug
> Top of `show` view (`actions`, `filters`, `controls`, etc) disappears if no fields are rendered outside tabs.

We are starting our migration to Avo 3. The more useful resource for us is one we actually tweaked a lot using `PanelComponents`.
As we choose to display the panels containing some custom views instead of the `fields` list, we hide _all_ the fields from the `show` view.
Now, this is making the `controls` render to vanish.

### Steps to Reproduce
Move all of your fields into a tab.
`hide_on: :show` any remaining field.
Go to resource's `Show` view.

### Expected behavior & Actual behavior

I would expect to the controls bar to be always rendered, as for Avo 2.
### Models and resource files

```ruby
# frozen_string_literal: true

class Avo::Resources::Patient < Avo::BaseResource # rubocop:disable Metrics/ClassLength
  self.title = :full_name
  self.show_controls = lambda {
    back_button label: 'Go back'
    actions_list
    edit_button label: 'Edit'
  }

  def fields
    field :id, as: :id, hide_on: :show  # This hides the controls, but I want them there.
    # field :id, as: :id                # This renders the controls, but I don't want this here.
    tabs do
      tab 'More info' do
        panel do
          field :account_status, as: :select, options: STATUSES
        end
      end
    end
  end

  def filters
    filter Avo::Filters::ActiveFilter
  end

  def actions
    action Avo::Actions::Reassign
  end
end
```
### System configuration
**Avo version**:

**Rails version**:
- 6.1.7.6

**Ruby version**:
- 3.0.6

**License type**:

 - [ ] Community
 - [X] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

https://github.com/avo-hq/avo/assets/60799999/bb225830-8968-4dfd-a181-a173cc141fe2

### Additional context

This is blocking us from continuing with the Avo3 upgrade.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@JeremasPosta this happens when the main panel (the one with the header that includes the title, description and controls) have no fields on it to render.

Maybe this section would clarify even more **https://docs.avohq.io/3.0/resource-panels.html** 

If not defined, the main panel will build itself by computing the visible fields, on your case there are no visible fields on show view.

This should work:

```ruby
# frozen_string_literal: true

class Avo::Resources::Patient < Avo::BaseResource # rubocop:disable Metrics/ClassLength
  self.title = :full_name
  self.show_controls = lambda {
    back_button label: 'Go back'
    actions_list
    edit_button label: 'Edit'
  }

  def fields
    main_panel do
      field :id, as: :id, hide_on: :show
    end
 
    tabs do
      tab 'More info' do
        panel do
          field :account_status, as: :select, options: STATUSES
        end
      end
    end
  end

  def filters
    filter Avo::Filters::ActiveFilter
  end

  def actions
    action Avo::Actions::Reassign
  end
end
```

Closing as completed, feel free to reopen if the issue persists

**Comment by JeremasPosta** [comment]
Hi @Paul-Bob , I was OOO, really sorry for the delayed response here.
I will give it a try later this week. Thanks a bunch!

**Comment by Paul-Bob** [comment]
No worries @JeremasPosta!

After trying let us know if you managed to fix it or the issue still persists

**Comment by JeremasPosta** [comment]
@Paul-Bob, everything works now, thank you!
