### ISSUE TITLE
Search bar is rendered event if the search class attribute is not defined

### ISSUE THREAD

**Issue by lpe** [avo-hq/avo#2305]
### Context
The search bar (local and global) is rendered event if the search class attribute is not defined
It also means I'm getting an error message to define ransack_attributes and ransack_associations
As temporary workaround I just set self.search = {} 
Ransack gem version : 4.1.1

### System configuration
**Avo version**: 3.2.2

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Hey @lpe I tested this on https://github.com/avo-hq/avodemo and the resource search is not visible.
You can try it on here https://avodemo.com/avo/resources/people.

Can you please confirm that you still see it?

Closing for now as we can't replicate it. Will reopen if it still persists.
