### ISSUE TITLE
conditional has_many field in def fields API will crash

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#2317]
```ruby
  def show_fields
   # normal field
    field :state, as: :text
   # condition for a has_many field using record
    if record.tests.size > 2
      field :tests, as: :has_many
    end
  end
```

if `record.tests.size` equals `1` the has_many field will be not rendered. fine. but if `record.tests.size` equals `3` the application will crash. The `record` / `@field` is `nil` at the time the has_many field renders in a turbo frame

the url `?turbo_frame=has_many_field_show_tests&view=show` will result in the error: ```undefined method `tests' for nil:NilClass```. 

![image](https://github.com/avo-hq/avo/assets/26464774/e36f4578-cd24-4c78-a09f-4615e0216f33)

The error went deeper into
[avo (3.2.3) app/controllers/avo/associations_controller.rb:103:in `set_attachment_resource']
![image](https://github.com/avo-hq/avo/assets/26464774/f88f306b-08a5-40a8-bd6c-c6f6a91c7f30)

Hope that helps. Maybe I miss something or this is not intended.

**Comment by FLX-0x00** [comment]
Also the following code is not working:

```ruby
def show_fields
    field :state, as: :text, visible: -> { record.state.present? }
    field :tests, as: :has_many
end
```

the `record` in the visilbe works fine but with the has_many "rerendering" the `record` is `nil` when loading the has_many field

**Comment by Paul-Bob** [comment]
@FLX-0x00 does this work as expected?

```ruby
def show_fields
    field :state, as: :text, visible: -> { resource.record.state.present? }
    field :tests, as: :has_many, visible: -> { resource.record.tests.size > 2 }
end
```

We enforce usage of `visible` block instead `if / else` on the fields declaration

**Comment by FLX-0x00** [comment]
Yeah this works but I thought using the IF statements directly in the def fields is the intended route on avo 3.

**Comment by FLX-0x00** [comment]
We are always try to make the code better and try to avoid multiple identical code lines

**Comment by Paul-Bob** [comment]
> We are always try to make the code better and try to avoid multiple identical code lines

Here are 2 examples on how to reuse field's argument(s):

```ruby
  def reusable_visible
    -> { resource.record.tests.size > 2 }
  end

  def show_fields
    field :state, as: :text, visible: reusable_visible
    field :tests, as: :has_many, visible: reusable_visible
  end
```

```ruby
def reusable_args
    {
      name: "Just an example",
      visible: -> { resource.record.tests.size > 2
    }
  end

  def show_fields
    field :state, as: :text, **reusable_args
    field :tests, as: :has_many, **reusable_args
  end
```

**Comment by FLX-0x00** [comment]
the reusable_visible will defintitely not work. we tried that. but the reusable args might work. we will give it a try. at the point the has_many renders into a turbo frame, the code gets evaluated again and fails as i described.

https://github.com/avo-hq/avo/issues/2317#issuecomment-1875994074

**Comment by Paul-Bob** [comment]
> the reusable_visible will defintitely not work.

@FLX-0x00 on my side it worked as expected, I tested it before putting the example.

> Inside the lambda, we have access to the [context](https://docs.avohq.io/3.0/customization.html#context) object and the current resource. The resource has the current record object, too (resource.record).

https://docs.avohq.io/3.0/field-options.html#field-visibility

#### `visible: -> { record.state.present? }` ✕
#### `visible: -> { resource.record.state.present? }` ✓

**Comment by FLX-0x00** [comment]
Thanks for your help! makes a lot more sense to us. Sadly the IF ELSE statements in the def fields is not intended

**Comment by Paul-Bob** [comment]
The `if / else` on the `def fields` can be evaluated in different circumstances with different variables and that lead to inconsistent behavior. Closing as completed
