### ISSUE TITLE
warning: already initialized constant ASSET_FILE

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2351]
### Describe the bug

A bunch of these warnings show up in our CI test logs after adding Avo. 
```
/home/runner/work/imagineclarity/imagineclarity/vendor/bundle/ruby/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:2: warning: already initialized constant ASSET_FILE
/home/runner/work/imagineclarity/imagineclarity/vendor/bundle/ruby/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:2: warning: previous definition of ASSET_FILE was here
/home/runner/work/imagineclarity/imagineclarity/vendor/bundle/ruby/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:4: warning: already initialized constant TAILWINDCSS_RAILS
/home/runner/work/imagineclarity/imagineclarity/vendor/bundle/ruby/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:4: warning: previous definition of TAILWINDCSS_RAILS was here
```

### Steps to Reproduce

Using bisection I could narrow down to this code:

```ruby
require_relative '../config/environment'
require 'rails/test_help'

class DummyTest < ActiveSupport::TestCase
  test "test 1" do
    MyApp::Application.load_tasks
  end

  test "test 2" do
    MyApp::Application.load_tasks
  end
end
```

`rails test` then produces this output:

```
/opt/homebrew/lib/ruby/gems/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:2: warning: already initialized constant ASSET_FILE
/opt/homebrew/lib/ruby/gems/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:2: warning: previous definition of ASSET_FILE was here
/opt/homebrew/lib/ruby/gems/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:4: warning: already initialized constant TAILWINDCSS_RAILS
/opt/homebrew/lib/ruby/gems/3.2.0/gems/avo-3.2.3/lib/tasks/tailwindcss_rails.rake:4: warning: previous definition of TAILWINDCSS_RAILS was here
```

If I delete avo from the Gemfile, remove the initializer, and remove the Avo engine from routes.rb, the warnings don't show up any more. The show up again as soon as the Avo gem is reintroduced (even if no Avo initializer or engine is present).

### Expected behavior & Actual behavior
No warning logs during tests when adding Avo.

### System configuration
**Avo version**: 3.2.3

**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (does not lead to user-facing issues but pollutes test logs.)

**Comment by Paul-Bob** [comment]
Doing a quick search some folks say that `bundle clean --force` and then `bundle update` fixed some similar issues. I've never noticed that warnings. Trying to reproduce

**Comment by sedubois** [comment]
I did see that same recommendation but it hadn't helped. Perhaps I did something wrong though.
