### ISSUE TITLE
has_and_belongs_to_many does not find the model if option class_name is specified

### ISSUE THREAD

**Issue by nicolascochin** [avo-hq/avo#236]
Hi, 

Imagine you have a resource `has_and_belongs_to_many` with option `class_name`
At the moment, the linked resource can't be found. 
Resource should be found the same way the `has_many` field

https://github.com/avo-hq/avo/blob/779951cec595656fdc8fd7935da27ab9cd3f5ab9/lib/avo/app/fields/has_and_belongs_to_many.rb#L43

it should be like this 
https://github.com/avo-hq/avo/blob/779951cec595656fdc8fd7935da27ab9cd3f5ab9/lib/avo/app/fields/has_many.rb#L45-L46

Regards,

Nicolas

**Comment by adrianthedev** [comment]
Yup. Makes sense! Dropping in a patch in an hour ⏰

**Comment by adrianthedev** [comment]
If your resource name differs from your model name like below, you may also specify the `@model` attribute on your resource. This is how Avo tries to infer the model for the resource at first.

Example:

Your model is called `User` and your Avo resource is called `People`, you can add the `@model = User` to the resource

```ruby
# app/avo/resources/people
module Avo
  module Resources
    class People < Resource
      def initialize
        @title = :name
        ...
        @model = User
      end
```

**Comment by adrianthedev** [comment]
https://github.com/avo-hq/avo/releases/tag/v0.4.9 contains this fix.

Let us know if this fixes your issue.

Thank you ✌️

**Comment by nicolascochin** [comment]
All good! 
Thank you
