### ISSUE TITLE
Hide "Create" action

### ISSUE THREAD

**Issue by rafaeliga** [avo-hq/avo#2363]
### Context

Is there a way to simply hide create action?

I see that we have a way to customize that with "index_tools" but I just want to hide it instead.

### System configuration
**Avo version**: 3.2.1

**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
You're looking for the authorization feature and the `create?` method.
[Docs](https://docs.avohq.io/3.0/authorization.html#create)

Closing for now. Feel free to reopen.

**Comment by rafaeliga** [comment]
Thanks @adrianthedev !

So no option for community version?

**Comment by adrianthedev** [comment]
You can override `Avo::Views::ResourceIndexComponent` on your end and apply your changes.
Just beware that that component is considered private API and we might change it in the future.

**Comment by Paul-Bob** [comment]
Resource [custom components](https://docs.avohq.io/3.0/resources.html#self_components) becomes handy when want to override a component only for a specific view and on specific resources.
