### ISSUE TITLE
Test out cuprite to see if tests are more sturdy

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2365]
Let's see if this fixes our flaky tests issue.

https://github.com/rubycdp/cuprite

**Comment by Paul-Bob** [comment]
> Let's see if this fixes our flaky tests issue.

Already running on cuprite, it didn't really fixed the flaky tests but[ this commit ](https://github.com/avo-hq/avo/pull/2371/commits/05f5a6053f8045e3acc9884f88341185115de341)made the flaky tests to retry
