### ISSUE TITLE
Unable to visit any resource index view

### ISSUE THREAD

**Issue by Guv0** [avo-hq/avo#2377]
### Describe the bug
Since upgrading to Avo 3.3, visiting any resource index view raises `uninitialized constant Avo::Advanced::Scopes` from `Avo::Views::ResourceIndexComponent#scopes_list`

### Steps to Reproduce
Try to render any resource index view.

### Expected behavior & Actual behavior
View renders successfully

### System configuration
**Avo version**: 3.3

**Rails version**: 7.1.2

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Please check your `Gemfile.lock` file. My hunch is that you are not on 3.3.

Try `bundle update avo-advanced avo`

**Comment by adrianthedev** [comment]
![](https://media.giphy.com/media/jc2PkKKr3clTBekMzn/giphy.gif)

Did that work @Guv0?

**Comment by adrianthedev** [comment]
And `avo-advanced` (in `Gemfile.lock`)?

**Comment by Paul-Bob** [comment]
Avo advanced is not getting updated, can you share how do you declare the avo gems in the gemfile?

**Comment by Guv0** [comment]
```
gem "avo", "~> 3.3"
gem "avo-advanced", "~> 1.0", source: "https://packager.dev/avo-hq/"
```

**Comment by Paul-Bob** [comment]
Remove the lock (`"~> 1.0"`) on the avo-advanced or change it to `3.3`. This should solve the issue

**Comment by Guv0** [comment]
That worked, thanks!

**Comment by Paul-Bob** [comment]
Anytime @Guv0! :muscle:

**Comment by pierry01** [comment]
Thanks for that !!!

> Remove the lock (`"~> 1.0"`) on the `avo-advanced` or change it to `3.3` then `bundle update avo-advanced`. This should solve the issue
