### ISSUE TITLE
Using Avo inside a Rails Engine

### ISSUE THREAD

**Issue by nicholaswellens** [avo-hq/avo#2378]
### Context
This is not necessarily an issue. I'm posting here to share information, and it could help someone who has the same (probably rare use case) as us. Note that this is considering Avo 3. We are creating a Rails Engine which uses Avo (although Avo installation and configuration is inside the main app). It took a bit of time to make it work as Avo resources and custom fields, defined in the engine, were not working out of the box:

- Resources: from what I understand, Avo needs to eager load resources on boot, in order to define the necessary routes. This is done with `Rails.autoloaders.main.eager_load_namespace(Avo::Resources)` (`avo/resources/resource_manager.rb`). However, it seems this method does not load files of external source trees (see [zeitwerk documentation](https://github.com/fxn/zeitwerk#eager-load-directories)), and thus does not load the resources inside our engine. We therefore explicitly need to load our engine-defined resources in our  `engine.rb` (see screenshot)

- Custom Fields: these were not working in the engine because the fields were not correctly being autoloaded in the engine (because of the Avo 3 naming convention). After digging through Avo configuration, we found that Avo handles this by adding the `Avo` namespace to the autoload directory. This works for the main app, but does not work for other engines. We thus needed to explicitly add it ourselves. (see screenshot)

`lib/my_engine/engine.rb`

![image](https://github.com/avo-hq/avo/assets/18333645/8f1c649b-3bdf-4261-8851-2c402b62bf94)

### System configuration
**Avo version**: 3.2.3

**Rails version**: 7.12

**Ruby version**: 3.0.2

**License type**

 - [x] Community
 - [ ] Pro

**Comment by adrianthedev** [comment]
Hey @nicholaswellens, this is interesting.
Yes, we are adding the Avo configuration files differently in the autoloader. If we were using the regular autoloading pattern we would loose the `Avo` namespace (eg: instead of `Avo::Resources::User` we would have `Resources::User`).

I'd love to see more of how you're using Avo's resources in your engine.
Are you pulling the UI too? is this an "open app" that we could see?

**Comment by nicholaswellens** [comment]
@adrianthedev It is an internal engine, but the idea is really simple: we define common resources and fields in an engine that will need to be shared over several apps. The resources will be shown in the main app _as if they were written in the main app_, with the normal Avo UI etc. The engine is unmountable to keep the route namespace of the main app. We override models and Avo resources of the main apps when needed. Time will tell if this is going to be a practical approach.

**Comment by adrianthedev** [comment]
Nice!
I'd love to see the code one day. I always search for when folks do new things with the framework.
