### ISSUE TITLE
Download action without refresh lead to unexpected behavior 

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2385]
### Describe the bug

Download action without refresh lead to unexpected behavior.

From here -> https://discord.com/channels/740892036978442260/1197846489163112449/1197912362213195847

### Steps to Reproduce
1. Go to https://main.avodemo.com/avo/resources/projects
2. Select some records
3. Click on Actions -> Export csv
4. W8 download to complete 
5. Repeat step 3
6. Notice weird behavior where URL changes and background turns white

[action_double_download.webm](https://github.com/avo-hq/avo/assets/69730720/b8341243-0837-4c7a-b7c3-a8189030dcff)

**Comment by mid** [comment]
Encountered the same issue.

Also, downloading the binary files (e.g., PNG images or PDF images) generated by Avo Actions no longer works after upgrading from 3.2 to 3.3 :( The downloaded files are corrupted.
