### ISSUE TITLE
Binary files generated by Avo Action are corrupted (after upgrade to 3.3)

### ISSUE THREAD

**Issue by mid** [avo-hq/avo#2392]
Related https://github.com/avo-hq/avo/issues/2385

### Describe the bug
Binary files generated by Avo Action are corrupted.

### Steps to Reproduce
```ruby
class Avo::Actions::DownloadFile < Avo::BaseAction
  self.name = "Download"
  self.visible = -> { view == :show }
  self.no_confirmation = true

  def handle(**args)
    file = File.open("/path/to/local/pdf")
    download file.read, "dummy-file.pdf"
  end
end
```

### System configuration
**Avo version**:
- avo-advanced (3.3.0)

**Rails version**:
7.1.3

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
This might be related to our recent refactor https://github.com/avo-hq/avo/pull/2269.
@Paul-Bob could you please have a look?
