### ISSUE TITLE
One-command install not working

### ISSUE THREAD

**Issue by Bergrebell** [avo-hq/avo#2405]
### Describe the bug
running `bin/rails app:template LOCATION='https://avohq.io/app-template' ` on a fresh install of a rails 7.1. application fails with:

```
bin/rails aborted!
SyntaxError: https://avohq.io/app-template:2: syntax error, unexpected '<'
<!DOCTYPE html>
^
https://avohq.io/app-template:3: syntax error, unexpected '<'
<html lang="en" class="bg-whit...
^
https://avohq.io/app-template:3: syntax error, unexpected `class', expecting end-of-input
<html lang="en" class="bg-white antialiased h-full...
                ^~~~~

Tasks: TOP => app:template

```

and visiting the template [linked in the docs](https://docs.avohq.io/3.0/installation.html#_1-one-command-install) shows an error page.

**Comment by adrianthedev** [comment]
https://railsbytes.com/ is down.
We should host that template on our own servers. Will do that very soon.
Thank you @Bergrebell!

**Comment by adrianthedev** [comment]
For reference, this is the code that was in the template

```
gem "avo", ">= 3.2"
Bundler.with_unbundled_env { run 'bundle install' }
run "rails generate avo:install"
```

One can get the same results by running

```bash
bundle add "avo"
rails generate avo:install
```

**Comment by Bergrebell** [comment]
yeah, i could install it via the manual installation already. i just thought it would be good to let you guys know! :)
