### ISSUE TITLE
Pundit Policy not applying to record

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#2408]
### Context
I have added pundit action_policy.rb, the corresponding application_controller policy. and a resource policy but it doesn't seem to be applying.

### System configuration
**Avo version**: 3.3.0

**Rails version**: 7.1.3

**Ruby version**: 3.2.3

**License type**

 - [x] Community
 - [] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<img width="3006" alt="image" src="https://github.com/avo-hq/avo/assets/48605824/8748a8aa-7834-4520-a210-776070225f8b">

**Comment by Paul-Bob** [comment]
@jmarsh24 [Authorization](https://docs.avohq.io/3.0/authorization.html) is a pro feature.

**Comment by jmarsh24** [comment]
@Paul-Bob Is there a different way to remove the edit button. I want to have this be a completely readonly record. It's a hobby project of mine.

**Comment by jmarsh24** [comment]
<img width="2998" alt="image" src="https://github.com/avo-hq/avo/assets/48605824/908dcc1e-93fd-4f54-bc8d-00949a8b73a0">

It's also not clear why the export_csv is greyed out.

**Comment by Paul-Bob** [comment]
Maybe overriding the components that renders that controls, I would not suggest that unless you want to learn and maintain (what you override) some Avo internals on your own.

There is also customizable controls but for advanced licenses https://docs.avohq.io/3.0/customizable-controls.html#customizable-controls
