### ISSUE TITLE
avo:js:install fails

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2411]
### Describe the bug
Running `bin/rails generate avo:js:install`fails:

```sh
Avo advanced 3.3.1
Add default app/javascript/avo.custom.js
Could not find "/Users/jetienne/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/avo-3.3.1/lib/generators/avo/templates/js/avo.custom.js" in any of your source paths.
```

### System configuration
**Avo version**:
3.3.1

**Rails version**:
7.1.3

**Ruby version**:
3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
I think the template is not packed on build because we ignore that file name [here](https://github.com/avo-hq/avo/blob/main/avo.gemspec#L34)...

`avo.custom.js` should be ignored from build directory but not from templates directory.

**Comment by Paul-Bob** [comment]
As a workaround you can create the template manually under that path until we fix it, here is the [original file](https://github.com/avo-hq/avo/blob/main/lib/generators/avo/templates/js/avo.custom.js)
