### ISSUE TITLE
Rails.cache used instead of Avo.cache_store

### ISSUE THREAD

**Issue by smathieu** [avo-hq/avo#2412]
### Describe the bug
We're seeing Avo caching to our Rails.cache (redis) store, even when the Avo cache store has been set to a NullStore.

### Steps to Reproduce

1. Set in `config/initializer/avo.rb`

```ruby
  if Rails.env.development?
    config.cache_store = ActiveSupport::Cache::NullStore.new
  end
```

2. Browse to an index page.

=> Cache keys are written to Redis.
<img width="331" alt="Screenshot 2024-01-25 at 10 04 10 AM" src="https://github.com/avo-hq/avo/assets/148622/8150e445-d493-49c6-92d9-d0e518834b73">

### Expected behavior & Actual behavior
The AVO cache store should be used everywhere.

### System configuration
**Avo version**: 3.1.1

**Rails version**: 7.0.8

**Ruby version**: 3.3

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

I think this is caused by the use of (cache_if)[https://github.com/avo-hq/avo/blob/f0674541d01bd62401c3f0b50eebe21f80551124/app/components/avo/index/resource_grid_component.html.erb#L6] that is a Rails helper, which implicitly uses Rails.cache.

#### Impact

This is causing subtle issue for us in development & production when changing resources files. We then have to manually clear the cache for all avo view by flushing specific Redis keys. 

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yes, that is correct.

We should mention the usage for the `cache_store` in the initializer.
We use that in the license-checking process and not for the regular caching that Rails does (e.g.: partial caching).

You have control over that in `development.rb` through `config.cache_store = CACHE_STORE`. More details on how to handle that [here](https://guides.rubyonrails.org/caching_with_rails.html).

If, however, you're looking to stop the caching of the table rows in Avo you can use [this setting](https://docs.avohq.io/3.0/customization.html#cache-resources-on-the-index-view) to turn it off.

**Comment by adrianthedev** [comment]
> This is causing subtle issue for us in development & production when changing resources files. We then have to manually clear the cache for all avo view by flushing specific Redis keys.

The cache flushing there should be "automatically" handled for you as it uses an md5 of the resource file and the `updated_at` of a record.

**Comment by smathieu** [comment]
Thanks.

If this is annoying everyone else, it's possible to have a different caching system for Avo than the rest of that app.

```ruby
Rails.configuration.to_prepare do
  # In dev, don't cache AVO controller like the rest of our app
  if Rails.env.development?
    Avo::ApplicationController.cache_store = ActiveSupport::Cache::NullStore.new
  elsif Rails.env.production?
    Avo::ApplicationController.cache_store = ActiveSupport::Cache::MemoryStore.new
  end
end

**Comment by adrianthedev** [comment]
Avo is using the `cache_if` helper internally.

I don't know how to set that up easily, just for Avo. If you find a solution we'll gladly add it to the framework.

**Comment by adrianthedev** [comment]
Oh, is that how you do it? That's a clever solution!
Let's use that!

**Comment by adrianthedev** [comment]
@Paul-Bob can we add this somewhere in the docs too?
