### ISSUE TITLE
`<mark>` tag persists when selecting on a belongs association with searchable true

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2416]
### Describe the bug

[mark_persist_bug.webm](https://github.com/avo-hq/avo/assets/69730720/d1d01ac5-6ea5-45df-867a-97d4af04f707)

## Approach
Remove the `<mark>` and `</mark>` from the string after selecting the option.

**Comment by adrianthedev** [comment]
Let's fix this one ASAP please.
