### ISSUE TITLE
Multitenancy and Pundit compatibility

### ISSUE THREAD

**Issue by iyerushalmi** [avo-hq/avo#2421]
### Context
We use acts_as_tenant gem to handle multitenancy, and Pundit to handle authorization. We have followed the recommendations in the documentation for setting up both of these, including setting up a concern for the multitenancy which we include into Avo's application_controller via initializer. However, this approach initializes the tenant AFTER pundit is initialized and we are unable to access tenant information in the Pundit policies. In some cases we need to access this information in Pundit, and it would therefore be preferable if we had some way of activating the multitenancy prior to Pundit.

One example of when we would need tenant information in Pundit is as follows: Users and Accounts have and belong to many. User can have different roles, depending on which account they are logged into. In order to know which role applies to the current account, we need access to the tenant information.

Our current workaround is to set up the Avo application_controller.rb hard copy in our repo, however this will likely cause breaking changes every upgrade and is not ideal.

**Comment by adrianthedev** [comment]
Can you please share the changes that you have in the overridden Avo application controller that help you in this use case?
Do you, and if so, how do you pass the user **and** the account to the pundit policy. AFAIK it supports only one "user" object

We definitely want to make supporting this user as easy as possible.

**Comment by iyerushalmi** [comment]
Yes, I copied the application_controller.rb and simply put the multitenancy functionality at the very start so that it initiates prior to Pundit. I am including the start of the overridden controller below. After doing this, I can access acts_as_tenant info such as ActsAsTenant.current_tenant inside of my Pundit policies.

```
module Avo
  class ApplicationController < ::ActionController::Base

    ## ADDED BY ME
    set_current_tenant_through_filter
    before_action :set_current_account

    def set_current_account
      if user_signed_in?
        if params[:account_id].present?
          selected_account = Account.find(params[:account_id])

          # Authorization check
          if current_user.accounts.include?(selected_account)
            session[:account_id] = selected_account.id
          else
            # Handle unauthorized access, e.g., redirect to a safe page with an error message
            redirect_to "/resources/accounts", alert: "You are not authorized to access this account."
            return
          end
        end

        account_id = session[:account_id] || current_user.accounts.first.id
        current_account = Account.find(account_id)
        set_current_tenant(current_account)
      end
    end


    ### END ADDED BY ME
    ### CONTINUING TO DEFAULT CONTROLLER

    if defined?(Pundit::Authorization)
      Avo::ApplicationController.include Pundit::Authorization
    elsif defined?(Pundit)
      Avo::ApplicationController.include Pundit
    end

    ### DEFAULT CONTROLLER CONTINUES TO END

end
```

**Comment by adrianthedev** [comment]
Could you go back to the concern pattern instead of overwriting the `ApplicationController` and use `prepend_before_action` instead of `before_action`?
It seems that adds it before all actions.

**Comment by iyerushalmi** [comment]
Yes that seems to work. I didn't notice it saying that in the docs before - I guess I didn't review it carefully enough. Thank you
