### ISSUE TITLE
Searchable polymorphic belongs_to isn't searchable

### ISSUE THREAD

**Issue by joshfester** [avo-hq/avo#2441]
### Describe the bug
I'm trying to add a searchable polymorphic belongs_to field, but can't get it to be searchable

### Steps to Reproduce
1. Add a searchable polymorphic belongs_to field
2. Go to new/edit page for the resource

### Expected behavior & Actual behavior
I would expect to see a searchable field, but instead see a dropdown that loaded all ProductBrand models

### Models and resource files
```ruby
class Avo::Resources::CmsPage < Avo::BaseResource
  self.model_class = ::Cms::Page

  def fields
    field :id, as: :id

    field :resource,
      as: :belongs_to,
      polymorphic_as: :resource,
      types: [::ProductBrand],
      searchable: true,
      show_on: :new

    field :sections, as: :code, language: "javascript", format_using: -> {
      if value.present?
        JSON.pretty_generate(value.as_json)
      end
    }
  end
end
```

and 

```ruby
class Avo::Resources::ProductBrand < Avo::BaseResource
  self.search = {
    query: -> { query.ransack(title_i_cont: params[:q]).result(distinct: true) }
  }

  def fields
    field :id, as: :id

    field :status, as: :select, enum: ::ProductBrand.statuses, sortable: true
    field :title, as: :text, sortable: true

    field :cms_page, as: :has_one
  end
end
```

### System configuration
**Avo version**: 3.3.3

**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
I noticed you're using the Community tier.

The [`searchable` feature](https://docs.avohq.io/3.0/associations/belongs_to.html#searchable) is a Pro tier feature.

![CleanShot 2024-02-02 at 13 57 57@2x](https://github.com/avo-hq/avo/assets/1334409/58f394ef-c3b5-494e-b650-13c3141f8896)

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen.

**Comment by joshfester** [comment]
Oh wow totally missed that. Thank you!
