### ISSUE TITLE
Association has_many not ordering correctly

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#2443]
I have a Visit model and a Cycle model.  A Visit has_many Cycles and a Cycle belongs_to a Visit.

I have these showing up as a has_many field type on my Visit Show view. I wish to add an order to them of position: :asc, but it just refuses to do so.

I see in my log:

`SELECT "cycles".* FROM "cycles" WHERE "cycles"."visit_id" = $1 ORDER BY cycles.created_at desc LIMIT $2 OFFSET $3`

My Cycle resource has:

```
  self.index_query = -> {
    if params[:via_association] == 'has_many'
        query.order(position: :asc)
    else
        query.order(date: :desc, position: :asc)
    end
  }
```

This works flawlessly on the Index view, but when being shown via an association, the order just doesn't take affect and seems to order by created_at as per the query shown.

**Comment by Paul-Bob** [comment]
Having a quick look into this, the `index_query` never gets executed when the table index is rendered from an association.

https://github.com/avo-hq/avo/blob/edb3a18aac8a15fd67be51e4758db12f0335df63/app/controllers/avo/base_controller.rb#L29

We should either apply it on the above line or on the `Avo::AssociationsController` when generating the query.

**Comment by rctneil** [comment]
@Paul-Bob Thanks for taking a look!

Glad I wasn't doing something wrong for a change!   Do you have an ETA on a fix for this one?

**Comment by Paul-Bob** [comment]
@rctneil forgot to mention that there is an workaround:

https://docs.avohq.io/3.0/associations/has_many.html#scope

You can scope the association field

**Comment by Paul-Bob** [comment]
Just opened an issue with a feature request on this one.

https://github.com/avo-hq/avo/issues/2445

We're not prioritizing it right now since there's a solid workaround. Any PR regarding this issue is welcomed!

**Comment by rctneil** [comment]
@Paul-Bob thanks for the workaround! Works perfectly!
