### ISSUE TITLE
belongs_to use_resource does not accept a block

### ISSUE THREAD

**Issue by jcn** [avo-hq/avo#2455]
### Describe the bug

The `use_resource` field option does not take a block, which means that we can't dynamically set this based on conditions about a particular resource/record (i.e. I have 2 "User" resources, and I'd like to link to different ones from an associated object depending on whether the user is an admin or not.

https://ptb.discord.com/channels/740892036978442260/1204490856015331368

### Steps to Reproduce

This does not seem to work:

```
field :user, as: :belongs_to, use_resource: -> { resource.record.user.is_admin? ? Avo::Resources::Admin : Avo::Resources::User }
```

### System configuration
**Avo version**: 3.3.0

**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello! Indeed `use_resource` should be able to receive a Proc.

As a workaround until that's implemented, since `def fields` are a resource's instance method you are able to access the `current_user` directly.

```ruby
def fields
    comments_resource = current_user.is_admin? ? Avo::Resources::Comment : Avo::Resources::PhotoComment

    field :comments, as: :has_many, use_resource: comments_resource
end
```

**Comment by Paul-Bob** [comment]
You also can access `record` but be aware that `record` is not always there, for example on index views, so make sure you use a safe navigation or a presence check

**Comment by Paul-Bob** [comment]
Closing in favor of [feature request](https://github.com/avo-hq/avo/issues/2457)

**Comment by adrianthedev** [comment]
@jcn do you see a difference between the block approach and the ternary approach?
Because if there isn't one, I'd just chuck this to "ternary is the way".
