### ISSUE TITLE
avo-pro/avo-menu requires Ruby 3.1

### ISSUE THREAD

**Issue by apauly** [avo-hq/avo#2458]
I just installed Avo Pro in an existing app running Ruby 3.0 which is the minimum Ruby version for Avo 3 according to the [docs](https://docs.avohq.io/3.0/installation.html). When I try booting the app, I get the following syntax error:

```
gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': gems/avo-menu-3.3.4/lib/avo/menu/renderable.rb:6: syntax error, unexpected ','

    super(renderable:, **kwargs)
```

The [hash value omission](https://bugs.ruby-lang.org/issues/14579) is only available since Ruby 3.1. It seems that this is the only issue with Ruby 3.0 as the app is booting as soon as I fix that one in the source directly.

### Steps to Reproduce
1. Add avo-pro to an app running Ruby 3.0
2. bundle install
3. Try booting the app

### Expected behavior & Actual behavior
Expected:  Avo 3 supports Ruby >= 3.0
Actual:  Avo 3 only supports Ruby >= 3.1

### System configuration
**Avo version**: 3.3.4

**Rails version**: 7.0.8

**Ruby version**: 3.0.2

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @apauly.
Yes, it was an oversight on our end to use the hash omission feature when we specified we support 3.0.
I think we have it in other places as well, not just `avo-menu`.

Considering that [Ruby 3.0 is EOL](https://endoflife.date/ruby) in two months, would you be open to upgrading to 3.1?
I feel it's easier (and a step forward) just to update the docs to show that we support 3.1 than to refactor all that code.

**Comment by apauly** [comment]
Hey @adrianthedev,
thanks for your quick feedback! I was not aware of the EOL being in two months already. Makes sense to move forward instead 👍
