### ISSUE TITLE
Avo::Advanced::Scopes module not loading, causing all index views to fail.

### ISSUE THREAD

**Issue by calebuharrison** [avo-hq/avo#2461]
### Describe the bug
After upgrading Avo to the latest version, all of my index views for resources raise an error:

![CleanShot 2024-02-07 at 11 30 15](https://github.com/avo-hq/avo/assets/3103806/96cbb750-a4d4-4a69-97ea-fe3ff340a6e8)

In the console I can verify that there isn't a `Scopes` module loaded under the `Avo::Advanced` module.

### Expected behavior & Actual behavior
I expect that the `Avo::Advanced::Scopes` module is loaded, but it is not.

### Models and resource files
This is happening for all of my resources.

### System configuration
**Avo version**: 3.3.5

**Rails version**: 7.1.3

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context
This application isn't making use of Avo's resource scopes yet.

<details>
<summary>Stack Trace</summary>

![CleanShot 2024-02-07 at 11 44 03](https://github.com/avo-hq/avo/assets/3103806/d66c7ccd-bea7-4fc3-b54e-f7345e027756)

</details>

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @calebuharrison can you ensure you're using the latest `avo` and `avo-advanced`?
`bundle update avo avo-advanced`
I see `avo` at 3.3.5, but not sure about avo-advanced.

We moved scopes from the pro gem to advanced.

I wasn't able to reproduce it locally on the https://github.com/avo-hq/avodemo app. I removed all the scopes and ran the app.

**Comment by calebuharrison** [comment]
Running `bundle update avo avo-pro avo-advanced` I'm left with these versions:

> Using avo 3.3.5
Using avo-dynamic_filters 0.5.19
Using avo-menu 3.3.5
Using avo-dashboards 3.3.5
Using avo-pro 3.3.5
Using avo-advanced 0.1.65

Sorry, should have included all of these in the description above.

**Comment by adrianthedev** [comment]
Oh. I see the issue. avo-advanced is `0.1.65`.

Your Gemfile should look something like this for avo entries.

```ruby
# Avo Advanced
gem "avo", ">= 3.3.0"
gem "avo-advanced", ">= 3.3.0", source: "https://packager.dev/avo-hq/"
```

We started to release all gems with the same version. so all should be 3.3.5

**Comment by calebuharrison** [comment]
> We started to release all gems with the same version. so all should be 3.3.5

Good to know! Alright, nothing to see here. Thanks for the help!

**Comment by adrianthedev** [comment]
No worries. It happens.
Nice to see you're still playing with Avo.
Thanks!
