### ISSUE TITLE
`avo-advanced` depends on `pg`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2476]
### Describe the bug

This dependency chain makes it impossible for users to use Avo without the `pg` gem.
Let's think about a solution and remove that dependency chain.

![CleanShot 2024-02-13 at 21 58 40@2x](https://github.com/avo-hq/avo/assets/1334409/b7549507-65c3-4b71-9c90-2cedf92ec73a)

**Comment by adrianthedev** [comment]
- [ ] let's remove that dependency requirement
- [ ] add that to the docs
- [ ] add it as a breaking change
- [ ] let's check where we use it and notify about it when missing or hide that filter/conditions
- [ ] let's create an app that uses sqlite, and run some light tests on it on CI

**Comment by Paul-Bob** [comment]
@adrianthedev about `let's create an app that uses sqlite, and run some light tests on it on CI` any suggestion? I think several dummies will change a bit our CI scripts because we'll need different gemfiles for each dummy and a way to trigger it.
