### ISSUE TITLE
Allow proc on actions name

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2496]
### Feature

Action `self.name` option should allow proc format

Right now this is the output:
`self.name = -> { "Dummy action #{arguments[:some_argument]}" }`
![image](https://github.com/avo-hq/avo/assets/69730720/1f843111-53cc-4480-a99e-b60e9bf08262)

**Comment by Paul-Bob** [comment]
https://discord.com/channels/740892036978442260/1138182212655788054/1209362769598619678

**Comment by adrianthedev** [comment]
Also here
https://discord.com/channels/740892036978442260/1211968358975803454
