### ISSUE TITLE
Timezone discrepancy on datetime fields

### ISSUE THREAD

**Issue by krzykamil** [avo-hq/avo#2510]
### Describe the bug
I noticed that without setting the timezone, it displayed a different time than saved in database (supposedly using browser settings by default)
So I've set up the fields like:
 ```
    field :start_time, as: :date_time, timezone: "UTC"
    field :end_time, as: :date_time, timezone: "UTC"
```
And in the show and index views it was correct

But when entering edit, the field value is different again (1 hour difference, CEST sits in the input value and UTC is supposed to be displayed it is in data attributes)
It seems that the timezone setting is not applied to the input field

Checking the field value in the hidden input it is in CEST, but regular JS conversion to UTC does return the correct value, but the field does not

### Steps to Reproduce
1. Create date_time
2. Add timezone UTC
3. Create a record (this happens both when record is created from avo and from the regular app)
4. Compare the hours in show/index view to the edit field value. There should be a difference 

### Expected behavior & Actual behavior
The values should always be the same, timezone setting should be applied always. It seems it is not applied in the edit

### Models and resource files
```ruby
    field :start_time, as: :date_time, timezone: "UTC"
    field :end_time, as: :date_time, timezone: "UTC"
```
The timezone is not set in avo config file. That is actually a different issue, cause when I've set up UTC there it simply did not take effect and always displayed CEST.

### System configuration
**Avo version**:
3.3.3

**Rails version**:
7.1.3

**Ruby version**:
3.2.2

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![image](https://github.com/avo-hq/avo/assets/25006471/2955e0a8-f317-48ed-9a7f-d8faa5177f21)
![image](https://github.com/avo-hq/avo/assets/25006471/f052bf22-a41b-4974-ad28-eb18ea695f11)

#### Impact
This is a very important field where hours and minutes matter a lot, but for now it can be explained to the admins that they need to accounts for the time zone. Also I can just create a custom field that replaces this one for the time being.

 - [] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

I can create a workaround in the form of a custom field.

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by krzykamil** [comment]
Temporary solution I am using is:
run
```
bin/rails generate avo:field my_date_time
```

Use the basic, default field for datetime

```erb
#app/components/avo/fields/my_date_time_field/edit_component.html.erb
<%= field_wrapper **field_wrapper_args do %>
  <%= @form.datetime_field @field.id, class: classes("w-full"), placeholder: @field.placeholder, disabled: disabled?  %>
<% end %>
```

And just use my_date_time instead of datetime. It works automatically.

**Comment by Paul-Bob** [comment]
Thanks for sharing the temporary solution @krzykamil.

We'll have a look and check what's causing this weird behavior

**Comment by Paul-Bob** [comment]
@krzykamil can you please confirm if it's fixed on last version?
