### ISSUE TITLE
When a field is marked as filterable, when its hidden from index view, error is thrown while filtering

### ISSUE THREAD

**Issue by giedriusr** [avo-hq/avo#2511]
### Describe the bug
When we have a field which is filterable, but it is hidden from the index page, an error is thrown.
Even your demo page is not working: https://main.avodemo.com/avo/resources/teams?filters[description][contains][]=hello

### Steps to Reproduce
1. Add an existing field of a model to avo resource, for instance:
```ruby
# Avo resource of your active record model
field :my_date, as: :date, name: "Date", hide_on: [:index, :show, :edit, :new], filterable: true
```
2. Load index page of this resource
3. Click on filter and select my_date
4. Pick random date and submit
5. See error

To make it work, I have to do this:
```ruby
# remove :index from hide_on array
field :my_date, as: :date, name: "Date", hide_on: [:show, :edit, :new], filterable: true
```

### Expected behavior & Actual behavior
It should filter by selected date, error thrown instead.

### System configuration
**Avo version**: 3.3.6

**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**License type**:
 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
<img width="1778" alt="image" src="https://github.com/avo-hq/avo/assets/210713/0efeeab3-6fdb-446f-aa15-234a8b171b31">
<img width="481" alt="image" src="https://github.com/avo-hq/avo/assets/210713/a48311b8-552a-4451-a009-c4f8f821f405">
<img width="633" alt="image" src="https://github.com/avo-hq/avo/assets/210713/cbf7c305-c37b-45f8-9ac4-b8dc6b738087">

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Thanks for the report @giedriusr.

Closing this since is a duplicated of https://github.com/avo-hq/avo/issues/2490 and @gabrielgiroe1 already fixed it.

This fix will be included on the next release.
