### ISSUE TITLE
Same association with different scopes.

### ISSUE THREAD

**Issue by ricvillagrana** [avo-hq/avo#2513]
### Feature
Same association with different scopes.

I need to show a Project with its tasks, but these tasks could be Bugs, Feature, or Refactor.

Currently, I am trying to do this.
```
    tabs do
      field :tasks, as: :has_many, name: 'All Tasks'
      field :tasks, as: :has_many, name: 'Bugs', scope: -> { query.bugs }
      field :tasks, as: :has_many, name: 'Features', scope: -> { query.features }
      field :tasks, as: :has_many, name: 'Refactors', scope: -> { query.refactors }
    end
```

It does not show an error, but all tabs have the first query, which in this case is `all`.

### Current workarounds
None.

**Comment by Paul-Bob** [comment]
This issue fallback to a more general one. Fields with same ID.

Avo uses the field ID (`:tasks`) in this example. When rendering the `field :tasks, as: :has_many, name: 'Features', scope: -> { query.features }` and searching for a `:tasks` field the first one will be targeted `field :tasks, as: :has_many, name: 'All Tasks'` this leads to all tabs being addressed with the first field. 

Possible approaches:

# 1

- [ ] Make field ID unique to avoid silent errors like this one and others reported and raise an error when detect multiple fields with same ID with a link to documentation with a brief explication.
- [ ] Implement an `association` option on associations fields that will be field ID as default or you can set it, this will make possible this API:

```ruby
tabs do
  with_options as: :has_many, association: :tasks do
    field :all_tasks
    field :bugs, scope: -> { query.bugs }
    field :features, scope: -> { query.features }
    field :refactors, scope: -> { query.refactors }
  end
end
```

# 2

Keep allowing multiple fields with the same ID and use another way to identify them. We can identify each field using a method that generates a string according to field arguments and pass that string as param

This way Avo knows what field to target. As downside to this solution, any hard-coded generated string on a link should be manually replaced if the field arguments change.

@adrianthedev WDYT, any other approach on mind?

**Comment by adrianthedev** [comment]
I do like the `association` option.
Does this work @Paul-Bob?

```ruby
tabs do
  with_options as: :has_many do
    field :all_tasks
    field :bugs, scope: -> { query.bugs } do 
      record.bugs
    end
    field :features, scope: -> { query.features } do 
      record.features
    end
    field :refactors, scope: -> { query.refactors } do 
      record.refactors
    end
  end
end
```

**Comment by Paul-Bob** [comment]
No, associations don't handle blocks, query is build by doing `record.field_id`. (`record.tasks`)

With the `association` option the first step would be to do something like:

```ruby
query = if association.present?
  record.send association
else
  record.send field_id
end
```

**Comment by adrianthedev** [comment]
Let's create an issue with `association` and use that to track that one.
Let's prioritize it a bit. Not super urgent but next up somehow.

**Comment by Paul-Bob** [comment]
> Let's create an issue with `association` and use that to track that one. Let's prioritize it a bit. Not super urgent but next up somehow.

Closing in favor of https://github.com/avo-hq/avo/issues/2559

**Comment by Paul-Bob** [comment]
@ricvillagrana there might be a workaround, duplicating the association at a model level and declare a avo field for each association. Not sure about negative effects, we're working on a PR to implement the `association` option.
