### ISSUE TITLE
Action fails with ActiveRecord::RecordNotFound when using friendly_id

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#2514]
### Describe the bug

Action fails with the following error when triggered from the `show` view:

```
ActiveRecord::RecordNotFound (Couldn't find Event with 'id'=sep-01-2023-thunderhill-east-bypass):
```

I'm using friendly_id.

### Steps to Reproduce

1. Create a dummy standalone action (code sample below)
2. Create a resource which uses friendly_id (code sample below)
3. Try to use the action
5. See error in console

### Expected behavior & Actual behavior

Action tries to find a record using `slug` from friendly_id as an `id`. It should use the correct way from `find_record_method`.

### Models and resource files

Resource part:

```ruby
  self.find_record_method = lambda {
    query.friendly.find(id)
  }
```

This is my dummy action (I just started working on it):

```ruby
class Avo::Actions::UploadResults < Avo::BaseAction
  self.name = 'Upload Results'
  self.standalone = true
  self.visible = -> { view == :show }

  def fields
    field :file, as: :file
  end

  def handle(query:, fields:, current_user:, resource:, **args)
    keep_modal_open
    succeed 'Success response'
  end
end
```

### System configuration

**Avo version**: 3.4.1
**Rails version**: 7.1.3.2
**Ruby version**: 3.1.4
**License type**:
 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

When opening action select seems fine and it's using `find_record_method`:

```
Started GET "/admin/resources/events/sep-01-2023-thunderhill-east-bypass/actions?action_id=Avo::Actions::UploadResults" for 127.0.0.1 at 2024-02-23 19:46:42 -0800
Processing by Avo::ActionsController#show as HTML
  Parameters: {"action_id"=>"Avo::Actions::UploadResults", "resource_name"=>"events", "id"=>"sep-01-2023-thunderhill-east-bypass"}
  Event Load (1.0ms)  SELECT "events".* FROM "events" WHERE "events"."slug" = $1 ORDER BY "events"."date" ASC LIMIT $2  [["slug", "sep-01-2023-thunderhill-east-bypass"], ["LIMIT", 1]]
  ↳ app/avo/resources/event.rb:7:in `block in <class:Event>'
  Rendering layout vendor/bundle/ruby/3.1.0/gems/turbo-rails-1.5.0/app/views/layouts/turbo_rails/frame.html.erb
  Rendering vendor/bundle/ruby/3.1.0/gems/avo-3.4.1/app/views/avo/actions/show.html.erb within layouts/turbo_rails/frame
  Rendered vendor/bundle/ruby/3.1.0/gems/avo-3.4.1/app/views/avo/actions/show.html.erb within layouts/turbo_rails/frame (Duration: 6.9ms | Allocations: 2904)
  Rendered layout vendor/bundle/ruby/3.1.0/gems/turbo-rails-1.5.0/app/views/layouts/turbo_rails/frame.html.erb (Duration: 7.1ms | Allocations: 3015)
Completed 200 OK in 22ms (Views: 7.5ms | ActiveRecord: 1.0ms | Allocations: 7357)
```

But when Running the action error happens:

```
Started POST "/admin/resources/events/actions" for 127.0.0.1 at 2024-02-23 19:48:41 -0800
Processing by Avo::ActionsController#handle as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "action_id"=>"Avo::Actions::UploadResults", "fields"=>{"avo_resource_ids"=>"sep-01-2023-thunderhill-east-bypass", "avo_selected_query"=>"", "arguments"=>""}, "button"=>"", "resource_name"=>"events"}
  Event Load (1.0ms)  SELECT "events".* FROM "events" WHERE "events"."id" = $1 ORDER BY "events"."date" ASC LIMIT $2  [["id", nil], ["LIMIT", 1]]
  ↳ app/avo/resources/event.rb:7:in `block in <class:Event>'
Completed 404 Not Found in 17ms (ActiveRecord: 1.0ms | Allocations: 5101)

ActiveRecord::RecordNotFound (Couldn't find Event with 'id'=sep-01-2023-thunderhill-east-bypass):

app/avo/resources/event.rb:7:in `block in <class:Event>'
```

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by xeron** [comment]
I think it has something to do with the following part in actions controller:

```ruby
resource.find_record(resource_ids, params: params)
```

`resource_ids` is an `Array` which doesn't work well with

```ruby
query.friendly.find(id)
```

**Comment by xeron** [comment]
Err, went through the docs on setting up friendly_id again and realized my `find_record_method` is incomplete. Changed to:

```ruby
  self.find_record_method = lambda {
    if id.is_a?(Array)
      query.where(slug: id)
    else
      query.friendly.find(id)
    end
  }
```

and it works now.

**Comment by adrianthedev** [comment]
👌

Nice! Thanks for responding with a resolve.
Maybe others will find this issue before the docs.

https://docs.avohq.io/3.0/customization.html#using-the-friendly-gem
