### ISSUE TITLE
Pagination buttons rendering

### ISSUE THREAD

**Issue by yorsant** [avo-hq/avo#2524]
### Describe the bug
![Screenshot 2024-02-27 at 9 22 21 AM](https://github.com/avo-hq/avo/assets/12414043/d6479bb1-42f1-4a94-9734-7eb44fcbdfd9)

The pagination buttons render like this when used on association fields (tabs)

### Steps to Reproduce
Find a resource with a `has_many` association.
Render that field in a tab

### Expected behavior & Actual behavior
All buttons should be aligned and have the same sizes.

### Models and resource files
```ruby
class Community < Avo::BaseResource
  ...
  def fields
    ...
    tabs do
      field(:people, as: :has_many)
    end
  end
```

### System configuration
```ruby
gem 'avo', '~> 3.4.1'
gem 'avo-pro', '~> 3.4.1', source: 'https://packager.dev/avo-hq/'
```
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

I'm using `self.components = { resource_index_component: Avo::Views::BankAccounts::ResourceIndexComponent }`
to add `data: { action: 'click->plaid-link#open' }` to my resource.

#### Impact
I haven't check if the buttons work, UI looks broken.

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [X] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
What does `bundle info pagy` give you?

**Comment by adrianthedev** [comment]
Nevermind. I see it too. Looking into it!

**Comment by brandondrew** [comment]
I'm seeing this behavior too.  I just noticed it for the first time today.  (Perhaps I haven't dealt with multiple pages since last updating Avo.)

**Comment by adrianthedev** [comment]
Yes. Pagy was updated to v7 in one of your bundle updates and changed some classes. 
I have a PR in the works. 
It'll be fixed soon.

**Comment by adrianthedev** [comment]
That's interesting! Can you please try `bundle update pagy` too? 
That should have been fixed.
