### ISSUE TITLE
After uploading File in ActionText (Trix) it can not be found when rendering (missing attachable)

### ISSUE THREAD

**Issue by tamaloa** [avo-hq/avo#2538]
### Steps to Reproduce
1. Go to https://main.avodemo.com/avo/resources/posts/new
2. Insert Title and save
3. Edit Post
4. In BODY field attach non image File (for example README.md)
5. Save and "show content"
6. No uploaded file is shown

### Expected behavior & Actual behavior

Expected behaviour would be to show the uploaded file, actual behaviour is showing nothing.

I replicated the problem on a fresh minimal setup (https://github.com/tamaloa/AvoActionTextAttachmentTest ).
If using the rails built in create action (and trix editor) a upload is rendered in rails view as expected (via` _blob.html.erb` partial).
If adding a file to a actiontext via AVO gem the attachment does not seem to be found.

Stacktrace from showing a resource created with avo (with file upload)

```
Processing by NotesController#show as HTML
  Parameters: {"id"=>"2"}
  Note Load (0.1ms)  SELECT "notes".* FROM "notes" WHERE "notes"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/notes_controller.rb:63:in `set_note'
  Rendering layout layouts/application.html.erb
  Rendering notes/show.html.erb within layouts/application
  ActionText::RichText Load (0.1ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = ? AND "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? LIMIT ?  [["record_id", 2], ["record_type", "Note"], ["name", "content"], ["LIMIT", 1]]
  ↳ app/views/notes/_note.html.erb:4
  Rendered .rvm/gems/ruby-3.2.2/gems/actiontext-7.1.3.2/app/views/action_text/attachables/_missing_attachable.html.erb (Duration: 0.2ms | Allocations: 116)
  Rendered .rvm/gems/ruby-3.2.2/gems/actiontext-7.1.3.2/app/views/action_text/contents/_content.html.erb within layouts/action_text/contents/_content (Duration: 5.9ms | Allocations: 10446)
  Rendered notes/_note.html.erb (Duration: 29.8ms | Allocations: 30333)
  Rendered notes/show.html.erb within layouts/application (Duration: 34.2ms | Allocations: 33322)
  Rendered layout layouts/application.html.erb (Duration: 75.0ms | Allocations: 83570)
Completed 200 OK in 116ms (Views: 77.1ms | ActiveRecord: 1.7ms | Allocations: 106168)
```

### Models and resource files

 https://github.com/tamaloa/AvoActionTextAttachmentTest

### System configuration
ruby 3.2.2, rails 7.1.3.2, avo (3.4.2)

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/avo-hq/avo/assets/118779/95d90bad-86c1-4031-868a-66edb88db8a5

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

Workaround is to let users upload Files via a standard rails edit view which is far from ideal :(

**Comment by adrianthedev** [comment]
@tamaloa sorry about that. I now read the whole message and saw the reproduction repo.
We'll have a look!

**Comment by tamaloa** [comment]
Cool - it's also still reproducable on avodemo.com (just tried).

**Comment by Paul-Bob** [comment]
Hello, I reproduced it and in avodemo the scenario is different. In avodemo we have this options: 
```ruby 
      hide_attachment_url: true,
      hide_attachment_filename: true,
      hide_attachment_filesize: true
```

That cause files without preview to be hidden.

I was able to reproduce the issue reported only when using `has_rich_text`.

**Comment by tamaloa** [comment]
Thanks for looking into this.

I tried to verify the fix by using avo from current main branch in my reproduction repository: https://github.com/tamaloa/AvoActionTextAttachmentTest (Note: necessary to run `rake avo:build-assets` when pulling gem directly from github).

Unfortunately, for me, the bug has not been fixed. As can be seen in below screenrecording (using the reproduction repository above) a uploaded file still is neither shown/downloadable in avo itself nor in a standard rails view.

https://github.com/avo-hq/avo/assets/118779/b7815925-30c0-49e9-a2eb-8baae8ecd754

Furthermore a file which was attached via the default rails actiontext editor now results in an exception in avo if one wants to show/edit this field (see end of screenrecording). This renders our current workaround (using a seperate editor only for adding files) less useful as we would have to exclude editing the whole field from avo.

**Comment by Paul-Bob** [comment]
@tamaloa try it after removing the `attachment_key`, when using rich text the `attachment_key` is not needed, that was the idea of the fix PR

**Comment by tamaloa** [comment]
I actually already had tried it without the key and now double checked it (https://github.com/tamaloa/AvoActionTextAttachmentTest/commit/440830337bb8293961a25422939788f30b010ccd). Unfortunately it still does not work for me I get the behaviour as shown in above video.

**Comment by Paul-Bob** [comment]
Can confirm that the issue persist, I included it on this issue list https://github.com/avo-hq/avo/issues/2715 lets keep the conversation there since there were already many trix related open issues
