### ISSUE TITLE
belongs_to resource creation link opens dialog on hover

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2539]
### Describe the bug
The linked resource creation dialog opens just when hovering "create new X" instead of waiting for it to be clicked.

### Steps to Reproduce
Hover the link: the creation dialog opens without waiting for it to be clicked. See video capture.

### Expected behavior & Actual behavior
Don't open "create new author" dialog on hover. Wait for click.

### Models and resource files

```rb
class Avo::Resources::Article < Avo::BaseResource
  self.includes = []
  # self.search = {
  #   query: -> { query.ransack(id_eq: params[:q], m: "or").result(distinct: false) }
  # }

  self.find_record_method = -> { query.find_by_slug(id) || query.find(id) }

  def fields
    field :slug, as: :text
    field :position, as: :number
    field :author, as: :belongs_to
    field :poster, as: :file
    field :poster_classes, as: :text
    field :template_blocks, as: :tags
    field :body, as: :trix
    field :publishing_status, as: :select, enum: ::Article.publishing_statuses
    field :published_at, as: :date_time
    field :versions, as: :has_many
  end
end

class Avo::Resources::Author < Avo::BaseResource
  self.includes = []
  # self.search = {
  #   query: -> { query.ransack(id_eq: params[:q], m: "or").result(distinct: false) }
  # }

  self.find_record_method = -> { query.find_by_slug(id) || query.find(id) }

  def fields
    field :slug, as: :text
    field :name, as: :text
    field :picture_url, as: :external_image
    field :position, as: :number
  end
end

```

### System configuration
**Avo version**: 3.4.2

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**: Community

**Are you using Avo monkey patches, overriding views or view components?**
No

### Screenshots or screen recordings
NB: I did not use mouse click, just hover:

https://github.com/avo-hq/avo/assets/4217871/a7219636-7cf0-4b89-881c-f549982ae666

#### Impact

 Medium impact (I'm annoyed, but I'll live.)

#### Urgency

 Low urgency

**Comment by Paul-Bob** [comment]
This is happening as a consequence of [turbo 8 instant click](https://turbo.hotwired.dev/handbook/drive#instantclick). We added a new configuration to disable the default behavior.

Avo version `3.4.2`:

```ruby
config.turbo = -> do
  {
    instantclick: false
  }
end
```

Avo version `>= 3.4.2` ( changed the syntax, not released yet):

```ruby
config.turbo = -> do
  {
    instant_click: false
  }
end
```

Both code blocks above are just an workaround for this particular issue, we're going to investigate and try a proper fix without having to disable instant click.
