### ISSUE TITLE
Scopes don't behave properly when viewing resource via `has_many` association.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#2558]
### Describe the bug

I have a Resource with several Scopes defined for it.  The scopes behave properly from the index page for the relevant resource, but not when viewing the resource as an association from another resource.

### Steps to Reproduce

See: <https://github.com/MrJoy/avo-debug>

Create and seed DB, then start the server.

Go to: <http://localhost:4000/admin/resources/calendars/1>.

Click "Kept" or "Discarded".

View browser console / Rails logs to see that the request was made to <http://localhost:4000/admin/resources/google_calendars/1/calendar_instances?scope=Avo%3A%3AScopes%3A%3AKept&turbo_frame=has_many_field_show_calendar_instances&view=show>

### Expected behavior & Actual behavior

It appears that it _should_ be going to <http://localhost:4000/admin/resources/calendars/1/calendar_instances?scope=Avo%3A%3AScopes%3A%3AKept&turbo_frame=has_many_field_show_calendar_instances&view=show> and is getting confused by the use of STI.

(Ignore the fact that this produces an error about not having a `kept` / `discarded` scope.  I didn't bother bringing over the `discard` gem to the repro project.)

### System configuration
**Avo version**: 3.4.3

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
annoyance._
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by MrJoy** [comment]
Correction:  Adding resource sub-classes for each STI sub-class makes things work.  I would kind of expect the choice of resource to either be directly computed based on the parent resource being displayed, or at least be based on `link_to_child_resource`, but this is an adequate workaround.

**Comment by MrJoy** [comment]
At a minimum, it might be worth calling this out in the STI docs.

**Comment by Paul-Bob** [comment]
Hey @MrJoy is this fixed? 

> Adding resource sub-classes for each STI sub-class makes things work.

Can you show an example please?

**Comment by MrJoy** [comment]
The issue is fixed.  It's just that if I have an `Account` model, and say, a `GoogleAccount < Account` model, I need both an `Account` resource and a `GoogleAccount` resource.  My solution has been to have the `GoogleAccount` resource extend the `Account` resource, making whatever changes/overrides are needed.

The example is in [this commit](https://github.com/SixtyAI/fb-core/commit/0f211e29a4c3d125465f3197c026528626df9aef).

Longer-term, that's worthwhile to do because different sub-types will need to show different subsets of fields.  But I was thinking that if I didn't do anything in Avo that was sub-type-specific I could coast on having a resource for just the top-level type.  It's a bit of a sharp corner with less than sufficiently clear information coming from the error from my outside perspective, which is why I think some documentation updates around STI are warranted.

Something to the effect of: "You cannot just make a Resource for the STI base class.  If you don't add a Resource for each sub-type, you may experience bizarre and broken behavior, including scopes not working properly (etc)."

**Comment by MrJoy** [comment]
(I would've closed the issue but for the ask that docs be updated.)

**Comment by Paul-Bob** [comment]
@MrJoy in the example provided the `http://localhost:4000/admin/resources/calendars/1` path is actually a `GoogleCalendar` instance right?

When trying to access it on a normal flux by going to `http://localhost:4000/admin/resources/calendars` and click on show view it also produces `http://localhost:4000/admin/resources/google_calendars/1` link which is correct.

I have 2 questions:

1 - What is flux that leads to the `http://localhost:4000/admin/resources/calendars/1`
2 - What is the real problem that the generated scope link is causing?

**Comment by MrJoy** [comment]
@Paul-Bob Honestly, I've mostly forgotten the details of this issue.  The big picture view is that I was seeing scopes blow up on me, but ultimately the issue was resolved when I set up Resource classes for the various STI sub-types of Calendar.

Either I had `link_to_child_resource` set but hadn't created child resources, or I had _not_ set it and Avo was trying to link to child resources anyway.  Contextually, I think it was the latter.  My fix for our application was to just create child resources for everything -- which was a good idea anyway for unrelated reasons.

I assume I got to `calendars/1` via the index page, and it sent me there instead of `google_calendars/1` because `link_to_child_resource` wasn't set.

This appears to be the relevant commit that should allow you to reproduce the issue: https://github.com/MrJoy/avo-debug/commit/a6cd4a71903087ad82f173f7eb7bb2b55b62a0b0

And I am not sure how sleep-deprived I was that I gave you a link to one of our private repositories.  Sorry about that.

**Comment by Paul-Bob** [comment]
I'll close this issue since the original problem is fixed, we want to start this best-practices docs page https://github.com/avo-hq/avodocs/issues/193 and maybe there we can include a notice about scopes and STI but for that we should properly identify the issue. Feel free to reopen this one if the issue re-appear in other circumstances.
