### ISSUE TITLE
Implement `association` option for association fields.

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2559]
### Feature

Implement `association` option that allow specifying the association target for an association filed.

```ruby
with_options as: :has_many do
  field :users, scope: -> { query.non_admins }
  field :admins, association: :users, scope: -> { query.admins }
end
```

### Additional context

https://github.com/avo-hq/avo/issues/2513

**Comment by FLX-0x00** [comment]
We want that feature too =)

**Comment by Paul-Bob** [comment]
We decided to implement this option to all fields and rename it to `for_attrbute`
