### ISSUE TITLE
When trying to detach has_many association it policy record becomes different model

### ISSUE THREAD

**Issue by giedriusr** [avo-hq/avo#2568]
### Describe the bug
I have models:
Appointment and Order. Appointment may have many Orders through AppointmentOrder (3rd model). I am using Attach Association functionality to add Orders to Appointment. Similarly as in https://main.avodemo.com/avo/resources/courses/150 by adding links. Attaching only those orders which aren't attached yet.
Now I am trying to detach order with some logic.

```ruby
# models

class Order < ActiveRecord
  has_one :appointment_order
  has_one :assigned_appointment, class_name: "Appointment", source: :appointment, through: :appointment_order, inverse_of: :assigned_orders
end

class Appointment < ActiveRecord
  has_many :appointment_orders
  has_many :assigned_orders, class_name: "Order", source: :order, through: :appointment_orders, inverse_of: :assigned_appointment
end

class AppointmentOrder < ApplicationRecord
  belongs_to :appointment
  belongs_to :order
end

```

```ruby
# Policies
# appointments_policies.rb

def attach_assigned_orders?
  record.some_method.present?
end

def detach_assigned_orders?
  record.assigned_appointment.some_method.present?
end
```
Documentation https://docs.avohq.io/2.0/authorization.html#detach_association says that above record is actual the Order record.
```
The record variable is the actual row record (a Comment instance in our scenario).
```

While displaying Index it works fine, but when I press on detach record, I get an error stating that record.assigned_appointment method is not found on Appointment record. Suddenly my "record" becomes an Appointment and not an Order.

Is it a bug or intented to work differently on GET and POST requests?

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### System configuration
**Avo version**: 3.4.4

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
<img width="1591" alt="image" src="https://github.com/avo-hq/avo/assets/210713/da79ee74-fe74-4e14-8e8d-3121a4424fd7">
<img width="1590" alt="image" src="https://github.com/avo-hq/avo/assets/210713/b7e4bd25-a20e-4ce6-af4d-471877700960">
<img width="1006" alt="image" src="https://github.com/avo-hq/avo/assets/210713/4aa26ed0-65db-4451-a01b-ec1ecda45b5a">

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@Paul-Bob can we prioritize and investigate this, please?

**Comment by adrianthedev** [comment]
Maybe @gabrielgiroe1 can pick this up?
