### ISSUE TITLE
Boolean Group Field in action fields yields to unpermitted param

### ISSUE THREAD

**Issue by lizdeika** [avo-hq/avo#2569]
### Describe the bug
See title

### Steps to Reproduce
1. Create an action for resource
2. Add boolean_group field in action
3. Submit
4. boolean_group field is unpermitted and unavailable in handle method fields parameter

### System configuration
**Avo version**: 3.4.4

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@gabrielgiroe1 can you please try and see if you can reproduce this?
