### ISSUE TITLE
Cannot install avo-dashboard.

### ISSUE THREAD

**Issue by louisroehrs** [avo-hq/avo#2575]
### Describe the bug

(.venv) (base) lroehrs@Louis-Tiger-Mac ~/awork/bloom (staging) $ bundle update --bundler
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from https://packager.dev/avo-hq/...
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching avo-dashboards 3.3.1
Fetching avo-menu 3.3.1

Retrying download gem from https://packager.dev/avo-hq/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-dashboards-3.3.1.gem)

Retrying download gem from https://packager.dev/avo-hq/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-menu-3.3.1.gem)

Retrying download gem from https://packager.dev/avo-hq/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-dashboards-3.3.1.gem)

Retrying download gem from https://packager.dev/avo-hq/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-menu-3.3.1.gem)

Retrying download gem from https://packager.dev/avo-hq/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-dashboards-3.3.1.gem)

Retrying download gem from https://packager.dev/avo-hq/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://packager.dev/avo-hq/gems/avo-menu-3.3.1.gem)

Bundler::HTTPError: Could not download gem from https://packager.dev/avo-hq/ due to underlying error <bad response Forbidden
403 (https://packager.dev/avo-hq/gems/avo-dashboards-3.3.1.gem)>
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_integration.rb:459:in `rescue in download_gem'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/rubygems_integration.rb:434:in `download_gem'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:488:in `download_gem'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:449:in `fetch_gem'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:433:in `fetch_gem_if_possible'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:162:in `install'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing avo-dashboards (3.3.1), and Bundler cannot continue.

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### Expected behavior & Actual behavior
Installs avo-dashboard.

Actual output error above.
### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@louisroehrs what kind of license do you have?
