### ISSUE TITLE
Search results don't respect `self.link_to_child_resource = true`.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#2581]
### Steps to Reproduce
1. Grab <https://github.com/MrJoy/avo-debug>
2. Bring it up, being sure to seed the DB.
3. Go to <http://localhost:4000/admin/resources/calendars/>
4. Hover over the ID column of the sample data row, and note that it links to <http://localhost:4000/admin/resources/google_calendars/1>, as expected.
5. Perform a search for "foo", and click on the result.  Note that the URL is <http://localhost:4000/admin/resources/calendars/1>.

### Expected behavior & Actual behavior

`self.link_to_child_resource` should be respected uniformly.

### System configuration
**Avo version**: 3.4.4

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
   - My "workaround" is to instruct my team that when searching one of about half a dozen resources, they will need to remember to manually edit the URL...
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello @MrJoy 

I was able to reproduce the issue, thanks for all the details and the reproduction repository, we're working on it
