### ISSUE TITLE
Some has_many links do not keep the breadcrumb

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2584]
### Describe the bug

I've noticed an issue where, in some instances, the breadcrumb for a nested resource doesn't show the parent resource. This appears to be because the URL lacks both `via_record_id` and `via_resource_class`. The relevant has_many association is defined as follows:

```ruby
field :contracts, as: :has_many, visible: -> { resource.record.ref_booking_type.present? }, discreet_pagination: true
```

### System configuration
**Avo version**:
3.4.2

**Rails version**:
7.1.3.2

**Ruby version**:
3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

<div>
    <a href="https://www.loom.com/share/c69e52d512144dd7a86923b916aa3347">
      <p>Brave Browser - BKG-0049 — Ultra Estates - 11 March 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/c69e52d512144dd7a86923b916aa3347">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/c69e52d512144dd7a86923b916aa3347-with-play.gif">
    </a>
  </div>

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@jetienne can you share please the reference field from contract resource?

**Comment by jetienne** [comment]
```ruby
field :reference, as: :text, hide_on: :forms
````

It's an auto-generated reference, not editable.

**Comment by Paul-Bob** [comment]
What are you using to make it clickable?

**Comment by Paul-Bob** [comment]
Closing as solved, feel free to comment / re-open if still need assistance
