### ISSUE TITLE
undefined method `apply' for nil on Scope

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2587]
### Describe the bug

On a given scope, the following visibility block will be OK:
```ruby
self.visible = -> { true }
```

when this one will fail:
```ruby
 self.visible = -> { false }
```

```ruby
undefined method `apply' for nil


Extracted source (around line #17):
      # Apply scope
            if params[:scope].present?
              @query = @scopes.find { |scope| scope.is_a?(params[:scope].constantize) }.apply
            end
          end
        end

[avo-advanced (3.4.4) lib/avo/advanced/concerns/scopes.rb:17:in `set_and_apply_scopes'](http://app.ultraestates.local:3000/admin/resources/deals?scope=Avo%3A%3AScopes%3A%3ADealsEnquiry#)
[avo (3.4.4) app/controllers/avo/base_controller.rb:562:in `safe_call'](http://app.ultraestates.local:3000/admin/resources/deals?scope=Avo%3A%3AScopes%3A%3ADealsEnquiry#)
[avo (3.4.4) app/controllers/avo/base_controller.rb:60:in `index'](http://app.ultraestates.local:3000/admin/resources/deals?scope=Avo%3A%3AScopes%3A%3ADealsEnquiry#)
```

### System configuration
**Avo version**:
3.4.2

**Rails version**:
7.1.3.2

**Ruby version**:
3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello @jetienne the scope is visible to click on it and then the block is evaluated again when clicked and this error is raised?

**Comment by jetienne** [comment]
hello @Paul-Bob The error is raised when loading the page

**Comment by Paul-Bob** [comment]
Loading the page with a manually written scope inside the URL? I'm checking your error log and i noticed this param `?scope=Avo%3A%3AScopes%3A%3ADealsEnquiry`. I suppose `Avo::Scopes::DealsEnquiry` is the one returning false but how can you select it if its not visible?

**Comment by jetienne** [comment]
Because that's the default one. I understand your point, but this would be nice to not raise any errors. 

This ties back to our discussion about establishing a default scope. For instance, consider a Kanban view where you prefer not to show empty scopes. Even though the first tab is default, it might not be visible.

**Comment by Paul-Bob** [comment]
Got it, when we add support for the default option this use case will be covered for sure! Since you're using a workaround I suggest to duplicate the visibility logic and set the scope on the URL only if it will be visible. 

Workarounds are great to unlock development but can lead to this kind of situations.

Not sure if adding a safe navigator on this one would be a good idea, that will lead to ignore any scope param that is not on the scope list and may lead to silent errors, for example: `...?scope=some_random_text` will just load the page without any error.

**Comment by jetienne** [comment]
Fine for me @Paul-Bob !

**Comment by Paul-Bob** [comment]
Closing as completed. Added a reminder here https://github.com/avo-hq/avo/issues/2402#issuecomment-1992194603
