### ISSUE TITLE
Default sort by for resource

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2600]
### Discussed in https://github.com/avo-hq/avo/discussions/2553

<div type='discussions-op-text'>

<sup>Originally posted by **krystof-k** March  3, 2024</sup>
It would be great if it would be possible to set default sorting for a resource, for example something like:

```ruby
  def fields
    field :created_at,
      as: :date_time,
      disabled: true,
      sortable: true,
      sort_by_default: :desc
  end
```

**Comment by Paul-Bob** [comment]
For index when visiting resource
```ruby
self.index_query = -> { query.order(created_at: :desc) }
```

For index when rendered on association
```ruby
field :users, as: :has_many, scope: -> { query.order(created_at: :desc) }
```

**Comment by Yash-Git-Hub** [comment]
Picking this up.

**Comment by Paul-Bob** [comment]
Hello @Yash-Git-Hub we decided to go with a global configuration as specified in this issue https://github.com/avo-hq/avo/issues/2982 and it's already assigned to @iamworrell

Let's continue the conversation there.

Closing in favor of https://github.com/avo-hq/avo/issues/2982
