### ISSUE TITLE
Secondary labels above each field

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2604]
### Describe the bug

_Discussed in https://github.com/avo-hq/avo/discussions/2578_

I have duplicate labels above each input in edit view. When there is a translation for such field:

```yaml
cs:
  activerecord:
    attributes:
      car:
        make: Značka
```

it is even translated:

![image](https://github.com/avo-hq/avo/assets/11633481/d0010ba1-9b6c-432a-8f9d-3d101343881d)

### Expected behavior & Actual behavior

There are no secondary labels.

### System configuration
**Avo version**: 3.5.3

**Rails version**: 6.1.7.7

**Ruby version**: 3.1.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

view_component version is 3.11.0

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
I'm not able to reproduce it, can you please provide a minimal reproduction repository? It only need to include an app with avo installed and 1 resource where this is happening

**Comment by krystof-k** [comment]
I will try, but I'm afraid I will not be able to… If you have any idea where to start digging in our app I'll try.

**Comment by Paul-Bob** [comment]
I would start by inspecting the element and try to figure out where is it rendered in the component

**Comment by krystof-k** [comment]
@adrianthedev Sure, thanks, I will try to investigate this as soon as I have a while and get back.

**Comment by krystof-k** [comment]
I found it. It was caused by [Foundation Rails Helper](https://github.com/sgruhier/foundation_rails_helper) used in our legacy app, which adds labels to all form fields. The fix was to disable it in `config/initializers/avo.rb`:

```ruby
Avo.configure do |config|
  FoundationRailsHelper.configure do |config|
    config.auto_labels = false
  end
end
```

So not an issue related to Avo (or – just to the fact that it is Rails engine).

**Comment by adrianthedev** [comment]
Wow. What a wild find!
Thank you so much for posting this!
I don't know if I could have found it myself.
