### ISSUE TITLE
View `edit` vs. `update`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2605]
### Discussed in https://github.com/avo-hq/avo/discussions/2601

<div type='discussions-op-text'>

<sup>Originally posted by **krystof-k** March 16, 2024</sup>
I had a condition like this:

```ruby
field :name,
  as: :text,
  disabled: -> { view == :edit },
```

which results on disabled field on edit view, but when validation fails, it stops being disabled because the view changes from `edit` to `update`.

Is this intentional? Is there any actual difference between `edit` and `update`? If so it would be nice it to have a mention in the docs about it (where I haven't found any).</div>

**Comment by adrianthedev** [comment]
This is an interesting edge-case @krystof-k. THanks for reporting.

Handling views can get a bit tricky in some cases, but IMHO this should be supported and have the field disabled even after the validation error.

Maybe we should force the `view` to be `edit` on if the validation fails? Same for `new`/`create` @Paul-Bob?

**Comment by Paul-Bob** [comment]
Agree, `edit` and `new` should persist when running `update` and `create` actions
