### ISSUE TITLE
Textarea doesn't preserve newlines on show view

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2606]
### Describe the bug

If you save a text with newlines to textarea field, it is then display with no newlines on the show view (as it is not rendered as textarea).

![image](https://github.com/avo-hq/avo/assets/11633481/21a7747e-da04-4635-bc7c-efad25fdd689)
![image](https://github.com/avo-hq/avo/assets/11633481/3959f1d7-a6f4-4ae5-9be3-0f013c07892e)

### Steps to Reproduce
1. Add textarea field
2. Save text with newlines to a resource
3. Go to show view
4. See no newlines

### Expected behavior & Actual behavior

I guess it should be either rendered as readonly textarea also on the show view or to convert newlines to `<br />` when rendering.

### System configuration
**Avo version**: 3.5.3

**Rails version**: 6.1.7.7

**Ruby version**: 3.1.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
What would that look like? Turning `\n` to `<br/>`?
Would you be able to send in a PR?

**Comment by krystof-k** [comment]
Yes, I can try that :)

**Comment by krystof-k** [comment]
@adrianthedev I found usage of div wrapper with `white-space: pre-line;` in the dummy app, which seems more appropriate, so #2678 implements it for the text area globally.
