### ISSUE TITLE
Key value field doesn't behave like disabled

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2608]
### Describe the bug

when `as: :key_value` field is set as disabled, it doesn't behave like disabled on edit view (although it doesn't save any changes so security-wise it's OK).

### Steps to Reproduce
1. Add disabled key value field
   ```ruby
   field :metadata,
     as: :key_value,
     disabled: true
   ```
2. Go to edit view
3. You can edit the values/rows

### Expected behavior & Actual behavior

It should not be editable (render as on show view).

### System configuration
**Avo version**: 3.5.3

**Rails version**: 6.1.7.7

**Ruby version**: 3.1.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
There are 3 option to disable different parts of `key_value` field:

- [`disable_editing_keys`](https://docs.avohq.io/3.0/fields/key_value.html#disable_editing_keys)
- [`disable_adding_rows`](https://docs.avohq.io/3.0/fields/key_value.html#disable_adding_rows)
- [`disable_deleting_rows`](https://docs.avohq.io/3.0/fields/key_value.html#disable_deleting_rows)

Lets add another one, `disable_deleting_values` that will disable the values slots.

Also lets ensure that if `disabled: true` is declared on this field all option above are automatically switched to `true`

**Comment by krystof-k** [comment]
@Paul-Bob are you sure about `disable_deleting_values`? Haven't you meant `disable_editing_values`?

**Comment by gabrielgiroe1** [comment]
@krystof-k we are working on this feature `disable_deleting_values`.

**Comment by Paul-Bob** [comment]
Thanks for the correction @krystof-k , I meant `disable_editing_values`
