### ISSUE TITLE
Suggestions on filters

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2621]
### Feature

```ruby
filterable: {
  suggestions: -> { Model.pluck(:name) }
} 
```
Suggestions works only on tag fields filters right now, may be interesting to make suggestion work for all filter types.

[From here.](https://discord.com/channels/740892036978442260/1219927831837016136)

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2268
