### ISSUE TITLE
Advanced filter for date with is_within not working

### ISSUE THREAD

**Issue by FLX-0x00** [avo-hq/avo#2622]
Also on avo demo page the filter is not working (without any errors)

On local instance it runs into an error
![image](https://github.com/avo-hq/avo/assets/26464774/a540d3a5-6c40-43c5-914e-2bcc0cd705a8)

The "is" operator works as expected.

**Comment by Paul-Bob** [comment]
Hello @FLX-0x00 I'm not able to reproduce it

Working as expected locally and on demo

https://main.avodemo.com/avo/resources/users?filters[birthday][is_within][]=2020-03-26%20to%202020-03-31

**Comment by FLX-0x00** [comment]
Maybe was a bug and now it's fixed? I will check this later that day ;)

**Comment by Paul-Bob** [comment]
Maybe =)) Let us know if the issue persist

**Comment by Paul-Bob** [comment]
@FLX-0x00 Any news about this one?

**Comment by FLX-0x00** [comment]
we are experiencing still an error if we use it - but we are unable to provide more information to this. we give adrian a short briefing to this

**Comment by adrianthedev** [comment]
I'm looking into this.

**Comment by FLX-0x00** [comment]
was me: config.ignore_unknown_conditions = false on ransack initializer was set
