### ISSUE TITLE
Money field (with decimals and currency)

### ISSUE THREAD

**Issue by Bergrebell** [avo-hq/avo#2624]
### Feature
There is currently no comfortable way to store money in Avo. This feature should help to store money in a more robust way using the battle-tested "money-rails"-gem, while providing a good UX for the users and DX for the developers. 

**The issue with money:**
There are some issues with storing money-amounts as `float` or `numeric` that can lead to rounding errors ([link](https://blog.appsignal.com/2023/11/29/keep-your-ruby-code-maintainable-with-money-rails.html)). One workaround is to store money-amounts in their smallest unit (eg. for Dollar this is cents) instead of using floats. A popular project that uses this stratey is RubyMoney and their [money-rails](https://github.com/RubyMoney/money-rails)-gem. 

Money-rails stores money as a combination of `amount_cents` and `amount_currency`. This allows for easy conversion between currencies and the gem further helps with the formatting according to different standards. 

### Current workarounds
But using the money-rails gem in avo is currently not possible with good UX and DX. 

One option is to use a text-field to display the amount and an additional dropdown for the currency. But this leads to a whole lot of strange behavior on saving and changing the currency. 
```
field :amount, as: :text,
          format_using: -> {
            value.format
          }, update_using: -> do
        value
      end
    field :amount_currency, as: :select, options: %w[CHF EUR USD], only_on: [:edit]
```

Another option is using a number-field, but this prevents us from storing decimals. 

### Screenshots
The field could look something like that, if currencies are provided (as an option)
<img width="1132" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/566a2a05-9f44-4300-9e3a-c242fd37053e">

or just do the correct formatting if no currencies are provided.

<img width="629" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/c75c4bc5-692d-4731-ba82-3deb4b811158">

**Comment by Bergrebell** [comment]
@adrianthedev - for the input formatting, we could use [cleavejs](https://nosir.github.io/cleave.js/) as described [here](https://dev.to/bilalbudhani/currency-input-masking-with-cleave-js-and-money-gem-in-ruby-on-rails-490l). 

but i'm not really sure if this is really necessary. the gem already does a nice job in formatting and [provides a good api](https://github.com/RubyMoney/money?tab=readme-ov-file#usage) to convert money from full-amounts or from cents into money-objects.

**Comment by adrianthedev** [comment]
Closed by https://github.com/avo-hq/avo/pull/2642, https://github.com/avo-hq/avo/pull/2669, and https://github.com/avo-hq/avo-money_field
