### ISSUE TITLE
Ability to Filter by Non-Visible Fields on Index Page

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2625]
### Feature

Implement filtering capabilities on index pages for fields that are not currently visible.

### Detail

Currently, on index pages, users can only filter using fields that are visible. It would be highly beneficial to enable filtering by fields that are not displayed on the index page. This feature would enhance the user's ability to manage and navigate through large datasets by applying more granular and specific filters, improving overall user experience.

For instance, a user could filter records by a creation date or a related record's ID without needing to clutter the index view with these fields.

### Use Case

As an example, in a project management tool, being able to filter tasks by their due date or associated project's status without displaying these fields would keep the index page uncluttered but still very functional.

Thank you for considering this feature request.

**Comment by Paul-Bob** [comment]
Hello @jetienne , there is already possible to make a non visible field filterable.

Ex: `field :something ... filterable: true, visible: -> { false }`

When using `def show_fields` and `def index_fields` is different because avo will fetch fields only from one of that methods depending on the view.

Can you please share a simple example where you can't filter on a non-visible field?

**Comment by jetienne** [comment]
@Paul-Bob Thank you.

### Scenario 1

```ruby
class Avo::Resources::Res1 < Avo::BaseResource
  self.includes = []

  def fields
    field :prop1, as: :text, filterable: true
    field :prop2, as: :text, filterable: true
    field :prop3, as: :text, filterable: true
  end
end
```

### Scenario 2
```ruby
class Avo::Resources::Res2 < Avo::BaseResource
  self.includes = []

  def index_fields
    field :prop1, as: :text, filterable: true
  end

  def fields
    field :prop1, as: :text
    field :prop2, as: :text, filterable: true
    field :prop3, as: :text
  end
end
```

### Scenario 3

```ruby
class Avo::Resources::Res3 < Avo::BaseResource
  self.includes = []

  def index_fields
    field :prop1, as: :text, filterable: true
    field :prop2, as: :text, filterable: true, visible: -> { false }
  end

  def fields
    field :prop1, as: :text
    field :prop2, as: :text
    field :prop3, as: :text
  end
end

```

I understand what you're saying. Looking at Scenario 2, it's clear there shouldn't be an additional declaration similar to what we see in Scenario 3. However, am I right in thinking that `fields` doesn't get executed in `Res#index` if an `index_fields` is present?

Although declaring it as shown in Scenario 3 is manageable for me...

**Comment by Paul-Bob** [comment]
Yes @jetienne, you're thinking it right. If `index_fields` is present fields will be fetched only from that method (when rendering index view), ignoring `fields`

If it becomes too duplicated you always can opt for this scenario:

```ruby
class Avo::Resources::Res4 < Avo::BaseResource
  self.includes = []

  def fields
    field :prop1, as: :text, filterable: true
    field :prop2, as: :text, filterable: true, hide_on: :index
    field :prop3, as: :text
  end
end
```

**Comment by jetienne** [comment]
thanks @Paul-Bob 

Additionally, it's worth mentioning that if a property isn't listed in `ransackable_attributes`, the filtering will fail without any warning. This instance of silent failure joins other similar cases that, in my opinion, ought to be avoided.

**Comment by Paul-Bob** [comment]
Agree 👍 

Created an issue to track it, closing this one as completed
