### ISSUE TITLE
STI: field with link_to_record does not link to child resource

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2629]
### Describe the bug
The hyperlinks added to some specific field using the option `link_to_record` do not behave consistently with the `link_to_child_resource` option set on the resource. 

### Steps to Reproduce
1. add `self.link_to_child_resource = true` on the parent resource, e.g. Person
2. visit the index page, observe that the eye button to go to the show page links to the sub-type (e.g. Spouse) as intended
3. define a field e.g. `field :name, as: :text, link_to_record: true`: observe that it does not link to the spouse resource but to the person resource

### Expected behavior & Actual behavior
A field with link_to_record: true should link to the child resource when link_to_child_resource has been set on the parent resource.

### System configuration
**Avo version**: 3.5.4

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@sedubois I tested this here https://main.avodemo.com/avo/resources/people and it works as expected.

Closing as fixed, let us know if the issue persists and provide a minimal reproduction repository please.
