### ISSUE TITLE
Ability to sort filter options in the dropdown manually

### ISSUE THREAD

**Issue by maokomioko** [avo-hq/avo#2634]
### Feature
Expose configuration to sort filter options in the dropdown manually.
Ex. I want "start date" to appear before "end date". Perhaps like this 
```ruby
  filter_options_position = {start_date: 1, end_date: 2} 
```

### Screenshots or screen recordings
![image](https://github.com/avo-hq/avo/assets/767496/018d4a78-1ceb-4920-bc8f-e330c04038cd)

**Comment by Paul-Bob** [comment]
Possible API:

```ruby
class Avo::Resources::Project < Avo::BaseResource
  self.dynamic_filters_order = -> {
    filters_list.map... # return list ordered as you wish here
  }
end
```

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2268
