### ISSUE TITLE
Sorting is not case-insensitive

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2636]
### Steps to Reproduce
1. Create a resource with `field :email, as: :text, sortable: true`
2. Create 3 records, with one of them having the email alphabetically greater than the email of the other two records, but capitalized, e.g. `a@example.com`, `b@example.com`, `C@EXAMPLE.COM`
3. Go to index view, click on the email column header to sort emails ascending (http://localhost:3000/avo/resources/users?sort_by=email&sort_direction=asc)

### Expected behavior & Actual behavior
The sorting should ignore capitalization: `a@example.com`, `b@example.com`, `C@EXAMPLE.COM`

But it is `C@EXAMPLE.COM`, `a@example.com`, `b@example.com`

### Models and resource files
```rb
class Avo::Resources::User < Avo::BaseResource
  def fields
    field :email, as: :text, sortable: true
  end
end
```

### System configuration
**Avo version**: 3.5.5

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2024-03-25 at 15 35 28](https://github.com/avo-hq/avo/assets/4217871/53dbec43-3c53-4541-97ce-6166ed0f74f7)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Would you be able to send in a PR to fix this @sedubois?
We'd love to have it fixed.

**Comment by sedubois** [comment]
@adrianthedev I don't know how to:
1. do the sorting while still using DB indices for performance. We could use `order('lower(name)')` but it will not use indices. 
2. restrict the case-insensitive order to only apply to string/text columns. How to detect that the Avo field is backed by a string/text column and apply point 1 in that case?
3. run a unit test: I get the error `objc[28075]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.` when running one of them in my IDE
4. add a unit test: the `field_sorting_spec` does not show how to test the actual order of records.
5. test with the dummy app. I ran `bin/init` and `bin/dev` but the CSS doesn't load and the login button doesn't work:

![Screenshot 2024-03-29 at 16 02 45](https://github.com/avo-hq/avo/assets/4217871/54889f97-b357-40da-b8c0-0904435ddf86)

**Comment by sedubois** [comment]
> 3. run a unit test: I get the error `objc[28075]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.` when running one of them in my IDE

Workarounded with `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in .zshrc. ([ref](https://github.com/rails/rails/issues/38560))

**Comment by sedubois** [comment]
> 4. add a unit test

Here is a failing test reproducing the issue:
https://github.com/sedubois/avo/commit/d5f32dbcca78ef52c8f1317517b4cc3e315a81b2

**Comment by adrianthedev** [comment]
1. That is the problem that needs fixing I suppose. I don't know how to fix that indexing issue.

2. You should be able to do `@resource.get_fields` or `@resource.get_field_definitions` in place to get all the fields and then filter by type (`field.id`).

3. I have never seen that error in my life. Thanks for posting the workaround!

4. Yes, that might have been overlooked or tested in another place. Let's add that test case please. The way I'd do it would be to fetch all the items from the DOM, get their id's (it's in the DOM) and assert an order.

5. The login screen doesn't have any styles attached to it. It's supposed to look like that. The rest of the app (Avo) should have valid styles and should look pretty.

Thanks for going this deep @sedubois! We appreciate the help!
