### ISSUE TITLE
Embedding images in Trix editor does not work

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2638]
### Describe the bug
Embedding images in Trix editor either leads to error or results in images which do not persist (see below).

### Steps to Reproduce
1. Create a resource with `field :body, as: :trix`
2. Create a new record
3. Go back to the edit page
4. Click on the paperclip icon in the Trix toolbar for this field
5. Select some image file

### Expected behavior & Actual behavior
Expected: the image gets inserted. After saving, it renders correctly.

Actual: error `You haven't set an `attachment_key` to this Trix field.` But the [documentation](https://docs.avohq.io/3.0/fields/trix.html#attachment_key) does not specify which value should be put for `attachment_key`. I tried `embeds` and `trix_attachments`, neither of those allow to embed images which persist after saving. Besides, Avo should be able to figure out by itself what is required: we have been able to embed images without specifying any "attachment key" when using Administrate.

### Models and resource files

```rb
class Article < ApplicationRecord
  has_rich_text :body
end
```

```rb
class Avo::Resources::Article < Avo::BaseResource
  def fields
    field :body, as: :trix
  end
end
```

### System configuration
**Avo version**: 3.5.5

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**:
 - [x] Community
 - [ ] Pro
 - [ ] Advanced

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

The only workaround known to us currently is to stop Avo development and continue to rely on Administrate as far as these resources are concerned.

**Comment by Paul-Bob** [comment]
Hello @sedubois maybe this documentation section helps to clear things out https://docs.avohq.io/3.0/fields/trix.html#file-attachments

The `attachment_key` should have the same name as the attachment association on your model:

If you have this model:

```ruby
class Post < ApplicationRecord
  has_many_attached :trix_attachments
end
```

You should declare the field this way:

```ruby
field :body, as: :trix, attachment_key: :trix_attachments
```

The `attachment_key` is the bridge between the field and the association that will keep the attachments.

**Comment by sedubois** [comment]
Hi @adrianthedev I saw that documentation, but what should I specify when my model just has:

```rb
class Article < ApplicationRecord
  has_rich_text :body
end
```

I tried this but doesn't work:

```rb
class Avo::Resources::Article < Avo::BaseResource
  def fields
    # also tried field :body, as: :trix, attachment_key: :embeds
    field :body, as: :trix, attachment_key: :trix_attachments
  end
end
```

**Comment by sedubois** [comment]
Hi @Paul-Bob I saw that documentation, but what should I specify when my model just has:

```rb
class Article < ApplicationRecord
  has_rich_text :body
end
```

I tried this but doesn't work:

```rb
class Avo::Resources::Article < Avo::BaseResource
  def fields
    # also tried field :body, as: :trix, attachment_key: :embeds
    field :body, as: :trix, attachment_key: :trix_attachments
  end
end
```

**Comment by Paul-Bob** [comment]
If you want to save several files you can do:

```ruby
class Article < ApplicationRecord
  has_rich_text :body

  has_many_attached :the_attachments_name
end
```

Then:

```ruby
class Avo::Resources::Article < Avo::BaseResource
  def fields
    field :body, as: :trix, attachment_key: :the_attachments_name
  end
end
```

**Comment by Paul-Bob** [comment]
This behaviour is needed specially when using a `text` structure without `has_rich_text`, Avo needs to know where to attach the files. For `has_rich_text` it might be possible to ignore this option, we'll give it a look maybe we can remove the need of `attachment_key` when using rich text and also fix this one https://github.com/avo-hq/avo/issues/2538

**Comment by sedubois** [comment]
Thanks @Paul-Bob but I don't understand why I would need to update the model definition. My understanding it that it should just work with `has_rich_text :body`:
https://edgeguides.rubyonrails.org/action_text_overview.html#creating-rich-text-content

Our app has been working this way for many years, both the front-end where the posts are rendered, and the Administrate backend.

At any rate we need to keep compatibility for our existing records.

**Comment by Paul-Bob** [comment]
@sedubois I understand your concern and we're working on it. Can you please follow this steps and return with feedback if this works or not?

1. In `avo.rb` after config:
```ruby
Avo.configure do |config|
  # ...
end

Rails.configuration.to_prepare do
  # ...
  Avo::BaseComponent.delegate :rich_text_area_tag, to: :helpers
end
```

2. Run `$ rails g avo:eject --field-components trix --view edit --scope active_text`
3. Replace the code on the ejected `app/components/avo/fields/active_text/trix_field/edit_component.html.erb` to:
```erb
<%= field_wrapper **field_wrapper_args do %>
  <%= @form.rich_text_area @field.id,
    value: @field.value,
    class: classes("w-full"),
    data: @field.get_html(:data, view: view, element: :input),
    disabled: disabled?,
    placeholder: @field.placeholder,
    style: @field.get_html(:style, view: view, element: :input)
  %>
<% end %>
```
4. Use this configuration on the field:
```ruby
    field : body, as: :trix, components: {
      edit_component: Avo::Fields::ActiveText::TrixField::EditComponent
    }
```

**Comment by sedubois** [comment]
Thanks @Paul-Bob, I've applied the changes:
https://github.com/sedubois/avo-trix-demo/commit/8ba9f852c362346dfd2db2350cbc8f5d20d33989

It seems to be an improvement as the embedded image gets saved to Active Storage.

However:
1. on edit: the text formatting in the field is wrong, see images below
2. on show (after I embed an image then click save), I get this error: `Can't resolve image into URL: undefined method `to_model' for an instance of ActiveStorage::VariantWithRecord`. This is raised in `app/views/active_storage/blobs/_blob.html.erb:3` which is a file which was created by `rails g action_text:install`. 

<img width="595" alt="Screenshot 2024-03-26 at 15 50 29" src="https://github.com/avo-hq/avo/assets/4217871/e45d2541-6100-4622-9be0-d0253527e153">
<img width="589" alt="Screenshot 2024-03-26 at 15 50 53" src="https://github.com/avo-hq/avo/assets/4217871/b640eac1-f2a0-49fa-ae0b-f7baa9c1abf3">

**Comment by Paul-Bob** [comment]
The show issue can be solved replacing some blob code into:

```erb
# Original
<% if blob.representable? %>
  <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
<% end %>

# Replace with this
<% if blob.representable? %>
  <%= image_tag main_app.url_for(blob) %>
<% end %>
```

Thanks for confirming that’s working, you can use this as a workaround until we release a proper per fix or revert the changes until then

**Comment by sedubois** [comment]
Thanks @Paul-Bob! That temporarily resolves point 2 👍 

But:
- in our real app, `app/views/active_storage/blobs/_blob.html.erb` calls not `blob.representation` but a custom helper method called `responsive_image_tag` which isn't found. How to make it available to the blob partial?
- the issue 1 (broken layout) prevents from using these changes in prod

**Comment by adrianthedev** [comment]
@sedubois can you paste the contents of your `app/views/active_storage/blobs/_blob.html.erb`?
It seems very important that we know what that does.

**Comment by sedubois** [comment]
@adrianthedev see below. The helper code is used both in the app front-end and in the existing Administrate dashboards. We would need to start using these in Avo as well.

```erb
<%# app/views/active_storage/blobs/_blob.html.erb %>

<% blob_html = capture do %>
  <figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
    <% if blob.representable? %>
      <%= responsive_image_tag blob %>
    <% end %>

    <% if caption = blob.try(:caption) %>
      <figcaption class="attachment__caption">
        <%= caption %>
      </figcaption>
    <% end %>
  </figure>
<% end %>

<% if local_assigns[:fullscreen] || controller.class.module_parent == Admin || @content.nil? || native_app? %>
  <%= blob_html %>
<% else %>
  <modal-link href="<%= url_for([blob, content_id: @content.id]) %>" rel="nofollow">
    <%= blob_html %>
  </modal-link>
<% end %>
```

```rb
# app/helpers/active_storage_helper.rb

module ActiveStorageHelper
  # ...
  def responsive_image_tag(blob, widths: [640, 1024, 1440, 1920], sizes: "100vw", **options)
    return unless analyze_blob(blob)
    image_tag(blob, srcset: srcset_for(blob, widths:), sizes:, **options)
  end

  def srcset_for(blob, widths:)
    return unless (blob_width, blob_height = blob_size(blob))
    widths
      .filter { |width| width <= blob_width }
      .tap { |w| w.append(blob_width) if blob_width < widths.max }
      .map do |width|
        height = (1.0 * width / blob_width * blob_height).to_i
        [rails_storage_proxy_url(blob_thumb(blob, [width, height])), "#{width}w"]
      end
  end

  private

  def analyze_blob(blob)
    if !blob.is_a?(ActiveStorage::Attached) || blob.attached?
      blob.tap { |blob| blob.analyze unless blob.analyzed? }
    end
  end

  def blob_size(blob)
    analyze_blob(blob)&.metadata&.values_at(:width, :height)
  end
end
```

**Comment by adrianthedev** [comment]
There's one thing that you should try.

In an initializer (can be in `avo.rb`), you should add this code to make the helper available to Avo's `ApplicationController`.

```ruby
# avo.rb (or a different initializer)
Avo.configure do |config|
  # your configs
end

# during Avo's initializing process we run this callback
Rails.configuration.to_prepare do
  # make all your app's helpers available inside the Avo context
  Avo::ApplicationController.helper Rails.application.helpers
end
```

@gabrielgiroe1 can you please add this in our documentation as well?
Let's add copy with the use case. Maybe from this issue, but just what's important, or maybe try to use a helper method inside an ejected partial (open to suggestions, but it has to be clear to the user reading this).
Also let's add the code that makes this happen.

Closing fornow as I was able to reproduce the fix on my end but please @sedubois let me know if this still persists and you need us to reopen.

**Comment by sedubois** [comment]
Thanks @adrianthedev that helps, [see updated code here](https://github.com/sedubois/avo-trix-demo/commit/0d5045c524c053488c950e1aa454dd9f8d8a5c17), however still 2 issues:
- how to fix the broken layout shown [in this comment](https://github.com/avo-hq/avo/issues/2638#issuecomment-2020653610)? Apparently because of `<trix-editor>` tag having `inline-flex`; it seems to be fixed when manually removing it from the DOM. It seems to be coming from [`Avo::ApplicationHelper#input_classes`](https://github.com/avo-hq/avo/blob/28878382725563e48cb018ef09a9ccb4659a4c69/app/helpers/avo/application_helper.rb#L74).
- wouldn't it make sense for Avo to support Action Text out of the box instead of needing all these monkey-patches in userland?

**Comment by sedubois** [comment]
OK I can workaround the layout issue as follows:
https://github.com/sedubois/avo-trix-demo/commit/59fa6f001faf4fbe41b826cd2d9c67c16569aa8f

But it feels to me like there might be a better fix and all this would better be done within Avo.
