### ISSUE TITLE
Do custom fields currently work with v3?

### ISSUE THREAD

**Issue by rgrapes** [avo-hq/avo#2643]
### Describe the bug

If I generate a custom field using

`rails g avo:field color_picker`

Then set the field as so `field :colour, as: :color_picker`

the colour field is not shown. If I use `as: :text` it shows again.

I'm just asking the question whether you would expect it to work before I spend any more time on it.

### Steps to Reproduce

1. Add any text field to your model.
2. Run 'rails g avo:field color_picker'
3. Add `field :text_field, as: :color_picker`
4. View the page, the field is not shown.
5. Change to `field :text_field, as: :text`
6. View the page, the field is shown.

### Expected behavior & Actual behavior

Behaviour should work as it did in v2. At this stage I haven't changed any of the .html.erb files to give the correct html, it's just using the default template.

### System configuration

** Avo version**

avo-advanced (3.4.0)
      avo (>= 3.4.0)
      avo-dynamic_filters (>= 3.4.0)
      avo-pro (>= 3.4.0)

** Rails version**

rails (7.1.3.2)

** Ruby version**

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No
 - [x] Don't think so

#### field :colour, as: :color_picker

<img width="670" alt="image" src="https://github.com/avo-hq/avo/assets/5386320/167f4f7b-a592-4f8d-9519-9b45cc3970e2">

#### field :colour, as: :text

<img width="760" alt="image" src="https://github.com/avo-hq/avo/assets/5386320/df1219b0-81f7-42dd-aa91-494c5e7d4e64">

#### field :color, as: :color_picker (v2)

<img width="760" alt="image" src="https://github.com/avo-hq/avo/assets/5386320/94f1f631-4b06-4cdc-be08-02fdeb706920">

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello @rgrapes It's working as expected. If the field is generated on avo 3 it should just work, if it was generated on version 2 and migrated to version 3 there are some little adjusts to do on the class definition: https://docs.avohq.io/3.0/avo-2-avo-3-upgrade.html#rename_avo_configuration_classes

**Comment by Paul-Bob** [comment]
@rgrapes can you please confirm if this still an issue?

**Comment by adrianthedev** [comment]
Closing for now. Let's reopen it if we have new information about it.
