### ISSUE TITLE
has_many searchable UX improvement ideas

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2648]
### Feature

In `app/avo/resources/playlist_resource.rb` I have

```
field :posts, as: :has_many, through: :playlist_posts, searchable: true
```

1) Already attached records are visible in search without any indicator of them being already attached:

<img width="1502" alt="Screenshot 2024-03-30 at 09 40 44" src="https://github.com/avo-hq/avo/assets/13472945/238b39db-e877-452b-b2fb-f5111b59a1b1">

2) The experience of attaching multiple records feels tedious 🥵:
1. click "Attach post"
2. click "search"
3. search / click on a record
4. click "attach" 
5. repeat

I think the experience can be improved with checkboxes, and having search directly in the modal ( not double modal )

<img width="249" alt="Screenshot 2024-03-30 at 09 43 27" src="https://github.com/avo-hq/avo/assets/13472945/d26fa887-6f0f-4788-89e8-42bbe28850fb">

**Comment by yshmarov** [comment]
@Paul-Bob thanks! I will update my searchable fields to use `attach_scope`

**Comment by yshmarov** [comment]
In my case `playlist` has many `posts` through `playlist_post`.

to get all the posts (`query`) that are not associated with the current playlist (`parent`), I did:
```
  field :posts, as: :has_many, through: :playlist_posts, searchable: true,
    attach_scope: -> {
      query.where.not(id: parent.playlist_posts.select(:post_id))
    }
```

**Comment by adrianthedev** [comment]
@gabrielgiroe1 can we add an example like this one to the docs? Maybe not quite `playlist_posts` but a `team` has many `members`, and you don't want to add the same member twice.
Please add it to all the places one can attach things multiple times (has many & HABTM, etc.)

Thanks

**Comment by adrianthedev** [comment]
@yshmarov do you think we could automate this inside Avo? like adding this computed query ourselves?
Do you think it will bite us in the but at some point?

**Comment by yshmarov** [comment]
I think updating the docs and examples to include it would be enough :)

**Comment by Paul-Bob** [comment]
I wonder, is there any circumstance where including the attached records on the attach list is desired?

**Comment by adrianthedev** [comment]
yeah, I don't think so, but I'm not completely sure I want to pull the trigger and have this as the default behavior.

On the other hand. it would be cool to have it like that 🤷‍♂️
It would make life so much easier.
