### ISSUE TITLE
Generator not working for model named `DS`

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2649]
### Describe the bug

A Rails magic edge-case bug…

I have model named `DS` at `app/models/ds.rb` with an inflection set:

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "DS"
end
```

Running

```shell
rails generate avo:resource DS
```

results in

```shell
Can't generate fields from model. 'ds.rb' not found!
      create  app/avo/resources/d.rb
      create  app/controllers/avo/ds_controller.rb
```

<details>
<summary><code>d.rb</code></summary>

```ruby
class Avo::Resources::DS < Avo::BaseResource
  self.includes = []
  # self.search = {
  #   query: -> { query.ransack(id_eq: params[:q], m: "or").result(distinct: false) }
  # }

  def fields
    field :id, as: :id
  end
end
```

</details>

<details>
<summary><code>ds_controller.rb</code></summary>

```ruby
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::DsController < Avo::ResourcesController
end
```

</details>

I also tried removing the inflection, but it was still failing, probably due to the model ending with letter s (like plural).

### Steps to Reproduce

1. Add model named `DS` or `Ds`
2. Try to run generator
3. It (partially) fails

### Expected behavior & Actual behavior

It should work like for any other model.

### System configuration
**Avo version**: 3.5.3

**Rails version**: 7.0.8.1

**Ruby version**: 3.1.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Thanks for reporting this @krystof-k.

I'm afraid I don't know why it's failing either. I don't have that much experience with inflections and how Rails handles naming.

We're not going to pursue fixing this as we're working on more pressing issues.
We would merge a PR with this fix if you were to try and submit one.

Will close for now to keep the issue queue free, but LMK if you want me to reopen it.

**Comment by krystof-k** [comment]
Yeah, sure, no worries, I wanted to rename the model anyway :) It's really an edge case, I just thought I would report it. If someone finds it critical it can be reopened.
