### ISSUE TITLE
Pagination design broken in all resources

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#2660]
### Describe the bug
Pagination in all resources is not as per design. It's show number instead of it in a block with `<` and `>` symbols

### Steps to Reproduce
Navigate to any resources and see the pagination in bottom right corner of page.
Repo with the issue https://github.com/SahSantoshh/avo_search

### Expected behavior & Actual behavior

Expected
![Screenshot 2024-04-04 at 5 37 59 PM](https://github.com/avo-hq/avo/assets/17696184/627a4fcf-2f1d-4686-bbe9-a953687e6f55)

Actual

![Screenshot 2024-04-04 at 3 56 07 PM](https://github.com/avo-hq/avo/assets/17696184/bf901478-a57b-49ac-b86f-ce1bcc852265)

### Models and resource files

Please refer the repo for all kind of configurations

### System configuration
**Avo version**: `3.5.5`

**Rails version**: `7.1.3`

**Ruby version**: `3.3.0`

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
Already added above

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@SahSantoshh as a workaround until we fix it lock `pagy` on version `7.0.6`

**Comment by Paul-Bob** [comment]
Let's apply changes for pagy 8 and lock the version to `>=8` https://ddnexus.github.io/pagy/changelog/#version-800

**Comment by adrianthedev** [comment]
When was 8 launched. Didn't we just get the 7 version?

Also, I think the latest version might have some breaking changes and some people won't be able to update their pagy or have to apply the breaking changes. 

Can you please find out when pagy 7 was launched?
If it's in the last 6 months, let's support 7 and 8 of we can. If itms more than 6 months, juat v 8.

WDYT?

**Comment by Paul-Bob** [comment]
7 was released Feb 15
8 was released last week

> Also, I think the latest version might have some breaking changes and some people won't be able to update their pagy or have to apply the breaking changes.

Agree

People using version 8 have no styles for pagination 
![image](https://github.com/avo-hq/avo/assets/69730720/779e9ace-b246-4fcc-8390-aeb03fc9a0c8)

We should support 7 & 8 IMO

**Comment by thiagovsk** [comment]
same here, and this solution works to me

**Comment by adrianthedev** [comment]
Thanks @thiagovsk for confirming. `pagy` 8 should be fully supported as well in the latest `avo` version.
