### ISSUE TITLE
Dynamic Filters not working

### ISSUE THREAD

**Issue by dlupu** [avo-hq/avo#2680]
### Describe the bug

Hy folks, I'm using Avo Advanced and I would like to be able to filter by the value of a field. 

I've followed the instructions on https://docs.avohq.io/3.0/dynamic-filters.html and I've added `filterable: true` on the field, and I can add via the UI a filter on that field.

I've also whitelisted the field using ransackable attributes

In Avo UI, I can add the filter but it has no effec on the results. 

Logs, when searching for the string `xyz` in the `auditable_type` field, show the DB request do not use the filters: 

```
Processing by Avo::CustomAuditsController#index as HTML
14:59:52 server.1   |   Parameters: {"filters"=>{"auditable_type"=>{"contains"=>["xyz"]}}, "host"=>"localhost"}
14:59:52 server.1   |   CustomAudit Count (36.3ms)  SELECT COUNT(*) FROM "custom_audits"
14:59:52 server.1   |   CustomAudit Load (287.9ms)  SELECT "custom_audits".* FROM "custom_audits" ORDER BY custom_audits.created_at desc LIMIT $1 OFFSET $2  [["LIMIT", 24], ["OFFSET", 0]]

```

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### System configuration
**Avo version**: 3.4.1

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
what's the resource like? can you share that `filterable` field declaration?

**Comment by dlupu** [comment]
```
class Avo::Resources::CustomAudit < Avo::BaseResource
  # self.includes = [:user]
  # self.search = {
  #   query: -> { query.ransack(id_eq: params[:q], m: "or").result(distinct: false) }
  # }

  def fields
    field :id, as: :id, filterable: true
    field :auditable_id, as: :number, filterable: true
    field :auditable_type, as: :text, filterable: true
    field :user_id, as: :number, filterable: true
    field :user_type, as: :text, filterable: true
    field :username, as: :text, filterable: true
    field :action, as: :text, filterable: true
    field :version, as: :number, filterable: true
    field :comment, as: :text, filterable: true
    field :remote_address, as: :text, filterable: true
    field :request_uuid, as: :text, filterable: true
    field :audited_changes, as: :code, language: 'javascript' do
      if record.audited_changes.present?
        JSON.pretty_generate(record.audited_changes.as_json)
      end
    end
    field :stack, as: :textarea
    field :created_at, as: :date_time
  end
end
```

**Comment by dlupu** [comment]
in the Custom Audit model I've added the ransackable methods

```
 def self.ransackable_attributes(auth_object = nil)
    [
      :id,
      :auditable_id,
      :auditable_type,
      :user_id,
      :user_type,
      :username,
      :action,
      :version,
      :comment,
      :remote_address,
      :request_uuid,
      :created_at
    ]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
  ```

**Comment by adrianthedev** [comment]
FYI, you could use `with_options` to DRY it up a bit

```ruby
def fields
  with_options filterable: true do
    field :id, as: :id
    field :auditable_id, as: :number
    field :auditable_type, as: :text
    field :user_id, as: :number
    field :user_type, as: :text
    field :username, as: :text
    field :action, as: :text
    field :version, as: :number
    field :comment, as: :text
  end
  ...
```

**Comment by adrianthedev** [comment]
Can you try to whitelist everything using this?

```ruby
  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end
```

**Comment by adrianthedev** [comment]
I think that they should be strings. can you try your other setting but with strings instead of symbols?

**Comment by dlupu** [comment]
Sorry for the bug report, I simply did not expect that to be the cause.

**Comment by adrianthedev** [comment]
@gabrielgiroe1, we should add this warning to the dynamic filters page. The attributes should be strings not symbols (which annoys me a lot).
