### ISSUE TITLE
New & different paging link problem: links are very small numerals with no styling

### ISSUE THREAD

**Issue by brandondrew** [avo-hq/avo#2688]
### Describe the bug

The paging links, upon upgrading, are very very small.
<img width="310" alt="image" src="https://github.com/avo-hq/avo/assets/9854/a69f9fd2-7c81-4733-b7b4-3991ea915ea0">

### Steps to Reproduce
1. Upgrade to 2.49.0
2. Open an Avo resource list with multiple pages
3. Look at the paging links at the bottom

### Expected behavior & Actual behavior

I expected larger, styled links.  These very small numerals are really too small for users to use.

### System configuration
**Avo version**: 2.49.0

**Rails version**: 7.0.8.1

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin21]

**License type**:

 - [x] Community

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] None that seem relevent.

I've ejected a view or two but none related to the paging.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

Somewhere between medium and high.  I'm sure I can manually style them but that seems likely to break once this is fixed.

**Comment by krystof-k** [comment]
I'm experiencing the same on 3.6.1.

**Comment by adrianthedev** [comment]
Please try `bundle update pagy` (should be on v8).

They made some changes to drop some CSS... things.

**Comment by krystof-k** [comment]
Yeah, but that's what probably caused this (I just upgraded to latest – 8.1.2).

**Comment by adrianthedev** [comment]
hmmm. grrrr. we just fixed it once like yesterday
https://github.com/avo-hq/avo/pull/2525

Please try some version of pagy 7.

We will support both of them (https://github.com/avo-hq/avo/issues/2660#issuecomment-2042708496).

**Comment by brandondrew** [comment]
@adrianthedev  maybe I want an earlier version of 8 before 8.1.2?  Is there a version you know to be working?

**Comment by adrianthedev** [comment]
I'm on 7.0.6 and the pagination looks good.

We'll provide support for pagy 8 in a short while.

**Comment by brandondrew** [comment]
Rebooting with 7.0.6 still gives me the results seen in the latest screenshot.  I see that in both Safari and SIdekick (which is basically Chrome).  From playing with the CSS in the Inspector, it appears that both the `<span>` and `<a>` elements are getting the same padding applied to them. 

```
<span class="page prev disabled">
  <a role="link" aria-disabled="true" aria-label="Previous">&lt;</a>
</span>
```

 If I select either one and disable the padding, it affects the other.  I think the CSS rule might need to be tweaked to ensure that it only affects the link:
 
 
<img width="635" alt="image" src="https://github.com/avo-hq/avo/assets/9854/ea48c887-92d6-4296-ab15-6963fbcebdfe">

**Comment by adrianthedev** [comment]
Are you sure @brandondrew?

[Avodemo](https://github.com/avo-hq/main.avodemo.com/blob/main/Gemfile.lock#L272) is on 7.0.11 and [they look fine](https://avodemo.com/avo/resources/projects).

Have you overriden any partials or components that tackle the pagination?

The next step is to see a reproduction repo with this issue so we can check out.
