### ISSUE TITLE
`link_to_record` should override link to association or throw warning

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2689]
### Describe the bug

Given

```ruby
class Avo::Resources::Example < Avo::BaseResource
  def fields
    field :type,
      as: :belongs_to,
      link_to_record: true
  end
end
```

still links to the `Type` association, not to the `Example` record.

### Steps to Reproduce

1. Add `link_to_record: true` to a `belongs_to` type
2. Try to click the link
3. You end up on the association, not the record

### Expected behavior & Actual behavior

It should either override the link to association or throw a warning.

### System configuration
**Avo version**: 3.6.1

**Rails version**: 7.0.8.1

**Ruby version**: 3.2.3

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yeah, we wrote in the docs that that option is available only on the `id,` `text`, and `gravatar` fields.

I understand your feedback that it should raise a warning, but we don't yet have a mechanism to mark fields which universal options they support.

TBH, we'd welcome a PR to support `link_to_record` on `belongs_to`. I could see that being helpful.

#### Approach

We should add [this](https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/text_field/index_component.html.erb#L7) [here](https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/belongs_to_field/show_component.html.erb#L2).

**Comment by krystof-k** [comment]
Sorry, I missed that. I'll try a PR to make it work.
