### ISSUE TITLE
No documentation/demo/testing for Action Text has_rich_text

### ISSUE THREAD

**Issue by sedubois** [avo-hq/avo#2714]
### Describe the bug
I could find neither in the [documentation](https://docs.avohq.io/3.0/) nor in the [Avo Demo](https://github.com/avo-hq/main.avodemo.com) nor in the test suite how to hook up a resource with Action Text `has_rich_text` attributes.

### Expected behavior
- [x] the documentation explains how to configure an Avo resource field to show and edit Action Text rich text as defined by the presence of `has_rich_text` in the Rails model
- [ ] when the model contains `has_rich_text :body` (*), `rails g avo:resource` generates an Avo field of the correct type and with the correct parameters (currently it generates `field :body, as: :text`). NB: The closest existing field name is `:trix` but the field name `:rich_text` would make more sense in my view (this field is about more than just the front-end editor, and using another name than `trix` also opens the door to other editors such as prosemirror, tiptap, rhino).
- [x] the Avo field works without the presence of an `attachment_key` parameter and without the presence of `has_many_attached` on the Rails model
- [x] the demo has a model with `has_rich_text`, with support for rich text editing and embeds of images and other media types; the corresponding Avo resource has a corresponding field defined, allowing to view and edit the rich text, without needing an `attachment_key` parameter
- [x] the demo DB has an `action_text_rich_texts` table and other files generated by `action_text:install`, e.g. `app/views/active_storage/blobs/_blob.html.erb`
- [ ] the test suite tests that Avo fields are created appropriately for models with `has_rich_text`

### Models and resource files
```rb
class Post < ApplicationRecord
  has_rich_text :body
end
```

### Additional context
The documentation and demo do make use of a `trix` Avo field ([example](https://github.com/avo-hq/main.avodemo.com/blob/795b0c27073f97c6fae19d203f2db5a2ca2d4720/app/avo/resources/post.rb#L30)), but only hooked up into regular `:text` ActiveRecord attributes, not Action Text ([example](https://github.com/avo-hq/main.avodemo.com/blob/795b0c27073f97c6fae19d203f2db5a2ca2d4720/db/schema.rb#L111)).

The Avo Demo DB schema does not contain an `action_text_rich_texts` table nor other Action Text config files. It looks like `rails action_text:install` was not run.

#### Impact
 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

Our current workaround is to suspend our Avo migration and continuing to rely on Administrate, due to some outstanding questions with the Avo Trix field, primarily related to the management of embeds. We also tried to check the situation with the latest main commit but encountered [issues](https://discord.com/channels/740892036978442260/1231172900535668736/1231529602841710653). Clearer documentation/demo on the subject would be helpful.

(*) or other equivalent definitions, such as `translates :body, backend: :action_text` in the case of [this gem](https://github.com/sedubois/mobility-actiontext) I wrote. In all cases the rich text is available as `record.body` or `record.rich_text_body` and returns an object of type `ActionText::RichText`.

**Comment by sedubois** [comment]
I would love to see this fixed. Lack of action text support prevents us from finishing our migration to Avo started a few months ago.

**Comment by adrianthedev** [comment]
Hey @sedubois.

It's true we didn't have all of these documented. I [added them now](https://github.com/avo-hq/docs.avohq.io/commit/a783cbba20b5bb096efec6692e8820854a8160cd).
I also added a [demo app](https://github.com/avo-hq/trix-field-demo) with the source code available (it's not that much).

We are a bit squeezed on time and can't add a `has_rich_text` test case on the `dummy` app, but we'll gladly take on a PR, please.
We'll definitely take a helping hand on tweaking the generator to use the trix field instead of `:text`. You're 100% on point with that suggestion.

Please let me know if there's anything else we can help you with in regards with documentation about Active Text and Action Storage, otherwise I'll close this to keep the issue queue clean.

**Comment by sedubois** [comment]
@adrianthedev it's great to have a first Avo demo with `has_rich_text`, thanks!

It does demonstrate that embed captions don't yet work, the caption text is displayed in the wrong place and breaks when re-saving the resource:
https://trix.avodemo.com/avo/resources/posts/1/edit

![Screenshot 2024-05-23 at 12 55 20](https://github.com/avo-hq/avo/assets/4217871/d092a529-1307-43c6-9d85-1b23389f9cb3)

It is also mentioned in this comment:
https://github.com/avo-hq/avo/issues/2715#issuecomment-2090643546

The other issue is this one with custom embeds, I don't know how to fix it but provided a repro:
https://github.com/avo-hq/avo/issues/2627

**Comment by adrianthedev** [comment]
For the custom embeds we'd need to dig in deeper and that takes time. Would you be open to book some paid support so we can look into it further?
