### ISSUE TITLE
ID field disappeared?

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2716]
### Describe the bug

I have no IDs visible (it just shows empty column on index view).

### Steps to Reproduce
1. Add this
   ```ruby
   class Avo::Resources::User < Avo::BaseResource
     def fields
       field :id,
         as: :id
     end
   end
   ```

2. Go to index:
   ![image](https://github.com/avo-hq/avo/assets/11633481/898e2090-f7a7-4416-83d8-73d923cfdbfd)

3. Go to show:
   ![image](https://github.com/avo-hq/avo/assets/11633481/1f40c449-bbd1-4f76-9a82-81fa1939d9b0)

### System configuration
**Avo version**:
3.6.1
**Rails version**:
7.0.8.1
**Ruby version**:
3.2.3
**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by krystof-k** [comment]
Yeah, of course, *** inflector acronyms… 😡

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "ID"
end
```

**Comment by adrianthedev** [comment]
Good to know!
Thanks for getting back to us with the resolve.

How did that influence it?
I'm trying to understand the implications so we add them to the docs.

**Comment by krystof-k** [comment]
I haven't dived deep enough, but I guess you are doing something like `id.classify` which would result in `ID` instead of `Id` and that broke it.

I'm also trying to understand the whole inflector thing and I'm more and more confused, you can follow along in rails/rails#51630. But I guess the answer is "don't use custom inflections or you may break Avo".

**Comment by adrianthedev** [comment]
Oh, yeah. that could be it.
our field class is `Avo::IdField`. Your inflection rule might turn it into `Avo::IDField` which doesn't exist.

https://github.com/avo-hq/avo/blob/main/lib/avo/fields/id_field.rb#L3

**Comment by krystof-k** [comment]
I think it is something else (maybe [this](https://github.com/avo-hq/avo/blob/5907bc58b5dc481cca0fc3d96f3fa5a5216de9c9/app/controllers/avo/base_controller.rb#L587)?), because for autoloading I have fixed it in a custom inflector:

```ruby
"**/gems/avo-*/app/components/avo/fields/id_field" => "IdField"
```

<details>
<summary><em>Custom Zeitwerk inflector to override conflicts</em></summary>

```ruby
# config/initializers/zeitwerk.rb

# List of file glob patterns and their corresponding camelized class names
OVERRIDES = {
  "**/gems/actionmailbox-*/app/models/action_mailbox/inbound_email/message_id.rb" => "MessageId",
  "**/gems/avo-*/app/components/avo/fields/id_field" => "IdField",
  "**/gems/avo-*/app/helpers/avo/url_helpers.rb" => "UrlHelpers"
}.freeze

# Override the default Zeitwerk inflector to use the overrides
Rails.autoloaders.each do |autoloader|
  autoloader.inflector = Class.new(Zeitwerk::Inflector) do
    define_method(:camelize) do |basename, abspath|
      # Check if the file path matches any of the overrides
      OVERRIDES.each do |glob_pattern, camelized|
        if File.fnmatch?(glob_pattern, abspath)
          # Return the hard-coded camelized class name
          return camelized
        end
      end
      # For all other files, use the default ActiveSupport::Inflector.camelize
      basename.camelize
    end
  end.new
end
```

</details>

I guess that for you as an author of a gem/engine, there are only two options:
- thoroughly avoid using inflector methods throughout the codebase (and even there it won't be 100% I guess, at least you cannot control your dependencies etc.) + recommend using custom autoloader inflector as I did in case of conflicts
- recommend not to use any custom inflection rules at all in the docs

I'll probably go with the second option and remove all inflection rules in our app.

**Comment by krystof-k** [comment]
Or, maybe, it could be possible to [monkey patch](https://medium.com/rubycademy/refine-and-using-methods-in-ruby-part-i-2aef6d7a4325) the inflector methods on the String class not to use the global inflector? But that's hacky as hell…

**Comment by adrianthedev** [comment]
TBH, I'd just use the Rails defaults to not use that inflection. As Rafael Franca said, that will break some stuff. Same with Avo.
