### ISSUE TITLE
Host app icons override avo icons

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#2729]
### Describe the bug

If the host app has an icon with the same filename as an icon in avo, the host app icon will be used instead of the avo one.

### Steps to Reproduce
1. Find an index view in avo and make sure you can see the edit icon
2. Upload a file named `edit.svg` to the `app/assets/images` directory of your host app
3. Reload the page - the edit icon should have changed to the icon you just uploaded.

### Expected behavior & Actual behavior

I'd expect avo icons to be used (within avo), but instead the host app icon is used.

### System configuration
**Avo version**: 3.6.1

**Rails version**: 7.0.8.1

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

Here's an example where I've added a different `edit.svg` file to `app/assets/images`

![Screenshot 2024-04-30 at 12 54 00](https://github.com/avo-hq/avo/assets/111963/35fb4cfb-26ef-4dbc-88b8-a38b35ff05b5)

### Additional context

I had a quick look at the code and it seems like this is happening deliberately, because of code in `lib/avo/svg_finder.rb`. I think that's wrong though because it's not obvious to users that this will happen. If you do want this behaviour, could avo-specific icons be in a namespaced directory like `app/assets/images/avo`?

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
> I had a quick look at the code and it seems like this is happening deliberately, because of code in lib/avo/svg_finder.rb. I think that's wrong though because it's not obvious to users that this will happen. If you do want this behaviour, could avo-specific icons be in a namespaced directory like app/assets/images/avo?

Not sure it was deliberate. We wanted a quick way to reference the icons. If we were to move them to a different directory then all the icons need `avo/` prepended to each icon declaration.

I do see the need for that, but I'm not sure how we could support this without breaking a lot of the behaviour of the current apps.
I'll think about it, and I'm open to suggestions.

**Comment by adrianthedev** [comment]
I think I know how to fix this.

Avo can use only the prefixed versions of the icon path `heroicons/outline/edit` and let the parent app override the simple one `edit` freely.

How does that sound @iainbeeston?

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2761
