### ISSUE TITLE
uninitialized constant Avo::Fields::TrixField::ActionText in avo (3.6.4)

### ISSUE THREAD

**Issue by therabidbanana** [avo-hq/avo#2738]
### Describe the bug

When editing a resource that has had a working Trix editor with version 3.6.4, we encounter an undefined constant referring to ActionText:

 lib/avo/fields/trix_field.rb:28:in `is_action_text?'

### Steps to Reproduce
1. Set up project without Activetext, latest avo
2. Create a trix editor field
3. Open the edit form for a resource with text already set via trix editor

### Expected behavior & Actual behavior

Actiontext installation should be optional or there should be clear documentation requiring it. Installing the actiontext gem and enabling the engine in config/application.rb is a sufficient workaround to allow the system to work again.

### System configuration

**Avo version**:
3.6.4

**Rails version**:
(7.1.3.2, notably without actiontext as it was upgraded from an earlier Rails app)

**Ruby version**:
3.3.1

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No
 
#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@therabidbanana just made an PR that should fix it. 

[Rails `7.1.3.2`](https://rubygems.org/gems/rails/versions/7.1.3.2) have `actiontext= 7.1.3.2` as runtime dependency, shouldn't have the constant defined?

**Comment by Paul-Bob** [comment]
No, you don't need to require rails, I wrongly assumed you're already requiring rails.
