### ISSUE TITLE
record_link format_using doesn't work

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#2747]
### Describe the bug

This works:

```ruby
field :item, as: :record_link, add_via_params: false, name: 'Item', only_on: %i[index show]
```

This doesn't:

```ruby
field :item, as: :record_link, add_via_params: false, name: 'Item', only_on: %i[index show],
  format_using: -> { record.item_id }
```

Whatever I use under `format_using`, even if just a string – `format_using: -> { 'test' }` – an exception happens:

```
Showing /<REDACTED>/vendor/bundle/ruby/3.1.0/gems/avo-3.7.0/app/views/avo/base/index.html.erb where line #2 raised:

undefined method `new' for nil:NilClass

    @label ||= resource_class.new(record: @record)&.record_title
```

### Steps to Reproduce

N/A

### Expected behavior & Actual behavior

Record link is generated but instead of using record title it uses `format_using` output.

### Models and resource files

N/A

### System configuration

**Avo version**: 3.7.0
**Rails version**: 7.1.3.2
**Ruby version**: 3.1.5

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

N/A

### Additional context

N/A

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @xeron.
Instead of returning `record.item_id` return an actual record. An ActiveRecord object, not an association foreign_key.
For you it might be something like `record.item`.

[Docs](https://docs.avohq.io/3.0/fields/record_link.html#:~:text=You%20give%20it%20a%20record%20and%20it%20will%20link%20to%20it)

**Comment by xeron** [comment]
> ```ruby
> format_using
> ```

My goal is to provide the link to `record.item` but format the visual representation as ID instead of `record.title` (default). So I'm trying to use `format_using` (https://docs.avohq.io/3.0/field-options.html) and it doesn't work.

My understanding is `format_using` should not affect the link itself in any way. It could be any string.

**Comment by adrianthedev** [comment]
That is partially correct. `format_using` will output the value of the block, not the label of that record.
So when you tell it ` format_using: -> { record.item_id }`, the `value` becomes an integer and it will try to create a link from that integer and fail.
It expects it to receive a record.
You can see the implementation here https://github.com/avo-hq/avo-record_link_field

What it could use is a field option where you can specify which property to use, somewhere around [here](https://github.com/avo-hq/avo-record_link_field/blob/main/lib/avo/record_link_field/fields/record_link_field/common_record_link_component.rb#L24).

```ruby
# maybe something like this?

field :item, as: :record_link, record_property: :item_id
```

Would you be able to try to do that in a PR?

**Comment by xeron** [comment]
> So when you tell it ` format_using: -> { record.item_id }`, the `value` becomes an integer and it will try to create a link from that integer and fail.

From my understanding of `format_using` and other field options that should not be the case. Field accepts a block to generate the value for the functionality you described? E.g. this should be possible:

```ruby
field :item, as: :record_link, add_via_params: false, name: 'Item', only_on: %i[index show],
  format_using: -> { record.item_id || 'or whatever I want here' } do
    record.item # this is default of course because field first argument is already `item`, but I can use any logic here
end
```

**Comment by xeron** [comment]
I took a look at the code and seems like it happens because in the context of the RecordLink field the `record` is `@field.value`. Even if we use `value` as a `label` it won't work because local context `record` will be wrong too.

This made me realize that `format_using` probably doesn't work for `belongs_to` fields either, and it indeed doesn't:

```ruby
field :car_class, as: :belongs_to, format_using: -> { 'test' }
```

```
undefined method `name' for "test":String

        @record.send title
               ^^^^^
```
