### ISSUE TITLE
Rails tests fail when record_link gem is added

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#2748]
### Describe the bug

After updating `avo` to 3.7.0 and adding `avo-record_link_field` gem rails tests don't work anymore:

```
$ ./bin/rails test -v
/<REDACTED>/vendor/bundle/ruby/3.1.0/gems/avo-3.7.0/lib/avo/plugin_manager.rb:12:in `register': uninitialized constant Avo::PluginManager::OpenStruct (NameError)

      @plugins << OpenStruct.new(klass: plugin_klass, priority: priority)
                  ^^^^^^^^^^
	from /<REDACTED>/vendor/bundle/ruby/3.1.0/gems/avo-record_link_field-0.0.1/lib/avo/record_link_field/railtie.rb:5:in `block in <class:Railtie>'
```

Removing `avo-record_link_field` gem from `Gemfile` fixes the issue.

### Steps to Reproduce

N/A

### Expected behavior & Actual behavior

Rails tests work.

### Models and resource files

N/A

### System configuration

**Avo version**: 3.7.0
**Rails version**: 7.1.3.2
**Ruby version**: 3.1.5

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

N/A

### Additional context

N/A

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Should be out in 3.7.1 soon.
