### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by manuelmeurer** [avo-hq/avo#2764]
### Describe the bug

I'd like to add basic auth to accessing Avo, but when I try the most straightforward approach, an error occurs.

### Steps to Reproduce

1. Add basic auth as detailed in https://blog.arkency.com/common-authentication-for-mounted-rack-apps-in-rails/

```ruby
authenticated =
  lambda do |app|
    Rack::Builder.new do
      if Rails.env.production?
        use Rack::Auth::Basic do |username, password|
          {
            username => "ADMIN_USERNAME",
            password => "ADMIN_PASSWORD"
          }.map { ActiveSupport::SecurityUtils.secure_compare _1, ENV.fetch(_2) }
           .all?
        end
      end
      run app
    end
  end

Rails.application.routes.draw do
  mount authenticated[Avo::Engine], at: Avo.configuration.root_path
end
```

2. Start Rails server
3. Go to 'localhost:3000/avo'

```
NameError - undefined local variable or method `avo' for an instance of Avo::HomeController`
in lib/avo/configuration.rb#82
```

### Expected behavior & Actual behavior

No error

### Models and resource files

Fresh install of Avo, app only has a few models which I'm sure are not the cause of this error.

### System configuration

**Avo version**: 3.7.4

**Rails version**: 7.1.3.2

**Ruby version**: 3.3.1

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by manuelmeurer** [comment]
I also tried ading basic auth like this, but it doesn't have any effect:

```
Avo::Engine.config.app_middleware.use Rack::Auth::Basic do |username, password|
  username == "admin" && password == "password"
end
```

**Comment by adrianthedev** [comment]
I added this article [here](https://docs.avohq.io/3.0/guides/basic-authentication.html).

Apologies about the delay.

**Comment by manuelmeurer** [comment]
Thanks @adrianthedev, after opening this issue I got it to work with `http_basic_authenticate_with` in Avo::ResourcesController but I guess using a concern is even cleaner.

**Comment by adrianthedev** [comment]
yeah, that will work too!

I'd like to push one more update at some point where all engines (pro, advanced, dynamic_filters, etc.) inherit from `Avo::ApplicationController` so we have just one point of contact.
Don't worry about it now, nobody's going to find those routes to try to access.
