### ISSUE TITLE
add `link_to` in a dropdown

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2775]
### Feature

Currently there is not way to have link_to's in a dropdown
Either we get a separate dropdown wrapper, or we find a way to include it in the `actions_list`?

```ruby
class Avo::Resources::Abc < Avo::BaseResource
self.index_controls = -> do
    action Avo::Actions::Action1, title: "Action 1"
    link_to "a", "https://fish.com"
    actions_list exclude: []
  end
```

### Current workarounds
Create a dedicated action class & use redirect response in an action? https://docs.avohq.io/3.0/actions.html#redirect_to 

but this will always give you a confirmation screen before doing the redirect?

**Comment by Paul-Bob** [comment]
Hello @pjmuller I think the workaround is a great solution and you can improve the confirmation by using `self.no_confirmation = true` 

https://docs.avohq.io/3.0/actions.html#customization

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2784
