### ISSUE TITLE
autogrow text areas

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2795]
it would be very comfortable if textarea could autogrow. something like this: https://stimulus-textarea-autogrow.stimulus-components.com/

<img width="1352" alt="Screenshot 2024-05-22 at 16 02 55" src="https://github.com/avo-hq/avo/assets/13472945/218aed6b-89d1-4374-8789-4170f77d5484">

**Comment by adrianthedev** [comment]
Would you be able to send in a PR? 🙏
