### ISSUE TITLE
`self.authorization_policy` doesn't apply to left side menu `Policy#index?` action.

### ISSUE THREAD

**Issue by mtomov** [avo-hq/avo#2799]
### Steps to Reproduce

1. Have an `application_policy`

```ruby
class ApplicationPolicy
  attr_reader :user, :record

  def initialize(user, record)
    @user = user
    @record = record
  end

  def index?
    false # this is important
  end
end
```

2. Create a custom policy

```ruby
class AvoPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end

  def index?
    true # note this
  end
end
```

3. Assign the custom policy to a resource

```ruby
class Avo::Resources::Recording < Avo::BaseResource
  self.authorization_policy = AvoPolicy
end
```

4. Go to admin UI, and check the menu on the left - the resource won't be visible. 

5. Change

```ruby
  def index?
    false # this is important
  end
```
to `true`, -> and the resource will be visible in the left menu.

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced
#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @mtomov can I please ask you to create a repo with those instructions so we can quickly clone and run it?
Thank you!
