### ISSUE TITLE
Sort dynamic filters based on manual order i.s.o. alphabetic

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2802]
### Feature
The dropdown of dynamic filters is in alphabetic order while it would make more sense to have it in the same order as the columns are displayed (and/or are defined in the `resource`.`fields` method)

Though I also understand this gets tricky quickly with hidden fields etc.

### Current workarounds
None

### Screenshots or screen recordings
![Screenshot 2024-05-23 at 17 25 51](https://github.com/avo-hq/avo/assets/1681106/7667f514-ed87-4311-883f-b685d72d8df2)

cfr screenshot would be nice to have
- firstname
- lastname
- gender

### Additional context
Low prio, mainly interested to know if there are some workarounds

**Comment by adrianthedev** [comment]
Currently, the filters are alphabetically ordered.
There's a PR that enables taking a lot more control and it will allow you to do that.

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2268, so please track that one.
