### ISSUE TITLE
dynamic filters: convert `params` to replicable hash

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2810]
### Feature
The ` avo-dynamic_filters` project transform URL query paramaters like `filters[lastname][contains][]=Bla` into a (Ransackable) ActiveRecord Scope.

We would like to do this transformation also in other parts of our codebase (e.g. in a cron where we want to send a mailing)

Can you make a method the ` avo-dynamic_filters` that does transformation public? Or have another way to capture the actual ransack parameters used?

**Comment by adrianthedev** [comment]
@pjmuller please try `Avo::DynamicFilters::Filter.unpack_params(params)`. I should return an array of `Avo::DynamicFilters::ParamFilter` instances which you should be able to work with.

Let me know if that helps and close it if so.

```
["parsed_params->", [#<Avo::DynamicFilters::ParamFilter:0x0000000306fc4780 @condition="is", @id="status", @value="closed">, #<Avo::DynamicFilters::ParamFilter:0x0000000306fc4758 @condition="is", @id="stage", @value="discovery">, #<Avo::DynamicFilters::ParamFilter:0x0000000306fc4730 @condition="is", @id="country", @value="AF">]]
```

**Comment by adrianthedev** [comment]
I'm going to close this one for now

**Comment by pjmuller** [comment]
@adrianthedev and @Paul-Bob ,

I tried
```ruby
Avo::DynamicFilters::Filter.unpack_params({"filters"=>{"boolean_column"=>{"is_false"=>[""]}}}) #  response = []
Avo::DynamicFilters::Filter.unpack_params({"my_boolean_column"=>{"is_false"=>[""]}}) # response = []

# or inside of a resource
  def fields
    Avo::DynamicFilters::Filter.unpack_params(params) # => []
  end
```

what am I doing wrong?

**Comment by Paul-Bob** [comment]
Hello @pjmuller

We parse the params and build the query on the [`apply_dynamic_filters` method](https://github.com/avo-hq/avo-dynamic_filters/blob/main/lib/avo/dynamic_filters/concerns/base_controller_extensions.rb#L9)

You can extract whatever logic you need and create a custom method.

I don't want to expose any `avo-dynamic_filters` code so let me know how it goes and if you need assistance.

**Comment by adrianthedev** [comment]
I think what @pjmuller needs is an exposed method that we use and they could use as well.
So if we change it, they get the benefit.

But Paul is right. I don't think we'll change the structure of the params for the dynamic filters anytime soon.
We spent some time on it to ensure it will be good to use for a long time.
