### ISSUE TITLE
Actions: Stimulus js integration

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2811]
### Feature
Similar to what you did in https://docs.avohq.io/3.0/stimulus-integration.html (and example in the avo main demo @ `courses` resource)

make it possible to do this within the action modal forms as well

### Current workarounds
?

**Comment by adrianthedev** [comment]
Closed by https://github.com/avo-hq/avo/pull/2079
Docs https://docs.avohq.io/3.0/stimulus-integration.html#assign-stimulus-controllers-to-resource-views
