### ISSUE TITLE
UI: posts list - card view - sort buttons overflow

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#2814]
<img width="805" alt="Screenshot 2024-05-27 at 21 47 24" src="https://github.com/avo-hq/avo/assets/13472945/337e0bf4-c56c-4b0c-b195-2c7063186ae1">

**Comment by Paul-Bob** [comment]
![Image](https://github.com/user-attachments/assets/2ab79c4e-a27a-4cc9-9e75-e22a1b29e7bb)


This is already fixed
