### ISSUE TITLE
Dynamic filter with enum, doesn't filter data

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#2822]
### Describe the bug

When I try to filter data with enum type using dynamic filter, it doesn't work. I might be doing something wrong but not sure what's missing there.

### Steps to Reproduce
1. Add filter using dynamic filter for enum
2. select enum type filter and choose of option
3. check the result

It would be better if you guys check with the repo I have created, please be free to make any kind of changes
https://github.com/SahSantoshh/avo_search 

### Expected behavior & Actual behavior
![Screenshot 2024-05-30 at 8 43 05 PM](https://github.com/avo-hq/avo/assets/17696184/6c291d14-3535-4036-8e3c-878d249f75c6)

Expected Result
- It should filter the data with enum type data

### Models and resource files
Resource file

```ruby
  def fields
    field :id, as: :id
    field :status,
          as: :status,
          except_on: %i[forms],
          neutral_when: [:UnReconciled],
          success_when: [:Reconciled],
          sortable: true,
          filterable: true

    field :status,
          as: :select,
          enum: Provider.statuses.keys,
          default: 'UnReconciled',
          only_on: :forms

    field :name, as: :text
    field :email, as: :text
   ....
```

Model
```ruby
  enum :status, { UnReconciled: 0, Reconciled: 1 }, default: :UnReconciled

  validates :name, presence: true
  monetize :amount_cents, as: :amount, default: 0
  ....
```

### System configuration
**Avo version**: 3.5.8

**Rails version**: 7.1.3

**Ruby version**: 3.3.0r

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Possible correlation: https://discord.com/channels/740892036978442260/1201874761546735636/1260949982886756443

**Comment by SahSantoshh** [comment]
Resource
```ruby
    field :status_check,
          as: :badge,
          options: {
            success: 'Reconciled',
            neutral: 'UnReconciled'
          },
          sortable: true

    field :status,
          as: :select,
          enum: Provider.statuses.keys,
          default: 'UnReconciled',
          hide_on: [:index, :show],
          filterable: true
```

Model

```ruby
class Provider < ApplicationRecord
  enum :status, { UnReconciled: 0, Reconciled: 1 }, default: :UnReconciled

  validates :name, presence: true
  monetize :amount_cents, as: :amount, default: 0

  class << self
    def ransackable_attributes(_auth_object = nil)
      %w[id name email amount status]
    end

    def ransackable_associations(_auth_object = nil)
      %w[]
    end
  end

  def status_check
    status
  end
end
```

There's weird behaviour

![Screenshot 2024-07-13 at 1 50 43 AM](https://github.com/user-attachments/assets/4ace04ad-c8b0-4117-a3ec-473ebd9dacec)

![Screenshot 2024-07-13 at 1 54 55 AM](https://github.com/user-attachments/assets/c02432db-3ac7-46be-970e-50303b0ee3c1)


![Screenshot 2024-07-13 at 1 48 34 AM](https://github.com/user-attachments/assets/6e5c78cc-5682-4416-ae57-bebd8c90dfcd)

**Comment by SahSantoshh** [comment]
Found interesting bug in dynamic filter

### works well for 1st option

![Screenshot 2024-07-13 at 4 13 18 PM](https://github.com/user-attachments/assets/d2146a5d-b8df-469d-ac92-23299c02f7e1)
![Screenshot 2024-07-13 at 4 13 51 PM](https://github.com/user-attachments/assets/fe05298a-c5a8-4c3b-b212-943d4b5586de)

----

### now it's again using same value for all

![Screenshot 2024-07-13 at 4 14 07 PM](https://github.com/user-attachments/assets/29118adc-fd3b-423b-baec-a443bc9776a4)
![Screenshot 2024-07-13 at 4 14 25 PM](https://github.com/user-attachments/assets/d4f0716f-86d3-46c0-a354-f9bf947ab58c)

----

 ### again works for first option

![Screenshot 2024-07-13 at 4 14 40 PM](https://github.com/user-attachments/assets/bd9356a3-46c8-4d0a-80bf-9049ff899d52)
![Screenshot 2024-07-13 at 4 14 49 PM](https://github.com/user-attachments/assets/0baa8dc4-6a3d-46d0-a0a4-1c1b1b892485)

----

### same issue as previous

![Screenshot 2024-07-13 at 4 15 05 PM](https://github.com/user-attachments/assets/f8ffc110-cf54-4d80-8fe9-581c0f0f9ad4)
![Screenshot 2024-07-13 at 4 15 18 PM](https://github.com/user-attachments/assets/1aa3570d-8245-482c-8830-c92821145c1b)

**Comment by binarygit** [comment]
Hey @SahSantoshh You'll need to pass in the enum hash for filtering to work in a badge field. It's because the badge field doesn't know what the enum value is mapped to in the database.
```ruby
  enum :status, { UnReconciled: 0, Reconciled: 1 }
 ```
 Here, 0 is the value in database for UnReconciled and 1 for Reconciled. Ransack needs to get the database value to search these correctly but Avo sends in the `string` value for badge fields. This is why the filtering is not working correctly.
 
 For filtering the badge field, you can pass `options to filterable`:
 ```ruby
     field :status, as: :badge, options: {neutral: "UnReconciled", success: "Reconciled"},
      filterable: {
        options: ::Provider.status
      }
 ```
 or you could create a filter defined in the filters method:
 ```ruby
   def filters
    dynamic_filter :status,
      type: :select,
      options: ::Provider.status,
      query_attributes: [:status]
  end
  ```
  
  I'm closing this issue for now but feel free to comment here and let us know if you have any queries or problems :smile:
