### ISSUE TITLE
Rails 7.2 beta - undefined method klass for nil

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#2830]
### Describe the bug

Hello Guys, i have upgrade my rails app to 7.2 beta and there is a bug with the associations (_reflections method):

`undefined method klass for nil` when we have some association field in AVO

![image](https://github.com/avo-hq/avo/assets/43936240/448cce9e-3fe1-4d3c-9efd-fc62af22a7e2)

### Steps to Reproduce
1. Create a resource with any association
2. Go to resource page

### System configuration
**Avo version**: 3.7.4

**Rails version**: 7.2-beta

**Ruby version**: 3.3

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by PedroAugustoRamalhoDuarte** [comment]
After i create the issue i seen this PR is already trying to solve this problem: #2789

**Comment by adrianthedev** [comment]
Hey @PedroAugustoRamalhoDuarte. Yes. I was going to mention that. We are working on a fix in that PR.
Thanks for bringing it to our attention.
