### ISSUE TITLE
How can I configure a custom toolbar of a trix field

### ISSUE THREAD

**Issue by stefsava** [avo-hq/avo#2834]
### Feature
I need to add and/or modify the trix field toolbar.

In my specific case I have to remove H1 and add H2 and H3.

However, I would be interested to know what your opinion might be on the best practice for extending functionality included in the stimulus controllers of the AVO fields.

**Comment by adrianthedev** [comment]
I guess the easiest way to do it is to clone the trix field (view components, field class, stimulus controller), and update the stimulus controller to your needs.

We would like to add the ability to "monkey-patch" or totally override the stimulus controllers at some point, but we don't have the bandwidth right now.
