### ISSUE TITLE
Overwrite the name of a resource

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2837]
### Feature
Looking at https://docs.avohq.io/3.0/resources.html 
We can set the description but we can't set the name
I would like to do this with a static string as well as a block

### Screenshots or screen recordings
![Screenshot 2024-06-04 at 18 19 13](https://github.com/avo-hq/avo/assets/1681106/2613533d-3257-425f-8abc-0975e9614990)

**Comment by adrianthedev** [comment]
This can be done using the [i18n](https://docs.avohq.io/3.0/localization.html#localizing-resources) (internationalization) feature.
Let me know if this work for your use-case.

**Comment by adrianthedev** [comment]
Another way to do it is to override the [`name` method](https://github.com/avo-hq/avo/blob/main/lib/avo/base_resource.rb#L172) in a resource file.

**Comment by pjmuller** [comment]
@adrianthedev thanks! case closed!
