### ISSUE TITLE
Global Search placeholder isn't replace by input text

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#2840]
### Describe the bug
With Global search, the place holder text is not override by the text input by user

### Steps to Reproduce

1. Click global
2. Type some text and observe
3. The place holder of global search is intact and the input text is added as suffix of the placeholder
4. This is not the case with resource search
5. The issue is reproducible in Avo Demo app

### Expected behavior & Actual behavior
The input text should replace the placeholder as resource search

### System configuration
**Avo version**: 3.7.0

**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x No

### Screenshots or screen recordings
![Screenshot 2024-06-06 at 2 33 05 PM](https://github.com/avo-hq/avo/assets/17696184/d67cfd5d-250d-4798-b893-0fdf217ee6a7)
![Screenshot 2024-06-06 at 2 44 21 PM](https://github.com/avo-hq/avo/assets/17696184/8ddc6a04-283f-4e0d-9302-51dc2c851696)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
### Approach

Let's resolve this by making the search plugin not write the text in the input or by keeping the current behavior, making the current placeholder an actual placeholder (now it's some text on a button) and fix https://github.com/avo-hq/avo/issues/2841
