### ISSUE TITLE
Searched input text doesn't clear on click of cancel

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#2841]
### Describe the bug
The text in search box doesn't clear if we cancel the search. It would be very helpful if we can add a clear icon within the search box both global and resource to clear the text if there is any.

### Steps to Reproduce

1. Users enter text in a search box (both globally and for resources).
2. If they cancel the search without submitting it or clicks outside of the search result dialog, the entered text remains in the search box.
3. This can be confusing for users who expect the text to clear when they cancel the search.

### Current workarounds
1. Click the search box
2. Click the `x` icon in search hover dialog to clear the text
### System configuration
**Avo version**: 3.7.0

**Rails version**: 7.1

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2024-06-06 at 2 59 15 PM](https://github.com/avo-hq/avo/assets/17696184/17821989-fe25-4fa0-81ca-bec5511cc4d5)
   
![Screenshot 2024-06-06 at 2 53 11 PM](https://github.com/avo-hq/avo/assets/17696184/459be018-8da0-453d-82fe-9d8e438f66ce)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yeah. That's a bug.

Recording:
![Uploading CleanShot 2024-06-07 at 10.30.27.gif…]()
