### ISSUE TITLE
Make error/warning/info/success response message appear longer/permanently 

### ISSUE THREAD

**Issue by NowakJR** [avo-hq/avo#2845]
Currently response messages disappear after few seconds, it is sufficient in most cases but when we want to display invalid elements (for example validating e-mails with regex in text field) so user may fix them the flash message may disappear too fast.

**Comment by adrianthedev** [comment]
### Approach

Let's create another [configuration item](https://github.com/avo-hq/avo/blob/main/lib/avo/configuration.rb) (`alert_dismiss_time` which defaults to `5000`) and add that to the [`alert_component.html.erb`](https://github.com/avo-hq/avo/blob/main/app/components/avo/alert_component.html.erb#L2) partial.

**Comment by adrianthedev** [comment]
@NowakJR, would you like to try and contribute a PR for this? It would be the fastest way to adding this enhancement to Avo.

**Comment by NowakJR** [comment]
> @NowakJR, would you like to try and contribute a PR for this? It would be the fastest way to adding this enhancement to Avo.

Sure, will try to find some time during break at work today :)

**Comment by adrianthedev** [comment]
Thank you!
https://github.com/avo-hq/avo/pull/2717/files does basically the same thing but for pagination.

**Comment by NowakJR** [comment]
do you mind having a look at PR? https://github.com/avo-hq/avo/pull/2846/files

**Comment by adrianthedev** [comment]
This looks great! Thank you!
Let me have a proper look on Monday and merge it.

We appreciate the help!

**Comment by adrianthedev** [comment]
Closed by https://github.com/avo-hq/avo/pull/2846

Thank you @NowakJR for your contribution 💪
