### ISSUE TITLE
order_controls not working in row controls on association view

### ISSUE THREAD

**Issue by TobiasKampAdmin** [avo-hq/avo#2847]
### Describe the bug
When you add order_controls to the row controls as described in the AVO documentation, pages displaying these in a has_many are breaking:
https://docs.avohq.io/3.0/customizable-controls.html#row_controls 

### Steps to Reproduce
1. Add sorting to an Avo resource with 'visible_on: :association'
2. All is working fine out of the box in the has_many displaying (screenshot 1) 
3. Try to overwrite the row controls like explained here: https://docs.avohq.io/3.0/customizable-controls.html#row_controls 
4. All works fine for show_button, edit_button ... (screenshot 2)
5. Once you add order_controls, the page breaks (screenshot 3)

<img width="1512" alt="Scherm­afbeelding 2024-06-07 om 22 27 12" src="https://github.com/avo-hq/avo/assets/60701859/9c385657-e4ca-4f4c-8834-06b4fc053a0b">
<img width="1504" alt="Scherm­afbeelding 2024-06-07 om 22 29 12" src="https://github.com/avo-hq/avo/assets/60701859/29887cfd-d82f-47ff-ae82-abfc8e4cc0a3">
<img width="1512" alt="Scherm­afbeelding 2024-06-07 om 22 30 17" src="https://github.com/avo-hq/avo/assets/60701859/3b1bdcb8-a715-4dfb-b17a-52252e0251a6">

Is there something wrong in the documentation and can you point out the correct syntax?
Or is there a bug in this scenario? 

Medium impact, Medium urgency.

**Comment by TobiasKampAdmin** [comment]
Any update on this?

**Comment by Paul-Bob** [comment]
Hello @TobiasKampAdmin this was a bug that is already fixed and will be included on the next release
