### ISSUE TITLE
Is it possible to import filter_controller.js from Avo into a custom _controller.js in own project

### ISSUE THREAD

**Issue by yuki-yogi** [avo-hq/avo#2849]
### Context
 If we can import avo's filter_controller.js and create a custom controller, you can create your own filters!
```
// Path to filter_controller.js in avo required
import BaseFilterController from '/**/**/filter_controller';

export default class extends BaseFilterController {
...
```

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

Fork avo to create custom filters
https://github.com/avo-hq/avo/pull/2743/files

**Comment by adrianthedev** [comment]
@yuki-yogi could you just copy it for now? I don't know exactly how to make it available from the bundled gem.

**Comment by yuki-yogi** [comment]
Thank you for your confirmation and response!
In my Rails App, just copying and pasting filter_controller.js didn't seem to work as expected.

It seemed necessary to match the front environment with Avo.

After a day of investigation, I could not find the cause of the problem, so I decided to fork Reposidtory itself and use its Repository if I wanted to use filter_controller.js👍

**Comment by adrianthedev** [comment]
Closing for now until we have a better solution.
