### ISSUE TITLE
The dynamic filters dropdown should `uniq` the filters based on their `id`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2852]
### Context

In some scenarios (when you try to extract the field definitions into methods) you might declare two fields as `filterable` and they show up twice in the dropdown.
We need to run a `uniq` on them.

**Comment by SahSantoshh** [comment]
We can make some changes and achieve the uniq of them as

```ruby
def client_fields(filter: false, **args)
    with_options(args) do
      field :application_id,
            as: :text,
            filterable: filter
end


def fields
  client_fields(filter: true, only_on: :index)

 tabs do
   tab 'Client Information' do
     panel do
       client_fields(filter: false, except_on: :index)
     end
   end
 end 
end
```

In this we can explicitly set the filterable to be true or false and achieve the uniq filters

**Comment by Paul-Bob** [comment]
This issue should be fixed by https://github.com/avo-hq/avo-dynamic_filters/pull/32
