### ISSUE TITLE
Ability to select multiple associated model's record

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#2854]
### Feature
I have 3 models

1. Users (devise)
2. Roles (rolify)
3. Permissions (custom model)

I have pre-populated permissions records created from `seed.rb` 

I want to create/update roles by un/selecting multiple permissions.

### Current workarounds
We can only attach single record to parent model. This is too hard to work. If we have any other work around that would be very helpful 

### Additional context

Repo https://github.com/SahSantoshh/avo_search

**Comment by SahSantoshh** [comment]
https://github.com/avo-hq/avo/assets/17696184/3beeeb07-2ea4-4c2b-be1d-96fb565692f0

**Comment by SahSantoshh** [comment]
just created a work around pushed in repo https://github.com/SahSantoshh/avo_search

Add a column in roles table as string array

```ruby
field :tags,
          as: :tags,
          suggestions: lambda {
            Permission.where.not(id: record.permissions.pluck(:id)).map(&:name)
          }
```

in `role.rb` model

```ruby
  before_create :create_permissions_roles
  before_update :update_permissions_roles

  def update_permissions_roles
    return unless tags_changed?

    old_permissions = Permission.where(name: tags_was - tags)
    permissions.delete(old_permissions) if old_permissions.present?

    new_permissions = Permission.where(name: tags - tags_was)
    permissions << new_permissions if new_permissions.present?
  end

  def create_permissions_roles
    permissions << Permission.where(name: tags)
  end
```

In this way at leas I can attach multiple permissions.


https://github.com/avo-hq/avo/assets/17696184/25689e62-23d5-4305-b5fd-b2e21c2ac041

**Comment by adrianthedev** [comment]
That's an amazing way to fix that! Augmenting the experience using the tags field.
Good job and thanks for sharing!

**Comment by Paul-Bob** [comment]
Great workaround @SahSantoshh ! I'm closing this one since your request is already tracked by this issue https://github.com/avo-hq/avo/issues/2116
