### ISSUE TITLE
Create new doesn't work when a resource has a trix field that uses `prefixed_ids`

### ISSUE THREAD

**Issue by cg5544** [avo-hq/avo#2857]
### Describe the bug
I am using the prefixed_ids gem (https://github.com/excid3/prefixed_ids) because I don't want to expose integer IDs to the world. It works with Avo resources fine with just one exception. When a resource has a `trix` field, when I attempt to create a new resource I get the following error, but editing the record works fine.

<img width="757" alt="Screenshot 2024-06-12 at 10 12 08 AM" src="https://github.com/avo-hq/avo/assets/5017304/22ff08c4-cf1e-44ba-8f5f-3f3224fa761f">

### Steps to Reproduce
1. Create a resource (mine is called `report`)
2. Add [prefixed_ids gem](https://github.com/excid3/prefixed_ids) to gemfile: gem 'prefixed_ids'
3. In model, set this for your resource: `has_prefix_id :user` 
4. Set a field on the report resource as trix with this configuration:
```
field :description,
      as: :trix,
      rows: 30,
      always_show: true,
      attachments_disabled: true
```
5. Now try to create a new report. 

### Expected behavior & Actual behavior
Should be able to create a new resource even if a field type is trix

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [x ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.) (not exposing id of the report is essential to our app)
 - [ x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
What Avo version are you using?

This should work, we are using it in our apps.

We'd love to help with this.
Can you please set up a small reproduction repo with those steps where we can run the code and troubleshoot?

To do that you should:
1. `rails new`
2. run `bin/rails app:template LOCATION='https://avohq.io/app-template'` to get Avo installed
3. add the necesary steps to reproduce the error
4. add to a repo and post it here

Thank you!

**Comment by Paul-Bob** [comment]
This issue happens because we call `record.to_param` without verifying if the record is or not persistent. Rails return `nil` if you do something like `Model.new.to_param` but prefixed_ids gem (https://github.com/excid3/prefixed_ids) modify `to_param` method and does not have a safe guard for nil id values coming from non-persistent records.

Just created [this PR](https://github.com/excid3/prefixed_ids/pull/69) that should fix this issue.

**Comment by Paul-Bob** [comment]
@cg5544 updating to `prefixed_ids` version `1.7.1` should fix this issue.
