### ISSUE TITLE
main_app.model_url when constrain in routes is added returns unexpected url.

### ISSUE THREAD

**Issue by giedriusr** [avo-hq/avo#2859]
### Describe the bug
First of all, not sure if it's Avo bug. Had a short discussion with Andrian in Discord, suggestion was to create a repo to reproduce it. Did below.

Description:

As per documentation: https://docs.avohq.io/3.0/resource-tools.html#using-path-helpers

>For the main app paths
>When you want to reference paths from your main app, instead of writing posts_path(1), you have to write main_app.posts_path.

```ruby
routes.rb
Rails.application.routes.draw do
  constraints subdomain: "foobar" do
    mount Avo::Engine, at: "/"
  end

  get "p/(:slug)/:id", to: "pages#show", as: :page
end

```

We have mounted avo engine under subdomain.
When I use 

avo/resources/page.rb
```ruby
field :page_url, as: :text do
  url_params = {slug: resource.record.slug, id: resource.record}
  link_to main_app.page_url(url_params), main_app.page_url(url_params), target: "_blank"
end
```

<img width="1570" alt="image" src="https://github.com/avo-hq/avo/assets/210713/ff91311e-a1d6-49cc-b480-a201b9195478">

I get `foobar.domain.com/p/whatever/1` (the page loads and I can see content, but the address is wrong). 
I'd expect to get domain.com/p/whatever/1.

### Steps to Reproduce
1. Go to Pages in Avo
2. Create new page & press Save
3. In the show page see if URL is without a subdomain (now it is with foobar.app.local, should be localhost)

I've created a repo to reproduce this behaviour:
https://github.com/giedriusr/reproduceavo

p.s. 
```
$ rails db:migrate
$ sudo vim /etc/hosts
```
// content for /etc/hosts
127.0.0.1 foobar.app.local

### System configuration
**Avo version**:
3.7.4
**Rails version**:
7.1.3
**Ruby version**:
3.2.2
**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Will look into it as soon as I catch up on some of the daily work.

**Comment by adrianthedev** [comment]
Yes @giedriusr, I think it's a Rails bug that it attaches the subdomain to the URL.

Can you please file a bug on the Rails repo?
I started to build a reproduction script for them, but it's unfinished and I have to drop off.
Maybe you can figure it out why the `main_app` is not available in that context.

https://gist.github.com/adrianthedev/743fc1834d68bc4b128dbb7c5e3b9913

Please tag the rails repo issue here for reference.

**Comment by giedriusr** [comment]
Will do.

**Comment by adrianthedev** [comment]
Closing for now. Feel free to re-open or come back to it.
