### ISSUE TITLE
Resource.row_controls does not have a drag_and_drop_button

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#2860]
### Describe the bug
Cfr 
- https://docs.avohq.io/3.0/records-reordering.html
- https://docs.avohq.io/3.0/customizable-controls.html#row_controls 
 
we can't explicitly add the drag and drop we icon we need for the acts_as_list sortable feature

### Expected behavior & Actual behavior
have a method I can call to register the drag & drop button

### Models and resource files
```ruby
class Avo::Resources::FooBar < Avo::BaseResource
  self.ordering = {
    display_inline: true,
    visible_on: :index,
    drag_and_drop: true,
    actions: {
      insert_at: -> { record.insert_at position }
    }
  }
  
  self.row_controls = -> do
    show_button
    drag_and_drop_button # does not exist
  end
end
```

### System configuration
**Avo version**: 3.9.1

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hey @pjmuller we have this `order_controls` helper that can be used as:

```ruby
  self.ordering = {
    display_inline: true,
    visible_on: %i[index association], # :index or :association or both
    # position: -> { record.position },
    drag_and_drop: true,
    actions: {
      higher: -> { record.move_higher }, # has access to record, resource, options, params
      lower: -> { record.move_lower },
      to_top: -> { record.move_to_top },
      to_bottom: -> { record.move_to_bottom },
      insert_at: -> { record.insert_at position }
    }
  }

  self.row_controls = -> do
    order_controls
  end
```

This will render:
![image](https://github.com/avo-hq/avo/assets/69730720/fd0fd3ed-f548-442a-b91a-b75110099247)


Just noticed that it is not executing as expected. We are already reviewing a PR that fixes it and the fix will be included on the next release. The drag and drop button is included on the ordering component.

**Comment by pjmuller** [comment]
Thanks @Paul-Bob , I'll use the `order_controls`

**Comment by pjmuller** [comment]
Hi @Paul-Bob , I'm getting the error `uninitialized constant Avo::Resources::Controls::OrderControl`

![Screenshot 2024-06-28 at 08 57 44](https://github.com/avo-hq/avo/assets/1681106/8bb97d8c-6848-4458-9645-972ca56d523c)

what am I doing wrong with this code
```ruby
class Avo::Resources::Table < Avo::BaseResource
  self.model_class = Avo::Table

  self.row_controls = -> do
    show_button
    order_controls
  end
```

**Comment by Paul-Bob** [comment]
> Just noticed that it is not executing as expected. We are already reviewing a PR that fixes it and the fix will be included on the next release.

We noticed that bug and it's already fixed. The Tuesday release will include this fix.

**Comment by pjmuller** [comment]
@Paul-Bob  Apologies, I read over that statement, looking forward for the fix next tuesday ;)
