### ISSUE TITLE
Missing translation when filters are applied

### ISSUE THREAD

**Issue by jpawlyn** [avo-hq/avo#2864]
Great product, I love it, thank you.

Very minor issue with a missing translation when filters are applied. Our application is in French and when we apply a filter we  see:

<img width="164" alt="Screenshot 2024-06-16 at 10 22 17" src="https://github.com/avo-hq/avo/assets/45294/f3ee80bd-717f-468c-abca-1bb1841a55d7">

Not sure if pluralisation could be an issue with certain languages but this is low priority for us.

https://github.com/avo-hq/avo/blob/fa7d182538ffba468aedd405e701e7b59c0a39d0/app/components/avo/filters_component.html.erb#L13

**Comment by adrianthedev** [comment]
Yup. A missed string on our end. Please send more if you find any and we'll fix them.

**Comment by jpawlyn** [comment]
> Yup. A missed string on our end. Please send more if you find any and we'll fix them.

Sure thing. One other popped up:

![Screenshot 2024-06-17 at 16 50 42](https://github.com/avo-hq/avo/assets/45294/730dc365-4fb7-4828-9001-c36cb2d1c8a2)

https://github.com/avo-hq/avo/blob/fa7d182538ffba468aedd405e701e7b59c0a39d0/app/components/avo/fields/files_field/index_component.html.erb#L2

Is it better to create a separate issue each time or just add to this issue while it remains open?

**Comment by adrianthedev** [comment]
Hmmm... let's see how this goes and how many we find.
Would you be able to help with a PR with the ones you find in the `avo` repo, and we tackle the ones in the private repos?

**Comment by jpawlyn** [comment]
Happy to help out but I can't commit to doing anything in the immediate
future as I am on holiday
