### ISSUE TITLE
Number field doesn't cast the value as float/integer

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2880]
### Describe the bug

I have a JSONB column where I want to save number value:

```ruby
…
    store_accessor :price, :amount, :currency
…
```

But when using number field, the value is saved as string:

```ruby
…
    field :amount,
      as: :number,
…
```

If I do this, it is saved as number (float in this case):

```ruby
…
    field :amount,
      as: :number,
      update_using: -> do
        value.to_f
      end
…
```

### Expected behavior & Actual behavior

I think it would be reasonable to cast the value as float by default, and optionally allow to change it to integer or string.

### System configuration
**Avo version**:
3.9.1
**Rails version**:
7.0.8.1
**Ruby version**:
3.2.3
**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
We don't cast anything to string on our end AFAIK.
How would you solve this in a regular non-Avo context?

**Comment by krystof-k** [comment]
Hmm, I'm not sure. Probably it would come as a string from some HTML input as well, so you would have to cast it manually `.to_f` or `.to_i` in the controller, right? I think it would be reasonable for `as: :number` to cast everything `.to_i` (or `.to_f`?) as default and allow some option to configure whether you want to cast integer/float/string.

**Comment by adrianthedev** [comment]
Automatically casting it to any of `to_i` or `to_f` by default seems a bit excessive and could lead to edge-cases.
I would leave it as is for now with the option to cast it yourself in `update_using`.

You could abstract that away by adding this method somewhere in the resource.

```ruby
  def field(id, **args, &)
    if args[:as] == :number
      args[:format_using] = -> { value.to_f }
    end

    super id, **args, &
  end
```

**Comment by adrianthedev** [comment]
I felt inspired and wrote an article about this.
https://avohq.io/blog/override-the-field-method-to-add-default-values-to-field-options

**Comment by krystof-k** [comment]
@adrianthedev cool. Yeah, I get it, you're right. Maybe just a notice in the docs would be useful. Usually this is controlled by the data type of the column in the database, so it is a kind of edge case when using the JSONB or such.

**Comment by adrianthedev** [comment]
Got it!
I added it under [guides](https://docs.avohq.io/3.0/guides.html).
Closing for now.
