### ISSUE TITLE
Validations not showed when attaching fails

### ISSUE THREAD

**Issue by krystof-k** [avo-hq/avo#2883]
### Describe the bug

When attaching an association using `:through`, Avo doesn't show validation errors, only reloads the associations table.

### Steps to Reproduce

Have field like this:

```ruby
class Avo::Resources::Subscription < Avo::BaseResource
  def fields
    field :plan_variants,
      as: :has_many,
      through: :subscription_items
  end
end
```

Validation in the model:

```ruby
class SubscriptionItem < ApplicationRecord
  belongs_to :subscription
  belongs_to :plan_variant

  validate :fail

  private

  def fail
    errors.add(:plan_variant, "already added to the subscription")
  end
end
```

Try to attach the record and it doesn't show the validation error.

### Expected behavior & Actual behavior

Validation error is shown.

### System configuration
**Avo version**:
3.9.1
**Rails version**:
7.0.8.1
**Ruby version**:
3.2.3
**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
I think it's a bug and Avo swallows that error. 
We'll have a fix in the first half of next week.

**Comment by adrianthedev** [comment]
Please try it tomorrow with Avo 3.10 to see if this is fixed.

**Comment by adrianthedev** [comment]
This PR should have fixed that
https://github.com/avo-hq/avo/pull/2905

Closing for now to keep the issue queue clean. Please re-open if this persists after tomorrow.

**Comment by krystof-k** [comment]
Just tested it in 3.10.5 and still the same case – no validation error, no message (actually now it reloads the whole page, not just the table as before if I remember correctly).

**Comment by adrianthedev** [comment]
hmmm. we'll need a reproduction repo.
I understand it might not be easy to make, but it's the only way we can run and troubleshoot the issue.

**Comment by krystof-k** [comment]
@adrianthedev hopefully I managed to do it [here](https://github.com/avo-hq/avo/compare/main...cloudaper:avo:reproducer).

**Comment by adrianthedev** [comment]
Ok. Thanks! We'll have a look.
