### ISSUE TITLE
Increase number of search results

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#2885]
Is there a way to increase the number of results when searching?  I'm searching for a name of a record, but as there are quite a few, the one i'm after doesn't get returned.

**Comment by adrianthedev** [comment]
Thanks for filing this issue @rctneil.

I added this approach if you'd like to take this on and help out.

### Approach

1. Follow [this PR](https://github.com/avo-hq/avo/pull/2846/files) to add the configuration item called `search_results_count`
2. Use that configuration item to change the limit [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L56)
3. add docs somewhere around [here](https://github.com/avo-hq/avodocs/blob/main/docs/3.0/search.md#L305) on how to use it

**Comment by binarygit** [comment]
@adrianthedev Could I take this on? (@rctneil hasn't replied so wanted to ask :sweat_smile:)

**Comment by adrianthedev** [comment]
Yes, why not?

**Comment by rctneil** [comment]
Yes, absolutely go for it.   I've been away on trips quite a lot this month and currently away right now so I've just not had any time to do much development at all.

I've done a tiny bit on my own project, hence hitting this issue, but that's about it.

Fingers crossed everything calms down a bit next month!  It's been sooo crazy!

I may take a stab at it myself without looking at what you come up with and then compare what I get to what you get.  I feel like that would be a good learning exercise for me!

**Comment by adrianthedev** [comment]
Yes @rctneil. It would be really beneficial to tackle one of these bugs one day, yourself. The quickest way to get something done is to do it yourself.
