### ISSUE TITLE
Configure `search_count` per resource

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2901]
### Context

As a follow up for https://github.com/avo-hq/avo/issues/2885 lets also enable resource level configuration for the search query limit.

#### Approach

1. Fetch the `results_count` from the search options like we do with the query [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_resource.rb#L213)
2. Execute it using `Avo::ExecutionContext` like we do with the `search_query` [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L44)
3. Make sure that `results_count` can be both, an integer or a Proc
4. Make sure that resource level `results_count` takes precedence over the global configuration `Avo.configuration.search_results_count`
5. Add docs somewhere around [here](https://github.com/avo-hq/docs.avohq.io/blob/main/docs/3.0/search.md#L305) 

Final DSL should look like:
```ruby
class Avo::Resources::User < Avo::BaseResource
  self.search = {
    query: -> { query.ransack(name_eq: params[:q]).result(distinct: false) },
    results_count: -> { user.admin ? 30 : 10 }
  }
end
```

**Comment by binarygit** [comment]
Could this be assigned to me?
