### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by berniechiu** [avo-hq/avo#2903]
### Context
Local admin always returns **_422_** `Can't verify CSRF token authenticity` when updating any resources
But weirdly it's fine under production environments.

### System configuration
**Avo version**:
3.7.4

**Rails version**:
7.0.8.3

**Ruby version**:
3.2.4

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [x] No
 
 Doesn't work either way
 ```ruby
 class Avo::ShopsOverrideController < ActionController::Base
  def update
    shop = Shop.find(params[:id])
    shop.assign_attributes(shop_params)
    Rails.logger.warn("shop_changes: #{shop.changed}")
    shop.save

    respond_to do |format|
      format.html { redirect_to "/admin2/resources/shops/#{shop.id}", notice: "Updated" }
      format.turbo_stream { redirect_to "/admin2/resources/shops/#{shop.id}", notice: "Updated" }
    end
  end

  private

  def shop_params
    params.require(:shop).permit!
  end
end

```

### Screenshots or screen recordings

Native
![Screen Shot 2024-06-28 at 6 05 26 PM](https://github.com/avo-hq/avo/assets/2749593/c2d11afb-c321-4fde-a7be-53905222087f)
![Screen Shot 2024-06-28 at 6 05 31 PM](https://github.com/avo-hq/avo/assets/2749593/84d663fe-5cbd-46c9-a50d-23b9703d7787)

With overrides
![Screen Shot 2024-06-28 at 5 43 48 PM](https://github.com/avo-hq/avo/assets/2749593/c93f501d-a49d-420c-b55b-890a6e51e6bd)
![Screen Shot 2024-06-28 at 5 43 55 PM](https://github.com/avo-hq/avo/assets/2749593/1009f100-98a7-49ff-b8a0-a8d8177b9117)

**Comment by adrianthedev** [comment]
This is most likely a local problem.
Is this a new app or an existing one?

**Comment by berniechiu** [comment]
It's an existing one, nothing fancy, straightforward installation

**Comment by adrianthedev** [comment]
Hmm, can you please check a few things?
- `api_mode` to be false
- to import the whole `rails` gem, not just a few

Also, do other resources where the `update` method is not overwritten work properly?

I see the authenticity token there.

**Comment by berniechiu** [comment]
> Hmm, can you please check a few things?
> `api_mode` to be false
> to import the whole `rails` gem, not just a few

We're a full-stack application from the start, never limited to any API only settings.
So it's all good here.

> Also, do other resources where the update method is not overwritten work properly?
I'm updated the description, it doesn't work with native updates too

**Comment by adrianthedev** [comment]
I'd say it's scoped to your particular app.
If you could get this on a reproduction repo we'd love to have a look and fix it.

Closing for now to keep the queue clean until we get a reproduction repo.
Please keep us up with how this develops.

**Comment by berniechiu** [comment]
What a bummer, we'll look into it at some point 😞

**Comment by berniechiu** [comment]
Should be resolved by now, found that we modified some custom `config.action_controller.default_url_options` somewhere in dev and causing issues from there 😮‍💨

**Comment by adrianthedev** [comment]
Thanks for letting us know about the fix!
