### ISSUE TITLE
Stimulus controller `alert` missing for `AlertComponent`

### ISSUE THREAD

**Issue by joeldrapper** [avo-hq/avo#2918]
I’m not sure if I’m missing something here, but I’m getting Stimulus LSP warnings for a missing Stimulus controller "alert", which is referenced in `AlertComponent`. It looks like AlertComponent is still used in various places. 🤔

**Comment by adrianthedev** [comment]
Yeah, I'm not sure if we did something wrong or the LSP can't read that we import the alert component from a package [here](https://github.com/avo-hq/avo/blob/depfu/batch_all/yarn/2024-06-28/app/javascript/js/application.js#L16).

Maybe @marcoroth knows if we're doing something wrong or not.

**Comment by adrianthedev** [comment]
For reference this is the error the LSP raises

![CleanShot 2024-07-01 at 10 16 43@2x](https://github.com/avo-hq/avo/assets/1334409/0ba24b07-5042-4a02-ad6c-ada45cfb71c3)

**Comment by marcoroth** [comment]
Hmm weird, it should be able to handle that. Is that diagnostic popping up in the Avo codebase itself or in a codebase that uses Avo and this alert controller?

**Comment by joeldrapper** [comment]
> Is that diagnostic popping up in the Avo codebase itself or in a codebase that uses Avo and this alert controller?

In the Avo codebase itself.

**Comment by marcoroth** [comment]
I looked at it with @joeldrapper in person yesterday, and I think I know what's wrong. Going to see if I can fix it. I was able to reproduce it on machine too 🙌🏼

**Comment by adrianthedev** [comment]
Thank you @marcoroth!
