### ISSUE TITLE
Field as: :tags adding custom delimiter ; doesn't work

### ISSUE THREAD

**Issue by giedriusr** [avo-hq/avo#2922]
### Describe the bug
Trying to use as: :tags field.
In the field :labels adding `Clothing, Shoes & Jewelry`, UI shows as 1 tag, though in DB it is being saved as: 
{Clothing," Shoes & Jewelry"}

### Steps to Reproduce
Prepared a repo: https://github.com/giedriusr/reproduceavo
1. rails s
2. foobar.app.local:3000
3. Go to Pages and add new page. Next to labels, add `Clothing, Shoes & Jewelry`
4. Try to save the page.

### Expected behavior & Actual behavior
Expected result:
1 tag in DB
Action result:
2 tags in DB

### System configuration
**Avo version**: 3.9.2

**Rails version**: 7.1.3 & rails/rails main branch

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
NEW:
<img width="1519" alt="image" src="https://github.com/avo-hq/avo/assets/210713/f9d259d5-08de-44a5-a22c-358a985c7a4f">
Show:
<img width="738" alt="image" src="https://github.com/avo-hq/avo/assets/210713/cd3808b7-8f4b-41c6-971e-3721fcabbc95">
EDIT:
<img width="1110" alt="image" src="https://github.com/avo-hq/avo/assets/210713/bec576d3-f885-430b-a045-f5c6a66214f0">

### Additional context
PostgreSQL: 16.1

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Thanks for the reproduction repository @giedriusr was handy to identify the problem.

**Comment by giedriusr** [comment]
No problem. Thank you for the fix!
