### ISSUE TITLE
Margin glitch when row controls placed on the right side

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2940]
### Describe the bug

When row controls are placed on the right, the standard margin is not applied:

### System configuration
**Avo version**:

3.10.1

**Rails version**:

7.2.0.beta2

**Ruby version**:

ruby 3.3.3

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![Screenshot 2024-07-04 at 09 31 34](https://github.com/avo-hq/avo/assets/201689/d90767d5-3a17-4ad9-b854-060108d25632)
![Screenshot 2024-07-04 at 09 32 20](https://github.com/avo-hq/avo/assets/201689/1a6a8648-b93f-4e9f-8c71-e7d2c5bd59bf)

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Do you mean this extra space here?
![CleanShot 2024-07-08 at 15 18 25@2x](https://github.com/avo-hq/avo/assets/1334409/73d5874e-b13a-4833-82e6-d5f29af62896)

**Comment by jetienne** [comment]
@adrianthedev Nope, here:
![Screenshot 2024-07-09 at 13 46 37](https://github.com/avo-hq/avo/assets/201689/e4de1b68-dd5f-4d3d-b951-aa4d21cb2a9c)
