### ISSUE TITLE
Alias `close_modal` action response to `do_nothing`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2944]
### Context

The `close_modal` response is great when you don't want the page to be reloaded, but users don't currently know about it. The `do_nothing` response would sound better.

### Approach

The tweak should be done [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_action.rb#L235) IMHO.
We also need tests for this response.

**Comment by gerard-simpson** [comment]
Happy to pick this up as a first issue. Please could you assign to me

**Comment by G-Simpson** [comment]
Hey, very new to avo, so it's why I'm taking a look at this.

Aliasing the method seems simple enough. 

I'm puzzled by "We also need tests for this response."

Looking at the `BaseAction` class, there are no tests for any of the similar responses [warn](https://github.com/avo-hq/avo/blob/main/lib/avo/base_action.rb#L223) [keep_modal_open](https://github.com/avo-hq/avo/blob/main/lib/avo/base_action.rb#L229) [close_modal](https://github.com/avo-hq/avo/blob/main/lib/avo/base_action.rb#L235).

My next thought is that I should be looking for a system test where each of the responses within the case statement are tested, but I can't find anything that intuitively looks like that either. What should I be looking for?

**Comment by binarygit** [comment]
Hey @G-Simpson. There's test for `close_modal` in `spec/system/avo/actions_spec.rb:182`

**Comment by adrianthedev** [comment]
Yeah, I didn't dig into where the tests are, but you could reuse the one above.
Thank you @G-Simpson!

**Comment by G-Simpson** [comment]
@binarygit @adrianthedev forgive me if I'm asking too much and this is a simple change, but as I see it,
1) if I just add the line: `alias do_nothing close_modal` to [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_action.rb#L240) shouldn't that be enough? The underlying functionality that's tested in `spec/system/avo/actions_spec.rb:182` remains the same so the tests will continue to pass.

2) I can see that in the docs there's [this](https://docs.avohq.io/3.0/actions.html#close_modal) and am not sure how it should be updated. The only reference I can find in the codebase is [here](https://github.com/avo-hq/avo/blob/e33060b99d10c7d406c78dc97c83dec2f699e2fc/spec/dummy/app/avo/actions/test/close_modal.rb#L11) which I can update

**Comment by binarygit** [comment]
@G-Simpson Yup adding the alias declaration there will be enough!

Now we just need another test. You can duplicate the test for close_modal but modify it. The  modification should be that It should call an action called DoNothingAction instead of CloseModalAction which makes use of the do_nothing method instead of close_modal. You’ll need to create the DoNothingAction and set it up accordingly.
The DoNothing action should be similar to CloseModal here but with the obvious changes that it should call do_nothing instead of close_modal. 
https://github.com/avo-hq/avo/blob/main/spec/dummy/app/avo/actions/test/close_modal.rb

**Comment by G-Simpson** [comment]
Perfect, thank you @binarygit. Will get to that asap
