### ISSUE TITLE
Attach Association Errors

### ISSUE THREAD

**Issue by ShroukAbozeid** [avo-hq/avo#2945]
### Feature

Show error raised during attaching association in avo show view 

### Additional context
example :

```
class Event < ApplicationRecord
  has_many :participating_teams, dependent: :destroy
  has_many :teams, through: :participating_teams
end
```

```
class ParticipatingTeam < ApplicationRecord
  belongs_to :event
  belongs_to :team
  
  validates :team_id, uniqueness: { scope: :event_id}
end
```

```
class Team < ApplicationRecord
  has_many :participating_teams, dependent: :destroy
  has_many :events, through: :participating_teams
end
```

```
 avo/resources/event.rb
   field :teams, as: :has_many, through: :participating_teams
```

**Steps**
1. admin goes to event user page
2. admin click on attach team and choose team 1
3. admin click on attach team again and choose same team
4. error happens while attaching due to unique validation errors 

**Requested feature:**
View the validation error message

**Actual scenario:** 
 The page is refreshed and team not attached and no message  shown

**Repo link**
https://github.com/ShroukAbozeid/avo-admin-bugs

**Comment by adrianthedev** [comment]
Could you please set up a reproduction error that raises those errors so we can tailor the code to that?

**Comment by ShroukAbozeid** [comment]
> Could you please set up a reproduction error that raises those errors so we can tailor the code to that?

okay  according to the previous example we would have 

table teams with `user_id` and `friend_id`

now if we add a uniqueness validation to `team.rb`

` validates :friend_id, uniqueness: {   scope:   :user_id }`

and then in avo/resources/user try to attach same friend twice , you'll get active record validation error

**Comment by adrianthedev** [comment]
We'll wait for the reproduction repository which we can run.

**Comment by ShroukAbozeid** [comment]
Hello @adrianthedev i've updated the description with reproduction repo

**Comment by adrianthedev** [comment]
Cool we'll have a look! Thank you!

**Comment by Paul-Bob** [comment]
Fixed by https://github.com/avo-hq/avo/pull/3002
