### ISSUE TITLE
Dynamic filter TAG type not clear

### ISSUE THREAD

**Issue by TobiasKampAdmin** [avo-hq/avo#2947]
### Describe the bug
For the TAG-type dynamic filter, it is not so clear for us what to expect or how to configure it correctly.
Ref: [https://docs.avohq.io/3.0/dynamic-filters.html#tags](https://docs.avohq.io/3.0/dynamic-filters.html#tags)

### Example in Demo
See for example the Avo Demo: 
Test it on [avodemo](https://main.avodemo.com/avo/resources/courses?filters%5Bskills%5D%5Barray_contains%5D%5B%5D=), check the [source code](https://github.com/avo-hq/main.avodemo.com/blob/main/app/avo/resources/course.rb#L42)

There in the code you load `suggestions` , but nothing seems to be suggested when you are using the filter.
Is it the goal to have all options available from the standard Tags field (like enforcing suggestions)?
[https://docs.avohq.io/3.0/fields/tags.html](https://docs.avohq.io/3.0/fields/tags.html)

Just some more information about this would be great, now it's a bit of guessing what is possible, should be possible but might be broken or what is not supported.
Thanks in advance!

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello @TobiasKampAdmin field suggestions are not being fetched on the filter, we're working on the new dynamic filter API that allows specifying `suggestions` 
[Peek 2024-07-09 09-41.webm](https://github.com/avo-hq/avo/assets/69730720/30f7f11c-f5b7-4199-a7eb-7ebc235837eb)

To use tags you need to separate them by using `,`. Maybe this delimiter can become configurable, we're adapting the DSL and options as we get requests. Let us know what is your use case and we'll improve docs to reflect it or implement the feature if it fits and is not implemented yet.

**Comment by Paul-Bob** [comment]
I'm checking on `suggestions` and I'll come back to you with some improved documentation

**Comment by Paul-Bob** [comment]
> For the TAG-type dynamic filter, it is not so clear for us what to expect or how to configure it correctly.
Ref: [https://docs.avohq.io/3.0/dynamic-filters.html#tags](https://docs.avohq.io/3.0/dynamic-filters.html#tags)

You only need to add the `filterable: true` option to apply a dynamic filter to a field. That applies to all fields including the tags. Then, as we reference on the [docs](https://docs.avohq.io/3.0/dynamic-filters.html#custom-dynamic-filters) since version 3.10 is possible to customize the filter by changing the `filterable: true` to a hash like `filterable: {}`. Inside that hash, you can configure some options like [`label`](https://docs.avohq.io/3.0/dynamic-filters.html#label), [`query`](https://docs.avohq.io/3.0/dynamic-filters.html#query), [`suggestions`](https://docs.avohq.io/3.0/dynamic-filters.html#suggestions), etc...

> There in the code you load `suggestions` , but nothing seems to be suggested when you are using the filter.

Already updated that part of the documentation, please let me know if something is still unclear.

> Is it the goal to have all options available from the standard Tags field (like enforcing suggestions)?

No, the field and the filter options are different. For example, the `suggestions` on the field will not influence the `suggestions` on the filter input field and vice-versa.

> Just some more information about this would be great, now it's a bit of guessing what is possible, should be possible but might be broken or what is not supported.

I updated the Docs, let me know if there is any part that is still unclear.

**Comment by TobiasKampAdmin** [comment]
Thanks for the update Paul!

Regarding the `suggestions`, this is more clear now.
However it feels strange to us that these suggestions are defined in the field config, while all other filter-logic is somewhere else when you use the new `dynamic_filters`.

Nothing urgent, I think we have a workaround now with all the info above.
But it would be great to have all logic together when using the `dynamic filters`, like this:

```ruby
  self.dynamic_filters = {
    filters: [
      {
        label: "Tags something",
        icon: "heroicons/outline/queue-list,
        type: "tags"
        options: { # <-- this part is not supported
          suggestions: ["aaa", "bbb"], # <-- is now in the field config
          ... # other options if needed
        }
        conditions:{
          contains: "Contains",
          overlap: "Overlap",
          ...
        }.invert,
        query: -> {
          case filter_param.condition.to_sym
          when :contains
            query # logic
          when :overlap
            query # logic
          end 
        }
      }
    ]
  }
```

**Comment by Paul-Bob** [comment]
> However it feels strange to us that these suggestions are defined in the field config, while all other filter-logic is somewhere else when you use the new `dynamic_filters`.

The `suggestions` as all other filterable options can be declared in both DSL https://docs.avohq.io/3.0/dynamic-filters.html#possible-values-6

> But it would be great to have all logic together when using the `dynamic filters`, like this:
The code you're sharing is not using the correct syntax, I rewrote it to valid syntax and now it should work as expected


```ruby
def filters
  dynamic_filter label: "Tags something",
    icon: "heroicons/outline/queue-list,
    type: "tags"
    suggestions: ["aaa", "bbb"],
    conditions:{
      contains: "Contains",
      overlap: "Overlap",
      ...
    }.invert,
    query: -> {
      case filter_param.condition.to_sym
      when :contains
        query # logic
      when :overlap
        query # logic
      end
    }
end
```

**Comment by pjmuller** [comment]
@Paul-Bob I'm closing this one and let's continue the conversation in https://github.com/avo-hq/avo/issues/3010
FYI I tried
```ruby
    dynamic_filter :person, 
      label: "Tags something",
      icon: "heroicons/outline/queue-list",
      type: "tags",
      suggestions: ["aaa", "bbb"]
      ```

but this gives the same error as I have in ticket 3010
