### ISSUE TITLE
The AVO Resource only submits a single resource tool, even though multiple resource tools are defined

### ISSUE THREAD

**Issue by musa-waris-dev** [avo-hq/avo#2948]
### Context
I've defined the Product Resource, which includes nested forms submitted alongside the main resource. Within the Product resource file, I've initialized two Avo::ResourceTools: `ProductVariants` and `CatalogueOrganization` for adding `nested forms` for `variants` and `catalogue_organization`. However, upon saving the record, I'm only receiving `nested_attributes` for one of these tools. At the model level, I've configured that a `Product` has many `Variants` and `CatalogueOrganizations`, and I've enabled `accepts_nested_attributes`.

Here are my models:
````
class Product < ApplicationRecord
  has_one :catalogue_organization, dependent: :destroy
  accepts_nested_attributes_for :catalogue_organization, allow_destroy: true
  has_many :variants, dependent: :destroy
  accepts_nested_attributes_for :variants, allow_destroy: true
end
````
````
class Variant < ApplicationRecord
  belongs_to :product
end
````
````
class CatalogueOrganization < ApplicationRecord
  belongs_to :product
end
````
Here's my Product resource where I've initialized the tools:
````
module Avo
 module Resources
  class Product < Avo::BaseResource
   self.title = :title
   self.includes = []
   def fields
    main_panel do
     field :id, as: :id
     field :title, as: :text
     tool Avo::ResourceTools::ProductVariants, show_on: [:edit, :show, :new]

     sidebar do
      tool Avo::ResourceTools::CatalogueOrganization, show_on: [:edit]
     end
    end
   end
  end
 end
end
````

Here is the HTML for my resource tools that include nested forms:

Avo::ResourceTools::ProductVariants
````
<%= render Avo::PanelComponent.new() do |c| %>
  <% c.with_body do %>
    <%= link_to_add_options_layout(t('avo.variant.add_option')) %>
  <% end %>
<% end %>
<%= t('avo.inventory_level.variant') %>
<%= check_box_tag :all_variant, false, nil %>
<%= t('avo.variant.price') %>
<%= t('avo.variant.available') %>
<%= t('avo.variant.sku') %>
<%= t('avo.variant.barcode') %>
<%= nested_form_for @record, url: resources_products_url(@record.id) do |f| %>
  <%= f.fields_for :variants, Variant.new do |form| %>
    <%= form.hidden_field :_destroy %>
      <%= check_box_tag :selected, false, nil %>
      <%= form.hidden_field :options, class:'variant_options', data: { variant_list_section_target: 'options' } %>
      <%= image_tag 'avo/products/gallery_add_icon.svg' %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :id %>
      <%= form.hidden_field :archived %>
      <%= link_to form.object.title, '' %>
      <%= form.number_field :price, placeholder: t('avo.variant.price_value'), step: 0.1 %>
      <%= form.number_field :available, placeholder: t('avo.variant.available_value'), step: 1 %>
      <%= form.text_field :sku, placeholder: t('avo.variant.sku') %>
      <%= form.text_field :barcode, placeholder: t('avo.variant.barcode'), class: "w-32 py-1 rounded-lg undo-input border variant_barcode", data: { action: "variant-list-section#variantLineItemHandler" } %>
  <% end %>
  <%= f.link_to_add t('avo.variant.add_option'), :variants, class:"new_variant ml-4 hidden" %>
<% end %>
````

Avo::ResourceTools::CatalogueOrganization
````
<%= render Avo::PanelComponent.new() do |c| %>
    <% c.with_body do %>
      <%= nested_form_for @record, url: resources_products_path, local: true do |f| %>
        <%= f.fields_for :catalogue_organization_attributes, @catalogue_organization do |catalogue_form| %>
          <%= catalogue_form.label :product_tag %>
          <% if @record.catalogue_organization %>
            <% @record.catalogue_organization.product_tags.each do |tag| %>
              <span><%= tag %></span>
            <% end %>
          <% end %>
          <%= text_field_tag :product_tag, nil, name: nil %>
          <%= catalogue_form.hidden_field :product_tags %>
          <%= catalogue_form.label :vendor%>
          <%= catalogue_form.select :vendor, [Shopeo::Current.store.title], {} %>
        <% end %>
        <%= f.label :collection %>
        <%= f.select :collection_ids, options_for_select( Shopeo::Current.store.collections.where(id: @record.collection_ids).or(
            Shopeo::Current.store.collections.where(status: 'manual')).map { |collection| [collection.title, collection.id,
            { class: collection.status, selected: @record.collection_ids.include?(collection.id) }] }), {}, { multiple: true} %>
      <% end %>
    <% end %>
  <% end %>
````

Here are the parameters I received upon submitting the form:

![image](https://github.com/avo-hq/avo/assets/163414100/459b9ae4-7013-4295-ae76-4085ee5b5762)

Expected parameters:

````
Parameters: {"authenticity_token"=>"[FILTERED]", "product"=>{"attachments"=>[""], "title"=>"Orange", "description1"=>"<p>Dream it. Wish it. Do it.</p>", "published"=>"0", "variants_attributes"=>{"0"=>{"_destroy"=>"false", "options"=>"", "title"=>"", "id"=>"", "archived"=>"false", "price"=>"", "available"=>"", "sku"=>"", "barcode"=>""}, "1720190324361"=>{"_destroy"=>"false", "options"=>"[{\"sectionId\":\"5526\",\"optionKey\":\"size\",\"optionValues\":[\"Medium\"],\"order\":\"1\"}]", "title"=>"Medium", "id"=>"", "archived"=>"false", "price"=>"10.0", "available"=>"0", "sku"=>"O-470571-M", "barcode"=>""}}}, "catalogue_organization_attributes"=>{"product_tags"=>"[\"sadsad\",\"asdsa\"]", "vendor"=>"N"}, "collection_ids"=>["", "3712"], "price"=>"10.0", "compare_at_price"=>"20.0", "cost_per_item"=>"", "store_id"=>"1bbd6b13-3f6c-4cea-b71e-fc3b17d6cf0d", "show_description_2"=>"0"}, "option"=>"size", "option_value"=>"", "remember"=>"1", "price"=>"", "available"=>"", "sku"=>"", "barcode"=>"", "alt"=>"", "title"=>"", "button"=>"", "locale"=>"en", "id"=>"19450"}
````

 
### System configuration
**Avo version**:
````
3.6.1
````
**Rails version**:
````
7.0.8
````

**Ruby version**:
````
3.1.2
````

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by Paul-Bob** [comment]
Please check this docs https://docs.avohq.io/3.0/guides/nested-records-when-creating.html#_7-permit-the-new-nested-params

To receive the nested params, you should configure `self.extra_params` in the resource.

**Comment by musa-waris-dev** [comment]
I've already attempted to resolve this by adding self.extra_params, but I'm still encountering the same issue with the received params.
````
self.extra_params = [variants_attributes: [:id, :title, :price, :available, :on_hand, :sku, :barcode, :position,
                                                 :options, :cost_currency, :avatar, :_destroy, :archived]]
````

**Comment by Paul-Bob** [comment]
Did you add extra_params for both? `catalogue_organization_attributes` and `variants_attributes`, or only for `variants_attributes`

**Comment by musa-waris-dev** [comment]
Only `variants_attributes`, `catalogue_organization_attributes` are correctly included in the parameters without needing to be added to self.extra_params.

**Comment by Paul-Bob** [comment]
It would be easier if I could reproduce it on my side. Can you create a reproduction repository with an app with just this setup so I can easily run and debug?

**Comment by adrianthedev** [comment]
Yes. Please crwate a new app with all of these already added. 
We want to be able to run bin/setup and start up the server to test it. 
Thank you!

**Comment by abdul-basit-khan-dev** [comment]
Alright, what if I could send the repo to you? Does that make sense to you? If so please share your email then.
Thnaks!

**Comment by adrianthedev** [comment]
No. please create a new, clean, public repo, and paste the link here. Maybe someone else from our team will have a look.

**Comment by musa-waris-dev** [comment]
Here's the public repo for the related issue: [demo-app](https://github.com/musa-waris-dev/shopeo-app)

**Comment by abdul-basit-khan-dev** [comment]
> Here's the public repo for the related issue: [demo-app](https://github.com/musa-waris-dev/shopeo-app)

Thanks, @musa-waris-dev for providing the public repo

**Comment by binarygit** [comment]
@musa-waris-dev You need to declare:
```ruby
       self.extra_params = [catalogue_organization_attributes: [:product_tags]]
```
in the resources file. This will permit the params:
![permit](https://github.com/avo-hq/avo/assets/87677429/78da5e08-39b8-46ac-af9a-8372745ba18b)

However, You're also nesting form tags which is not allowed by the HTML spec. https://stackoverflow.com/a/379622/17780828. This is why the data you submit in the form isn't showing up in the controller action.

![nested_form](https://github.com/avo-hq/avo/assets/87677429/dc44da95-fdb2-443f-ad5b-8356e480a9e0)

**Comment by binarygit** [comment]
@musa-waris-dev You need to declare extra params like this:
```ruby
      self.extra_params = [catalogue_organization_attributes: [:product_tags], variants_attributes: [:id, :title, :price, :available, :on_hand, :sku, :barcode, :position,
                                                                                                        :options, :cost_currency, :avatar, :_destroy, :archived]]
```
If you don't neither catalogue params nor variants are included by default.
Before:
![before](https://github.com/avo-hq/avo/assets/87677429/2e23c069-3754-40a0-8c2b-ac94b17be0dc)

After:
![after](https://github.com/avo-hq/avo/assets/87677429/27f33397-497b-4007-8163-e8124cacdaf3)

In the repo you gave us, you're nesting form tags which is not allowed by the HTML specs so the actual values won't reach the controller. https://stackoverflow.com/questions/379610/can-you-nest-html-forms
![Screenshot_2024-07-11_21-01-42](https://github.com/avo-hq/avo/assets/87677429/144f38c6-d437-404b-a07a-e41ff8de1d05)

**Comment by adrianthedev** [comment]
I guess this should work as well?
```ruby
      self.extra_params = [catalogue_organization_attributes: [:product_tags], variants_attributes: {}]                                                                                                        ```

**Comment by binarygit** [comment]
@musa-waris-dev Please try out the solution and if this still persists, feel free to re-open or continue the conversation. I'll close this issue to keep the queue clean.

**Comment by musa-waris-dev** [comment]
Thank you! @binarygit. I'll give the solution a try and let you know if it works.

**Comment by musa-waris-dev** [comment]
In [general](https://www.ombulabs.com/blog/learning/rails/nested-forms.html), when adding nested forms in Rails, it is possible to include multiple nested forms on a single page. Similarly, in the product's edit view, I have implemented two nested forms using the `nested_form` gem. This creates two nested forms within the main form. I suspect this issue might be related to how AVO generates the HTML form structure. If I'm wrong than please guide me.

**Comment by adrianthedev** [comment]
I don't know how the `nested_form` gem works.
I'm not saying it won't work, but you'll have to do the troubleshooting to get to the bottom of this.

If you'd like us to do actually run the app, learn how that gems works, and do the troubleshooting, I'll recommend the Advanced hands-on support plan [here](https://avohq.io/support).

**Comment by binarygit** [comment]
@musa-waris-dev I also don't know how the nested_forms gem works. But having form element within form elements in HTML is not recommend by the HTML5 RFC and this has side effects (like values from only one form getting submitted). It's what I noticed in your reproduction app and let you know. 

Also I mistakenly reopened this so I'm going to close this again.

**Comment by binarygit** [comment]
@musa-waris-dev I also don't know how the nested_forms gem works. But having form element within form elements in HTML is not recommend by the HTML5 RFC and this has side effects (like values from only one form getting submitted). It's what I noticed in your reproduction app and let you know. 

Also I mistakenly reopened this so I'm going to close this again.
