### ISSUE TITLE
Upstream the dependency fix to the official `ActiveRecordExtended` repo

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2950]
Let's upstream this update to the official repo and follow that PR

https://github.com/avo-hq/ActiveRecordExtended

**Comment by Paul-Bob** [comment]
https://github.com/GeorgeKaraszi/ActiveRecordExtended/pull/104

**Comment by binarygit** [comment]
Closing because @Paul-Bob submitted to AR repo.
