### ISSUE TITLE
Auto suggest for text field

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#2955]
An option for text or textarea fields where we could have some sort of auto suggest.   Eg, I ahve a field called "model".

I want this as a free text input, but i'd also like to be able to see values of the model field from other records, so if the model was "Blah Blah (MX49)", I could ensure it's consistent when i type it so both are like that rather than one being like that and another being "Blah Blah MX-49" for instance.

I would look at this myself, but i just want to focus on the feature i'm on right now, but wanted to suggest it anyway.

**Comment by adrianthedev** [comment]
Thanks for the suggestion, Neil!

We have these issues open to track this so I'll close this one to keep the issue clean.

https://github.com/avo-hq/avo/issues/2711
https://github.com/avo-hq/avo/issues/2406
