### ISSUE TITLE
Create a blank `Avo::BaseResource`

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2959]
We should move the contents of `Avo::BaseResource` to something else and leave a blank `Avo::BaseResource` instead.
This will enable our users to override it in their own apps so they can add their own custom methods more easily.

This should be a best practice for us to use in more places.

`Avo::Resources::Post` inherits from `Avo::BaseResource` which inherits from `Avo::Resources::Base` (or some other name)

The user can add their own `Avo::BaseResource` and add custom methods that all of their resources will inherit.

```ruby
class Avo::BaseResource < Avo::Resources::Base
  # make all number fields cast their values `to_f`
  def field(id, **args, &)
    if args[:as] == :number
      args[:format_using] = -> { value.to_f }
    end

    super id, **args, &
  end
end
```

**Comment by Paul-Bob** [comment]
For consistency's sake, I suggest following the same approach we used on the controllers 

https://docs.avohq.io/3.0/resources.html#parent-controller-option-on-the-generators

**Comment by Yash-Git-Hub** [comment]
I would love to pick this up would that work @Paul-Bob  ? 
Would you be okay review a pr for the same ?

**Comment by Paul-Bob** [comment]
Sure @Yash-Git-Hub! Thanks for looking into it. Let me know if you need any help
