### ISSUE TITLE
Error redirecting after creating an association 

### ISSUE THREAD

**Issue by ShroukAbozeid** [avo-hq/avo#2961]
### Describe the bug

Hey i found an error while trying to create a related association  through another association 

 [reproduction repo](https://github.com/ShroukAbozeid/avo-admin-bugs)
### Steps to Reproduce
Steps to reproduce the behavior after having model and resourced defined as below section:

1. Go to Events, and create an event
2. Create games in that event
3. Click on create player inside event page
4. Fill in the information and click save
5. See error that is raised from `after_create_path` method
in lines
```
 association_name = BaseResource.valid_association_name(@record, params[:via_relation])

        return resource_view_path(
          record: @record.send(association_name),
          resource: parent_resource,
          resource_id: params[:via_record_id]
        )

```
 `association_name` is nil because of wrong params in the url 
 url contains `via_relation=events` while it should be `event`  
 
 causing this error 👇 
 
```
TypeError
nil is not a symbol nor a string (TypeError)
 record: @record.send(association_name),
```

### Models and resource files
```
class Event < ApplicationRecord
  has_many :participating_teams, dependent: :destroy
  has_many :teams, through: :participating_teams
end
```

```
class Game < ApplicationRecord
  belongs_to :event
  has_many :players, dependent: :destroy
end
```

```
class Player < ApplicationRecord
  belongs_to :game
  has_one :event, through: :games
end
```

and having these in avo resources 

```
avo/resources/event
 field :players, as: :has_many, through: :games
```

```
 avo/resource/player
    field :game, as: :belongs_to
```

### System configuration
**Avo version**:  3.10

**Rails version**: 7.1.3.4

**Ruby version**: 3.2.2

**License type**:

 - [x] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context
this happens because `via_relation` in the url is `events` while it should be `event` 

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
I'm going to be honest and say that I can't figure it out from just the code.
There are too many things there.

You could: 
1. try to see if you can reproduce it in our demo app (https://www.avodemo.com/)
2. build a reproduction repo with those steps

We'll gladly look into it and see if it's a bug on our end or not

**Comment by ShroukAbozeid** [comment]
> I'm going to be honest and say that I can't figure it out from just the code. There are too many things there.
> 
> You could:
> 
> 1. try to see if you can reproduce it in our demo app (https://www.avodemo.com/)
> 2. build a reproduction repo with those steps
> 
> We'll gladly look into it and see if it's a bug on our end or not

do you have 'have many through association in the demo app? '

**Comment by adrianthedev** [comment]
The app is open source: https://github.com/avo-hq/main.avodemo.com

Check [this](https://github.com/avo-hq/main.avodemo.com/blob/main/app/models/team.rb#L16) file.

**Comment by ShroukAbozeid** [comment]
Hello @adrianthedev i've updated the description with reproduction repo
