### ISSUE TITLE
Show alert when using Pro features on the Community license

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2964]
Some that we can figure our pretty fast from the initializer:

- authorization
- `main|profile_menu`
- `branding`

### Approach

When Avo displays a page, check if those features have been toggled on and if so, show an error with `Avo.error_manager`.

Similar to https://github.com/avo-hq/avo/pull/2963/files

**Comment by Paul-Bob** [comment]
Menu related alert already done by https://github.com/avo-hq/avo/issues/3054

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/issues/2311
