### ISSUE TITLE
Remove the `avo-hq/ransack` patch

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2969]
Please have a look at https://github.com/avo-hq/ransack/pull/1#issuecomment-2221708905 and see if we can remove our patch and tell others to do so.

Also update the docs where we mention about ransack.

**Comment by Paul-Bob** [comment]
With `rails (= 7.2.0.beta3)` and `ransack (4.1.1)` this error is raised: 
```
undefined method `with_connection' for an instance of ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
```

No error is raised with `rails (= 7.2.0.beta3)` and `ransack (4.2.0)`.

Our patch can be removed and we should change the ransack dependency lock to `4.2.0` here https://github.com/avo-hq/avo_filters/blob/main/avo-dynamic_filters.gemspec#L29

**Comment by adrianthedev** [comment]
Let's do that then! Thanks!

**Comment by Paul-Bob** [comment]
@binarygit is this ready for review? Please link all the PRs to this issue

**Comment by binarygit** [comment]
This was the actual pr which fixed this: https://github.com/avo-hq/avo-dynamic_filters/pull/54

Pending docs PR: https://github.com/avo-hq/docs.avohq.io/pull/249
