### ISSUE TITLE
Add the `visible` option to Panels

### ISSUE THREAD

**Issue by icaroryan** [avo-hq/avo#2971]
It'd be nice if we had the `visible` option available for Panels so that we can control the visibility of all contained fields at once, without having to set them individually.

By looking at `lib/avo/concerns/visible_items.rb`, I imagine this was done by design. However, since `has_one` associations, for example, have dedicated panels and we can control whether to show all fields with `visible`, it would be great to have that much control with customized panels too.

#### Example
```rb
panel 'Foo', visible: -> { context[:user].is_admin? } do
  field 'Bar', as: :text
  field 'Baz', as: :date_time
end
```

### Current workarounds
```rb
panel 'Foo' do
  field 'Bar', as: :text, visible: -> { context[:user].is_admin? }
  field 'Baz', as: :date_time, visible: -> { context[:user].is_admin? }
  field 'Qux', as: :text, visible: -> { context[:user].is_admin? }
  field 'Fred', as: :text, visible: -> { context[:user].is_admin? }
end
```

**Comment by icaroryan** [comment]
I'm not sure if this is right, but would it be just a matter of adding `include Avo::Concerns::IsVisible` to `panel.rb`? I'm curious how I can contribute to the project.

I'm a bit unsure how to change and test AVO code on my local. But once I get that setup, I'd be happy to take on some issues

**Comment by Paul-Bob** [comment]
Hello @icaroryan thanks for the initiative.

There is this [contribution guide](https://github.com/avo-hq/avo/blob/main/CONTRIBUTING.MD) that will help you with the setup. 

Let us know if you find any obstacles

**Comment by icaroryan** [comment]
Thanks @Paul-Bob!

**Comment by icaroryan** [comment]
Hi @Paul-Bob, I managed to set up the project locally and I successfully implemented the feature 🚀
I do have some questions about testing, but I'll save them for when I open the PR, which I should be able to do as soon as I get the rights to do so. Can you help me with that?

**Comment by Paul-Bob** [comment]
Great news!

> which I should be able to do as soon as I get the rights to do so. Can you help me with that?

You should be able to create a PR from a forced branch

**Comment by binarygit** [comment]
Hey @icaroryan You don't need any special rights to open a PR.

If you've forked this repo you'll be able to send in a PR. You can follow the steps outlined [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and feel free to comment here if you get stuck :smile:

**Comment by icaroryan** [comment]
Perfect, thank you guys! I managed to get it going!
