### ISSUE TITLE
Wrong UI displaying when combining dynamic filters on the same field

### ISSUE THREAD

**Issue by TobiasKampAdmin** [avo-hq/avo#2976]
### Describe the bug
When you use a `dynamic filter` twice, the query is perfomed correctly and the URL is also correct.
BUT the displaying in the UI of the filters, is showing the wrong condition and value.

### Steps to Reproduce
1. Add a dynamic filter to for example a number field like this:
```ruby
          type: "number",
          conditions: {
            is: "=",
            gte: ">=",
            lte: "<=",
          }.invert,
          query: -> {
            case filter_param.condition.to_sym
            when :is
              # TODO for custom field to typecast to integer
              query.where("#{my_col.query_selector} = ?", filter_param.value)
            when :gte
              query.where("#{my_col.query_selector} >= ?", filter_param.value)
            when :lte
              query.where("#{my_col.query_selector} <= ?", filter_param.value)
            else
              query # unknown
            end
```

2. Go to the resource in the browser

3. Filter on the field with the filter like '>=60'. You will get an URL like this: 
`.../avo/resources/avo_playgrounds?filters[number_column][gte][]=60 `
And a UI like this, 100% correct:
<img width="432" alt="Scherm­afbeelding 2024-07-12 om 15 56 05" src="https://github.com/user-attachments/assets/746645e7-e591-49d2-abea-e16a21a937b3">

4. Filter again on the same field with '<=70'. You will get an URL like this: 
`.../avo/resources/avo_playgrounds?filters[number_column][lte][]=70&filters[number_column][gte][]=60`
The filtering is done correctly and you actually have a list where the field is BETWEEN 60 and 70, this behavior is perfect!

BUT the UI is displaying two times the first filter:
<img width="617" alt="Scherm­afbeelding 2024-07-12 om 15 58 03" src="https://github.com/user-attachments/assets/cd93bdf6-961e-4dc9-be73-52418688bda6">
This remains the same when you reload.

This is the same for other filter types, the number-type is just an example.

### Expected behavior & Actual behavior
Show each of the filters correctly in the UI above the table/grid.

Like this for the example:
<img width="616" alt="Scherm­afbeelding 2024-07-12 om 15 59 59" src="https://github.com/user-attachments/assets/f5704cfa-3400-4384-91be-b095539d1cae">

### System configuration
**Avo version**: 3.10.2 (you need to have the dynamic filters) 

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
[This PR](https://github.com/avo-hq/avo-dynamic_filters/pull/52) fixed this issue. Let us know if still happening on Avo `3.10.5` and please re-open this issue if the problem persists.

**Comment by TobiasKampAdmin** [comment]
THanks, I tested this after bumping our version of Avo to `3.10.6` , but I'm getting an error now when filtering multiple times on the same field: 

So for example on an URL like this:
`.../avo/resources/avo_playgrounds?filters[number_column][lte][]=60&filters[number_column][gte][]=50`

Error:
```
undefined method `with_indifferent_access' for [#<Avo::DynamicFilters::ParamFilter:0x0000ffff0fbc6cb8 @condition="lte", @id="number_column", @value="60">, #<Avo::DynamicFilters::ParamFilter:0x0000ffff0fbc6c68 @condition="gte", @id="number_column", @value="50">]:Array

      def build(params)
        params.with_indifferent_access.each do |key, value|
          case key
          when /^(g|c|m)$/
            self.send("#{key}=", value)
```
![Scherm­afbeelding 2024-07-18 om 15 05 27](https://github.com/user-attachments/assets/5e0072ac-914b-4fa0-973a-c26a056fc230)

Can you have a look at this?

**Comment by Paul-Bob** [comment]
Thanks for reporting it @TobiasKampAdmin I'm pushing a fix. Also will release Avo `3.10.7` later today which will include this fix.
