### ISSUE TITLE
Fix dynamic filters `enum`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2979]
Investigate what's wrong with the `enum` dynamic filter.

Possible correlation: https://discord.com/channels/740892036978442260/1201874761546735636/1260949982886756443

**Comment by Paul-Bob** [comment]
Closing in favor of #2822

**Comment by SahSantoshh** [comment]
Please take a look https://github.com/avo-hq/avo/issues/2822#issuecomment-2226288733

**Comment by SahSantoshh** [comment]
More info on the bug https://github.com/avo-hq/avo/issues/2822#issuecomment-2226852021
