### ISSUE TITLE
Allow to customize the default sorting attribute

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#2982]
By default, records are sorted by the `created_at` attribute (if it exists)

Let's make it possible to globally customize the sorting attribute.

## Approach

- Add a configuration option (name to be decided)
- Apply that option if configured around [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/base_controller.rb#L308)

**Comment by iamworrell** [comment]
can you assign this task to me?

**Comment by Paul-Bob** [comment]
> can you assign this task to me?

Sure, thanks for looking into it!

**Comment by iamworrell** [comment]
@Paul-Bob im sorry thought this was a react project, no idea it was ruby. You can assign someone else

**Comment by icaroryan** [comment]
@Paul-Bob if you want I can take this one

**Comment by adrianthedev** [comment]
You got it, @icaroryan!

**Comment by adrianthedev** [comment]
Hey @iamworrell 👋

Rails is quite easy to pick up and we're a friendly bunch ✌️
If you'd like to give it a try, we'll find something for you to start with.

**Comment by icaroryan** [comment]
@adrianthedev @Paul-Bob Would we still want to keep the sort_by created_at if the default_sort_column set in the configuration doesn't exist in the model? I think it's a good idea

**Comment by adrianthedev** [comment]
Yes! Keeping it is going to prevent a breaking change for existing users as well.
