### ISSUE TITLE
Boolean field always treats null as falsey

### ISSUE THREAD

**Issue by serene** [avo-hq/avo#2996]
### Describe the bug

When a boolean field is nullable, it shows false as a red X instead of a dash.

### Steps to Reproduce
Create a boolean field that has a false value.

### Expected behavior & Actual behavior
The field should display on index and show as a dash "-".

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
@Paul-Bob Let's also add this mention on the upgrade guide.
