### ISSUE TITLE
Two jobs enqueued when Turbo instant click disabled

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3001]
Hi,

If I have Turbo Instant Click enabled then this link (which enqueues a job), queues a single job on both hover as well as when clicked:

`<li><%= link_to "Update Media", main_app.update_media_path %></li>`

I wished to disable Instant Click so disabled it in the Avo Initialiser with:

```
    config.turbo = -> do
        {
          instant_click: false
        }
      end
```

This or adding `data-turbo-prefetch="false"`, does stop the Instant Click functionality BUT when the link is clicked, TWO of the same job get enqueued.

Bit confusing but seems to be the case.  I've now experienced this in two separate apps when I have a link to an action that enqueues a job, that is clicked from within Avo.

**Comment by Paul-Bob** [comment]
Hey @rctneil It seems that this particular request is triggered twice somewhere. Can you please share a reproduction repository?

**Comment by adrianthedev** [comment]
Is that a `GET` request which triggers a job?
If so, wouldn't it be better to use a `POST` request for that? In that way, Instant click would not try to fetch it and in turn trigger it.

**Comment by rctneil** [comment]
It is a get request.  

Would doing that merely be a case of adding 'method: :post' to the link and updating the route?

**Comment by adrianthedev** [comment]
It's `data: {turbo_method: :post}` and change the route to support post requests, not get.

Closing for now.
