### ISSUE TITLE
Handle case when record is invalid and new image is attached

### ISSUE THREAD

**Issue by iljandi** [avo-hq/avo#3008]
### Describe the bug

Avo breaks when the user adds a new image, makes an error in other form field, and tries to save/update the record.

### Steps to Reproduce

I was able to reproduce the issue using the [main.avodemo.com](https://main.avodemo.com) app:

1. [Open Posts](https://main.avodemo.com/avo/resources/posts/)
2. Edit existing post:
- remove `name` (which is required)
- attach new `cover photo`
- click on save

### Expected behavior & Actual behavior

_Expected behavior:_
The form is displayed again with errors.

_Actual behavior:_
App crashes with `ArgumentError: "Cannot get a signed_id for a new record"`. 
The problem is with `app/components/avo/fields/common/files/view_type/grid_item_component.html.erb`, line: 5. `helpers.main_app.url_for(file)` does not work. 

### System configuration

Avo version: 3.10.6

Rails version: 7.2 beta

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by binarygit** [comment]
Hey. Thanks for reporting this. We are looking into it!
