### ISSUE TITLE
make search.hide_on_global accept a lambda

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3011]
### Feature
see code below

```ruby
class GenericResource < Avo::BaseResource
  self.search = {
    query: -> { ... },
    hide_on_global: -> { resource.model_class.table_name.starts_with?("foo") } # 👈 currently only true/false allowed while we want to pass a block
  }
end

class Avo::Resources::Person < GenericResource
end

class Avo::Resources::Booking < GenericResource
end

...
```

❗ please at least make `resource.model_class` available within this block (or anything else that can make me identify which resource this was called onto)

### Current workarounds
None

### Additional context
We use avo in a very "meta"/DRY way.
All of our resources inherit from `GenericResource`.
This is why we need the lambdas (and also need the `resource.model_class` ) to know in which context we are operating

**Comment by binarygit** [comment]
`hide_on_global` already accepts a lambda and it also allows you to query which model class it's being called from. Just like you want for your use case.

![annotely_image(1)](https://github.com/user-attachments/assets/420b6369-970c-41a6-95da-cfb324793ee1)

Please try it out and let me know if it's not working on your end :pray:

**Comment by pjmuller** [comment]
My bad, your totally right, this works perfectly.
Thanks!

**Comment by binarygit** [comment]
No worries 😅
