### ISSUE TITLE
Implement support for custom search system

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3012]
### Feature
Accoring to @adrianthedev we should be able to pass an `array` or `object` (rather than the standard `ActiveRecord::Relation`) within `query`.
Yet the exact syntax is not documented anywhere. 

@adrianthedev pulled out this snippet but doesn't seem to be the right one.

```ruby
class Avo::Resources::Person < Avo::BaseResource
  self.search = {
    query: -> { 
      [{
        _id: "123", _label: "abc", _url: "#"
      }]
    }
end
```

Could someone document how we can return output from our own search system (e.g. coming from elasticsearch, API, ...)

**Comment by Paul-Bob** [comment]
>Accoring to @adrianthedev we should be able to pass an `array` or `object` (rather than the standard `ActiveRecord::Relation`) within `query`.
Yet the exact syntax is not documented anywhere. 
> @adrianthedev pulled out this snippet but doesn't seem to be the right one.

The code from the shared snippet is not possible with the current version without some method overriding inside `Avo::SearchController`

Anyway, it is possible and there is a documented API to customize the `title` and the `result_path`.

To customize the `title` ([check docs here](https://docs.avohq.io/3.0/search.html#title))

```ruby
self.search = {
    query: -> { query.ransack(name_cont: params[:q], m: "or").result(distinct: false) },
    item: -> do
      {
        title: "[#{record.id}]#{record.name}",
      }
    end
  }
```

Customize the `result_path` ([check docs here](https://docs.avohq.io/3.0/search.html#result_path))

```ruby
class Avo::Resources::City < Avo::BaseResource
  self.search = {
    query: -> { query.ransack(name_eq: params[:q]).result(distinct: false) },
    result_path: -> { avo.resources_city_path record, custom: "yup" }
  }
end
```

> Could someone document how we can return output from our own search system (e.g. coming from elasticsearch, API, ...)

If your `query` result can return active records you can use the above suggestion otherwise we should implement some DSL close to what Adrian presented.

**Comment by Paul-Bob** [comment]
I'm interpreting this as a feature request (correct me if I'm wrong)

## Aproach

Check the query returned value [around here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L58), if it is an array don't apply the `apply_search_metadata` method on it.

Possible code: (untested)
```ruby
      results = apply_search_metadata(query, resource) unless query.is_a?(Array)
```

**Comment by adrianthedev** [comment]
I tested the code and the issue seems to be in the search controller when we try to count all the results.
Avo tries to count it as an active record query and we shouldn't do that. 
At least check if it's AR. If it isn't we should remove the count for now and allow the use to pass anything that would result in an array of hashes. 

We also need to document this process can you please add a ticket for that?

**Comment by Paul-Bob** [comment]
> I tested the code and the issue seems to be in the search controller when we try to count all the results. Avo tries to count it as an active record query and we shouldn't do that. At least check if it's AR. If it isn't we should remove the count for now and allow the use to pass anything that would result in an array of hashes.
> 
> We also need to document this process can you please add a ticket for that?

Everything in this green area should be adapted to also work with arrays.

![image](https://github.com/user-attachments/assets/723d84a7-1891-4f66-b2ed-39c68d64ab1c)

The count can be done by `query.size` the limit can be done by `query.first(8)` and we only need to figure out how to extract the highlight method to also apply highlights on labels when passed as an array.

 I will adapt this issue to be the feature request so we don't lose context.

**Comment by pjmuller** [comment]
@Paul-Bob , 
- yes you can interpret it as a feature request if it's not possible yet.
- I'm aware of the `title` and `result_path` however I would want to bypass the whole active record relation thing (while the 2 methods still rely on `record`)
- so would be great if at some time you allow us (without monkey patching) to return an array in some search configuration. But for now I have enough workarounds and is low/med prio

**Comment by Paul-Bob** [comment]
Yes @pjmuller, we'll implement this as a first-party feature.

@adrianthedev I'm wondering if we should separate the key for the query and for the custom results array:

For active records query:
```ruby
self.search = {
    query: -> { query.ransack(name_cont: params[:q], m: "or").result(distinct: false) }
  }
```

For custom results:
```ruby
  self.search = {
    results: -> { 
      [
        { _id: "123", _label: "abc", _url: "#" },
        { _id: "1232", _label: "abc2", _url: "#2" }
      ]
    }
  }
```

**Comment by adrianthedev** [comment]
I see what you mean, but before we go down that route of adding another API, how about this.

- in the search controller try to figure out if the result is an ActiveRecord query.
- if so, do whatever we do now
- if it's not, prevent the counting and the limit statements and treat it as an array.

This way we don't change the API, indeed, we remove the count from the results, but support any search provider.

If later we want to readd the count, we can create a special API for it.

```ruby
# possible API
self.search = {
  query: -> {
    search_args = SOME_SEARCH_PROVIDER.perform_search(params[:q])

    # run this method to set the count
	records_count search_args[:count]

    # return the results to display to the user
    search_args[:records]
  }
}

What do you think @pjmuller and @Paul-Bob?

Also, @pjmuller do you need the `count` now? If so, how would you perform the search with a different provider?

**Comment by Paul-Bob** [comment]
Let's keep the API.

The count and the limit are straightforward to adapt for array results, there is no need to exclude them and limit the feature.

**Comment by Paul-Bob** [comment]
The count and limit could become more complex when the search service applies a restriction, returning only a subset of the total results while still including the overall count in the response.

@pjmuller, what's your scenario? Will your custom search return all the results, or will it be limited to a subset of the total results?
