### ISSUE TITLE
Pagy 9.0.0 not compatible with Avo 3.10.6

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#3014]
### Describe the bug

Pagy 9.0.0 not compatible with Avo 3.10.6

### System configuration
**Avo version**:
avo (3.10.6)

**Rails version**:
rails (7.2.0.beta3)

**Ruby version**:
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![image](https://github.com/user-attachments/assets/e8bbecf1-a586-4057-a643-90c8226dc823)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by binarygit** [comment]
Hey @jetienne Thanks for creating this issue. We really appreciate you letting us know about this. We will have a fix for this shortly!

**Comment by giedriusr** [comment]
Same here, but today was too lazy to open an issue :))

**Comment by tvararu** [comment]
To work around this for now, you can manually specify an older Pagy version in your `gemfile`:

```ruby
gem "pagy", "< 9"
```

**Comment by rickychilcott** [comment]
Thanks. I didn't find this issue immediately because I searched for `@pagy.items`. 

I'm adding this comment so hopefully, others will see it!

**Comment by gkunwar** [comment]
Thanks @jetienne creating this issue. As I'm first time user, was struggling to fix. Finally found work around. Thanks @tvararu

**Comment by adrianthedev** [comment]
I found this to be the list of breaking changes.
https://ddnexus.github.io/pagy/changelog/#simple-renaming

Would someone be able to take this and make Avo compatible with pagy 9 as well?
This version shoul dbe added to the current pagy versions we support, not replace them. Some folks are using pagy outside Avo and they need compatibility with versions 7 or 8.

Thank you!

**Comment by Paul-Bob** [comment]
Avo has pagy 9 compatibility since version 3.10.8

**Comment by koppen** [comment]
I didn't immediately find this issue searching for the actual error message, so here it is for posterity:

```
undefined method `items' for an instance of Pagy
```

[Locking pagy to < 9](https://github.com/avo-hq/avo/issues/3014#issuecomment-2238690884) does fix the problem, though, and here's hoping https://github.com/yshmarov/avo/commit/418661ef34cc1a4e65ab182effd714240bc0db1f gets backported to the 2.x line.

**Comment by koppen** [comment]
- Avo 2.52 (hoping for https://github.com/avo-hq/avo/pull/3050 backport 🤞)
- Pagy 9.something (which broke things).

**Comment by Paul-Bob** [comment]
Is something blocking you from updating to avo `3.x`?

**Comment by koppen** [comment]
A 40%+ price increase, which our customer doesn't see the value in paying for just yet.

**Comment by Paul-Bob** [comment]
> A 40%+ price increase, which our customer doesn't see the value in paying for just yet.

I guess you missed the email with the avo2 -> avo3 update. We also mention it [here](https://docs.avohq.io/3.0/avo-2-avo-3-upgrade.html#upgrade-from-2-x-to-3-x) that:

>We upgraded all Avo 2 Pro licenses to Avo 3 Pro licenses without any cost additions.
If you had an Avo 2 license, you received an email about that and instructions on next steps.
Thank you for being an awesome customer! 

Please check if you have your license [here](https://avohq.io/licenses)

**Comment by koppen** [comment]
Oh, I very much did miss that, yes. Probably because I am not the purchaser of the license ;) I will get in touch with the customer and see if we can schedule an upgrade. Thanks!

**Comment by jmarsh24** [comment]
I'm also running into this issue on avo 2.53

**Comment by Paul-Bob** [comment]
@jmarsh24 is something blocking you from updating to avo `3.x`?
