### ISSUE TITLE
action fields > record or resource not behaving consistently

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3021]
### Describe the bug
See code below

```ruby
class Avo::Actions::HappyBirthday < Avo::BaseAction
  def fields
    person = record || Person.find(params[:fields][:avo_resource_ids]) # 👈

    field :number_of_cancles, as: :number,  value: person.age
  end
end
```

whenever I post the action form, the `Avo::ActionsController#handle` calls the `fields` method (most likely to know which `params[:fields]` are safe.

Tet in that context the `record` becomes `nil` (as well as `resource.record`).
So without my hack `Person.find(params[:fields][:avo_resource_ids])` the code crashes with `undefined age for nil`.
This hack feels too much based on the internal API (of the param `avo_resource_ids`) so is not long term suited

Solution?
Make the record also available within the Avo::ActionsController#handle context?

Sidenote: when you get to an action via `navigate_to_action` the record is also not present anymore, though in that scenario I can understand we have to pass the ID as `arguments` because is not always tied to a specific resource.record

### System configuration
**Avo version**: 3.10.6

**Rails version**: 7.2.0.beta

**Ruby version**: 3.2.2

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [X] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hey @pjmuller is this happening from the record's `show` view?
