### ISSUE TITLE
`date` and `date_time` can't be used as computed fields

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#3023]
### Describe the bug

They still use `model[id]` and they shoudl use `model.send(id)`.
Same for getters and setters.

### Approach

Change it to `send` as we did on https://github.com/avo-hq/avo/pull/2985

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by pravo23** [comment]
Hi, Can I work on this?

**Comment by Paul-Bob** [comment]
Yes @pravo23, we appreciate it!

**Comment by adrianthedev** [comment]
Thank you @pravo23!

**Comment by pjmuller** [comment]
thanks @pravo23 , I've checked your PR and looks what we need ❤️
