### ISSUE TITLE
[RFC] Remove the `includes` statement from the search query

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#3024]
### Context

Some don't need the whole `includes` statement in the search and that can bring overhead to that particular `query`.

### Proposal

Removing the `includes` statement from the `search[:query]` API.
Users will still be able to add their own `includes` statement in the `searc[:query]` section.

**Comment by Paul-Bob** [comment]
@adrianthedev At first sight it seems that `self.includes` aren't being included in the search query.

**Comment by adrianthedev** [comment]
Oh, OK
I had a pairing session with @pjmuller and found some eager loading in the logs and thought it was that. 
Ok. Thanks for checking. I'll close it for now.

**Comment by pjmuller** [comment]
@adrianthedev & @Paul-Bob: just to clarify, I'm not using the `self.includes` but the `index_query` where I'm applying `query.includes()`. Is that one being used in search?

If not I'll further dig deeper in my codebase why I do see this in my project and create a reproduceable code snippet

**Comment by Paul-Bob** [comment]
Yes @pjmuller the `index_query` is used on search as the base query and it makes sense.

You are in control of `index_query` and you can do an early return for the search controller:

```ruby
  self.index_query = -> do
    return query if controller_name == "search"

    query.order(last_name: :asc)
  end
```

I'm reopening this issue until you confirm that this works for you.

**Comment by Paul-Bob** [comment]
@pjmuller any updates on this one?

**Comment by pjmuller** [comment]
Apologies for not getting back, I decided to do the searching in a different way so this ticket is not relevant anymore
