### ISSUE TITLE
Hiding the rails version issues in production

### ISSUE THREAD

**Issue by jpawlyn** [avo-hq/avo#3030]
Just wandering if appending `Rails.env.local?` to the conditional for the display of rails version issues would be useful or is there some other way to easily hide it like with an env var ie `ENV['AVO_RAILS_VERSION_ISSUES'] != 'hide'`

The problems mentioned thankfully don't seem to apply to us so it would be useful for us to be able to hide the message without a monkey patch. 

For context please see:
https://github.com/avo-hq/avo/blob/34c48c7e65d0862aa237c77dca23dc29c4daeb15/lib/avo.rb#L149-L160

**Comment by Paul-Bob** [comment]
These messages should be rendered only in local environments. It's a bug if those are rendered on production, @binarygit could you have a look, please?

`Avo.error_manager` should render the messages only locally, at first glance at the code I couldn't identify the check for the environment so this might be broken.

**Comment by Paul-Bob** [comment]
@jpawlyn this should be fixed since 3.10.8, thanks for reporting it
