### ISSUE TITLE
TipTap label and field IDs don't match

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#3036]
### Describe the bug

TipTap field label (id is `post_content`):

```html
<label for="post_content">Content</label>
```

TipTap textarea (id is `tiptap_post_content`):

```html
<textarea class="appearance-none inline-flex bg-gray-25 disabled:cursor-not-allowed text-gray-600 disabled:opacity-50 rounded py-2 px-3 leading-tight border focus:border-gray-600 focus-visible:ring-0 focus:text-gray-700 placeholder:text-gray-300 border-gray-200  w-full hidden" data-tiptap-field-target="input" data-resource-edit-target="contentTiptapInput" id="tiptap_post_content" placeholder="Content" style="" name="post[content]"></textarea>
```

This prevents from getting textarea focused when clicking on label and results in browser reporting an issue:

```
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
```

### Steps to Reproduce
1. Add tiptap field
2. Go to new record in Chrome
3. Open Chrome inspector
4. Go to Issues tab
5. See error

### Expected behavior & Actual behavior

Label id for the field and actual field id should match. This makes sure that when user clicks the label input focus is getting to the correct field.

### Models and resource files

```ruby
class Avo::Resources::Post < Avo::BaseResource
  def fields
    field :content, as: :tiptap
  end
end
```

### System configuration
**Avo version**: 3.10.7
**Rails version**: 7.1.3.4
**Ruby version**: 3.1.6
**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

N/A

### Additional context

N/A

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Aaryanpal** [comment]
@Paul-Bob can you assign this to me

**Comment by Paul-Bob** [comment]
Sure @Aaryanpal, thank you!
