### ISSUE TITLE
belongs_to dynamic filter config to allow select

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#3038]
### Feature
When defining a belongs_to filter, it would be very convenient to add two options:
- allow the type `select` for belongs_to association
- `searchable` true or false: like for fields, when true, it would turn the filter from a select input to a searchable experience

The current implementation would then be extended like:

```ruby
dynamic_filter label: "User (email & first_name)",
  type: :select,
  searchable: true,
  icon: "heroicons/solid/users",
  query_attributes: [:user_email, :user_first_name]
```

### Current workarounds
The current workaround, to have a text search box for belongs_to association is not really suitable when the user doesn't know the possibles values.

**Comment by Paul-Bob** [comment]
> allow the type `select` for belongs_to association

The select for association is already possible using the `options` since `3.10.10` @jetienne 

### Code

```ruby
  def filters
    dynamic_filter label: "User (email & first_name)",
      type: :select,
      options: (User.pluck(:first_name) + User.pluck(:email)).select(&:present?),
      icon: "heroicons/solid/users",
      query_attributes: [:user_email, :user_first_name]
  end
```

### Video
https://github.com/user-attachments/assets/c1c8437a-42cb-41ba-b40e-379fc34c0379

#

> `searchable` true or false: like for fields, when true, it would turn the filter from a select input to a searchable experience

Closing this one since there is already [this issue](https://github.com/avo-hq/avo/issues/2980) tracking autocomplete fields for filters.

**Comment by Paul-Bob** [comment]
Hi @danielbwa we want to support it and there is an issue tracking a proper autocomplete field for filters. https://github.com/avo-hq/avo/issues/2980

As a workaround, you can use a tags filter with `fetch_values_from` option https://docs.avohq.io/3.0/dynamic-filters.html#fetch_values_from

If you go with this workaround you'll need to change `options` with `suggestions` https://docs.avohq.io/3.0/dynamic-filters.html#suggestions

Let me know how it goes

**Comment by danielbwa** [comment]
Thanks @Paul-Bob !

Looking at the workaround, I believe that will offer a solution for now. Hopefully something like [HotwireCombobox](https://hotwirecombobox.com/) will be available.
