### ISSUE TITLE
First action border is mistakenly bold

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3040]
![image](https://github.com/user-attachments/assets/b37d5441-6fb3-40e6-9209-ef9f232c2556)

The first border between actions is bolder than others

**Comment by adrianthedev** [comment]
![CleanShot 2024-10-04 at 00 47 52@2x](https://github.com/user-attachments/assets/c96db26b-22b8-48eb-8a49-f73ff8cca363)
Doesn't seem to happen anymore.
