### ISSUE TITLE
Avo resource generator renaming resource file

### ISSUE THREAD

**Issue by iyerushalmi** [avo-hq/avo#3047]
### Describe the bug
I ran the command:

`rails g avo:resource ShipmentItemReceive
`
The response was:

```
Avo advanced 3.10.2
-- check_all_pending!()
      create  app/avo/resources/shipment_item_receife.rb
      create  app/controllers/avo/shipment_item_receives_controller.rb
```

It seems the system named the file shipment_item_receife.rb instead of shipment_item_receive.rb. I am not sure why.

**Comment by Paul-Bob** [comment]
Interesting one, at first sight it seems to be an rails issue around here https://github.com/rails/rails/blob/main/railties/lib/rails/generators/named_base.rb#L150

**Comment by adrianthedev** [comment]
I agree. It doesn't seem to be Avo related. 
Thanks for sending this in.
