### ISSUE TITLE
main_menu not being applied

### ISSUE THREAD

**Issue by djolereject** [avo-hq/avo#3052]
### Context
I'm trying to customize `main_menu` as per docs but it appears that whatever I put there, it's still showing all resources like it did before I tried any cusomization. 
I tried 

```
config.main_menu = -> {
    section "Anything, icon: "resources" do
      group "Test", collapsable: true do
        all_resources
      end
}
```
but it's just not working. 

Is there any way that this gets overwritten somewhere? I tried adding binding.pry in the initializer and it's obviously getting read, but changes are not applied.

### System configuration
**Avo version**: 3.3.0

**Rails version**: 7.1.3

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
BTW, on the Community license you can hide resources from the menu on a per-resource basis
https://docs.avohq.io/3.0/resources.html#self_visible_on_sidebar

**Comment by djolereject** [comment]
Thanks!
