### ISSUE TITLE
Side menu always displays

### ISSUE THREAD

**Issue by jpawlyn** [avo-hq/avo#3059]
### Describe the bug
On upgrading from Avo 3.10.7 to 3.10.8 or 3.10.9, the side menu on mobile view is always displaying when either a resources menu item or a record link is clicked. 

### Steps to Reproduce
1. Switch to a mobile view
2. Click on a resources menu item

### Expected behavior & Actual behavior
For Avo 3.10.7, when a resources menu or link is clicked on the mobile view, no side menu appears when the new page has been loaded. For Avo 3.10.8 and 3.10.9, the side menu is always displayed.

### System configuration
**Avo version**:
3.10.9

**Rails version**:
7.1.3.4

**Ruby version**:
3.3.4

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/user-attachments/assets/7ad381b2-0e6b-4fb8-9e60-4f5380284fa4

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Thanks for sending this in.
This might be related to https://github.com/avo-hq/avo/pull/3041.

We'll have a look!

**Comment by adrianthedev** [comment]
@G-Simpson would you be available to have a look at this?

**Comment by G-Simpson** [comment]
> @G-Simpson would you be available to have a look at this? Maybe there's a CSS-only version of fixing this bug.

Sorry I've been away for a few days. Glad to see it was resolved
