### ISSUE TITLE
PG::UndefinedTable: ERROR:  missing FROM-clause entry for table

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#3063]
### Context
I have a join model that is resulting in the following error only when joining songs. The person relation is rendering fine but not the song. I'm rendering the person_roles from the admin interface.

https://github.com/jmarsh24/tangocloud/pull/166

summary of relevant models and migrations
https://gist.github.com/jmarsh24/8643ecc327edfc0de535f0453fe24e46

`app/avo/resources/external_catalog_el_recodo_person_role.rb` 
`app/avo/resources/external_catalog_el_recodo_person.rb`
`app/avo/resources/external_catalog_el_recodo_song.rb`

```
ActionView::Template::Error (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "person_roles"
LINE 1: ...atalog_el_recodo_person_roles"."song_id" = $1 AND "person_ro...
                                                             ^
):
    1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
    2:   <%= render @component.new(
    3:       resource: @resource,
    4:       resources: @resources,
    5:       records: @records,
  
  ```

### System configuration
**Avo version**:
3.10.6
**Rails version**:
7.1.3
**Ruby version**:
3.2.4
**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

### Screenshots or screen recordings

<img width="1082" alt="image" src="https://github.com/user-attachments/assets/d286e318-eed8-4197-b432-ee3d564db22e">

**Comment by Paul-Bob** [comment]
Is this fixed @jmarsh24? Anything from the avo side?

**Comment by jmarsh24** [comment]
Yes it actually ended up being an issue in my title that was referencing the join tables. I ended up creating a database field for it instead so it's not an issue.

**Comment by Paul-Bob** [comment]
Thanks for letting us know
