### ISSUE TITLE
Fix base resource extending

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3073]
### Context

Move `lib/avo/base_resource.rb` under `app/avo/base_resource.rb`

**Comment by adrianthedev** [comment]
Is there a reason why we need to do that?

**Comment by Paul-Bob** [comment]
Feels more natural to override it on `app/avo/base_resource.rb` path than `lib/avo/base_resource.rb`

**Comment by Paul-Bob** [comment]
Also would be coherent with `app/controllers/avo/resources_controller.rb`
