### ISSUE TITLE
Show an array of items as association table

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3112]
### Context

Let's make a brief recipe on how to "hack" and show an array of items as association table

```ruby
users = [
  {
    name: "Nancy",
    age: 34
  },
  {
   name: "Vince",
   age: 43 
  },
  # ...
]
```

```ruby
field :users, as: :has_many
```

**Comment by adrianthedev** [comment]
Hey @rctneil here's the chat with the hack that I mentioned.

Please let me know if that worked for you.

If you set up a reproduction repo, we can try to apply the hack for you.

Thanks!

https://discord.com/channels/740892036978442260/1207036282732150824

**Comment by adrianthedev** [comment]
I’m closing this issue to keep the queue clean, but please feel free to comment or reopen if needed.

**Comment by adrianthedev** [comment]
Please track https://github.com/avo-hq/avo/issues/1418 to see when we'll support array drivers for `has_many`.

**Comment by rctneil** [comment]
@adrianthedev Just got this working for the first time.  I think I was overcomplicating it.   Simplified it down and it now works a treat!  Love this!

Used:

`has_many :versions, class_name: "Attraction"`

```
        def versions
            self.class.where(version_of: version_of).reorder(order_ridden: :asc)
        end
```

`field :versions, as: :has_many`
