### ISSUE TITLE
Drag and drop UI for reordering in a hierarchy

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3115]
I'd love an expansion to the drag and drop reordering feature where you can drag and drop left and right to add hierarchies to resources.

Underneath this could be structured via parent child etc or acts as nested set.  

Would also provide a nice visual view of the structure of a Resource record type.

I see it as working similarly to the Wordpress menu editor

Example in image below:
![image](https://github.com/user-attachments/assets/8eb85f95-4208-4341-9fa4-0e178a48e39a)

**Comment by adrianthedev** [comment]
Hey @rctneil I know we talked about this on the Office Hours call.
I had mentioned it there as well; we need a specific use-case to be able to evaluate or build this.
The Wordpress example has a specific use case. It's managing menu items in menus. We don't have that and probably won't for a while as we manage our menus with code.
If you have a different one that can be applied largely to other code-bases, yes, please write more about it so we can discuss it.
If it's something very specific, then, it can be done using custom code and probably should be done like that.

So, I'm looking forward to the use-case as it could be something that we overlooked and people might need it.

**Comment by rctneil** [comment]
Hey @adrianthedev I can see this being super useful for any Resource Models that may use some sort of parent-child setup/gem such as awesome_nested_set.

Having a "Hierarchy" view of that resource could show all the records in their hierarchy and then users can grab a grab handle / the record itself and drag it up and down / left and right to position it where it needs to be.

I see a benefit to this as users can at a glance visually see the structure of their records.

I can also see this possible working as another View of a resource OR in a way like you demoed for the upcoming Kanban board if it is to support multiple Resource types.

I could also see an option to allow people to specific whether it should allow only up/down movement (like current record re-ordering), or up/down and left/right in order to make it super flexible.

It could be used to manage ordering of a multi level navigation / menu (as in Wordpress' case, or handling A family structure, or Photo Albums in Collections, or even just a basic file/folder hierarchy like in Finder/Windows Explorer.

I hope this explains a few use-cases.

**Comment by adrianthedev** [comment]
Do you have any examples UIs in the wild? Something where we can gather inspiration from.
Also, we need to find a JS plugin that already does this and supports the options we want as I don't want us building and maintaining that.

**Comment by rctneil** [comment]
I'll take a look around and get back to you.
