### ISSUE TITLE
Show/Hide attribute or change it's value depending on other attribute's value

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#3118]
### Feature
1. Similar to has_skills attribute checkbox in course resource which controls the filed to hide/show on click of the checkbox. I would like to do it with ruby.
2. I want to automate some calculations depending on value of other attribute's value.

### Current workarounds
https://docs.avohq.io/3.0/stimulus-integration.html

### Screenshots or screen recordings
![Screenshot 2024-08-11 at 12 15 05 PM](https://github.com/user-attachments/assets/159f7345-a75e-45c0-98a1-887131144c1b)
![Screenshot 2024-08-11 at 12 15 12 PM](https://github.com/user-attachments/assets/79f395ab-6c24-44e7-9634-460ac06a5a41)

**Comment by Paul-Bob** [comment]
> Similar to has_skills attribute checkbox in course resource which controls the filed to hide/show on click of the checkbox. I would like to do it with ruby.

There are pre-made stimulus actions that allow you to easly toggle visibility on your fields. Let me know if those conver your use case. https://docs.avohq.io/3.0/stimulus-integration.html#pre-made-stimulus-methods

**Comment by SahSantoshh** [comment]
This request is to find a way to do in ruby instead of going deep in finding  action, JS, class names and all.

**Comment by adrianthedev** [comment]
@Paul-Bob sent you to the right location for that.
I think that the next step is actually having the dynamic fields feature which we'll have to break ground at some point.

Please subscribe to https://github.com/avo-hq/avo/issues/2983 to keep up to date.
