### ISSUE TITLE
Blank menu section is visible without any groups or resources

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#3119]
### Describe the bug

A menu section has lot's of groups and each group have multiple resources with their respective permissions. Groups are not visible as their resources are not permitted but the section is still visible. It is only working if resources are child the section or groups. But not if resource is child of group and groups are child of section

### Steps to Reproduce
Create menu sections similar to

```ruby
section 'Cources', icon: 'banknotes', collapsable: true do
  group 'Art', collapsable: true do
    resource :xyz, visible: -> { false}
  end

 group 'Games', collapsable: true do
    resource :pqr, visible: -> { false }
  end
end
```

### Expected behavior & Actual behavior

In this case, the groups are hidden but the section is still visible. Expected behaviour would be to hide the section as well

### System configuration
**Avo version**: 11.4

**Rails version**: 7.2.0

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2024-08-11 at 12 45 09 PM](https://github.com/user-attachments/assets/55ad94c1-e4fa-4687-95ef-d5df163ac8f5)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
@SahSantoshh this is fixed in Avo `3.11.7`
