### ISSUE TITLE
default_sort_column for scopes

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3137]
### Feature

Avo 3.11 introduced the default_sort_column ( https://github.com/avo-hq/avo/pull/3018 )
It would be great to have this for [scopes](https://docs.avohq.io/3.0/scopes.html) as well + add default_sort_direction

```ruby
class Avo::Scopes::Girls < Avo::Advanced::Scopes::BaseScope
  self.name = "Girls 123"
  self.scope = -> { query.where(gender: "female") }
  self.default_sort_direction = :lastname # 👈
  self.default_sort_direction = :asc # 👈
end
```

PS: adding the `  self.scope = -> { query.where(gender: "female").order(:lastname) }` doesn't work as you'll get a query like
```sql
ORDER BY people.created_at desc, "people"."lastname" ASC
```
this is very understandable and I also don't think sorting should be WITHIN the `self.scope` as it makes things too hardcoded

### Alternative

I can also get it to work if you allow the Resource level one to allow a block (via the params I could reverse engineer in which scope I am)

```ruby
class Avo::Resources::FooBar < Avo::BaseResource
  self.default_sort_column = -> {
    :lastname
  } 
  self.default_sort_direction = -> {
    :asc
  } 
end
```

**Comment by pjmuller** [comment]
@Paul-Bob , I tried it, but doesn't work as we're thinking -> https://www.loom.com/share/b57623e095d64fa9946890b9d7b1e740

So could you please consider supporting two extra attributes? (which are OVERWRITTEN if the user starts to sort by clicking in the table)

```ruby
class Avo::Scopes::Girls < Avo::Advanced::Scopes::BaseScope
  self.name = "Girls 123"
  self.scope = -> { query.where(gender: "female") }
  self.default_sort_direction = :lastname # 👈
  self.default_sort_direction = :asc # 👈
end
```

**Comment by Paul-Bob** [comment]
Got it, we'll discuss it

I wrongly put the `usnscoped` after the `where` clause on the example snippet.

This should work as a workaround since is unscoping only the `created_at` attribute.

`self.scope = -> { query.unscope(:created_at).where(gender: "female").order(:lastname) }`

**Comment by pjmuller** [comment]
Thanks @Paul-Bob for finding a solution together with me, for others, this solution ticks all boxes 🎉 

```ruby
  self.scope = -> { 
    scope = query.where(gender: "female")
    if params[:sort_by].blank?
      scope = scope.unscope(:order).order(:lastname) # to remove default :created_at DESC
    end
    scope
  }
```
