### ISSUE TITLE
Implement radio field

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3140]
### Context

Similar to the boolean group field but using radio input so the options become exclusive

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Originally requested [here](https://discord.com/channels/740892036978442260/1273023803168915608)

**Comment by zhephyn** [comment]
Hey @Paul-Bob. I'll take up this one

**Comment by Paul-Bob** [comment]
Great @zhephyn! This one is challenging! Let me know if you find any obstacles

**Comment by Paul-Bob** [comment]
Thank you!

**Comment by zhephyn** [comment]
Hey  @Paul-Bob. I'm trying to access the discord channel where the feature is stated to have been requested for initially, but it seems the link is broken. Could you provide some more context about the feature to be implemented or maybe the specific page in the application where the feature ought to be implemented. Thank you

**Comment by Paul-Bob** [comment]
Hey @zhephyn, there's not much happening on the Discord thread, it's mainly here to track the source of the original request.

>Could you provide some more context about the feature to be implemented or maybe the specific page in the application where the feature ought to be implemented. Thank you

Sure. The idea is to implement a new field that will allow this DSL:

```ruby
field :gender, as: :radio
```

This will use a radio input element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Let's take the `boolean_group` field as a reference for structuring it:

- Field definition file here: `lib/avo/fields/boolean_group_field.rb`
- Component files here: `app/components/avo/fields/boolean_group_field`

We need to build a file to keep the `radio` field and components.

**Comment by zhephyn** [comment]
Hey @Paul-Bob. It seems this issue received a PR that could result into it becoming a closed one. I was still working through my solution, but now I'm not sure how to proceed. Should i abandon working on and  submitting a PR for this issue and pick up another one? Or should i continue working on it? Any guidance is appreciated. Thanks in advance.

**Comment by Paul-Bob** [comment]
The PR for this issue is on track to be merged soon, which will indeed close it.

You're still welcome to open a PR for your current work if you'd like some feedback, though it won't be merged, I can review it to provide any insights or suggestions

I'm sorry that it happened again. I've just created this issue: https://github.com/avo-hq/avo/issues/3426. If you're interested, we can assign it exclusively to you. Let me know!

Thank you @zhephyn !
