### ISSUE TITLE
Hook on unauthorized policy

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3146]
For this feature, I can imagine a hook somewhere in the `avo.rb` or `application_policy.rb`.
Basically the developer does whatever he wants inside that block, we just need to call this hook on unauthorized action
```ruby
config.on_unauthorized_policy = ->(policy_class, action, record, user)
  # can log in console
  # can log in file
  # can send notification
  # can do whatever he wants
end
```

I guess we should not decide, who and where to see what, because each case is a different case, and each developer team should make the best decision for their app.

_Originally posted by @Paul-Bob in https://github.com/avo-hq/avo-pro/issues/86#issuecomment-2289875628_

**Comment by adrianthedev** [comment]
Closing for now until we see further feedback/research on this.
