### ISSUE TITLE
Ability to remove duplication for authorization policy for view associations records

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#3149]
### Feature
From policy helper we can inherit methods except view from another association. It would be very helpful if we can pull this methods from other policies as well.

```ruby
module Avo
  module Pro
    module Concerns
      module PolicyHelpers
        extend ActiveSupport::Concern

        class_methods do
          def inherit_association_from_policy(association_name, policy_class)
            [:create, :edit, :update, :destroy, :show, :reorder, :act_on, :attach, :detach].each do |method_action|
              define_policy_method(method_action, association_name, policy_class)
            end

            define_policy_method("view", association_name, policy_class, "index")
          end
...
```

### Current workarounds
```ruby
class RolePolicy < ApplicationPolicy
  inherit_association_from_policy :permissions, PermissionPolicy

  def view_permissions?
    false
  end

.....
end
```

**Comment by Paul-Bob** [comment]
`view_...?` is already being applied [here](https://github.com/avo-hq/avo-pro/blob/main/lib/avo/pro/concerns/policy_helpers.rb#L13). I'm closing this one as fixed, feel free to comment or reopen it if something is not working as expected.

Please don't publically share code from `avo-pro` or other paid packages.
