### ISSUE TITLE
Add option to specify what component to use on `grid_view`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3155]
> I'm working on building out a system that lists events. In the grid view, I'd like to show the date and time as well as some other information in addition to the title and description/body. 
Do I do that with a partial card? If so, how do I tell the resource to use that card instead of the default?
Or, is there a way to add more fields to the default resource cards displayed?

_Originally posted by @cmaxw in https://github.com/avo-hq/avo/discussions/3154_

# Possible DSLs

## Override whole component
With this approach, the user should begin by ejecting the current component within a specific scope, then make modifications from there.

![image](https://github.com/user-attachments/assets/1855e8af-ff84-4458-95d5-d3695f8e7bfc)

```ruby
  self.grid_view = {
    component: ...
  }
```

## Additional partial
I'm suggesting this partial approach because overriding the entire component requires manually rendering the controls. The user might prefer to retain the existing appearance while simply adding extra information, without the need to figure out how to replicate the current design in a new component.

```ruby
  self.grid_view = {
    card: -> do
      {
        cover_url:
          if record.cover_photo.attached?
            main_app.url_for(record.cover_photo.url)
          end,
        title: record.name,
        body: ActionView::Base.full_sanitizer.sanitize(record.body).truncate(130),
        extra_partial: ...
      }
    end
  }
```

![image](https://github.com/user-attachments/assets/49cbb11f-baf5-45b6-a10e-3e47ee9796ed)

**Comment by adrianthedev** [comment]
Maybe we can use this API to change more than just the grid view.

```ruby
self.components = {
  "Avo::Index::GridItemComponent": "Avo::Index::CustomGridItemComponent",
  "Avo::RowComponent": "Avo::CustomRowComponent",
  "Avo::Views::ResourceIndexComponent": "Avo::Views::CUSTOMResourceIndexComponent"
}
```

You get the point...

**Comment by cmaxw** [comment]
As mentioned in the Discussions [here](https://github.com/avo-hq/avo/discussions/3154) the [extra fields PR](https://github.com/avo-hq/avo/pull/2650) would also solve this problem.

For meetups, podcast episodes, etc on my app, it's be really great to be able to add these fields in.

Note that I'm trying to add a date field, but I'd also like to potentially add authors, which is a relation. I'm sure this complicates things. For now I'd settle for extra fields or being able to create my own card partials or components.

**Comment by cmaxw** [comment]
> Maybe we can use this API to change more than just the grid view.
> 
> ```ruby
> self.components = {
>   "Avo::Index::GridItemComponent": "Avo::Index::CustomGridItemComponent",
>   "Avo::RowComponent": "Avo::CustomRowComponent",
>   "Avo::Views::ResourceIndexComponent": "Avo::Views::CUSTOMResourceIndexComponent"
> }
> ```
> 
> You get the point...

I like this. I think I'd prefer the keys on this to be something more like this:

```ruby
self.components = {
  grid_item: "Avo::Index::CustomGridItemComponent",
  row: "Avo::CustomRowComponent",
  resource_index: "Avo::Views::CUSTOMResourceIndexComponent"
}
```

This is easier to remember the keys on.

**Comment by Paul-Bob** [comment]
> I like this. I think I'd prefer the keys on this to be something more like this:

I was thinking about the same, it feels more "natural", even if is not as flexible as using the whole name as a key.

**Comment by adrianthedev** [comment]
Let's change [this](https://docs.avohq.io/3.0/resources.html#self.components) feature.

1. continue to support the key way of doing it (`resource_index_component`) and add the new ways of fully qualified names.
2. let's extend it to more components with just the fully qualified name.

- [ ] grid view
- [ ] resource index component
- [ ] resource table
- [ ] ResourceMapComponent
- [ ] Avo::RowComponent

Just to be clear, we'll only support fully qualified names in the future (let's change the docs as well).
