### ISSUE TITLE
Rendering associations on show page causes `NoMethodError: undefined method 'use_resource' for an instance of Avo::Fields::TagsField`

### ISSUE THREAD

**Issue by marcoroth** [avo-hq/avo#3158]
### Steps to Reproduce
1. Uncomment L24-L26 in the [`talk.rb` resource](https://github.com/adrienpoly/rubyvideo/blob/f62f6d4d7693e64ad1aa0e46dbacc4451c878add/app/avo/resources/talk.rb#L24-L26)
2. Go to `/admin/resources/talks`
4. Click on any of the talks
5. Scroll down to the "Speakers" section
6. See error that will be caused once the request for the associated table finishes (`/admin/resources/talks/keynote-thriving-in-uncertainty/speakers?view=show&turbo_frame=has_many_field_show_speakers`)

### Expected behavior & Actual behavior

I'm not sure why the association view for speakers on the show page crashes if you add the field `:speakers` for the `:index` page:

This is for the `:index` page:
```ruby
    field :speakers, as: :tags, hide_on: [:show, :forms] do
      record.speakers.map(&:name)
    end
```

And for the `:show` we have:
```ruby
field :speakers, as: :has_many, through: :speaker_talks
```

I would expect that the association view for the talks show page renders without errors, even when both of the `fields` are present.

### Models and resource files

The repo/project is open source and available at: https://github.com/adrienpoly/rubyvideo

Running the project on the `main` branch causes this exception.

* [`talk` resource](https://github.com/adrienpoly/rubyvideo/blob/f62f6d4d7693e64ad1aa0e46dbacc4451c878add/app/avo/resources/talk.rb) 
* [`talk` model](https://github.com/adrienpoly/rubyvideo/blob/f62f6d4d7693e64ad1aa0e46dbacc4451c878add/app/models/talk.rb)
* [`speaker` resource](https://github.com/adrienpoly/rubyvideo/blob/f62f6d4d7693e64ad1aa0e46dbacc4451c878add/app/avo/resources/speaker.rb) 
* [`speaker` model](https://github.com/adrienpoly/rubyvideo/blob/f62f6d4d7693e64ad1aa0e46dbacc4451c878add/app/models/speaker.rb)

My bad, if we use any of the options/config wrong, but this seems like it should it work 🙈 

### System configuration
**Avo version**:  3.11.7

**Rails version**: 7.2.0

**Ruby version**: 3.3.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

![CleanShot 2024-08-20 at 19 07 43](https://github.com/user-attachments/assets/6f427728-4142-4422-90ba-2c75b0971ca6)

### Additional context

I tried to "fix" it by making sure it's not calling the method on an object that might not have the `use_resource` method defined. While it made this error go away, it was failing down the stack because of similar reasons, but if it helps, here is the commit:

https://github.com/marcoroth/avo/commit/4ce93537096fe7d85f95fbfa460227d2e1f0be3f

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
It looks like you're encountering a field overlap issue. This occurs when multiple fields are defined with the same ID. When rendering the `has_many` field, Avo attempts to fetch the `speakers` field but instead retrieves the first field with that ID, which in this case is `tags`. As a result, the `has_many` logic is incorrectly applied to the `tags` field.

To avoid this issue, you can use the [`for_attribute`](https://docs.avohq.io/3.0/field-options.html#for_attribute) option and assign a different ID to one of the fields.

If you want to keep the same display name, you can specify `name: "Speakers"` in the field with the different ID.

I'm closing this one as completed, feel free to comment if there are any questions or reopen it if the issue persists.

**Comment by marcoroth** [comment]
It also occurs if you just have this one field, but not the `has_many`
```ruby
   field :speakers, as: :tags, hide_on: [:show, :forms] do
      record.speakers.map(&:name)
    end
```

But maybe I have to look into the `for_attribute` feature, though it might be good to say that something is "wrong" with the resource.

**Comment by Paul-Bob** [comment]
> It also occurs if you just have this one field, but not the `has_many`

That's strange, can you share the error when only `field :speakers, as: :tags`.... is present?

**Comment by marcoroth** [comment]
No sorry, my bad. It was the other way around. But using `for_attribute` and a `name` makes it work! Thank you! 🙌🏼

**Comment by Paul-Bob** [comment]
https://github.com/marcoroth/avo/commit/4ce93537096fe7d85f95fbfa460227d2e1f0be3f

This may appear to fix the issue but IMO it's just "hiding" the error. At that point, the field should respond to `use_resource` if it doesn't something is wrong.

> though it might be good to say that something is "wrong" with the resource.

This could be a developer experience improvement, and we're merging more and more of those. However, in this specific case, it can be challenging to programmatically detect such overlaps.

There are scenarios where using the same ID for two fields is intentional. For instance, you might define `field :status, as: :select` in edit views and `field :status, as: :badge` in display views.

> No sorry, my bad. It was the other way around. But using `for_attribute` and a `name` makes it work! Thank you! 🙌🏼 

All good. Cool, anytime!

**Comment by marcoroth** [comment]
Thank you @Paul-Bob! 🙏🏼
