### ISSUE TITLE
Ability to position the scopes

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#3174]
### Feature
Similar to our demo app, I have multiple scopes view and I like to position them differently. By default `All` the system provided is positioned at first but I wan to move it last.

### Current workarounds
No workarounds

### Screenshots or screen recordings
![Screenshot 2024-08-22 at 2 39 39 PM](https://github.com/user-attachments/assets/2e22b37a-b93d-40a7-8340-2c948083ee17)

### Additional context
Something like:
```ruby
  def scopes
    scope Avo::Scopes::Admins
    scope Avo::Scopes::NonAdmins
    scope Avo::Scopes::Active
    scope Avo::Scopes::All ( the default one provided system)
  end
```

**Comment by Paul-Bob** [comment]
The default "All" scope is not a real scope backed by a file, just a link that clears the applied scope.

Your use case is achievable by a custom implementation of an "All" scope:

#### 1
`bin/rails generate avo:scope all`

#### 2
Insert it wherever you want 
```ruby
  def scopes
    remove_scope_all
    scope Avo::Scopes::OddId
    scope Avo::Scopes::EvenId
    scope Avo::Scopes::Admins
    scope Avo::Scopes::All, default: true
    scope Avo::Scopes::NonAdmins
    scope Avo::Scopes::Active
  end
```
#### 3
Visit page
![image](https://github.com/user-attachments/assets/99e97859-2324-4f4d-830b-67c431688a60)

I'm closing this one as solved, feel free to comment/reopen it if something goes wrong.

**Comment by SahSantoshh** [comment]
Yeah, another way to achieve it. Thanks
