### ISSUE TITLE
Dynamic filter on an attribute of belongs_to

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3181]
### Feature
Filter on a attribute of a relation.

```ruby
class Order
  belongs_to :customer  
end

class Customer
   # firstname
   # gender
   # ...
end
```

Within the orders resource, I want to filter out all orders with customer firstname starts with "foo"

https://www.loom.com/share/9a55ade0e01147a294453fa89ef7e224

### Current workarounds
See loom, make separate dynamic_filters for each

**Comment by Paul-Bob** [comment]
@pjmuller correct me if I'm wrong but after implementing the filter list (check this issue https://github.com/avo-hq/avo/issues/3206) the problem described here should be solved since you could re-organize all the belongs to filters on a sub-list

**Comment by pjmuller** [comment]
Yes you are right, this other is a more preferred option, closing this one
