### ISSUE TITLE
Installing tailwind missed adding a newline to my Procfile.dev

### ISSUE THREAD

**Issue by cmaxw** [avo-hq/avo#3187]
### Describe the bug
I ran `bin/rails generate avo:tailwindcss:install` on the command line. When I tried to run `bin/dev` on my app, I got errors on the previous line in the Procfile because it appended `avo_css: yarn avo:tailwindcss --watch` to the last line instead of adding it on its own line.

### Steps to Reproduce
1. Run `bin/rails generate avo:tailwindcss:install`
2. Run `bin/dev`
3. Watch it fail if you had anything else in the Procfile.

### Expected behavior & Actual behavior
It should launch the app.

### System configuration
**Avo version**:
3.11.3

**Rails version**:
7.2.0

**Ruby version**:
3.3.3
**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Got it!
We should probably add a `\n` or something similar to the generator.
Thanks for reporting it!

**Comment by cmaxw** [comment]
I could probably do a PR...

I did another one for a tailwind issue I ran into.

**Comment by Paul-Bob** [comment]
Thank you @cmaxw! Closing as fixed by https://github.com/avo-hq/avo/pull/3189
