### ISSUE TITLE
[LOW prio] ACTIONS: access arguments in fields & message

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3194]
❗️ [EDIT 2024-08-29] I'm using a workaround by persisting more state into the database rather than using arguments.
So we don't need this anytime soon. I do keep it open as the behavior still seems inconsistent

### Feature
Currently the arguments are only accessible in `name` and `handle`. See example

```ruby
class Avo::Resources::Person < Avo::BaseResource
  def actions
     action Avo::Actions::SayHello, arguments: {foo: "bar"}
  end
end

class Avo::Actions::SayHello
  def self.name = -> {
      arguments[:foo] # ✅ works
   }

  def self.message = -> {
     arguments[:foo] # ❌ not available (can live without it)
     # request.referer ✅ works
   }
  
  def fields
     arguments[:foo] # ❌ not available (would really make a difference for me)
     # request.referer ❌ not available
  end

  def handle(query:, fields:, current_user:, resource:, **args)
     arguments[:foo] # ✅ works
  end
end
```

This feels very inconsistent behaviour

### Current workarounds
Within message we can use `URI.parse(request.referer).query` to try to derive some arguments FROM the parameters.
However this is not available in the TOP level `fields` (as it's not a proc), only in sub procs like `field :xxx, disabled: -> {}` but that doesn't help me.

But if you can make `request.referer` available then I can also make it work :)

### Additional context
Quite high prio as I want to differentiate the fields based outside settings

**Comment by pjmuller** [comment]
Or do I need to a pre step like you have in your demo project `app/avo/actions/pre_update.rb`? where via the navigate_to_action flow arguments are remembered i.s.o. definining them in the resource@actions, feels quite cumbersome...

Got me quite confused as in main demo -> app/avo/actions/update.rb you are using `arguments` within the `fields` method...

**Comment by Paul-Bob** [comment]
Hey @pjmuller could you please verify if this issue persists on last version? 

Just tried to reproduce it and `arguments` are accessible on `def fields`

Closing this as fixed, don't hesitate to reopen it if the issue persists.
