### ISSUE TITLE
Viewing a resource results in `TypeError: no _dump_data is defined for class Proc`

### ISSUE THREAD

**Issue by koppen** [avo-hq/avo#3196]
Viewing a resource with an associated resource results in a redirect to a URL that raises `TypeError: no _dump_data is defined for class Proc`. 

This looks mighty similar to https://github.com/avo-hq/avo/issues/3151, but #3151 is about applying a filter, this issue is for simply viewing a resource. I'll gladly move this discussion there if it's deemed more relevant.

### Steps to Reproduce

1. Given the below models and resources...
2. Go to Customers index (/avo/resources/customers)
3. Click on Show customer for a Customer that has one or more Assets
4. This takes us to the customer page (ie /avo/resources/customers/42)
5. Wait a bit before being redirected to a page saying:

> TypeError in Avo::Associations#index
> no _dump_data is defined for class Proc
> 
> activesupport (7.2.1) lib/active_support/messages/codec.rb:36:in `dump'
> activesupport (7.2.1) lib/active_support/messages/codec.rb:36:in `serialize'
> activesupport (7.2.1) lib/active_support/messages/metadata.rb:138:in `serialize_to_json_safe_string'
> activesupport (7.2.1) lib/active_support/messages/metadata.rb:34:in `serialize_with_metadata'
> activesupport (7.2.1) lib/active_support/message_encryptor.rb:257:in `create_message'
> activesupport (7.2.1) lib/active_support/message_encryptor.rb:221:in `encrypt_and_sign'
> avo (3.11.10) lib/avo/services/encryption_service.rb:21:in `encrypt'

The URL for that page is /avo/resources/customers/42/assets?view=show&turbo_frame=has_many_field_show_assets

### Models and resource files

```ruby
class Customer < ApplicationRecord
  has_many :assets, :dependent => :destroy
  normalizes :number, :with => ->(number) { number.strip }
end
```

```ruby
class Asset < ApplicationRecord
end
```

```ruby
class Avo::Resources::Customer < Avo::BaseResource
  def fields
    field :assets, :as => :has_many
  end
end
```

```ruby
class Avo::Resources::Asset < Avo::BaseResource
end
```

### System configuration
**Avo version**: Avo 3.11.10

**Rails version**:    7.2.1

**Ruby version**:     3.3.1

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] Yes, we are using view components. Will happily post relevant ones if requested.
 - [ ] No

### Additional context

The issue only appears for Customers that actually have Assets. Customers with no associated Assets render just fine.

As in #3151 the presence of `normalizes` in the model is significant. Removing that makes the problem go away. However, that is hardly optimal nor expected behaviour.

This isn't a problem in Avo 2. We've only encountered it when trying to upgrade to Avo 3.

#### Impact

 - [ ] High impact (It makes my app un-usable.) - Well, it makes us unable to upgrade to Avo 3 without changing our model code.
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by koppen** [comment]
Looking closer at the documentation for [`normalizes`](https://api.rubyonrails.org/classes/ActiveRecord/Normalization/ClassMethods.html#method-i-normalizes):

> Be aware that if your app was created before Rails 7.1, and your app marshals instances of the targeted model (for example, when caching), then you should set `ActiveRecord.marshalling_format_version` to `7.1` or higher via either `config.load_defaults 7.1` or `config.active_record.marshalling_format_version = 7.1`. Otherwise, `Marshal` may attempt to serialize the normalization `Proc` and raise `TypeError`.

This seems relevant. Our application is created before Rails 7.1 (we have `config.load_defaults 7.0`). It would appear that Avo 3 has started marshalling instances of the model, which causes `Marshal` to serialize the normalization `Proc` and raise `TypeError`.

Adding

    config.active_record.marshalling_format_version = 7.1

to `config/application.rb` makes the problem go away while being able to preserve `normalizes` in our models. This seems like a good solution for now, and definitely reduces the impact for us.

**Comment by Paul-Bob** [comment]
Thanks for sharing your solution @koppen
 
Let's catch this error and disable the select all feature when the error occurs.

In development, let's show an error message with a link to a documentation page where `config.active_record.marshalling_format_version` is mentioned.
