### ISSUE TITLE
unknown keyword: :rel

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#3199]
### Describe the bug

Upgrading to Rails Rails 7.2.1 and Avo 3.11.10, I got the following error, when it works well with Avo 3.11.7 and Rails version 7.2.0.rc1

```
web      | ActionView::Template::Error (unknown keyword: :rel):
web      |
web      | Causes:
web      | ArgumentError (unknown keyword: :rel)
web      |     32:         <%= render partial: "avo/partials/navbar" %>
web      |     33:         <div data-sidebar-target="mainArea" class="content-area flex-1 flex pt-16 relative <%= "sidebar-open" if @sidebar_open %>">
web      |     34:           <div class="hidden lg:flex">
web      |     35:             <%= render Avo::SidebarComponent.new sidebar_open: @sidebar_open %>
web      |     36:           </div>
web      |     37:           <div class="flex lg:hidden">
web      |     38:             <%= render Avo::SidebarComponent.new sidebar_open: false, for_mobile: true %>
web      |
web      | config/initializers/avo.rb:112:in `block (3 levels) in <main>'
```

avo.rb

```ruby
    section 'Statistics', icon: 'chart-pie' do
      link_to 'Foo', path: 'https://bar.com', target: :_blank, rel: 'noopener'
    end
```

### System configuration
**Avo version**:
3.11.10

**Rails version**:
7.2.1

**Ruby version**:
3.3.4

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
We'll have a look next week, until there you can remove the `rel` option to avoid breaking the app
