### ISSUE TITLE
UI issue with card grid view only on tabs

### ISSUE THREAD

**Issue by m7madmagdy** [avo-hq/avo#3214]
### Context

If you have a gride view with full controls plus reorder controls the delete button will be outside the card view 
this issue happens only on tabs not in the main resource index view

### System configuration
**Avo version**: 3.12.0

**Rails version**: 7.2

**Ruby version**: 3.3.4

**License type**

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![IMG-20240903-WA0002](https://github.com/user-attachments/assets/6de11d58-5409-4616-9e00-87b15aeae1bd)

**Comment by Aaryanpal** [comment]
@Paul-Bob can i assign this to me?

**Comment by Paul-Bob** [comment]
Sure @Aaryanpal thanks for the initiative!

For the approach I guess wrapping the controls on a flex box and making them to verticaly expand should do the trick

**Comment by Aaryanpal** [comment]
@Paul-Bob can you guide me how can navigate to this particular window?

**Comment by Paul-Bob** [comment]
The screen shot was taken from @m7madmagdy's project.

To reproduce a similar behavior go to http://localhost:3030/admin/resources/posts 

To simulate more controls on the card go to `app/components/avo/index/resource_controls_component.html.erb` and triplicate the `<%= render_control control %>` line. 

Don't forget to remove the triplicated controls after fixing the styling.
