### ISSUE TITLE
Change name of resource via attribute instead of i18n

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3221]
### Feature
Currently the only way to change the name of a resource is to use i18n
![Screenshot 2024-09-05 at 14 23 00](https://github.com/user-attachments/assets/58d9bf62-71ac-4fa8-b9e0-dd47ffb7dc32)

However we want to dynamically change it (based on a tenant) which makes it much harder to do via a static i18n.

could we introduce a `name` or `label` attribute on the Resource level?

```ruby
class Avo::Resources::Person < Avo::BaseResource
  self.name = "BlaBla"
  self.name = -> { resource } # make all standard
end
```

Perhaps we could implement this ourselves? if so, please guide us which files to alter so that we can create a pull request

### Current workarounds
i18n, but not sure how I would need to do this dynamically

**Comment by Paul-Bob** [comment]
Overriding the `plural_name` method on the resource file should allow you to define a custom name:

```ruby
class Avo::Resources::User < Avo::BaseResource
  self.title = -> {
    record.name
  }

  # ...
  
  def plural_name
    "The custom plural name"
  end

  # ...
end
```

![image](https://github.com/user-attachments/assets/dc926b21-7586-4e73-b02e-cfffbe059afc)

Could you give it a try and let us know how it goes?

**Comment by pjmuller** [comment]
@Paul-Bob works like a charm, you and the whole avo community just scored some more brownie points 🍪 💪
