### ISSUE TITLE
self.includes: not optimal

### ISSUE THREAD

**Issue by RocKhalil** [avo-hq/avo#3224]
### Describe the bug
When using the includes option, it will always include the values even if they are not rendered, which will trigger bullet's N+1 error.

![image](https://github.com/user-attachments/assets/168da473-2a43-499d-8e21-dbf29eadad9a)
![image](https://github.com/user-attachments/assets/f3018798-44ce-4ada-9119-6f6462e39298)
![image](https://github.com/user-attachments/assets/7653a45d-0cc8-4249-94b7-eda58682e5d1)

`price_list` won't render when using the `has_many` fields but will render on the listing ( / index ) page;
```ruby
AVOID eager loading detected
  BuildingUnitPrice => [:price_list]
  Remove from your query: .includes([:price_list])
```

**Comment by Paul-Bob** [comment]
Hey @RocKhalil whatever is inside `self.includes = [ ... ]` will always be included on the `query` on the `index` view.

And whatever is inside `self.single_includes` will be included in the `query` on the `show` and `edit` pages.

Avo doesn't check if it will be rendered or not, if you define it Avo will include it in the `query`.

Could you please provide more details and explain the expected behavior versus what is currently happening?

Right now the correct behavior for your setup is whenever you visit the `BuildingUnitPrice` index then `:building`, `:building_unit`, and `:price_list` are included. The includes should not be applied on any other page. Isn't this the current behavior?

**Comment by RocKhalil** [comment]
correct, this is the right behavior when you open the `BuildingUnitPrice` index page. However, on `BuildingUnit`, we have `building_unit_prices, as: :has_many` which will render the list without the `building_unit` for example ( default avo behavior ). Since it's included, it will show the `eager load` error

**Comment by Paul-Bob** [comment]
So in your case `building_unit_prices, as: :has_many` is not using the `building_unit` and it is unnecessarily included, right?

I understand that this is not ideal for your use case. But what if you would use the `building_unit` on a computed field? 

```ruby
field :price_with_discount, as: :text do
  record.minimum_price - record.building_unit.discount
end
```

In this case would make sense to keep the `building_unit` included right?

As you can see there are use cases where the include make sense and others where don't and IMO is not Avo's responsibility to check against all of them. To keep things simple Avo includes whatever is defined in the `self.includes` without any additional "magic".

As a solution for your use case you could remove the `building_unit` from the includes and do that include only on the `index_query`:

```ruby
self.includes = [:building, :price_list]

# Only for inxed
self.index_query = -> {
  query.includes(:building_unit)
}
```

Closing this one as solved, let me know if the solution works or if you need further assistance.

**Comment by RocKhalil** [comment]
I totally get that... the only problem is that, when you have a `has_many` field, Avo directly removes the current resource from rendering ( which makes sense ) - however, since in the `index_query` or in the `includes` you have that model predefined ( for the index page listing ), it will trigger an eager load issue.

I'm not sure if I'm being clear or no on this..

**Comment by Paul-Bob** [comment]
> I'm not sure if I'm being clear or no on this..

You are, this approach still trigger the eager load issue?

```ruby
self.includes = [:building, :price_list]

# Only for inxed
self.index_query = -> {
  query.includes(:building_unit)
}
```

**Comment by RocKhalil** [comment]
yes it does, just tried it:

```ruby
AVOID eager loading detected
  BuildingUnitPrice => [:building_unit]
  Remove from your query: .includes([:building_unit])
```

Basically, it's not a big issue but just wanted to point it out :-p

**Comment by Paul-Bob** [comment]
The original warning was:

```ruby
AVOID eager loading detected
  BuildingUnitPrice => [:price_list]
  Remove from your query: .includes([:price_list])
```

Now it's:

```ruby
AVOID eager loading detected
  BuildingUnitPrice => [:building_unit]
  Remove from your query: .includes([:building_unit])
```

Not sure if I'm still following, if you consider it an Avo issue a reproduction repository with clear steps would be helpfull.

> Basically, it's not a big issue but just wanted to point it out :-p

Got it, It should be solvable by using:

- [`self.includes` ](https://docs.avohq.io/3.0/resources.html#self.includes)for includes that are necessary on tables even if on associations
- [`self.index_query`](https://docs.avohq.io/3.0/resources.html#self.index_query) for includes only on index without associations
- [`self.single_includes`](https://docs.avohq.io/3.0/resources.html#self.single_includes) for single views like show and edit
- [`scope`](https://docs.avohq.io/3.0/associations/has_many.html#scope) to add custom includes for associations

This way you ensure that only required includes are made for each context
