### ISSUE TITLE
[BUG] Array enums not displaying properly 

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#323]
### Describe the bug
When using array enums Avo won't display them properly

### Steps to Reproduce
1. Add an Array enum `enum status: [:draft, :published, :archived]`
2. Add a select field feeding off of that enum `field :status, as: :select, enum: ::Product.statuses`
3. Update a record on that field.
4. Check that the field to see the empty dash

### Expected behavior
See the enum

### Actual behavior
See the empty dash

### System configuration
**Avo version**: 1.1.0

### Screenshots
![image](https://user-images.githubusercontent.com/1334409/113599065-bf856680-9646-11eb-8266-cbe7d1218b78.png)
![image](https://user-images.githubusercontent.com/1334409/113610828-51e13680-9656-11eb-913c-3c09c411fe6f.png)

**Comment by marcelobarreto** [comment]
Hi @adrianthedev, is this something you already started to work? Do you mind if I took this one to start contribute on this project :smile:

**Comment by adrianthedev** [comment]
Hi Marcelo.
No, we haven't started work on this. You can pick this up if you want to.
Let me know if you need help navigating the codebase.

Thank you!

**Comment by marcelobarreto** [comment]
@adrianthedev after some tries and some research, what I could retrieve is:

To reproduce what you said, we need the status column to be a string but it should be an integer following [Rails docs](https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html)

But even if I use an integer, I see the following:

![image](https://user-images.githubusercontent.com/1276556/114212859-adeada00-9938-11eb-978e-e27a1f7f4be0.png)

Can you confirm that you tried using a string?

**Comment by adrianthedev** [comment]
No, I haven't tested any scenario with array enums.
Right now I have done the following:

 - created a migration for posts `r g migration add_status_to_posts status:integer`
 - added enum on the `Post` model `enum status: [:draft, :published, :archived]`
 - added status field to the `PostResource` `field :status, as: :select, hide_on: [:index], enum: ::Post.statuses`

I do see the same thing as you do. I manually updated the field in the DB with `0`.

![image](https://user-images.githubusercontent.com/1334409/114218630-55383300-9972-11eb-9c01-552c91dafba0.png)

**Comment by marcelobarreto** [comment]
Thanks, I have work to do, but it's different that what I was expecting. Still counting on me for this one :+1:

**Comment by adrianthedev** [comment]
Yeah. No worries. 
You can create a draft PR on which to collaborate further. 

Thank you for your contributiin 👍

**Comment by marcelobarreto** [comment]
@adrianthedev #339 :+1:

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/avo/pull/339
