### ISSUE TITLE
Use `.well-known` path for assets to avoid conflicts

### ISSUE THREAD

**Issue by reesericci** [avo-hq/avo#3234]
### Context
I was reading [this blog post about assets](https://avohq.io/blog/how-to-bundle-assets-in-a-rails-engine) and noticed that y'all were using `/avo-assets`. While it is _extremely_ unlikely to conflict with anything, it is a possibility.

### Proposition

To solve this, I think it would make sense to use a `.well-known` path, as defined in [RFC 86150](https://www.rfc-editor.org/rfc/rfc8615.html) which are designed for exactly this purpose: to define a pathname for well-known resources that won't conflict with the webmaster's path namespace. Additionally, these can be [registered with IANA](https://www.iana.org/assignments/well-known-uris) to further prevent conflicts.

**Comment by adrianthedev** [comment]
Sounds great! Are you open to send in a PR?

**Comment by reesericci** [comment]
Potentially, I just don't know the full extent of the usage of `/avo-assets` and I'm not super familiar with the codebase
