### ISSUE TITLE
Add support for setting dynamic suffix on MetricCard (e.g., currency)

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#3235]
### Feature
I would like the ability to dynamically set the suffix on a MetricCard based on the resource or record being displayed. For instance, when displaying a monetary amount, the suffix should reflect the currency of the related record.

Use case:
In my current use case, we display the total amount of a Deal, and I need to append the correct currency symbol (e.g., $, €, etc.) to the value shown on the MetricCard. However, it seems there is currently no way to access the resource or record within the MetricCard to set the suffix dynamically.

Here's a proposed solution:
```ruby
class Avo::Cards::Revenue < Avo::Cards::MetricCard
  self.suffix = = lambda { resource.record.currency }
```

**Comment by adrianthedev** [comment]
PRs that added this functionality:
- https://github.com/avo-hq/avo/pulls?q=sort%3Aupdated-desc+is%3Apr+callable+is%3Aclosed
- https://github.com/avo-hq/avo/pull/1757
- https://github.com/avo-hq/avo/pull/1508
