### ISSUE TITLE
Allow proc on filter `self.name` and `self.button_label`

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3244]
### Feature

Allow callable `name` and `button_label` on filters to ensure that localization is applied on each request.

```ruby
class Avo::Filters::Club < Avo::Filters::TextFilter
  self.name = -> { I18n.t("avo.filter_translations.club.name") }
  self.button_label = -> { I18n.t("avo.filter_translations.club.button_label") }

  def apply(request, query, value)
    query.joins(:club).where("clubs.name ILIKE ?", "%#{value}%")
  end
end
```

**Comment by adrianthedev** [comment]
PRs that added this functionality:
- https://github.com/avo-hq/avo/pulls?q=sort%3Aupdated-desc+is%3Apr+callable+is%3Aclosed
- https://github.com/avo-hq/avo/pull/1757
- https://github.com/avo-hq/avo/pull/1508
