### ISSUE TITLE
Remove `OpenStruct` from the codebase

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#3245]
### Context

`OpenStruct` seems to be "deprecated" and not that performant.
Let's try to replace it with `Data` (carefull. it's not mutable).

**Comment by Yash-Singh-Pathania** [comment]
hi @adrianthedev  would you be okay assigning this to me .

**Comment by adrianthedev** [comment]
Done!  Thanks @Yash-Singh-Pathania!

**Comment by adrianthedev** [comment]
Maybe this is a good alternative?
https://api.rubyonrails.org/classes/ActiveSupport/OrderedOptions.html

**Comment by Yash-Singh-Pathania** [comment]
@adrianthedev Makes sense. I'll try to implement it and have the pull request ready by today or the day after. Thanks for the help!

**Comment by Yash-Singh-Pathania** [comment]
@adrianthedev : https://github.com/avo-hq/avo/actions/runs/11178246617/job/31075442563?pr=3307
could you please help me with the test cases ?
