### ISSUE TITLE
Using belongs_to in attach_fields causes error

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3248]
### Describe the bug
When using a `belongs_to` field inside `attach_fields`
<img width="1023" alt="Screenshot 2024-09-15 at 10 20 23" src="https://github.com/user-attachments/assets/84fae9b0-7595-44c5-91a2-6b896836b6c6">

I'm assuming it's because the join table record does not exist at that point?  That's my guess anyway!

`attach_fields`:

```
                    attach_fields: -> {
                        field :role, as: :text
                        field :companyable_type, as: :hidden,
                            default: "Attraction" # Hardcode type to ensure the polymorphic has_many :through works.
                        field :model, as: :belongs_to, use_resource: Avo::Resources::Model
                    }
```

Companyable:
```
  class Companyable < ApplicationRecord
    belongs_to :company
    belongs_to :companyable, polymorphic: true
    belongs_to :model, optional: true
```

Model:
```
class Model < ApplicationRecord
  has_many :companyables
  has_many :submodels
end
```

**Comment by rctneil** [comment]
Do you have a comment on this?   I really would love to be able to use a belongs_to field here in order to be able to select a record via a dropdown.

**Comment by Paul-Bob** [comment]
Hey @rctneil we would merge a PR that adds `belongs_to` support for `attach_fields`. I'll also have a look

**Comment by adrianthedev** [comment]
Which resource has that `attach_fields` option? Can you please add the whole configuration?
