### ISSUE TITLE
Action resource breaks when switching between resources

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3249]
### Describe the bug
see screen recording: https://www.loom.com/share/18b5bdd56bd34ba182bac32e38484759

### Steps to Reproduce
My resource files look like
```ruby
    def actions
      action Avo::Actions::ExcelImport
   end

   self.index_controls = -> do
      action Avo::Actions::BulkEdit, icon: "heroicons/outline/paint-brush", style: :outline, title: "Bulk Edit", label: ""
      actions_list style: :primary, color: :primary, icon: "heroicons/outline/bars-arrow-down", label: "", title: "lists"
   end
end
```

### Expected behavior & Actual behavior
actions are able to load everywhere

### System configuration
**Avo version**: 3.12.0

**Rails version**:  7.2.1

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by pjmuller** [comment]
@Paul-Bob ok, I'll try to nail it down what is causing it in our setup.
Challenge accepted :)

**Comment by Paul-Bob** [comment]
Does it happen with all the actions or only with some specific ones?

**Comment by pjmuller** [comment]
@Paul-Bob after removing all my actions and only using https://github.com/avo-hq/avo/pull/3218 I don't have this issue anymore 💪 .

So if other users ever encounter this, it's most likely a combination of the `def actions` and `action lists` within the `self.index_controls = -> do` that caused it (we weren't monkey patching anything there, so it's likely that other people will have this as well)
