### ISSUE TITLE
default sort_direction ASC when clicking column

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3260]
### Feature
Whenever you click a sortable column the sort_direction=desc
see https://www.loom.com/share/dbcd797b87b943b0811da5d335bae59c

could we change this to asc?

### Current workarounds
Hack the sorting to actually do ASC whenever the params say DESC, but that's asking for trouble...

```ruby
sortable: -> {
            sort_direction = params[:sort_direction] == "asc" ? "desc" : "asc"
            query.order(Arel.sql("#{col_name} #{sort_direction} NULLS LAST"))
          } ,
```

**Comment by adrianthedev** [comment]
I wanted to make a video about how to do this PR, but I ended up actually doing the work.
