### ISSUE TITLE
Rhino WYSIWYG improvements

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3261]
### Feature
- is it possible to localize/modify the tooltips of the bold/italic/... buttons
- the color button don't have tooltips
- only accept images
   - this is possbible https://rhino-editor.vercel.app/how-tos/specifying-accepted-file-types/ but how do I pass the option?
- underline: could we add this button? (trix had it...)

**Comment by adrianthedev** [comment]
> * is it possible to localize/modify the tooltips of the bold/italic/... buttons

I guess we need a mechanism to pass some i18n strings from Rails to JS and then pass them to rhino. Not sure how easy it is to implement them into rhino/TipTap

> * the color button don't have tooltips

We can add them. Same applies for i18n

> * only accept images
>   
>   * this is possbible [rhino-editor.vercel.app/how-tos/specifying-accepted-file-types](https://rhino-editor.vercel.app/how-tos/specifying-accepted-file-types/) but how do I pass the option?

We need to add support for that

> * underline: could we add this button? (trix had it...)

THis can be added to the Avo field or to rhino itself.

---

This is the kind of issue that steers me to making this an extra paid add-on to Avo.
it will take so much of our time to add things everytime.

The alternative is to spend that time to build a comprehensive plugin system, but I'm not sure that's the right option either as Avo is using Rhino, which uses TipTap, which uses ProseMirror. So many abstraction layers and another thing to architect and maintain in the future.

---

My main question is, would you be open to contribute those features to the rhino field? 😬
The follow-up is, if not, would you be open to support adding them?
