### ISSUE TITLE
create_association in resource policy does not work with belongs_to associations, only on has_many

### ISSUE THREAD

**Issue by NowakJR** [avo-hq/avo#3266]
### Context

```
def create_association?
   false
end
```

does not hide "create new association" button if relation is belongs_to, seems to work fine with has_many
The workaround is adding can_create: false to belongs_to field, then the button wont be visible, but it would be nice to have it all in one place

### System configuration
**Avo version**: 3.7.4

**Rails version**: 7.0.8.4

**Ruby version**: 3.2.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by Paul-Bob** [comment]
@NowakJR any updates on this one?
