### ISSUE TITLE
Template file and inline render method found for Avo::TurboFrameWrapperComponent.

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3291]
With `gem "view_component", ">= 3.15.0"` some users started to notice this error: 

![image](https://github.com/user-attachments/assets/880161ab-9333-427f-a601-de7bc5ce1a24)

I could reproduce it on [avodemo](https://github.com/avo-hq/main.avodemo.com) development. The same code is running in [production](https://main.avodemo.com/avo/dashboards/dashy) just fine without any errors.

On development it only happens on some servers, for example, if I stop and start the server the error can disappear entirely, but if I stop and start the server again it could reappear on each refresh.

**Comment by Paul-Bob** [comment]
@jetienne were you using 🐧Linux while experiencing this issue?

**Comment by jetienne** [comment]
MacOS for me

**Comment by rickychilcott** [comment]
I’ve seen this unrelated to Avo in my app — I’m also on Mac.

**Comment by Paul-Bob** [comment]
> I’ve seen this unrelated to Avo in my app — I’m also on Mac.

I guess it is more of a `view_component` issue then?

**Comment by adrianthedev** [comment]
Maybe stay on VC 3.14 until this is getting fixed?

**Comment by jetienne** [comment]
@adrianthedev 

-    view_component (3.15.0)
+    view_component (3.15.1)

IMHO, 3.15.0 was fine

**Comment by rickychilcott** [comment]
3.15.0 had a bug with NewRelic. 3.15.1 is a very minor change to support that.

**Comment by Paul-Bob** [comment]
Fixed by https://github.com/ViewComponent/view_component/pull/2121

Should be fixed on `view_component (3.17.0)`

**Comment by jetienne** [comment]
It does for me. Already in production
