### ISSUE TITLE
Dynamic filter > tags closes too soon

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3296]
### Describe the bug
First of all thanks for https://github.com/avo-hq/avo-dynamic_filters/pull/69 however in combination with  https://github.com/avo-hq/avo/pull/3283 we have a regression.

See loom: https://www.loom.com/share/4bd5e9457c8d45e3b1417c1ca3d54b01

### System configuration
**Avo version**: 3.13.1

**Rails version**: 7.2.1

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Thanks for reporting this, we'll add the tags element to the exception list!
