### ISSUE TITLE
global search resource ordering / priority to currently open resource

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3301]
### Feature
In global search we want to give the current resource you are looking at "priority" over the others

see https://www.loom.com/share/00800b5971954d58b821672d292d6b6d

The order of the global search resources seems alphabetical, can we overwrite this for all the resources that returned search results?

To clarify, resources without search results should always be at the bottom.

### Current workarounds
None

**Comment by adrianthedev** [comment]
What if that current resource returns less records or zero?
