### ISSUE TITLE
WARNING: The Class.identifier is undocumented and was meant for internal framework usage only. As it is no longer used by the framework it will be removed in a coming non-breaking ViewComponent release.

### ISSUE THREAD

**Issue by m7madmagdy** [avo-hq/avo#3316]
### Context

I got this warning in the logs: 
WARNING: The Class.identifier is undocumented and was meant for internal framework usage only. As it is no longer used by the framework it will be removed in a coming non-breaking ViewComponent release.

### System configuration
**Avo version**: 3.13.3

**Rails version**: 7.2.0

**Ruby version**: 3.3.5

**License type**

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

**Comment by Paul-Bob** [comment]
Hey @m7madmagdy, is there any information about where this warning is being raised?

**Comment by m7madmagdy** [comment]
Hi @Paul-Bob, Can you look for this issue https://github.com/ViewComponent/view_component/issues/2122

**Comment by m7madmagdy** [comment]
Also, inside the gemfile.lock I found that avo dashboards or something else use the 3.7.0 version of view component

**Comment by Paul-Bob** [comment]
> Hi @Paul-Bob, Can you look for this issue https://github.com/ViewComponent/view_component/issues/2122

Got it, at first look, I wasn't able to find any `identifier` call. Let me know if there is any information on the warning message.

> Also, inside the gemfile.lock I found that avo dashboards or something else use the 3.7.0 version of view component

There is a dependency on `"view_component", ">= 3.7.0"` and that is intentional. Some components would not work with versions lower than that.

**Comment by AhmedAliIbrahim** [comment]
This is an issue with NewRelic and they will fix it in an upcoming update

**Comment by Paul-Bob** [comment]
Thanks for sharing @AhmedAliIbrahim
