### ISSUE TITLE
Global search: receive extra parameters

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3324]
### Feature
We want the global search to "dynamically" include the current resource you are on 

However when you invoke global search you get NO context (via the params) of where the user currently is

```
[GET] /avo/avo_api/search?q=foobar&global=true
```

Please add two extra parameters
- via_resource_class on index, show & forms
- via_record_id: on show / forms

```
[GET] /avo/avo_api/search?q=foobar&global=true&via_record_id=xxx&via_resource_class=Avo::Resources::Foobar
```

These inputs can be consumed in the `self.search = {}` proc and allow other finetunings as well

### Current workarounds
in the resource controller, we could reload the page if we see there are no ?via_resource_class=... (as all of the url query params are passed to the search controller) but feels dirty

**Comment by adrianthedev** [comment]
### Approach

If the following params are present pass them to the search query

`via_resource_class`, `via_record_id`, `via_relation`, `via_association_type`

**Comment by Paul-Bob** [comment]
> ### Approach
> 
> If the following params are present pass them to the search query
> 
> `via_resource_class`, `via_record_id`, `via_relation`, `via_association_type`

To complete the approach:

When on an index page let's also send the resource class and record the ID

This will follow the scope of the feature to have access to the current resource and record when clicking on the global search

**Comment by pjmuller** [comment]
> ### Approach
> If the following params are present pass them to the search query
> 
> `via_resource_class`, `via_record_id`, `via_relation`, `via_association_type`

⚠ this is not how I see it, maybe the names I used in the original ticket are confusing. 
please check this loom: https://www.loom.com/share/146a7970c16c41d98e613b418cedf232

**Comment by pjmuller** [comment]
Hi @Paul-Bob , works like a charm, thanks a lot :)

**Comment by Paul-Bob** [comment]
Awesome!
