### ISSUE TITLE
action modal not closable

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3326]
### Feature
We have some very big action forms where we don't the user to accidentally click out of the modal and close it.

Propositions

- [convention over configuration approach] show a warning when a user clicks outside of the modal, "are you sure you want to exit the action", only on confirm close it
- add a setting on the action that

```ruby
class Avo::Actions::Dummy < Avo::BaseAction
  self.standalone = true
  self.close_only_via_button = true
end
```

### Current workarounds
None that Paul and I could think of

### Screenshots or screen recordings
https://www.loom.com/share/d9a52b1c2dd942af879ddffa025a7819

**Comment by adrianthedev** [comment]
Got it!
Makes sense in some scenarios, I agree.

### Approach

- add a `self.close_on_backdrop_click` option on actions. it defaults to `true`
- if the user sets it to `false` then the modal won't close on backdrop click
- the stimulus controller needs a new [value](https://stimulus.hotwired.dev/reference/values) that takes that configuration and takes that into account not to close the modal
