### ISSUE TITLE
Dependent Select placeholder being "null"

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3337]
### Describe the bug
Using a slight tweak to the example of dependent Selects, I find that they get a null placeholder.

### Steps to Reproduce
Repro repository: https://github.com/rctneil/avorepro

1. Edit an existing "Companyable" record
2. Choose a "Company"
3. Check the placeholder for "Model"
4. Same happens for "Model" => "Submodel"

### Expected behavior & Actual behavior
The placeholder specified on those fields should show.  I just get "null" instead.

### System configuration

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [X] Yes. If so, please post code samples. - Added head view to include custom JS
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Issue on the custom stimulus logic, closing as completed.
