### ISSUE TITLE
Dependent Select going from 2 to 1 option

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3338]
### Describe the bug
Using a slight tweak to the example of dependent Selects, I find that sometimes values do not save.

### Steps to Reproduce
Repro repository: https://github.com/rctneil/avorepro

1. Edit an existing "Companyable" record that has both a "Model" and a "Submodel"
2. Change "Submodel" to not have a value. (eg, only choose a "Model")
3. Save record

### Expected behavior & Actual behavior
Companyable should have a "Company", a "Model", and no "Submodel", I find that in reality, none of those changes get saved and they stay as they were pre-editing.

### System configuration

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [X] Yes. If so, please post code samples. - Added head view to include custom JS
 - [ ] No

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Issue on the custom stimulus logic, closing as completed.
