### ISSUE TITLE
Belongs_to dropdown not using includes when creating record titles

### ISSUE THREAD

**Issue by rctneil** [avo-hq/avo#3339]
### Describe the bug
When listing record titles to show in a belongs_to field dropdown, the values do not seem to take account of any "includes" to fix N+1 issues, if the title value of the records uses a method from the model.

### Steps to Reproduce
Repro repository: https://github.com/rctneil/avorepro

1. Edit an existing "Companyable" record
2. Choose "Attraction" as the "Companyable" type.
3. Behavior occurs on the "Companyable" field.  In this demo, the name of the "Attraction" records use a method. This method uses a delegates call.

### Expected behavior & Actual behavior
The "Venue" records should not be loaded one by one for each Attraction when loading the records to display in the select box.

### System configuration

**License type**:

 - [ ] Community
 - [ ] Pro
 - [X] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples. - Added head view to include custom JS
 - [X] No

### Additional context
NOTE: If using "searchable: true", the issue gets reduced slightly due to the JS popup search box but in reality does still exist in there too. Couldn't demo in repo due to not having Advanced license in there.

#### Impact

 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Issue on the custom stimulus logic, closing as completed.
