### ISSUE TITLE
Only reload one row in :index with append_to_response

### ISSUE THREAD

**Issue by lizdeika** [avo-hq/avo#3342]
### Context
Any way to reload just one row in index view using `append_to_response`?
Have tried this from custom action(modal form dialog like in https://main.avodemo.com/avo/resources/cities) `handle` method
```
succeed "Item #{record.id} updated!"
append_to_response -> {
      turbo_stream.update view_context.dom_id(record)
    }
```
and
```
succeed "Item #{record.id} updated!"
append_to_response -> {
      turbo_stream.turbo_frame_reload("[data-record-id=\"#{record.id}\"]")
    }

```

But every time the whole list reloads and jumps to the beginning of the index table

Thank you

### System configuration
**Avo version**:  3.12

**Rails version**:

**Ruby version**:

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by Paul-Bob** [comment]
Hi @lizdeika, this is not possible right now.

`turbo_frame_reload` requires a frame with a valid `src` to be reloaded and we're not wrapping each row on a turbo frame.

> But every time the whole list reloads and jumps to the beginning of the index table

To avoid that jump you can use a custom component that actually wraps the index on a frame and when handling the action you reload that frame, check my demo here https://github.com/avo-hq/avo/commit/231d96996053cefa72c97f3113232c101fbde03a

Let me know how it goes.

I tested and it works as expected but I'm unsure if it brings any unwanted behaviors.

**Comment by Paul-Bob** [comment]
Hey @lizdeika, could you clarify the use case a bit more?

> But every time the whole list reloads and jumps to the beginning of the index table

Are you referring to a table on a resource index view (like this one: https://main.avodemo.com/avo/resources/users), or is it a table rendered as an association on a show page? (like Projects here: https://main.avodemo.com/avo/resources/users/avo-cado-da86f681-936c-46b9-9ab7-f5ce94e679a4?tab-group_tabs=Projects)

**Comment by Paul-Bob** [comment]
Hey, just sharing a possible DSL and a Loom video demonstrating the expected behavior for this feature.

Loom: https://www.loom.com/share/20dfb692b7b148efb2c0c8df29052bfe?sid=05cc3b14-59e3-4937-b49e-7c6f7091726a

```ruby
class Avo::Actions::DummyAction < Avo::BaseAction

  # action's configuration here

  def handle(query:, **args)
    query.each do |record|
      record.do_something
    end

    # more action logic here

    succeed "Success response ✌️"

    # To close the modal and flash messages:
    close_modal # or do_nothing

    reload_record(record)
    # OR
    reload_records([record1, record2])
  end
end
```

**Comment by adrianthedev** [comment]
@lizdeika can you please confirm this is the end result you are looking for?

**Comment by Paul-Bob** [comment]
Yes @lizdeika `reload_records` will definitively cover such setups and behave as you described on the expected behavior section.

**Comment by lizdeika** [comment]
sounds good then
but still will need to try it flesh 😅
