### ISSUE TITLE
Scopes should reset pagination

### ISSUE THREAD

**Issue by yuki-yogi** [avo-hq/avo#3353]
### Describe the bug
Pagy::OverflowError occurs in Scope

It may be related to the following Issue
- https://github.com/avo-hq/avo/issues/2468
- https://github.com/avo-hq/avo/issues/3352

### Steps to Reproduce
1. Go to https://avodemo.com/avo/resources/projects/31?via_record_id=avo-cado-a0905c85-e370-43a3-9eb9-f067eb5bfe2b
2. Click Next Page Button On User at All Scope
3. Click Admins Scope

### System configuration
**Avo version**: Avo v3.13.6
**Rails version**: Rails 7.2.0
**Ruby version**: 
**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://github.com/user-attachments/assets/72cdcdef-7f8e-4bfe-9343-ba983a4b31ff

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Thanks @yuki-yogi for sending this in.
I think scopes should reset pagination and that would fix it.
