### ISSUE TITLE
500 Internal Server Error When Loading Inline SVGs in Avo v2.48.0

### ISSUE THREAD

**Issue by waliffcordeiro** [avo-hq/avo#3367]
### Describe the bug
I am encountering an error when trying to load inline SVGs in Avo version 2.48.0. The application fails to retrieve the SVG from the development server, resulting in a 500 Internal Server Error. I have also experienced this issue in a production application.

### Steps to Reproduce
1. Set up the application using Avo version 2.48.0.
2. Ensure the Vite development server is running on `http://localhost:3036`.
3. Navigate to the resource index page that attempts to render the inline SVG.
4. Observe the error in the browser console and the server logs.

### Expected behavior & Actual behavior
**Expected behavior:** The inline SVG should load and render correctly without errors.  
**Actual behavior:** The application throws an error indicating it failed to load the inline SVG from `http://localhost:3036/vite-dev/entrypoints/arrow-circle-right.svg`.

### Models and resource files
The issue occurs on any page that renders inline SVGs.

### System configuration
**Avo version**: 2.48.0  
**Rails version**: 7.1.3.2
**Ruby version**: 3.2.2  

**License type**:
 - [X] Community
 - [ ] Pro
 - [ ] Advanced

### Screenshots or screen recordings
![Image](https://github.com/user-attachments/assets/2daeca29-4909-4f1a-b3f0-39b171723ebc)
![Image](https://github.com/user-attachments/assets/0fb840ad-265e-4984-b962-3c8d4ac3d92b)

### Additional context
I would like to maintain Avo version 2.48.0 for now, but I am open to upgrading to version 3 if necessary for a resolution. This issue has also impacted a production application.

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

---

**Comment by adrianthedev** [comment]
Hey @waliffcordeiro.

I'll preface with the fact that Avo 2 is no longer maintained. We recommend you update to Avo 3, but you already know that from what I see.

Second, we never used (still don't) Vite so we don't know that could have happened there.
It's probably a misconfiguration on the app? 🤷‍♂️

To quickly fix it, you could do a `bundle open avo`, get all the svg's from there, move them to your current app and hopefully will work.
But this is a hotfix...

I'll go ahead and close this issue, but let us know if you have any news.
