### ISSUE TITLE
Backtrace in rails server logs

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3386]
### Feature
Super admins seeing backtraces in the UI (cfr https://github.com/avo-hq/avo/pull/2905 ) is a good start.
But seeing them ALSO in the rails server logs would be better.

As within the UI they disappear after a few seconds and is not super "developer friendly"

### Current workarounds
?

### Screenshots or screen recordings

![Image](https://github.com/user-attachments/assets/a819540c-e666-4569-8224-09ff528f2265)

**Comment by Paul-Bob** [comment]
Good point, the backtrace can be logged here https://github.com/avo-hq/avo/blob/main/app/controllers/avo/base_controller.rb#L258

It's not present on logs since we're rescuing it.

**Comment by adrianthedev** [comment]
Could this be overwritten in the parent app like this?

```ruby
    def perform_action_and_record_errors
      super

      # do something with the trace if you need it
      Rails.logger.error(@backtrace) if @backtrace.present?
    end
```

**Comment by adrianthedev** [comment]
Closing for now, but let's keep the conversation open
