### ISSUE TITLE
SideBar Menu doesn't scroll after upgrading to 3.14 on Safari browser

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [avo-hq/avo#3387]
### Context
Side Bar menu doesn't scroll on Safari
### System configuration
**Avo version**: 3.14.0

**Rails version**: 7.2.2

**Ruby version**: 3.3.5

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

**Comment by adrianthedev** [comment]
Hey @AhmedAliIbrahim can you please do a hard-refresh on that page to see if that fixes it?
We think that the old css file might be browser-cached.

**Comment by AhmedAliIbrahim** [comment]
It worked! Thanks
