### ISSUE TITLE
Save button icon (floppy disk) issue (on click, doesn't save the record in Safari browser)

### ISSUE THREAD

**Issue by giedriusr** [avo-hq/avo#3389]
### Describe the bug
![Image](https://github.com/user-attachments/assets/05cde918-c0a0-4606-82fa-8dc7116febd3)
In Safari 17.5 when I click on the icon, the button starts to blink, but nothing happens. If I click on text or on the button area (avoiding icon) it works as usual.

### Steps to Reproduce
1. Add this configuration '...'
2. Go to any resource page
3. Click on edit
4. Click on save button (straight on the floppy disk icon)
5. The button should hang (blinking)

### Expected behavior & Actual behavior
It should save the record and redirect to show page.

### System configuration
**Avo version**: 3.13.7 (but this behaviour was noticed in previous versions as well)

**Rails version**: 7.2.2 (also rails 8.0.0.rc2)

**Ruby version**: 3.3.4 (also 3.3.2)

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Yup. I see that too.
So weird.

![Image](https://github.com/user-attachments/assets/990fe48d-a1b2-4c5b-bbcd-ac8fdf924207)
