### ISSUE TITLE
actions can sometimes trigger an infinite redirect

### ISSUE THREAD

**Issue by jamesmacwilliam** [avo-hq/avo#3409]
### Describe the bug

Clicking an action without a confirmation page before the js loads triggers an infinite redirect that resubmits the action continuously

### Steps to Reproduce
- Given an avo action with `self.no_confirmation = true`
- Given that I add the action to a resouce
- right click the action and follow the link
- expected result, the action succeeds and I am redirected back to the resource
- actual result: I am stuck in an infinite loop
- fix: specify an explicit `redirect_to` in the action
- this can occur without right clicking if the js doesn't load on the page before I click the link

### Expected behavior & Actual behavior
- expected result, the action succeeds and I am redirected back to the resource
- actual result: I am stuck in an infinite loop

### System configuration
**Avo version**: 3.7.4

**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x ] Pro
 - [ ] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @jamesmacwilliam thanks for reporting this. Unfortunately I wasn't able to reproduce it. Are you able to share the action code and a video on how to reproduce it?
