### ISSUE TITLE
style a resource row with css classes

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3417]
### Feature
Some of our index (and association) tables contain a lot of rows.
It would help a lot if we can set css classes on a row per row basis based on the current record

### Current workarounds
add a dummy field with text containing `<span class='foobar'></span>`

so that this css
```css
tr:has(.foobar) {
  /* styles */
}
```
would capture the whole row

```html
<tr>
  <td>
     <span class='foobar'></span>
  </td>
</tr>
```

**Comment by TobiasKampAdmin** [comment]
This is solved by applying this article: https://docs.avohq.io/3.0/guides/conditionally-render-styled-rows.html

**Comment by pjmuller** [comment]
Thanks @TobiasKampAdmin for spotting this, was looking in the wrong place in the docs
