### ISSUE TITLE
Title and description for tabs

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3421]
### Feature

Create a header section for tabs that displays a title and a description, similar to the resource's title and description.

DSL should look something like this:

```ruby
tabs "Title here", description: "Description here" do
  # ...
end
```

![Image](https://github.com/user-attachments/assets/cd735226-80c7-4ec4-8743-e7b1f6bfc507)

**Comment by Nevelito** [comment]
(For assignment)
