### ISSUE TITLE
make the  the empty association results (has_many, habtm) use a lot less height when NO records found

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3435]
### Feature
Currently the partial showing no associated results takes up a lot of height causing the users to scroll
![Image](https://github.com/user-attachments/assets/5f4abf78-dcde-4403-8512-26b4d1b3ddc8)

can we make this a lot smaller (like 3x less?)

### Current workarounds
likely via some CSS hacks and or overwriting the partial?

**Comment by Paul-Bob** [comment]
Hi @pjmuller you can eject that component and implement your own empty state component by running: `rails g avo:eject --component Avo::EmptyStateComponent`

I'm making an issue on docs to make an entry about this :D

**Comment by pjmuller** [comment]
We'll do in via the eject, thanks for the suggestion!
