### ISSUE TITLE
Access selected records from action fields method

### ISSUE THREAD

**Issue by nrgbistro** [avo-hq/avo#3446]
### Feature
This new feature would allow the run action popup modal to display dynamic data about the records it's about to run on. This would be useful to show users a message like "You're about to run X action on Y records". 

My specific use-case is a merge action, where users select a single 'primary' record in a dropdown from the records they've checked off in the index page. I don't want users to have to search through every record in our system to find the primary one. The dropdown should instead only contain selected records, making it much easier to pick the correct primary record.

### Current workarounds
Showing all records instead of the selected subset is the best I can find right now. This is not ideal because a user can accidentally select an incorrect primary record that is completely unrelated to the other selected records.

### Additional context
I envision something like this:

```
...
def fields(query:)
    field :primary_location_id,
          as: :select,
          name: 'Primary Location',
          options: -> do
            query.map { |location| [location.name, location.id] }
          end
  end

def handle(query:, fields:, current_user:, resource:, **args)
...
```

**Comment by Paul-Bob** [comment]
@nrgbistro thanks for reaching out! We already have an issue about this: https://github.com/avo-hq/avo/issues/2935

Could we please continue the discussion there? You can subscribe to it to check the progress

Closing as duplicated.
