### ISSUE TITLE
has_many does... nothing?

### ISSUE THREAD

**Issue by perryn** [avo-hq/avo#3448]
### Context
I have two models: Organisation and Company. They have a has_many/belongs_to relationship.

I installed avo and generated resources for Organisation and Company. They contain fields for the associations as you would expect.
in Organisation: `field :companies, as: :has_many` and in Company: `field :organisation, as: :belongs_to`

When I view a  company I see a link to the Organisation, but when I view an Organisation the companies are not listed.
The documentation says I should "see a new panel with the model's associated records below the regular fields panel", but I ... don't.

I can't see any errors in the log.

Not sure what I have missed here, or how to go about debugging it.

### System configuration
**Avo version**:  3.13.5

**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0

**License type**

 - [ x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ x] No

**Comment by Paul-Bob** [comment]
Thanks for opening this issue @perryn 

This issue should be fixed on versions >= [v3.13.7](https://github.com/avo-hq/avo/releases/tag/v3.13.7)

Can you confirm that upgrading fixes the issue?

> That certainly wasn’t a pleasant experience, it’s fixed on >= [v3.13.7](https://github.com/avo-hq/avo/releases/tag/v3.13.7)
> 
> Still has an impact on applications where Avo was installed on a version between [v3.13.4](https://github.com/avo-hq/avo/releases/tag/v3.13.4) and [v3.13.6](https://github.com/avo-hq/avo/releases/tag/v3.13.6).
> 
> Upgrading to >= [v3.13.7](https://github.com/avo-hq/avo/releases/tag/v3.13.7) fixes it.

_From https://github.com/avo-hq/avo/pull/3355_

**Comment by perryn** [comment]
Thanks for the exceedingly quick response @Paul-Bob 

I can confirm that a fresh avo install using 3.14.1 seems to fix this issue.

Just as an FYI I tried to upgrade the gem in place and ran into a  `undefined method `implicit_authorization=' ` error, so I just started from scratch again.

**Comment by Paul-Bob** [comment]
> Thanks for the exceedingly quick response @Paul-Bob

Anytime!

> I can confirm that a fresh avo install using 3.14.1 seems to fix this issue.

Cool!

> Just as an FYI I tried to upgrade the gem in place and ran into a undefined method implicit_authorization=' ` error, so I just started from scratch again.

For reference, we document all the breaking changes on the [Upgrade guide docs section](https://docs.avohq.io/3.0/upgrade.html)

This specific `undefined_method` is refereed here https://docs.avohq.io/3.0/upgrade.html#upgrade-from-3-13-6-to-3-13-7

Happy coding!
