### ISSUE TITLE
Fix `I18n` on resource class methods

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3449]
> @Paul-Bob @adrianthedev 
> 
> We discovered one more issue that's reproducible on the repo I have created if you run on `bin/rails dev:cache`
> 
> ![Image](https://github.com/user-attachments/assets/1f8db19d-c672-4434-9181-f8e55c000097)
> 
> You can see the german translation is used in the new resource create button.
> 
> 
>  

 _Originally posted by @jmarsh24 in [#3445](https://github.com/avo-hq/avo/issues/3445#issuecomment-2490974670)_

Steps to reproduce:

1. Checkout to this branch https://github.com/avo-hq/avo/tree/fix/i18n_on_resource_class
2. `bin/dev`
3. visit http://localhost:3030/admin/resources/products?force_locale=pt
4. Notice that the resource name is not translated inside the create button label 

Expected: "Criar novo produto"
Current label: "Criar novo product"

### Approach

I did a quick look into it and think the problem comes from the resource name methods being set up as class methods, which makes the locale stick to the original value from when the class is first loaded. 

To test this theory, I've added a commented section that duplicates the class methods as instance methods to test if it resolves the problem. Testing confirms that this adjustment indeed resolves the issue.

The code section is marked as follows (on the branch from step 1):

```ruby
      # Test if instance methods fixes the issue
      # Uncomment to test theory
```

Let's do some research on this issue and explore another approaches as well...

**Comment by adrianthedev** [comment]
Can those be declared in blocks so they are evaluated at runtime?

**Comment by jmarsh24** [comment]
@adrianthedev @Paul-Bob Thank you for the quick fix! ✊🏼
