### ISSUE TITLE
rails 8 authentication doesn't work out of the box

### ISSUE THREAD

**Issue by yshmarov** [avo-hq/avo#3455]
### Context

if I just follow this guide https://docs.avohq.io/3.0/guides/rails-authentication-scaffold.html, I get the error:
![Image](https://github.com/user-attachments/assets/275a39ac-3224-42b5-b355-804eb011101b)

Must be because the default app routes are not available in the avo controller context

```
>>  root_path
=> "/avo/"
>>  root_url
=> "http://localhost:3000/avo/"
>>  new_session_path
NameError: undefined local variable or method `new_session_path' for #<Avo::HomeController:0x00000000087dc0>
>>  main_app.new_session_path
=> "/session/new"
```

works if I set
```diff
-       redirect_to new_session_path
+      redirect_to '/session/new'
```

or

```diff
    def request_authentication
      session[:return_to_after_authenticating] = request.url
-      redirect_to new_session_path
+      redirect_to main_app.new_session_path
    end
```

What is the correct approach?

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**License type**

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

**Comment by Paul-Bob** [comment]
Hi @yshmarov!

Thanks for reaching out 

The recipe was released before releasing the code, it should work as documented on the fresh release, version `3.14.3`.

Closing as completed, feel free to reopen it if still having any issue.

Thank you!
