### ISSUE TITLE
`Attach and Attach Another` action refreshing entire page when `searchable: true` on `has_many` field

### ISSUE THREAD

**Issue by ObiWanKeoni** [avo-hq/avo#3456]
### Steps to Reproduce
1. `git clone git@github.com:avo-hq/main.avodemo.com.git`
2. in `app/avo/resources/project.rb`:
```diff
-    field :users, as: :has_and_belongs_to_many
+    field :users, as: :has_and_belongs_to_many, searchable: true
```
3. Attempt to `Attach and Attach Another` User on the Projects resource

### Expected behavior & Actual behavior
Expected: `Attach and Attach Another` keeps the modal open so you can attach another record
Actual: `Attach and Attach Another` refreshes the whole page, closing the modal.

### Models and resource files
in `app/avo/resources/project.rb`:
```diff
-    field :users, as: :has_and_belongs_to_many
+    field :users, as: :has_and_belongs_to_many, searchable: true
```

### System configuration
**Avo version**: 13.4.1

**Rails version**: 7.2.0beta2 / 8.0.0

**Ruby version**: 3.3.0 / 3.3.4

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://github.com/user-attachments/assets/23547ff8-8622-486f-b543-0cea180f1aac

### Additional context
Probably unrelated, but seems to be a bug in the `search_controller.rb`
```javascript
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'remove')
    at n.handleOnSelect (search_controller.js:223:51)
    at Object.onSelect (getDefaultProps.js:90:22)
    at getPropGetters.js:312:18
    at createCancelablePromise.js:60:12
```

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by ObiWanKeoni** [comment]
@adrianthedev and/or @Paul-Bob i took the liberty of putting a PR up for this one - if one of you could take a look, it would be much appreciated!

Thank you in advance 😄

**Comment by Paul-Bob** [comment]
Thanks for opening and reporting this issue @ObiWanKeoni 

Double thanks for opening a PR that fixes it, that's amazing! =)

I confirmed the issue both, locally and here https://main.avodemo.com/avo/resources/courses/150

We'll have a look at the PR and most probably merge it until the next minor release, which is always on the first Tuesday of each month.

Thank you again ✌
