### ISSUE TITLE
New bug in 3.14.5 (not in 3.14.0) some items/actions not visible when clicking on the admin menu (KampAdmin)

### ISSUE THREAD

**Issue by RafKampAdmin** [avo-hq/avo#3482]
### Expected behavior & Actual behavior

We should see four actions when pressing on the admin menu, we now see only two. 

### System configuration
**Avo version**:
3.14.5
**Rails version**:
7.2.1
**Ruby version**:
3.2.2
**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

### Screenshots or screen recordings

When pressing here:
![Image](https://github.com/user-attachments/assets/2eacaa33-dcc2-47c8-aafa-0f214d181929)
We should get four actions but get only two:
![Image](https://github.com/user-attachments/assets/b4f63aec-f8d2-4183-bbd2-b426ae639a35)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @RafKampAdmin could you please provide a way to reproduce this?

Can you share the `config.profile_menu` configuration code?

**Comment by RafKampAdmin** [comment]
Yes!

```
config.profile_menu = -> {
      [
        link_to('Profiel bewerken',
                "/t/#{params[:tenant_id]}/admin/resources/admin_users/#{current_user.id}/edit",
                icon: 'pencil'),
        link_to('2FA Activeren',
                path: main_app.setup_2fa_url,
                icon: 'user-circle'),
        link_to('Wachtwoord wijzigen',
                main_app.admin_user_password_change_request_path(tenant_id: params[:tenant_id]),
                method: :post,
                icon: 'key')
      ]
    }
```

**Comment by Paul-Bob** [comment]
Thanks @RafKampAdmin 

I was able to reproduce the issue with:

```ruby
  config.profile_menu = -> {
    link "Profile", path: "/profile", icon: "user-circle"
    link "Profile 2", path: "/profile", icon: "user-circle"
    link "Profile 3", path: "/profile", icon: "user-circle"
  }
```
