### ISSUE TITLE
Make source code available for ticketting demo

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3484]
### Feature
Really like to see avodemo.com , it gave me fresh insights on how to use Avo in different ways.
However when we click the source code button in the banner for the ticketting demo

![Image](https://github.com/user-attachments/assets/d570770b-6fb2-41fa-b7cf-5d6e85152655)

you get a 404

![Image](https://github.com/user-attachments/assets/a6e1a048-a826-42c7-8665-27f788f3a810)

Other than that
- https://avobookr.avodemo.com/ is offline
- https://kanban.avodemo.com/ doesn't have a source code button but it is publicly available https://github.com/avo-hq/kanban.avodemo.com
- when you click demo in the footer you don't go to avodemo.com top level site (might be a deliberate choice) ![Image](https://github.com/user-attachments/assets/6cd0a304-07ec-4a69-9015-ce5ec3ccfecd)

- maybe on avodemo.com  you could add some youtube videos where the community showcases how they tweaked avo.
  - ask some of us to make a screen recording of what we did with Avo (I'm willing to do it ❤ ) to give some more teasers in what it is all capable of (+ shortly highlighting some code how to achieve those tings)

Keep up the great work :)

**Comment by adrianthedev** [comment]
Thanks for the feedback PJ.
Always on point and super helpful 🚀

- ticketing repo is now public
- avobookr removed until we update it with a few things
- added source code links
- fixed the footer
- great idea about the videos. We'll come back with this improvement.
- we'd love ❤️ it if you would do a video like that.
