### ISSUE TITLE
failing to load mapbox - "Failed to initialize WebGL" (on avodemo.com as well)

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3485]
### Describe the bug
See https://main.avodemo.com/avo/resources/cities
![Image](https://github.com/user-attachments/assets/08ea5403-5bfc-46d0-a01a-77763db66389)

we have the same as well on our local / staging / production setup while our MAPBOX_ACCESS_TOKEN env did not change

I'm not sure when it was introduced, but my hunch is that in 3.13 it still worked (maybe even 3.14.0)

### System configuration
**Avo version**: 3.14.5

**Rails version**: 7.2.1

**Ruby version**: 3.2

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
It seems to be working in [avodemo](https://main.avodemo.com/avo/resources/cities).

Do you think it could be a hiccup from mapbox part?

**Comment by adrianthedev** [comment]
I’m closing this issue to keep the queue clean, but please feel free to comment or reopen if needed.

**Comment by pjmuller** [comment]
Very strange, my colleagues see the mapbox, but I don't...
we checked chrome versions and we are on the same. Also via incognito

We'll first try to figure out where the difference lie
