### ISSUE TITLE
Content Missing when hitting browser back button on fishies release salmon action

### ISSUE THREAD

**Issue by johnvtroy** [avo-hq/avo#3496]
### Describe the bug
Getting error when using browser back button for row action

### Reproduction repository for the bug
NA

### Steps to use in the reproduction repository
1. On Avo Demo
2. Click Fishies
3. Open record
4. Hit browser back button
5. click release salmon hand
6. get content missing error with error in console:

Uncaught (in promise) SV: The response (200) did not contain the expected <turbo-frame id="fish_list"> and will be ignored. To perform a full page visit instead, set turbo-visit-control to reload.

### Expected behavior & Actual behavior
Action should open

### System configuration
**Avo version**: 3.15.0

**Rails version**: 7.2.2

**Ruby version**: 3.3.1

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://github.com/user-attachments/assets/79401bdf-ed7f-4487-8e2c-ff5936da0e6a

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by johnvtroy** [comment]
This bug is affecting our production application environment. Could you let me know if this could be released as a patch? And a time estimate also if possible?

**Comment by Paul-Bob** [comment]
I'll have a look into this during this week. We can release a patch after merge but can't give any accurate estimation
