### ISSUE TITLE
Tables become horizontally scrollable after clicking "Select All"

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#3509]
### Describe the bug

When the "Select All" button is clicked, the tables become horizontally scrollable, leaving a wide space on the right.

Reproduced here: https://main.avodemo.com/avo/resources/projects

https://github.com/user-attachments/assets/e65f936c-ee74-4796-a4ef-ef6339c1a1f0

**Comment by Shub3am** [comment]
can i work on this issue?

**Comment by Shub3am** [comment]
can i work on this issue?

**Comment by Shub3am** [comment]
![Image](https://github.com/user-attachments/assets/5d8d7c69-94fd-4483-9dc3-f656b9e2374b)
this is the issue, the selector bar is overflowing

**Comment by Shub3am** [comment]
@Paul-Bob Raised a PR for the same
