### ISSUE TITLE
[Feature request] Allow custom view component directory

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#415]
From https://github.com/avo-hq/avo/discussions/414

The custom field generator generates several view components that are used to render the field. It would be nice if the generator could make use of a configuration option that allows the directory of these generated components to change. Currently, it places the components in `app/components`, but in my apps, I put components in different directories, such as `app/view_components` or `app/frontend/components`.

**Comment by vitaly107** [comment]
I generated new field `rails generate avo:field custom_editor`

and it is not showing despite me adding `field :content, as: :custom_editor` to the resource

what do I do wrong?

**Comment by mihaimdm22** [comment]
@vitaly107 this is a different issue, please open another issue so we can handle them separately

**Comment by vitaly107** [comment]
done

**Comment by nulldotpro** [comment]
@adrianthedev I'll find some time to work on this one, since I requested it!

**Comment by adrianthedev** [comment]
Released in [1.7.3](https://rubygems.org/gems/avo/versions/1.7.3)
