### ISSUE TITLE
[BUG] cannot see a new custom field

### ISSUE THREAD

**Issue by vitaly107** [avo-hq/avo#417]
I generated new field rails generate avo:field custom_editor

and it is not showing despite me adding field :content, as: :custom_editor to the resource

what do I do wrong and where next?

**Comment by mihaimdm22** [comment]
@vitaly107 I've tested locally and it works
double check what you modified or try to restart the server
let me know if we can help further

**Comment by vitaly107** [comment]
I restrated the server and the field is not showing. all I did is as above just ran generator and added the field to resource. I have not touched any files as yet that have been generated.

**Comment by mihaimdm22** [comment]
hmm seems strange
in order to troubleshoot i need more information about:
- which version do you use? latest one?
- do you used the correct path for generating the field?
- have you tried to see that field using a text field?

**Comment by vitaly107** [comment]
not sure what you mean by p.2

I just had:

```
 uk-public git:(ukp-202) ✗ rails generate avo:field custom_editor
Running via Spring preloader in process 47450
      create  app/components/avo/fields/custom_editor_field
      create  app/components/avo/fields/custom_editor_field/edit_component.html.erb
      create  app/components/avo/fields/custom_editor_field/edit_component.rb
      create  app/components/avo/fields/custom_editor_field/index_component.html.erb
      create  app/components/avo/fields/custom_editor_field/index_component.rb
      create  app/components/avo/fields/custom_editor_field/show_component.html.erb
      create  app/components/avo/fields/custom_editor_field/show_component.rb
      create  app/avo/fields/custom_editor_field.rb

```
then added to the resource 
`field :content, as: :custom_editor`

restarted and the filed is not shown

**Comment by vitaly107** [comment]
if I change that to `field :content, as: :custom_editor` then it appears.

**Comment by vitaly107** [comment]
Rails 6.0.3.6

**Comment by mihaimdm22** [comment]
try update to latest version of Avo, bcs this bug might have been solved as it works for us locally with latest version (1.7.2)
thanks!

**Comment by vitaly107** [comment]
I have updated as above and I can now see the field in question. Thanks. This is now resolved.

**Comment by mihaimdm22** [comment]
good to hear! I'll close this issue
