### ISSUE TITLE
[BUG] readonly does nothing on :has_many

### ISSUE THREAD

**Issue by TheFehr** [avo-hq/avo#420]
### Describe the bug
I have ActionJobs that generate a lot of different model's which I would love to observe with avo. 
There is multiple instances where there is a :has_many relationship, that I don't want to be able to attach myself, since this is the ActionJob's job.
I was expecting the readonly flag to disable attachments on the :has_many fields.

### Steps to Reproduce
1. Add a :has_many field with readonly: true
2. Open that resource
3. See the attach button

### Expected behavior
3. Not see the attach button

### System configuration
**Avo version**:
1.7.2

**Rails version**:
6.0.3.6

**Ruby version**:
2.7.3p183

**Comment by adrianthedev** [comment]
Yes. This is a valid bug. There's [a discussion](https://github.com/avo-hq/avo/discussions/398) about hiding those buttons.

We could go with `readonly: true` or with options like `disable_creation: true/false` and disable_attaching: true/false` so you can disable them however you need them.
