### ISSUE TITLE
[BUG] Caching `service_url` for images on S3 causes 403s as links expire

### ISSUE THREAD

**Issue by jdbann** [avo-hq/avo#422]
### Describe the bug
With images hosted on S3, the `service_url` method includes an `expires_in` amount ([default of 5 minutes](https://github.com/rails/rails/blob/main/activestorage/lib/active_storage/engine.rb#L92)). As Avo caches index rows, it retains a link which will expire and eventually return 403s for attempts to load the image.

### Steps to Reproduce
1. Setup a model with an ActiveStorage file attachment backed by S3
2. Create an Avo resource with the file field and `is_image` set to true
3. Create an instance of the model with an image as the file
4. View the index to generate the variant
5. Wait 5 minutes
6. View the index again and see a 403 when attempting to download the image

### Expected behavior
Should load the image regardless of caching

### Actual behavior
Attempts to load the image with an expired token

### System configuration
**Avo version**: 1.7.2

**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/avo/pull/429

**Comment by adrianthedev** [comment]
Released in [1.7.3](https://rubygems.org/gems/avo/versions/1.7.3)

**Comment by jdbann** [comment]
Looks like it's working perfectly. Thank you @adrianthedev!
