### ISSUE TITLE
[BUG] Actions don't work on index view

### ISSUE THREAD

**Issue by TheFehr** [avo-hq/avo#431]
### Describe the bug
On index view the actions do not work. It sends an empty array to the backend in the ajax call.

### Steps to Reproduce
1. Create an action.
2. Add it to a resource.
3. Select 1-x Rows on index of that resource 
4. Press the action button
5. Select your action
6. Confirm
7. Nothing happens

### System configuration
**Avo version**:
1.7.3

**Rails version**:
6.0.3.6

**Ruby version**:
2.7.3p183

**Comment by adrianthedev** [comment]
Hi,

Can you share the contents of the action? I'm testing the latest version on the [demo site](https://avodemo.herokuapp.com/avo/resources/users) and can't seem to replicate it.

**Comment by TheFehr** [comment]
This is the url and the post body, the fields[resource_ids] is empty
``http://localhost:3000/avo/resources/scrap_service_specifications/actions/re_execute_parser``
``authenticity_token=RjUL44G9nV6OoX5kd0VtsoqCkKavciPVNmAA/VTKjngzj8qax1/MgDS/J+34SnXty3BsEcSK0YYKBZwxEXb62A==
fields[resource_ids]
button``

And this is the action:
``
# frozen_string_literal: true

# noinspection RubyUnusedLocalVariable
class ReExecuteParser < Avo::BaseAction
  self.name = 'Re execute parser'

  def handle(models:, fields:)
    models.each do |model|
      raise 'Service Specification has no ScrapRows' if model.scrap_rows.empty?
      next if model.scrap_rows.empty?

      ServiceSpecificationParser::Service.run(model.scrap_rows.last)
    end

    succeed 'Re-parsed all ServiceSpecifications!'
  end
end
``

**Comment by adrianthedev** [comment]
This is weird. It should work.

Does the `ServiceSpecificationParser::Service.run` action run?

Are you using a custom asset pipeline with Avo? Are you inserting any javascript? I'm wondering if anything is interfering with Turbo.

**Comment by TheFehr** [comment]
```
ServiceSpecificationParser::Service.run
```
Runs not when the avo action is called from the index page.
It does from the view page of the resource.

I belive there was a js exception I saw in the browser console. I can check that again later today and send you the details


I do not use any custom js or assets. But I wouldn't be surpised if I somehow broke the pipeline by mistake.

**Comment by adrianthedev** [comment]
That would be very helpful. Thank you!

**Comment by TheFehr** [comment]
The exception actually does happen when I select a row on the index view.
And then also after the reload caused by the action:

```
Uncaught Error: Missing target element "toggle-panel.panel"
    get target_properties.js:20
    value toggle_panel_controller.js:12
    s use-click-outside.js:17
    l use-click-outside.js:28
    l use-click-outside.js:27
    value use-click-outside.js:45
    value toggle_panel_controller.js:8
    connect context.js:21
    connectContextForScope module.js:34
    scopeConnected router.js:92
    elementMatchedValue scope_observer.js:41
    tokenMatched value_list_observer.js:44
    tokenMatched token_list_observer.js:60
    tokensMatched token_list_observer.js:53
    tokensMatched token_list_observer.js:53
    elementMatchedAttribute token_list_observer.js:41
    elementMatched attribute_observer.js:49
    addElement element_observer.js:122
    refresh element_observer.js:35
    start element_observer.js:14
    start attribute_observer.js:23
    start token_list_observer.js:17
    start value_list_observer.js:17
    start scope_observer.js:12
    start router.js:55
    r application.js:70
    s application.js:32
    s application.js:13
    a application.js:4
    promise callback*l application.js:6
    start application.js:7
    start application.js:3
    start application.js:59
    <anonymous> application.js:34
    <anonymous> application.js:56
    <anonymous> application-651ed7b9bc727c83f673.js:25
target_properties.js:20:26
```

**Comment by adrianthedev** [comment]
Could you have any weird extensions that mess with the markup? Can you try in a different browser to see if that could cause it?

Also, did you eject the `_actions.html.erb` partial?

**Comment by TheFehr** [comment]
I did not eject anything. Do I need to?

I will check with another browser. The one I tested was firefox. With only 2 or 3 extensions.

**Comment by adrianthedev** [comment]
No, you shouldn't if you don't need to. I was asking to asset the issue.

Let me know if it works in a different browser. If not, I can hop on a call with you to troubleshoot it.

**Comment by TheFehr** [comment]
I get the same error on Firefox and on a clean Microsoft Edge.
I won't be free for a call again until next week Wednesday evening.
The project I'm using avo in is for my startup. And I still work fulltime another job

**Comment by TheFehr** [comment]
```
<div class="relative z-30" data-controller="toggle-panel actions-picker">
      <button name="button" type="submit" class="inline-flex flex-grow-0 items-center text-sm font-bold leading-none fill-current whitespace-nowrap transition duration-100 rounded-lg shadow-xl transform transition duration-100 active:translate-x-px active:translate-y-px cursor-pointer disabled:cursor-not-allowed focus:outline-none text-white bg-light-blue-500 hover:bg-light-blue-600 disabled:bg-light-blue-300 p-4" color="light-blue" data-action="click->toggle-panel#togglePanel" data-actions-dropdown-button="scrap service specifications" disabled="disabled">
    
      <svg fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor" class="h-4 mr-1 transform -rotate-90"><path d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
 Actions

</button>    <div class="absolute block inset-auto right-0 top-full bg-white min-w-300px mt-2 py-4 z-20 shadow-context rounded-xl overflow-hidden hidden" data-toggle-panel-target="panel">
        <a data-turbo-frame="actions_show" data-action="click->actions-picker#visitAction" class="flex items-center w-full py-2 px-4 font-bold text-gray-700 hover:text-white hover:bg-blue-500" href="/avo/resources/scrap_service_specifications/actions/re_execute_parser">
          <svg class="h-5 mr-1 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
 Re execute parser
</a>    </div>
  </div>
```

**Comment by adrianthedev** [comment]
Hmm, that should work. The DOM has that target (`data-toggle-panel-target="panel"`) available.

So you're seeing this on the `http://localhost:3000/avo/resources/scrap_service_specifications` url?

**Comment by TheFehr** [comment]
> So you're seeing this on the `http://localhost:3000/avo/resources/scrap_service_specifications` url?

Yes and also on a production (docker, self-hosted) deploy.

**Comment by adrianthedev** [comment]
Do you have any other actions on other resources? Do those work? If you don't have any other, can you add one and see if that works?

If not... I'd love to jump on a call to see the behavior.

**Comment by TheFehr** [comment]
I have a similar action on another resource showing the exact same symptoms.

I am generally Monday and Wednesday evening free for a call.
Is that possible for you, if not I could maybe make some time during Thursday morning or afternoon.
What call platform would you prefer?

**Comment by adrianthedev** [comment]
Feel free to book [a slot](https://calendly.com/adrianthedev ) whenever you're available, please.

**Comment by TheFehr** [comment]
Is booked
