### ISSUE TITLE
[BUG]Table View Sort Not Work if Using `deafult_scope` or `resolve_query_scope`

### ISSUE THREAD

**Issue by luonet** [avo-hq/avo#436]
### Describe the bug
If you are using the `default_scope` in the model,
or `resolve_query_scope` in the resource;
When you set a field as `sortable`,
the record in the table view would not be sortable by the field.

And the record would be sortable only if you remove the `default_scope` from the model,
and `resolve_query_scope` from the resource.

### System configuration
**Avo version**: 
1.8.1

**Rails version**:
6.1.3.2

**Ruby version**:
3.0.0

### Additional context
I think this bug might be caused by not `unscope(:order)`.
If we want to sort only by the `sortable` field, we should `unscope(:order)` of the query object first.

**Comment by mihaimdm22** [comment]
hey @luonet 

first of all thanks for reporting this and also suggesting how to solve it

we added a fix for it and tested for both `default_scope` and `resolve_query_scope` and it works

we'll release very soon -> get latest version of gem -> test it -> let me know if you have additional questions

**Comment by luonet** [comment]
Hi @mihaimdm22

First, thanks for your fix and response.
So fast!

I noticed following lines added:
```ruby
unless @index_params[:sort_by].eql? :created_at
  @query = @query.unscoped
end
```

I have one concern:
The `@query.unscoped` will unscope all scopes, and I doubt it might be too agressive?

For example, suppose we declared a default_scope in the Movie model,
```ruby
  default_scope { where(published: true).order(release_date: :desc)
```

If we apply unscoped to the default_scope, the order and where scope would all be removed.
So when you click the field sorting in the movies index, the unpublished movies will show!

So I think it's better to only unscope order in this case?
```ruby
  @query = @query.unscope(:order)
```

Thanks again!
Thanks you very much!

**Comment by mihaimdm22** [comment]
Hi @luonet 

Sorry for my late reply!

I pushed the change you suggested regarding scoping.

Now looking into issue #439.

Thanks for your patience!

**Comment by luonet** [comment]
Hi @mihaimdm22 

Thank you very much!

Got the latest version and tested in my environment.

I think for most cases, it perfectly works;
but in some extreme edge cases, it may have a very subtle issue(NOT a bug).

Suppose we have a Movie model with default_scope:
```ruby
class Movie < ApplicationRecord
  default_scope { order(release_date: :desc) }
```

In the avo movie resource index page, if no sortable field clicked, the expected SQL should be:
```SQL
SELECT "movies".* FROM "movies" ORDER BY "movies"."release_date" DESC
```

but actually it is:
```SQL
SELECT "movies".* FROM "movies" ORDER BY "movies"."release_date" DESC, movies.created_at desc
```

Why? Let's look into the code:

```ruby
      if @index_params[:sort_by].present?
        unless @index_params[:sort_by].eql? :created_at
          @query = @query.unscope(:order)
        end
        @query = @query.order("#{@resource.model_class.table_name}.#{@index_params[:sort_by]} #{@index_params[:sort_direction]}")
      end
```

In this case, `@index_params[:sort_by].present?` is the default value `:created_at`, which is set in the `set_index_params` method, so the `@query` would be `Movie.order("movies.created_at :desc").` 
Since Movie already has a default_scope with order, the final result will have double orders.

Though it's NOT a bug, but for perfect, I try to make a pull request to resolve this very subtle issue.
After looking into active record and avo code, finally, I give up.

To resolve this issue, we need to know if the corresponding model_class has already had a default scope with :order.
I could use following code to check:
```ruby
# It means we already declared order in default_scope or resolve_query_scope
if (@query.is_a?(ActiveRecord::Relation) && @query.values[:order]) || (@query.is_a?(ActiveRecord::Base) && @query.default_scoped.values[:order])
  # In this case, nothing need to do since we already had order scope. 
  # @query = @query 
```

But I think it's too sophisticated to introduce such code to fix EVEN NOT a bug. So I give up. 😄 

BTW:
I found another very interesting issue. If we declared the created_at field as sortable in the avo resource:
```ruby
  field :created_at, as: :date_time, sortable: true
```

I thought it might be an issue but It works fine.
After investigation, I found in this case, @index_params[:sort_by] would be `"created_at"` rather than `:created_at`.
So it works FINE! Very interesting!


After all,
this comment seems a little verbose.
But the use cases are really complicated and I think it deserves a detailed record.

Thanks for your patience!

**Comment by mihaimdm22** [comment]
Hi @luonet 

This is not too verbose at all. We appreciate your effort into explaining it so clearly with snippets and digging inside code.

I'll look into that little issue and find a fix for it asap.

Thanks!

**Comment by mihaimdm22** [comment]
Hey @luonet 

I investigated more, couldn't find a solution for the edge case and as you said this is not a BUG per se, so we'll live with it.

Let me know if you have related issues in the future.
