### ISSUE TITLE
[BUG]Action Not Work When Using String ID

### ISSUE THREAD

**Issue by luonet** [avo-hq/avo#439]
### Describe the bug
Rails uses auto-increment integer as ID by default.
But in some cases, we'd like to use string based IDs.

And I found Avo::ActionsController can not handle the string ids.

I looked into the code, found there is an integer based ID assumption in the code:
```ruby
    # app/controllers/avo/actions_controller.rb:13L
    def handle
      resource_ids = action_params[:fields][:resource_ids].split(",").map(&:to_i)
``` 

The `map(&.to_i)` will always return 0 with non-integer like string IDs.
So the action will not work.

### Steps to Reproduce
1. Create a new model with string IDs. For example:
```ruby
class CreateMovies < ActiveRecord::Migration[6.1]
  def change
    create_table :movies, id: :string do |t|
      t.string  :name, null: false
```
2. Add some data, like `Movie.create(id: 'aaa', name: 'Test')`.
3. Create avo:resource and avo:action for this model.
4. In the resource index page, you'll see the action will not work.

### System configuration
**Avo version**:
1.8.1

**Rails version**:
6.1.3.2

**Ruby version**:
3.0.0

### Additional context
I think we should consider the ID-as-string use case.

Thanks!

**Comment by luonet** [comment]
Besides this issue, I added a comment in the closed bug:
https://github.com/avo-hq/avo/issues/436#issuecomment-864186865

Please check again, thanks.

**Comment by adrianthedev** [comment]
Hello. Yes, unnecessary assumption again. We’ll get on it to fix this. 

We’re actively working on the other issue too. My colleague forgot to mention it. 
We’ll have a release out in the next 24 hours. 

Apologies for the delay.
