### ISSUE TITLE
[Feature] How to sort column with association?

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#451]
### Describe the bug
The current behavior always appended the current table name at the beginning of the column. This does not work on the associated column so we should support the below format

`field :name, as: :text, sortable: 'people.name'`

### Steps to Reproduce
1. Go to the index page with associated column
2. Enable sortable option on the associated column
3. Clicking sort enabled column throws an exception

### System configuration
**Avo version**: 1.10.1

**Rails version**: 6.0

**Ruby version**: 2.7.2

### Additional information
We can use this as reference - https://github.com/activeadmin/activeadmin/pull/623

**Comment by luonet** [comment]
In other Rails admin framework like [trestle](https://github.com/TrestleAdmin/trestle)，we could use joins to sort association's   field(or counted field).

For example, we have Movie and Director model, each movie belongs to a director:

```ruby
class Movie < ApplicationRecord
  belongs_to :director
end

class Director < ApplicationRecord
  has_many :movies
end
```

Now, suppose we are in the directors index page, we want to sort directors by each director's movies count.
In trestle, we could use the left outer joins to introduce a `movies_count` field:

```ruby
  collection do
    def count(col)
      col.unscope(:select, :left_outer_joins, :group).count
    end

    model.select('directors.*, COUNT(movies.id) AS movies_count')
         .left_outer_joins(:movies)
         .group('directors.id')
  end
```

then we could sort by `movies_count` as a normal field:

```ruby
    column 'movies_count', sort: {field: :movies_count, default_order: :desc}
```

I tried the same method in avo, we could declare the same left_outer_joins in `resolve_query_scope` as `collection` does in trestle.

It almost works, but failed(will raise an exception) in the `count` calculation.

So I think we should provide a user redefine interface for `count` as what trestle does in the `collection`.

**Comment by adrianthedev** [comment]
This is a good ideea. Could you make a PR with this feature?

**Comment by mighani** [comment]
is there any news on this issue. In 2.19.0 It's still the case.

**Comment by mighani** [comment]
still can not figure out how to sort by the association
