### ISSUE TITLE
[BUG] Action Controller does not resolve action class names correctly.

### ISSUE THREAD

**Issue by nulldotpro** [avo-hq/avo#459]
### Describe the bug
The `ActionController` uses the `classify` method on `params[:action_id]`, which returns a singularized version of the action's name. 

### Steps to Reproduce
1. Create an action called `EmailUsers`
2. Attempt to use the action
3. Notice that nothing happens, because `EmailUser` is not the name of the action class.

### System configuration
**Avo version**: 1.11.0

**Comment by adrianthedev** [comment]
Released in 1.11.2
