### ISSUE TITLE
[BUG] Make the File field UUID friendly

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#461]
### Describe the bug
Impossible to use `active_storage` file fields when using `uuids` in the application.

### Steps to Reproduce
1. On a blank app, when generating `active_storage` install, change the `record_id` type into `text` to accomodate for both `id` and `uuid` types OR
1. On an existing app with ActiveStorage, run a migration to change the `record_id` type into `text` (see screenshot below)
2. [Install the UUID pg extension](https://itnext.io/using-uuids-to-your-rails-6-application-6438f4eeafdf)
3. Create a new resource
4. Configure a file attachment in the resource model file
5. Create a resource with a file attached
6. Generate the resource with Avo + add the `field :photo, as: :file` in the avo model file config
7. Visit the resource index and see the error

### Expected behavior
The resources should display correctly with their attached image

### Actual behavior
We get an `ActiveRecord::StatementInvalid in Avo::InsurersController#index` error :

```
PG::UndefinedFunction: ERROR: operator does not exist: text = bigint LINE 1: ...= $2 AND "active_storage_attachments"."record_id" = "insurer... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
To resolve this issue run: bin/rails active_storage:install
```

### System configuration
**Avo version**: 1.11.2

**Rails version**: 6.1.3.2

**Ruby version**: 2.6.6

### Screenshots
The error :
![Capture d’écran 2021-07-01 à 11 47 49](https://user-images.githubusercontent.com/38864576/124105708-c95f1000-da63-11eb-88a9-fff82c102b80.png)
My DB schema:
![Capture d’écran 2021-07-01 à 12 00 16](https://user-images.githubusercontent.com/38864576/124105822-e8f63880-da63-11eb-82c5-1537d92a8238.png)
The migration to change `record_id` type :
![Capture d’écran 2021-07-01 à 12 01 54](https://user-images.githubusercontent.com/38864576/124106048-24910280-da64-11eb-8fab-a764d9f50f9d.png)

### Additional context
There is a notorious limitation of `ActiveStorage` which is by default unable to handle UUID foreign_keys. You normally have to either choose UUID or ID type when generating the install migrations. One of the workarounds when using both types of ID in an application is to change the column type for `record_id` as `text` which is working fine.

**Comment by adrianthedev** [comment]
Hmm... We haven't used `ActiveStorage` with `uuid`s before. Is this an Avo limitation or a Rails limitation?

Also, not sure what we can do in Avo to support this use case. Could you advise on how Avo could fix it?

**Comment by bear-in-mind** [comment]
It's definitely a Rails limitation. I'll have a look at the code and propose a PR when I have the time :)

**Comment by adrianthedev** [comment]
Got it! I mean, if there's something we can do in Avo to make it usable, I'm all for doing it, just not sure what.

**Comment by bear-in-mind** [comment]
My guess is there might be a way to make the `active_storage_attachment_id` more agnostic in the way it's being passed in your implementation of `active_storage` fields ; maybe it's currently being _forced_ as an integer type ? Or maybe we could convert the id to a string before it's passed ? On my `postgres` app, I never had any problem of the kind, and use indifferently `ids` or `uuids` as foreign keys.

**Comment by adrianthedev** [comment]
I understand your concern. I had a quick look in our AS implementation and couldn't find any _forced_ integer casting.

**Comment by bear-in-mind** [comment]
Found the culprit ! Let me know what you think in the PR.
