### ISSUE TITLE
[BUG] Tool generator seems to be broken

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#462]
### Describe the bug
Tool generator seems to be broken ; the 4th step updating the routes file exits with an error

### Steps to Reproduce
1. Launch the tool generator with something like `bin/rails g avo:tool quotes` 
2. See the terminal error when trying to update the routes file

### Expected behavior
It should generate files and exit gracefully

### Actual behavior
I get the following error after the creation of the `_quotes.html.erb` partial :
```
/Users/louis/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/avo-1.11.2/lib/avo/configuration.rb:96:in `namespace': undefined method `delete' for nil:NilClass (NoMethodError)
```

### System configuration
**Avo version**: 1.11.2

**Rails version**: 6.1.3.2

**Ruby version**: 2.6.6

### Screenshots
![Capture d’écran 2021-07-01 à 12 19 57](https://user-images.githubusercontent.com/38864576/124109000-feb92d00-da66-11eb-9774-800c190f7073.png)

### Additional context
Not much to add

**Comment by mihaimdm22** [comment]
Hi @bear-in-mind 

This was due to not checking for nil. We pushed the changes.

Let me know if you have addtional questions regarding this.
