### ISSUE TITLE
[BUG] Custom helpers don't seem to be visible/usable

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#463]
### Describe the bug
Trying to use a custom helper (defined in `app/helpers`) resulted in  a `NoMethodError`

### Steps to Reproduce
1. Define a helper in `ApplicationHelper`
2. Add a call to the helper in a custom view or tool
3. See the error when displaying the view

### Expected behavior
The helper method is expected to be found and executed correctly

### Actual behavior
The method is not found and triggers a 500

### System configuration
**Avo version**: 1.11.2

**Rails version**: 6.1.3.2

**Ruby version**: 2.6.6

### Screenshots
![Capture d’écran 2021-07-01 à 14 31 52](https://user-images.githubusercontent.com/38864576/124124736-17cad980-da79-11eb-8a9d-56fb8cd59b32.png)

![Capture d’écran 2021-07-01 à 14 32 23](https://user-images.githubusercontent.com/38864576/124124794-27e2b900-da79-11eb-8f40-3e6c8f6bba1d.png)

### Additional context
-

**Comment by bear-in-mind** [comment]
Found a workaround ; in my main controller inheriting from `Avo::ApplicationController`, I added `helper :all` to load all the helpers defined in `app/helpers`.

**Comment by adrianthedev** [comment]
Hey @bear-in-mind. Could you try `main_app.admin_path_to_form` instead of `admin_path_to_form` and see if that works without adding `helper :all` to your controller?

Curious to see if that fixes it. It fixed it for us.

**Comment by bear-in-mind** [comment]
Nope, I get this error instead:

![Capture d’écran 2021-07-01 à 16 47 33](https://user-images.githubusercontent.com/38864576/124144213-0b03b100-da8c-11eb-85b4-dc0bc8e43560.png)

**Comment by adrianthedev** [comment]
Can you also try `avo.admin_path_to_form`? Not sure where the controller is located.

**Comment by bear-in-mind** [comment]
Exact same error ! It very much looks like a problem I had with [my own gem](https://github.com/eki-177/abyme), which was due to a view `context` issue, that was not being passed as it should. Don't know if it could be related to the one at hand

**Comment by bear-in-mind** [comment]
By the way, I just had the case where I indeed needed to call `main_app.my_own_path` to redirect to one of my own routes from an `avo` action. But it only works for route helpers, not for view helpers :)

**Comment by adrianthedev** [comment]
I looked into this issue this morning. 

Because the custom tools inherit from Avo's `ApplicationController` (`avo` engine) you have to include the helpers from your app (the Rails engine).

I couldn't get it to work with `helper :all` but I managed to make it work by specifying the helper file `helper HomeHelper`.

I documented the feature [here](https://docs.avohq.io/1.0/custom-tools.html#using-helpers-from-your-app).

Thank you for looking into this 🙏
