### ISSUE TITLE
[BUG] `bin/init` fails with `ActiveRecord::NoDatabaseError: FATAL:  role "postgres" does not exist`

### ISSUE THREAD

**Issue by chrismdp** [avo-hq/avo#471]
### Describe the bug
I'm trying to get a clean dev environment running in order to work on [select all](https://github.com/avo-hq/avo/discussions/452).  I've got the tests passing through dropping an active storage table and re-running `RAILS_ENV=test bin/rails db:migrate` but I cannot get the rails build running in development. Instead I get the error in the title.

I tried creating a `config/database.yml` but it seemed to have no effect.

### Steps to Reproduce
1. Clone repo
2. Install + boot docker
3. run `bin/init`
4. Choose `y` for database in docker

### Expected behavior
Should successfully complete script and allow `bin/rails server`

### Actual behavior

Command output:

```
[skip bundle + yarn output]
...
==========================
Creating the Docker volume
==========================

avo-db-data

=====================================
Creating and running the Docker image
=====================================

avo_db_1 is up-to-date

======================
Preparing the database
======================

FATAL:  role "postgres" does not exist
Couldn't create 'dummy_development' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "postgres" does not exist
```

### System configuration
**Avo version**: latest master

**Rails version**:

**Ruby version**: `ruby 2.6.6p146 (2020-03-31 revision 67876) [-darwin20]`
- had to force a later ruby due to being on an M1 - `msgpack` refused to install otherwise

**Comment by adrianthedev** [comment]
This is weird. It should just work OTB. I deleted my container and ran it again and it worked.

<details>
<summary>Details</summary>

```
==========================
Creating the Docker volume
==========================

avo-db-data

=====================================
Creating and running the Docker image
=====================================

Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "avo_default" with the default driver
Creating avo_db_1 ... done

======================
Preparing the database
======================

warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Database 'dummy_development' already exists
Database 'dummy_test' already exists

=========================
Stopping the Docker image
=========================

Stopping avo_db_1 ... done
```

</details>

I added [instructions](https://github.com/avo-hq/avo/pull/472) on how to test using your local installation rather than the docker image.

Most probably you need to change the `POSTGRES_PORT=5432` and update your postgres credentials in your `.env.test` file.

LMK if you can use this 👆

**Comment by adrianthedev** [comment]
Oh, and thanks 🙏 for contributing to the project. You rule!

**Comment by chrismdp** [comment]
Yeah that worked fine thanks. Also turned out Homebrew-installed Postgres created a default user with my username rather than `postgres` - should have checked! 🤦‍♂️

**Comment by adrianthedev** [comment]
No problem! Happens to all of us ✌️
