### ISSUE TITLE
[BUG] Custom field doesn't appear

### ISSUE THREAD

**Issue by ev-bordiuk** [avo-hq/avo#481]
### Steps to Reproduce
1. `rails generate avo:field carrier_upload`
2. added field to resource `field :description, as: :carrier_upload`

### Actual behavior
field doesn't appear.

### System configuration
**Avo version**: 1.11.6

**Rails version**: 6.1.3.2

**Ruby version**: 2.6.6

### Additional context
Also, as mentioned in another issue Avo version 1.7.2, but it didn't help

**Comment by adrianthedev** [comment]
Hello, did you restart the server?

**Comment by ev-bordiuk** [comment]
yes, several times

**Comment by adrianthedev** [comment]
I tested with 1.9.1 right now and the field shows up.
![image](https://user-images.githubusercontent.com/1334409/126480491-464c647f-cf7f-4829-b402-284b480c56bd.png)
![image](https://user-images.githubusercontent.com/1334409/126480507-f8037f3a-225e-452e-80d3-51e3cd071843.png)
![image](https://user-images.githubusercontent.com/1334409/126480585-ccc8a713-7e52-4072-9f0f-b6dbdde8cae8.png)


Can you check the console for a message like this? `[Avo] The FIELD_NAME field, as: :carrier_wave from RESOURCE_NAME has an invalid configuration.`

**Comment by ev-bordiuk** [comment]
I have same error when tried to break it up to verify, does it throw an error.

**Comment by adrianthedev** [comment]
Hmmm... this is weird. Can you try to add the field on a different resource? See what results we get.

**Comment by ev-bordiuk** [comment]
Result is the same. And when I change it to built-in field type everything appears.

**Comment by adrianthedev** [comment]
This is weird. Do you want to jump on a call to try and get to the bottom of this issue?

Please [schedule](https://calendly.com/adrianthedev/30min) something when it's most convenient for you.

**Comment by adrianthedev** [comment]
I'm closing this for now. Please let me know if you want us to re-open it.
