### ISSUE TITLE
[BUG] Custom tools navigation breaks

### ISSUE THREAD

**Issue by TheFehr** [avo-hq/avo#482]
### Describe the bug
On a custom tool page the left side navigation is broken.
Generates routes are in the form of `avo/{toolname}.{resource}`

### Steps to Reproduce
1. Add custom tool page

### System configuration
**Avo version**:
 v1.11.6

**Rails version**:
6.0.4

**Ruby version**:
2.7.4p191

**Comment by mihaimdm22** [comment]
Avo v1.12.0 fixes this. Let me know if you have further problems with this!
