### ISSUE TITLE
[BUG] Error deleting ActiveStorage files

### ISSUE THREAD

**Issue by jdbann** [avo-hq/avo#487]
### Describe the bug
I'm getting an `ActiveRecord::RecordNotFound` error when trying to delete a file attached with ActiveStorage. It's coming from an attempt to load an `ActiveStorage::Blob` - but the provided `id` is for the related `ActiveStorage::Attachment`.

### Steps to Reproduce
1. Setup a resource with a file field for an ActiveStorage `has_one_attached` association
2. Setup a record for the resource with an attached file (this works fine with Avo)
3. Click on 'Delete File'

### Expected behavior
Should delete the `ActiveStorage::Attachment` (and the `ActiveStorage::Blob` if no other files use it, but I believe Rails should handle this rather than Avo).

### Actual behavior
Returns an error when trying to find the `ActiveStorage::Blob`.

### System configuration
**Avo version**: 1.12.2

**Rails version**: 6.1.4

**Ruby version**: 2.7.2

### Additional context
- [`Avo::Fields::FileField::ShowComponent`](https://github.com/avo-hq/avo/blob/master/app/components/avo/fields/file_field/show_component.html.erb#L2) provides the `@field.id` value as the id param, and `@field.value.attachment` value as the file param for `Avo::Fields::Common::SingleFileViewerComponent` - `@field.value.attachment` here returns the `ActiveStorage::Attachment` ([see `ActiveStorage::Attached::One#attachment`](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activestorage/lib/active_storage/attached/one.rb#L12-L14))
- [`Avo::Fields::Common::SingleFileViewerComponent`](https://github.com/avo-hq/avo/blob/master/app/components/avo/fields/common/single_file_viewer_component.html.erb#L20-L21) then builds a destroy link with (I think) the model's id as the `:attachment_name` and `@file.id` (which will be the `ActiveStorage::Attachment`'s id) as the `:signed_attachment_id`
- That link makes a GET request. the response of which updates the `destroy_attachment_form` TurboFrame, which doesn't change any values - just creates a form in the page which can make the request to destroy the attachment
- This gets routes to the `destroy` action on `Avo::AttachmentsController` which [tries to find an `ActiveStorage::Blob` based on the `params[:signed_attachment_id]`](https://github.com/avo-hq/avo/blob/master/app/controllers/avo/attachments_controller.rb#L24) - and because this is the id for the `ActiveStorage::Attachment`, it raises the error

I'm just not sure if there's a specific reason you're working with the blob in the `Avo::AttachmentsController` rather than the attachment - otherwise I'd have submitted a PR.

**Comment by adrianthedev** [comment]
First of all, apologies for the delay. We've been swamped these days.

You're saying that the destroy action get's sent the wrong `id` (attachment instead of blob).

To answer your question, there isn't any reason why that id is being used. It probably a bug that didn't show up until now because the blob and attachment had the same `id` IMHO.
Does that theory make sense?

**Comment by jdbann** [comment]
No problem! Yeah, it looks like the wrong `id` is provided.

I think that theory makes sense for incrementing integer primary keys - most simple setups will have a 1-1 relationship between an attachment and a blob, so the ids are likely to be the same.

I'm using uuids primary keys for all tables, including ActiveStorage tables - so the ids are random.

**Comment by adrianthedev** [comment]
I pushed a fix with #490 that should fix it. Do you mind having a look to see if the fix makes sense?

**Comment by jdbann** [comment]
Yeah, looks like it should do the job!

**Comment by adrianthedev** [comment]
Releasing `1.12.3`. Thanks for the help 🙏
