### ISSUE TITLE
[BUG] adding associated model in a view 

### ISSUE THREAD

**Issue by vitaly107** [avo-hq/avo#488]
1/ I have user model/resource that has_many user_tanks
2/ I have added `field :tanks, as: :has_many, through: :user_tanks` to user_resource as per Avo Docs
3/ then in a browser I access the user and I see a teacup loading icon and nothing is shown for the associated objects
4/ in a rails console I can see ` NoMethodError - undefined method hydrate for nil:NilClass` - not sure what that means and why is that called on nil class (when I do have a user and the user has a number of associated objects in the DB).

I also tried adding a different association as follows:
`field :tanks, as: :has_many, through: :user_tanks` 

Still the same - says loading and not showing the records despite the user object I am accessing does have associated tanks and user_tanks - that is in the console if I do `user.tanks` or `user.user_tanks` I can see the respective collections of tanks or user_tank objects.

Is that a bug or there is something I am missing?

NB: I have `has_many association` showing for my other model and that was done 2 months ago and still works, so it is strange that this is not working for my user model.

**Comment by adrianthedev** [comment]
Hi Vitaly.

Apologies for the delay. We were swamped with work these days.

Could you paste some more code from the `User` model and `UserResource`?
From the model file, I'm interested in the `has_many` and the corresponding `has_many` `through` relation.

**Comment by vitaly107** [comment]
`class User < ApplicationRecord
  include ActiveModel::Dirty

  belongs_to :user_status
  has_many :user_other_addresses
  has_many :billing_addresses, through: :user_billing_addresses, source: :address
  has_many :other_addresses, through: :user_other_addresses, source: :address
  has_many :user_informations
  has_many :user_tanks
  has_many :tanks, through: :user_tanks
  has_many :contacts

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :primary_phone_number

  before_save :format_primary_phone
  after_update :update_user_status, if: :user_creates_password?
  after_save :sync_with_mysql

  devise :database_authenticatable, :registerable,
         :recoverable, :confirmable, :trackable, :rememberable, :validatable
`

**Comment by vitaly107** [comment]
```
class UserResource < Avo::BaseResource
  self.devise_password_optional = true

  self.title = :email
  # If you regularly need access to a resource's associations, you can tell Avo to eager load those associations on
  # the Index view using includes. This will help you avoid those nasty n+1 performance issues.
  self.includes = [:user_status]

  self.search_query = lambda { |params:|
    scope.ransack(id_eq: params[:q], email_cont: params[:q], first_name_cont: params[:q], first_name_last: params[:q],
                  primary_phone_cont: params[:q], m: 'or').result(distinct: false)
  }

  # @titles_hash = FormOption.name_value_hash_for('title')

  field :id, as: :id
  field :email, as: :text, link_to_resource: true

  # field :title, as: :select, options: @titles_hash, display_value: true, placeholder: 'Choose the title'
  field :title, as: :select, options: ->(model: model, resource: resource, view: view, field: field) { FormOption.ordered_by_position.name_value_hash_for('title') }, display_value: true, placeholder: 'Choose the title'
  field :first_name, as: :text
  field :last_name, as: :text
  field :primary_phone, as: :text
  field :created_at, as: :date_time, picker_format: 'Y-m-d H:i', format: :db, time_24hr: true, readonly: true
  field :updated_at, as: :date_time, picker_format: 'Y-m-d H:i', format: :db, time_24hr: true, readonly: true

  field :sign_in_count, as: :number, readonly: true
  field :last_sign_in_at, as: :date_time, readonly: true
  
  field :user_tanks, as: :has_many
end
```

**Comment by vitaly107** [comment]
and this results in this
![Screenshot 2021-08-11 at 10 34 12](https://user-images.githubusercontent.com/67646688/129006173-6f0226b1-fa82-4ccc-ae0e-6adc9c97ac82.png)

**Comment by vitaly107** [comment]
and this is what I have in the rails console
![Screenshot 2021-08-11 at 10 35 43](https://user-images.githubusercontent.com/67646688/129006383-98b3a727-08d5-43fe-99e7-c50c49520b4a.png)

**Comment by vitaly107** [comment]
as stated below it works with other models association, that I implemented a month ago. so I do not know if it is a bug in new avo version (1.11.6) or if there is something peculiar in the User model (such as Devise gem connection). another thing is that I tried other associations in avo view instead of `field :user_tanks, as: :has_many` and none worked - same `hydrate` error in the console.

**Comment by adrianthedev** [comment]
Do you have a resource for `user_tanks`? Can you post that one as well please?

**Comment by vitaly107** [comment]
ah, I do not have  a n avo resource for `user_tanks`.  I will create that and see, I did not create that as I had no intention to manage that directly in avo - only through users.

**Comment by adrianthedev** [comment]
Got it.

I'll close this issue then.
