### ISSUE TITLE
[BUG] cannot access custom tool/dashboard

### ISSUE THREAD

**Issue by vitaly107** [avo-hq/avo#489]
1/ created a custom tool- dashboard
2/ then accessing it here https://localhost:3016/uk/bj-admin/dashboard
2/ I am getting an error `undefined method `join' for nil:NilClass` in 

actionpack (6.0.3.6) lib/action_dispatch/routing/routes_proxy.rb line 65
this was something discovered and reported long ago but I still cant access it even after upgrading to Avo v.1.11.6

my routes:
`scope :uk do

    scope 'bj-admin' do
      get 'dashboard', to: 'avo/tools#dashboard'
    end

    scope module: 'avo' do
      post '/pages/:id/image_upload', to: 'pages#create'
    end

    devise_for :users,
               controllers: {
                 sessions: 'sessions',
                 registrations: 'registrations',
                 confirmations: 'confirmations',
                 passwords: 'passwords'
               },
               path_names: {
                 sign_in: 'login',
                 sign_out: 'logout',
                 sign_up: 'register',
                 edit: 'profile'
               }
               end`

In Avo initialiser I have  `config.root_path = '/uk/bj-admin`

so please can we have a working solution when Avo is located under some namespace. many thanks!

**Comment by adrianthedev** [comment]
Hi Vitaly,

I think you should play around with the routes a bit. Where is the Avo engine mounted? I can't see it in your routes.

This is how I have it set-up:

```ruby
    scope :admin do
      get "dashboard", to: "avo/tools#dashboard"
    end

    mount Avo::Engine, at: '/admin'
```

So if I go under `/admin` I get to Avo root and `/admin/dashboard` I go into the new dashboard page inside Avo.

Can you try this?

```ruby
# Instead of this
scope 'bj-admin' do
  get 'dashboard', to: 'avo/tools#dashboard'
end

# try this
get '/uk/bj-admin/dashboard', to: 'avo/tools#dashboard'	
```

**Comment by vitaly107** [comment]
Thanks, if I change as above the I am getting some incompatibility with Friendly ID gem (that is now setup according to AVO docs)
![Screenshot 2021-08-11 at 10 50 17](https://user-images.githubusercontent.com/67646688/129008708-b5980284-da98-4873-a3ba-9509bea70cf5.png)

**Comment by vitaly107** [comment]
not sure why pages_controller is invoked - probably because I have this line down my routes file:
` get ':slug', to: 'pages#show'`
but I need that to make pages URLs SEO friendly

**Comment by vitaly107** [comment]
OK, this is what I tried:

```
mount Avo::Engine => Avo.configuration.root_path
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root to: redirect('/uk'), as: :redirected_root

  resources :mob_app_configs

  get 'home/loggedout', to: 'home#loggedout', as: :logout
  get 'oauth/callback', to: 'oauth#callback', as: :oauth_callback

  scope :uk do

    # scope 'bj-admin' do
    #   get 'dashboard', to: 'avo/tools#dashboard'
    # end

    get 'bj-admin/dashboard', to: 'avo/tools#dashboard'
```

**Comment by vitaly107** [comment]
and this what I got:
![Screenshot 2021-08-11 at 11 04 59](https://user-images.githubusercontent.com/67646688/129010773-9c53252a-4d8b-4454-b99c-bd92cc60434a.png)

**Comment by vitaly107** [comment]
I also tried moving that dashboard route out of uk scope and adding uk folder to the route itself:
```
 get '/uk/bj-admin/dashboard', to: 'avo/tools#dashboard'

  scope :uk do

    # scope 'bj-admin' do
    #   get 'dashboard', to: 'avo/tools#dashboard'
    # end
```

**Comment by adrianthedev** [comment]
Hmmm, I can't figure out why it isn't working.

TBH, this doesn't seem like a bug with Avo, but with Rails routing and the localization gem.

Please set up a repo with the same scenario and install instructions so I can clone on my machine and investigate.

**Comment by adrianthedev** [comment]
Any news on this? Can I close the issue?
