### ISSUE TITLE
[BUG] Custom Field doesn't work

### ISSUE THREAD

**Issue by him-wtag** [avo-hq/avo#495]
### Describe the bug
Custom field doesn't work.

### Steps to Reproduce
1. Generate a custom text field: `bin/rails generate avo:field custom_text`
2. Use it for a string column inside resource: `field :name, as: :custom_text`
3. Check the view for that resource. 

### Expected behavior
The text field should render using the custom field.

### Actual behavior
The column disappears from resource view.

### System configuration
**Avo version**: 1.12.2

**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2

**Comment by adrianthedev** [comment]
I just tested the functionality now with `1.12.0`. 
Please restart the server so the app can register the new field and let me know if that fixed it. If not, I'm glad to jump on [a call](https://calendly.com/adrianthedev) to straighten this out.

**Comment by Santho07** [comment]
> I just tested the functionality now with `1.12.0`.
> Please restart the server so the app can register the new field and let me know if that fixed it. If not, I'm glad to jump on [a call](https://calendly.com/adrianthedev) to straighten this out.

Thanks a lot for your availability and help. ( This is my another account. )

I have tested it in another dummy project and it is the same behaviour. Restarting the app doesn't help. Can you please check this PR - https://github.com/Santho07/mini-twitter/pull/8/files to see if I am doing anything wrong?

I also booked a call with you if not solved with the link you have provided.

**Comment by adrianthedev** [comment]
Circling back to let you know we managed to reproduce the issue under rails `6.1`. This doesn't happen with `6.0`.

What's happening:

The field is named `custom_text`. The field class is `Avo::Fields::CustomTextField`. The view_components have a class of their own `Avo::Fields::CustomTextField::ShowComponent`.

Not sure why, but under 6.1 there's a conflict with the class name, and can't find de class `Avo::Fields::CustomTextField` but finds the module from `Avo::Fields::CustomTextField::ShowComponent`.

Currently looking for a fix. If you have any ideas, they are greatly appreciated.

**Comment by Santho07** [comment]
Thanks! Hope we will find a fix a soon.

**Comment by adrianthedev** [comment]
@Santho07 I found out what the issue is 🤦‍♂️

You need to specify the license to 'pro' in `config/initializers/avo.rb` (`config.license = 'pro'`)

Custom fields are a part of the `pro` license.

Let me know if that fixes the issue for you.

**Comment by him-wtag** [comment]
Glad that you find the issue. Yes updating the license to pro solves the problem with custom field. I think it will be better for future users if it is mentioned in the doc if it is a pro feature or not.

On another note, currently, is it technically possible to render video using custom field? I tried with the license ( 'pro' ) but it doesn't render the video.

![image](https://user-images.githubusercontent.com/67682207/129044273-54d79319-0088-4c57-b3c8-982e2a1218ab.png)
This is the screenshot of the code. I was expecting to render the video player for the content identifier value. The code shown in the screenshot belongs to the video player custom field. The code is generated inside html but not showing in the view. Maybe i need to tweak the assets in some way? Thanks

**Comment by him-wtag** [comment]
Yes, the <video> tag could render the video inside custom field. I am closing the issue.

Really appreciate your help and support. Wising all the best for Avo & Thanks a lot.

**Comment by adrianthedev** [comment]
For sure! Anytime!
