### ISSUE TITLE
[FEATURE] Support search by placeholder or help text

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#496]
### Describe the feature
We do support search by three attributes, we've to educate our customer about the search fields. Instead, if we have a placeholder or text to describe all the search fields in UI then it would be helpful to improve user expereince. 

Below are my ransack query and I'm quite not sure how to display in UI that we support multiple search attributes. 

```ruby
 self.search_query = lambda { |params:|
    scope.ransack(primary_investor_cont: params[:q],
                  second_investor_cont: params[:q],
                  third_investor_cont: params[:q],
                  account_id_eq: params[:q],
                  m: 'or')
         .result(distinct: false)
  }
  ```

**Comment by adrianthedev** [comment]
So, as I understand it, the missing piece here is highlighting to the user in the interface how the search query is being done behind the scenes?

**Comment by santhanakarthikeyan** [comment]
Yes @adrianthedev

**Comment by adrianthedev** [comment]
Got it👌Let us think of a good way to signal that. We need to make sure all the resources are signaled in a proper way.

**Comment by mihaimdm22** [comment]
Hey @santhanakarthikeyan 

Version 1.12.4 brings this functionality.

Please check the [docs](https://docs.avohq.io/1.0/search.html#configure-the-search-result) for this.

Let me know if you have additional questions!

Cheers! - Avo Team
