### ISSUE TITLE
[BUG] association display issue

### ISSUE THREAD

**Issue by vitaly107** [avo-hq/avo#497]
I have a model 
```
class UserTank < ApplicationRecord
  belongs_to :tank
  belongs_to :user
  belongs_to :billing_address, class_name: 'Address', optional: true, foreign_key: 'billing_address_id'
```

This give me an opportunity to do 
`UserTank.first.billing_address` in the console

UserTanks table has billing_address_id attribute

so now if I add:

`field :billing_address_id, as: :belongs_to, link_to_resource: true` to user_tank_resourse this cause issue in a view where I can see a teacup loading icon instead of any user_tanks and in the console I have

` NoMethodError - undefined method `foreign_key' for nil:NilClass`

I do not expect this  as the virtual association works fine and I can run `UserTank.first.billing_address` in the console (or find any user_tank object and ask it `.billing_address` and it will respond.

So an I doing something wrong or avo has abug working with virtual associations like the one above?

How should we display that association in an admin view then?

**Comment by adrianthedev** [comment]
I think it should be `field :billing_address, as: :belongs_to, link_to_resource: true`. `billing_address` not `billing_address_id`.
Does that fix your issue?

**Comment by adrianthedev** [comment]
Where is the first screenshot taken from? Is it from the `User` show view? If so, then, it's designed not to show that column. 

Ex: If you're on the `John Doe` view page, all values in that column would be `John Doe`, and it's kind of redundant.

It's a bit difficult for us to respond when all of this information is taken out of context.
The best way to get help, from our experience, is to reproduce the scenario in a different repo. 
It's a good occasion for the issuer to understand the problem better. Usually the issuer figures out the solution after reproduction.
