### ISSUE TITLE
[BUG] Getting Avo HQ Error due to request timeout

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#498]
### Describe the bug

Can we not show `Avo HQ Error` when there is a timeout? 

<img width="213" alt="Screenshot 2021-08-17 at 11 39 19 AM" src="https://user-images.githubusercontent.com/35058248/129672983-e2948566-911f-415f-a06d-60b83f137fe4.png">

**Comment by adrianthedev** [comment]
Yes, we could add a config option to not show that banner.

**Comment by mihaimdm22** [comment]
Hey @santhanakarthikeyan 

Version 1.12.4 brings this fix.

Please check the [docs](https://docs.avohq.io/1.0/licensing.html#configure-display-of-license-request-timeout-error) for this.

Let me know if you have additional questions!

Cheers! - Avo Team
