### ISSUE TITLE
[Feature] Signal user about filters

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#501]
There is no way to figure out `filter` has been applied. Can we have a different colour scheme or text when filters are applied?

**Comment by mihaimdm22** [comment]
Hi @santhanakarthikeyan 

We worked on this and it's released with version 1.13. Thanks for suggesting this!
![Screenshot 2021-08-30 at 14 00 49](https://user-images.githubusercontent.com/23171533/131331772-ecbc2aab-5a02-4bb6-a33c-fcd91526b3cf.jpg)

Let us know if you need further help. Cheers!
