### ISSUE TITLE
[BUG] The action modal can only be opened once per page load

### ISSUE THREAD

**Issue by notnotdrew** [avo-hq/avo#505]
### Describe the bug
After the action modal is opened, after it is closed (either by canceling or running the action), it fails to open again.

### Steps to Reproduce
1. Go to a resource page
2. Click on actions
3. Select an action
4. Cancel the action
5. Click on actions again
6. Select the action again
7. The action modal does not open

### Expected behavior
After closing the modal, the action modal should open on subsequent attempts.

### Actual behavior
After closing the modal, the action modal does not open on subsequent attempts.

### System configuration
**Avo version**: 1.13.1

**Rails version**: 6.1.3

**Ruby version**: 2.6.6

### Screenshots

https://user-images.githubusercontent.com/7977907/132386014-ec56b4c6-20a8-4181-adc0-48191a2aabfe.mov

**Comment by adrianthedev** [comment]
Hey Drew,

Apologies for missing this notification. I see the issue on avodemo too. We don't have a lot of bandwidth to fix this right now. 

I applied "help wanted" label to this issue. Maybe someone else can give a hand and check it out.

Thank you,

**Comment by adrianthedev** [comment]
@notnotdrew can you check with the latest version of Avo and let me know if the issue is fixed for you too?

![](https://i.gyazo.com/bffa1e49886e3f828d5f8f77e670ff18.gif)

**Comment by notnotdrew** [comment]
@adrianthedev updated to 1.19 and it is resolved for us! Thank you! 👏🏻
