### ISSUE TITLE
[BUG] Sidebar label does not uses resource plural_name

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#513]
### Describe the bug
Sidebar label does not uses resource plural_name

### Steps to Reproduce
1. Create a resource with plural_name method
```ruby
class RoleResource < Avo::BaseResource
  self.title = :name
  self.includes = []

  field :id, as: :id
  field :name, as: :text

  def plural_name
    'Funções'
  end

  def name
    'Função'
  end
end

```
2. Go to avo admin
3. Shows another name in sidebar
![Screenshot_2](https://user-images.githubusercontent.com/43936240/133627579-41764cb4-efe5-4822-b986-2791942d87e2.png)

### Expected behavior
Plural name shows in sidebar

### Actual behavior
Shows resource.name.pluralize.humanize in sidebar

### System configuration
**Avo version**: 1.11.6

**Rails version**: 6.1.4

**Ruby version**: 2.7.2

Is a very small change in this piece of code:
```ruby
# avo/sidebar/sidebar.html.erb
<%= render Avo::NavigationLinkComponent.new label: resource.name.pluralize.humanize, path: resources_path(resource.model_class) %>
```
Do you think is better uses `resource.plural_name` with humanize or not?

**Comment by adrianthedev** [comment]
Yeah, sure! PR's are most welcomed!

I'm more than happy to help you navigate the codebase so let me know how I can help.

**Comment by PedroAugustoRamalhoDuarte** [comment]
Closed: (https://github.com/avo-hq/avo/pull/515)
