### ISSUE TITLE
[Feature] Add selectable column option on index page

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#514]
I'm looking for an option to exclude few columns on the index page. I'm not taking about `hide_on` it is more specific to selective columns to be pulled from DB instead of all columns. 

### Why is this required?

We have a table where we store requests and responses which is a JSON column and it consumes a lot of space. Avo by default pulls all the columns and response time is very poor when we pull all the columns. 

We need a `selectable_column` option only specific to the index page. 

### Reference
Ref: https://activeadmin.info/3-index-pages/index-as-table.html

**Comment by adrianthedev** [comment]
Does adding a [custom query scope](https://docs.avohq.io/1.0/customization.html#custom-query-scopes) would help? Can you manipulate the query that way?

**Comment by santhanakarthikeyan** [comment]
Can we apply custom queries only for index action? because I want to show these attributes on the show page.

**Comment by adrianthedev** [comment]
I was under the impression you want to hide something from index. But yeah, you can use 'resolve_find_scope' for the show view.

**Comment by adrianthedev** [comment]
You can also use computed fields to show other fields on the show page.

**Comment by santhanakarthikeyan** [comment]
> You can also use computed fields to show other fields on the show page.

@adrianthedev It's a good idea, i can use this approach. I'm  facing another issue related to scope queries, below are my code

```ruby
self.resolve_query_scope = ->(model_class:) do
  model_class.select(:id, :fp_id, :controller_action, :url, :soap_action, :updated_at).order(id: :desc)
end
```

The above code generated below SQL query. As you can see `created_at` order clause was also added. Is there a way i can get rid of `created_at` order by clause? because it's slowing performance. 

```sql
 BseLog Load (51495.3ms)  SELECT "bse_logs"."id", "bse_logs"."fp_id", "bse_logs"."controller_action", "bse_logs"."url", "bse_logs"."soap_action", "bse_logs"."updated_at" FROM "bse_logs" ORDER BY "bse_logs"."id" DESC, bse_logs.created_at desc LIMIT $1 OFFSET $2  [["LIMIT", 24], ["OFFSET", 0]]
```

**Comment by adrianthedev** [comment]
Hmm, I don't think you can do that at the moment. The `created_at` will be replaced if a user [tries to sort by another column](https://github.com/avo-hq/avo/blob/master/app/controllers/avo/base_controller.rb#L40), but you can't remove it at the moment.

If you want to create a PR to add this functionality, I'm more than happy to guide you through the codebase.

**Comment by santhanakarthikeyan** [comment]
@adrianthedev Oops, I don't have free time to contribute, sorry.
