### ISSUE TITLE
[BUG] Custom tool navigation broken

### ISSUE THREAD

**Issue by TheFehr** [avo-hq/avo#516]
### Describe the bug
The Resources navigation items are broken under a custom tool

### Steps to Reproduce
1. Add a custom tool
2. Open it
3. Press any other navigation item
4. See nothing new because the tool is still rendered

### System configuration
**Avo version**:  v1.14.0 

**Rails version**: 6.0.4.1

**Ruby version**: 2.7.4p191

### Additional context
Resulting url after press on resource navigation item is in following format: https://tld.example/avo/toolname.resourcename

**Comment by TheFehr** [comment]
@adrianthedev Any updates on this?

**Comment by adrianthedev** [comment]
I thought that was the answer and the fix. Sorry about that.

So, it seems that those helpers break the links? So, why do you need to add those helpers?

**Comment by adrianthedev** [comment]
> to use path helpers for my custom diagrams on the dashboard.

Got it. Have you tried adding `main_app.` to the link helpers?

Like if you have some helpers like `diagram_path` did you try `main_app.diagram_path`? It's how rails deals with links in engines.

**Comment by TheFehr** [comment]
And then I would not need to add the helper by hand?

I will give this a try tonight, I did not think of searching for path helpers and engines my guess was it was due to the component.
I will update you once I managed to give it a try.

**Comment by adrianthedev** [comment]
Sure! Thanks! Let me know how it goes.

**Comment by adrianthedev** [comment]
And yes. You wouldn't have to add those helpers.

**Comment by TheFehr** [comment]
Works like a charm. Thanks a lot
