### ISSUE TITLE
[BUG] The TextFilter can not filter Unicode string

### ISSUE THREAD

**Issue by luonet** [avo-hq/avo#533]
### Describe the bug
I noticed you have released a new feature"text filter". Great job! That's what I've expected for long time!  Thanks!
But I found the text filter could only filter ASCII characters, and would not work on Unicode string like Chinese.

### Steps to Reproduce
1. Following the docs.avohq.io, create a NameFilter < Avo::Filters::TextFilter.
2. Create two model with names "谢谢你们！❤️" and "Thank you!❤️"
3. Use the text filter，you can filter with "Thank", but can not with "谢谢" or "❤️".

### System configuration
**Avo version**:
1.16.2

**Rails version**:
6.1.4.1

**Ruby version**:
3.0

**Comment by adrianthedev** [comment]
Hmmm... I don't know how to answer this issue. Is this really an issue with Avo? I mean... what happens when you have a regular Rails route and send that payload to a ransack query? Would that find the records or not?

**Comment by luonet** [comment]
Yes, I think it's an issue within the TextFilter frontend. I'm not experienced in frontend so I can not find the root cause.

The ransack works perfect with the Unicode string search.

**Comment by luonet** [comment]
I've found the root cause.

In the `app/packs/js/controllers/filter_controller.js`,
The filter base class use `btoa` method to encode filter params.
But it will raise an error when handling Unicode string. So the request will never send to server side.

I carefully read the solutions suggested by Stackoverflow, MDN, and base64.guru,
and made a pull requst: https://github.com/avo-hq/avo/pull/543/files
It might be the best solution I knew.

You can check the details in:
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
https://developer.mozilla.org/en-US/docs/Web/API/btoa#unicode_strings
https://base64.guru/developers/javascript/examples/unicode-strings

Tested in my local environment, and the bug seems to be fixed.

**Comment by luonet** [comment]
#543

**Comment by luonet** [comment]
Fixed in version 1.17.1.
Close issue.
Thanks.

**Comment by adrianthedev** [comment]
Thank you for your contribution!
