### ISSUE TITLE
[BUG] "Could you help us improve this page?" leads to 404

### ISSUE THREAD

**Issue by vfonic** [avo-hq/avo#545]
### Steps to Reproduce

1. Visit any Avo documentation page. For example: https://docs.avohq.io/1.0/authentication.html
2. Scroll down to the bottom and click on: "Could you help us improve this page?"

### Expected behavior

There's publicly visible GH repo.

### Actual behavior

GitHub 404 page is displayed.

This could be because the documentation project is private.

**Comment by adrianthedev** [comment]
Fixed with https://github.com/avo-hq/docs/commit/a0baeebd8e0b457c2c11e8d375643e3e06a1ef6b

Thanks for reporting.
