### ISSUE TITLE
[BUG] Avo assumes `current_user` and `User` model

### ISSUE THREAD

**Issue by vfonic** [avo-hq/avo#546]
### Describe the bug

I'm setting up Avo gem for the first time ever.
I added Devise gem and set up `AdminUser` model and authentication as follows (in `config/routes.rb`):

```rb
  devise_for :admin_users
  authenticate :admin_user do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
```

In `config/initializers/avo.rb`, I've also set this config option:

```rb
  config.current_user_method = :current_admin_user
```

This shows current admin user's email address in the top-right corner of Avo interface.

However, it doesn't render the arrow down nor the "Sign out" in the dropdown (there's no dropdown).

I figured that I can eject profile dropdown and, after having done that, I noticed that all the checks refer to `user`, for example: 

```rb
main_app.respond_to?(:destroy_user_session_path)
```

In order to make this work, I've changed it to:

```rb
main_app.respond_to?(:destroy_admin_user_session_path)
```

I assume it would be better if there would be a way to specify the `user` method in the configuration and if that configuration value would be used throughout. Something similar to: `config.current_user_method = :current_admin_user`.

Perhaps:

```rg=b
config.current_user_resource_name = 'admin_user'
```

**Comment by adrianthedev** [comment]
Yup. That makes sense!
I don't think we can tackle this issue for the next week or so. Do you think you could try to make a PR for this feature?

**Comment by vfonic** [comment]
Unfortunately, I'm also swamped this and next week. :/

**Comment by adrianthedev** [comment]
No worries. We'll figure something out.
