### ISSUE TITLE
Improved Select for Belongs To fields

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#589]
### Discussed in https://github.com/avo-hq/avo/discussions/574

<div type='discussions-op-text'>

<sup>Originally posted by **nulldotpro** January 17, 2022</sup>
Currently, the `belongs_to` field is just a dropdown displaying the titles of all the resources that the user has permission to see. In my app, this could be thousands of options. It would be great if we could have a fuzzy search of some kind to make the selection less tedious.</div>

**Comment by Bar2d2** [comment]
I agree! That would be great to have more possibilities in using belongs to field. As you said it could be thousands of options.

**Comment by adrianthedev** [comment]
Will probably re-use the search modal.
