### ISSUE TITLE
[BUG] Search not working with uncountable resource

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [avo-hq/avo#600]
### Describe the bug
Search not working with uncountable resource

### Steps to Reproduce
1. Create a uncoutable model like fish `rails g model fish name:string`
1. Create avo resource `rails generate avo:resource Fish`
3. Adds serach_query to resource: 
```ruby
class FishResource < Avo::BaseResource
  self.title = :name
  self.includes = []

  self.search_query = ->(params:) do
    scope.ransack(name_eq: params[:q], m: "or").result(distinct: false)
  end

  field :id, as: :id
  field :name, as: :text
end

```
4. Go to fish resource page and try to search for a fish
5. Receive the error:
```
Started GET "/avo/avo_api/fish_index/search?q=" for ::1 at 2022-01-21 16:04:12 -0300
Processing by Avo::SearchController#show as */*
  Parameters: {"q"=>"", "resource_name"=>"fish_index"}
Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 1322)


  
ActionController::RoutingError (No route matches):
```

### Expected behavior
Search work well

### Actual behavior
Return error above

### System configuration
**Avo version**: 1.18.2

**Rails version**: 6.1.4.4

**Ruby version**: 2.7.2

### Test repo
https://github.com/PedroAugustoRamalhoDuarte/avo-test-uncountable

**Comment by adrianthedev** [comment]
Fixed by https://github.com/avo-hq/avo/pull/601 Can you try it @PedroAugustoRamalhoDuarte?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Thank you, its working very well!!
