### ISSUE TITLE
Create new button on has_many relationship.

### ISSUE THREAD

**Issue by emnimata** [avo-hq/avo#606]
I have two has_many relationships, I want to be able from the parent div to add new has_many objects, somehow my first has_many works like that, I am able to render the new button from the parent view page, but on the second has_many only the 'attach resource' button is rendered and not the 'create resource' button.
My second resource is an STI model if that makes a difference.

<img width="1098" alt="Screen Shot 2022-01-24 at 7 18 07 PM" src="https://user-images.githubusercontent.com/97155645/150841701-a83d729a-137c-4c6f-9300-ce4992a772da.png">

**Comment by adrianthedev** [comment]
I'm AFK this week so I can't test it. 
Do you have a pundit Policy for the comment model?

**Comment by emnimata** [comment]
Thanks for your response, I don't yet have any policies, what should be the expected behavior, should has_many fields be provided with the new resource button?

**Comment by adrianthedev** [comment]
Hmmm. I'll have to check it out by myself. Thanks for the STI detalis.

**Comment by adrianthedev** [comment]
Hey @emnimata 

I replicated the scenario like so: 

```ruby
# app/models/user.rb
class User < ApplicationRecord
  has_many :people
  has_many :spouses
end

# app/models/person.rb
class Person < ApplicationRecord
  has_many :spouses, foreign_key: :marriage_person_id
end

# app/models/spouse.rb
class Spouse < Person
  belongs_to :person, foreign_key: :marriage_person_id, optional: true
end

# app/avo/resources/user_resource.rb
class UserResource < Avo::BaseResource
  field :people, as: :has_many
  field :spouses, as: :has_many
end
```

I get the create button for both resources.

![image](https://user-images.githubusercontent.com/1334409/151759513-9976c071-9d8c-411b-875f-33f91b3f5637.png)

Is this scenario the same as yours?

**Comment by emnimata** [comment]
```ruby 
class Emnima < ApplicationRecord
has_many :emnimas_users, dependent: :nullify
has_many :clients, through: :emnimas_users, class_name: 'Client'

class Client < User
  has_many :emnimas_users, dependent: :nullify, foreign_key: :user_id, inverse_of: :clients
  has_many :emnimas, through: :emnimas_users, class_name: 'Emnima', foreign_key: :user_id, inverse_of: :clients
end

class ClientResource < Avo::BaseResource
self.model_class = ::Client

class EmnimaResource < Avo::BaseResource
field :clients, as: :has_many,  through: :emnimas_users
```

**Comment by adrianthedev** [comment]
Ok, I see. It's a `has_many` `through` association. I'll look into it.
