### ISSUE TITLE
Remove create resource option

### ISSUE THREAD

**Issue by vital14** [avo-hq/avo#607]
I would like to know if it is possible to remove the option to create resources and keep only edit and delete, i need it to my system

**Comment by nulldotpro** [comment]
@vital14 https://docs.avohq.io/1.0/authorization.html#authorization

**Comment by adrianthedev** [comment]
Yup @vital14. The [create](https://docs.avohq.io/1.0/authorization.html#create) method is what you need.

Please let us know if that fixes the issue.
