### ISSUE TITLE
[BUG] Resources with more than one name aren't being handled ok.

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#610]
### Describe the bug

When you save a resource with two names (`TeamMembership`) the form attribute should be `team_membership` but it's `teammembership`

### Steps to Reproduce
1. Go to https://avodemo.herokuapp.com/avo/resources/team_memberships
2. Click on a record
3. Click edit
4. Click save
5. See error

### System configuration
**Avo version**:
1.19.0

**Rails version**:

**Ruby version**:

### Screenshots

![image](https://user-images.githubusercontent.com/1334409/151768381-175ffc5c-efda-407b-bdfb-3e43019e4747.png)

![image](https://user-images.githubusercontent.com/1334409/151768450-3155b68e-1f8a-40a1-ba9d-9b5b7a04b1a3.png)

**Comment by notnotdrew** [comment]
@adrianthedev++ thanks for this!

**Comment by adrianthedev** [comment]
Anytime! I'll release a new version this week.
