### ISSUE TITLE
Associated informations should be visible on demand

### ISSUE THREAD

**Issue by santhanakarthikeyan** [avo-hq/avo#623]
Displaying associated entries can be on a tab layout instead of listing layout design, this will bring in on-demand access.

With the current design, the problem is it loads all associated entries even though the user may not need that information.

**Comment by santhanakarthikeyan** [comment]
We do show 4 associated information on a show page, we have to increase that further and it is really difficult because a user has to scroll through a lot of sections, and performance-wise as well it is not good.

**Comment by adrianthedev** [comment]
Hey,

This issue has been raised before and we pinned it down using [this discussion](https://github.com/avo-hq/avo/discussions/580). We agree that it may not be the best interface and it can be improved. There are also performance issues that we're aware of (loading data that might not be necessary).

We are in the process of revamping the default theme. We're working with our designer to improve that.
So, we'll tackle this with the next iteration of themes. To give you an ETA, it's probably land early March.
