### ISSUE TITLE
`attach_RELATION` is broken for some model names (hide attach/detach buttons)

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#634]
Similar to `attach_RELATION`

**Comment by adrianthedev** [comment]
This is [supported](https://docs.avohq.io/1.0/authorization.html#associations) now. There is a bug because we use the model name and we should use the association name given to the resource by the user.

 [ ] Also check in other places for this kind of code.

The [bad code](https://github.com/avo-hq/avo/blob/main/app/components/avo/resource_component.rb#L15)
```ruby
method_name = "#{policy_method}_#{@reflection.name.to_s.underscore}?".to_sym
```

**Comment by jony1993** [comment]
Hi Adrian,

If you try to edit an namespaced model like 'Course::Link' you get also following error:
`method=PUT path=/new/resources/course_links/9 format=turbo_stream controller=Avo::CourseLinksController action=update status=400 error='ActionController::ParameterMissing: param is missing or the value is empty: course_link'
Creating and destroying still works.

Maybe that error is also related to this?

**Comment by adrianthedev** [comment]
> Hi Adrian,
> 
> If you try to edit an namespaced model like 'Course::Link' you get also following error:
> 
> ```
> method=PUT path=/new/resources/course_links/9 format=turbo_stream controller=Avo::CourseLinksController action=update status=400 error='ActionController::ParameterMissing: param is missing or the value is empty: course_link
> ```
> 
> Creating and destroying still works.
> 
> Maybe that error is also related to this?

That error was fixed in `1.19.1.pre.9` and will be released tomorrow in `1.20`.

**Comment by jony1993** [comment]
Hi Adrian,

I'm already using 1.19.1.pre.9 and here I have the same bug...

**Comment by adrianthedev** [comment]
Ok @jony1993 . Let me check before releasing. I presume that `Course::Link` `belongs_to` `Course` (or is it `Course::Course`?)?

**Comment by jony1993** [comment]
@adrianthedev 
Thanks :)

Yes correct. `Course::Link` belongs to `Course`.
