### ISSUE TITLE
Date field incorrectly populated in edit form.

### ISSUE THREAD

**Issue by nulldotpro** [avo-hq/avo#658]
### Describe the bug
When a resource is edited that contains a `date` field, the value of that field is different from what is stored in the database - it's one day earlier. When I save a record with the `date` field set to February 14th and then try to edit that record, the same date field in the edit form is pre-populated as February 13th. This causes the date to backslide when I'm making changes to other attributes.

### Steps to Reproduce
1. Add a `date` field to a resource.
2. Save a new instance of that resource with the date set to February 14th.
3. Open the edit form on the resource
4. See that the date has backslid to February 13th.

### Expected behavior
The edit form should populate the date with the value stored in the database.

### Actual behavior
The edit form populates the date with the day before the value stored in the database.

### System configuration
**Avo version**: 1.20.1

**Rails version**: 6.1.4.4

**Ruby version**: 3.0.2

### Additional context
I am in "America/Chicago" timezone.

**Comment by adrianthedev** [comment]
I can't seem to replicate this bug on avodemo. Can you go [here](https://avodemo.herokuapp.com/avo/resources/users/38) and try to update the date? Does it work fine?

I'm wondering, **is that date field an actual date field in your DB**, or is it a time field (datetime/timestamp)? Because that might interfere with the actual date bc of how Avo updates the date to match the current user timezone.

**Comment by nulldotpro** [comment]
I have the same issue on the demo site you linked. And yes, it's an actual date field in my DB. No issue with date times because I can set the timezone as a field argument, which works great!

**Comment by adrianthedev** [comment]
Oh, got it "America/Chicago"

**Comment by nulldotpro** [comment]
It's the default UTC setup, yes.

**Comment by adrianthedev** [comment]
I managed to replicate the bug. Thanks! 

Fixing it this week and will cut a release ASAP.

**Comment by nulldotpro** [comment]
Awesome, thank you!
