### ISSUE TITLE
On creating has_many item: error message is shown and user is not redirected back but item is beeing created

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#666]
### Describe the bug
When I try to create a has_many entry, I see following error
```
You might have missed something. Please check the form.
```
When I go back I see that the entry was created successfully

It was introduced in Avo Versio v 1.21.0. I double checked, it was working in 1.20.1

### Steps to Reproduce
1. Go to a model with a `has_many`relation
2. Click on `create`
3. Enter data and click on `create`
4. See error message "You might have missed something. Please check the form."
5. Go back and you see the entry

### System configuration
**Avo version**:
1.21.0

**Rails version**:

**Ruby version**:

**Comment by adrianthedev** [comment]
I got the same behavior and just merged https://github.com/avo-hq/avo/pull/665 😅

**Comment by adrianthedev** [comment]
Released https://rubygems.org/gems/avo/versions/1.21.1.pre.1. Can you give it a try?

**Comment by jony1993** [comment]
Seems to be working if its a normal `belongs_to`.

For polymorphic belongs_to it seems not to be working. See below the screenshot. There is "Choose an option" but you cannot choose anything because its readonly.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/11912368/154278563-ab921d42-16ea-45fb-94fd-71a7a27702e3.png">

**Comment by adrianthedev** [comment]
Got it. Checking

**Comment by jony1993** [comment]
Thanks :)

Maybe also https://github.com/avo-hq/avo/issues/660 is related to this error?

**Comment by adrianthedev** [comment]
Not sure. I believe not.

**Comment by jony1993** [comment]
Just as info:
If you try to edit an already existing entry, then the belong_to is filled and readonly, but on saving its shows also an error.

**Comment by jony1993** [comment]
@adrianthedev 
Seems not to be working on Avo v1.22.0

If you try to edit an already existing entry, then the belong_to is filled and readonly, but on saving its shows also an error.

After loading:
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/11912368/154939372-47cc7434-4c63-4ddd-869b-202fc0790f47.png">

After saving:
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/11912368/154939459-e1fb94cd-d0bd-4c19-997a-d9df09ec2c5a.png">

**Comment by jony1993** [comment]
Here an example of a resource/model where on "new" the belongs_to is not prefilled when is_searchable is true:

```
class Client < ApplicationRecord
  has_many :qualifications, class_name: "Client::Qualification", dependent: :destroy
end
```

```
class Client::Qualification < ApplicationRecord
  belongs_to :client
end
```


Resource:

```
class ClientResource < Avo::BaseResource
  field :qualifications, as: :has_many
end

```

```
class ClientQualificationResource < Avo::BaseResource
  self.model_class = Client::Qualification

  field :id, as: :id
  field :client, as: :belongs_to, searchable: true
end

```

**Comment by adrianthedev** [comment]
Hmm... It might be that the `ClientQualificationResource` has a namespaced model (`Client::Qualification`). trying to replicate and will get back to you.

**Comment by jony1993** [comment]
Mhm yes, but other namespaces models are working correctly...

**Comment by adrianthedev** [comment]
@jony1993 can you give [1.22.1.pre.2](https://rubygems.org/gems/avo/versions/1.22.1.pre.2) a run for it's paces?

**Comment by jony1993** [comment]
Thanks. Yes let me try :)

**Comment by jony1993** [comment]
@adrianthedev 
Belongs_to seems to be working now for all my scenarios :)

**Comment by adrianthedev** [comment]
Glad to hear that. Belongs to with all the scenarios was a PITA to build/fix.
I'm going to check it again and then cutting a release.
