### ISSUE TITLE
format_using should receive the view

### ISSUE THREAD

**Issue by darkhelmet** [avo-hq/avo#681]
### Describe the bug

I have a select field using an enum. I use `format_using` to translate the value for display. When I edit the resource, the select is on the wrong option, because the translated value is not in the enum options.

### Steps to Reproduce

```ruby
class Thing < ApplicationRecord
  enum category: { left: 'left', right: 'right' }
end

class ThingResource < Avo::BaseResource
  field :category, as: :select, enum: Thing.categories, format_using: ->(value) { value.upcase }
end
```

1. Create a `Thing`
2. Edit the thing
3. Might need to try saving it with left or right as the category, but it won't set back to the proper value since `'LEFT' != 'left'`

### Expected behavior

I would expect the form to populate with the correct value.

I would expect this for other field types as well. If I'm formatting a text field in some way for display, it shouldn't get formatted for the form.

### Actual behavior

The formatted value is used in the form, breaking the select field

### System configuration
**Avo version**: 1.21.0

**Rails version**: 7.0.2.2

**Ruby version**: 3.1.0p0

**Comment by darkhelmet** [comment]
A way around this currently is `format_using: ->(value) { view == :edit ? value : do_format(value) }`

**Comment by adrianthedev** [comment]
I see what you mean regarding formatting the value only on `show`. I'm wondering if other devs are using `format_using` on the `edit` view too. 🤔

**Comment by adrianthedev** [comment]
What would probably be best to pass in the view too to that block.

**Comment by adrianthedev** [comment]
I see there is a pretty good workaround for this so I'll close it for now.
