### ISSUE TITLE
Deleting an item from a key_value table deletes the wrong item

### ISSUE THREAD

**Issue by darkhelmet** [avo-hq/avo#682]
### Describe the bug

I edit an item with a `:key_value` field hooked up to a `jsonb` attribute, it has 2 entries. I delete the second one, and the first one disappears, leaving me with the second one.

### Steps to Reproduce

```ruby
class ThingResource < Avo::BaseResource
  field :tags, as: :key_value
end
```

1. Make a thing with 2 entries in the tags table
2. Edit the thing
3. Click the trash can icon on the second row
4. Observe the first row disappears

### Expected behavior
It should delete the row I clicked on

### Actual behavior
It deletes the first row. Haven't dived further into this, but I can reproduce this with 2 rows.

### System configuration
**Avo version**: 1.21.0

**Rails version**: 7.0.2.2

**Ruby version**: 3.1.0p0

**Comment by adrianthedev** [comment]
The `key_value` field has been designed to work with a regular string/text field. It works on the [demo app](https://avodemo.herokuapp.com/avo/resources/projects/38) with a text field.

What happens in Rails with the `jsonb` column? Does that cast the value to an object? I'll have to check it out.
If that's true, it might interfere with how the field works.
We might be able to check what kind of DB field it is and mitigate the issue in the field.

**Comment by darkhelmet** [comment]
Using the `jsonb` column in Postgres just results in it parsing the value to whatever JSON is in it, so it could be an object or array typically. The `key_value` field works properly as far as I can see. I've been using it just fine. I swear it worked before, but I think this is is a UI problem, not a server-side problem.

**Comment by adrianthedev** [comment]
Oh, ok. I'm a bit confused. So, does it work now fully (add, update, and delete rows) with `jsonb` or not?

**Comment by darkhelmet** [comment]
My models use the `jsonb` column type. I can create resources, edit them, add and update values in the `key_value` table, but when I actually delete a row, in the UI, it removes the first row in the table, not the one I click on. I say I swear it worked before because I think in a version before whatever I'm on now it worked fine (deleting a row) but I can't be sure.

**Comment by adrianthedev** [comment]
Got it! I'll try to reproduce it with a `jsonb` column myself.

Meanwhile, can you try the demo app [here](https://avodemo.herokuapp.com/avo/resources/projects/38) and tell me if the delete button works ok? I just want to rule out any front-end interference on your end.

**Comment by adrianthedev** [comment]
BTW, I dig your title "Software mechanic" 🙂

**Comment by darkhelmet** [comment]
The problem is reproducible on the demo app. I added 3 rows to a resource, save, the edit, click x icon on last row, first row deletes.

**Comment by adrianthedev** [comment]
Ok. got it! managed to reproduce it. Fixing it today.

**Comment by adrianthedev** [comment]
Released in https://github.com/avo-hq/avo/releases/tag/v1.22.3
