### ISSUE TITLE
Notification/Alert fired twice after saving on Index view

### ISSUE THREAD

**Issue by jony1993** [avo-hq/avo#687]
### Context

In 1.22.0 version notification is fired twice when updating/destroying a record

<img width="521" alt="image" src="https://user-images.githubusercontent.com/11912368/154928794-dd7710ed-63e4-41c4-b5e3-f875e40f324f.png">
 

### System configuration
**Avo version**:

**Rails version**:

**Ruby version**:

**Comment by adrianthedev** [comment]
Yup, I see it. Thanks. 
Trying to fix & release today.
