### ISSUE TITLE
Does not redirect on edit/delete

### ISSUE THREAD

**Issue by khris-p** [avo-hq/avo#741]
### Describe the bug
When I click on edit, it's stuck on the button spinner/bounce and does not redirect even if it persisted. Another one is when when it has a validation, it does not show up the error message and does not redirect as well. Same when deleting. Create works fine.

### Steps to Reproduce
1. Resource has the following fields:
`  field :id, as: :id`
` field :name, as: :text, required: true, sortable: true`
2. Click on 'edit' or 'delete'.
3. The spinner get stuck.

### Expected behavior
It should redirect to show after edit/delete.
It should show the error message if it does not pass validation.

### Actual behavior
It gets stuck on edit/delete with the spinner moving.

### System configuration
**Avo version**: 1.25.0
**Rails version**: 6.0
**Ruby version**: 3.0.2p107

### Screenshots
![Screen Shot 2022-03-24 at 7 16 09 AM](https://user-images.githubusercontent.com/90044824/159931666-e2911c17-78d9-4d80-9f9a-0270dff049da.png)
![Screen Shot 2022-03-24 at 7 26 55 AM](https://user-images.githubusercontent.com/90044824/159931677-767ad404-b8f4-4357-9825-4cf32e1a18c1.png)
<img width="1117" alt="Screen Shot 2022-03-28 at 6 38 41 AM" src="https://user-images.githubusercontent.com/90044824/160390247-d1b061ff-497f-435d-bb1d-b017590c82d4.png">

### Additional context
No errors on the console. Tried on Chrome, Safari & Firefox and resulted in the same behavior.
App uses hotwire, turbo and js (vue).

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @khris-p. I wasn't able to reproduce the issue. 
**Can you try v2.0 and see if it's still broken**? 
If it's still broken, let's set up a call where we can troubleshoot it together.

**Comment by khris-p** [comment]
Hello @adrianthedev, Yes, it's still happening. We actually upgraded to v2.0 with a pro license and still having the same issue.

**Comment by adrianthedev** [comment]
Got it. I sent a PM with a link to calendly. We'll figure it out!

**Comment by adrianthedev** [comment]
Hey @iainbeeston.

This has been fixed but it wasn't released as stable yet. Please try `https://rubygems.org/gems/avo/versions/2.1.2.pre1` (`gem avo, '2.1.2.pre1'` in your Gemfile). This pre-release should contain the fix.
I'll release 2.2.0 on Monday.

**Comment by iainbeeston** [comment]
Actually I've realised I have a different issue, so I've raised that separately #799 (sorry!)

**Comment by adrianthedev** [comment]
All good! Thanks for getting back to us. That's the most important thing.
