### ISSUE TITLE
ActiveRecord::UnknownAttributeReference (Query method called with non-attribute argument(s):)

### ISSUE THREAD

**Issue by rajaravivarma-r** [avo-hq/avo#763]
### Describe the bug

When the table name is specified for a model, with its schema, then it throws `ActiveRecord::UnknownAttributeReference` error.
 The line which causes it is app/controllers/avo/base_controller.rb:46. 
 `@query = @query.order("#{@resource.model_class.table_name}.#{@index_params[:sort_by]} #{@index_params[:sort_direction]}")`

### Steps to Reproduce
1. Create a model with `self.table_name` set to a table name with the schema.
```ruby
class Product < ApplicationRecord
  self.table_name = 'public.fund_details'
end
```
2. Create the associated `ProductResource` and `Avo::ProductsController`
3. Visit the `/products` page

### Expected behavior
* The page should list the products

### Actual behavior
* Throws ActiveRecord::UnknownAttributeReference (Query method called with non-attribute argument(s): "public.fund_details.created_at desc"):

### System configuration
**Avo version**: 1.23.0

**Rails version**: 6.1.4.6

**Ruby version**: 3.0.0

### Additional context
https://api.rubyonrails.org/v5.2/classes/ActiveRecord/UnknownAttributeReference.html

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
From [the docs](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-table_name) I think it's better to add the schema using `table_name_prefix` like so:

```ruby
class Product < ApplicationRecord
  self.table_name_prefix = 'public.'
  self.table_name = 'fund_details'
end
```

Can you do that for your model?

**Comment by rajaravivarma-r** [comment]
I tried it, but it didn't help. 

In fact, it wouldn't work because you are directly access `model_klass.table_name`, but the default `schema_search_path` for all other tables is different, so the table `fund_details` wouldn't even be available in that schema.

**Comment by rajaravivarma-r** [comment]
It doesn't work in my case because, the default `schema_search_path` is different for all other tables. 

I would say `ApplicationRecord.connection.schema_search_path = 'a_tenant_name'`, but the `users` table is available only in the `public` schema.

Let me know if that doesn't make sense I will create a sample app or something.

**Comment by adrianthedev** [comment]
I don't know anything about `schema_search_path`. Before you go out and create a sample app, do you have anything in mind that would help fix this issue with Avo?

**Comment by adrianthedev** [comment]
I'm thinking about splitting by `.` whatever we get in `table_name` and using the last part. WDYT?

``` ruby
@resource.model_class.table_name.split('.').last
```

**Comment by rajaravivarma-r** [comment]
1. Quick fix (but feels hacky): Wrap the whole string using `Arel.sql(...)`, as below
`@query = @query.order(Arel.sql("#{@resource.model_class.table_name}.#{@index_params[:sort_by]} #{@index_params[:sort_direction]}"))`

2. Is there a reason you are explicitly specifying the table_name? `@query = @query.order(@index_params[:sort_by] => @index_params[:sort_direction])` would just work fine right?

3. Create a PR to rails repo to change this regex, to match `"public.fund_details"."created_at" desc` on top of `"fund_details"."created_at" desc`. 😉 
```
/
          \A
          (
            (?:
              # "table_name"."column_name"::type_name | function(one or no argument)::type_name
              ((?:\w+\.|"\w+"\.)?(?:\w+|"\w+")(?:::\w+)?) | \w+\((?:|\g<2>)\)(?:::\w+)?
            )
            (?:(?:\s+AS)?\s+(?:\w+|"\w+"))?
          )
          (?:\s*,\s*\g<1>)*
          \z
        /ix
```

> I'm thinking about splitting by . whatever we get in table_name and using the last part. WDYT?

I don't think it will work, because specifying the `table_name` without a `schema` will look for the table in the current `schema_search_path`. This will lead to two things,
* The table may not be there in the current schema
* Find the table in a wrong schema

To add more clarity:
Postgres schemas are like Ruby module namespaces, 
```ruby
class Foo
  def self.hello
    puts 'Foo from global namespace'
  end
end

class Bar
  class Foo
    def self.hello
      puts 'Foo from Bar'
    end
  end
  
  puts Foo.hello  # Will print `Foo from Bar`. If the `table_name` is specified without the `schema`, it will look in the current namespace. We do not want this, when we want to actually call `::Foo.hello`
  puts ::Foo.hello # Will print `Foo from global namespace`
end

 puts ::Foo.hello # Will print `Foo from global namespace`
```

**Comment by rajaravivarma-r** [comment]
Update: I just checked, the regex has been updated in Rails 7, to accept schema. It will match `public.fund_details.created_at desc` (https://rubular.com/r/ZIvqHINrPpktQc) as well as `fund_details.created_at desc` (https://rubular.com/r/WTMOMB0R2lkkKw)

**Comment by adrianthedev** [comment]
The reason why we prepend the table name when ordering is to avoid conflicts when joining tables 'Post.include(:user).find(1)'. 

The solution we choose here should also be compatible with Rails 6.

**Comment by adrianthedev** [comment]
Ok. I'm AFK at the moment but will fix it somewhow tomorrow. 

Thanks for brainstorming this with me.

**Comment by rajaravivarma-r** [comment]
Happy to help in anyway 🙂 

For people with similar problem, I have done this abomination as a quick fix.
```ruby
  class ActiveRecord_Relation
    def order(dirty_sql)
      return super unless dirty_sql == 'public.fund_details.created_at desc'

      super(Arel.sql(dirty_sql))
    end
  end
```

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r. 
Could you make that sample app after all? It would help me understand your issue better.
I haven't used `schema_search_path` and I don't understand if this is actually an Avo issue or something that should be fixed in Rails. 

I'm a bit weary in introducing this change. Not sure if that will break something for other users. 
I also don't want to introduce some arbitrary mechanism that actually fixes a scenario that's not really "the Rails way".
Does that make sense?

Saying all that, I want to help you get the best of Rails and Avo.

**Comment by rajaravivarma-r** [comment]
Hi @adrianthedev, I can understand the way you feel about this.

Here, I have created a sample app https://github.com/rajaravivarma-r/avo-schema-demo. Please checkout the `avo-schema-demo` branch setup everything using docker.

When you visit `http://localhost:3000/`, you should see the error.

**Comment by rajaravivarma-r** [comment]
To address you other comments,
1. No, it will not break something for other users. You are just telling Rails that `I know what I'm doing, just consider this as SQL`.
2. I'm not sure, but it looks like it is "the Rails way" for the scenario.
3. Like I said, it is already fixed in Rails 7.

**Comment by adrianthedev** [comment]
Hey @rajaravivarma-r, thanks for the demo app.

I see better what you mean now. I was testing but only on the `public` schema and that's why the issue wasn't popping up for me.

Please try `https://rubygems.org/gems/avo/versions/2.1.2.pre1` and let me know if that fixes ti for you. What I did was to wrap everything in `Arel.sql()`. If that looks good to you too, I'll probably release it wrapped in `Arel` but only under a configuration flag like `use_unsafe_arel_queries` that will default to false, but you can turn it to true.

Again, thanks for the demo app and let me know if 2.1.2.pre1 works ok for your case.

**Comment by adrianthedev** [comment]
Closing for now. feel free to reopen it if it still persists.
