### ISSUE TITLE
Namespaced model_class maps derivation of controller name

### ISSUE THREAD

**Issue by yrashk** [avo-hq/avo#773]
### Steps to Reproduce
1. Have a resource with `model_class = SomeNamespace::Model`
2. Go to resource list

### Expected behavior

Works.

### Actual behavior

Get error

```
uninitialized constant SomeNamespace::Model Object.const_get(camel_cased_word) 
(uninitialized constant SomeNamespace::ModelsController)
```

(I expected it to be mapped by resource's class, not underlying model's class.)

### System configuration
**Avo version**: 2.1

**Rails version**: 7.0

**Ruby version**: 3.1

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hi.
That should work. 

Can you post a few more details regarding your issue? 
Actual error with line numbers.  The file location of that model. Is that an active record model?

**Comment by adrianthedev** [comment]
Hey @yrashk,

We pushed [some changes](https://github.com/avo-hq/avo/pull/795/) this week that might fix your issue. Can you try v2.2.1?

Also, if you have this model `SomeNamespace::Model` you should create also have this controller for your resource `SomeNamespaceModelsController` in `app/controllers/avo/some_namespace_models_controller.rb`.

Please keep me posted if this works.

Cheers,

**Comment by adrianthedev** [comment]
We talked about this on the call. 

I created [this](https://github.com/avo-hq/avo/discussions/846) discussion to keep the conversation open and for easier tracking.
