### ISSUE TITLE
Sidebar duplication after some error conditions.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#784]
### Describe the bug

Sometimes, when editing Avo resources, the entry for the resource will subsequently appear in the sidebar twice.

### Steps to Reproduce

This seems to happen after some particular type of error, although I'm having trouble coming up with a way to reproduce it.  When it happens, the only fix is to restart the Rails process.

Basically though, the way I encounter it is that I:

1. Begin working on my resource (or perhaps its associated model)
2. I screw something up
3. An exception is thrown
4. I fix the issue, and reload the page
5. The resource is now in the sidebar twice

### Expected behavior

Whatever state is used to derive the sidebar should be fully reset on code reloading.

### Actual behavior

State about sidebar configuration becomes poisoned.

### System configuration
**Avo version**: 2.0.0 for sure, possibly 2.1.1 as well.

**Rails version**: 7.0.2.3

**Ruby version**: 3.0.3

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Yes, I get those too sometimes as you said after you recover from an error. What I usually do after I get the duplicated items, I do another update to the resource file (add an empty line or something, save the file and remove it) and the duplication goes away. I think that's the time when Rails loads the resources one more time and figures out there's a duplicate.

Because it's only a development issue and happens sporadically, I haven't given it too much attention.

The autoloading of files, getting the `BaseResource` descendants, and the order in which to do that are a few of the issues that I personally struggled with, and hopefully will find someone (even paid contract) to help me fix them.

**Comment by MrJoy** [comment]
Interesting.  I wonder what I'm doing differently than you.  When I encounter it, no amount of changes to the resource fixes the issue.  It's only fixable with a restart.  My project is a from-scratch Rails 7 project, without Spring (and using Proshaft/cssbundling-rails/jsbundling-rails, although I don't know that that's materially relevant here).

Autoloading is a really thorny and complex issue and has been the bane of the Rails team surprisingly often.

And yeah, dev-only issue of minor significance.  I only even brought it up because it strikes me as the kind of thing where it may be a tip-of-the-iceberg thing.  Rather:  More significant pain points with the same root cause could exist, and might only emerge when the project begins to reach a broader audience.

(I may have a bit of twitchiness from my experiences with first Active Scaffold and then ActiveAdmin having some frustrating sharp corners baked into their architecture that both projects were too far into their lifecycle to really fix by the time I ever discovered them.  Take my feedback on this and other issues with an appropriately sized grain of salt.)

**Comment by adrianthedev** [comment]
Hmm... that's weird that it works differently on your end. Let me try it with some of our apps and see what results we get.
Still, I'd love not to have to restart the server every time. It's kind of a PITA to do and you get tired pretty quick. 

**I started to post on job boards to get some outside help for this autoloading issue.**

BTW, thanks for this eloquent display of your thoughts. I love reading your comments 😅  and feedback. Please keep it coming!

**Comment by adrianthedev** [comment]
This has been fixed. Accidentally pushed to `main`, but it's fixed. Releasing soon.
