### ISSUE TITLE
Add the ability to style an index field cell

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#787]
### Feature

It would be useful to be able to style the cell of an Index cell.
What comes to mind is adding a `style` field option or `class`. Ideally, you'd be able to add TailwindCSS classes on the fly but Tailwind is compiled when shipped and some un-used classes from the packed gem will be unavailable to the user. That can be fixed by introducing your own asset pipeline so the new classes are available to the user.

## To do:

- [ ] add `style` option to the field options
- [ ] add `classes` option to the field options
- [ ] figure out how to separate them for `Index`, `Show`, `Edit` views.

### Screenshots

Support to align these to the right.
<img width="282" alt="CleanShot 2022-04-05 at 10 21 28@2x" src="https://user-images.githubusercontent.com/1334409/161710851-86f953b3-9dc5-4331-93ec-683d463eedfe.png">

**Comment by rassom** [comment]
Note that CSP (Content Security Policy) does not permit inline CSS styles, so use CSS class(es) would be preferable.

**Comment by adrianthedev** [comment]
How did you try to add those inline CSS styles? I'm curious.

**Comment by rassom** [comment]
I didn't try. I just know that CSS inline style would break many peoples Content Security Policy (https://content-security-policy.com/) and as such wouldn't work.

**Comment by adrianthedev** [comment]
Oh. Got it. Good to know.

Avo is built with tailwind css but the styles are pre-compiled (to strip away the unused classes) when packaged. You'd need to run your own tailwindcss CLI or something similar for the newly added classes.

**Comment by adrianthedev** [comment]
Anytime @rassom

**Comment by adrianthedev** [comment]
It will be released in a few days. Monday the latest.
