### ISSUE TITLE
Seeing  Missing target element "panel" for "toggle-panel" controller  

### ISSUE THREAD

**Issue by rickychilcott** [avo-hq/avo#793]
### Context
I'm seeing the following in my js logs when navigating to various resources:

![Screen Shot 2022-04-06 at 9 34 30 PM](https://user-images.githubusercontent.com/445759/162102572-c1020f9c-31f5-4295-8965-65be86d059ef.png)

### System configuration
**Avo version**:
2.1.1

**Rails version**:
6.1.x

**Ruby version**:
3.0.3

**Comment by rickychilcott** [comment]
I'm not sure it's right, but `app/components/avo/filters_component.html.erb` seems to have an extra closing div, at least that's what I think it's showing in my editor. Maybe that's the source?

**Comment by adrianthedev** [comment]
The filters partial extra div came from a misalignment.

It was from the profile sign-out link in the sidebar footer. You must not have your [`current_user_resource_name`](https://docs.avohq.io/2.0/authentication.html#customize-the-sign-out-link) option. So the link is hidden with that controller target too.

Pushed a fix to hide the whole controller div.

Thanks for bringing it up!
