### ISSUE TITLE
LICENSE.md still mentions that the community version of Avo may be used for noncommercial purposes for free

### ISSUE THREAD

**Issue by fcbr** [avo-hq/avo#794]
### Context

Hi the LICENSE.md file still mentions that the community version of Avo may be used for noncommercial purposes, but recently you have [announced](https://avohq.io/blog/community-license-free-for-commercial-projects) that this is no longer the case.

Could you kindly update the file as well to clear any confusion?  Thank you!

**Comment by adrianthedev** [comment]
You're right. Fixing it today.

**Comment by adrianthedev** [comment]
Hey @fcbr, [the license](https://github.com/avo-hq/avo/blob/main/LICENSE.md) got updated to include commercial purposes with the Community license.

Thanks for bringing it up!
