### ISSUE TITLE
Save button doesn't submit on safari

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#799]
### Describe the bug

In safari, after changing a resource and clicking save, the button changes to the loading state but then nothing happens - no network request is sent, and the button just stays in the loading state forever. I can see this on my own site as well as on the avo demo site.

### Steps to Reproduce

Using Safari (I'm on 15.4)

1. Go to (https://avodemo.herokuapp.com/avo/resources/courses/28)
2. Click on Edit
3. Change the name to whatever you like
4. Click Save

### Expected behavior
The browser should redirect back to the show page, with the updated name

### Actual behavior
The loading state on the button appears but never goes away again.

### System configuration
**Avo version**:

2.1.1

**Rails version**:

7.0.2.3

**Ruby version**:

3.1.1

### Screenshots

![Screenshot 2022-04-09 at 09 16 20](https://user-images.githubusercontent.com/111963/162563119-a0643454-14e1-460d-945e-d11880f38dd5.jpg)

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

This makes avo unusable for people using safari.

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

I have a limited set of users, so I can ask them to use chrome, but it's not ideal.

**Comment by adrianthedev** [comment]
Yeah. I see it too. So interesting that nobody reported it. Maybe not many people use Avo & Safari?

I'm AFK right now but will pick this up to fix it ASAP.

Thanks!
