### ISSUE TITLE
Specifying `current_user_method` when not using Devise causes things to blow up.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#807]
### Describe the bug

When attempting to specify a `current_user_method` in the Avo configuration, I'm unable to get things working regardless of where I define the method.  I'm not using Devise, and it appears to have some code loading involvement.

(Why am I attempting to use this without Devise -- or even the actual concept of a "user" in my app?  I'm trying to exert control over what operations are present in the UI and the only apparent way to do that is via Pundit.  It's a very awkward kludge, but a necessary one to ensure I don't accidentally hork my data.)

### Steps to Reproduce

In my Avo config, I have:

```ruby
config.current_user_method = :dummy
```

I've tried adding a method named `dummy` into `ApplicationController`, `ApplicationHelper`, and the various Avo controllers from my app (e.g. `Avo::TransformersItemsController`).  If added to the latter, the method _is_ picked up in _some_ situations -- but not all.  Specifically, when rendering a `has_many` association in the `show` view of another entity, I get:

```
NoMethodError (undefined method `dummy' for #<Avo::HomeController:0x0000000002d780>)
```

I tried monkey-patching `Avo::HomeController`, and `Avo::ApplicationController` at various points, but any attempt I make to do so winds up resulting in errors about the `set_resource_name` method not existing:

```
undefined method `set_resource_name' for #<Avo::TransformersToylinesController:0x00000000025918>
```

Am I not putting my `dummy` method in the right place?

### Expected behavior

Ideally, I should be able to define my method in a well-known place, like my app's ApplicationController and have it be recognized in all Avo controllers.

### System configuration
**Avo version**: 2.1.1 (gem), and commit e9210d74f761be23c4b532b80e8604ea221f12de.

**Rails version**: 7.0.2.3

**Ruby version**: 3.0.3

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by MrJoy** [comment]
To add more detail:

My approach to monkey-patching the method into place was to add this code:

```ruby
module Avo
  class ApplicationController < ::ActionController::Base
    def dummy
      "dummy_user_from_avo_application_controller"
    end
  end
end
```

I've tried adding it in `app/controllers/avo` within my app, and I've tried putting it in an initializer.  Both seem to produce the same result.

**Comment by MrJoy** [comment]
Err, sorry.  I misremembered.  If I put it in an initializer, then it gets loaded too early, and everything explodes even trying to start the app (`uninitialized constant Avo::ActionsHelper (NameError)`).

**Comment by MrJoy** [comment]
I just tried adding (in `app/controllers/avo`) monkey-patches for `Avo::AssociationsController`, `Avo::HomeController`, and `Avo::ResourcesController`.  This caused the errors to go away and removed the need to define `dummy` on every resource's controller.  But it broke association handling such that on my show-toyline view, instead of seeing associated _items_, I saw... a list of all toylines.  At this point, I'm kind of out of ideas on how to actually achieve what I need to achieve. :-/

**Comment by adrianthedev** [comment]
Got it. My assumption was that the "`dummy`" method could have been placed in your `ApplicationHelper`, but that's not correct.

I'll work on this today to see how it can be fixed.

**Comment by adrianthedev** [comment]
@MrJoy What are you returning from that dummy method?

**Comment by MrJoy** [comment]
To date, I've been returning a string.  As you might have guessed from above, I had each version of the method returning  a different string to help me diagnose what was going on.  My Pundit policies don't care about the user object at all and just discard whatever they're passed.

**Comment by adrianthedev** [comment]
Can you use an empty block for that?

```ruby
  config.current_user_method do

  end
```

**Comment by adrianthedev** [comment]
Ok. Let me know how that works. Closing for now. Feel free to open if it pops up again.
