### ISSUE TITLE
Includes are not utilized with actions (other than `index`)

### ISSUE THREAD

**Issue by rickychilcott** [avo-hq/avo#816]
### Describe the bug
My expectation is that within a Avo::Rescoure setting `self.includes` would be used in all locations where a resource is being queried. However, it's only utilized for the `index` action.

This isn't a problem in most cases, but if you utilize [strict loading](https://guides.rubyonrails.org/configuring.html#config-active-record-action-on-strict-loading-violation), especially when choosing to raise an exception, then Avo is unuseable.

I see that there is `resolve_find_scope` and `resolve_query_scope` which could be set, per resource, but I'm thinking that this should be the default

I'm happy to provide some tests to build this functionality, but I'm not sure the ideal interaction between the two methods above with what I'm asking for.

### System configuration
**Avo version**: 2.1.1

**Rails version**: 6.1.x and 7.x

**Ruby version**: 3.0.3

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] Low urgency

**Comment by adrianthedev** [comment]
Hey @rickychilcott,

I don't know a lot of details about strict loading. 
Can you provide a bit more context around this? 
Where is this an issue? Can you share some code?

Thanks!

**Comment by rickychilcott** [comment]
Here is how strict loading works:

```ruby
class User
  self.strict_loading_by_default = true
  
  has_many :memberships
  has_many :organizations, through: :memberships
end

User.find(1).memberships # will raise ActiveRecord::StrictLoadingViolationError
User.includes(:memberships).find(1).memberships  # won't raise

User.includes(memberships).find(1).organizations  # will raise ActiveRecord::StrictLoadingViolationError
User.includes(memberships: :organizations).find(1).organizations  # won't raise
```

When viewing a resource index, everything works fine when we have the following config:
```ruby
class UserResource < Avo::BaseResource
  self.includes = [{memberships: :organizations}]
end
```

But when you hit the `edit` or `show` actions it will raise `ActiveRecord::StrictLoadingViolationError` because the `includes` are not being used in the finders.

**Comment by adrianthedev** [comment]
Ok. Got it. I see the issue now. 

Let me see what I can do to fix this.

**Comment by adrianthedev** [comment]
@rickychilcott can you remove `strict_loading_by_default` from your app? 

We're a little backed up with a few other chores and need to make headway with the other features.

**Comment by rickychilcott** [comment]
I have. I'm doing it on a model-by-model basis, so I'm just deactivating it temporarily for now, but I'm seeing strict loading as a best practice for greenfield apps to limit N+1s, so you're bound to see this come up again.

I'm fine for now, but just wanted to highlight. Let me know if I can help directly or indirectly.

Ricky

Ricky Chilcott (he/him)

Partner

844-677-7526 x 701

***@***.***

www.missionmet.com ( http://www.missionmet.com/ )

------------------------------------------------

P.S. *Mission Met's first book, a nonprofit guide to resolving common strategic planning barriers, is here!* Learn more and purchase your copy of Mission Met: Proven Strategic Planning Guidance to Help You Build a Financially Secure and Impactful Nonprofit ( https://www.missionmet.com/mission-met-proven-strategic-planning-guidance-to-help-you-build-a-financially-secure-and-impactful-nonprofit ).

**Comment by adrianthedev** [comment]
Thanks for understanding. I'll keep this in mind going forward.

**Comment by dhnaranjo** [comment]
Short term workaround:

```
# app/overrides/avo/application_controller_override.rb

module Avo
  class ApplicationController
    before_action -> { ActiveRecord.action_on_strict_loading_violation = :log }
  end
end
```

This requires that you're set up for [reopening classes Zeitwerk-style](https://guides.rubyonrails.org/engines.html#overriding-models-and-controllers).
