### ISSUE TITLE
Unclarity of the new LICENSE.md

### ISSUE THREAD

**Issue by ArisBee** [avo-hq/avo#824]
I see that following https://github.com/avo-hq/avo/issues/794, the community edition License was updated to allow the use in commercial projects, however the following statement is not really clear:

> 4. **Not for reuse.** The Software and the proprietary code therein, not limited to but including  designs, components, classes, and patterns, may not be reused in other projects without the express written consent of Avo HQ.

Wouldn't that also limit the use of Avo as a library without the explicit written consent from Avo HQ?

**Comment by adrianthedev** [comment]
This refers to using parts of Avo in other projects. I [updated](https://github.com/avo-hq/avo/commit/64a718a59f110053dc5f4617b7f1affc75580ad8) the license.

The license states how one can use the `Commercial` and `Pro` licenses.

Let me know if I can be of help 🤙
