### ISSUE TITLE
Do not set I18n.default_locale in set_locale before_action in Avo::AplicationController

### ISSUE THREAD

**Issue by brunoprietog** [avo-hq/avo#828]
### Describe the bug

I am trying to set a locale for Avo but nothing works. My default locale in Rails is :es, and this causes Avo to not find translations.

### Steps to Reproduce

1. Set the language to :es globally with I18n.default_locale = :es.
2. Set the locale in the Avo configuration to "en".
3. Log in to the Avo panel. You will see missing translations.

### Expected behavior

The locale for Avo should be application independent and Avo should not change default_locale, only I18n.locale, so that it changes the locale only for that particular request and not for subsequent ones.

### Actual behavior

If I enter /avo?locale=en, this causes my entire application to change its default locale to en for all subsequent requests. This should not happen.

### System configuration
**Avo version**: v2.2.1

**Rails version**: v7.0.2.3

**Ruby version**: v3.1.1

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
I agree that `?locale=en` was a bad naming choice. A much better `param` would be `?set_locale=en`. It does make sense to change the locale on the current request only when doing `?locale=en`.  I'll make a PR with those changes. Thanks!

That locale is set throughout all the app in order for others to be able to change [multi-language records](https://docs.avohq.io/2.0/recipes/multilingual-content.html).

**Comment by brunoprietog** [comment]
Great.

Anyway, is there any way to set locale=en only for Avo without changing the default_locale for the whole application?

Since in my application I have default_locale=es, Avo doesn't find the translations for es.something. I would like Avo to stay in English without altering the default_locale of my application? Is that possible?

Thanks!

**Comment by brunoprietog** [comment]
@adrianthedev Hi, sorry to bother you again. Do you think you can see this? Since the default_locale of my application is "es" and avo always uses the default_locale, there are several translations that it doesn't find.
Thanks!

**Comment by adrianthedev** [comment]
Ok. I'll see what I can do.

Do you speak Spanish? Could you by any chance translate Avo to Spanish? I'd love to add `es` to the list of languages. [This](https://github.com/avo-hq/avo/blob/main/lib/generators/avo/templates/locales/avo.en.yml) is the language file for english.

**Comment by brunoprietog** [comment]
Yes, of course. At the weekend I will make a pr with the translations.

**Comment by adrianthedev** [comment]
That would be perfect! Thank you for contributing to the project ❤️

**Comment by adrianthedev** [comment]
Hey @brunoprietog 
I merged https://github.com/avo-hq/avo/pull/1003 which adds the `force_locale` param. This will enable to change the locale only for the current request.

The guide has been updated too: https://docs.avohq.io/2.0/recipes/multilingual-content.html

Try it out with [rubygems.org/gems/avo/versions/2.9.1.pre4](https://rubygems.org/gems/avo/versions/2.9.1.pre4)
