### ISSUE TITLE
Missing pro feature flag for Dashboards feature in docs

### ISSUE THREAD

**Issue by hassyyy** [avo-hq/avo#830]
It would be great if the docs mention that [Dashboards](https://docs.avohq.io/2.0/dashboards.html#generate-a-dashboard) is a pro feature just like [Tools](https://docs.avohq.io/2.0/custom-tools.html#generate-tools)

**Comment by adrianthedev** [comment]
Hey @hassyyy. I was updating the docs last night and noticed that same thing. I just haven't pushed the changes yet.
Apologies for that and thanks for the heads-up!

![CleanShot 2022-04-14 at 10 25 56](https://user-images.githubusercontent.com/1334409/163335309-61d2e8c1-68c1-4c5f-b940-d8e701dec7ca.png)

**Comment by hassyyy** [comment]
Thanks for the quick fix @adrianthedev. Cheers!
