### ISSUE TITLE
Default filters are cleared on apply

### ISSUE THREAD

**Issue by hassyyy** [avo-hq/avo#841]
### Steps to Reproduce
Steps to reproduce the behaviour:
1. Add 2 or more filters with default values to a resource
2. Go to index page of the resource
3. Change the value of any of the filter

### Expected behavior
Other filters should not be cleared

### Actual behavior
Other filters are cleared

### System configuration
**Avo version**: 2.2.1

**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1

### Screen recording
https://user-images.githubusercontent.com/23002310/163369618-9e81b8bf-0f19-4767-b7e2-e043964e852d.mov

### Additional context
It makes the filtering difficult as the user has to select the values for all the filter which are cleard
#### Impact & Urgency
High

**Comment by hassyyy** [comment]
@adrianthedev I'm still able to reproduce this issue with v2.3.0 😕

**Comment by adrianthedev** [comment]
Hmm, I might have fixed it just for one filter type. Sorry. I'll make another PR.

**Comment by adrianthedev** [comment]
Hey @hassyyy 
Can you try out [this prerelease](https://rubygems.org/gems/avo/versions/2.3.1.pre.1) and let me know if that fixed your issue? Made a few refactors to it.

Add `gem 'avo', '2.3.1.pre.1` in your `Gemfile`.

**Comment by adrianthedev** [comment]
Perfect! Thanks for testing it out. Please use that version until we release 2.4.

🤙
