### ISSUE TITLE
Add support for belongs_to :though

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#843]
### Feature

The `bloengs_to` `:through` association might not be working properly.

**Comment by lorint** [comment]
ActiveRecord does not support `belongs_to :___ through: :___`.  Only `has_many` and `has_one` can have `:through`.

**Comment by adrianthedev** [comment]
Yeah, my bad there. I meant to say `has_one`, and I think it's supported 🙂 
I'll check Avo and remove this if so.

**Comment by adrianthedev** [comment]
Thank you for the message

**Comment by adrianthedev** [comment]
The `:through` associations are supported. Closing for now
