### ISSUE TITLE
generate avo:install gives an arror

### ISSUE THREAD

**Issue by qubitam** [avo-hq/avo#848]
### generate avo:install gives an arror
When I try to add avo to my existing project or a new project, and try to run the generate command I get an error everytime.

### Steps to Reproduce
1. rails generate avo:install 
2. See error

### Actual behavior
`/Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load': cannot load such file -- /Users/qubitam/Workspace/CleverUP/unipharm/config/initializers/avo.rb (LoadError)
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/reloader.rb:6:in `block in reload!'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/reloader.rb:6:in `each'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/reloader.rb:6:in `reload!'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/reloader.rb:16:in `block in updater'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/reloader.rb:2:in `execute'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/engine.rb:46:in `block (2 levels) in <class:Engine>'
	from <internal:kernel>:90:in `tap'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/avo-2.2.1/lib/avo/engine.rb:45:in `block in <class:Engine>'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
	from /Users/qubitam/Workspace/CleverUP/unipharm/config/environment.rb:5:in `<main>'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/qubitam/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'`

### System configuration
**Avo version**: 2.2.1

**Rails version**: 7.0.2.3

**Ruby version**: 3.0.2

<img width="1306" alt="Screen Shot 2022-04-17 at 10 46 07 AM" src="https://user-images.githubusercontent.com/22918060/163709201-e75642c4-95ea-4c08-9bdf-2384054547ec.png">

**Comment by adrianthedev** [comment]
Ok. I think I see the issue.
I'm AFK right now but let try a fix in a few minutes

**Comment by qubitam** [comment]
Sure Adrian, take your time I will be waiting

**Comment by adrianthedev** [comment]
@qubitam releasing [`2.2.2`](https://rubygems.org/gems/avo/versions/2.2.1) in a sec. That should fix it.
