### ISSUE TITLE
Likely logic error in `Avo::Services::AuthorizationService#authorize_action`

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#851]
### Describe the bug

Just eyeballing the code in the screenshot below it looks like line 74 can never result in `true` being returned, and a `nil` action would actually result in a `NoMethodError` on line 72.

Did you maybe mean to put `return true if action.nil?` above `action = "#{action}?" unless action.end_with? '?'` ?

### System configuration
**Avo version**: d1b9a7efbe8a4063b60d948161eadc22ce082e43

**Rails version**: N/A

**Ruby version**: N/A

### Screenshots

<img width="911" alt="image" src="https://user-images.githubusercontent.com/113625/163732172-96f261af-9431-4e80-9a5b-3dd2165355f6.png">

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
It needs a bit more than just that. You can tell Avo to raise an error if the policy is missing.

Thanks for bringing it up.
