### ISSUE TITLE
Avo requires ActionMailer for seemingly no reason

### ISSUE THREAD

**Issue by aldent95** [avo-hq/avo#860]
### Context
I'm currently trying to do a memory optimization pass on one of my websites, including getting rid of ActionMailer.
After getting rid of ActionMailer I found that Avo for some reason requires ActionMailer in app/mailers/avo/application_mailer.rb

Is there any specific reason for this? I didn't think Avo sent emails, and it looks like it's just using the default mailer setup in that file.
If it's not being used can it please be removed.

### System configuration
**Avo version**: 2.2.1

**Rails version**: 7.0.2.3

**Ruby version**: 3.0.4

**Comment by adrianthedev** [comment]
Hey Alex.
Where did you find that Avo requires ActionMailer? We don't send any mails in Avo.

**Comment by aldent95** [comment]
@adrianthedev 
https://github.com/avo-hq/avo/blob/main/app/mailers/avo/application_mailer.rb

**Comment by adrianthedev** [comment]
Oh I see. Thanks!
I took some time off with the family for Easter. I'll be back next week to handle this and cut a release. 

Thanks for getting back to us with this.

**Comment by aldent95** [comment]
Sweet, sounds good
