### ISSUE TITLE
Able to create a record without required fields

### ISSUE THREAD

**Issue by hassyyy** [avo-hq/avo#865]
### Describe the bug
I'm able to create/edit a record in resource without specifying the required fiekds

### Steps to Reproduce
1. Go to a resource with required fields
2. Click on create button
3. Click on save

### Expected behavior
Record should not be created/updated. Error message must be displayed

### Actual behavior
Record is created/updated

### System configuration
**Avo version**: 2.3.1.pre.1

**Rails version**: 3.1.1

**Ruby version**: 7.0.2.3

### Screen recording
https://user-images.githubusercontent.com/23002310/165072740-96cee783-f346-41ac-ae22-19c30320e2c7.mov

#### Impact & Urgency
High

**Comment by adrianthedev** [comment]
Hey @hassyyy,

It's mentioned in the [docs](https://docs.avohq.io/2.0/field-options.html#required) (below the code sample) that the required option is there only to show the asterisk and does not provide the validation logic.

**Comment by hassyyy** [comment]
Oops! Missed it
Thanks a lot 🙏
