### ISSUE TITLE
HABTM field display in Create and Edit

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#870]
### Feature
I found out we only can attach and detach models with HABTM relationships in show view. I think it will be interesting, more intuitive  and helpful to have that partial in create and edit views too.

### Current workarounds
Maybe some tricky JS

**Comment by adrianthedev** [comment]
It's going to be more difficult to support that in the create view as there is no record yet created and the attach/detach mechanism needs one. 

We're open to PRs if you want to champion this feature. Support for the `Edit` screen shouldn't be that difficult to implement.
