### ISSUE TITLE
Cancel button in edit view always redirect to resource show view

### ISSUE THREAD

**Issue by Paul-Bob** [avo-hq/avo#887]
### Describe the bug
Cancel button in edit view always redirect to resource show view

### Steps to Reproduce
1. Go to https://avodemo.herokuapp.com/avo/resources/courses
2. Click on 'edit' on some random course
3. Click on 'cancel'
4. Redirected to show page instead to the original path

### Expected behavior
Cancel should redirect to last visited page before edit view

### Actual behavior
Cancel should redirect to resource show view

### System configuration
Irrelevant 

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ x] low urgency

**Comment by adrianthedev** [comment]
Closing this for now
