### ISSUE TITLE
Standalone actions not showing in index view 

### ISSUE THREAD

**Issue by npickelny** [avo-hq/avo#894]
### Context
Can't find a way to show the standalone action in the index view
https://docs.avohq.io/2.0/actions.html#standalone-actions

Im generating the action with the gem generator making sure that the standalone flag is true (literally copying the [
 standalone actions doc](https://docs.avohq.io/2.0/actions.html#standalone-actions) )

Cant find a way to add it to the index view even following the [docs](https://docs.avohq.io/2.0/actions.html#hide-actions-on-specific-screens)
`self.visible = -> (resource:, view:) { view == :index }`

Index view
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/13019291/168092483-c55b2dda-597c-47e8-88a7-17c62e0c0b91.png">

Show view
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/13019291/168091745-d6f1087b-c7ae-4f55-8124-814375a0568c.png">

-------

Am i doing something wrong? 
Or am I misinterpreting the docs?

Thanks in advance

### System configuration
**Avo version**: 2.5.1
**Rails version**: 6.1
**Ruby version**: 2.7.2

**License type**: PRO

**Comment by adrianthedev** [comment]
Hey. Did you add it to the resource?

https://docs.avohq.io/2.0/actions.html#registering-actions

**Comment by adrianthedev** [comment]
That's weird. It should work. I am checking it out on [avodemo](https://avodemo.herokuapp.com/avo/resources/fish/10) as we speak.

Can you try and output the view to see what we get in the console? 

```ruby
self.visible = -> (resource:, view:) { puts view.inspect; view == :index }
```

Also, can you try and restart the rails server? Maybe there's something iffy there (although it should work without a restart).

**Comment by npickelny** [comment]
Sure, i added `  self.visible = -> (resource:, view:) { puts '***** AVO ****'; puts view.inspect; view == :index }`  and this is the output

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/13019291/168098994-f4a07086-3a4d-47e9-a55a-1feda1d647b0.png">

**Comment by adrianthedev** [comment]
Can you jump on a quick call with me to troubleshoot it together?

https://whereby.com/adrianthedev

**Comment by adrianthedev** [comment]
Otherwise, it should work. On index should be visible and on show hidden

**Comment by npickelny** [comment]
Solved the issue, Thanks to adrian!!
The issue was that i have Pundit implemented in my project, and i didn't have the `act_on?` policy method defined.

https://docs.avohq.io/2.0/authorization.html#policies

**Comment by adrianthedev** [comment]
Thank you for taking the time to troubleshoot it with me. I figured out that the action should not have been visible on the `Show` view either. 
Gonna fix the bug in https://github.com/avo-hq/avo/issues/895.
