### ISSUE TITLE
Hiding resources from sidebar (based on user's role)

### ISSUE THREAD

**Issue by barmic12** [avo-hq/avo#901]
### Context
Based on the documentation regarding to authorization ([here](https://docs.avohq.io/1.0/authorization.html#policies)) I've created a Pundit policy and defined the` index?` method. Unfortunately, the resource still shows up (according to the policy, it shouldn't), but you can't actually enter it (redirection). How can I hide a resource (based on the user's role).

I've also read FAQ about authorization ([link](https://docs.avohq.io/1.0/faq.html#the-authorization-features-are-not-working))

### System configuration
**Avo version**:
2.5.1
**Rails version**:
7.0.2.4
**Ruby version**:
3.0.0
**License type** (Community or Pro):

Pro (trial)

**Comment by barmic12** [comment]
Ok, I've found the issue. It was caused by defining menu in `avo.rb` file:

```
  config.main_menu = lambda {
    section "Zasoby", icon: "resources" do
      #resource :organizations
      resource :organizations
      resource :admins
      resource :users
    end
  }
```

When the menu is defined, authorization rules don't apply.

**Comment by adrianthedev** [comment]
Got it!

I haven't mentioned anything in the docs about this kind of thing. I'll add that now.

I should probably surface a way to re-use the authorization rules in the menu builder as well.
