### ISSUE TITLE
Add possibility to use external_image and link_to_resource for the same field

### ISSUE THREAD

**Issue by teenu4** [avo-hq/avo#920]
### Feature
Currently, if I add `as: :external_image, link_to_resource: true` to one field, only `as: :external_image` will work.

### Screenshots

<img width="616" alt="Screen Shot 2022-05-24 at 2 45 05 PM" src="https://user-images.githubusercontent.com/16734597/170027553-57197c3d-a860-4947-959c-f14cd6144c00.png">
<img width="1083" alt="Screen Shot 2022-05-24 at 2 45 16 PM" src="https://user-images.githubusercontent.com/16734597/170027588-de33ae29-2562-4fb8-9ca1-5976dffeb355.png">

**Comment by adrianthedev** [comment]
That's a good suggestion and shouldn't be very complicated to do. We're working on something at the moment so we don't have the bandwidth right now, but if you want to try and contribute a PR, we're more then happy to help you navigate the codebase

After the refactor, it should look something like [this field](https://github.com/avo-hq/avo/blob/main/app/components/avo/fields/common/gravatar_viewer_component.html.erb#L12).
