### ISSUE TITLE
Override the maxTags option on the TagsFieldController

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#922]
### Feature
Right now the tags fields controller hard-codes the maximum number of tags at 10 (see [here](https://github.com/avo-hq/avo/blob/345ff4389a1fa58fdc786046c621316ba2eeb134/app/javascript/js/controllers/fields/tags_field_controller.js#L43). I need to add more than that. I would love if when I define the tags field in the avo resource (ruby) model I could override this number.

### Current workarounds
Not that I can see.

### Additional context
When I try to add more than 10 tags, the 11th tag appears in red and then disappears. Looking at the html it looks like tagify tries to show an error by adding a HTML element with the text "number of tags exceeded" (although this isn't visible in avo).

**Comment by adrianthedev** [comment]
I see now that this is actually a bug. I thought it was just a display issue.

This PR https://github.com/avo-hq/avo/pull/927 should remove the arbitrary limit.
