### ISSUE TITLE
Field visibility on specific type of users

### ISSUE THREAD

**Issue by Gpapidas** [avo-hq/avo#924]
Hello, I have been using Avo for about 6 months now and I have encountered the following issue when using the set_context method to pass current_user. When I first run the server and the current_user is empty, nothing gets passed on the context, however, when I log in, the dependent field on the current_user described in a emnima_resource.rb file is never shown, even if current_user is not empty. 

### Steps to Reproduce
1. Go to avo.rb file and set context,   
```
## == Set the context ==
  config.set_context do
    # Return a context object that gets evaluated in Avo::ApplicationController
    {
      current_user: current_user
    }
  end
```
2. Create a resource (i.e. emnima_resource.rb file) where you have a field dependent on the current_user type:

```
if !context.nil? && (context[:current_user].superadmin? || context[:current_user].admin?)
    field :published, as: :boolean, readonly: true, name: 'Published'
end
```

3. Restart your server
4. Check the resource

### Expected behavior
To see the published field if I am logged in as an admin or superadmin

### Actual behavior
The actual behavior is a little tricky. If you restart the server, log as admin, and check the resource you will not see the field. If however, you modify and save the emnima_resource.rb file in any way, and reload the page you will then see the field. It's like as if the emnima_resource.rb file is being read only once, and since at the server start the context is nil, the published field is never shown. With the exception of the modification after the server is up.

### System configuration
**Avo version**: 2.7

**Rails version**: 7.0.2.4

**Ruby version**: 3.0.4

**License type** (Community or Pro): Community

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey @Gpapidas. 
That's not how we imagined one would conditionally hide a field. Why don't you try the visibility option?

https://docs.avohq.io/2.0/field-options.html#field-visibility

The reason why that's not working is that the fields are loaded onto the model at boot time and there's no request then. The visibility option kicks in at request time. So you'll have the context populated with the current user. 

There's also this helper available for more complex configurations. 

https://docs.avohq.io/2.0/recipes/manage-information-heavy-resources.html

**Comment by Gpapidas** [comment]
Hey Adrian,
Field visibility options seems to be working great, I must have missed it in the docs,
thanks for the help

**Comment by adrianthedev** [comment]
I added an explanation [here](https://docs.avohq.io/2.0/field-options.html#using-if-for-field-visibility).
