### ISSUE TITLE
Associations aren't showing at all?

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#925]
### Describe the bug
I've been trying to get a has-and-belongs-to-many field working in my own app but nothing appears. But looking at the demo app it seems that none of the associations are appearing there at all. For example, in the demo app, if you look at the code for the [user resource](https://github.com/avo-hq/avodemo/blob/e7e481d7eb392a9e9462a40a1ed66bf60b54abe9/app/avo/resources/user_resource.rb) there should be several associations, including post, projects, teams, comments. But when I look at the [demo app on heroku](https://avodemo.herokuapp.com/avo/resources/users/avo-cado-de4e8d28-0802-4ecd-8add-4cd490887cab/edit), none of them appear. Here's a screenshot to show what I see:

![Screenshot 2022-05-27 at 16-52-59 Avo Cado — Avodemo7](https://user-images.githubusercontent.com/111963/170734996-75bdd9e4-71a8-47fc-bf31-aca18e56a162.png)

### Steps to Reproduce
1. Add a resource with an association field (eg. has and belongs to many)
2. View that resource in avo
3. Look for the association field

### Expected behavior
There should be a field that allows you to select the association.

### Actual behavior
There is no error, but the field does not appear

### System configuration
**Avo version**: 2.7

**Rails version**: 7.0

**Ruby version**: 3.1

**License type** (Community or Pro): Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [x] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Hey Iain, that's a feature, not a bug. The association screens are hidden by default on edit views. To show them on the edit view, add 'show_on: :edit' to them. This way you will force showing them on edit.

**Comment by iainbeeston** [comment]
Aha! Thanks for explaining that, I can deliver that feature now!

There are [examples in the documentation](https://docs.avohq.io/2.0/associations.html) that show associations being edited but it doesn't mention anywhere that you must add `show_on: :edit` to the field (I think it would be helpful to add that if you can). I'll close this issue

**Comment by adrianthedev** [comment]
Totally agree! On it!
