### ISSUE TITLE
Use of `bg-white` on logo image causes bleed.

### ISSUE THREAD

**Issue by MrJoy** [avo-hq/avo#929]
### Describe the bug

As you can see, the logo image is bleeding over.  The image itself fits solidly in the specified area (it's 900x878, but gets scaled by the browser to 49.2x48), it's the padding that's causing the bleed.  Removing the `bg-white` class from the `a` tag fixes the issue.

### Steps to Reproduce

N/A

### Expected behavior

Logo shouldn't bleed over.

### Actual behavior

Logo bleeds over.

### System configuration
**Avo version**: 2.7.0

**Rails version**: 7.0.3

**Ruby version**: 3.0.4

**License type** (Community or Pro): Community

### Screenshots

<img width="133" alt="image" src="https://user-images.githubusercontent.com/113625/171465338-047cf3fc-326a-49de-aae3-4c082c224e56.png">

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Hey @MrJoy I think you can fix that from your side. Edit the `logo.html.erb` partial you ejected and remove the `bg-white` class.

I pushed some changes for the next release to have that class removed and make it nicer on mobile too.

I'm closing this for now, but please re-open it if that didn't fix it for you.

**Comment by MrJoy** [comment]
Ah!  I had forgotten that I had ejected it.  Thanks!
