### ISSUE TITLE
translation_key on field being ignored

### ISSUE THREAD

**Issue by koppen** [avo-hq/avo#932]
We've been trying to translate the field names in our application, however following the instructions at https://docs.avohq.io/2.0/localization.html#localizing-fields doesn't seem to work.

### Steps to Reproduce

We have a `CustomerResource` with the following field:

```ruby
field :number, :as => :text, :required => true, :sortable => true, :translation_key => "customer.number"
```

And `config/locales/da.yml` with:

```yml
da:
  customer:
    number: "Kundenummer"
```

Translating directly via `I18n` works:

```ruby
I18n.translate("customer.number")
#=> "Kundenummer"
```

### Actual behavior

The field name is still shown as "Number" in Avo:

![CleanShot 2022-06-02 at 13 58 56](https://user-images.githubusercontent.com/6480/171624444-f47d58bc-c6a5-4011-94b7-941370711982.png)

### Expected behavior

The field name is shown as "Kundenummer" in Avo.

### System configuration
**Avo version**: v2.7.0

**Rails version**: 7.0.3

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**License type**: Pro

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by koppen** [comment]
Uh, well done, and dammit, my beatiful bug report was all for naught! 😆 Looking forward to the next release then.

**Comment by adrianthedev** [comment]
No worries. We love these reports. Please, keep them coming!

![](https://media.giphy.com/media/X0dtyf35H9SSLhiaJ3/giphy.gif)
