### ISSUE TITLE
Right align headers to same value as index_text_align

### ISSUE THREAD

**Issue by rassom** [avo-hq/avo#934]
### Expected behavior
Headers should be right aligned the same way as table contents

### Actual behavior
Headers are currently unaffected by the index_text_align specification

### System configuration
**Avo version**: 2.7.0

**Rails version**: 7.0.3

**License type** (Community or Pro): Pro

### Screenshots
![2022-06-02 at 15 36](https://user-images.githubusercontent.com/594378/171641993-ab74a308-6d81-48cd-adb2-de7f200f0f65.jpg)

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by rassom** [comment]
Thank you 🙏

**Comment by adrianthedev** [comment]
No problem man! Glad to help.
