### ISSUE TITLE
Trix editor doesn't show list types in editor

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#947]
### Describe the bug

When I use the trix editor, the editor shows the formatting I have selected except for lists. Lists just look like normal text for me. Looking at the HTML produced, they do have the correct HTML but they are not formatted.

### Steps to Reproduce

1. Find a resource that has a trix field2. 
2. Write text
3. Select that text
4. Press either the ordered list or unordered list buttons

### Expected behavior
The text should appear as the first item of a list, in the editor

### Actual behavior
The formatting of the text does not change.

### System configuration
**Avo version**: 2.7.0

**Rails version**: 7.0.3

**Ruby version**: 3.1.1

**License type** (Community or Pro): Pro

### Screenshots

I've recorded a video, here:

https://user-images.githubusercontent.com/111963/172576903-eff8eacd-8f49-4fb6-8743-2e154332362c.mov

### Additional context

I haven't overridden any css or themes for avo.

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Got it. I'll have a look and see where the issues is. 
Thanks for the video!
