### ISSUE TITLE
Url for resource uses model class name not resource name

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#950]
### Describe the bug
If you create a resource and define `model_class` to be something different to the resource name, then when you navigate to that resource in avo the path will be something like `/resources/original-class-name` rather than `/resources/resource-name`, which can be confusing

### Steps to Reproduce
1. Create a dog and a cat active record model in your rails project
2. Generate an avo resource named 'Dog'
3. In the dog resource class, set `self.model_class = ::Cat`
4. Start avo and navigate to `Cat` in the sidebar

### Expected behavior
The path for the cat admin page is `/resources/cats`

### Actual behavior
The path for the cat admin page is `/resources/dogs`

### System configuration
**Avo version**: 2.7.0

**Rails version**: 7.0.3

**Ruby version**: 3.1.1

**License type** (Community or Pro): Pro

### Additional context
In my own project, I'm using acts as taggable on to manage tags. I have a tag resource for editing these tags, but the class name for a tag is `ActsAsTaggableOn::Tag`. In avo the resource is referred to as the tags resource everywhere but the url is `/resources/acts_as_taggable_on_tags`

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Yes. I have [ran into](https://github.com/avo-hq/avo/discussions/846) that before and had one more customer complain about that.

All you laid out here makes total sense. The routes should respect the resources and not their model.
I'll make sure to prioritize it in the near future. I'd love to have this fixed sooner rather than later.
