### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#959]
### Describe the bug
When I installed avo on my project, it added an i18n translations file (`avo.en.yml`) that allows me to change the wording of certain things in avo. However, it doesn't seem to be used and no matter what I do the default translations are used.

### Steps to Reproduce
1. Change the `avo.resource_destroyed` translation in `avo.en.yml` to "hello world"
2. Open a rails console, run `I18n.locale` and confirm that it's `en`3. 
4. In the rails console, check `I18n.t('avo.resource_destroyed')`

### Expected behavior
It should be `'hello world'`

### Actual behavior
It is `'Resource destroyed'`

### System configuration
**Avo version**: 2.7.0 (also tried in 2.8.0)

**Rails version**: 7.0.3

**Ruby version**: 3.1.1

**License type** (Community or Pro): Pro

### Additional context
I've checked other translations (eg. from devise) and they work fine. You can also reproduce in app by making the same translation change and then deleting a resource (it will show "Resource destroyed" instead of "hello world")

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Got it. I found the bug.

We're adding Avo's locales directory and somehow that gets the most importance on runtime.
It will be fixed in the next release.

Thank you for sending this in!
