### ISSUE TITLE
Add the ability to skip the Show view for a resource

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#968]
### Feature

Some users don't need the `Show` screen for resources and only need the `Edit` one. It would be nice to be able to completely remove it.

#### Some things that came out from our brainstorming:

 - [ ] ensure all current controller paths (after create/update)
 - [ ] ensure all current resource paths lead to resource edit path
 - [ ] ensure all fields that support "link_to_resource" do the same
 - [ ] ensure actions redirects to edit
 - [ ] remove show link from resource controls
 - [ ] make it testable
 - [ ] add the redirect from routes

**Comment by hassyyy** [comment]
Would be great if we can have the ability to hide the show button in list view. 
Justification: It is not needed when `link_to_resource` is set

**Comment by adrianthedev** [comment]
Some things that came out from our brainstorming:

# Skip show view

 - [ ] ensure all current controller paths (after create/update)
 - [ ] ensure all current resource paths lead to resource edit path
 - [ ] ensure all fields that support "link_to_resource" do the same
 - [ ] ensure actions redirects to edit
 - [ ] remove show link from resource controls
 - [ ] make it testable
 - [ ] add the redirect from routes

**Comment by Paul-Bob** [comment]
@adrianthedev i suggest to no do the last step (add redirect from routes) yet. We expect all system to work fine without the forced redirect and if we add that redirect we kinda lost track if something is not working as expected
