### ISSUE TITLE
Automatically determine required fields from validations

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#972]
### Feature
Right now, to mark a field as required you have to explicitly add the `required: true` to the field declaration in the resource class. Simple form does this automatically by looking at the validations on the model (see the code [here](https://github.com/heartcombo/simple_form/blob/86429bceb950096df3c29616f31bd5a5ce706c06/lib/simple_form/helpers/required.rb)). It would be great if avo could do this too (if `required:` is not set in the resource)

### Current workarounds
The only way to do this right now is to manually keep the validations in the model and resource definition in sync, but it is a lot of work and I'm not sure that anyone could do that reliably

### Additional context
Here is the code that simple form uses:

* https://github.com/heartcombo/simple_form/blob/86429bceb950096df3c29616f31bd5a5ce706c06/lib/simple_form/helpers/required.rb
* https://github.com/heartcombo/simple_form/blob/86429bceb950096df3c29616f31bd5a5ce706c06/lib/simple_form/helpers/validators.rb

**Comment by adrianthedev** [comment]
Great idea. I'll have a look over that snippet and add it to the roadmap.

**Comment by rickychilcott** [comment]
I was pointed to this issue on the discord server. I think it'd be fantastic for `required` to be inferred based on the model/validations, but I think the `required` field should also continue to be overridable such that we can force it to be required (or not) in Avo.

**Comment by rickychilcott** [comment]
Also, this feels like a nice first issue so @iainbeeston, if you want to take a stab, that'd be super cool!

https://github.com/avo-hq/avo/pull/955 might help get you started in seeing where to hook in and make this happen.

**Comment by imamrb** [comment]
Hi
Can I work on this if no one is working on it yet?

**Comment by rickychilcott** [comment]
That sounds lovely!

Ricky Chilcott (he/him)

Partner

844-677-7526 x 701

***@***.***

www.missionmet.com ( http://www.missionmet.com/ )

------------------------------------------------

P.S. *Mission Met's first book, a nonprofit guide to resolving common strategic planning barriers, is here!* Learn more and purchase your copy of Mission Met: Proven Strategic Planning Guidance to Help You Build a Financially Secure and Impactful Nonprofit ( https://www.missionmet.com/mission-met-proven-strategic-planning-guidance-to-help-you-build-a-financially-secure-and-impactful-nonprofit ).
