### ISSUE TITLE
Date format is not working in mobile browsers

### ISSUE THREAD

**Issue by hassyyy** [avo-hq/avo#975]
### Describe the bug
Display format for date fields doesn't work in mobile browsers. In web, it works fine

### Steps to Reproduce
1. Configure a resource with date field
2. Specify a custom format for date
3. Go to new/edit page in web & mobile browsers

### Expected behavior
Web & Mobile: Date should be displayed in the specified format

### Actual behavior
Web: Date is displayed in the specified format
Mobile: Date **is not** displayed in the specified format

### System configuration
**Avo version**: 2.4.1

**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1

**License type** (Community or Pro): Community

**Resource Field Config**: `field :date, as: :date, required: true, picker_format: 'd F, Y', format: '%d %B, %Y', default: Date.today`
### Screenshots
**Web**
<img width="1126" alt="Date Field - Web" src="https://user-images.githubusercontent.com/23002310/174466859-895595cb-a2f2-4283-b678-e09ed90b933e.png">
**Mobile**
<img width="404" alt="Date Field - Mobile" src="https://user-images.githubusercontent.com/23002310/174466857-973f03c8-b0e6-41c6-bfe1-82acae449c76.png">

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] Low urgency

**Comment by adrianthedev** [comment]
Hey @hassyyy,

It seems that flatpickr (the date picker we use) [gets disabled](https://flatpickr.js.org/mobile-support/) on mobile by default because the device date picker is a better experience altogether. Also, I don't see a way of formatting the date in the picker. I'm open to suggestions though.

**Comment by hassyyy** [comment]
Uh-oh! That's unfortunate

Is there a way to pass the option `disableMobile` to the field? I would like to try out how would that behave

**Comment by adrianthedev** [comment]
Not right now, but we're open for PRs. We could use a hand to add this feature.

**Comment by hassyyy** [comment]
Sure, I will give a try 💪

**Comment by adrianthedev** [comment]
Lovely! Thank you! Let me know if you need any help navigating the codebase.

**Comment by hassyyy** [comment]
Sure, I will reach out to you if I am stuck somewhere

**Comment by adrianthedev** [comment]
How about giving it the same name as on flatpickr `disable_mobile: false` (defaults to true)? 

I launched Avo on [Product Hunt](https://www.producthunt.com/posts/avo-for-rails) (any feedback and comments help a lot BTW) and my efforts go there today. But I'm happy to help more hands-on from tomorrow 💪

**Comment by hassyyy** [comment]
Using "disable_mobile" as a field parameter may not be right as it denotes that the field will be disabled in mobile

**Comment by hassyyy** [comment]
Hey @adrianthedev 
Kindly let me know your thoughts ☝️

**Comment by hassyyy** [comment]
Hi @adrianthedev 
When can we expect this to be released?

**Comment by adrianthedev** [comment]
Hey @hassyyy. I usually release on Monday or Tuesday. I still have a few things to finish with Tabs so It will most probqbly be released tomorrow.
