### ISSUE TITLE
Cant see actions on edit

### ISSUE THREAD

**Issue by OlexandrStorchak** [avo-hq/avo#977]
Avo version: 2.8.0
Rails version: 7.0.3
Ruby version: 3.0.0
License type (Community or Pro): Community

Cant see actions on edit

<img width="1392" alt="Screenshot 2022-06-20 at 11 18 30" src="https://user-images.githubusercontent.com/22897472/174557398-10c573fb-b2bf-4de0-a3ff-cc9d36bde5be.png">

<img width="491" alt="Screenshot 2022-06-20 at 11 18 10" src="https://user-images.githubusercontent.com/22897472/174557142-80bb3bb5-eb4f-46a2-b972-83b8b4bd51ee.png">

**Comment by adrianthedev** [comment]
Is the action attached to that resource?

https://docs.avohq.io/2.0/actions.html#registering-actions

**Comment by OlexandrStorchak** [comment]
<img width="279" alt="Screenshot 2022-06-20 at 11 23 21" src="https://user-images.githubusercontent.com/22897472/174558171-4aec3011-d7b9-4346-8cd0-58f49c6a4daf.png">

Yes! I can see it only on :index and :show pages

<img width="1401" alt="Screenshot 2022-06-20 at 11 24 44" src="https://user-images.githubusercontent.com/22897472/174558471-a4c01b61-6699-46da-a823-4ca8ed008018.png">

**Comment by adrianthedev** [comment]
Ok. I managed to replicate it.

I'll add a fix and release it in the next release cycle (today or tomorrow).

Thank you for coming to us with this.

**Comment by OlexandrStorchak** [comment]
Thanks Adrian! Very fast and responsive!
