### ISSUE TITLE
Polymorphic belongs_to throws undefined method foreign_key in association index view

### ISSUE THREAD

**Issue by btonic** [avo-hq/avo#979]
### Describe the bug
A polymorphic belongs_to Resource C, defined in Resource A, is causing an index view failure in Resource B's show view, when Resource A has many Resource B's, and Resource B has many Resource A's (has_many through relationship). When visiting Resource B's show view, the association index view throws the following error.

```
Showing /usr/local/bundle/gems/avo-2.7.0/app/views/avo/base/index.html.erb where line #2 raised:

undefined method `foreign_key' for nil:NilClass
Extracted source (around line #175):

                  field.is_polymorphic? &&
                  reflection.respond_to?(:polymorphic?) &&
                  reflection.inverse_of.foreign_key == field.reflection.foreign_key
                is_valid = false
              end
            end
```

### Steps to Reproduce
1. View a record of Resource B

### Expected behavior
The association index view should be displayed within Resource B's show view, for all associated records.

### Actual behavior
An error occurs.

### System configuration
**Avo version**: 2.7.0

**Rails version**: 6.1.4

**Ruby version**: 3.0.2

**License type** (Community or Pro): Community

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by btonic** [comment]
It's notable, if I attempt to represent the same information about the polymorphic association through a computed field, it successfully displays (e.g. `model.resource_c.some_attribute`) across all views properly.

**Comment by adrianthedev** [comment]
Hey @btonic. Sorry, but I'm having a hard time keeping up with the associations.
Could you make a super short schema with the models please? Something like below👇

Thank you

```ruby
class ModelA
  belongs_to :what
end

class ModelB
  has_many :whats
end

class ModelC
  has_many :whats, poluymorphic: true
end
```

**Comment by gilangmlr** [comment]
Hey @adrianthedev , I encountered the same error when trying to show rolify resources. It failed to load Roles on the User details.

```ruby

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

class Forum < ApplicationRecord
  resourcify
end


```

Here is the full rails project, https://github.com/gilangmlr/avo-rolify

Thanks for the awesome product!

**Comment by adrianthedev** [comment]
Hey @gilangmlr. Can you please send over the resources you have set up for those models?

Thank you!

**Comment by gilangmlr** [comment]
These are the avo resources

```ruby
class UserResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  # self.search_query = ->(params:) do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id, link_to_resource: true
  field :email, as: :text
  field :roles, as: :has_and_belongs_to_many
end

class RoleResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  # self.search_query = ->(params:) do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id, link_to_resource: true
  field :name, as: :text
  field :users, as: :has_and_belongs_to_many
  field :resource, as: :belongs_to, polymorphic_as: :resource, types: [::Forum]
end

class ForumResource < Avo::BaseResource
  self.title = :name
  self.includes = []
  # self.search_query = ->(params:) do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id, link_to_resource: true
  field :name, as: :text
  field :description, as: :text
end

```

Rolify adds the association with their methods (`rolify`, `resourcify`)

**Comment by adrianthedev** [comment]
Ok. Got it. I'll have a look at it this week or next week. If you need it sooner and want to pick it up let me know.

**Comment by adrianthedev** [comment]
I had a look over this, @btonic please add the inverse association on the resource that's failing with the `as:` attribute. You haven't sent over any code samples, so I can't help you more than just that.

I think that should fix it on your end.

Please try out this pre-release version and let me know if this fixes it for you guys @btonic and @gilangmlr.

https://docs.avohq.io/2.0/faq.html#try-a-pre-release-version
https://rubygems.org/gems/avo/versions/2.10.3.pre.1
