### ISSUE TITLE
Keep scroll position or don't reload everything when interacting with an association on the resource show page

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#983]
### Describe the bug

When interacting with an association or something from the lowe part of a resource page, after the interaction, Avo reloads the page and goes up.

### Steps to Reproduce
1. Go to a user
2. scroll to the reviews page
3. attach a review

### Expected behavior

The page should remain scrolled there.

### Actual behavior

The page reloads and scrolls up

### Screenshots

![CleanShot 2022-06-22 at 13 46 14](https://user-images.githubusercontent.com/1334409/175011030-6fd6c9b4-be71-4af2-b521-c31618ea00fd.gif)

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by Aaryanpal** [comment]
hey @adrianthedev, can you Assign this one too..

**Comment by adrianthedev** [comment]
You are on fire @Aaryanpal. Yes!

**Comment by adrianthedev** [comment]
Amd thank you!

**Comment by adrianthedev** [comment]
This might be solved with Turbo 8's morphing feature
