### ISSUE TITLE
Paths for ActiveStorage attachments are being prefixed with avo.root_path

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#984]
### Describe the bug
When using `rails_blob_path` or trying to display an `ActiveStorage` attachment manually in a view, it fails with a 404. After careful inspection, it appears that the redirected URL for the attachment is being prefixed with whatever is being set as `config.root_path` in `avo.rb`.
When replacing `rails_blob_path` by `Rails.application.routes.url_helpers.rails_blob_path`, then the prefix disappears and it works properly.

### Steps to Reproduce
1. In any custom component/view, call an object's attachment and try to display it. For instance:
```ruby
<%= image_tag @model.avatar %>
```
2. It should not display the avatar
3. When inspecting the `src` attribute, it should be prefixed with `/avo/rails/active_storage/...`

### Expected behavior
It should display the image or make the link work

### Actual behavior
The path is generated with a prefix that breaks the link

### System configuration
**Avo version**: 2.9

**Rails version**: 6.1

**Ruby version**: 2.7.6

**License type** (Community or Pro): Pro

### Screenshots
When clicking on a link generated with `rails_blob_path`: (my root_path is set to `/admin`)
![Screenshot 2022-06-22 at 15 23 45](https://user-images.githubusercontent.com/38864576/175039896-5d770d97-112b-4088-abf8-78e75694cb63.png)

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by bear-in-mind** [comment]
Right now, I'm in a component, so it fails with `undefined local variable or method `main_app'`
But it might work in a regular view :)

![Screenshot 2022-06-22 at 15 28 00](https://user-images.githubusercontent.com/38864576/175040811-9b66474f-03da-413c-b4e8-98bec893793c.png)

**Comment by adrianthedev** [comment]
Yeah, I think turning a PDF file into a reviewable format requires a little bit of processing on your part.

That's weird it doesn't work. Try one more thing please :) Try and use the `attachment` on the `url_for`.

`<%= image_tag helpers.main_app.url_for(@field.value.attachment) %>`

**Comment by adrianthedev** [comment]
Active storage [might have something](https://api.rubyonrails.org/classes/ActiveStorage/Preview.html) to help you there.

Here's another quick snippet that might work. You'd need to cache it for best results.


```ruby 
pdf = MiniMagick::Image.open "doc.pdf"

MiniMagick::Tool::Convert.new do |convert|
  convert.background "white"
  convert.flatten
  convert.density 150
  convert.quality 100
  convert << pdf.pages.first.path
  convert << "png8:preview.png"
end
```

https://stackoverflow.com/questions/45937501/convert-a-pdf-to-png-using-mini-magick-in-ruby-on-rails

**Comment by bear-in-mind** [comment]
> Yeah, I think turning a PDF file into a reviewable format requires a little bit of processing on your part.
> 
> That's weird it doesn't work. Try one more thing please :) Try and use the `attachment` on the `url_for`.
> 
> `<%= image_tag helpers.main_app.url_for(@field.value.attachment) %>`

Generated link is OK, but it still doesn't work. I tried various things, but it wouldn't change. I'm wondering if there isn't a `context` issue here. I'll try your snippet. Thanks Adrian !

**Comment by bear-in-mind** [comment]
Might be worth adding this somewhere in the docs, maybe ?
Thank you so much for your help 🙏 💪
