### ISSUE TITLE
[Feature] Provide hooks in controller actions

### ISSUE THREAD

**Issue by bear-in-mind** [avo-hq/avo#986]
### Feature
Provide hooks on `create` or `update` after save to perform some actions. Here's what I'm trying to achieve:
```ruby
class Avo::EmailsController < Avo::ResourcesController
  def create
    super
    # This is not being called
    @model.send_as_reply
  end
end
```
Here's how it could work:
```ruby
class Avo::EmailsController < Avo::ResourcesController
  def create
    super do |resource|
      resource.send_as_reply
    end
  end
end
```

### Current workarounds
Right now, we can hook onto these actions through ActiveRecord callbacks, but it's not always convenient.

### Additional context
A simple and good implementation is the pattern used in the `devise` controllers, where the resource is being `yield` if a block is passed : https://github.com/heartcombo/devise/blob/f8d1ea90bc328012f178b8a6616a89b73f2546a4/app/controllers/devise/registrations_controller.rb#L20

**Comment by bear-in-mind** [comment]
It's probably 20 mn of work which I'd gladly take on this week if you find it interesting :)

**Comment by adrianthedev** [comment]
YES! I want that! That looks amazing!

I launched Avo on [Product Hunt](https://www.producthunt.com/posts/avo-for-rails) (any feedback and comments help a lot BTW) and my efforts go there today. But I'm happy to help more hands-on from tomorrow 💪

**Comment by bear-in-mind** [comment]
Upvoted ✅ Congrats on the launch !

**Comment by adrianthedev** [comment]
We're going to use [this](https://github.com/avo-hq/avo/pull/993#issuecomment-1208499226) approach.
