### ISSUE TITLE
Using custom `model_class` with classes using Rails 7 encryption fails

### ISSUE THREAD

**Issue by damianlegawiec** [avo-hq/avo#994]
### Describe the bug
When using custom `model_class` (as described here: https://docs.avohq.io/2.0/resources.html#custom-model-class) with a class with encrypted attributes, eg

```ruby
encrypts :name, deterministic: true, ignore_case: true
encrypts :email, deterministic: true, downcase: true
```

it fails on test/production environment (with class caching on):

as it tries to connect to the DB during class autoloading

### Expected behavior
What I would suggest is to have the `model_class` as a string and use `safe_constantize` when needed to access the class itself. 

### System configuration
**Avo version**: 2.9

**Rails version**: 7.0

**Ruby version**: 3.0

**License type** Community

**Comment by adrianthedev** [comment]
Hey @damianlegawiec. Thanks for getting back to me with this. 
I haven't used encrypted attributes with Avo, but that makes sense. 

I'm AFK now, but I'll push out a pre-release tomorrow with that fix applied so you can test it too.

**Comment by damianlegawiec** [comment]
@adrianthedev thanks for the quick reply. Take your time, no pressure!

**Comment by adrianthedev** [comment]
Hey @damianlegawiec I just published [`2.9.1.pre1`](https://rubygems.org/gems/avo/versions/2.9.1.pre1).


I wasn't able to replicate the bug on my end (the app booted ok), but there might be differences in configuration.

 Please try it out and let me know if that fixes the issue.

**Comment by damianlegawiec** [comment]
Thanks @adrianthedev , that indeed helped, I've found one more issue and created a PR with a fix - https://github.com/avo-hq/avo/pull/997

**Comment by adrianthedev** [comment]
Hey @damianlegawiec could you test [2.9.1.pre2](https://rubygems.org/gems/avo/versions/2.9.1.pre2) as well when you have the time. I did a tiny refactor and want to make sure it still supports your use case.

I'll merge that PR and come back to it before release if necessary.
